### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by Cazadorsniper** [Cazadorsniper/PO3#1]
- [x] Enchanter missing from JEI
- [ ] crash with sound mufflers: https://pastebin.com/jJWbsiaP
- [x] Xia fight phase 2 crashing: Reported to mod dev
- [ ] Crafting station 2 player issue which allows duplication
- [ ] Crash with Soot involved: https://gist.github.com/Pival81/bd1e24e6727ca9880aacecfa684a1dc2
- [x] Crash with blue slimes using oozing doll: https://pastebin.com/76CKUY0R
- [x] Drinking a bucket of milk duplicates the bucket
- [x] Silver ore chunk in a redstone furnace is turned into lead ingots
- [x] Staff of Gaea quest not working
- [x] Diamatine Crystals (and Emerald) vanish when pressure plate is in front of reconstructor 
- [ ] Can't order more than 4096 buckets of oil with Amadron Tablet
- [ ] Induction Smelter does not accept Fused Quartz JEI recipe
- [x] Project Crafting Table (Projectred) Crash on Crafting
- [x] PneumaticCraft pressure chamber destroys inputs when making multiple liquid antimatter buckets.
- [x] Diamond nugget recipe conflict
- [x] Wyvern to Gem fusion crafting not working (do /de_reload_custom_fusion if its not working)
- [ ] Cannot insert certain non-stackable items into a drawer by hopper (or other insertion methods)
- [x] Extra planets creeper bosses make screen go black
- [x] Crash when putting the Wireless Terminal and Crafting Terminal into the Crafting Terminal grid
- [ ] Game not responding after Save and Quit on Lan
- [x] Add all silicon to laser cutter
- [ ] Higher tier Flux Capacitors & Jetpacks not craftable with AE2 autocrafting
- [x] Add Ender and Stellar armor into armor Progression
- [x] Quantum Entangloporter quest not detecting
- [ ] Embers Rekindled particles from Overworld showing up in other dimensions

**Comment by Nectarino** [comment]
Sorry if this is the wrong way to do this. 
When there is a seed analyser nearby, pressing t to 'search nearby inventories' won't work at all.
Removing the seed analyser or unloading those chunks makes it work again.

**Comment by Cazadorsniper** [comment]
probably fixed the pneumaticcraft issue just replaced buckets with florbs

**Comment by Cazadorsniper** [comment]
Wireless Crafting Terminal crash is known afaik

**Comment by fightmesun** [comment]
I've got issues with the fused quartz in the induction smelter too

**Comment by lachlanapple** [comment]
PO3 takes 30 mins too load then stops responding
