### ISSUE TITLE
Cannot craft Gem Boots or Gem Chestplate

### ISSUE THREAD

**Issue by squillis** [Cazadorsniper/PO3#100]
**Pack Version:**
3.0.38
**Description:**
Cannot craft Gem Boots or Gem Chestplate.
**Steps to reproduce:**
Placing items in the Wyvren Infusion Crafting Injector and the main item in the Crafting Core does not allow craft.
**Crash log:**
No crashlog.

As you can see I crafted the Helm and Leggings, but the other two do not work.
(Required items are in the backround on the Injectors)
![2019-03-06_13 52 08](https://user-images.githubusercontent.com/14357840/53906087-0fcd0d00-4018-11e9-9d4f-161d4697cc62.png)
![2019-03-06_13 57 23](https://user-images.githubusercontent.com/14357840/53906089-1196d080-4018-11e9-8a9b-a8fdff628aa5.png)

**Comment by Zapstur** [comment]
Ok, this is really weird.  Sometimes the recipes work, other times they don't.  I got the Leggings recipe to work once, the Chestplate recipe has been consistent so far, the Helmet worked twice, and the boots have yet to work even once for me.  This is after 8 attempts each to create the recipes (in the exact same way, every time).

There's definitely a major issue here, and I have no clue what causes it.

**Comment by Zapstur** [comment]
> /de_reload_custom_fusion

And that has made the recipes somehow work consistently.  That command should be listed in the questbook somewhere.

**Comment by squillis** [comment]
/de_reload_custom_fusion seemed to work, thanks. Would have had no clue that was even a thing if not for you. lol Thanks.
