### ISSUE TITLE
Duplicate any item with Depths Ghoul in Mob Duplicator

### ISSUE THREAD

**Issue by Nonsense331** [Cazadorsniper/PO3#1000]
**Pack Version:** 3.2.55
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Depths Ghoul can pick up any item and is not blacklisted in the mob duplicator. I assume this was just an oversight as it trivializes a ton of stuff.

**Comment by Cazadorsniper** [comment]
ok
