### ISSUE TITLE
game not launching from the native launcher

### ISSUE THREAD

**Issue by thegamingmetagross** [Cazadorsniper/PO3#1001]
**3.2.51**
**kappa**
*Singleplayer**

**After leaving the game I am unable to load the pack, the pack gets to about half way loaded on the launcher (green preparing bar) then closes (not crashing), java se platform binary starts to run in the background but cannot be opened. I am able to open other packs just fine, I am using 14g of ram to the modpack. the main difference between this and #403 is that 1) the game does not give a crash report and 2) the game stoppes on the launcher instead of during mod loading. it is not a ram issue as I have been able to run the game with no lag on 14g.**

**N/A**

**N/A**

**Comment by Cazadorsniper** [comment]
I need the log to determine what is going on and I recommend you decrease the amount of allocated ram to around 6 or 8 and update the pack.

**Comment by thegamingmetagross** [comment]
I am very sorry about the delay in replying, I have been having internet problems
here is the latest.log file https://pastebin.com/NdaQ9hjZ
additionally here are my jmv argurments with the ram lowered to 8 gigs instead of my normal 14 which did not help. https://pastebin.com/EJq3J9Kz
if it would help I could make a short video showing the problem (basically it opening but if you think it would help I can make one)

**Comment by Cazadorsniper** [comment]
Is there more of the latest.log? Use https://gist.github.com/ for the log.

**Comment by thegamingmetagross** [comment]
went through and highlighted and copied the entire log

**Comment by Cazadorsniper** [comment]
Can you do the short video?

**Comment by thegamingmetagross** [comment]
it might take a bit due to slow internet

**Comment by thegamingmetagross** [comment]
https://youtu.be/YTUyuUS-2pE

**Comment by Cazadorsniper** [comment]
Try updating the pack.
Set the ram allocation in the twitchapp settings.
You can also try the repair profile button.

**Comment by Cazadorsniper** [comment]
Maybe try deleting the 1.12.2.jar and/or the forge version:
Demonic Gaming\Twitch\Minecraft\\Install\versions

**Comment by thegamingmetagross** [comment]
none of those worked. I ended up just saving my world and deleting and reinstalling the pack, thank you for your help
