### ISSUE TITLE
Project Ozone 3 A New Way Forward server connection problems

### ISSUE THREAD

**Issue by darkstar117** [Cazadorsniper/PO3#1002]
3.2.55

Multiplayer

I have made a server for me and my girlfriend to play on but she can't connect to it at all. We've tried different ips and I have tried different things in the server files but nothing is working please help I don't know what to do 

It just tell her she can't connect to the server

**Comment by Cazadorsniper** [comment]
Can you give me a log of when she tried to join it?

**Comment by darkstar117** [comment]
> Can you give me a log of when she tried to join it?


I can try but i don't thing it has a log for her it just says she cant connect to the server like the server is down but is not

**Comment by Cazadorsniper** [comment]
You sure she has the correct IP address and have clicked the refresh button?

**Comment by darkstar117** [comment]
> You sure she has the correct IP address and have clicked the refresh button?

yes and yes but i can see right now

**Comment by Cazadorsniper** [comment]
Does she have the same pack version as the server?
Also I needed a log of her trying to join the server (Minecraft logs everything that is happening).

**Comment by ExtinctInsanity** [comment]
Do you have it setup in your router's firewall to allow outside connections for your Minecraft server...
