### ISSUE TITLE
Magneticraft Heavy Steel plates can't be crafted

### ISSUE THREAD

**Issue by Oraxian** [Cazadorsniper/PO3#1004]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:  3.2.55
**Pack Mode: Kappa
**Singleplayer

The Magneticraft Heavy Steel plates (used in Tier 7 Heavy Duty plate recipe for Extra Planets) can't be crafted.  The recipe is for the Magneticraft Hydraulic press, and it will only take the Magneticraft steel ingot, which does not show up in JEI.  Other steel ingots do not work.

Tried unsuccessfully to work around with ore dictionary converters in-game.  Can't add the steel ingot in creative mode.  Only solution I had was to add the finished plates in creative mode.

**Comment by Cazadorsniper** [comment]
The recipe works fine for me.
