### ISSUE TITLE
Can't craft Wireless Universal Terminal

### ISSUE THREAD

**Issue by EternalClickbait** [Cazadorsniper/PO3#1006]
**Pack Info:**
v3.2.55 (forge-14.23.5.2847)
Normal Mode
Singleplayer

**Description:**
Even though the Universal Terminal (and the recipe) appears in JEI, it cannot be crafted (placing it in any crafting block gives no output):
[In inventory](https://user-images.githubusercontent.com/48875125/79286026-a8fc7180-7f02-11ea-9bad-0020a5225780.png)
[In Crafting Terminal](https://user-images.githubusercontent.com/48875125/79286063-c7fb0380-7f02-11ea-8a1b-fb47fe0aa185.png)

**Steps to reproduce:**

1. Craft Wireless Terminal (from AE2)
2. Attempt to combine with ME Terminal/ME Gas Terminal (as shown in JEI)
3. Expected result: Wireless Universal Terminal
    Actual Result: No output

Also tested using wireless crafting terminal instead of Wireless Terminal, with same result

**Crash log:**
N/A

**Comment by Cazadorsniper** [comment]
Don't try to craft it unless you want to crash the pack.

**Comment by EternalClickbait** [comment]
Is there a reason it's enabled and in the pack then?
