### ISSUE TITLE
Can't craft some tester materials

### ISSUE THREAD

**Issue by Naini0712** [Cazadorsniper/PO3#1007]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.55
**Pack Mode:**Kappa
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**
Can't craft Gottobemanian Metal(Ludicrite) and Wilxate Gear(Industrial Machine Chassis)
![2020-04-15_17 29 31](https://user-images.githubusercontent.com/55199184/79317935-4bd3e080-7f41-11ea-8008-f785f93cd912.png)
![2020-04-15_17 29 37](https://user-images.githubusercontent.com/55199184/79317939-4e363a80-7f41-11ea-9e3f-3a04a6d61e25.png)

**Steps to reproduce:**
Put requied materials in Quantum Compressor

**Comment by Cazadorsniper** [comment]
Break the compressor.

**Comment by Naini0712** [comment]
Thanks. Both of compressing succeeded.
