### ISSUE TITLE
1.12.2 catserver not generating netherex biomes

### ISSUE THREAD

**Issue by motofam93** [Cazadorsniper/PO3#1008]
3.2.55
Kappa
Multiplayer catserver

**Description:**

Multiplayer nether biomes not generating. Simply boot up server and go into nether

No crash when you go into nether. Just not generating biomes in the nether. Therfore players cant complete quests

**Comment by Cazadorsniper** [comment]
Do you have anything that could interfere with nether world gen?

**Comment by motofam93** [comment]
No, the nether mod dev team was helping me and have concluded that it is a catserver issue….others have had this issue as well I suppose. I boot up the pack with normal forge and no plugins and it works just fine. Then boot up with cat server and no plugins and it doesn’t work….

**Comment by Cazadorsniper** [comment]
Then there is nothing I can do.

**Comment by motofam93** [comment]
What do i run besides catserver? Nothing i have found can run plugins for a po3 server?!

**Comment by Cazadorsniper** [comment]
We don't really support plugins because mods and plugins don't mix well most of the time, but you can try sponge.

**Comment by motofam93** [comment]
I have tried spokge forge but they dont have a version for this forge version you have created this pack with... guess im out of luck tbh.
