### ISSUE TITLE
Optifine 1.12.2

### ISSUE THREAD

**Issue by Fabifoot** [Cazadorsniper/PO3#1009]
Bonjour,

Version : 3.2.55
Version de Minecraft : 1.12.2
(moddé) forge-14.23.5.2847

Aucun Optifine de toutes les versions 1.12.2 ne fonctionnent. Le Launcher ce bloque à (6/7 et 14).

Cordialement.

**Comment by Cazadorsniper** [comment]
I'm unsure which optifine works with PO3 if that is what you're asking.

**Comment by Fabifoot** [comment]
Hello, Thank you for the quick reply.

No, I tested all versions of optifine tuned to the modpack version (1.12.2) but the launcher stops at loading 6/7 (14/2xx).
I have all tried but the modpack must be blocked for x reason...

cordially.

**Comment by Fabifoot** [comment]
P.S : There is a strange thing. the up versions of optifine (13.2, 15.2) do not block the launcher but it stops once the menu is open.

**Comment by Cazadorsniper** [comment]
You're going to have to ask the Optifine developers for help on this issue.

**Comment by Fabifoot** [comment]
d'accord

**Comment by Cazadorsniper** [comment]
Disable or remove the Waiting Time mod.
