### ISSUE TITLE
Some recipes not craftable in multiplayer (kappa mode)

### ISSUE THREAD

**Issue by Lylithrea** [Cazadorsniper/PO3#1012]
Pack Version: 3.2.55

Pack mode: Kappa

Multiplayer (singleplayer)

Description:
When i try to craft certain recipes, i do not see the output. (So far i cant craft most smeltery blocks (tinkers construct) but could craft a drain. and coal block). But in singleplayer i can craft those blocks?

Step to repoduce: Auto fill craft coal block.

https://gyazo.com/644191c97861b22875cc4ae5e9bd9239

**Comment by Cazadorsniper** [comment]
Is this server and client on the same mode?

**Comment by Lylithrea** [comment]
they werent, but that didnt fix the problem sadly. I restarted the server again too
