### ISSUE TITLE
Barley Recipe Conflict

### ISSUE THREAD

**Issue by CrypticDivide** [Cazadorsniper/PO3#1015]
**Pack Version:** 3.2.55
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** There is a conflict for using Barley to craft Barley Flour and using Barley to craft Barley Seeds.

**Steps to reproduce:** Use the "Show Uses" function of JEI to see that the recipe for using Barley to make Barley Flour is the same as using Barley to make Barley Seeds. I have attached screenshots for each of these recipes.

![image](https://user-images.githubusercontent.com/17485942/79628779-5210bb00-8101-11ea-83bb-1113f9c0d77f.png)
![image](https://user-images.githubusercontent.com/17485942/79628783-5ccb5000-8101-11ea-8044-529e3c3cb480.png)

**Crash log (use pastebin or issue will be closed):** No crash log to upload.

**Comment by Cazadorsniper** [comment]
Use the market to get the seed.
