### ISSUE TITLE
Removed mod from Curseforge, update required!

### ISSUE THREAD

**Issue by NLBlacky** [Cazadorsniper/PO3#1016]
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

The mod plustic is no longer available on Curseforge due to breaking Curseforge's ToS. Since Project Ozone 3 is using this mod, Project Ozone 3 will no longer be downloadable till this mod has been removed from the modpack. I believe a few other mods below this developer were removed as well but I have no names.

**Comment by Cazadorsniper** [comment]
Tech has already told me that PO3 will still be downloadable though.

**Comment by NLBlacky** [comment]
I've noticed that as well but I cannot tell exactly for how long. When downloading from Twitch, the mods are grabbed from Curseforge. Since the page isn't available anymore, the download should become unavailable as well soon.

**Comment by Cazadorsniper** [comment]
PO3 will stay available.
