### ISSUE TITLE
Players can't join to the server because of "reading a NBT tag that was too big"

### ISSUE THREAD

**Issue by VincentChui2005** [Cazadorsniper/PO3#1017]
# Players can't join to the server because of "reading a NBT tag that was too big"
**Pack Version:** 
3.2.55
**Pack Mode:** 
Kappa
**Singleplayer, Multiplayer, or LAN?:** 
Multiplayer

**Description:** Recently I was playing with my friends in this modpack. For that, I started a server that runs on my computer (my client runs on the same computer as well). Everything was fine and was running smoothly before the problem suddenly popped up. Just before this issue occurred, I was about to play on the modpack so I booted up both my server and client as usual. However, I can't join in the server. The console yielded an exception and the client disconnected with the following message:
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big: tried to allocate: 16777227 bytes where max allowed: 16777216"
As neither the client nor the server crashed, there's no crash report. The 1st pastebin link was captured from the latest log about what happened after I tried to join the server. At the last of the log it showed there's 0 players online as I tried to type "list" in the console just to check if the server has crashed.

After all that and the story has not ended :D
I looked through the log and saw line 21 saying ingameinfoxml was making the error, so I cloned my whole server into another folder and tried to start the server and the client without the ingameinfoxml mod.
I successfully joined the server... for 10 seconds before the server just crashed.
I tried to start the server a few more times and join in. But all those tries came to a crash of the server (This time there are the crash reports! Although I found it useless. The second and third links are the reports. Other crash reports are having similar reports going on, so I took 2 different ones only). Coming to this point, I really got no idea on how to solve this, so I'm just gonna report this as a bug.

**Steps to reproduce:** Well, I don't really know how to reproduce, sry for that

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/CYdUhUVH
https://pastebin.com/x1zMVeu2
https://pastebin.com/cPagg04u

**Comment by Cazadorsniper** [comment]
in server.properties find max-tick-time then set it to -1.

**Comment by VincentChui2005** [comment]
The server just jammed. I can't type anything in the console. I can't join the server in my client. The server displayed nothing more

**Comment by Cazadorsniper** [comment]
Use World Edit or something to remove the /Dank/Null Dock from the world.

**Comment by VincentChui2005** [comment]
I've just found the single lonely /Dank/Null Dock in my friend's base and broke it. I can now freely play in the server! Thanks for that!
