### ISSUE TITLE
Can't craft Infinite Ember

### ISSUE THREAD

**Issue by DangerHSW** [Cazadorsniper/PO3#102]
**Pack Version:**.38

**Description:**I placed every item needed on the pedestals around the Combiner. The Core has power. The pedestals dont reach further then 3 Blocks. Tried Inscription tiles with "E.M.B.E.R" and with blank ones. I have 5 Infinity Ingots, 8 Dawnstone Plates, 3 Morganine and 2 Creative Essence and the ultimate ingot in on the core. Just like the JEI Recipe shows. I tried switching everything, placing them in order, etc.

Then I tried to make the Everlasting Mana Pool and that worked first try without having something in order. So I knew, the order was irrelevant and the power worked.

The core sees every pedestal but just says: "No recipe found"

**Steps to reproduce:** Try crafting the Infinite Ember with Combine Crafting

**Crash log:**no crash

**Comment by Cazadorsniper** [comment]
can you give me a picture of how you have it set up?

**Comment by DangerHSW** [comment]
I tried different orders, less pedestals etc.
![2019-03-09_20 16 49](https://user-images.githubusercontent.com/48067686/54076159-7700f080-42a8-11e9-8bc0-721fc1162b7d.png)
Only says no recipe (Worked with the Everlasting Manapool, with the same setuip)
![2019-03-09_20 17 00](https://user-images.githubusercontent.com/48067686/54076160-7700f080-42a8-11e9-95c6-b1843c2cc8ae.png)
Power is provided by the Quantum Entangloporter, has right configuration and worked with Manapool too.
![2019-03-09_20 17 28](https://user-images.githubusercontent.com/48067686/54076161-77998700-42a8-11e9-83d5-90fcd8ce9ef4.png)

**Comment by DangerHSW** [comment]
For reference:
![2019-03-09_20 34 14](https://user-images.githubusercontent.com/48067686/54076324-c34d3000-42aa-11e9-9355-91def4a16212.png)
Recipe worked instantly with the same setup.
![2019-03-09_20 34 16](https://user-images.githubusercontent.com/48067686/54076326-c516f380-42aa-11e9-9baf-984ec5c3a853.png)

**Comment by Cazadorsniper** [comment]
i want you to add 1 more morganine then try it.

**Comment by DangerHSW** [comment]
Yep that worked. I realized that its 4 Morganine, just very hard to notice in JEI. Thanks.
![2019-03-09_23 00 30](https://user-images.githubusercontent.com/48067686/54077892-3fea0980-42bf-11e9-94ea-b9fd4759f96b.png)
