### ISSUE TITLE
Modpack keeps crashing anytime I try to run it.

### ISSUE THREAD

**Issue by zanjackson** [Cazadorsniper/PO3#1020]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.55
**Pack Mode: Any
**Singleplayer, Multiplayer, or LAN?: Does not matter

**Description: Any time I try to load up the mod it starts out fine, but when I get to stage 6/7 it will always freeze at a specific spot and crash. It crashes at stage 6/7, Just enough items, recipe 85,216 everytime

**Steps to reproduce:**

**Crash log https://pastebin.com/uB7d51hN

**Comment by Cazadorsniper** [comment]
How much ram is allocated?

**Comment by zanjackson** [comment]
I am not sure how would i check that

**Comment by Cazadorsniper** [comment]
Pastebin the crash report and I can tell you.

**Comment by zanjackson** [comment]
I did it is in the original report I made, https://pastebin.com/uB7d51hN but here it

**Comment by Cazadorsniper** [comment]
Yup, needs more ram. Adjust ram settings in the twitchapp settings.

**Comment by zanjackson** [comment]
It works great now thank you.
