### ISSUE TITLE
Java crash

### ISSUE THREAD

**Issue by 314resqi** [Cazadorsniper/PO3#1022]
**Pack Version:** 3.2.55
**Pack Mode:** kappa
**Singleplayer, Multiplayer, or LAN?:** multiplayer

**Description:**
I opened chest and it crashed
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/CL1gEvFF

**Comment by Cazadorsniper** [comment]
Start the pack over.
