### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by Exys** [Cazadorsniper/PO3#1024]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.55**
**Pack Mode: NA**
**Singleplayer, Multiplayer, or LAN?: NA**

**Description: While installing through the Twitch Client for the newest version, 3.2.55, I get an error:

This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 226910**

**Steps to reproduce: Try to install fresh copy**

**Crash log (use pastebin or issue will be closed): NA**

**Comment by NotNyarlathotep** [comment]
https://github.com/Cazadorsniper/PO3/issues/727

Search function my friend.
