### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by Pauleen2020** [Cazadorsniper/PO3#1025]
**Pack Version: 3.2.55**
**Pack Mode: Normal**
**Singleplayer, Multiplayer, or LAN?: Running a server on my pc and joining via localhost:25565**

**Description:  once started after one time I quit the game and went to go back on it. it was running absolutely fine before but all of a sudden I can't play as once the server starts it lags, i'm able to join it for like 10 seconds and i get 1 fps at best. i have given it as much ram as i think it would want but i fear something in the world is breaking it. all i was doing was making a legacy reactor in the void dimension.**

**Steps to reproduce: Not sure tbh I was doing what i normally do i think, i went come come back on one day and it kept crashing like it was running out of ram or something.**

**Crash log (use pastebin or issue will be closed): This is the latest server crashlog - https://pastebin.com/CtgcAZeN **

**Comment by Cazadorsniper** [comment]
in server.properties find max-tick-time then set it to -1.

**Comment by Pauleen2020** [comment]
Thank, this allowed me to be able to lag myself towards the void dimension, as soon as I tp to the void dimension, my fps goes back to normal and the server ticks go back to normal. There must still be something in the original world that's making the server lag. As soon as I get to the overworld, my fps slowly deteriorates to an unplayable 1fps and server starts seriously lagging again. I don't even know what has caused it as I didn't do much in that world before these issues started. I stopped the reactor in the void dimension and emptied some stuff out of the me system to make sure that it's not full etc, Still hasn't fixed it. If you want I could try and record what I'm experiencing?

**Comment by Pauleen2020** [comment]
Wait what, I've just hit /kill @e to try and get rid of any entities which may be causing lag, I forgot it would kill me, so I died as well, but what was strange is when I respawned in the overworld/the place where it lagged before, it didn't lag. Somehow killing myself fixed the lag issue :/ I have no idea why, but it's now fixed >:( Sorry to bother you and I hope this may help others of this issue.

**Comment by Pauleen2020** [comment]
I have also noticed when I got my stuff back from the grave, I didn't get my wireless crafting terminal back :/ would that have caused the lag? I'll try make a new one and report back if the lag continues, if that would be of interest?

**Comment by Cazadorsniper** [comment]
Check your baubles for your terminal.

**Comment by Pauleen2020** [comment]
So it happened again, so i checked my baubles, just had my lava charm. whilst i was running at 1 fps again. i used /kill [playername] to kill just myself and it didn't fix the lag. so i did /kill @e and then all lag went away. so i don't know what is causing all this lag but somthing is. when i collected my stuff from the grave i did also have two lootbags out of nowhere so not sure if they are a part of it, i doubt it. But i'll try and see if i can work out what entity is causing the lag if it happens again.

**Comment by Cazadorsniper** [comment]
Maybe too many entities, check your mob farms and your auto sieve setup, also remove loot bag storage block if you have it.
