### ISSUE TITLE
Constant player effects

### ISSUE THREAD

**Issue by PaternoX** [Cazadorsniper/PO3#1026]
I've got a slight issue, in that i seem to be having a constant Jump Boost II, Speed II player effects, and my silk touch pick now auto-smelts everything. Effects remain even after drinking milk. I've removed my enori armour, incase that was causing it, i've used a shifting star to remove my attunement, incase that was causing it, but i still get the effects.

Any idea what may be causing this, and how to stop it? Or how i might be able to check to find out the cause?

Playing latest version ( 3.2.55) in single player
Mode : Kappa

**Comment by Cazadorsniper** [comment]
Try checking Lord Craft passive skills.

**Comment by PaternoX** [comment]
yup, that sorted it. Thank you very much sir ;)
