### ISSUE TITLE
Server crashes, "ticking entity"

### ISSUE THREAD

**Issue by Kingi-s** [Cazadorsniper/PO3#1027]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*3.2.55*
**Pack Mode:*Skylands*
**Singleplayer, Multiplayer, or LAN?:*Multiplayer, Its just a server hosted on a home server.*

**Description:*My server have now crashed because of both abyssalcraft AND embers rekindled.
When the server crashes because of that ticking entity, restarting the server doesnt help anything, i just have to go back to an backup, which ive set to be taken every 15minutes because of this god dam crashing. I cant really progress on the pack without cheating.*

**Steps to reproduce:*ember rekingled's "ember_packet" entity. And abyssalcraft's "lesserhoggoth" entity, crashes my server. I first got around the issue of abyssalcrafts lesserhoggoth crashing the server by cheating myself what i would have needed from the mod, And now i need to use embers rekindled and now it is crashing the server, i asked about this from abyssalcraft' developer and they said its because of zerocore.**

**Crash log (use pastebin or issue will be closed):* https://pastebin.com/wJAZKeGX *

**Comment by Kingi-s** [comment]
I didnt find a fix for the issue when searching for it.

**Comment by Cazadorsniper** [comment]
I have no idea either.
