### ISSUE TITLE
Launcher issues

### ISSUE THREAD

**Issue by eliteshadow0000** [Cazadorsniper/PO3#103]
**Pack Version:**
1.12.2
**Description:**
Whenever I press play on the modpack in the twitch app, the launcher loads a bit then it says "Unable to update the Minecraft Native Launcher". I do not know what the problem is, but if any of you guys know, please tell me.

Screenshot:
https://user-images.githubusercontent.com/48301032/53922260-96e2ab00-4041-11e9-985c-8627644494f6.png

**Comment by skychock** [comment]
Hi, first of all twitch launcher is actual crap. The only advice I can give you is to get MultiMC, since then I didnt have any problems. 

When I used the twitch app, I had so much problems with installing mods, and even going in the mod section (infinite loading)
