### ISSUE TITLE
Server Wont launch

### ISSUE THREAD

**Issue by MythicalMang0** [Cazadorsniper/PO3#1030]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
I downloaded the server files and accepted the eula but whenever i try to run the .bat file it comes up in cmd saying:

Invalid maximum heap size: -Xmx6G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

i have not changed anything in the .bat file either and have tried to re-download the server files aswell.
**Steps to reproduce:**
idk
**Crash log (use pastebin or issue will be closed):**
there isnt one?

**Comment by Cazadorsniper** [comment]
Try updating to a 64-bit Java.

**Comment by MythicalMang0** [comment]
that worked thanks, just beed to know how to change the world to Garden Of Glass

**Comment by Cazadorsniper** [comment]
Can read the overview of the pack for that.
