### ISSUE TITLE
Unable to attach Porcelain faucet to Porcelain smelter

### ISSUE THREAD

**Issue by leewickert** [Cazadorsniper/PO3#1034]
I have confirmed via Youtube that I am constructing the smelter correctly. I am able to add lava to the tank and even add ingots to the melter which breaks down the ingots. However, I am unable to add the faucet to the side which allows the melted metal to flow out.

Any help?

**Comment by Cazadorsniper** [comment]
Are you using the correct faucet?

**Comment by leewickert** [comment]
I am using the porcelain smelter from Tinkers; Complement, but the Porcelain faucet itself is from Ceramics. I looked up the description of Tinkers' Complement on Curse and the description said it had interactions with Ceramics.

I am needing the porcelain smelter to work so I can get scorched bricks! lol
Thanks for taking some time to help

**Comment by leewickert** [comment]
Alright alright post of shame. You have to shift+right click to place the faucet. closing thread. Thanks again lol
