### ISSUE TITLE
Agricraft Crop breeding not working

### ISSUE THREAD

**Issue by ArchaicBlock** [Cazadorsniper/PO3#1035]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.55
**Pack Mode:**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
When using sprinklers and tick acceleration, seeds are not producing any mutated offspring.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Trying to 10/10/10 the seeds?
