### ISSUE TITLE
Crash with Null Pointer Exception Creating a New Garden of Glass World

### ISSUE THREAD

**Issue by canpan14** [Cazadorsniper/PO3#1036]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.55**
**Pack Mode: Creative/Survival Garden of Glass**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: Creating a new world with the above settings crashes the game.**

**Steps to reproduce: See above**

**Crash log (use pastebin or issue will be closed): https://pastebin.com/QRkSDFNp**

**Comment by Cazadorsniper** [comment]
Reinstall PO3.

**Comment by canpan14** [comment]
Easy enough to do. Is there anything specific that caused this? Just want to prevent it from happening again.

**Comment by canpan14** [comment]
I used the 'repair' feature of the Twitch launcher which basically reinstalled the mod and I was able to create a world this time.
