### ISSUE TITLE
Missing items in JEI and unable to see a recipe for Magneticraft and Extra Utilities.

### ISSUE THREAD

**Issue by wildkurt** [Cazadorsniper/PO3#1039]
This all starts with the recipe for the Industrial Foregoing Plant Gatherer needing Heavy Tungsten Plates and the only recipe for making them is the Hydraulic Press multiblock from Magneticraft. I was able to make it, but I can't make any of the power generators because I can't bring up the blue print recipes for Small Steam Engine, Solar Tower, Solar Mirror, and Steam Turbine. Also, in creative-mode I can't see a tab for this mod, but I can search in the inventory window and find the blue prints.

Also, in Extra Utilities 2, I don't see the Transfer Pipe or Transfer Nodes in JEI, only in the creative inventory window. 

I tried uninstalling, downloading a fresh copy, and reinstalling. Nothing changed. 

This originally happened when I updated my client and server to 3.2.55 version of Project Ozone 3. I was going to make Transfer nodes and noticed the recipes were gone. I tried making the recipe and it doesn't work.

**Comment by ColdtQ** [comment]
did you figure this out?

**Comment by wildkurt** [comment]
I was able to make the wind generator and the solar panel from Magneticraft and that powered the press. Everything else that has been removed from the pack or is not available from what I understand was removed or disabled because they were crashing the game. Just to many conflicts with other mods, and I think the mod authors are no longer updating since 1.12.2 is getting to be an older version.
