### ISSUE TITLE
Open Bug minecraft not Load

### ISSUE THREAD

**Issue by pahholek** [Cazadorsniper/PO3#1040]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Not Defined, Start Error

**Description:** When I try to open Project Ozone 3. I need to click a button play in launcher. And when I click this button. Launcher disapper and minecraft didn't open. In Task Menager i have only this 2 java process [Imgur](https://imgur.com/a/cHlKwZ8). Forge mod loading window wasn't showed.

**Steps to reproduce:**
I don't knew what does it mean because my English is Very Bad
**Crash log (use pastebin or issue will be closed):**
I don't have crash report so I send Lasted Log
[Pastebin](https://pastebin.com/V4Kgnq9r)

**Comment by Cazadorsniper** [comment]
Try updating to 64-bit Java.

**Comment by Cazadorsniper** [comment]
Also did you try to add any mods.
