### ISSUE TITLE
(Not completely an issue but a thing of curiosity) 

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1042]
Version: 3.2.55

Status: Unmodified beyond the base modpack

Question: I didn't know where I would ask this, and I've seen no video about this. 
Is there a way to use a machine to stop mob spawning, like a mega torch in other packs?

Working with Ember's has become annoying as I've made my setup around my bore and Slimes spawn rapidly. 

(Also side question,  if anyone knows before I have time to test it myself, does the farming station work on Agricraft plants might be a bit OP so I'd assume no and I'd need to use a cloche, but it's weird, just thought I'd ask, but my main issue is the Slime problem)

**Comment by Cazadorsniper** [comment]
For you first  question as far as i know, no there isn't anything that can block spawns but you could use interdiction torches to move mobs (and you maybe) away.

The second question, Farming station nor the cloche work with agricraft.

**Comment by loltatoez** [comment]
There also the Dark Utils `Anti Slime Block`, which can prevent slimes from spawning in a chunk (I believe it's a chunk, could be a radius? I don't know)
