### ISSUE TITLE
Twitch download doesn't work

### ISSUE THREAD

**Issue by younappayougetslappa** [Cazadorsniper/PO3#1044]
Whenever I try to download the mod pack, while downloading, one of the mods is "unable to install" and the download is cancelled. Each time I install, a different mod fails to install. It is very annoying and I have looked up fixes for it but there are none.

**Comment by Cazadorsniper** [comment]
That is all on Twitchapps side, will have to ask for support from them.

**Comment by wolfielove1992** [comment]
actually it works fine must be your com I downloaded all three forms of project ozone and never once failed

**Comment by loltatoez** [comment]
I believe this happened to me on Skyfactory 4. I forget how I fixed it, but one thing that has happened before is that the mods actually duplicate in my mods folder. Check there for any duplicates.
