### ISSUE TITLE
Forge stuck at 7/7

### ISSUE THREAD

**Issue by oalkaya** [Cazadorsniper/PO3#1049]
I have been unable to launch the after reinstalling everything many times. I have been able to launch other modpacks such as Skyfactory 4, so I am assuming there something wrong with my system and this pack and possibly the java version Im running specifically.
Here are the logs. Any help is welcome, I have been trying to find a solution for days but have found nothing so far. Java becomes unresponsive at 7/7 every time.

[latest.log](https://github.com/Cazadorsniper/PO3/files/4560256/latest.log)

**Comment by Cazadorsniper** [comment]
how long does minecraft stay unresponsive and lower the maximum ram allocation from 12G to around 6-8G.

**Comment by Dragonminer99** [comment]
I have tried it with 6g, 7g, 8g and 10g ram. And I let it stay for at least 5-8 mins unresponsive. It still does not open. Should I wait even more?

**Comment by Cazadorsniper** [comment]
can you send me a more recent log?

**Comment by Dragonminer99** [comment]
Here is a more recent log:
[latest.log](https://github.com/Cazadorsniper/PO3/files/4563634/latest.log)

**Comment by Cazadorsniper** [comment]
Did you add any mods to the pack?

**Comment by oalkaya** [comment]
Nope, I have installed it from the Twitch launcher as is.

**Comment by Cazadorsniper** [comment]
You can try updating the java version, other than that I don't know the issue. You could just wait longer.

**Comment by oalkaya** [comment]
I have tried old and new java versions none of them seem to be working, I will leave my PC open for as long as I can and see if I can notice any changes.

**Comment by oalkaya** [comment]
I have lowered the ram to 6gigs and waited for 5-7 minutes without changing any other settings. This time I managed to get the game to crash and got a crash log. I have attached the crash log below.
[crash-2020-05-09_01.06.28-client.txt](https://github.com/Cazadorsniper/PO3/files/4601939/crash-2020-05-09_01.06.28-client.txt)

**Comment by oalkaya** [comment]
And I tried relaunching yet again, it worked? By changing nothing yet again? I am seriously confused.

**Comment by Cazadorsniper** [comment]
Check your anti virus software or windows firewall to see if they are blocking PO3 from starting.

**Comment by oalkaya** [comment]
I have firewall disabled and nor do I have any antivirus software installed.

**Comment by Cazadorsniper** [comment]
If you're using Windows 10 then you have windows defender.

**Comment by oalkaya** [comment]
I have disabled defender as well.
