### ISSUE TITLE
Server Crashes Constantly

### ISSUE THREAD

**Issue by HelpAccepted** [Cazadorsniper/PO3#105]
Im hosting a server and everything runs fine it starts up and runs for days without a problem but once someone joins the server they can play for about 5-10 min before the server crashes.

Heres my crash report.-----> https://pastebin.com/Gn9BMM2s

**Comment by Zapstur** [comment]
Seems like it is trying to do too many things at once, like spawning mobs due to a Bloodmoon (the timeframe matches if you get a Bloodmoon on the first night).  Try disabling the mod first, and see if that solves the issue.  If so, feel free to either keep it turned off, or modify the settings so that the number of mob spawns is closer to normal (I.E. Spawn rate, and he max number of spawns.

**Comment by HelpAccepted** [comment]
That didn't work the server still crashed only a minute or 2 after I logged on but it runs fine if no one logs on.

**Comment by HelpAccepted** [comment]
https://pastebin.com/irhpsgs4

This is a new crash report even after I removed Bloodmoons mod and created a new world

**Comment by nzminecraftDOTcom** [comment]
What hardware is the server running on, this pack requires a decent system in order to stay alive, 
CPU make/model
Allocated memory

**Comment by HelpAccepted** [comment]
Im running a 2.5 GHz Intel i5
with 16GB 1600 MHz DDR3 
I'm using 6GB of that Ram to run the server. 
It runs fine when I launch the server and for about 5 min once someone logs on and then it crashes.
I used the same computer and same Ram dedication to run a Project Ozone 2 on Kappa and had a whole bunch of stuff running and it help up fine with little to no lag.

**Comment by Cazadorsniper** [comment]
Please don't compare PO2 with PO3, the 2 are on different minecraft versions. 1.12.2 takes a lot more to run than 1.7.10.

In the server.properties turn "max-tick-time" to -1.

**Comment by nzminecraftDOTcom** [comment]
Have you had a look at how many chunks, entities etc are loaded in when the server is idle with nobody on and when someone joins?

**Comment by HelpAccepted** [comment]
Its a brand-new garden of glass world there is nothing around to load

**Comment by nzminecraftDOTcom** [comment]
Presuming you have used tickprofiler before (the pack comes with it from memory)

Do what @Cazadorsniper has suggested
Your server will probably take some time to respond when doing this but be patient
Run /profile e from console, enable the whitelist on the server so nobody can join
Wait for an output
Post it here

**Comment by HelpAccepted** [comment]
I got TPS: 6.456377.
Also before that I did everything that @Cazadorsniper said and now I can't connect to my server before the connection times out

**Comment by nzminecraftDOTcom** [comment]
Did you run /profile e like I suggested
You should get an output stating what is running, and the tick time each "item" is taking. Not just the TPS.

**Comment by HelpAccepted** [comment]
yeah those categories appear but there is nothing in them and they are all blank.

**Comment by nzminecraftDOTcom** [comment]
Perhaps try re-installing the server.
You aren't playing on the same machine as the server right?

**Comment by HelpAccepted** [comment]
Yeah Ive tried a fresh server and used the same properties and start up files but it kinda runs now it just doesn't have a spawn Island and I fall into the nether and then load that for 10 min. Ive got a separate computer to play on. I think its working right now so Im gonna close this thread and if I need more help I open a new one.
