### ISSUE TITLE
Recipes Missing

### ISSUE THREAD

**Issue by NEP1192** [Cazadorsniper/PO3#1050]
# Recipes not working.
Pack Version:Current (3.2.55)**
Pack Mode (Normal, Titan, Kappa): Titan
Singleplayer, Multiplayer, or LAN?:Multiplayer (But same issue resides in singleplayer)

Description: I am missing a majority of vanilla crafting recipes, whenever I look at how to make sticks for example it shows me all the different ways except two planks. Whenever I use two planks, it says I will craft 64 diamonds (I actually get sticks).

Steps to reproduce: All I have to do is launch the game.

Crash log (use pastebin or issue will be closed):
[Pastebin to Fatal + Error game output log](https://pastebin.com/5z0HtTX1)
[Pastebin to entire Log](https://pastebin.com/upMuysD1)

**Comment by Cazadorsniper** [comment]
Server and client must have the exact same packmode.

**Comment by NEP1192** [comment]
They do, both on titan.

**Comment by Cazadorsniper** [comment]
Are you sure?

**Comment by NEP1192** [comment]
![image](https://user-images.githubusercontent.com/43355484/80781941-7d4bcf00-8b31-11ea-80aa-31935461a04c.png)

**Comment by NEP1192** [comment]
I should probably also add, that of the other 4 people playing, I am the only one with the issue.

**Comment by Cazadorsniper** [comment]
Did you restart the server and/or client after changing modes?

**Comment by NEP1192** [comment]
I did. All the other recipes have changed (that should have changed, as far as I can tell), its just the vanilla ones that are missing or acting weirdly.

**Comment by Cazadorsniper** [comment]
Probably just a visual glitch.

**Comment by Cazadorsniper** [comment]
All I can say is restart the server and client.
