### ISSUE TITLE
Massive crater randomly generated in the twilight forest

### ISSUE THREAD

**Issue by IAmRedMyst** [Cazadorsniper/PO3#1051]
![unknown2](https://user-images.githubusercontent.com/50675064/80782855-53ef6b00-8b52-11ea-87a6-059fa1267921.png)
![unknown](https://user-images.githubusercontent.com/50675064/80782857-5651c500-8b52-11ea-9491-fd5d74b7aef3.png)

Me and 3 friends are currently playing Kappa mode and when one of them was in the Twilight Forest today, this massive crater randomly spawned and we are very confused. It has taken out even the bedrock. My friend is currently running the server through his personal PC and he had restarted the server earlier in the day.

**Comment by Cazadorsniper** [comment]
Someone was opening chance cubes.

**Comment by IAmRedMyst** [comment]
Only 2 of us have actually stepped foot in the twilight forest and neither of us did that with a chance cube. Afaik they don’t cause damage like that

**Comment by aldiron** [comment]
Hey Cazadorsniper,

I'm the friend running the server.

Do you know what the chance cube event would be called that would make a crater that big, just so I can look through the logs? I'm completely fine with the crater being there, and honestly doesn't bother me at all. I'm just curious to see when it happened to see if it lines up when I was actually having server issues or anything like that at all.

Thanks for making an insanely fun mod-pack with Kappa Mode. Absolutely loving it :)

**Comment by Cazadorsniper** [comment]
Look for matrix in the log

**Comment by aldiron** [comment]
We found the culprit haha.

Thanks again!
