### ISSUE TITLE
Crash loop - Tried smelting Ex Nihlo Ores in a Embers Melter. Server restart looping happening.

### ISSUE THREAD

**Issue by Queen-Gambit** [Cazadorsniper/PO3#1052]
Logs when trying to start the server:
https://pastebin.com/DejZAt7T

Crash logs:
https://pastebin.com/zxRaKCDs

Any idea how to fix? I tried loading backups that were made hours before my experiments and it still won't load. Another odd thing is that everytime I stop the server, the server after a few minutes start itself again. I even tried restarting the Server Instance too. I tried opening backup through MCedit but the mini map is correctly shown but the 3D world view is blank (maybe I'm not using MCedit correctly? ). My last resort (pending) is that I sent in a ticket to the server host, Creeperhost.com

Do we have a discord?

**Comment by Cazadorsniper** [comment]
Look in the forge.cfg in the config folder have set errored tile entities to disappear to true.
