### ISSUE TITLE
Quantum Entangloporter Power Storage

### ISSUE THREAD

**Issue by OrbitStudios** [Cazadorsniper/PO3#1053]
**Pack Version:**
3.2.55
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer - Server over LAN
**Description:**

Quantum Entangloporter resets it's internal storage after it reaches the maximum storage

**Steps to reproduce:**

Fill a quantum Entangloporter completely
Video of the issue: https://www.screencast.com/t/BvUh2krK

**Comment by Cazadorsniper** [comment]
I'm unsure of the cause of this.
