### ISSUE TITLE
Extra Utilities Trouble

### ISSUE THREAD

**Issue by Gehenna0** [Cazadorsniper/PO3#1054]
The Extra Utilities Mod is not working correctly. Items like transfer pipes & nodes are not present. I noticed the problem today, reinstalled the individual mod to no effect, eventually removing the mod pack completely to also no effect. I use twitch to for this modpack. When I click on the mods list inside Minecraft, Extra Utilities is present, but the disable and configure buttons are grayed out and have no interaction. Any assistance appreciated.

**Comment by Cazadorsniper** [comment]
Duplicate of #996
