### ISSUE TITLE
RFTools Builder not chunkloading properly 

### ISSUE THREAD

**Issue by VoidedOut** [Cazadorsniper/PO3#1057]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.55
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Trying to have an rftools builder be chunkloaded in landia to mine friscion ore. I have a filter and a max sized clearing quarry card, and it works when Im in landia. I have it chunkloaded with chicken chunks, not ftb utils. I have a fairly large area chunkloaded as well. It does not work when I am in any other dimension. I tested a couple times just goin back in forth, I gained friscion ore when in the dimension and I don't gain friscion when Im not in landia. I haven't tested this in any other dimension.
**Steps to reproduce:**
(above)
**Crash log (use pastebin or issue will be closed):**
N/A

**Comment by Cazadorsniper** [comment]
How large of an area is the chunkloader chunkloading?

**Comment by Cazadorsniper** [comment]
The chunkloader only needs to chunkload the builder itself afaik.

**Comment by VoidedOut** [comment]
At first I only had the chunk the buildet was in loaded, now I have the chunk loader set to 11. Neither worked

**Comment by VoidedOut** [comment]
Guessing with the newest update this doesn't matter much anymore. Will test eventually with other dimensions in newest version

**Comment by VoidedOut** [comment]
It just started working. Not sure if it was the item filter or not, I put endstone in there with the end draconium ore and it started working

**Comment by Cazadorsniper** [comment]
Probably was the item filter maybe.
