### ISSUE TITLE
Missing recipe from extra utils2

### ISSUE THREAD

**Issue by VoidedOut** [Cazadorsniper/PO3#1058]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.55
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
single
**Description:**
No recipe for item filters from extra utils in JEI. Not sure if they are still craftable because I do not know the recipe
**Steps to reproduce:**
Look up item filter from extra utils 2 and try to see the recipe

**Comment by Cazadorsniper** [comment]
They are disabled.

**Comment by Cazadorsniper** [comment]
Duplicate of #996
