### ISSUE TITLE
Thermal Expansion pulverizes 

### ISSUE THREAD

**Issue by Zeata** [Cazadorsniper/PO3#1059]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.56
**Pack Mode (Normal, Titan, Kappa):**
Titan
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
while trying to use the pulverizer the RF kept fully charging then fully emptying, stopping the process from working

this was not an issue on pack version 3.2.55

**Steps to reproduce:**
I am using Solar panels tier 6 from Solar flux
I am using a Thermal Expansion Energy Cell at max upgrade (Resonant)
I am using Mekanism Power cables at ultimate level
i am using pulverizer from thermal expansion at max upgrade (Resonant)
i was attempting to pulverize fluix crystals from AE2

**Crash log (use pastebin or issue will be closed):**
no crash log as server didnt crash

**Comment by Cazadorsniper** [comment]
Insert power more slowly and see if it still resets.

**Comment by Cazadorsniper** [comment]
This was very much an issue before version 3.3.56.
Also version 3.2.56 doesn't exist.

**Comment by bloodscon** [comment]
**I am using Mekanism Power cables at ultimate level**
try using ender io or thermals pipe meka as a mod is great but it's pipe compared to ender io and thermal for cross mod use can throw a few curve balls also meka energy pipe limit is for the pipe where as for ender io and thermal it's per connection
