### ISSUE TITLE
Loot Bag Storage Block Missing

### ISSUE THREAD

**Issue by pleggins** [Cazadorsniper/PO3#1060]
**Pack Version:**
3.3.56

**Pack Mode (Normal, Titan, Kappa):** Titan
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:** I am unable to craft the loot bag storage block or find it in JEI. I was able to see the block in JEI in version 3.2.55. I updated to the latest version and now the block is missing. I can see the bag opener and not the bag recycler, but I think that is disabled in the configs. I copied my world from 3.2.55 to 3.3.56.

I tried starting a new world in 3.3.56 and I am getting the same issue. I verified that the lootbag mod version is the same between packs, as well as the lootbag config files are the same. 

**Steps to reproduce:**
1. Launch Project Ozone 3 version version 3.2.55
2. Verify the loot bag storage block is present in the pack
3. Launch Project Ozone 3 version 3.3.56
4. The loot bag storage block is missing

**Crash log (use pastebin or issue will be closed):**
N/A (pack does not crash)

**Comment by Ralsch** [comment]
I can confirm that the block is also missing in Kappa mode.

**Comment by PiggyWhiskey** [comment]
https://github.com/Cazadorsniper/PO3/issues/958

**Comment by ilyahryapko** [comment]
Is it possible to reenable this for local use? Dont seem that commenting in config folder "removeShaped" works. There's no other good ways to store lootbags, conduits refuse to put lootbags into drawer controller or yabba controller

**Comment by Atzromix** [comment]
> Is it possible to reenable this for local use? Dont seem that commenting in config folder "removeShaped" works. There's no other good ways to store lootbags, conduits refuse to put lootbags into drawer controller or yabba controller

I just gave the Storagte to me in my Single player world ^^ Give name lootbags:loot_storage

**Comment by Cazadorsniper** [comment]
Good luck with the dupe bugs that can possibly lag your game to a halt.

**Comment by slimpie2003** [comment]
> Good luck with the dupe bugs that can possibly lag your game to a halt.

i know this is old but the mod "LootBag Patches" should fix this.
