### ISSUE TITLE
[3.3.56] Charcoal cannot be molten into Liquifacted Coal anymore

### ISSUE THREAD

**Issue by Frikkle** [Cazadorsniper/PO3#1061]
**Pack Version:** `3.3.56`
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
After upgrading from 3.2.55 to 3.3.56 the Tinkers' Construct smeltery does not seem to accept Charcoal anymore as input to create Liquifacted Coal. Is this intentional?

We have an automated setup producing Liquifacted Coal which stopped working after the upgrade. We broke it down and set it back up in order to check if it was some weird glitch, it wasn't. Additionally, the recipe is also gone in JEI.

**Steps to reproduce:**
1. Create a Tinkers' Construct smeltery.
2. Fuel it up with lava.
3. Insert Charcoal into the Controller.

Result: 
![image](https://user-images.githubusercontent.com/9324165/80910693-93c07900-8d31-11ea-831f-d56aa5a5719b.png)

**Crash log (use pastebin or issue will be closed):** Server nor client does crash.

**Comment by Cazadorsniper** [comment]
Then the recipe probably came from PlusTic as I have not disabled any recipe like that.
