### ISSUE TITLE
Agricraft and Ender IO integration issue

### ISSUE THREAD

**Issue by JosephStar318** [Cazadorsniper/PO3#1062]
**Pack version: 3.2.55**
**Pack Mode: Kappa**
**Multiplayer and might be in singleplayer (haven't tested)**

if i use agricraft seeds with cropsticks with ender io farmer, it wipes the output deletes the crops only gives the cropsticks and doesn't place cropsticks back.

these are the screenshots that shows the bug

https://imgur.com/9d4rkeP
https://imgur.com/E1esVM7

**Comment by Cazadorsniper** [comment]
Agricraft and Ender IO farmer aren't compatible, use a different farmer like from Industrial Foregoing.
