### ISSUE TITLE
Suggestion: add Betweenlands to make up for lost dimension mods

### ISSUE THREAD

**Issue by Ieldra2** [Cazadorsniper/PO3#1063]
I am seeing a pattern of removed mods that add dimensions. First Voidcraft, now Landcraft. May I suggest adding Betweenlands to make up for that loss. It has a nice selection of interesting resources and mechanics.

**Comment by Cazadorsniper** [comment]
I thought about adding Atum too, but decided not to add it.

**Comment by Ieldra2** [comment]
I would appreciate that mod, too. Just saying. ;) I've never played it.
