### ISSUE TITLE
Iron Block can't convert to Iron Ingot 

### ISSUE THREAD

**Issue by Grappeyy** [Cazadorsniper/PO3#1064]
The Iron block can be converted form block to ingot at all

**Comment by Frikkle** [comment]
You don't follow the support template, but apart from that, most metal blocks cannot be crafted regularly into their ingot forms. This was also the case in previous versions. You need to smelt them down into their liquid form and then cast them into ingots in for instance your smeltery. I think this is as designed.

**Comment by RobbeSchepens** [comment]
Or use a Factorizer I think it is called.

**Comment by Cazadorsniper** [comment]
That is correct for Kappa mode.
