### ISSUE TITLE
how to update your server?

### ISSUE THREAD

**Issue by Fabifoot** [Cazadorsniper/PO3#1065]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.56
**Pack Mode (Normal, Titan, Kappa):normal
**Singleplayer, Multiplayer, or LAN?:Multiplayer

Hello, I would like to know how to update your version server?
copy and paste everything?
Can you tell me the steps please?

**Comment by Grappeyy** [comment]
Download the new server files
Run the new server 
Move World File from old server to new Server Files aswell as Server Properties
Reload Server

**Comment by Fabifoot** [comment]
thank you, it works great!

(by removing the reforge mod)

**Comment by Frikkle** [comment]
@Fabifoot could you close your issue since it has been solved? :)
