### ISSUE TITLE
Enderium (possibly others too?) can no longer be cast to ingots/blocks.

### ISSUE THREAD

**Issue by tecnobrat** [Cazadorsniper/PO3#1066]
**Pack Version:** 3.3.56
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**

Enderium, Lumium, Signalum cannot be cast into ingots or blocks in the tinkers smeltery.

**Steps to reproduce:**

Melt enderium in smeltery, try to cast into ingot (or just check NEI, recipe doesn't exist)

I will check for some others as well.

**Comment by tecnobrat** [comment]
Looks like its likely the case with most of the enhanced TE metals. Lumium, Enderium, Signalum, etc.

**Comment by Frikkle** [comment]
Similarly, tinkers toolparts from these materials are not craftable anymore; has to do with PlusTic being removed/replaced.

**Comment by tecnobrat** [comment]
Tool parts are craftable for me.

**Comment by Frikkle** [comment]
@leaf-bot PlusTic has become unavailable for future use in modpacks; many packs are switching to alternatives. This usually comes with transition problems, like this :)
