### ISSUE TITLE
Had to remove mod. Now recipes do not work

### ISSUE THREAD

**Issue by XortiX-UR** [Cazadorsniper/PO3#1067]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.56**
**Pack Mode: Kappa**
**Multiplayer**

**Description:**
I updated my server and client to version 3.3.56.
Client started flawlessly. Server crashed every time until i removed the Tinkers Reforged mod.
Then it started again. But now i tried to craft a cobblestone generator tier 3, wich did not result in a new item. Also i tried to craft some LV Wire Coils. Same here. Recipe is showing in the JEI but does not work.

**Steps to reproduce:**
As i've already said. Just updated, to version 3.3.56. Then had to remove Tinkers Reforged to even get the server going. Now recipes are broken.

**Comment by Caedis** [comment]
There is an issue that the mod author is working on.
A workaround is to temporarily install Construct's Armory (mod isnt properly checking if the mod is installed on startup)

**Comment by Menion01** [comment]
Are you saying to keep Refoged enabled and to load Construct as well? Or just load construct by itself? 1.1.1 is still crashing my server. I can disable it but then I cant craft lasers. :)
