### ISSUE TITLE
DankNull not opening when flying

### ISSUE THREAD

**Issue by VoidedOut** [Cazadorsniper/PO3#1068]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.56
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Single
**Description:**
Using ability totem flight, trying to open the dank null's inventory when flying, doesn't work. I am using the emerald one specifically, not sure if it is the same issue with other types of flight or other dank nulls.
**Steps to reproduce:**
Fly then attempt to open dank null inventory (ctrl+right click)
**Crash log (use pastebin or issue will be closed):**
N/A

**Comment by VoidedOut** [comment]
Found this after posting, it also does not work if you walk to the very edge of a block with crouching and try to open it

**Comment by Cazadorsniper** [comment]
Its probably designed like that to prevent death from falling.

**Comment by VoidedOut** [comment]
It didn't do this in the previous version, but if you think that's what it is I can try and ask mod author or find a way to do that

**Comment by Cazadorsniper** [comment]
There were about 2 or 3 updates to the mod so it maybe in its changelog maybe.
