### ISSUE TITLE
Cant Download/Update pack

### ISSUE THREAD

**Issue by hendolad1234** [Cazadorsniper/PO3#1070]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.356**
**Pack Mode (Normal, Titan, Kappa):Kappa**
**Singleplayer, Multiplayer, or LAN?:Singleplayer**

**Description:Unable to update/download pack "Missing Addon ID: 275300"**

**Steps to reproduce: try to download the pack**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
That is on twitchapps side. Keep trying to download the pack.
