### ISSUE TITLE
v3.3.56 server not starting

### ISSUE THREAD

**Issue by Kevitto** [Cazadorsniper/PO3#1072]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.56
**Pack Mode (Normal, Titan, Kappa): Normal
**Singleplayer, Multiplayer, or LAN?: Server

**Description: Server crashes on initial bootup (fresh installation)

**Steps to reproduce: Downloaded and installed server pack 3.3.56 from CurseForge, extracted, crashes.

**Crash log (use pastebin or issue will be closed): https://pastebin.com/Gxj6kEEU

**Comment by gatanes** [comment]
Same crash log for me too

**Comment by gatanes** [comment]
disable Tinkers' Reforged.

**Comment by Cazadorsniper** [comment]
Duplicate of #1055
