### ISSUE TITLE
To Landia quest not removed, all the quests impossible

### ISSUE THREAD

**Issue by RagingStormMC** [Cazadorsniper/PO3#1073]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.56
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
The quest to create to portal to Landia hasn't been removed, while the Landcraft mod has been. Thus, you can't complete all the quests.
**Steps to reproduce:**
Go to the Lambda section in your quests tab (for which the icon is also missing), and the quest for Landia is still there.
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Didn't read the changelog? /bq_admin default load
