### ISSUE TITLE
Server Files Keep Crashing

### ISSUE THREAD

**Issue by DaHolyPriest** [Cazadorsniper/PO3#1074]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.56
**Pack Mode (Normal, Titan, Kappa):Normal
**Singleplayer, Multiplayer, or LAN?:Multiplayer

**Description: The Server is not able to compile and continues to crash when setting up.

**Steps to reproduce: Downloaded server files from twitch app and the server will crash on setup.

**Crash log (use pastebin or issue will be closed): https://pastebin.com/M7xvfCq7

**Comment by opters** [comment]
I'm wondering if the Server pack version 3.3.56 is actually working for someone. 
My server just freezes randomly, I've been told to remove tinkers-reforged but I still get the same problem.

**Comment by Menion01** [comment]
If you disable tinkers reforged in the mods folder the server should load. There was a post that version 1.1.1 fixed this problem but my server still crashes with that version as well.

**Comment by Speedy8g** [comment]
Server files are also not working for me either. As for how to disable tinkers reforged in the mod folder, not sure how to just disable a mod server side. Any help would be great, thanks!

**Comment by Ciros** [comment]
To disable a mod in the server files you need to rename the file to add .disabled after .jar
So go to your server folder then the mods folder then find tinkers_reforged. Right click the file and click rename. If you don't see .jar when you go to rename the file then you have to change a windows setting.
If you go to the File Explorer Options under the tab "View". Look for a setting that says "Hide extensions for known file types". Uncheck that setting then you should be able to see .jar when you try to rename the file.

**Comment by Caedis** [comment]
Update Tinker's Reforged to version 1.1.3
