### ISSUE TITLE
problem with screen who showin the block i'm looking at 

### ISSUE THREAD

**Issue by saw123456789** [Cazadorsniper/PO3#1075]
i've been playing to project ozone for 1 week and i cannot see the window on the of the screen which showing what kind of block i'm looking at 
![Problème Jei](https://user-images.githubusercontent.com/64756930/80928528-6ca38f00-8da5-11ea-8439-6bb236ab24ac.png)
Sorry for my english 
i hope you will answer soon

**Comment by Cazadorsniper** [comment]
Look for waila keybinds.

**Comment by Foodbegger** [comment]
By default press numpad 0 to open the menu for Hwyla/Waila then click waila once you have done that find Show/Hide Waila and set it to visible. Screenshots if you cant find the settings.

![2020-05-03_22 59 55](https://user-images.githubusercontent.com/47768358/80937507-a7e89280-8d92-11ea-90c0-5c1936af5606.png) 

![2020-05-03_22 59 58](https://user-images.githubusercontent.com/47768358/80937512-adde7380-8d92-11ea-8529-74f5a0d01faa.png)
