### ISSUE TITLE
Osmiridium is still in the aluminium crystal seed recipe

### ISSUE THREAD

**Issue by JoshuaBradbury** [Cazadorsniper/PO3#1076]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  3.3.56
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
The recipe for the embers aluminium crystal seed still contains osmiridium in the recipe, but not in JEI. This was found in a fresh install of PO3 in the kappa_3x3.zs file.

**Steps to reproduce:**
Try to craft the aluminium crystal seed.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Fixed it.
