### ISSUE TITLE
Missing Recipe for Bag Storage

### ISSUE THREAD

**Issue by hendolad1234** [Cazadorsniper/PO3#1078]
**Pack Version:3.3.56**
**Pack Mode (Normal, Titan, Kappa):Kappa**
**Singleplayer, Multiplayer, or LAN?:Singleplayer**

**Description:The recipe for the Bag Storage seems to be removed**

**Steps to reproduce:N/A**

**Crash log (use pastebin or issue will be closed):**

**Comment by VoidedOut** [comment]
This is intentional

**Comment by Foodbegger** [comment]
You can use quantum bags for the same effect

**Comment by FowD8** [comment]
> You can use quantum bags for the same effect

@Foodbegger  how do you go about using quantum bags for the same effect? didn't the Bag Storage store bags internally and you can convert to any other bag? You can't do that with Quantum Bags as far as I know?
