### ISSUE TITLE
Pebbles in Skylands world gen

### ISSUE THREAD

**Issue by Foodbegger** [Cazadorsniper/PO3#1079]
Pack Version: 3.3.56
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: When you right click the ground for pebbles in Skylands world gen you get 2 different kinds of pebbles from the Rite clicker and botania. Exact items are botania:manaresorce/21 and riteclicker:pebs

Steps to reproduce: Simply shift right click the ground in Skylands world gen.

Crash log (use pastebin or issue will be closed):

**Comment by Cazadorsniper** [comment]
This is fine.
