### ISSUE TITLE
crash on loading chisel

### ISSUE THREAD

**Issue by butterbrine22** [Cazadorsniper/PO3#108]
**Pack Version:**3.0.38

**Description:**when ever I am loading in the pack when it gets to chisel it crashes (I don't use a resource pack)

**Steps to reproduce:** I closed it early I think that may have something to do with it

**Crash log:** 
[crash-2019-03-07_00.24.44-client.txt](https://github.com/Cazadorsniper/PO3/files/2939723/crash-2019-03-07_00.24.44-client.txt)

**Comment by Cazadorsniper** [comment]
try letting it load then sending that crash report using pastebin

**Comment by chef-cheezy** [comment]
I don't know if this issue got fixed. Seeing that they didn't give a crash report probably not. PO3 loaded fine for me yesterday multiple times the past few days but today has crashed 5 times.

Here is the pastebin link... https://pastebin.com/ZqmSy7hK

**Comment by chef-cheezy** [comment]
So apparently it's fine now. I just started up the client today to see if it would work and it started on the first try.

**Comment by Cazadorsniper** [comment]
That has to do with your graphics card, make sure the pc is using the correct graphics card and that the drivers are up to date.
