### ISSUE TITLE
When joining the serve I am hosting, quests don't work

### ISSUE THREAD

**Issue by Voties** [Cazadorsniper/PO3#1082]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** project ozone 3 new way forward
**Pack Mode (Normal, Titan, Kappa):** normal
**Singleplayer, Multiplayer, or LAN?:**
multiplayer
**Description:** quests and pre given items work on singleplayer  but not multiplayer and it wont host an island world.  it spawns normal world.
really have no idea what im doing so I could use some help on this.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Start the pack using forge.

**Comment by Voties** [comment]
Im trying to do that but when I start the server using forge it runs out of available memory.  How do I allocate more m
![Annotation 2020-05-04 224402](https://user-images.githubusercontent.com/64776273/81033335-da5cc300-8e58-11ea-868d-e5f84b068422.png)
![Annotation 2020-05-04 224402](https://user-images.githubusercontent.com/64776273/81033336-dcbf1d00-8e58-11ea-80f7-abc16319b4d1.png)

emory towards the server?

**Comment by Voties** [comment]
> Start the pack using forge.

How do i allocate more memory to the server as seen in my comment

**Comment by Cazadorsniper** [comment]
Adjust the ram value in the bat file.
