### ISSUE TITLE
Server keeps skipping ticks and creating lag

### ISSUE THREAD

**Issue by AntonDotEXE** [Cazadorsniper/PO3#1085]
[crash-2020-05-01_00.22.34-server.txt](https://github.com/Cazadorsniper/PO3/files/4577283/crash-2020-05-01_00.22.34-server.txt)
[crash-2020-05-01_00.22.34-server.txt](https://github.com/Cazadorsniper/PO3/files/4577288/crash-2020-05-01_00.22.34-server.txt)

# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:* 3.2.52*
**Pack Mode (Normal, Titan, Kappa):* Kappa*
**Singleplayer, Multiplayer, or LAN?:* Multiplayer*

**Description:**
I've been hosting a PO3 server for a few months now and it has just started skipping ticks and has become pretty laggy. It has 12 gigs of memory that it could use but it hasn't capped yet. Here's what is popping up.

[Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 35530ms behind, skipping 710 tick(s)

A message like this is popping up every few seconds and it is very hard to see who is on and what is happening because of this problem.

I am running the server on a Ryzen 5 2600x with 16gigs of ram
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/fmLuQb4j

**Comment by Cazadorsniper** [comment]
Check people's bases, could be too many entities or someone has more than 1 barrel connector in a yabba barrel setup or someone is using an ME system with Yabba or storage drawers.

**Comment by NoahIles** [comment]
Can confirm Yabba does not handle bulk storage well with ME even though it has the infinity upgrades. Haven't fully tested but constant server lag from connecting via storage bus once the barrels start to hold millions of items. I believe it's CPU bound. Is there an intended end game storage?

**Comment by Cazadorsniper** [comment]
Yes, the ME system.

**Comment by NoahIles** [comment]
I realize, I guess we are still a bit mid game and it takes a boatload of capacitors, empowers are so slow and your stuck with them until we can get the energy condenser. Have you considered moving the blue capacitor requirement higher then the 4k drives. It would make a significant difference just putting it in the 16k or 64k recipe. Working towards the max extra cells drive right now and even with AE autocraftin 246k's 24/7 its taken over a day to get the drives we need.  with 6 active empowers.

**Comment by Cazadorsniper** [comment]
I have not considered it.

**Comment by icywhisker-official** [comment]
It's more than likely an ME issue as stated above. Personally I have seen massive lag spikes exactly as you described due to importing or exporting from a /dank/null see if your players are using those and promptly remove them from the ME system. Exporting to or from chests from the dank null may mitigate lag spikes but I haven't tried it yet.bi wish the toolbelt mod was in the pack so I could use that instead. There are other voiding options and the dank null isn't being updated anymore afaik

**Comment by Cazadorsniper** [comment]
Dank/Null is being updated.

**Comment by OxGG** [comment]
@Cazadorsniper  
i have similar bug, my server has to much lag tick, when i put to the me system the transmutation chamber with storage bus, this is the first server log , i created "tome of knowledge" and put in.

[ticklag.txt](https://github.com/Cazadorsniper/PO3/files/4665918/ticklag.txt)

a lot of items i guess?

**Comment by Cazadorsniper** [comment]
yes, a lot of items have emc.
