### ISSUE TITLE
Unable to pick items up after playing for a while

### ISSUE THREAD

**Issue by 123zane321** [Cazadorsniper/PO3#1086]
Pack Version: 3.3.56
Pack mode: Kappa
Singleplayer, Multiplayer, or LAN: Multiplayer

Description: After playing on the multiplayer world for roughly an hour or so, I seem to be unable to pick items up, even though my inventory is definitely not full. Jumping into the void and dying seems to temporarily fix the issue, but it's starting to get a bit annoying.

Steps to reproduce: Just stay logged in for an hour or so, then try to pick up any item.

Crash log: No crash log, issue is not with game crashing

**Comment by Cazadorsniper** [comment]
Could be item physics doing that or someone is causing a lot of tps lag.

**Comment by 123zane321** [comment]
Doesn't seem to be that case. I actually tried using a DE item dislocator to pick up items when the issue occured, and it tries to pick the items up, but they just don't want to go into my inventory - it's as if something is making the game think my inventory is full, which it definitely isn't.

**Comment by Cazadorsniper** [comment]
Try updating the pack to 3.3.57

**Comment by 123zane321** [comment]
Ok, will ask our server staff when they plan to update, will respond once they have and I've had a chance to test it again

**Comment by 123zane321** [comment]
Feel free to close this issue, apparently the problem was being caused by one of the plugins our server uses - sorry to waste your time XD
