### ISSUE TITLE
Kappa Mode Weak Blood Orb won't craft

### ISSUE THREAD

**Issue by SpeedSlider** [Cazadorsniper/PO3#1087]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
3.3.57

**Pack Mode (Normal, Titan, Kappa):**
Kappa
 
**Singleplayer, Multiplayer, or LAN?:** 
Single Player

**Description:**
I crafted and placed a Tier 1 blood altar. I then crafted a Lordic Rune Stone of Fire (Utility). This is where I think I screwed up somewhere. I actually crafted 8 runes. I thought there was enough LP in the altar but there wasn't so I added some while the rune was in the altar, but I think it ran out before I started adding. Anyway, after that nothing I did could get the weak blood orb to craft. I tired full blood altars, 10k LP, I broke and replaced the altar, I moved the altar to a new location, I exited and re-entered the world. Finally, this morning a new update was released to I restarted the pack with a new updated version and that didn't fix it. When I place the rune in the altar I get the particles indicating it is charging a blood orb but no LP drains and nothing happens. In the end I had to place 2k LP in a blood altar and break the altar, trash the rune, and cheat in a weak orb.

I am a noob at blood magic as I am not really a fan of the self-harm aspect of the mod. I did go through it partially in normal PO3 mode. But my noobness may be the real issue I suppose. However, noobs break stuff real good and make great bug finders/testers :P

**Steps to reproduce:**
1: try crafting without sufficient LP (maybe?)
2: refill altar with sufficient LP
3: Place Lordic Rune Stone of Fire (Utility) in tier 1 altar. Note: since you are trying to craft the weak blood orb that implies you are using a tier 1 altar.
4: you should see charging blood orb particles instead of the crafting particles and no LP will drain the process will just be stuck

**Crash log (use pastebin or issue will be closed):**
No crash associated with the issue.

**Comment by Cazadorsniper** [comment]
Its possible that it got stuck since it ran out of LP during a craft and the crafting progress deteriorates over time. 
Need more LP.

**Comment by mkaito** [comment]
More LP doesn't seem to solve the issue. I've never ran out of LP on the altar. The altar is full at 10k LP. It doesn't do anything with the Lordic Rune Stone of Firer (Utility). It just sits there. Guess I'll do as SpeedSlider did and just cheat in my weak blood orb.

**Comment by mocoman133** [comment]
I think you might not have used utility rune stone of fire,  I was having the same problem until I realized mine was offensive. You need to craft the simple rune stone offensive, then the lordic rune stone offensive and before you convert it to a lordic rune stone of fire put it in your inventory crafting table to change it from offensive to utility. That was the only way it worked for me. Double check that you are using utility otherwise you cannot create the blood orb. Hope it helps.

**Comment by mkaito** [comment]
> I think you might not have used utility rune stone of fire

I definitely did try a utility stone. I tried both, for good measure.
