### ISSUE TITLE
Platinum, Iridium, Invar, Aluminum & Tinkers' Construct Are Like Oil & Water

### ISSUE THREAD

**Issue by TheOrangeMadness** [Cazadorsniper/PO3#1088]
**Pack Version:3.3.57
**Pack Mode (Normal, Titan, Kappa): Normal
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: You can sometimes smelt the specific chunks and ore in the Tinkers' smeltery---and alloy with some---, and sometimes you can't. It is also strange that you can melt ore and chunks down, but if you have an ingot, you cannot smelt it at all. The straw that broke the camels back with this issue is that you can sometimes put the specific molten metals into ingot form, block form, and cast form, but other times your stuck with a boat load of molten metal in your smeltery that you can't get rid of. 

**Steps to reproduce: Description pretty much sums it up: you can throw ore chunks and ore blocks in smeltery 50% of the time; you can alloy Invar 50% of the time; you can make ingots, blocks, and casted forms of molten metal 50% of the time; you can loose out on a lot of molten metal due to it being stuck in smeltery. The only two ways to fix these issues is by either restarting the game, or by breaking the smeltery and starting back over. However, you'd be better off restarting the game, because the breaking of the smeltery sometimes doesn't work. 

**Note 1: I've seen anther issue report regarding Enderium (?) and that it too couldn't be put into block/ingot form. This, however, was only in the 3.3.56 branch. There could most likely be more metals (if not alloys) out there that could be bugged out as well.

**Note 2: I'm unaware of it also having this result in the other modes. There could be a high probability of it being buggy as well in Titan and Kappa.

This is just an idea, but I do believe that this issue could be solved by re-introducing the original idea of Platinum, Iridium, Invar, and Aluminum before 3.3.56. There were never any issues regarding making these molten metals in version 3.3.55. I can understand a little if the original concepts for the tools from Tinkers' Construct were a bit broken---if someone could elaborate further on this, it would be much appreciated---, but there were no bugs in smelting down the metals forming tool patterns/ingots/blocks. 

**Crash log: None required; game does not crash or seize up.

**Comment by aesguitar** [comment]
Still cannot cast invar as ingots or blocks from tinker's smeltery using Tinker's Reforged 1.2.0

**Comment by Mogibear** [comment]
Created an issue on the Tinkers Reforge GitHub. 

https://github.com/Mrthomas20121/Tinkers-Reforged/issues/8
