### ISSUE TITLE
cardboard box shelving issue

### ISSUE THREAD

**Issue by Magnumic0ray** [Cazadorsniper/PO3#1089]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.57**
**Pack Mode (Normal, Titan, Kappa): Kappa**
**Singleplayer, Multiplayer, or LAN?:singleplayer**

**Description:using a mekanism cardboard box on the magneticraft shelf multiblock causes the multiblock to deform, turning back to the blocks it was made from. In addition, the items inside the system are all deleted, and the cardboard box drops itself when shift right-clicked. I know this is just how the boxes work, but please prevent the boxes from interacting with the shelves.**

**Steps to reproduce: right-click a cardboard box on any block of a formed magneticraft shelf multiblock.**

**Crash log (use pastebin or issue will be closed): No crashes occur from this issue**

**Comment by Jokrskyz** [comment]
i click a shelving unit and lost all my items due to this
