### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by opters** [Cazadorsniper/PO3#1090]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.3.57
Pack Mode (Normal, Titan, Kappa): Kappa
Singleplayer, Multiplayer, or LAN?: multiplayer

**Description:** Server crashes after loading new pack version.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/EhJLB1rq

**Comment by Cazadorsniper** [comment]
Are you sure you're on 3.3.57? This issue has been solved already.

**Comment by opters** [comment]
100% sure.

**Comment by Caedis** [comment]
Your log says tinker's reforged is version 1.0.6, the latest version with the fix is 1.1.3

**Comment by opters** [comment]
This is weird, I'm downloading the current version that is on the site. Maybe it's a bug with my save? 
I will try removing it and checking. Sorry for taking so long to answer. Be right back.

**Comment by opters** [comment]
I went in my folder, got my save, threw it in my single player client, and it crashed my game too. 
Removed it from my server and it also worked. I dunno, maybe it just had something that was old in my save, and it wasn't loading properly? 

Anyways, solved! Thanks for you help :)
