### ISSUE TITLE
Landia missing from 3.3.57

### ISSUE THREAD

**Issue by Terrandel** [Cazadorsniper/PO3#1091]
Just updated to the newest release and found Landia missing entirely. I didnt see anything in changelogs, so i'm assuming this is unintended.

**Comment by kaotic2** [comment]
it's been removed from the pack along with a couple other mods.

**Comment by AnimeNerdDJBROS** [comment]
May be related to my issue with the quest log not having anything updated. (I'll go test this in a new world to see if its just a world based thing) But yes I was having problems with the quest system being messed up by these removals. 

Update-The test has proven the quest has updated upon opening a test world. 
These results show they either intended this, or the quest system has a system of voiding quests that would be unattainable.

**Comment by QGroundZeroQ** [comment]
So would there be another dimension  where i could find the temples for astral sorcery?

**Comment by Znavz** [comment]
You can find what you need in the deep dark.

**Comment by VoidedOut** [comment]
/bq_admin default load
To update your quest book

**Comment by Pe4enie** [comment]
It was completely intended, as all the mods from LandMaster were removed from curse (the dude got banned, google it up)

**Comment by Terrandel** [comment]
Sorry for the late reply. thank you for all the information! I'm glad it was intentional and not an accident. reloading the quest book also corrected my game (since I was updating an existing game). Thanks for all your work to make a fun pack for us to play!
