### ISSUE TITLE
Quest Log Troubles

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1092]
I found myself quite confused after downloading the latest update, the removal of Landia and Thorium screwed over my quest log making them unobtainable as it doesn't just pass it off and say you've attained it, but rather it calls it a placeholder item. 

So what I'm looking for here is to get an answer as to how to either force complete the quest, or refresh the questing log to what it should be now without resetting my progress, as that would be quite annoying to redo every single quest.

**Comment by Znavz** [comment]
Did you remember to use "/bq_admin default load" after the update?

**Comment by AnimeNerdDJBROS** [comment]
Ah , I'll try that, I'll follow up with what's going on there, but it is quite weird, multiple things suddenly disappeared , while the change log listed none of the removed mods.

**Comment by AnimeNerdDJBROS** [comment]
It worked thanks.  @Znavz
