### ISSUE TITLE
server freezing/crashing

### ISSUE THREAD

**Issue by MrFieryPotato** [Cazadorsniper/PO3#1094]
3.2.55
Normal
Multiplayer also happens in single player

When i boot up the server and someone joins the world is ok until a few minutes later it randomly freezes and requires a reboot. In this world i have set up many mob duplicators to get the landia singularities with a wand of animation. After it stars the server sits around 40% memory usage and does not move. It has 12 gigs

I have no idea how this happened

https://pastebin.com/2htLQX1T

**Comment by Cazadorsniper** [comment]
There is an anvil falling at this location: (-2383,22,-1290) recommend removing it with mcedit or something like that.

**Comment by MrFieryPotato** [comment]
ic thanks

**Comment by Cazadorsniper** [comment]
Or use the forge.cfg option to remove broken entities/tileentities, I'm not sure if it will work though.
