### ISSUE TITLE
Electrotine recipes

### ISSUE THREAD

**Issue by Alpodip** [Cazadorsniper/PO3#1096]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  PO3-3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:**  Singleplayer

**Description:**
i updated PO3-3.3.55 to PO3-3.3.57 and Electrotine Alloy Ingot kiln recipe is going. i can craft only 8x Electrotine dust and iron

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by MrFieryPotato** [comment]
you need to smelt the electrotine compound
