### ISSUE TITLE
Lasers? 

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1097]
TCon Laser guns were previously in the  pack, along with wither bone arrow shafts, both have disappeared from the pack, what removals have been intentionally and what have not? A lot of mods which would've needed to be used prior have been removed for some reason along with certain weaponary and other items.

**Comment by Arkangeli** [comment]
TCon Laser guns have been removed (don't know the reason but they were a little bit OP imo) and all other needed materials which was needed to progress that were from the removed mods such as Landia, has been replaced with new materials. So, there should not be any problems in progressing through the pack other than a few bugs.

**Comment by AnimeNerdDJBROS** [comment]
Yes, I understand why the may have been removed , however there's no mention of these mods being removed in the change-log and the lasers had been a thing since the start of the pack, why remove them now?

**Comment by VoidedOut** [comment]
They were mentioned in the changelog. They were removed from the pack because they were removed from curse

**Comment by AnimeNerdDJBROS** [comment]
Ah mk, though that doesn't explain the other parts of the issue, generally things like Landia, some armors , wither bone arrowshafts, all disappearing from the pack.

**Comment by AnimeNerdDJBROS** [comment]
I understand maybe some things were replaced, but it seems odd as for a reasoning, and also some things that were removed that likely were not replaced. It's just stumps me as to why.

**Comment by Cazadorsniper** [comment]
PlusTic, Land Core and Land Craft are gone from curseforge therefore I can no longer use them at all. 
Tinkers' Reforged and Materialis replaced PlusTic so no more lasers.
