### ISSUE TITLE
Causing Game Crash On launch

### ISSUE THREAD

**Issue by ThomsonGaming** [Cazadorsniper/PO3#11]
during the load of the pack, the client seems to crash due to what seems to be a texture issue. 

here a Pastebin of my crash report
https://pastebin.com/zy0uTACt

**Comment by devi4nt** [comment]
Have you tried during Breakfast?

**Comment by ThomsonGaming** [comment]
sorry?

**Comment by devi4nt** [comment]
Sorry, clearly not funny huh. think you meant "launch" :)

**Comment by Cazadorsniper** [comment]
Try removing optifine

**Comment by ThomsonGaming** [comment]
> Try removing optifine

i get the same crash with or without optfine

**Comment by Cazadorsniper** [comment]
if that doesn't work try using a dedicated graphics card. If on a laptop and the only graphics is coming from the cpu then good luck.

**Comment by ThomsonGaming** [comment]
i guess i was just rushing to file this crash report

**Comment by Cazadorsniper** [comment]
This isn't really a pack issue, its more so your pc not being able to handle some textures.
