### ISSUE TITLE
Project Ozone 3 freeze in loading terrain

### ISSUE THREAD

**Issue by LnOxJeSus** [Cazadorsniper/PO3#110]
Every time i try to load a world it frezzes on loading terrain
My specs: CPU Ryzen 7 1700 GPU geforce gtx 1060 6gb RAM 8GB I use 6gb in minecraft
Anyone can help me please

**Comment by Cazadorsniper** [comment]
Give me the latest.log to see what its doing.

**Comment by LnOxJeSus** [comment]
I found the Problem i only need to start the World in windowed Mode

Cazadorsniper <notifications@github.com> schrieb am Do., 7. März 2019,
19:53:
