### ISSUE TITLE
Burning Saplings

### ISSUE THREAD

**Issue by icywhisker-official** [Cazadorsniper/PO3#1100]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.57
**Pack Mode Normal
**Singleplayer

**Description:**
Placing a furnace next to a crafting station will make the furnace show beside the crafting grid.

**Steps to reproduce:**
Open the crafting station
place a oak plank on the left slot.
right click an oak sapling into the middle slot (have more than one on your mouse)

observe that you are kicked out of the crafting menu and your oak saplings vanish from your inventory and the furnace burns one.

**Comment by Cazadorsniper** [comment]
I tried this, and the furnace burned 1 sapling and threw the rest of the saplings on the ground for me. Sadly I can't fix this issue on my side afaik.
