### ISSUE TITLE
dank/null contents reset on update

### ISSUE THREAD

**Issue by Kename** [Cazadorsniper/PO3#1101]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Lan

**Description:** After updating to 3.3.57 from 3.2.55 the dank/null was empty. Emerald tier with all but one slot of the dank/null containing items.

**Steps to reproduce:** updated server & client, launched server, connected, checked dank/null

**Crash log (use pastebin or issue will be closed):** No crash, Only dank/null affected (that I can tell).

**Comment by Cazadorsniper** [comment]
Check /dank/null recent update changelogs.

**Comment by BuggaNoia** [comment]
A hint in the WTF section of the changelog would be nice
