### ISSUE TITLE
Chunk updates when placing items in crafting grid of tinker's crafting table

### ISSUE THREAD

**Issue by Pe4enie** [Cazadorsniper/PO3#1102]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** I noticed pretty hard FPS drops when placing items in crafting grid of tinker's crafting table. After some investigation I've found out the following:

- FPS in tinker's table GUI is lower in general even when not doing anything (usually I have it at 120+)
- the issue doesn't occur in vanilla crafting table
- the issue is reproducible even in the new empty world
- the issue is likely caused by chunk updates occuring when placing/removing items
- the issue remained even when I turned off rendering of placed items in the world (under tinker's construct mod configuration > clientside > renderInventoryInWorld)
- the issue was not related to chunk loaders I had in the world

**Steps to reproduce:**

1. have a tinker's construct crafting station placed in the world
2. have a stack of something
3. open debug information
4. spread that stack over crafting grid of tinker's table
5. double click on one of the crafting grid cells to collect placed items
6. see caused chunk updates in the debug info

My recording of the issue - https://imgur.com/a/wP9Vyrh

**Comment by Cazadorsniper** [comment]
Try disabling the very first config in tconstruct.cfg.

**Comment by Pe4enie** [comment]
You mean renderInventoryInWorld? I already did that (it's also mentioned in the issue body btw)

**Comment by Cazadorsniper** [comment]
Well I couldn't get this issue top reproduce.

**Comment by Pe4enie** [comment]
Is there anything I could provide from my side?

**Comment by Cazadorsniper** [comment]
Can you try to reproduce the issue with only TConstruct?

**Comment by Pe4enie** [comment]
Cloned the instance, removed everything besides TConstruct and Mantle (it depends on it). Can't reproduce the issue anymore. I guess it's something else then

**Comment by Cazadorsniper** [comment]
Likely.
