### ISSUE TITLE
Thorium in the new update

### ISSUE THREAD

**Issue by MrMoustachioo** [Cazadorsniper/PO3#1103]
I recently updated to the newest version that removed Landcraft. Previously that mod provided thorium. 
Now the only remaining source of thorium is the Nuclearcraft ore, which doesnt seem to spawn anywhere (I checked the deep dark exstensively, new chunks too). You can get it from the laser drill but you need thorium first to craft that....

Am I missing something? Do I maybe need to regenerate the entire deep dark or is this an oversight after Landcraft got removed?

**Comment by Cazadorsniper** [comment]
Look in Lost Cities dimension.
