### ISSUE TITLE
moo fluids cows not spawning

### ISSUE THREAD

**Issue by M7mdayyoubhr** [Cazadorsniper/PO3#1104]
Pack Version : 3.3.56
Pack Mode : normal
Singleplayer

**Description:**
my world type is garden of glass and im in jungle biome and ihave built a grass area but no cows are spawning
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
It takes awhile sometimes.

**Comment by AnimeNerdDJBROS** [comment]
You can get more Fluid cows by the mob duplicator and turning exact copy off, but it takes quite a bit of grinding to get up to both the duplicator and mob crusher and an ender tank to route essence from the crusher (At an auto mob farm) into a duplicator (Down wherever you want) and the duplicator has a limited radius,  and if too many cows are within that radius you will not get cows spawning. It's definitely an annoying process but if you look into that it'll definitely make your life a bit easier than waiting like an hour per fluid cow.

**Comment by Cazadorsniper** [comment]
Could look for cows in the lost cities dimension.
