### ISSUE TITLE
Server world type won't work.

### ISSUE THREAD

**Issue by GSanspaps** [Cazadorsniper/PO3#1105]
# Use the search function before reporting to see if the issue has been reported before.
**3.3.57**
**Normal**
**Multiplayer**

**I changed the Level Type to botania-skyblock and It's not changing:**

**Apparently , after I asked someone that knows how to make servers , it shouldn't happen**

**No crashes**

**Comment by Cazadorsniper** [comment]
Are you starting the server with forge?

**Comment by GSanspaps** [comment]
Yeah , I deleted the world and then I restarted the server.

**Comment by GSanspaps** [comment]
I deleted the Server folder and I have redownloaded the server files .Should I start with the batch file or how.... ? I am not that experienced with servers

**Comment by Cazadorsniper** [comment]
Start minecraft server, accept eula, start again, change server.properties and delete the world folder, edit bat file to start the pack with forge.

**Comment by GSanspaps** [comment]
I have started to server , I stopped it, deleted the world server and changed the level type (I suppose that server.properties is the server PROPERTIES Files) and also set the IP. But how do I do that with the bat file ?

**Comment by Cazadorsniper** [comment]
Edit the bat file to start forge instead of minecraft server.

**Comment by GSanspaps** [comment]
Yeah , but idk how to edit the bat file to start forge instead .

**Comment by MrFieryPotato** [comment]
it should be somthing like forge1.12.jar or somthing in the .bat file

**Comment by GSanspaps** [comment]
![GitHub1](https://user-images.githubusercontent.com/58392844/81386197-48391100-911d-11ea-8dad-afc3cfd8ac6a.PNG)

**Comment by GSanspaps** [comment]
What I don't know is how to edit it in the said way.

**Comment by MrFieryPotato** [comment]
@ECHO OFF
java -Xms2048m -Xmx16g -jar forge-1.12.2-13.23.5.3847-universal.jar nogui
pause

allocate as much ram as you need in the -Xmx16g spot copy this in tho the start file

**Comment by Cazadorsniper** [comment]
Can be edited with windows notepad or other text programs like Notepad++ and Sublime.

**Comment by GSanspaps** [comment]
![GitHub2](https://user-images.githubusercontent.com/58392844/81467093-f658bf80-91de-11ea-8b31-44235a365c33.PNG)

**Comment by GSanspaps** [comment]
What do I need to write in the notepad to make it start the forge ?

**Comment by GSanspaps** [comment]
Nvm I saw it in MrFieryPotato ;)

**Comment by GSanspaps** [comment]
With off and pause aswell ?

**Comment by GSanspaps** [comment]
So If I copy what @MrFieryPotato I just change the RAM allocated , right ? So what do I have to write in the bat file to start  with forge ?

**Comment by MrFieryPotato** [comment]
i put the correct jar file in you just need to copy it in and change the ram amount

**Comment by GSanspaps** [comment]
So I use the edit option on the start  .bat file and copy that string ? With the pause and off as well ?

**Comment by GSanspaps** [comment]
I pasted what you gave me and put 6g of ram , but it won't start

**Comment by Cazadorsniper** [comment]
rename the forge portion of the edit to: forge-1.12.2-14.23.5.2847-universal.jar

**Comment by Cazadorsniper** [comment]
Also You should look up a youtube video on how to start modded servers.

**Comment by GSanspaps** [comment]
I did that at first , and from the looks of it , no one hit the same roadblock as me .

**Comment by GSanspaps** [comment]
I got this message 
[19:50:37] [Server thread/WARN] [minecraft/DedicatedServer]: **** FAILED TO BIND TO PORT!
[19:50:37] [Server thread/WARN] [minecraft/DedicatedServer]: The exception was: java.net.BindException: Cannot assign requested address: bind
[19:50:37] [Server thread/WARN] [minecraft/DedicatedServer]: Perhaps a server is already running on that port?
[19:50:37] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[19:50:37] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds

**Comment by GSanspaps** [comment]
NVM that error , it was an internet problem on my end . I want to thanks you so so much ! It works! Thank you for all of your effort put into this! I hope only the best happen to you and I hope you have a good day !
