### ISSUE TITLE
Lord Craft research issue

### ISSUE THREAD

**Issue by CptFir3** [Cazadorsniper/PO3#1106]
# Use the search function before reporting to see if the issue has been reported before.

**Pack Version:** 
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
kappa

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer(server)

**Description:**
Lord Craft "Basics" Research shows as completed. I was going to start on Water research but its locked. Under the requirements it says: Basics. 

So I am kind of stuck, Basics is showing complete but the requirements for all research (Water, Earth, Air, Dark) are locked. I had already started Light, and under light progression I had done Light tools, and robes. But I am unable to start research for the other elements 

**Steps to reproduce:**
I was running server and client version 3.2.55 and updated to 3.3.57, I went con continue where I left off in Lord Craft and that happen. 

I try trhowing a crystal on the floor and picking it up to see if it would complete basics again and nope. I also went and mined crystals and that did not work either. 

Here is a screenshot: 
https://imgur.com/a/nsKa5lM

Any suggestions?  

**Crash log (use pastebin or issue will be closed):**
No crash log.

**Comment by Cazadorsniper** [comment]
Research more until it other elements unlock.
