### ISSUE TITLE
Thorium generation

### ISSUE THREAD

**Issue by loltatoez** [Cazadorsniper/PO3#1107]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer (with LAN, no impact though)

**Description:**
Thorium does not generate
**Steps to reproduce:**
After updating to .56+, since Landcraft has been removed, no Thorium generates. This is because you (I assume) had the Landcraft Thorium generate instead of the Nuclearcraft so you disabled the Nuclearcraft thorium in the config. Since Landcraft is now removed, the Thorium doesn't generate since the Nuclearcraft one is still disabled.

(Line 868 in the nuclearcraft.cfg, ore just Ctrl + F and search for `#Will ores generate`)

Edit: After doing some digging, I figured out that ALL ores spawn in Darkland Forests in the Lost Cities. Thorium, Uranium, Magnesium, Lithium. All of them. That's a bug on its own, but this seems to be the only way to get Thorium

**Comment by loltatoez** [comment]
Edit

**Comment by Cazadorsniper** [comment]
po3/config/cofh/world
