### ISSUE TITLE
Crash while launching after pack update

### ISSUE THREAD

**Issue by ianv365** [Cazadorsniper/PO3#1108]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version 3.3.57
Pack Mode Kappa
Singleplayer

Updated pack through twitch launcher and went to launch it and it crashed while launching with the error message "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers' Reforged (tinkers_reforged)|

**Steps to reproduce:**

Crash log: https://pastebin.com/1ggJzLYw

**Comment by Cazadorsniper** [comment]
Remove conarm-1.12.2-1.2.5.3.jar
