### ISSUE TITLE
Glimmer Crystal, Alchemical Waste

### ISSUE THREAD

**Issue by AscendInTime** [Cazadorsniper/PO3#1109]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Single

**Description:**
Every time I attempt to make a glimmer crystal with different amounts of ash it results in getting an alchemical waste of 8 every time. I started with 64 ash initially and it told me it was 8 off, tried again using 72 and got the same thing. Same thing when I tried with 80. Alchemical waste said 8 tried 72 again and got the same amount of alchemical waste. I was trash canning the alchemical waste as I was getting them so i'm not sure why it keeps coming up with 8 every time
**Steps to reproduce:**
Attempt to make Glimmer Crystal using various amounts ash
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
This is better suited to ask on our discord server. Can find the invite on the overview of the pack.

**Comment by AscendInTime** [comment]
Understood thank you
