### ISSUE TITLE
Typo in pebble quest

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Cazadorsniper/PO3#111]
**Pack Version:**
PO3-3.0.38

**Description:**
The quest to gather pebbles has a typo. It says to "right-click" on grass or dirt, but that does not work. I found "shift-right-click" works, so I edited our BQ on our server; thought you might want to do the same

**Steps to reproduce:**

**Crash log:**

**Comment by Cazadorsniper** [comment]
my bad.
