### ISSUE TITLE
Lootbag Storage can't be find  nor crafted. but Confing is the opposite 

### ISSUE THREAD

**Issue by player1560** [Cazadorsniper/PO3#1110]
So i'm in game, and i can't find the craft for the lootbag storage even if in the config it says the opposite :     # Disables the bag storage from being crafted.
                     B:"Disable Storage Recipe"=false

**Comment by player1560** [comment]
same for the filter of EXTRA UTILITIES 2 
it's true in config but cant craft it

**Comment by kaotic2** [comment]
I think the lootbag storage was disabled due to duping.

**Comment by Cazadorsniper** [comment]
Lootbag storage is disabled due to duping and filter is disabled due to some lag.
