### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by MrFieryPotato** [Cazadorsniper/PO3#1111]
3.2.55
normal
singleplayer and tested world on a server

when playing in the world for a few minutes the game randomly freezes and any progress in the world is deleted

no idea how it happens but i have about a thousand ingot formers running and a huge mob farm if thats the issue.

game gives no report file on freeze

i can show a video of what happens if needed

**Comment by Cazadorsniper** [comment]
Maybe due to the ingot formers and mob farm.

**Comment by MrFieryPotato** [comment]
ill try deleting em

**Comment by MrFieryPotato** [comment]
i destroyed them relogged and it still froze after

**Comment by Cazadorsniper** [comment]
I will need the latest.log to figure out more.

**Comment by MrFieryPotato** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/4602195/latest.log)

**Comment by MrFieryPotato** [comment]
https://gist.githubusercontent.com/MrFieryPotato/82204a451379736edaedb81359406013/raw/6aa844e7f9233a89c6625c770824a1f7f204251b/latest.log

**Comment by Cazadorsniper** [comment]
Locate dimension -6 (should be aroma mining dimension) Chunk: 289, 289 and Chunk: 441, 441 in the overworld, these chunks seem to be causing the world to memory leak.

**Comment by MrFieryPotato** [comment]
i think i know. me and my friend were playing with chance cubes and got a few chaos explosions then the server crashed. after restarting it did work for a while though

**Comment by MrFieryPotato** [comment]
https://raw.githubusercontent.com/MrFieryPotato/hi/master/latest this is what happens after deleting the chunks

**Comment by Cazadorsniper** [comment]
Something wrong?

**Comment by MrFieryPotato** [comment]
idk it still has the same issue

**Comment by Cazadorsniper** [comment]
I don't know the problem sorry.
