### ISSUE TITLE
Server crashing on boot

### ISSUE THREAD

**Issue by xtreemninja** [Cazadorsniper/PO3#1112]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.3.7
**Pack Mode (Normal, Titan, Kappa):**normal
**Singleplayer, Multiplayer, or LAN?:** multiplayer

**Description:**
Server crashes almost as soon as it fully loads I've tried allocating more ram and still have the same issue
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/HSyiht3i

**Comment by MrFieryPotato** [comment]
I believe in server properties change server tick to -1 its usually at 60000 or something . its works for me

**Comment by xtreemninja** [comment]
thanks MrFieryPotato that fixed the issue of it crashing now however the server now is  running "120180ms" behind constantly according to the console here any ideas?
