### ISSUE TITLE
Unable to obtain thorium

### ISSUE THREAD

**Issue by Hendri475** [Cazadorsniper/PO3#1113]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** As far as I can see, it is now impossible to obtain thorium when you don't already have Thorium Seeds or a Industrial Foregoing Laser. I couldn't find any ore in a default generated world or in the Deep Dark and the Landia dimension doesn't exist anymore. For the Thorium Seeds you already need to have thorium and the Industrial Foregoing Laser Base requires glowstone ingot. This ingot can only be made in a Osmium Compressor, which requires Enriched Alloy. For that you need a Pneumaticraft capacitor. This needs an Ender IO Melodic Capacitor, which needs melodic alloy. However, the melodic alloy is made with thorium, so you also aren't able to build the Industiral Foregoing Laser Base.

I hope my explanation wasn't too confusing, but the recipes in Kappa mode are really complex.

**Comment by nycolassoares** [comment]
If i remember correctly it spawns in the Lost Cities (not sure) and in the Mining Dimension (100% sure it generetes there).

**Comment by Hendri475** [comment]
Also found thorium in the Mining Dimension, thanks! Didn't knew of the dimension until now
