### ISSUE TITLE
portal to deep dark 

### ISSUE THREAD

**Issue by luki222555** [Cazadorsniper/PO3#1115]
**Pack Version:**
 3.3.57
**Pack Mode (Normal, Titan, Kappa):** 
Kappa
**Singleplayer, Multiplayer, or LAN?:**
single

**Description:**
Portal to deep dark can't be crafted because required coralium ore witch can be mined only in the landia wich now been removed , so i can't craft it now .

**Comment by Caedis** [comment]
I have found Coralium in the Lost Cities

**Comment by luki222555** [comment]
Where i find lava crystal ?

**Comment by Caedis** [comment]
The Nether

**Comment by luki222555** [comment]
i dont find any

**Comment by Caedis** [comment]
Check around Magma Blocks, especially in the big magma block lakes

**Comment by luki222555** [comment]
and how to create portal to lost citiess ?

**Comment by Caedis** [comment]
Find that out on your own (hint: use 2 blocks of Lava Crystals instead of Emeralds)
