### ISSUE TITLE
Portal to erebus 

### ISSUE THREAD

**Issue by luki222555** [Cazadorsniper/PO3#1116]
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
kappa
**Singleplayer, Multiplayer, or LAN?:**
single
**Description:**
portal to erebus can't be crafted because gaean keystone required thorium block . Thorium can be only mined in the deep dark and poratl to deep dark can't be crafted required because mising landia mod .

**Comment by Jyrath** [comment]
Try looking around the Lost Cities Dimension (Quest in Lamba section)
