### ISSUE TITLE
No way to obtain abyssalnite

### ISSUE THREAD

**Issue by vehyr** [Cazadorsniper/PO3#1117]
Pack Version:3.3.57
Pack Mode (Normal, Titan, Kappa):normal
Singleplayer, Multiplayer, or LAN?:All

Description:On reddit i found the way to get abyssalnite was to go to landia ... but there's no landia and i can't find a dreadlands biome to laser drill in , fix pls

**Comment by Cazadorsniper** [comment]
Lost Cities
