### ISSUE TITLE
Blutonium can be acquired too early

### ISSUE THREAD

**Issue by Jaymus3** [Cazadorsniper/PO3#1118]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
N/A
**Description:**
Cyanite is a prerequisite for most Nuclearcraft machines, which is a good gate since Nuclearcraft's fusion reactor makes the extreme reactor obsolete by comparison.  Cyanite can be acquired without making a big reactor which seems to break progression a bit.
**Steps to reproduce:**
Run yellorium through a SAG mill (preferably with grinding balls for bonus secondary) and receive cyanite without making a reactor.
**Crash log (use pastebin or issue will be closed):**
No crash.

An easy solution would be to remove the cyanite from the SAG mill products, or if access to Nuclearcraft machines being easier is intended, then the fusion core should have its recipe modified, potentially to include PneumaticCraft capacitors or something of that difficulty.

**Comment by MrFieryPotato** [comment]
might be intended. not sure
