### ISSUE TITLE
Cant find thorium

### ISSUE THREAD

**Issue by Moreth** [Cazadorsniper/PO3#1119]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
kappa
**Singleplayer, Multiplayer, or LAN?:**
single
**Description:**
I've mined in twilight forest zone,deep dark and lost cities for hours and still can't find any thorium on the latest version of the pack. My progression stopped and i can't find any info other then "mine in the twilight forest or landia"

**Comment by MrFieryPotato** [comment]
it should be in the lost cities. your probably just unlucky

**Comment by Moreth** [comment]
Found it, tyvm.
I generated some new chunks and found really fast. Looks like the chunks generated before the update didnt have the ore on them.
