### ISSUE TITLE
Tome of Knowledge + Equivalent Integration = Unplayable

### ISSUE THREAD

**Issue by MrPopannes** [Cazadorsniper/PO3#112]
Pack Version: 3.0.38

Description: After using the tome of knowledge, The ME-Network (Using Equvalent Integration Chamber) and the game in general lagged out. This might be expected, but why is the tome then enabled? And why is there no warning?

Steps to reproduce: ME-System + Transmutationchamber + Tome

Cash log: None. Server side lag of about 3-5 seconds opening or using anything.

Edit: I posted a similar Ticket at the equivalent integration github. Just so you know

**Comment by DangerHSW** [comment]
That is expected if you realize what you do. The amount of items you have learned is huge. And it has to calculate all these items in the system and how many you can have with the amount of emc you have. There is no one to blame for it and definitely not the Modpack Dev to "not warn". Also it isn't to bad. If you don't like the lag you get for that brief moment, remove the Integration Chamber and just use your tablet. It is just alot of calculations and stuff with it.
