### ISSUE TITLE
Game Is Breaking

### ISSUE THREAD

**Issue by SHOVEL-KING** [Cazadorsniper/PO3#1120]
# Use the search function before reporting to see if the issue has been reported before.
I have no idea what this is called so sorry if it has already been answered.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Titan
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
When I join the world the game works for a few seconds and then devolves into this monstrosity. It only happens when the character moves, and the position does not update. It also does not happen on vanilla mc. Was wondering if I could get some help on this.  
**Steps to reproduce:**
Yeah I could not reproduce this if I wanted to. 
**Crash log (use pastebin or issue will be closed):**
Did not crash.

Here is a link to the video:
https://drive.google.com/file/d/11fz4DthPzp4S8vRlXkPLtkjrBY3bXu4p/view?usp=sharing

**Comment by Cazadorsniper** [comment]
What BetterFPS algorithm are you using? If its Taylor's algorithm then change it to something else.

**Comment by SHOVEL-KING** [comment]
Yeah I was using Taylor's and changing it worked. Thanks for the help.
