### ISSUE TITLE
Ender Modular Solar Panel creates too much power

### ISSUE THREAD

**Issue by tree856** [Cazadorsniper/PO3#1121]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Titan
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
The RF generation upgrade for the Ender Modular Solar Panel adds 6400 RF/t insted of 100 RF/t

**Comment by Cazadorsniper** [comment]
Yup.
