### ISSUE TITLE
Can't Craft Gaia Mana Spreader in Kappa Mode

### ISSUE THREAD

**Issue by Nightman211** [Cazadorsniper/PO3#1122]
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
I cannot craft the Gaia Mana Spreader from Botania. The recipe says I have all the items, and it can be auto put into a crafting table using the + button from JEI, however the item is uncraftable and does not show up. I tried inputting the recipe as an ME pattern, however it also didn't recognize the recipe as crafting anything.

**Steps to reproduce:**
I have 4 Terrasteel Ingots, 1 Gaia Spirit, 1 Elven Mana Spreader, and 1 Dragonstone
Attempt to craft Gaia Mana Spreader
It is unable to be crafted
I also attempted it as an ME pattern, which also did not work

**Crash log (use pastebin or issue will be closed):**
No crash log as there was no crash

**Comment by Cazadorsniper** [comment]
Is the client and server on kappa mode?

**Comment by Nightman211** [comment]
I am fairly certain both the client and server are on kappa mode, as other kappa mode recipes also worked. Before I tried to craft the mana spreader, and I had successfully crafted the 7x7 and 9x9 elite crafting tables, which I believe have different kappa mode recipeps.
