### ISSUE TITLE
astral sorcery ancient shrine problem

### ISSUE THREAD

**Issue by Alpodip** [Cazadorsniper/PO3#1123]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  3.3.57
**Pack Mode (Normal, Titan, Kappa):**  Kappa
**Singleplayer, Multiplayer, or LAN?:**  Singleplayer

**Description:**
how can be found ancient shrine after without landia ?
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Lost Cities
