### ISSUE TITLE
Invar and other molten ores missing ingot casting recipe

### ISSUE THREAD

**Issue by Wargarbler** [Cazadorsniper/PO3#1125]
Pack Mode Normal,

This issue has been reported below, but not in a way that was easy to read. Something about oil and vinegar.

**Comment by random53** [comment]
Usually if you can still cast but it doesnt show in jei its to have less items loading in jei to help with lag loading etc

**Comment by Wernerdeschryver** [comment]
Tried today and Invar cannot be cast from a smeltery into ingot or block form at all. This doesn't seem intended to me?

**Comment by random53** [comment]
Looks to me like its intended. You can cast tinker's parts with invar but im assuming (at least for kappa) that invar is blocked until you make other machines for it.

**Comment by Wargarbler** [comment]
I can see it being blocked in Kappa, seems strange to be blocked in normal. If intended it is what it is. Just caught me by surprise, it wasn't blocked in .55

**Comment by Cazadorsniper** [comment]
Because its not intended, mods are being weird at the moment.

**Comment by Wargarbler** [comment]
Thanks for the feedback. Loving the pack. Hope you can get it working the way you want without too much trouble :)
