### ISSUE TITLE
Twilight Forest Portal 

### ISSUE THREAD

**Issue by Jendx517** [Cazadorsniper/PO3#1128]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** PO3-3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
I create the twilight forest portal , then I went into it, but when I came out from the portal, it create a new twilight portal which out of my base.
**Steps to reproduce:** N/A

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by NoahIles** [comment]
This has more to do with the twilight forest mod then this pack lol. If anything post an issue on his mod page over at https://github.com/TeamTwilight/twilightforest/issues.
