### ISSUE TITLE
Update Coralium Ore Quest Description

### ISSUE THREAD

**Issue by tkoopman** [Cazadorsniper/PO3#1129]
Pack Version: 3.3.57
Pack Mode: Kappa

Description: Update quest "Coralium Ore" description from "Can be found in Landia" to maybe something like can be found in Twilight Forest Swamps.

**Comment by Tirexxg** [comment]
Also the Quest "Astral Sorcery Structures" description says that you can find Astral Sorcery structures mostly in the Landia Dimension. How and where can we find these Structures now?

**Comment by LordKedryn** [comment]
Can't recall where Coralium Ore spawns, it probably spawns in Landia like the quest book says, as for the Astral Sorcery Structures they do infact spawn all over the Landia Dimension you can't miss them, they are big structures made out of marble.

**Comment by hendolad1234** [comment]
@LordKedryn the landia dimension has been removed. @Tirexxg you can find the astral structures in the lost cities i believe
