### ISSUE TITLE
Extra Utilities machine Shift-click causes crash

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Cazadorsniper/PO3#113]
**Pack Version:**
 PO3-3.0.38
**Description:**
Extra Utilities machine [Shift-click causes crash](https://github.com/rwtema/Extra-Utilities-2-Source/issues/254)
**Steps to reproduce:**
For resolution, please see https://github.com/rwtema/Extra-Utilities-2-Source/issues/254

**Crash log:**

**Comment by DangerHSW** [comment]
#knownissues

**Comment by ClaudiusMinimus** [comment]
As shown by the link in my post the issue in Extra Utilities has been resolved for some time. Hopefully, the pack can soon be updated to resolve this.
