### ISSUE TITLE
Animals not spawning

### ISSUE THREAD

**Issue by JoelGusto** [Cazadorsniper/PO3#1132]
**Pack Version: 3.3.57
**Pack Mode (Normal, Titan, Kappa): Titan
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: I just recently started playing PO3 Titan mode and wanted to build a grass area, for animals to spawn in, I've built a 15x15 grass area, but there ain't no animals spawning (can't bring them from Landia either, because the mod isn't in the pack in this version of the pack). I'm in a Savanna, but I'm pretty sure that animals can spawn in this biome.

**Comment by Cazadorsniper** [comment]
Give it some time, it takes awhile sometimes.

**Comment by JoelGusto** [comment]
> Give it some time, it takes awhile sometimes.

Alright, as you said, it took awhile, but some spawned, ty!!
