### ISSUE TITLE
Extra cells 4096K fluid drives not working

### ISSUE THREAD

**Issue by jwhunter123** [Cazadorsniper/PO3#1133]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.3.57
**Pack Mode (Normal, Titan, Kappa):**Kappa
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**I set up a bunch of drives filled with 4096k fluid drives from extra cells. The will show up green and the channel will be active. However whenever I go to insert a fluid into the me system it doesn't insert. I think its a problem with Extra Cells because the AE2 64k fluid cells work fine.

**Steps to reproduce:**Set up an ME system with extra cells fluid drives, even if the cells light up green, the system won't store any fluid. But will store it with regular AE2 fluid drives/

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
There is nothing I can do about the EC2 fluid cells.
