### ISSUE TITLE
EnderIO Crafter can become broken switching from Single to Stack option

### ISSUE THREAD

**Issue by Cellidor** [Cazadorsniper/PO3#1134]
3.3.57
Normal Mode
Singleplayer

**Description:**
When switching the EnderIO "Crafter" buffering setting from Single to Stacks and back, if too many items are being sent to the export slot as a result, the crafter will break and be incapable of crafting anything. The Crafter will need to be mined up and self-crafted to reset the whole thing to fix the issue.

**Steps to reproduce:**
1. Place down and EnderIO Crafter
2. Place any storage utility on top of the Crafter (Issue happened both with 2x2 drawer and pulling from another machine directly)
3. Ensure Crafter is powered and both input/output are set to the storage
4. Set up a recipe requiring more than one space, more the better.
5. Select buffer option of "Stacks"
6. Place a large number of the needed items in the storage above
7. Switch back and forth from "Stack" to "Single" buffer option

Result: It seems as if, in attempting to push more than 64 worth of ingredients back to the output slot, that the Crafter will break. Changing the recipe or clearing the storage bins will not help, the Crafter will not craft anything even if moved elsewhere, it can only be fixed by fully re-setting it by self-crafting.

![Crafter](https://user-images.githubusercontent.com/5710572/81526162-dfbc8080-9324-11ea-9c52-acbc394e83c5.png)

**Comment by Cazadorsniper** [comment]
Not able to reproduce this.
