### ISSUE TITLE
ae2 p2p me not working. also no crafting recipe for the other p2p variants

### ISSUE THREAD

**Issue by icywhisker-official** [Cazadorsniper/PO3#1137]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:**

singleplayer version 3.3.57

Applied energistics 2, p2p tunnels do not transfer channels. always say offline. no matter what.

**Comment by hyodocraft** [comment]
Are you powering a P2P network?

> also no crafting recipe for the other p2p variants
You can change the type by clicking on the P2P tunnel with the corresponding item. (duct, conduit, redstone, etc.)
This is the normal procedure. I think you need to learn how to use P2P.

**Comment by icywhisker-official** [comment]
Apologies, I meant to close this. There is no but here. Though I will mention that applying two different power sources to two different ME controllers and then linking the controllers via P2P only will cause massive lag spikes as the system fails to initialize but continues to try every 4 ticks or so.
My initial issue was a PEBKAC error. (Problem exists between keyboard and chair).
