### ISSUE TITLE
Extending Crafting Zoom out?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1140]
Rather simple issue, I was just wondering as to what could be done in JEI to make the preview of certain crafting recipes more accessible, as half the time you don't even know what you're looking at because the bottom of the crafting recipe goes off screen. (Such as some of the Elite Crafting tables recipes, and ALL of the Ultimates)

**Comment by Cazadorsniper** [comment]
Have you tried changing the gui size in the video settings?

**Comment by AnimeNerdDJBROS** [comment]
Worked, thanks.
