### ISSUE TITLE
Bolt or Cast?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1142]
For some reason bolts are possible to be made with a gold / aluminum brass tip. So everytime I'm trying to make an arrow shaft cast it makes a gold / aluminum brass tipped bolt.

So my question is , how do I stop it from turning into a bolt and instead get the cast I need? (I'm trying to make a fiery iron bolt)

**Comment by Cazadorsniper** [comment]
Will be able to use regular minecraft arrows to make the cast next update.
