### ISSUE TITLE
Cannot Eat

### ISSUE THREAD

**Issue by Kevitto** [Cazadorsniper/PO3#1143]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.57
**Pack Mode (Normal, Titan, Kappa):Normal
**Singleplayer, Multiplayer, or LAN?:Multiplayer

**Description:**
For some reason, I cannot get my hunger to go down in any way.  I tried removing all my gear, buffs and talents and reloading the server and client, but I cannot consume Meef Stroganoff to continue in the Twilight forest.  I do not have ability potions active, but I died twice with one, and since then my hunger NEVER goes down, even with the Hunger debuff 5 on.

**Steps to reproduce:**
Fairly complex, too many steps to reproduce.

**Crash log (use pastebin or issue will be closed):**
No crash report.

**Comment by Cazadorsniper** [comment]
Do you have some type of saturation on?

**Comment by hyodocraft** [comment]
LordCraft's Water tier 2 skill ignores the maximum hunger value and continues to restore it. (I have over 1000 /20)
In PO3, it's hard to notice this because it doesn't rain even when it's "raining".
