### ISSUE TITLE
Bucket Duplication bug

### ISSUE THREAD

**Issue by Soul2431** [Cazadorsniper/PO3#1145]
Pack Version: 3.3.57
Pack Mode: Kappa
Singleplayer

Description: When i drink a bucket of milk and have another stack of 2 or more buckets on my hot bar the bucket i just drank stays in my hand and creates a new bucket in the stack of bucket.

Steps to reproduce: get a bucket of milk and 2 other buckets then drink the milk while the 2 other buckets are in your hot bar

Crash log: N.A.

**Comment by Cazadorsniper** [comment]
Don't need the other buckets for this issue to happen.

**Comment by Soul2431** [comment]
okay, I didn't test much with it
