### ISSUE TITLE
Astral/Abyssal Ore Generation

### ISSUE THREAD

**Issue by Hgwells1** [Cazadorsniper/PO3#1146]
**Pack Version:3.3.57
**Pack Mode (Normal, Titan, Kappa):Kappa
**Singleplayer, Multiplayer, or LAN?:Multiplayer

**Description:**
Astral Sorcery Ores/Structures don't generate when playing Skyblock mode, looking at the config it's still pointing at Landia which no longer exists, I have changed this to Twilight dimension for now and will see if this makes any difference.

I can only assume this is the same with Abyssalcraft Coralium Ore which I have been unable to locate in twilight and can't find anywhere in the config file to change this. Currently progressing in the pack is gated behind getting these 2 ores at various stages so makes it pretty much impossible to complete without cheating/altering the world.

**Steps to reproduce:**
Play the pack.
**Crash log (use pastebin or issue will be closed):**
No Crashes just world generation

**Comment by Hgwells1** [comment]
Can confirm that changing to twilight did no difference.

I should also note that I'm running a sponge-forge server.

**Comment by LateNightTic** [comment]
These ores are available in the Deep Dark and Mining Dimension since Landia is no longer available

Specifically Starmetal, Aquamarine, Abyssanite and Coralium

**Comment by Hgwells1** [comment]
That may be true then but you still require coralium to get to the deep dark in order to craft the portal you need unstable ender pearls which use coralium.

**Comment by ManIkWeet** [comment]
When playing Titan mode, the Deep Dark is locked behind 4 octuple compressed cobblestone... Isn't that a bit harsh for getting to Astral Sorcery?

**Comment by Duckapple** [comment]
The current workaround is to scour the overworld to find Astral Sorcery structures on slime islands, and pray that RNG blesses you with 4 aquamarine at some point. It definitely beats out trying to gather 180000000 cobblestone, but still is a really hard gate.
I agree with ManIkWeet
