### ISSUE TITLE
Thorium Ore Generation

### ISSUE THREAD

**Issue by ancientscarab** [Cazadorsniper/PO3#1147]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I am struggling to find Thorium ore, and the people i have asked also have no clue where it spawns. Thanks for the help!
**Steps to reproduce:**
n/a
**Crash log (use pastebin or issue will be closed):**
n/a

**Comment by LateNightTic** [comment]
Thorium spawns in LostCities and MiningWorld dimensions (DIMS 10 and -6) as per the config in COFH
