### ISSUE TITLE
ME System Limit?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1148]
Is it just me or does the ME system max out at 3 ME Drives? [Everytime I place one ME drive close to the controller the furthest one away stops working]

This won't particularly matter once I get to transmutation table with project E , but the ME system SHOULD have some way of having quite a bit of storage right? [I use 1k's since number of item types tend to be the issue, not the number of items in general.]

**Comment by AnimeNerdDJBROS** [comment]
Also if someone has any idea on a possible way to make the ME system recognize in crafting that it only needs one of it , and not like 3000 of it. [Like the Philospher Stone and Master Infusion Stone] 

Would be appreciated.

**Comment by Cazadorsniper** [comment]
Likely exceeded the 8 (or 32) channel limit/

**Comment by AnimeNerdDJBROS** [comment]
Hmm, idk perhaps, any knowledge on the secondary curiosity thing?

**Comment by AnimeNerdDJBROS** [comment]
> Hmm, idk perhaps, any knowledge on the secondary curiosity thing?

Just asking incase, if there's a way to do something that will allow my ME system to be a lot more efficient, I'd rather it to make things easier on things.

**Comment by Cazadorsniper** [comment]
Maybe make sure items like that are always in the ME System.

**Comment by GodlyIdea** [comment]
@AnimeNerdDJBROS
ME should know how to reuse items but in overall it causes long crafting calculation times.
So it should be used only to make couple of items but in long term use crafters and make processing patterns (Without the reusable item (and keep it in the crafter) and I suggest like stack based as it lessens bytes needed to make the craft).

**Comment by AnimeNerdDJBROS** [comment]
Hm, mk. But it didn't work for me and said cannot craft cuz you don't have 3000 philospher stones XD
