### ISSUE TITLE
Fertilised Essence

### ISSUE THREAD

**Issue by HonViddaj** [Cazadorsniper/PO3#115]
**Pack Version:** 
3.0.38
**Description:**
Haven't received any Fertilised Essence in my playthrough at all
**Steps to reproduce:**
Been harvesting Mysticraft crops via Machines, manually, with and without cropsticks. Supposed to be 8% drop rate but have never seen a drop?? Can't find any info on internet and already queried Discord with no response
**Crash log:**

**Comment by bigmaciraq** [comment]
I managed to get it via Emerald plants grown non-agri.  (In a EnderIO farm)  I haven't tested beyond that but perhaps there is a minimum  crop level?

**Comment by HonViddaj** [comment]
Thanks @bigmaciraq i will attempt via the EnderIO farm and test a few different crops. Appreciate your response, given me another direction at least.
