### ISSUE TITLE
Astral Sorcery Structures?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1151]
I'm sorry for the rapid issues here, some of them have tended to be issues I've just spotted normally , but some things have just been done with intent of seeing if anyone else had a fix or something.

In this case I know nothing is broken, but I would like some assistance with just answering a quick question, what's the fastest and easiest way to get astral sorcery structures [One structure had appeared near my start, but ever since I haven't seen ONE] 

Would like to get more knowledge on this matter as it would be helpful, as I kinda need to get all the constellations discovered that I can.

**Comment by AnimeNerdDJBROS** [comment]
Also , I would like to know if the green thumb or increase fertility perks are still in the version of the astral sorcery pack [I would assume not based on the videos I've watched on it having an older looking GUI, but I thought it'd be worth it because breeding without anything would be helpful for certain things]

**Comment by Banno1973** [comment]
Just wanted to add that I have same Astral Sorcery issue. No structures at all to be found. I'm on version 3.3.57 on a Garden of Glass world.

I have scouted Twilight Forest, Lost Cities and The Overworld without finding any. I assume they spawn neither in The Nether or Deep Dark :D 

I'm curious where they are supposed to spawn now that Landia is not in the package.

I have not checked Erebus yet, as I haven't quite gotten there.

**Comment by LateNightTic** [comment]
I don't think any dimension has AS structures as of this current version of the pack, however you can get constellation papers either through crafting in AS (for the Dim and Faded) or through white and green loot bags (for all constellations as you unlock them)

**Comment by hyodocraft** [comment]
in astralsorcery.cfg "S:skySupportedDimensions" and "S:weakSkyRenders", Dim12 was removed and Dim10 was added, but in "S:worldGenWhitelist" it hasn't been done.

**Comment by Banno1973** [comment]
> I don't think any dimension has AS structures as of this current version of the pack, however you can get constellation papers either through crafting in AS (for the Dim and Faded) or through white and green loot bags (for all constellations as you unlock them)

I had a ton of constellation papers in my mob farm barrel wall. I picked one up and got 'Aevitas'. But the rest are just 'blank' - at least, they don't give anything. I'll check out the crafting part later.
Thanks for the reply!

> in astralsorcery.cfg "S:skySupportedDimensions" and "S:weakSkyRenders", Dim12 was removed and Dim10 was added, but in "S:worldGenWhitelist" it hasn't been done

I'm not a config expert, so bear with me :) 
I googled Dim12 and Dim10 and I believe they are Landia and Lost Cities, respectively.
So if Dim10 was added to the "S:worldGenWhitelist" the AS structures should generate?
