### ISSUE TITLE
Mod compatiblity

### ISSUE THREAD

**Issue by EPHGamicon** [Cazadorsniper/PO3#1152]
I tried to put the two mods along with optifine into project ozone 3.

the two mods:

armoryexpansion 1.4.2
conarm- 1.12.2-1.2.5.4

and then tinker's reforged had a conflict. I do want to play the mod pack with tinker's construct armour but I don't know how to fix this
[crash report.txt](https://github.com/Cazadorsniper/PO3/files/4632740/crash.report.txt)

**Comment by hyodocraft** [comment]
reinstall PO3 and play without adding mods

**Comment by EPHGamicon** [comment]
The normal mod pack doesn't have tinker's armor. I'm asking for help on how to solve the compatibility issue like is there an additional mod I need to add to make it work??

Because I've played the mod pack with the **_same additional mods stated above_** before and it worked perfectly fine but with the new versions of the mod pack I can't.
