### ISSUE TITLE
Transmutation Table Troubles?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1153]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer [On and off Lan for when I've been of doing something]

**Description:** I have been grinding for TWO days tryna get enough stuff for the transmutation table of project E [Not including the continuous grind for a while before that for the utlimate crafting table itself [Although mystical agriculture helped] ] 

**Point of that is that after all of this grinding it is , bugged and literally when I try to take it , or shift click it into my inventory, it just bugs out, and the crafting materials go back to the crafting table.**

**Steps to reproduce:** I assume just try crafting transmutation table?

**Crash log (use pastebin or issue will be closed):** [No crash log as it's not that type of bug]

**Comment by AnimeNerdDJBROS** [comment]
[Was Transmutation meant to have been removed or something?] As it seems like that kind of thing?

**Comment by AnimeNerdDJBROS** [comment]
Rather annoying if so , as I spent literally two days grinding for it.

**Comment by AnimeNerdDJBROS** [comment]
[Update: Just tested it in a test world , recipe was still there, but the issue was gone. [Will attempt to troubleshoot now in my main world]

**Comment by AnimeNerdDJBROS** [comment]
**Fixed it on my single player world , but before I close this myself, I would like an explanation as to why this had happened, and if it was meant to be like that?** When crafting the transmutation table, it has the issue I was talking about, literally being unable to craft, unless in creative mode. Only once activating creative mode does it work. [Just curious because at this point idk if its a bug or a feature.

**Comment by AnimeNerdDJBROS** [comment]
**I don't mean like I'm demanding full technical reasons why it did happen or not**  just want to know if it was actually a bug , or if it was intended.

**Comment by AnimeNerdDJBROS** [comment]
I would assume not , since the table is an achievement, but perhaps you planned to limit it for now until you for what ever reason might've tried making the table harder to progress to.

**Comment by Cazadorsniper** [comment]
Have you tried just charging the philosophers' stone?

**Comment by AnimeNerdDJBROS** [comment]
Let me check in a test world if that worked, as it ended up working only in creative in my original experience. [I had troubleshooted a little after making this post]

[Test World: Worked no problem]
[Normal World Test, it worked in survival mode this time, I believe something about going into creative refreshed something or something along those lines. [But no, not the charge being the problem]

**Now I have no reason to keep his open as that response makes it pretty apparent that's not meant to be a thing, but it was just a singular instance that is easily amendable by just poppin in and out of creative.**
