### ISSUE TITLE
Taking a single instance of damage removes all health

### ISSUE THREAD

**Issue by KoningSanderPander** [Cazadorsniper/PO3#1154]
I'm playing on version 3.2.55 Kappa mode.
My friends and I were spamming eachother with TicPlus lasers. After I killed him every instance of damage that we take instantly removes all health and our screen is sideways from the game glitching out and playing the damage effect continuously. /kill doesn't kill us any more and hostile mobs ignore us. The only way to fix it is to use the /heal command. Restarting the server is pointless too.

![2020-05-15_18 28 53](https://user-images.githubusercontent.com/54803741/82074263-ccb9ff80-96da-11ea-8eba-6cfaa4d37772.png)
![2020-05-15_18 29 04](https://user-images.githubusercontent.com/54803741/82074266-cdeb2c80-96da-11ea-9eee-39c468f11abf.png)

**Comment by fedekk2014** [comment]
~~nice map~~

**Comment by Cazadorsniper** [comment]
There is nothing I can do.

**Comment by jonny1102** [comment]
We had this same issue and were able to fix it by deleting the player data file for the affected player on the server. You will lose your inventory, but it does seem to fix this issue.
