### ISSUE TITLE
problem quest

### ISSUE THREAD

**Issue by fedekk2014** [Cazadorsniper/PO3#1156]
Pack Version: 3.3.57
Pack Mode (Normal, Titan, Kappa): Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

I have a problem with Questing because removed completed, I don't know how it loads!

start minecraft, load the game and then "/ bq admin default load" to load
https://i.imgur.com/Uhy8EMy.png
but all reboots completed
https://i.imgur.com/qIqwdCS.png
**Crash log (use pastebin or issue will be closed):**
no crash

**Comment by fedekk2014** [comment]
And another one doesn't work watch this video 
https://youtu.be/n4HUkE-H7x8

**Comment by Cazadorsniper** [comment]
I don't understand the issue.

**Comment by fedekk2014** [comment]
Missions have become a big problem. but it doesn't work load missions

**Comment by Cazadorsniper** [comment]
Reinstall the pack and see if that helps.

**Comment by fedekk2014** [comment]
yes but same :(

**Comment by Cazadorsniper** [comment]
Sorry, I still don't understand the issue.

**Comment by Cazadorsniper** [comment]
Are you saying the quests reset upon using the command?

**Comment by fedekk2014** [comment]
https://youtu.be/F6hoy83dgeI

**Comment by Cazadorsniper** [comment]
Ok now I see, why are you in edit mode? Do /bq_admin edit.

**Comment by fedekk2014** [comment]
edit, to test the completed button but it doesn't work.
https://youtu.be/x8rky61d33I

past worked minecraft launcher version 2.0.700 and now new Launcher no longer worked

**Comment by Cazadorsniper** [comment]
What minecraft launcher are you using?

**Comment by fedekk2014** [comment]
Launcher is 2.1.13827

**Comment by fedekk2014** [comment]
another launcher is already working
SKLAUNCHER (NO PREMIUM): https://skmedix.pl/sklauncher/
Thank you!

**Comment by Cazadorsniper** [comment]
I recommend you buy minecraft at some point.

**Comment by fedekk2014** [comment]
I always play for free

**Comment by Cazadorsniper** [comment]
That is why you can't play modded the normal way. If you like Minecraft, just buy it so you can play it at anytime.

**Comment by fedekk2014** [comment]
Ok, tomorrow I bought minecraft.
