### ISSUE TITLE
Crafting Issue, No other issues on this Github like this.

### ISSUE THREAD

**Issue by therealfox92** [Cazadorsniper/PO3#1159]
I'm not able to craft much. Not a visual glitch, have restarted both server and my pack numerous times. Stuff like drawers will craft, just no upgrades above obsidian. Also, if I switch both over to normal mode, the animation wand calls for Neutral Ingots from Craft Tweaker, but they don't exist in JEI. I've even tried crafting them, but to no avail. Googled this issue, apparently the command /mt reload no longer exists. Also, I searched all the issues on here, before I posted this.
![Capture d](https://user-images.githubusercontent.com/22946481/82110341-31895000-9703-11ea-8c87-b915ea59c03b.PNG)
![Capture s](https://user-images.githubusercontent.com/22946481/82110342-33ebaa00-9703-11ea-9235-7ad2972f1802.PNG)

**Comment by Cazadorsniper** [comment]
Copy the entire scripts folder on the client then paste them on the server's script folder. Restart both server and client afterwards.

**Comment by therealfox92** [comment]
Ok, that worked. Thank you sir. Btw, we do appreciate all your hard work. I never realized how much work this was until I looked at Github and realized you're on here constantly fixing any issues. Thank you for creating great modpacks.
