### ISSUE TITLE
bug with universal cables

### ISSUE THREAD

**Issue by MrFieryPotato** [Cazadorsniper/PO3#1160]
any i belive
normal
all

if you placed enough elite/ultimate universal cables to exceed the integer limit machines will receive negative power

place a cube of ultimate universals and use a thermal machine and watch as waila shows it has weird amounts of rf

idk if this is a issue with the config of the pack or how the mod devs designed it

**Comment by Cazadorsniper** [comment]
Mekanism's Universal Cables have always been kind off buggy, nothing I can do about it really except to tell  you to use a cable that transfers a smaller amount of power.
