### ISSUE TITLE
Spectre Coils

### ISSUE THREAD

**Issue by Pauleen2020** [Cazadorsniper/PO3#1161]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.57**
**Pack Mode (Normal, Titan, Kappa): Normal**
**Singleplayer, Multiplayer, or LAN?: Multiplayer**

**Description: My friend who is playing on our server ran on my computer, can't use power from spectre coils. When he places a spectre coil on a machine, it doesn't transmit power to that machine, when I break the coil, replace it exactly the same way, it then transmits power. Like it has security or somthing on it. Which i'm not sure i did. We're both not an op, we tried oping my friend too and still didn't work.**

**Steps to reproduce: Other player on uses spectre coil like normal, doesn't work, when who made the spectre coils breaks it and replaces it, it works again.**

**Crash log (use pastebin or issue will be closed): None?**

I could produce video evidence if required.

**Comment by Narutoscreed** [comment]
Spectre coil systems are individual, your friend needs to place a second energy injector on your generation system to be able to utilize spectre coils.

**Comment by Cazadorsniper** [comment]
Believe it.
