### ISSUE TITLE
Throwing nether diamond ore in Immersive engineering crusher crashes the game

### ISSUE THREAD

**Issue by XLgaminginc** [Cazadorsniper/PO3#1162]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa mode
**Singleplayer, Multiplayer, or LAN?:** SinglePlayer

**Description:** When I tried throwing 3 pieces of nether diamond ore in my immersive engineering crusher, the game crashed. 
Probably related to https://github.com/Cazadorsniper/PO3/issues/1136.

**Steps to reproduce:**
- Build IE crusher
- Throw in pieces of nether diamond ore
- Crash ensues

**Crash log (use pastebin or issue will be closed):**
[https://pastebin.com/A1P0112y](https://pastebin.com/A1P0112y)

**Comment by Frikkle** [comment]
Possibly related to #1136

**Comment by XLgaminginc** [comment]
It now also crashes on loading the world, resulting in virtually the same crash log, so I can't play in my world anymore. Guess I'll try some mcedit magic to remove the crusher and see if that helps :(

**Comment by Frikkle** [comment]
I ended up placing my backup back, which saved the day
