### ISSUE TITLE
Lexica Botania missing recipe

### ISSUE THREAD

**Issue by loltatoez** [Cazadorsniper/PO3#1166]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
When looking at the lexica botania (In an Akashic Tome, don't know if it is the same outside of it), the recipe for the Terrestrial Agglomeration Plate is missing.
![image](https://user-images.githubusercontent.com/25886582/82133558-b20b8780-97bb-11ea-9dd4-4b69d2f85e03.png)

**Comment by Cazadorsniper** [comment]
Probably because the recipe for it is changed.

**Comment by loltatoez** [comment]
Yeah I know. Just putting it here cause it's a bug.
