### ISSUE TITLE
Issue crafting enderio parts

### ISSUE THREAD

**Issue by Machine-Maker** [Cazadorsniper/PO3#1168]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Some recipes do not work. All players/server have packmode.cfg set correctly.

**Steps to reproduce:** Try crafting EnderIO Fluid Tank, or Energized Bimetal Gear. Was also tried in a vanilla crafting table.

![image](https://user-images.githubusercontent.com/15055071/82136406-acfe0680-97c2-11ea-89ce-2adeecd40b5d.png)
![image](https://user-images.githubusercontent.com/15055071/82136411-be471300-97c2-11ea-8705-fa358c461a21.png)

![image](https://user-images.githubusercontent.com/15055071/82136413-c56e2100-97c2-11ea-90ed-e00e1cc6653b.png)
![image](https://user-images.githubusercontent.com/15055071/82136416-d159e300-97c2-11ea-8e3a-166b6a8dbdb3.png)

**Comment by Cazadorsniper** [comment]
Copy the scripts folder from the client to the server then restart the server.

**Comment by Machine-Maker** [comment]
Yep, Fixed it.
