### ISSUE TITLE
Ghostwood sticks recipe is broken

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Cazadorsniper/PO3#117]
**Pack Version:** 
PO3-3.0.38

**Description:**
Ghostwood sticks recipe is broken. Needed for making arrows for hunting dimension. Also, Tinker's Construct arrows are not accepted in hunting dimension portal block recipe.

**Steps to reproduce:**
1. Use JEI to make Ghostwood sticks
2. Output slot shows regular sticks

**Crash log:**

**Comment by quietust** [comment]
The arrow recipe does not require ghostwood sticks - JEI may suggest ghostwood sticks when you first open the UI, but it should accept _any_ type of stick.
