### ISSUE TITLE
1 FPS

### ISSUE THREAD

**Issue by Guzzy18** [Cazadorsniper/PO3#1170]
Getting 1FPS
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
I have 8gb of ram allocated to this modpack. I just created an auto mob farm and put a drop of evil down. the mob masher kills the mobs. a vacuum hopper takes the items and sorts them in barrels. i have the masher turned off and i'm still getting 1fps. my tick is at 99%. what do i need to do? I'm not very far into the game. I've only been to the hunting dimension. no nether. 
**Steps to reproduce:**
unsure

**Comment by Cazadorsniper** [comment]
Do /cofh killall and see if that helps.

**Comment by Guzzy18** [comment]
So I had to get rid of 50% of the cursed earth and it fixed it. But now it’s happening again. I just made a grass plot to have animals spawn and a farm plot for an essence farm. What could it be this time?

**Comment by Cazadorsniper** [comment]
Idk, since I don't know what your world looks like.

**Comment by Guzzy18** [comment]
Just an FYI, I have to do command /kill @e and the FPS goes back to normal. I have to do it every now and then (every few hours) and it appears to be fine
