### ISSUE TITLE
Inventory gets "reset" to an earlier state every time I load up the world

### ISSUE THREAD

**Issue by Bneboy** [Cazadorsniper/PO3#1171]
Latest version (3.3.57), Singleplayer world, Kappa mode.

Hey, so I have noticed whenever I save and quit, then next time I open it back up, my inventory will be from a much earlier state when I played the map. The map itself is fine, all changes I make on the map are saved, but my inventory keeps getting reset to an earlier state.

To reproduce:
Just save and quit, then exit the game. Next time, it will be reset. Unsure if others will have this problem.

No crash report, not a crash.

**Comment by Cazadorsniper** [comment]
I've seen this a couple of times and don't know the cause of it.

**Comment by bloodscon** [comment]
have you tried putting a chest down emptying all your items into the chest then log out to see if you end up with a reset inventory also check you save files are not locked/ read only for the entire save file folder (goto minecraft instance folder find the mod pack and look for the save directory right click on the save folder and look to see if attributes are set to read only
