### ISSUE TITLE
Landia is mentioned in the newest version of the pack

### ISSUE THREAD

**Issue by jonas8217** [Cazadorsniper/PO3#1172]
Pack Version: 3.3.57
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description:
Landia is mentioned both in the aquamarine and the astral sorcery structures quest.
![javaw_YFXRQkINki](https://user-images.githubusercontent.com/28251769/82196275-c786cb80-98f9-11ea-94d2-b6d5ece13564.png)
![javaw_9SUf1FLddg](https://user-images.githubusercontent.com/28251769/82196266-c5bd0800-98f9-11ea-84bd-947886eb1760.png)

**Comment by Cazadorsniper** [comment]
Landia is definitely not mentioned in 3.3.58.
