### ISSUE TITLE
Item Translocators not working with drawer controller

### ISSUE THREAD

**Issue by Kacyqui** [Cazadorsniper/PO3#1173]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer/LAN

**Description:** I can't use item translocators from any kind of storage to a drawer controller if the drawer attached to the controller have void upgrade in it. Already tried other methods of item transportation but they can't keep up.

**Crash log (use pastebin or issue will be closed):** none

**Comment by Cazadorsniper** [comment]
Have 1 empty drawer.
