### ISSUE TITLE
Tinkers' Complement Duplication Glitch

### ISSUE THREAD

**Issue by hp3721** [Cazadorsniper/PO3#1174]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Titan
**Singleplayer, Multiplayer, or LAN?:** LAN

**Description:**
Using Tinkers' Complement Sledge Hammer along with the direct modifier to duplicate certain blocks.

**Steps to reproduce:**

1. Create a Tinkers' Complement Sledge Hammer.
2. Apply the direct modifier.
3. Place a block that is affected by Ex Nihilo's hammers. (ex: cobblestone)
4. Break block with the sledge hammer which gives the player both the original block (ex: cobblestone) and the resulting block (ex: gravel).

**Comment by Caedis** [comment]
#204 was opened, but closed without explaination

**Comment by Cazadorsniper** [comment]
Its just sand, gravel. dust, endstone and netherrack. I'm not too worried about it.

**Comment by hp3721** [comment]
Alright
