### ISSUE TITLE
kappa crafting

### ISSUE THREAD

**Issue by danidude55** [Cazadorsniper/PO3#1175]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
when joining a new server any kappa recipes will still be displayed and when attempted to be crafted they will not work but the vanilla recipes cannot be recovered

**Comment by Caedis** [comment]
Make sure that both the Server and the Client are set to kappa mode
