### ISSUE TITLE
Consider adding empowerer recipes to extended crafting

### ISSUE THREAD

**Issue by Jaymus3** [Cazadorsniper/PO3#1176]
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
N/a
**Description:**
The capacitor recipes are a unique addition to this pack, but there aren't any great solutions available for mass production later on besides multi-threading lots of empowerers.  Adding the capacitor recipes at least to the combination crafting would make wanting a decent sized ME system not devolve into building 50 empowerer arrays.  You could make the combination crafting stuff more expensive if you wanted to make sure it was a costly option, and amp up the energy consumption considerably.  I've attached a modified file where I tweaked in the capacitor recipes, but these use the energy costs found in the Actually Additions config.  Thanks for your consideration.
[combination.txt](https://github.com/Cazadorsniper/PO3/files/4648476/combination.txt)

**Steps to reproduce:**
See above.
**Crash log (use pastebin or issue will be closed):**
No crash.

**Comment by Caedis** [comment]
BTW, latest updated has a Mechanical Empowerer (modular machines) to help with all of the caps.
