### ISSUE TITLE
Server Login Crash issue

### ISSUE THREAD

**Issue by Alpodip** [Cazadorsniper/PO3#1177]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.357
**Pack Mode (Normal, Titan, Kappa):**
Server
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
i start server but i cant login
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/bG2U4Y6k

**Comment by Cazadorsniper** [comment]
Maybe be possible that your connection to the server is being blocked by windows firewall or anti-virus software. Try whitelisting Minecraft so it won't be blocked.

**Comment by Alpodip** [comment]
normal mode is working. when i try change the kappa mode i take this error. i can join if start server-side and client-side both of normal mode

**Comment by Cazadorsniper** [comment]
Is the server and client on kappa mode?

**Comment by Alpodip** [comment]
now both of them are in normal mode. if both of them get kappa mode or titan mode i get this error

**Comment by Cazadorsniper** [comment]
Are you restarting both the client and server when you change the packmode?

**Comment by Alpodip** [comment]
yes 2-3 times

**Comment by ExtinctInsanity** [comment]
I'm getting the same issue. Just crashes when trying to connect to the multiplayer server. Mine is getting a "Faulty Registry Values" and "faulty crafting recipe and config" errors. Even doing single player through the twitch app I get the same errors on the screen after getting kicked from server.
