### ISSUE TITLE
Mob spawner in coralium infested swamp not staying loaded with chunk loader

### ISSUE THREAD

**Issue by Wernerdeschryver** [Cazadorsniper/PO3#1178]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** I set up a 2nd mob spawner in a coralium infested swamp for anti bones. I'm using cursed earth with extreme vector plates to push them into a mob masher. Then I'm using an advanced item collector on an enderchest to pick up the drops. I pull out of the enderchest at my base into a barrel system. The 2 enderchests are about 360~ blocks apart in the overworld. When I'm close to the spawner it works perfectly, but when I'm at the base there are no drops coming in. I have a ChickenChunks chunk loader set up but it apparantly isn't working. All my other chunkloaders work as expected. My base is loaded in as well. I used /chunkloaders to check the loaded chunks with the tool and it says the chunkloader is working on there. I tried using spot loaders instead but no changes. I don't know if there is a weird bug with the biome not being able to be loaded by a chunk loader, or if it actually requires a player nearby to spawn anything at all. I tried reinstalling the pack already but nothing changed. I placed a cobblestone generator on top of the spawner pushing into the same enderchest just to see if it would work, and it did even without a chunk loader there.

**Steps to reproduce:** Load singleplayer world & check if mob spawner is spawning mobs and drops are going into enderchest. Go back to base and check enderchest there. The previous drops will be pulled out but no new ones will show up (likely due to chunk loader not keeping the chunk loaded)

**Crash log (use pastebin or issue will be closed):** No crash

**Comment by Cazadorsniper** [comment]
What type of mob spawner?

**Comment by Wernerdeschryver** [comment]
Just a cobblestone cube with cursed earth as the floor, vector plates pushing into a mob masher

**Comment by Cazadorsniper** [comment]
Do you have any other mob spawners?

**Comment by Wernerdeschryver** [comment]
Yes, exact same setup but not in a coralium infested swamp. Works perfectly. It's a little closer to the base and at a lower Y level.
I've tried enabling the chunk loading option in ftbutilities.cfg but same problem. The mobs just won't spawn there if I'm too far away for some reason.

**Comment by Cazadorsniper** [comment]
Maybe hitting minecrafts mob count cap I guess, try making an actual spawner for the mob you're looking for using apotheosis, enderio, Industrial foregoing, or Draconic Evolution.

**Comment by Wernerdeschryver** [comment]
Alright, anyways I've also noticed the mob drops are going up slowly when I've been in different dimensions for a long time, so don't know what's up with that. Thanks for replying !
