### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by mortenh1234** [Cazadorsniper/PO3#1179]
**Pack Version:** 3.3.5.7
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I cannot make the level type botania-skyblock, no matter what i try i always get the same result, a randomly generated default map

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Are you starting the server using forge?

**Comment by mortenh1234** [comment]
I didnt know i could do that, never said anything about loading a world when trying to open it using forge

**Comment by Cazadorsniper** [comment]
Mods won't work without forge.

**Comment by mortenh1234** [comment]
starting it with the forge jar file doesn't seem to work

**Comment by Cazadorsniper** [comment]
That is the correct one.
