### ISSUE TITLE
Breaking multiple blocks of the same type does not work

### ISSUE THREAD

**Issue by naxhh** [Cazadorsniper/PO3#118]
**Pack Version:**
3.0.38

**Description:**
This may seem stupid, but I saw a few youtube plays and all of them are able to break a full tree only breaking a block. In my case that doesn't work, with tree or any other block.

Is that intended?

**Steps to reproduce:**
Create a new world as "Garden of glass"
Claim first reward
Plant tree
Punch tree

**Crash log:**
No crash

**Comment by mirawu1** [comment]
Check for the  "Ore Excavate" key bind in the controls menu.
