### ISSUE TITLE
Phytonic Insolator not accepting fluix seed

### ISSUE THREAD

**Issue by Spit1989** [Cazadorsniper/PO3#1181]
Pack Version: PO3 Version: 3.3.57
Pack Mode (Normal, Titan, Kappa): Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description:
Thermal Expansion Phytogenic Insolator not accepting fluix seeds.
Glowstone dust + Fluix Seed (0%) = Pure Fluix Crystal   recipe not working.

Tried it in creative ... same problem.

Is this an intended change or a bug? i read the latest changes and couldnt find sth. about it.

**Comment by Alpodip** [comment]
you should use to grow accelertion

**Comment by Cazadorsniper** [comment]
Best to use the Crystal Growth Chamber.
