### ISSUE TITLE
Server Corrupting Game Modpack.  <1FPS in server before getting kicked and crashing the game if in single player

### ISSUE THREAD

**Issue by Pooker120** [Cazadorsniper/PO3#1183]
# Use the search function before reporting to see if the issue has been reported before.
**3.3.57:**
**Normal**
**Multiplayer and Singleplayer:**

**While playing my game dropped to <1FPS and after a couple of minutes I was kicked from the private multiplayer server I play on.  Every time I logged back in I would continue to have <1FPS and be kicked again in a couple of minutes.  If I tried to open a single player world the game would then crash.  I tried deleting the mod pack and installing it fresh and deleting my launcher (curseforge or twitch whatever name is the correct one) and installing it fresh.  But the problem persisted.  I did find out that if I opened a single player world first it would work just fine, but after attempting to play on the server and being kicked opening that same single player world or starting a new one would crash the game.  The server team have no idea what is wrong and their only answer is that the crash report seems to be do to the mod RFTools Dimensions trying to generate chunks.  The server has 6gb of ram and was running just fine before hand and I have 8gb ram dedicated while playing the mod pack.  I will attach the crash reports and my communications with the server team. 
 If you have any ideas please let us know.  At this point if it happens to the other players we are just going to load up the most recent back up before the issue but knowing can help prevent the problem encase it happens again.**

**No idea how to reproduce the issue all I know is that we were having some weird power brown outs despite being able to produce enough power for everything and I was just experimenting with extra cells 2 and the fluid interface attached to a magma crucible and a fluid crafter (the block with green crafting grid on all of its sides) when the issue first started.**

[server_crash.txt](https://github.com/Cazadorsniper/PO3/files/4660007/server_crash.txt)
[single_player_crash.txt](https://github.com/Cazadorsniper/PO3/files/4660011/single_player_crash.txt)
[Server chat window of me being kicked..txt](https://github.com/Cazadorsniper/PO3/files/4660012/Server.chat.window.of.me.being.kicked.txt)

**Comment by Cazadorsniper** [comment]
The Brown outs is likely what caused the issue and I recommend going ahead to use the back up before the brown outs happened.

**Comment by Pooker120** [comment]
Thank you and I will get the pastebin link up prompto.

**Comment by Pooker120** [comment]
Severcrash link: https://pastebin.com/RcXbTciz

**Comment by Pooker120** [comment]
Single Player Crash Report link: https://pastebin.com/bXXcnaTP

**Comment by Pooker120** [comment]
Okay so another oddity is every other player is just fine.  It is just my account that is causing the issues.  Just had another player on and they were just fine even while I had 0 fps and was kicked.

**Comment by Pooker120** [comment]
Okay it just fixed itself.  And I have know clue why.  RF was already unpowered by another player and I was still experiencing the issue but after logging in a third time to dry to hotkey drop my inventory it fixed itself.

**Comment by Cazadorsniper** [comment]
lol

**Comment by Cazadorsniper** [comment]
The server crash has something to do with ProjectE other than that I don't know.

**Comment by Pooker120** [comment]
That makes some sense.  Found out while playing that EMC and ProjectE tablet items are saved on the client side (Goodbye my billions upon billions of EMC).  Also found out that if projectE is hooked up to the ME system and you manage to remove enough items at once (did this by removing the 15 octocompressed cobble) and/or put them back in, it seriously lags the game.  Probably because the ME system just lost every item from related to EMC or gained them back.  This would explain why the brown outs caused the massive lag and why it initially only effected me because it was my EMC system that was hooked up the ME system.  After another player got in and temporally solved the brown out my account after a few logins would be able to catch up and get through the lag and there by fixed itself.  I am not a hundred percent sure if this is what caused the issue but it is my best guess so far.  Though it still doesn't explain screwing up any single player world on the same pack that I would try to start.
