### ISSUE TITLE
Problem with Luminous Crafting Table

### ISSUE THREAD

**Issue by SentakuTetsuya** [Cazadorsniper/PO3#1185]
Pack Version: 3.3.57
Pack Mode (Kappa)
Multiplayer: Own Server

Description:
Can't Craft any Astral Sorcery recipe in the Luminous Crafting Table

![1](https://user-images.githubusercontent.com/65720168/82569742-f2368580-9b80-11ea-9b51-9d03d107cb97.png)
![2](https://user-images.githubusercontent.com/65720168/82569746-f2cf1c00-9b80-11ea-8559-504a9727f781.png)
![3](https://user-images.githubusercontent.com/65720168/82569747-f367b280-9b80-11ea-95bf-67287ba09aad.png)

**Comment by Caedis** [comment]
Wait for night for more star light

**Comment by SentakuTetsuya** [comment]
> Wait for night for more star light

Does not work.

**Comment by Caedis** [comment]
Can you post a higher resolution picture?

**Comment by SentakuTetsuya** [comment]
> Can you post a higher resolution picture?

of what exactly? There is missing the end product.... i think it's a problem in the recipes. but i don't know how to fix it.

**Comment by Caedis** [comment]
The recipe is the default one for the lightwell, so the issue isnt with the pack.  

Here are a few things to try:

1. If you have flight, craft an angel block and go way up in the sky at night. Place the angel block and the altar on it and try the recipe again.
2. If you dont have flight, you can nix the angel block and just pillar up with everything on you. Try the recipe again much higher (more star light the higher you are).

**Comment by SentakuTetsuya** [comment]
Build at y height 127
![](https://puu.sh/FNb3F/988a78c598.png)
Recipe from JEI
![](https://puu.sh/FNb5o/8698c64e15.png)
Recipe in Luminous Crafting Table with missing end product on the right
Right clicking with resonanting wand: nothing!
Shift+Right click: nothing
![](https://puu.sh/FNb8b/801288d3c7.png)
Quest line Nu
![](https://puu.sh/FNbbd/b2bd6ab906.png)
Astral Sorcery Advancements
![](https://puu.sh/FNbcp/a6e004e2e6.png)

**Comment by Caedis** [comment]
Thanks for the high res and plentiful screenshots. I am logging onto my local server now

**Comment by Caedis** [comment]
Weird, I was able to get mine to show up. 
![2020-05-21_13 57 24](https://user-images.githubusercontent.com/18713839/82595437-2d2dbe80-9b6b-11ea-909f-aa90d1972eaf.png)

**Comment by SentakuTetsuya** [comment]
right i have an issue with the recipe maybe.... or do i have to do anything else before it shows the lightwell?

**Comment by Caedis** [comment]
I think I know the issue, checking into it real quick (wth did i close my client)

**Comment by SentakuTetsuya** [comment]
same problem on laptop too!

**Comment by Caedis** [comment]
Humor me, and try crafting another lumin altar using a normal crafting table

**Comment by Caedis** [comment]
Be sure to watch the server's console/log while doing that

**Comment by SentakuTetsuya** [comment]
Crafting in normal crafting table gives "Exploration"
Now i can see the well....
![](https://puu.sh/FNbTi/6db09c26e3.png)
![](https://puu.sh/FNbV5/d5558e4ca1.png)

**Comment by Caedis** [comment]
Bingo, I think the tinker's crafting station doesnt cause the correct event to trigger which AS is hooked into to look for to unlock that part.

**Comment by SentakuTetsuya** [comment]
Thank you a lot!

**Comment by Caedis** [comment]
No problem, gave me an excuse to look in AS's code.  
[Here is where you unlock the ability to make the lightwell](https://github.com/HellFirePvP/AstralSorcery/blob/12162429a92f5a44f4a6b8cf8c01df4008e9b56c/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchManager.java#L733)
