### ISSUE TITLE
invar bug has returned

### ISSUE THREAD

**Issue by wolfielove1992** [Cazadorsniper/PO3#1187]
version 3.3.57
normal mode
singleplayer

I currently have a large supply of invar in my smeltery but i cannot pour into anything but a bucket or a barrel but cant casting basins seems like it was converted to the fluid only form cause it presented as buckets and milibuckets permanently and will only pour into fluid containers.
also names of invar items are messed up see images
![2020-05-21_16 38 24_3](https://user-images.githubusercontent.com/61435631/82608682-1eee9b00-9b89-11ea-83f3-2a705bc968d1.png)
![invar name mess up](https://user-images.githubusercontent.com/61435631/82608683-1eee9b00-9b89-11ea-914d-b4c86ffaffa0.png)

invar-bug
constantin-pass
brass-pass
bronze-pass
electrum-pass

normal ores
platnium-bug
aluminum-bug
iridium-bug
just put iron and nickel into the smeltery

no crash log

**Comment by wolfielove1992** [comment]
![2020-05-21_16 38 24_3](https://user-images.githubusercontent.com/61435631/82607015-0b8e0080-9b86-11ea-95ae-5fee61ba233e.png)

**Comment by Caedis** [comment]
This is fixed in the latest version of Tinkers' Reforged. Either update the mod manually, or wait for the next pack update.

**Comment by wolfielove1992** [comment]
i dont know how to manually do it
