### ISSUE TITLE
Crashing while trying to connect to server (multiplayer & singleplayer)

### ISSUE THREAD

**Issue by ExtinctInsanity** [Cazadorsniper/PO3#1188]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**

**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer and single player
**Description:**
Crashes when logging into server.
I get the error: "Fatally missing registry entries" try relogging without restarting I get another error when trying to connect again: 
"Internal Exception: com.google.common.util.concurrent.UncheckedExcecution: java.lang.IllegalStateException: Recipe minecraft:wheat (net.minecraft.item.crafting.ShapedRecipes@309ac89e) produces unregistered item minecraft:wheat (net.minecraft.item.Item@524b1e41
**Steps to reproduce:**
Just tried to log in. I restarted the server and client several times and the same thing happend
**Crash log (use pastebin or issue will be closed):**
Including all three logs of my client and server.
Client "Crash" Log:
https://pastebin.com/BMUqCS2B
Server "Debug" Log: File too bit for pastebin
[debug.log](https://github.com/Cazadorsniper/PO3/files/4664741/debug.log)
Server "Latest" Log: File too bit for pastebin
[latest.log](https://github.com/Cazadorsniper/PO3/files/4664747/latest.log)

**Comment by Cazadorsniper** [comment]
Server and Client must have the same scripts/configs.

**Comment by ExtinctInsanity** [comment]
Ok, my bad though I had done that so I fixed the config/scripts issue for both client and server. I was able to get a singleplayer but multiplayer just get's "Timed Out" and the server closes. I have 10GB ram dedicated to the server and 8GB dedicated to the client.

**Comment by ExtinctInsanity** [comment]
Ok, my bad though I had done that so I fixed the config/scripts issue for both client and server. I was able to get a singleplayer but multiplayer just get's "Timed Out" and the server closes. I have 10GB ram dedicated to the server and 8GB dedicated to the client.
 

    On Thursday, May 21, 2020, 03:25:02 PM PDT, Cazadorsniper <notifications@github.com> wrote:  
 
 


Server and Client must have the same scripts/configs.

**Comment by Cazadorsniper** [comment]
Put the log here: https://gist.github.com/
