### ISSUE TITLE
Teleport to the overworld while accidentally moving the mouse and crash

### ISSUE THREAD

**Issue by mirawu1** [Cazadorsniper/PO3#119]
**Pack Version: **  3.0.38

**Description:** Teleport back to the overworld while accidentally moving the mouse and crash.
Chunks loaded by FTB utilities.

**Steps to reproduce:**Teleport to another dimension then teleport back to the overworld and move the mouse.

**Crash log:** https://pastebin.com/AJxtRa47

**Comment by mirawu1** [comment]
**Update:** https://pastebin.com/7EAGV3Tg

**Comment by Cazadorsniper** [comment]
This has to do with the sound mufflers, just need to remove them then you can enter your world.

**Comment by mirawu1** [comment]
There are no sound mufflers in my world.

**Comment by mirawu1** [comment]
If you want to look at my world.

https://mega.nz/#F!Cc9EXQ4C!Hp5c7eeFs2c8TC5slSxhww

**Comment by Cazadorsniper** [comment]
Block coordinates: World: (-641,84,-1213),

**Comment by Cazadorsniper** [comment]
Whatever block that is, is what is causing the error.

In forge.cfg try turning "# Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES. B:removeErroringTileEntities=false"

to true, load world then turn it back to false.

**Comment by tommyyx** [comment]
I am getting the same crashes related to sound mufflers whenever my world finishes loading.

Had to disable sound mufflers inside the extra utilities 2 config file to be able to enter my world again.

My crash log for reference: https://gist.github.com/tommyyx/19b90f614335203fbdf294edd637fd04

**Comment by mirawu1** [comment]
When the game crashed I moved the character between dimensions by mcedit it was around 8 times and now the game working without any problems.
I checked the coordinates (-641,84,-1213) and there was one cobblestone block(chiselled) from 0 to 255.

![2019-03-10_12 31 18](https://user-images.githubusercontent.com/48353311/54084464-30a3a400-4331-11e9-91b2-1a8ed0682af7.png)
