### ISSUE TITLE
Induction smelter recipe

### ISSUE THREAD

**Issue by ayabar91** [Cazadorsniper/PO3#1190]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.57
**Pack Mode (Normal, Titan, Kappa): Kappa
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description:**
When trying to do the recipes of rich slag using sand and compass or clock, the induction is not letting put the compass/clock in the slot even tho JEI clearly states that this recipe is valid.

**Steps to reproduce:**
Get an induction Smelter and try to put sand and clock/compass to get 4 iron ingot and rich slag

**Comment by Cazadorsniper** [comment]
Is the induction smelter slot locked? There is a button in the GUI that should unlock it if that is the problem.

**Comment by ayabar91** [comment]
The recipe doesn't work with or without the slot being locked

**Comment by Cazadorsniper** [comment]
NBT data was keeping the recipe from working, probably fixed next update.

**Comment by pigalot** [comment]
This fix breaks the recipe if the clock or compass didn't come from the players inventory (ie crafter piping into induction smelter), would suggest reverting the recipe and disabling all "Compasses work everywhere" options in quark.cfg

**Comment by Cazadorsniper** [comment]
Did my own fix.
