### ISSUE TITLE
Server crashing after playing for a minute or so.

### ISSUE THREAD

**Issue by TheeHeckler** [Cazadorsniper/PO3#1192]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** The night before, I had updated my server from version 3.3.55 to 3.3.57. Some friends and I played for a few hours and got off. The next day, when I ran the server, it started crashing after a few minutes of being on.

**Steps to reproduce:** Just log in and wait.

**Crash log (use pastebin or issue will be closed):**
[https://pastebin.com/9j5LGenH](url)

**Comment by Cazadorsniper** [comment]
According to that crash some type of Thermal Dynamic energy ducts and actually addition energy relay are causing this to happen. In server.properties set max-tick-time=-1.

**Comment by TheeHeckler** [comment]
Thanks, it worked :)
