### ISSUE TITLE
Electrotine not generated in the Auto Sieve

### ISSUE THREAD

**Issue by LogicFalls** [Cazadorsniper/PO3#1193]
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Description:**
Electrotine does not appear in the list of outputs when Sand is put through the multiblock Auto Sieve. This is incongruous with the other Auto Sieve recipes, which all fully represent their Ex Nihilo Creatio sieve counterparts.

**Comment by LogicFalls** [comment]
Addendum: Aluminum ore pieces are not produced by the auto sieve at all, regardless of input.

**Comment by Cazadorsniper** [comment]
Fixed that too but only for sand and gravel. Dust already has hit max capacity I believe.
