### ISSUE TITLE
Dark and Light Lord Craft Benefits?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1195]
Not precisely a Project Ozone 3 problem but it has involvement.
I am wondering as to why only the four first natures are stated in the skills and abilities tab, and is there any way to read up on the benefits of Corruption or Calm for Light OR Shadow or Void for Dark?

**Comment by Cazadorsniper** [comment]
Will need to ask the Developer of the mod for that.

**Comment by AnimeNerdDJBROS** [comment]
Ah, mk I just opened this up to see if anyone else had anything they knew about in regards to that.
