### ISSUE TITLE
Project Ex? 

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1196]
Doesn't ProjectEx seem rather irrelevant for the pack as it stands? Most of projectEx has been removed aside from EMC links, EMC links can't be used without collectors , so unless I'm missing something the only things from project EX that aren't disabled are the matters and the links which are both useless.

Mid writing test: I noticed items linked with EMC can be piped into a personal EMC link into your EMC value, making it worth something, but why I'm still doing this , is what does the matter do aside from just presenting a tedious step [Which isn't even difficult , just tedious as it can be automated]  to completing the modpack?

**Comment by Cazadorsniper** [comment]
The mod will not be removed that is all I will say.
