### ISSUE TITLE
Landia / Coralium Ore

### ISSUE THREAD

**Issue by Syclone81** [Cazadorsniper/PO3#1198]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.56 and Higher
**Pack Mode (Normal, Titan, Kappa):**
Kappa Mode
**Singleplayer, Multiplayer, or LAN?:**
Single

**Description:**
In 3.2.55 you removed Landia aka Land Craft mod. I search in Twigligh for Coralium Ore after 10h of mining, i can not find one of the Coralium Ore. The discription in Omnicron and the Quest from Coralium Ore "can be found in Landia". I can not find a way into Landia after this change
You removed the mod, there is no Landia anymore. 3.3.58A have no way into Landia, with the pack changes at 3.3.56 are the Landia Portal Marker missing. So no Landium Ore in Nether or a Landia Portal Marker.

There is no way to get Coralium Ore. I start a new Map with 3.3.56 and yeah. there is not realy a way.

I have Dimensions aktiv:
Nether / End / Farm Dimension / Twighlight

Dimensions i miss:
Deep Dark => no Coralium to make a Coralium Pearl
Abyssal Portal => missing Thoirum for the Gaean Keystone
The Lost Cities => i used 2 diamond block or 2 Block of Lava Crystals under the bed + 6 skell-heads arround - no teleport into dimension ok i check the wiki. need 2 Emerald blocks. Lambda => Lost Cities Dimension has wrong blocks and discription. you need 2 Emerald blocks and a right click.
https://rlcraft.fandom.com/wiki/The_Lost_Cities_(Dimension)
edit: yes its right. need 2 blocks of Lava Crystals under the bed

**Steps to reproduce:**
search in NEI Landium Ore | Landium | Landia Portal Marker | @landcraft or @land

**Crash log (use pastebin or issue will be closed):**

**Comment by Caedis** [comment]
Lost Cities is working fine for me. It uses 2 blocks of Lava Crystals.
Also in 3.3.58A, the quest texts were updated to point you to Lost Cities (where its been since LandCraft has been removed)

Example:  
![2020-05-24_02 48 54](https://user-images.githubusercontent.com/18713839/82748619-371d1080-9d69-11ea-952a-7665a592f8c4.png)

Then you get on and right click the bed (may take a couple of clicks to get right)

**Comment by Syclone81** [comment]
yes i checked it. it works with the 2 lava crystal blocks. so i get thorium / coralium now

but the descriptions are wrong in the quest line

**Comment by Caedis** [comment]
They were corrected in the latest update (make sure you run "/bq_admin default load" as that is what updates the quests)

**Comment by Syclone81** [comment]
Lost Cities Deimension quest description can be better ;)
with a info how to build the portal and the right click on the bed
