### ISSUE TITLE
Server crashed and can't start server

### ISSUE THREAD

**Issue by feralind** [Cazadorsniper/PO3#1199]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
After landing on the moon for about 30 mins and wandering around the server straight up crashed the server. The server only has 2 players, my friend was at spawn (base) setting up new ME setup 
We cannot start it back up since every time it starts preparing spawn, it stops at 46% and gives out this error: "Encountered an unexpected exception
java.util.ConcurrentModificationException: null"

**Steps to reproduce:**

**Crash log (use Pastebin or issue will be closed):**
Here's the crash log: https://pastebin.com/1kyQ9fPg
And Server "lastest" log: 
[2020-05-24-7.log.gz](https://github.com/Cazadorsniper/PO3/files/4673187/2020-05-24-7.log.gz)

**Comment by Cazadorsniper** [comment]
Can I have the latest.log?

**Comment by feralind** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/4673567/latest.log)
@Cazadorsniper here sir

**Comment by valtilion** [comment]
Here you go:

[latest.log](https://github.com/Cazadorsniper/PO3/files/4673571/latest.log)

**Comment by Cazadorsniper** [comment]
In the forge.cfg there is a setting to make erroring TileEntities to disappear, turn that on (probably entities too) and see about updating the pack.

**Comment by feralind** [comment]
@Cazadorsniper Sill crash 
![image](https://user-images.githubusercontent.com/65848602/82767576-784f0800-9ddd-11ea-8dd5-9a2bba9bae8f.png)

![image](https://user-images.githubusercontent.com/65848602/82767598-9f0d3e80-9ddd-11ea-9898-ecfa3179df1e.png)

**Comment by Cazadorsniper** [comment]
Maybe updating galacticraft will work.

**Comment by feralind** [comment]
Did update to the latest patch but still crash as usual

**Comment by Cazadorsniper** [comment]
So you updated it to 4.0.2.280?

**Comment by feralind** [comment]
The latest modpack patch i meant

**Comment by Cazadorsniper** [comment]
I'm talking about Galacticraft specifically.

**Comment by feralind** [comment]
Still crash after update

**Comment by feralind** [comment]
@Cazadorsniper I found out what causes the server crash there were 2 problem that's the entities caused it and map seed if I go too far off the skyblock (spawn) it will generate the entire new world "normal world". The first crash caused because I was on the moon same coordinate of the new biome spawn on the overworld. Apparently it the biomes crash only spawn west and eat not north and south. 
![image](https://user-images.githubusercontent.com/65848602/82815521-3316ee80-9e4e-11ea-85c3-c3f893abd263.png)

**Comment by Cazadorsniper** [comment]
In server.properties is the level type botania-skyblock? May need to use a backup of the world.
