### ISSUE TITLE
RiteClick mod disabled

### ISSUE THREAD

**Issue by Nerlis** [Cazadorsniper/PO3#12]
**Pack Version:**

3.0.38

**Description:**

Can not right click on dirt or grass to get pebbles at start of pack.

**Steps to reproduce:**

I uninstalled and reinstalled Minecraft and the mod.

**Crash log:**

**Comment by gsoxreptile** [comment]
everyone else can do it just fine... so i dont know what would be the problem other then the version your running

**Comment by Schildos** [comment]
Sounds like a stupid question but.. did you try sneaking while right clicking? (Your statement isn't that clear there..

**Comment by Nerlis** [comment]
It would only be a stupid question if it weren't true.  🙄

Thank you for taking the time to reply!
