### ISSUE TITLE
Extra planets creeper bosses invisible and unkillable

### ISSUE THREAD

**Issue by naseem142** [Cazadorsniper/PO3#120]
**Pack Version:**
3.0.38

**Description:**
Upon entering any boss room on Extra Planet's planets, the creeper boss type is invisible and there is no way to kill it. I tried deflecting back TNT, dropping it into the void, blowing up the room with TNT.
I'm not sure if this issue is related to "Extra planets creeper bosses make screen go black", but that does happen too which you guys are aware of, but it's not the only issue apparently.

Image: https://i.imgur.com/MKpRRlD.png
(In creative mode momentarily so it stops attacking)

**Steps to reproduce:**
1. Enter boss room.
2. Boss Creeper type spawns invisible.

**Crash log:**
Not crashing

**Comment by jamaa** [comment]
I also experienced this, with the addition of the screen going completely black intermittently. I was able to kill it nonetheless, though.

**Comment by naseem142** [comment]
> I also experienced this, with the addition of the screen going completely black intermittently. I was able to kill it nonetheless, though.

it's a problem that i can't kill it though, since spawning in a key wont yield loot into the chest so i just directly spawn schematics which is kinda lame.
