### ISSUE TITLE
Modularium

### ISSUE THREAD

**Issue by WonkyWombat** [Cazadorsniper/PO3#1201]
**Pack Version:**
3.3.58A

**Pack Mode (Normal, Titan, Kappa):**
Kappa

**Singleplayer, Multiplayer, or LAN?:**
Single Player

**Description:**
Modularium has been added so we can craft the mechanical empowerer, the recipe in JEI states its 2 lead ingots, 3 cobalt ingots, 3 redstone and 1 glowstone dust and can be crafted in an ordinary crafting table. Adding these to a crafting table produces nothing.

**Steps to reproduce:**
Add 2 lead ingots, 3 cobalt ingots, 3 redstone and 1 glowstone to a crafting table.
L C L
C R C
R Y R

**Crash log (use pastebin or issue will be closed):**
N/A

![crafting](https://user-images.githubusercontent.com/65854479/82753725-cbb25d80-9dbf-11ea-87ff-dfdeec56ae68.jpg)
![Recipe](https://user-images.githubusercontent.com/65854479/82753727-cce38a80-9dbf-11ea-9b22-5db7b08e313e.jpg)

**Comment by WonkyWombat** [comment]
Just found that the vivid alloy recipe has been changed to 1 ender pearl + 1 energetic silver ingot in an alloy smelter and this also produces nothing.

have I messed up my server installation?

**Comment by LateNightTic** [comment]
Check your packmode.cfg file to ensure that you are actually running Kappa mode on both your server and clients

**Comment by WonkyWombat** [comment]
Changed the servers packmode but forgot to change the client. doh!
Thanks for the help!
