### ISSUE TITLE
Transmutation Table Crafting Issue [Kappa]

### ISSUE THREAD

**Issue by designandbuld** [Cazadorsniper/PO3#1202]
# Use the search function before reporting to see if the issue has been reported before.
3.3.58A
Kappa
Single Player

**Description:**
Transmutation Table recipe won't let me pull the item from the from the ultimate crafting table. It appears to not be syncing properly. If I shift click, the table shows up in my inventory momentarily. It will then re-sync to not being crafted, but the items are still in the ultimate crafting table.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Use the search function before reporting to see if the issue has been reported before. Charge the philosophers stone.

**Comment by designandbuld** [comment]
Sorry, my bad!  Thank you for making an amazing modpack!
