### ISSUE TITLE
Crash When Loading World

### ISSUE THREAD

**Issue by fightmesun** [Cazadorsniper/PO3#1203]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.54
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Single

**Description:** Game crashes when trying to load save state. 

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://paste.atlauncher.com/view/4881d27f

**Comment by Cazadorsniper** [comment]
delete the 'EnderStorage' folder Here: **USERSDIR**\instances\PO3\saves\New World\EnderStorage and start the server again.
