### ISSUE TITLE
RFT - XNET

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [Cazadorsniper/PO3#1205]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** LATEST
**Pack Mode (Normal, Titan, Kappa):** NORMAL
**Singleplayer, Multiplayer, or LAN?:** SINGLE

**Description:**
Soz if this is a stupid question, but why is XNET so expensive; it is more expensive then AE2 :(
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by MrFieryPotato** [comment]
this isnt an issue...

**Comment by VenerableTimeWanderer** [comment]
Kind of, it makes XNET kind of redundant; if you can just go right AE2?

**Comment by Cazadorsniper** [comment]
Recipes won't change.

**Comment by VenerableTimeWanderer** [comment]
Ok i just thought that it was a mistake cause it was easier to craft in early updates it was crafted with telsa something machine frame.
