### ISSUE TITLE
Suggestion, about bundled cables

### ISSUE THREAD

**Issue by Nilixen** [Cazadorsniper/PO3#1207]
**Pack Version: 3.3.58A**
**Pack Mode (Normal, Titan, Kappa): Kappa**
**Singleplayer, Multiplayer, or LAN?: doesn't matter**

**Description: So i was wandering about adding some bundled cables, they could be somewhat expensive, I want them, due to the fact that there're opencomputers already, but there are no boundled cables, and working with redstone, and conduits is just simply annoying **

**Steps to reproduce:**
Well, I didn't place bundle cable :P

**Comment by Cazadorsniper** [comment]
You can add the mod that adds bundled cables to your instance.
