### ISSUE TITLE
cannot repair old tools

### ISSUE THREAD

**Issue by wolfielove1992** [Cazadorsniper/PO3#1208]
3.3.58A
normal
singleplayer

tinkers tools data wiped do i just need to make new tools not a big deal just thought it was odd

load save after update

no crash log

**Comment by Caedis** [comment]
What version were you on previously?

**Comment by wolfielove1992** [comment]
literally one version before

**Comment by Cazadorsniper** [comment]
Likely need to make a new tool.

**Comment by wolfielove1992** [comment]
yeah i had to i loaded a few of my other saves any that had tools with parts from before the reforged update were broken
