### ISSUE TITLE
Land Craft missing

### ISSUE THREAD

**Issue by Luckshotx** [Cazadorsniper/PO3#1211]
PO3-3.3.58A , PO3-3.3.57
Normal, Titan, Kappa
Singleplayer, Multiplayer, LAN

In order to get coralium you need to go to landia but the quest and all items are missing. It seems like the whole mod is missing and I cant find it at curse as well. 
https://www.curseforge.com/minecraft/mc-mods/project-265768

**Comment by Cazadorsniper** [comment]
Land Craft is gone.
