### ISSUE TITLE
Unobtainable materials.

### ISSUE THREAD

**Issue by Riukdn** [Cazadorsniper/PO3#1213]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.58A
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
I'm trying to obtain boron but the only way is by using the laser drill from Industrial Foregoing but it requires boron in order to be made so it's unobtainable.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
deep dark
