### ISSUE TITLE
Unable to craft some singularity's with Quantum Compressor

### ISSUE THREAD

**Issue by F13ERROR** [Cazadorsniper/PO3#1217]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: PO3Serv3.3.58A **
**Pack Mode (Normal, Titan, Kappa):Normal**
**Singleplayer, Multiplayer, or LAN?:Lan server**

**Description: Using the same setup as with emerald singularity, there are several others that will not craft. IE: Aluminum, Copper, Awakened Draconium. This issue persists after breaking and replacing and with trying different types of the same metal.**

**Steps to reproduce: Set up multiple quantum compressors in a row doing all of the singularities, some seem to catch**

**Crash log (use pastebin or issue will be closed): No crash, pictures uploaded.

![ErrLogAluminum](https://user-images.githubusercontent.com/64626190/83132441-06114880-a0a7-11ea-810c-5e18c1624fdb.png)

![ErrLogWorking](https://user-images.githubusercontent.com/64626190/83132449-0a3d6600-a0a7-11ea-8add-6bb5c7d98def.png)

![ErrLogSetup](https://user-images.githubusercontent.com/64626190/83132464-10334700-a0a7-11ea-8e8e-353e3df15a8d.png)

**

**Comment by F13ERROR** [comment]
Got both screens it seems, my bad

**Comment by Cazadorsniper** [comment]
break the machine then place it back down.

**Comment by F13ERROR** [comment]
That's the first thing I tried unfortunately

**Comment by F13ERROR** [comment]
Seems it is working now. Don't know which of these fixed it but this is the order I did it in. Resarted server, Broke compressor a second time, Deleted old Catalyst just to be sure, and replaced everything. Didn't seem to want to work when I broke it the first couple of times, maybe the server reset?

**Comment by Cazadorsniper** [comment]
Maybe.
