### ISSUE TITLE
End chaos island explosion

### ISSUE THREAD

**Issue by scottie612** [Cazadorsniper/PO3#1218]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** normal
**Singleplayer, Multiplayer, or LAN?:** Lan server

**Description:**
my buddies and i killed the ender dragon and then the island exploded like the explosion that happens when the chaos dragon is killed, thus the entire end island is gone and everyone died.  wondering if this is intended or a bug
**Steps to reproduce:**
kill the ender dragon

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
More likely someone opened a chance cube.

**Comment by scottie612** [comment]
Ahh, thats gotta be what it is ! thank you, and thank you for all your work on the pack :D
