### ISSUE TITLE
Forge Microblocks not working for Chisel blocks. (Works in other modpacks).

### ISSUE THREAD

**Issue by xavizus** [Cazadorsniper/PO3#122]
**Pack Version:** 3.0.38

**Description:**
Forge Microblocks only works for standard Minecraft blocks (Such as cobblestone / stone). It does not work for any Chisel mod blocks.

**Steps to reproduce:**
1. Open crafting table.
2. Place Flint/Iron/Dimond Saw from Froge Microblocks in the middle.
3. Place any Chisel block below.
4. Not craft able.

**Comment by hellsinginst** [comment]
Was this issue resolved? I Still can't get forge microblocks to work with marble
