### ISSUE TITLE
Enderlillies not growing

### ISSUE THREAD

**Issue by TheGameGeek** [Cazadorsniper/PO3#1222]
# Use the search function before reporting to see if the issue has been reported before.
3.3.58A
Kappa
Multiplayer

In my server some people are trying to grow enderlillies and we put them on endstone in the end and the overworld and we waiting one irl day and they still didnt grow 1 bit

place enderlillies in the overworld on endstone

**Comment by Slyklaw** [comment]
I've seen them grow on my server. They don't like skylight, put a block over them. And they're very slow, add sprinklers, etc.
