### ISSUE TITLE
Mods not loading into server

### ISSUE THREAD

**Issue by DrunkenPuppy** [Cazadorsniper/PO3#1225]
Can I please get some help. I'm currently having my server hosted by ShockByte, which uses Multicraft. The server is running on 7 Gbs of ram. Previously, I've played Spitgot then swapped to Teknix 3 and now i'm swapping to Project Ozone 3. The first two ran smoothly, but heard this mod will need a bit more juice so I upgraded. 

So now you have the back story, here is what's happening;
When I download the server files, from "https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward", the server properties file isn't in there, so I can't change the "level-type" to "level-type=botania-skyblock". I found a way around this, is by importing an different server properties, and changing that file to what it should be. 

The second problem; The server isn't creating a world file with the correct level type, it is creating a default world...
The solution I've found around this, is creating a single player world with a "Garden of Glass" type world. and then importing that world file into the server files. 

This leads me to the third problem; When we join that server, we don't spawn with the 3 or 4  starting items. When we go into creative to try to give us the items as it says "there is no such item with name...". This also applies to any modded items but vanilla items work. We can see the modded items but it seems that the server isn't registering the items or loading it properly? 

Please if anyone have any solutions or tips to try, we're really looking forward to trying this mod out. 
Thanks!

**Comment by Cazadorsniper** [comment]
Start the server using Forge.

**Comment by DrunkenPuppy** [comment]
Interestingly enough I had the Forge jar in the server but the server didnt recognize it. I was able to fix by doing a fresh wipe of server and re-enabling the server settings to allow the custom.jar to work. Thanks for your tip tho Cazadorsniper.
