### ISSUE TITLE
Block reappears immediatly after being broken

### ISSUE THREAD

**Issue by St3althyPandas** [Cazadorsniper/PO3#1226]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: PO3-3.3.58A
**Pack Mode (Normal, Titan, Kappa): ANY
**Singleplayer, Multiplayer, or LAN?: Multiplayer (Apex 8Gb hosted)

**Description: When players join in to play they can dig blocks but the second they get broken they reappear, this does not effect the player who set the server up.

**Steps to reproduce: any blocks in the world reappear (51.68.218.9:25565 if you would like to test for yourself)

**Crash log (use pastebin or issue will be closed): Game is not actually crashing so no crash log

**Comment by MrFieryPotato** [comment]
probably a bad connection you might need op ti break blocks aswell

**Comment by Slyklaw** [comment]
That is spawn protection. Move away from spawn.

**Comment by St3althyPandas** [comment]
oh wow im an idiot thanks very much @Slyklaw
