### ISSUE TITLE
(Not a bug) Need help

### ISSUE THREAD

**Issue by Tubby737** [Cazadorsniper/PO3#1229]
Hi there, I'm currently playing project ozone 3 kappa mode on the latest version as of date witch is  3.3.58A - (release). Now I'm having an issue with AE2. Every time i go to craft something let's say a piston for example and i shift right click it doesn't craft a full stack, even though i have all the ingredients inside the AE2. Now i have a storage bus attached to my drawer controller so i can see all my ingots and other things from the drawer system into my AE2 crafting grid. Is it possible that it might be a power issue? since i just started into AE and haven't gotten a controller block yet. Not sure will try to troubleshoot in the mourning. Figured I'd see if anyone else is having the issue.

P.S I'm playing on a multiplayer server by myself if that helps anything.
P.P.S Not sure how to add the labels to my issues so sorry if this is in wrong section or anything like that.

**Comment by Cazadorsniper** [comment]
AE2 has issues looking into drawers and barrels for crafting, I recommend quickly getting to the controller.
