### ISSUE TITLE
I can't find a way to make extrautils2 enchanted ingot

### ISSUE THREAD

**Issue by lizardluis** [Cazadorsniper/PO3#123]
I would like to craft the "Upgrade Speed (Magical)" from ExtraUtils2, but in jei there's no way to make the enchanted ingot required to do that craft. I dunno if it's a bug of if I'm just too stupid or if it's even intended to be that way (why though?). Help would be appreciated.

**Comment by Schildos** [comment]
JEI seems to be a little outdated on that, just throw in some gold and lapis into the XU2 enchanter, it should produce it.

**Comment by lizardluis** [comment]
@Schildos That works. thank you. The weird thing is that the enchanter was previously also hidden from jei. That, and the fact that jei doesn't display it's recipes must be a bug.
