### ISSUE TITLE
Portality Mod questions

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [Cazadorsniper/PO3#1230]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**Latest
**Pack Mode (Normal, Titan, Kappa):**Normal
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**
The portality mod, is it meant to consume like a 2 and half million RF per second to keep a portal open. As you need it open to transfer items, fluids and energy. At 5 long then at 10 long it is 5 million.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
# How much power it will be consumed/tick based on the portal length and if it is the caller. (portalLength*ThisValue). If it is the portal the created the link the power will be double
    # Min: 1
    # Max: 2147483647
    I:POWER_PORTAL_TICK=25000

**Comment by IRONDOGKILLER** [comment]
Wow that is scary high. If its that high the only thing to mod might be good for would be to portal to different dimensions. Could it be set for a huge teleport cost not for a high maintenance cost? Otherwise it is kind of useless.

**Comment by Cazadorsniper** [comment]
RF generation is not an issue in Project Ozone.

**Comment by VenerableTimeWanderer** [comment]
Yeah that might be the case but if you can get to the dislocator & pedestal at the same time. you can use no power and less resources to make them. Portalitiy is just a waste of time. You might just get to portality first but you need the power to run them at that stage.

**Comment by Cazadorsniper** [comment]
so make dislocator harder? got it.

**Comment by IRONDOGKILLER** [comment]
Wow friendly fire Venerable, i would rather have portality redundant then making dislocators harder. Though dislocators is like trying to compare god to ant when comparing it with portality.
