### ISSUE TITLE
Fused Quartz doesn't go into Industrial Smelter

### ISSUE THREAD

**Issue by tree856** [Cazadorsniper/PO3#1231]
**Pack Version:**
3.3.58A
**Pack Mode (Normal, Titan, Kappa):**
Titan
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
According to JEI it is possible to use Fused Quartz in the Industrial Smelter to create Hardened Glass, but it is not possible to insert the Fused Quartz in any way.

**Comment by Cazadorsniper** [comment]
I believe fused quartz and hardened glass are the same thing.

**Comment by tree856** [comment]
> I believe fused quartz and hardened glass are the same thing.

In order to mix hardened glass with metals you need to put hardened glass with pulverized metal.
JEI says it is posible to use fused quartz from ender io insead of hardened glass.

**Comment by Cazadorsniper** [comment]
Ah so another recipe that needs to be removed.

**Comment by Cazadorsniper** [comment]
I can't fix this recipe at this time, so its just gonna remain in the pack. Recommend just using hardened glass for those recipe.

**Comment by DeleteMetaInf** [comment]
Still an issue in [Enigmatica 2: Expert Skyblock](https://www.curseforge.com/minecraft/modpacks/enigmatica2expertskyblock).

**Comment by DeleteMetaInf** [comment]
This is also an issue in[Enigmatica 2: Expert Skyblock](https://www.curseforge.com/minecraft/modpacks/enigmatica2expertskyblock).

**Comment by Nevrai** [comment]
This is also an issue in [Enigmatica 2: Expert Skyblock](https://www.curseforge.com/minecraft/modpacks/enigmatica2expertskyblock).
