### ISSUE TITLE
AE2 Wireless Fluid Terminals breaks ALL AE2 systems on a server

### ISSUE THREAD

**Issue by Machine-Maker** [Cazadorsniper/PO3#1232]
**Pack Version:** 3.3.57
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** All AE2 systems on the server work, but all terminals are blank. Interfaces/export/importing works just fine, just the terminals are blank

**Steps to reproduce:** https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4380#issuecomment-634860428

**AE2 Github Issue:** https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4380

**Comment by Cazadorsniper** [comment]
Removed mod.
