### ISSUE TITLE
Urgent fix required, It is not possible to get liquid antimatter in the new version.

### ISSUE THREAD

**Issue by umut25** [Cazadorsniper/PO3#1233]
Pack Version:3.3.58A
Pack Mode: Normal
Singleplayer
Description: Liquid antimatter was gathered from landia before and it got removed, I think refinery recipe got removed too because I could not find it in recipes.
Steps to reproduce: Just play the game trough normal progression.

**Comment by Cazadorsniper** [comment]
I think its underground in coralium infested swamps, so try Lost Cities.

**Comment by Cazadorsniper** [comment]
Or find an antimatter fluid cow.

**Comment by umut25** [comment]
After I have gone to the dimension the game crashed for the first time ever.
http://batman.gyptis.org/zerobin/?1d6d56e5dedaf02e#CPdBwCE1cuX+EXFNRr8ywlYmUoup7YSRc/+NAFrGL80=

I gave the game 9 Gigs of ram.

**Comment by umut25** [comment]
Also I cannot use pastebin since it is banned in my country.

**Comment by umut25** [comment]
I got in and found an antimatter cow right away but I think you should add an easier way to find it!

**Comment by umut25** [comment]
How can I find coralium stone?

**Comment by umut25** [comment]
I reopened by mistake sorry.
