### ISSUE TITLE
Acceleration of process?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1234]
This is less of an issue,  more me just curious if there's anything out there to make the process quicker

I tend to end up only missing neutral steel of [whatever] degree when trying to craft some stuff with extended crafting. 
I have a bunch of fluid cows automated into fluid transposers that make the process semi automatic , but my problem is that the reasoning why the neutral steel usually takes so long naturally is because of the Moo Fluids cool down time, so I was curious if anything in this modpack changed tick speed or anything of the sort [That doesn't need me to re-enable disabled items like the watch of flowing time] 

Just wanted to know, the system is fine as is, just a tad repetitive so having a quicker way would be favorable.

**Comment by 4dam3k** [comment]
I think that Astral Sorcery Tick Acceleration works

**Comment by AnimeNerdDJBROS** [comment]
Do you know of a way I could research how to do that?

**Comment by 4dam3k** [comment]
Look on youtube for: "Hypnotizd PO3 Astral Sorcery Tick Acceleration" BTW: Its kappa but it work on normal too

**Comment by AnimeNerdDJBROS** [comment]
k
