### ISSUE TITLE
Circuit Fabricator Automation

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1237]
This isn't exactly an ISSUE, more I was just curious and it may make things more favorable.

But can the circuit fabricator extract into a chest or something so I can automate wafers with interfaces?

**Comment by AnimeNerdDJBROS** [comment]
Update, I actually need help with extraction on ALL of the galaticraft machines, NONE of them export.

**Comment by iInFiniTyyy** [comment]
Using AE2 you are able to automate the machines, so I guess using itemducts/item conduits you should be able to recreate the process AE2 is doing.
Picture below: Interface on top and import bus on bottom does the trick for me.
![2020-06-05_10 53 53](https://user-images.githubusercontent.com/66466654/83857193-e7e8bf80-a71a-11ea-85f7-61c819cafd77.png)

**Comment by AnimeNerdDJBROS** [comment]
Thanks,  that helped,  I didn't expect devs to put the output at the bottom. Lul
