### ISSUE TITLE
PO3 Kappa issue when crafting Neutral Steel of the 5th Degree 

### ISSUE THREAD

**Issue by FreddyFrog24** [Cazadorsniper/PO3#1240]
3.3.58A
Kappa
Single player

Bug 1: The JEI recipe for the Neutral Steel of the 5th degree says that it needs 3 NS4thdegree in the center of the alloy smelter and 1 on either side when it actually only needs 3 NS4thdegree total
Bug 2: If more than 1 is put in each slot at a time it will consume all up to 5 at a time and only output 1 NS5degree
Bug 3(may be intended feature of Ender io): The stack of NS4thdegree will not split into all three but stay in the first slot until full then into the second and so on, this makes it difficult to automate them in small quantities

**Comment by iInFiniTyyy** [comment]
Please read #1200
