### ISSUE TITLE
PO3 crash when loading world

### ISSUE THREAD

**Issue by Fluoxi** [Cazadorsniper/PO3#1241]
3.2.55
Kappa
Singleplayer

I was messing around with Industrial Foregoing laser base/drills when suddenly the world crashes and now I can't get back into the game. I tried some Google searches and I found some similar results with people messing around with inverted lenses causing the game to crash. I think I need to delete the base and drills through MCedit but I don't know how. Also why the crash in the first place?

Placed laser base and 4 drills, powered by 4 spectre coils with access to the void. Used 1 pink lens and the rest was various inverted colors.

I couldn't save the log in pastebin because it exceeded the maximum size.a

[2020-06-06-1.log](https://github.com/Cazadorsniper/PO3/files/4739822/2020-06-06-1.log)

**Comment by Cazadorsniper** [comment]
Use the forge.cfg options to remove the laser.

**Comment by Fluoxi** [comment]
B:removeErroringEntities=true
B:removeErroringTileEntities=true

Changing these seems to fixed the issue, thanks. Made a copy of my world just in case.
