### ISSUE TITLE
[Request] Can you make it so that you can craft neutral steels with emc on normal mode?

### ISSUE THREAD

**Issue by umut25** [Cazadorsniper/PO3#1244]
As I said in the title, it takes way too long and machines cannot work fast enough even with automation. Can you at least make it so you can make them with emc?

**Comment by umut25** [comment]
It is not about materials, I have to leave it overnight in order for it to finish, which is boring.

**Comment by iInFiniTyyy** [comment]
Just upgrade the setup? Especially on normal mode. On kappa, I have a autonomous setup for the neutral steels and its keeping up with the demand for it.

**Comment by VoidedOut** [comment]
Use dimensions of the fluids for the first tiers if you can, melters and magma crucibles will never be fast enough

**Comment by umut25** [comment]
You dont understand the problem, i have all the resources it needs all the time, but it still did not craft it all, there  are still 1/4 left to craft and my setup is at max speed 
![image](https://user-images.githubusercontent.com/11256132/84017538-7a8d9680-a987-11ea-9390-cd4826d269c7.png)

**Comment by umut25** [comment]
And mind you im only crafting seventh ones currently.

**Comment by umut25** [comment]
>  melters and magma crucibles will never be fast enough
If you use 8 of them at max speed It is enough and will work without stopping.

**Comment by umut25** [comment]
It is currently balanced as is but there needs to be a faster way of making it, that is why I recommended emc. He can also speed up the making time.

**Comment by 4rcadius** [comment]
Pretty sure if you go into the ProjectE config file you can set up custom emc values for specific items

**Comment by umut25** [comment]
I know I can but I want to it legit. If he updates this system I'd be happy, otherwise I will have to use an absurd amount of melters  to make a system.

**Comment by VoidedOut** [comment]
Use dimension builders for the fluids then have multiple transposers.

**Comment by Cazadorsniper** [comment]
I will not be adding EMC to the neutral steel.

**Comment by iInFiniTyyy** [comment]
The whole point of the pack is getting headaches from all the crazy recipies and coming up with solutions for it.
