### ISSUE TITLE
World type wont change on server

### ISSUE THREAD

**Issue by 4rcadius** [Cazadorsniper/PO3#1245]
So I downloaded the server files, went on server properties, changed the level type to SKYLANDS (or 
 botania-skyblock) and even deleted the previous world so a new one generates and it still gives me a default world. Please help!

**Comment by Cazadorsniper** [comment]
Are you starting the server using forge? Also you should of searched up closed issues in this github, there are other issues pretty much exactly same as this one.

**Comment by 4rcadius** [comment]
Yeah my bad that was the problem, should've looked at closed cases but thanks for your help!
