### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kzero12357** [Cazadorsniper/PO3#1246]
Hello, I have been trying to get the most recent update of PO3 on my server and it will not stop crashing. I am unsure what the issue is, but maybe someone else here will.

https://pastebin.com/ie9Vjb85

**Comment by Cazadorsniper** [comment]
Do you have 2 versions of Astral Sorcery in the mods folder?

**Comment by kzero12357** [comment]
I do not, I just checked

**Comment by kzero12357** [comment]
although when I was troubleshooting I took out astral sorcery, and this is the crash it generated 

https://pastebin.com/TR9Bu9qG

**Comment by kzero12357** [comment]
is there any update on this?

**Comment by Cazadorsniper** [comment]
Probably naming of resources, I don't know because I don't work with Linux often.

**Comment by Cazadorsniper** [comment]
Its crashing with Contenttweaker for some reason.
