### ISSUE TITLE
Lordcraft Automation?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1247]
I'd like for someone to tell me here a simple thing, can you automate the void interface so I don't have to pull my hair out to do anything big with lord craft?

**Comment by VoidedOut** [comment]
I don’t think so. You can fill the interface with blocks of the crystals though

**Comment by loltatoez** [comment]
You can use the void crystal and right click to to put your mana in it. Won't require the interface. Keep in mind, if you have no mana, you cannot cast any spells. You can shift right click it to get the mana back out

**Comment by AnimeNerdDJBROS** [comment]
Um, I don't think you understood the issue, right clicking IS the problem, it's fairly repetitive and it'd be useful if there was a way to get around that.
