### ISSUE TITLE
AE2 Help?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [Cazadorsniper/PO3#1248]
If anyone may respond, I've been having an issue with my ME controller being way too small for my bases requirements with autocrafting and crap, and I have the resources to make it bigger, just AE2's ridiculous rules on how a ME controller works is quite annoying and I don't know how to do it. 

So if anyone has an idea of any run through on how to get a lot of channels on  a system with a demonstration of how you utilize those channels afterwards, that would help quite a lot.

**Comment by Cazadorsniper** [comment]
A lot of your questions can be answered on the discord server.

**Comment by AnimeNerdDJBROS** [comment]
There's a discord server? May I have a link? I was unaware.

**Comment by AnimeNerdDJBROS** [comment]
Nvm, found it.
