### ISSUE TITLE
Game crashes post new update

### ISSUE THREAD

**Issue by loltatoez** [Cazadorsniper/PO3#1249]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Whenever I open an ME terminal, my game just crashes. No explanation in the logs at all. And it is not crashing every time, but I am on like the 6th time loading my pack and it keeps crashing.
**Steps to reproduce:**
Load game
Open ME System Crafting Terminal 
Edit: Just waiting a few seconds seems to do it as well
**Crash log (use pastebin or issue will be closed):**
No crash report generated. I will supply my latest.log, but since it exceeds pastebin max size I am gonna use a gist.
[Here it is](https://gist.githubusercontent.com/loltatoez/32eed6c34ec681785860a622f360a8f3/raw/8ffc4db8b1e7a4dbd365978ec08a8dcdb1ef956a/latest.log).
I also recorded a [video](https://www.dropbox.com/s/a6vtve8ggwfiwg6/2020-06-09%2017-02-36.mp4?dl=0) of it happening. It took a few trys but nonetheless it keeps happening.

No idea why this is happening. I am supplying it with enough RAM, but if not I have 40 GB at my disposal.
Edit: The game seems to crash after a little bit even when not opening the ME Terminal.

**Comment by loltatoez** [comment]
Also I did not intentionally assign you if that was not automatic. Sorry if that isn't, no idea how that happened.

**Comment by Cazadorsniper** [comment]
I can't tell what the issue is, maybe have an item in 1 of the 1k's that is breaking, not sure what its though.
