### ISSUE TITLE
coralium infested swamp not staying loaded with chunk loader

### ISSUE THREAD

**Issue by theduskflyer** [Cazadorsniper/PO3#1257]
Version 3.2.50 Kappa Mode

Ok, so set up is like this. 

Base, where i have everything. with a Mob Farm(Just cursed Earth, to a mob masher) 
Then about 800 blocks away in the Coralium Infested Swamp, another Mob farm(same thing, Cursed Earth to a mob masher)
When im back at the base, no mobs spawn at the other mob farm. go to the farm, works perfectly.
I have a ChickenChunks chunk loader and using the /chickenloaders I show
Tickets: 5
Forced Chunks: 96
Chunks: 634
Players: 1

I also tried to switch on the FTButils chunk loader and still have same issue. 

i found a post with some one having the same issue, but nothing was ever found to be the problem

I have deleted the Base mob farm thinking i was hitting max minecraft mobs. 

should have a picture of the chunksloaders command. big red area is base, small area is second farm.

No crash log, as game doesn't crash.
![chunks](https://user-images.githubusercontent.com/66760234/84339779-cea1a200-ab64-11ea-8f5f-668fb53565e9.PNG)

**Comment by theduskflyer** [comment]
update, being in another dimension the farm works.

**Comment by TheKedart** [comment]
This is normal behavior for Cursed Earth mob spawns. They follow normal mob spawning rules (player must be in proximity), however they function when chunkloaded if no players are in the dimension. Not a bug.
