### ISSUE TITLE
plastic issues

### ISSUE THREAD

**Issue by wolfielove1992** [Cazadorsniper/PO3#1259]
3.3.59
normal
singleplayer

cannot get the plastic mixer to take any plastic at all

tried to put it in but i cant get liquid plastic without a refinery and there is no in game book to explain any of it.
no crashlog

**Comment by Cazadorsniper** [comment]
Oil should be in the twilight forest.

**Comment by wolfielove1992** [comment]
yeah i just got a really bad spawn i had to fly 15000 blocks from my portal to find some but why cant the plastic mixer take other plastic other then the refinery plastic

**Comment by Cazadorsniper** [comment]
Different mods.

**Comment by wolfielove1992** [comment]
yes but a lot of the mods in this pack have interchangeable materials but this is like slamming a big fat boulder in the way what would happen if i had a twilight forest spawn with no oil within the perimeter of the first boss it would lock out the quest book till way later

**Comment by Cazadorsniper** [comment]
Interchangeable items not liquids.

**Comment by Cazadorsniper** [comment]
There are also oil cows that you could find.

**Comment by Acnologia-** [comment]
You can try to find oil from immersive petroleum. that can be found in all dimensions. Use a core sample drill to find an oil deposit and build a pumpjack to extract it.
