### ISSUE TITLE
Cannot spawn island for players on server

### ISSUE THREAD

**Issue by sharkck** [Cazadorsniper/PO3#126]
**Pack Version:**
3.0.38

**Description:**
Using the command, /botania-skyblock-spread (@p[r=3]) -player name- does not work and just throws an error.

**Steps to reproduce:**
Use the command, get error.

**Crash log:**
None

**Comment by Cazadorsniper** [comment]
remove (@p[r=3]) then try it

**Comment by sharkck** [comment]
Did not work.

**Comment by Hachuurui** [comment]
/botania-skyblock-spread <playername> <distance over 250 I recommend at least 3k or higher>

**Comment by sharkck** [comment]
Did not work.  Not sure what is going wrong.

**Comment by Hachuurui** [comment]
That's the command I use to build islands on my server

  /botania-skyblock-spread sharkck 3500 as an example above. it could be
how you are typing it. You also need to be opped when running the command.
