### ISSUE TITLE
Crash on singleplayer world loading

### ISSUE THREAD

**Issue by MechaFinch** [Cazadorsniper/PO3#1260]
**Pack Version:**
3.3.57, 3.3.59
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
During world loading at `Preparing spawn area: 50%`, the following exception occurs. This is identical across multiple retries and after updating the pack to 3.3.59. I don't know what caused this as I exited the world normally and the crash is during world loading.
While similar to #1199, this is in single player and there was no initial crash.
```
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
```

**Steps to reproduce:**
Unknown

**Crash log (use pastebin or issue will be closed):**
Crash Report: https://pastebin.com/rN0J4ESM
lastest.log is attached as it is too large for pastebin
[latest.log](https://github.com/Cazadorsniper/PO3/files/4767585/latest.log)

**Comment by Cazadorsniper** [comment]
Make a new profile of version 3.3.59 then move your world over to see if it works.

**Comment by MechaFinch** [comment]
That's what I tried with updating to .59 but it got the exact same issue, crashing at the same time with the same exception character for character.

**Comment by Cazadorsniper** [comment]
There are mods in there that isn't in the pack anymore and some of those mods you have in that crash aren't updated. Recommend manually (copy/pasting) updating the mods, config, and scripts files.

**Comment by MechaFinch** [comment]
I went through the process of manually updating things, only difference being that Modular Machinery couldn't be updated to keep it compatible with Modular Diversity.
Same issue, same exception as the other two versions of the install.

[crash-2020-06-11_20.46.53-server.txt](https://github.com/Cazadorsniper/PO3/files/4768012/crash-2020-06-11_20.46.53-server.txt)
[latest.log](https://github.com/Cazadorsniper/PO3/files/4768008/latest.log)

**Comment by Cazadorsniper** [comment]
Maybe some software is blocking it or hardware issue is happening. But I recommend just installing a entirely new instance of 3.3.59 since Modular Diversity was removed.

**Comment by MechaFinch** [comment]
Since that was my method for updating to .59 originally, I'm going to assume that the issue is world corruption and I'll just have to load a backup.
Thank you for your time & help.

**Comment by MechaFinch** [comment]
I've figured out the cause of the issue. Once I leave my world having placed down the ArmorPlus workbench, I can no longer open the world as the crash happens.

**Comment by MechaFinch** [comment]
Removing the workbench via MCEdit fixes the crash, so I can confirm it as the cause.

**Comment by kamik1979** [comment]
I also had the same issue. I removed the workbench using MCEdit, but what, now I cannot use ArmorPlus? Is there a way of fixing this? Or I just need to break the workbench each time I'm leaving the game?

**Comment by kamik1979** [comment]
I also had the same issue. I removed the workbench using MCEdit, but what, now I cannot use ArmorPlus? Is there a way of fixing this? Or I just need to break the workbench each time I'm leaving the game?
