### ISSUE TITLE
Draconic Bow Draw-Animation Looping

### ISSUE THREAD

**Issue by scottmmuc** [Cazadorsniper/PO3#1262]
Version - 3.3.59
Normal Mode
Multiplayer 

I just looked around for this but didn't any existing issues for it so I hope I'm not repeating anything here, but I just made the Draconic Bow and it was doing this weird thing where if I hold left click to draw an arrow it would just repeatedly start the drawing animation over and over. The bug seems to be a bad interaction between the bow and the Ender Spectre Charger from Random Things, if I take off the charger the bow draw animation works normally. I think it just goes to start the animation over whenever a new RF value is detected, and because of the charger it constantly has a new RF value. 

If the bow is full on RF the animation is fine, but after a single shot if I go to shoot again right after it will repeat the animation on loop until the bow is fully charged again, and then it'll stop. So I think it's less to do with the coil itself and more just an issue with the bow constantly changing values. 

No crash log. 

Thanks for your help!

**Comment by Cazadorsniper** [comment]
Does it do the samething using DE's method of recharging?

**Comment by scottmmuc** [comment]
Yeah but definitely not as much. I just tried using a Draconic Flux Capacitor and with that it'll only repeat the animation one time if at all, and only if I'm trying to rapid fire it with auto-fire off. It'll repeat until it's full, and the coil is way slower than the flux capacitor so that's why it kept doing it. The flux capacitor tops it off almost immediately so at most there's only one repeat animation if I go to draw again right after firing just before it's full.
