### ISSUE TITLE
Fabricator Dupe Bug

### ISSUE THREAD

**Issue by DrewSin-4** [Cazadorsniper/PO3#1264]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59 (Dupe also occurs on ,3,3.58a)
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
Bug with fabricator which causes easy duping.

**Steps to reproduce:**

1. Get a fabricator.
2. Place it down.
3. Place the block you want to duplicate in any number of slots on the left side.
4. Place the block on the right hand side also 
5. Double Click on the item in the right hand side.

Proof (Video/Gif):
https://i.imgur.com/DYE0ZUN.gif

**Crash log (use pastebin or issue will be closed):**

No crash log due to it being a dupe.

**Comment by ManIkWeet** [comment]
Confirmed working
