### ISSUE TITLE
Several Chunks refuse to stay loaded

### ISSUE THREAD

**Issue by Acnologia-** [Cazadorsniper/PO3#1266]
Pack Version 3.3.57
Pack Mode: Kappa
Multiplayer server.

**Description:**

After updating my server to from version 3.2.54 to version 3.3.57  I have 3 chunks in my world that refuse to stay loaded when the last player disconnects from the server. I have set chunkloaders and even spotloaders from chickenchunks in those chunk and yet they refuse to stay loaded. According to the chunk inspection tool they should be loaded.

To verify I have placed an automated farms in those chunks using various machines and none produced any more items after letting the server on over night.

Only 3 specfic chunks in the world are affected and none other have this problem.

**Steps to reproduce:**

Steps are unknown.

**Crash log (use pastebin or issue will be closed):**

No crash log. If any logs or world downloads are needed please tell me and ill upload them.

**Comment by Cazadorsniper** [comment]
I don't know what causes this issue.
