### ISSUE TITLE
Cant craft string mesh

### ISSUE THREAD

**Issue by SaltyMemess** [Cazadorsniper/PO3#127]
**Pack Version:**
3.0.38

**Description:**
I and my friends tried crafting the string mesh but its just ends up crafting "silk:

**Steps to reproduce:**
retry crafting recipe

**Crash log:**
none
![2019-03-09 02_51_45-Greenshot](https://user-images.githubusercontent.com/48182103/54067427-4ec8b180-4216-11e9-8c95-82eb3a1d10e4.png)

**Comment by Cazadorsniper** [comment]
Are you playing on a server?

**Comment by SaltyMemess** [comment]
> Are you playing on a server?

Yes i am, my own

**Comment by Cazadorsniper** [comment]
Make sure the scripts folder on the server matches the client.

**Comment by Pierrrick** [comment]
I have the same problem and we tried that solution but it hasn't worked also I found that the cooking recipe  for black quartz also don't work.

**Comment by SaltyMemess** [comment]
> Make sure the scripts folder on the server matches the client.

oh that worked, thanks!!!!
