### ISSUE TITLE
Mining Nether Quartz Ore with Silktouch drops Quartz, not the Ore Block

### ISSUE THREAD

**Issue by helgeh** [Cazadorsniper/PO3#1270]
Pack Version 3.3.58A
Pack Mode Normal
Singleplayer

Mining Nether Quartz Ore either with Tinkers Silktouch or using a regular Diamond Pickaxe with regular Silk Touch on it, it will only drop normal Quartz and not the Ore Block itself. Am I wrong to think it should drop the Ore? I have searched both here and elsewhere without finding anyone reporting the same so it feels like I am missing something.

I am trying to complete the first part of Karat Carrots quests and the only way I can get hold of some Nether Quartz Ore it seems I need the Combiner which seems a bit early?

**Comment by Cazadorsniper** [comment]
Have you've tried mining it normally without silk touch?

**Comment by helgeh** [comment]
Absolutely.

**Comment by helgeh** [comment]
I have no idea what just happened. But after i double checked that I in deed *had* mined it with a *regular* pickaxe without silk touch, confirming that it still dropped the quarts items. Then, for some reason I just mined it with my normal Tinkers pickaxe, which is the one I have used earlier and tried to specifically to get the Ores with, now it mined the Ore Block. 

I'm just totally weirded out by this... 

Well, closing the issue then :)

**Comment by helgeh** [comment]
@Cazadorsniper Today I discovered there are two different Nether Quartz Ore types from different Mods. One of which only drops Quartz items, no matter what. The other one drops according to what kind of tool you use, e.g with Silk touchy picks it drops the Ore Block. Mystery solved! :D
