### ISSUE TITLE
No Gaia Spirits In Patient Bag

### ISSUE THREAD

**Issue by coolside** [Cazadorsniper/PO3#1271]
Version 3.3.59
Kappa Mode
Single Player

I've not received any Gaia Spirits from Patient Bags still only Nether Stars.  Verified as well in Creative world.  Looked in config and it shows Nether Star under patient bag

Patient bag in Loot Bag Opener

No Crash Log

**Comment by Cazadorsniper** [comment]
your configs must be broken, recommend replacing them.

**Comment by coolside** [comment]
Thanks for the reply.  I did just that and it worked

Cheers!
