### ISSUE TITLE
Mob Duplicator and GM Chicken Feed(for spawn egg)

### ISSUE THREAD

**Issue by FastHit** [Cazadorsniper/PO3#1273]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.59**
**Pack Mode (Normal, Titan, Kappa): Kappa**
**Singleplayer, Multiplayer, or LAN?: Multiplayer(but also tested in SP)**

Description: spawning chicken with mob duplicator using exact copy and giving to one of them GM Chicken Feed(from to get spawn egg) makes all spawned chicken explode and give spawn egg.

Steps to reproduce:
1. Spawn chicken with the mob duplicator on exact copy.
2. give one of them GM Chicken Food.

Crash log (use pastebin or issue will be closed):
game did not crash.

Here is a video showing it: https://imgur.com/iNMpHyx

**Comment by Cazadorsniper** [comment]
lol
