### ISSUE TITLE
Tinkers' Construct Stone Torch not working on Crucible 

### ISSUE THREAD

**Issue by kubilayerislik** [Cazadorsniper/PO3#1275]
**Pack Version: 3.3.59
**Pack Mode (Normal, Titan, Kappa): Kappa
**Singleplayer, Multiplayer, or LAN?: Singleplayer

I'm playing on the version 3.3.59 and I recently started a new world (garden of glass).

My problem is that the Stone Torch from TinkersContruct  isn't working for the lava processing, it's at the rate of 0. It is not a big problem but it can be fixed new version. 

![2020-06-21_00 44 21](https://user-images.githubusercontent.com/60624996/85212143-6d45b400-b358-11ea-80b5-5e98f54d255d.png)

**Comment by Cazadorsniper** [comment]
How about using a normal torch?

**Comment by kubilayerislik** [comment]
Normal torch works fine.

**Comment by Cazadorsniper** [comment]
Then there is no real issue here.
