### ISSUE TITLE
Red Seeds can't grow on redstone while there's particle effects.

### ISSUE THREAD

**Issue by smith505** [Cazadorsniper/PO3#1277]
Any pack mode(I'm guessing)
Red seeds will not grow while Redstone ore has the particle effect on it. Particle effect happens if you step or click on the block or even place a block on it.
https://gyazo.com/5d6c1737754dbdb1262af3317f26d348

**Comment by Cazadorsniper** [comment]
Nothing I can do about that suggest waiting for the particles to stop.
