### ISSUE TITLE
PO3 Server crashes right after running .bat

### ISSUE THREAD

**Issue by Kanubbel** [Cazadorsniper/PO3#1278]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.59 Server**
**Pack Mode (Normal, Titan, Kappa): all of them**
**Singleplayer, Multiplayer, or LAN?: Multiplayer **

**Description: 
Hello ,

maybe someone can help me with this issue.
It occures right after i run the batch file.

After that the console closes itself.
I have not changed any settings but tried once Xmx8G with Xms256M same result. And Xmx16GB once.

What i have tried so far:
Unpacked it on Windows Server 2016 and tried to run it, now the "server" is running Windows Education (Education is like professional, just for students or something like that).

Reinstalled Java on both operating Systems.

Redownloaded the Serverfiles and unpacked them again and again after i tried something.

Downloaded a bunch of Java stuff, hoping it fixes it:
https://i.imgur.com/v1qA2dt.png
Using Ninite there to check current version...

If you need some more information, just tell me i'm trying to provide it as fast as possible :D**

**Steps to reproduce: Downloading zip file, unpack it and start .bat (not sure if you can recreate it)**

**Crash log (use pastebin or issue will be closed): https://pastebin.com/5tZFL7aH **

**Comment by Cazadorsniper** [comment]
Did you accept the eula?
Maybe try fixing the folder name from PO3+-+3.3.59server to PO3-3.3.59server.

**Comment by Kanubbel** [comment]
Layer 8 problem :D downloaded wrong java
