### ISSUE TITLE
new server file not working to start server

### ISSUE THREAD

**Issue by hdhdn** [Cazadorsniper/PO3#1279]
# Use the search function before reporting to see if the issue has been reported before.
3.3.59
normal
Multiplayer
It doesnt have the neccessary files to start the server after downloading the serve pack, not sure how to fix

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
What files are missing?

**Comment by ZooFology** [comment]
I see this same issue. this is all I see within the newly downloaded server zip. https://i.imgur.com/DtDoy5L.png

**Comment by hdhdn** [comment]
That's all I download as well, and it doesn't explain what yo do with them, ive tried dragging and dropping,  and it kills the server, ive tried re downloading the server with just those files and they dont work, im not sure anymore

**Comment by Cazadorsniper** [comment]
Youtube tutorial would help with this. Hard to explain in text.
