### ISSUE TITLE
Modular Machinery/Ore Dict.

### ISSUE THREAD

**Issue by squillis** [Cazadorsniper/PO3#128]
**Pack Version:**
3.0.38
**Description:**
Modular Machinery/Ore Dict.
**Steps to reproduce:**
None
**Crash log:**
None

Steel Ingot, for Compressed Steel is not ore dictionaried.

Also not sure if intended for gating/progression, some recipes for Titanium aren't ore dictionaried for Galacticraft Planets.

**Comment by squillis** [comment]
After trying all the ore dict items/mods I could find, the Mekanism Oredictionificator allowed me to switch the ingots with out actually having the Galacticraft Planets ingot.

**Comment by quietust** [comment]
You can also craft the Forge Lexicon from Thermal Foundation (a whole lot cheaper) to perform the same function.

**Comment by squillis** [comment]
I tried that, but i think you needed the target ingot to be able to change it.

**Comment by quietust** [comment]
I just tried, and it worked just fine - you right-click the book, place the item stack in the lower-left slot, select the desired oredict version in the top-center slot, then click the big right-arrow to transform it into the lower-right slot.
