### ISSUE TITLE
Ember emitter not emitting embers

### ISSUE THREAD

**Issue by xxlongarrow34xx** [Cazadorsniper/PO3#1282]
So i recently started to play this modpack on a personal server and ran into an issue with embers rekindled. I have ember emitters connected to an activator which is fueled by a hopper with shards. I Shift right clicked on the receptor connected to my melter and right clicked to one of the emitters. The emitter has a lever on it which is turned on but does not emit anything after being connected. It does emit for a few seconds when i break and replace the receptor but stops working. The activator has a constant supply of ember shards. Ive looked online for solutions but to no avail. I'd appreciate if someone could help. Thanks :)

**Comment by VoidedOut** [comment]
Do you give it a redstone signal

**Comment by xxlongarrow34xx** [comment]
> Do you give it a redstone signal

Yes, with a lever which is turned on whenever i try to power the melter. (The waila tooltip says Status: ON)

**Comment by VoidedOut** [comment]
Did u also put the ember emitters/receptors in the right spot? Try checking the manual. If you’ve done that there’s probably nothing I as a normal person trying to help can do lol, sorry

**Comment by xxlongarrow34xx** [comment]
Yes i did. When i didnt work for the first time i watched a tutorial online and built a block by block replica of it. It said to shift right click the receptor first then right click an emitter(both with the tinkerer's hammer). If nothing can be done to fix it then this should be labeled as a bug.
