### ISSUE TITLE
thermal expantion flux capacitor 

### ISSUE THREAD

**Issue by shadowknight559** [Cazadorsniper/PO3#1286]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.59
**Pack Mode (Normal, Titan, Kappa): Normal
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: thermal expansion flux capacitor keeps disappearing from my inventory every time i die. all other item are there just not the capacitor 

**Steps to reproduce: die with any thermal expansion flux capacitor in your inventory and collect grave.

**Crash log (use pastebin or issue will be closed): N/A no crash

**Comment by Cazadorsniper** [comment]
Might be in your bauble slot maybe.
