### ISSUE TITLE
Missing Recipe And Can't Even Craft It If i use the right recipe

### ISSUE THREAD

**Issue by ArchiToxic** [Cazadorsniper/PO3#1288]
Missing Recipe Item Filter, Dont work even if u use the right itms in crafting table
**Pack Version: Latest**
**Mode Kappa**
**Singleplayer**

**Description: If u search "filter" and find the item named Filler used for the Trash Can, u click it and don't want to show any recipe, but if u know the recipe, or u find it on google, not even then can be used because even if u use the right recipe in any crafting table, the itm don't show**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
That is likely due to the recipe being removed recommend using item conduits then use those filters. 
Also Latest is not a version.
