### ISSUE TITLE
Game crash when switch windows

### ISSUE THREAD

**Issue by rodom10** [Cazadorsniper/PO3#129]
**Pack Version:**
3.0.38

**Description:**
Game crash when press "ATL + Tab" 

**Steps to reproduce:**

**Crash log:**
not have crash log

**Comment by Cazadorsniper** [comment]
Game crash but no crash log....

**Comment by CraftalotReloaded** [comment]
You want to give the game some time when alt tabbing without clicking or it may crash alternatively you could give this mod a try https://minecraft.curseforge.com/projects/fullscreen-windowed-borderless-for-minecraft

**Comment by Cazadorsniper** [comment]
if the game crashes then something has had to happen whether it makes a crash report or not. Try looking for the latest.log.

**Comment by CraftalotReloaded** [comment]
A crash when switching window is common with minecraft, especially with that many mods; hence why someone made a mod to turn it borderless so that transition can occur much faster
