### ISSUE TITLE
Neutral Steel of Eleventh Degree

### ISSUE THREAD

**Issue by Keycz1** [Cazadorsniper/PO3#1290]
Pack version - 3.3.59  - newest version
Pack Mode - Kappa
Singleplayer

1. If you want to make Neutral Steel of the Eleventh Degree (in PRC), it won't do anything
2. I know it's a kappa mode but I hate making the Neutral Steels (all of them), for example I want do six Neutral Steel of Tenth Degree. I'll start it (in applied energistics 2 - auto crafting) and I will spend like 1 full day (real day) of making it, it's so tedious.

Just please delete the Neutral Steel Degrees or change recipe

Last Message: Sorry for my English

Keycz1

**Comment by ItsTheGriz** [comment]
I agree with this completely. Before Landia was removed, the recipes were far more balanced. Sure, you can scale up the machines needed to build the lesser steels for the creation of this. However, the shear amount that is needed and the time sink involved is absolutely overtuned compared to earlier releases with Landia.

Might I suggest adding new easier to craft recipes for the lesser degree steels and a block that can be animated. I think this would go a long way to make this more balanced yet still challenging.

Recipe Examples:
- Draconium Ingot + 8x Pyrotheum Dust = Neutral Steel of the First Degree
- 3x Neutral Steel of the First Degree + 8x Cryotheum Dust = Neutral Steel of the Second Degree
- 3x Neutral Steel of the Second Degree + 8x Aerotheum Dust = Neutral Steel of the Third Degree
- 3x Neutral Steel of the Third Degree + 8x Petrotheum Dust = Neutral Steel of the Fourth Degree

These would be the comparable recipes with the same amount of liquid if the same balance is wanted. I might even suggest even using rods as a recipe as it would streamline the mid-game with seeds.

Recipe Examples with Rods:
- Draconium Ingot + 8x Blaze Rods = Neutral Steel of the First Degree
- 3x Neutral Steel of the First Degree + 8x Blizz Rods = Neutral Steel of the Second Degree
- 3x Neutral Steel of the Second Degree + 8x Blitz Rods = Neutral Steel of the Third Degree
- 3x Neutral Steel of the Third Degree + 8x Basalz Rods = Neutral Steel of the Fourth Degree

**Comment by Keycz1** [comment]
That would be awesome. 👍  Hope the author fixes it and saves me some of my time :)

**Comment by Cazadorsniper** [comment]
Would it help if I added EMC to the 6th degree?

**Comment by Keycz1** [comment]
Yes a lot

**Comment by Keycz1** [comment]
Can I ask when will it be done? I want to continue in the game :)

**Comment by Cazadorsniper** [comment]
Idk since I have to work but about yopur first issue have you've tried adding energy upgrades to the PRC.

**Comment by Keycz1** [comment]
Ok I'm really looking forward to it. And yes it's working with the energy upgrades :) I'm sorry about that

**Comment by Keycz1** [comment]
One more problem. In Delta section is one seed which it cannot be crafted (Alumite seed)
<img width="1039" alt="Alumite seed" src="https://user-images.githubusercontent.com/67666580/86531289-388d3d00-bec0-11ea-85dc-f4e5ea89e260.PNG">

**Comment by Keycz1** [comment]
Can I ask when will be my "problem" solved. It's been a week and still nothing. Sorry, that I'm annoying but I want to finish the pack. BTW. I love this pack a lot. 👍

**Comment by Cazadorsniper** [comment]
I doubt you're playing the pack anymore but my pc broke and it will still be more time before I can update the pack.
