### ISSUE TITLE
Crashes when loading

### ISSUE THREAD

**Issue by maxicode2** [Cazadorsniper/PO3#1291]
**Pack Version:*3.3.59*
**Pack Mode (Normal, Titan, Kappa)*:normal*
**Singleplayer, Multiplayer, or LAN?:*Singleplayer*

**Description:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Steps to reproduce: load the latest version of PO3

**Crash log (use pastebin or issue will be closed):*[](https://pastebin.com/DNXqsz6u)*

**Comment by Cazadorsniper** [comment]
Allocate more ram
