### ISSUE TITLE
Neutral steel of the fifth degree recipe

### ISSUE THREAD

**Issue by MartoA** [Cazadorsniper/PO3#1295]
Pack Version: 3.3.59
Pack Mode: Normal
Singleplayer

Hello, I am not able to find any recipe for Neutral steel of the fifth degree, I couldn't find any about it on the issue tracker. Sorry if it was already asked.
In the quest book it says you can craft it in the Alloy smelter, but the machine does not accept any quantity on any machine mode (alloys/furnace).

Thanks :)

**Comment by ItsTheGriz** [comment]
The recipe should be in the Alloy Smelter.

Recipe:
- 3x Fourth Steel + 1x Tungsten + 1x Vivid Alloy = 1x Fifth Steel

**Comment by MartoA** [comment]
The Alloy smelter does not accept the fourth degree , I tried it already... I tried all mods of the machine - Alloys only, Furnace only, Alloys/Furnace.
When I try to see the recipes that include the fourth degree also does not show anything in JEI.

**Comment by ItsTheGriz** [comment]
Interesting. I am playing on Kappa so it could be slightly different. I don't have this issue though and I am on the same version. You might want to backup your world, make a fresh install on your server, and move the world folder over to the new install.

To me, it sounds like you have an issue with your update. Could be an old config, script, etc. that isn't playing nice.

**Comment by MartoA** [comment]
Thanks, reinstalling worked, everything is fine now:)
