### ISSUE TITLE
can no longer use tinkers to create pulsating iron

### ISSUE THREAD

**Issue by MrGundum** [Cazadorsniper/PO3#1296]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.59
**Pack Mode (Normal, Titan, Kappa):kappa
**Singleplayer, Multiplayer, or LAN?:Multi

**Description:**
Updated to new version and can no longer alloy pulsating iron in smeltery tank, used to be ender pearls and iron to make it
**Steps to reproduce:**
place 1 ender pearl and  4 iron chunks into smeltery, they do not alloy together
**Crash log (use pastebin or issue will be closed):**
Na

Unless the recipe was removed and i just didn't notice it in change log.
so the only way to make it now is the alloy smelter?

**Comment by ItsTheGriz** [comment]
You may be able to get the developer to help you out. They changed a lot of the code from what it looks like and could have easily missed this alloy.

https://github.com/Mrthomas20121/Tinkers-Reforged/issues
