### ISSUE TITLE
Multiplayer Server Crash-report

### ISSUE THREAD

**Issue by Crawfort** [Cazadorsniper/PO3#1297]
**Pack Version: 3.3.59
**Pack Mode (Normal, Titan, Kappa): Normal
**Singleplayer, Multiplayer, or LAN?: Multiplayer

**Description: 
I tried several times, I could not install the server. Sorry if the problem is from me, I couldn't understand.

**Crash log (use pastebin or issue will be closed):
https://pastebin.pl/view/518b0795

**Comment by Cazadorsniper** [comment]
Try replacing (copy/paste) Aroma Mining Dimension config with the client (singleplayer) config.
