### ISSUE TITLE
Mismatching recipes for void workbench

### ISSUE THREAD

**Issue by Tralomine** [Cazadorsniper/PO3#1298]
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** The void workbench craft is different (and way easier) if you use the Basic Crafting Table from extended crafting instead of the Advanced Arcane Workbench from Lordcraft, and this is very probably not wanted since you can then craft it way before you're suposed to

**Comment by Cazadorsniper** [comment]
I'm not worried about it.
