### ISSUE TITLE
Neutral Steel of the fifth Degree.

### ISSUE THREAD

**Issue by Exokay** [Cazadorsniper/PO3#1299]
**Pack Version:** 3.3.58a
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** When trying to Craft Neutral Steel of the fifth Degree the Alloy Smelter "ate" a lot of fourth Degree Steel.

**Steps to reproduce:**
Place 5 ingots of fourth Steel in every slot and see then all getting crafted to 1 Ingot.
The original recipe says 1/1/3 but in our case we managed to craft 1 Ingot with 5/5/5

**Crash log (use pastebin or issue will be closed):** No crash etc.

**Comment by ItsTheGriz** [comment]
This bug was already reported/closed. Read #1200 for info.

I believe it is fixed in 3.3.59 as I don't have this problem.
