### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by datsniper** [Cazadorsniper/PO3#1303]
**Pack Version:** 3.3.59
**Pack Mode:** Normal
**Multiplayer**

**Description:**
Can't run the server, after downloading the files and extracting them to a folder, clicking start only flashes the command prompt and clicking the forge server file doesn't do anything. After adding a pause line to start.bat, I was able to see the full error message. I tried a previous version of the server, but same problem occurred. This could be a problem with my java version, but it should be relatively new and i don't want to start reinstalling it just yet.

**Crash log:**
https://pastebin.com/veStKeFa

**Comment by tom380** [comment]
I had the same problem on my ubuntu server. But when i changed my openjdk version from 11 to 8 it worked

**Comment by raapid** [comment]
same
