### ISSUE TITLE
Server crashing after a couple minutes

### ISSUE THREAD

**Issue by Imranzi** [Cazadorsniper/PO3#1304]
Pack Version: 3.3.59
Pack Mode: Normal
Multiplayer

Description
Tried to start up a new server using the Skylands world-type. After a few minutes of spawning in the server would crash. Restarting the server allows it to load again but continues to crash after some time. 
If anyone could help us out that would be greatly appreciated. 

Crashlog
https://pastebin.com/W5CWwFeN

**Comment by KangyKSLG** [comment]
I'm also getting this error. Just started happening around 10 hours ago. Also on a Skylands world and also on a server. 1 of my crashes is different but i'll post all 3 crash logs anyway. If you'd rather I make a new issue @Cazadorsniper let me know please

[PO3 Server Crashes.zip](https://github.com/Cazadorsniper/PO3/files/4902492/PO3.Server.Crashes.zip)
