### ISSUE TITLE
Item Placeholder bug or corrupt save?

### ISSUE THREAD

**Issue by Worsleychase** [Cazadorsniper/PO3#1305]
**3.3.59**
**Normal**
**Local Server**

Description: Item placeholders in quests: 
Mana I/O Hatch
Ember I/O Hatch
Wireless Pattern Terminal
Wireless Fluid Terminal

No idea what is causing it. Can't find any open reports on same bug. Used the same world file from 3.3.58A and just put it into the 3.3.59 server folder.

**Comment by GertJanH** [comment]
3.3.59 Changelog (Always Backup your world before updating and "/bq_admin default load" after updating)

run /bq_admin default load and your questbook wil be updated

**Comment by Worsleychase** [comment]
> 3.3.59 Changelog (Always Backup your world before updating and "/bq_admin default load" after updating)
> 
> run /bq_admin default load and your questbook wil be updated

Thank you so much!
