### ISSUE TITLE
Fluid Transposer Stops Working

### ISSUE THREAD

**Issue by RogueInstinct** [Cazadorsniper/PO3#1306]
Pack Version: 3.3.59
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: When using a fluid transposer with a phantomface, phantom liquid face, and phantom energy face while the transposer is surrounded by thermal mediators, it will stop working. Items, liquid, and power are still input, but the transposer will not craft. This is for neutral steel of the first, second, third, and fourth. The issue is only solved when you break the transposer, the phantomface, and the phantom liquid face then replace and relink them.

Steps to reproduce:
Create a tower of alternating thermal mediators and fluid transposers. Connect phantomfaces, liquid faces, and energy faces to the transposer. Cover all sides of the transposer with thermal mediators. After a while, one or several transposers will stop filling but will still have power, items, etc. Alternatively, it seems leaving the area, even when it's chunkloaded, for 5+ minutes also seems to cause this issue.

Crash log (use pastebin or issue will be closed): No crash etc.

**Comment by RogueInstinct** [comment]
Just wanted to add, here's a video showing the issue as I know the description is a bit convoluted. https://www.youtube.com/watch?v=zA_KSdVPGyk&feature=youtu.be

**Comment by Cazadorsniper** [comment]
Should need less of them next update.
