### ISSUE TITLE
Pressure Chamber destroying input items

### ISSUE THREAD

**Issue by Uzukru** [Cazadorsniper/PO3#1307]
So, I'm having this big problem with the pressure chamber, first time this hapenned I just rebuilt the structure by breaking a block, it seemed to work at first, but some time later it happened again and again. It will be impossible to keep working with, because I won't be able to automate it and also takes some time to recover presurre. It seems like in the moment that the item gets into the PC, the moment when it should go to the middle it just vanishes. Would really apreciate some help.

**Comment by VoidedOut** [comment]
Maybe you should try and get a video of this happening?
