### ISSUE TITLE
Wheat error?

### ISSUE THREAD

**Issue by Powersen** [Cazadorsniper/PO3#1308]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Powersen** [comment]
Sorry what i meant to say is that it is multiplayer, and it wouldnt let me join the world because of an error with the wheat recipie
I dont understand, it is on normal, and lan. I had uninstalled and reinstalled the pack, but nothing worked

**Comment by Cazadorsniper** [comment]
Copy the client scripts folder and replace the server's scripts folder with the client's.
