### ISSUE TITLE
visual glitch

### ISSUE THREAD

**Issue by domhugs** [Cazadorsniper/PO3#1309]
3.3.59
kappa
single

after a short amount of time in multiple worlds i have had a visual glitch where walking/ flying would send ure camera flying across the map to only stop if u let go of wasd
make new world wait a min or 2 and use the walk function

didnt crash

if u would like video footage please dm me on discord :domhugu#6997

**Comment by Cazadorsniper** [comment]
Check your BetterFPS algorithm use anything but Taylor's.
