### ISSUE TITLE
Getting unbearable fps

### ISSUE THREAD

**Issue by soulfoood** [Cazadorsniper/PO3#131]
I'm getting about 2-3 fps with all my graphics on the lowest settings. I have a decent computer with an rx 580, a ryzen 5 2600 and plenty(8) of ram allocated on the twitch app. I have about 20 in total. I feel like I should be able to run this pack pretty well. Any advice?

Edit: I've reinstalled this pack many times as well as repairing minecraft.
Note: I'm on the Twitch App if that helps.

**Comment by CraftalotReloaded** [comment]
20GB of ram is a strange amount so i wanna be sure you actually got 20GB of ram and not like 8GB

**Comment by soulfoood** [comment]
I know it sounds weird that I have only 20 and not like 16. It's because my CPU cooler blocked me from putting in more RAM and I'm to lazy to flip the cooler so I can put in more. I have 20 in total and about 8 allocated like said before.

**Comment by soulfoood** [comment]
@CraftalotReloaded dont really think I need a log for this do I? Here
[latest.log](https://github.com/Cazadorsniper/PO3/files/2949019/latest.log)

**Comment by Cazadorsniper** [comment]
Is there a lot of entities or tileentites around you? Have you tried letting it load up a bit?

**Comment by soulfoood** [comment]
All I did was start up a garden of glass world and I get 2-3 fps. I let it sit for like an hour and it didn't work

**Comment by CraftalotReloaded** [comment]
@soulfoood A latest log is always usefull for performance issues and crashes
You do however have 4GB allocated rather than 8GB so id suggest you try giving it more but i believe 4GB would be sufficient to handle an empty world

**Comment by Cazadorsniper** [comment]
yeah add 2G of ram.

**Comment by mnm358** [comment]
I had the same problem (it may be an incompatibility issue with AMD cpus or with RX580; i also have this graphic card). I solved it by going to FoamFix config and put "client.disableTextureAnimations" to TRUE .I'm 99% sure this is the problem.

**Comment by soulfoood** [comment]
Yeah, i figured this out finally. Now it's time to grind the frick out of the begining....
