### ISSUE TITLE
Modular Auto Sieve is slower than expected

### ISSUE THREAD

**Issue by mkaito** [Cazadorsniper/PO3#1310]
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Single

**Description:**

This is entirely subjective, and I'll accept a "works as intended", but I figured I'd bring it up anyway.

I just built the modular auto sieve after a long time using a grid of 9x9 waterwheel-powered diamond mesh sieves. I just got my first fission reactor up and running, and with the excess power I figured I'd upgrade my sieving. Turns out, it was actually a huge downgrade. Just eyeballing, it seems to process about 2 items per second, while my former 9x9 grid did 81 items every 2-3 seconds. So from an average ~27 items/second to ~2 items/second. So I'd have to build 14 of these just to match the speed of the early game sieve.

Maybe you'll say that I'm just supposed to build 20 of them, but right now it feels quite underwhelming. I tried dropping a Horologium anchor on it, but it doesn't seem to do anything.

**Steps to reproduce:** N/A

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by VoidedOut** [comment]
Are they enchanted with sieve efficiency and sieve fortune? They help a lot.

**Comment by mkaito** [comment]
Nope, the books don't seem to have a recipe, at least in Kappa mode, and I never found them anywhere.

**Comment by VoidedOut** [comment]
Enchantment table to get them then you can use bibliocraft to dupe the books

**Comment by mkaito** [comment]
I believe you might have me wrong. My issue is that the modular machines auto sieve is slower than I expected. My wooden sieves were working just fine, even without enchanting the meshes.

I'm considering just tearing down the modular sieve and rebuilding the waterwheel setup I was using, and I didn't know you could use the enchantment table to get sieve luck and sieve efficiency, so thanks for that!

I'd still like to hear what Cazadorsniper's opinion might be on the subject.

**Comment by VoidedOut** [comment]
Yeah modular sieve sucks ass. It’s nowhere near as good as even a 3x3 setup of the waterwheel sieves.
3x3 autosieves that are fully enchanted pulled me through kappa until I got to magical crops

**Comment by mkaito** [comment]
> Yeah modular sieve sucks ass.

I mean, I was trying to be diplomatic here :joy:
