### ISSUE TITLE
Twilight Oak Logs gives 4x Planks

### ISSUE THREAD

**Issue by CrankySupertoon** [Cazadorsniper/PO3#1312]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
Read the info

**Comment by Cazadorsniper** [comment]
This is fine.
