### ISSUE TITLE
Huge negative numbers

### ISSUE THREAD

**Issue by ArkhamAggron** [Cazadorsniper/PO3#1315]
Pack Version: 3.3.59
Pack Mode (Normal, Titan, Kappa): Titan
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: I put a Random Things Ender Specter Coil on an Actually Additions Farmer and came back to the power being massively in the negatives.

Steps to Reproduce: I'm not sure how it happened, it didn't crash my game and retains the value when i break it like normal.

![2020-07-12_12 22 30](https://user-images.githubusercontent.com/57226567/87501934-f41f4100-c625-11ea-8810-46398ede7723.png)

**Comment by MrGundum** [comment]
Please read the wtf section in the change log, it explains this.
