### ISSUE TITLE
Glow mushroom overgrows the whole of the erabus world

### ISSUE THREAD

**Issue by fibrowolf** [Cazadorsniper/PO3#132]
**Pack Version:**3.0.38

**Description:** Glow mushroom overgrows the whole of the erabus world

**Steps to reproduce:** we left a chicken chunk loader with a miner for 24 hours and came back to a mushroom world

**Crash log:**

**Comment by Cazadorsniper** [comment]
lol

**Comment by vadis365** [comment]
working as intended. :P
