### ISSUE TITLE
Removed Mod Locked Out Quest Line

### ISSUE THREAD

**Issue by fasttrak48** [Cazadorsniper/PO3#1320]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):**Normal (started 6 months ago not positive Not Kappa)
**Singleplayer, Multiplayer, or LAN?:**Single

**Description:** Stopped the mod for several months came back in early July and updated to current release. It appears Landia and several mods removed. Doing the Iota armor quest line and Thorium and Tungsten quest removed yet armor still in the quest book. How do I remove or toggle quest complete to move on. Just shows a question mark on those two quests and can't continue with out cheating in the next armor and would prefer not to do that. I did look through the 65 other Bug Reports and did not see this there.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by VoidedOut** [comment]
When you update the pack you have to run a command to update the questbook. If I remember it’s “/bq_admin default load” or something. It’s in the text when you check the version you’re updating to.

**Comment by fasttrak48** [comment]
Thank you, VoidedOut, totly missed needing to run that update and that fixed my issues. Much appreciated.
