### ISSUE TITLE
LordCraft skill Earth-Shake seemingly impossible to cast

### ISSUE THREAD

**Issue by pie3636** [Cazadorsniper/PO3#1324]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Single player

**Description:** When going through the Lordic quests, eventually the third earth spell is unlocked (Earth-Shake). A quest requires to cast it 25 times. This quest cannot be cancelled since it is a "special" quest. The problem is, even with the new spell selected, it seems it can't be cast or anything, whether it be NPCs, animals, mobs, on the ground or in the air. Since there is no documentation about spells anywhere (in-game or online), it is also very hard to figure out if the spell is bugged or if it's meant to be cast on a specific target that I haven't tried yet. All other spells so far, including from other elements, were at least valid on either monsters, NPCs or the ground.

**Steps to reproduce:** Go through the whole LordCraft quests, unlock the third Earth spell, try to cast it.

**Crash log (use pastebin or issue will be closed):** None

**Comment by quietust** [comment]
Is that particular quest required to progress through the PO3 quest tree? If not, you can probably just skip it.

**Comment by pie3636** [comment]
This quest is a lot farther than the minimum needed for PO3. I'm mainly doing it to get more LordCraft resources without having to mine/craft them, and to get more mana to make the lordic crafting table go faster.

**Comment by ItsTheGriz** [comment]
You can cast it. It has a minimum mana requirement. If you stored all your mana in the void crystal, you need to get it back out by shift clicking your crystal.

**Comment by pie3636** [comment]
I made sure my void crystal was empty before trying to cast it. I can cast all other earth spells (and other elements as well) without any issue. What kind of target are you aiming at when casting it?

**Comment by M-T-Rod** [comment]
I just encountered this problem and the fix is very simple... You need to be on the ground to cast the spell

**Comment by osirisgothra** [comment]
I had a comment about this but it kinda goes off track so i put it [here](https://pastebin.com/raw/ijSRcWu3)
