### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LubricatedSock** [Cazadorsniper/PO3#1325]
**Pack Version:** 3.3.59
**Pack Mode Normal
**On startup 

**Description:**
During startup the game loads for a while but then when it reaches the part where it says its initialising the too many items mod it crashes giving the enclosed crash report. 
[crash-2020-07-23_16.16.00-client.txt](https://github.com/Cazadorsniper/PO3/files/4967187/crash-2020-07-23_16.16.00-client.txt)

**Crash log (use pastebin or issue will be closed):**

**Comment by Caedis** [comment]
How much memory is in your system, and how much are you allowing MC to use?
