### ISSUE TITLE
Titanium Singularity not craftable

### ISSUE THREAD

**Issue by TonTonAsoX** [Cazadorsniper/PO3#1326]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.52**
**Pack Mode (Normal, Titan, Kappa): Normal**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: For craft the Titanium Singularity, we need a Titanium Block from ThermalSolars, BUT, when the block is crafted, he's always a Titanium Block from GalacticCraftPlanets, and it's impossible to get a block from Thermal (ForgeLexicon and Chisel dont work). So it's impossible to do the Titanium Singularity.**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Update the pack to 3.2.55.
