### ISSUE TITLE
JEI reports wrong diamond amounts when smelting diamond ore with redstone furnace

### ISSUE THREAD

**Issue by Kendragon7** [Cazadorsniper/PO3#1328]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I was checking JEI by pressing U for 'uses' on diamond ore to see which method would be most efficient. I saw that redstone furnace gave 2 diamonds on JEI and with the Flux Anodizer Augment, it gave 3 diamonds. But when I tried it, the redstone furnace only gave 1 diamond and with flux anodizer it gave 2.

**Steps to reproduce:** Check the uses of diamond ore and look at redstone furnace and redstone furnace with flux anodizer. In practice, the amounts don't match with JEI.

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by Cazadorsniper** [comment]
It only gives what JEI is telling me which is 1 and 2 with the augment.
