### ISSUE TITLE
Pneumaticcraft loop

### ISSUE THREAD

**Issue by wuast94** [Cazadorsniper/PO3#133]
**Pack Version:** 3.0.38

**Description:**
i want to create unassambled pcb but i cant.
i can do it with acid .. but i must take them to UV Light Box .. to craft this i need pcb blueprint and for this i need the amadron tablet. for the amadron tablet i need an air canister with 10bar pressure .. but i cant get over 5 bar pressure. for this i need advanced pressure tube where i need the unassambled pcb

all other ways are the same. cant get over 5 bar pressure or cant create unassambled pcb

**Comment by DangerHSW** [comment]
you dont need 10 bar pressure, an empty one works.

**Comment by wuast94** [comment]
no it di
