### ISSUE TITLE
Suggestion: add crafting calculator

### ISSUE THREAD

**Issue by Trevlouw** [Cazadorsniper/PO3#1330]
I have seen nothing for suggesting stuff so Im adding mine here, the crafting calculator is an item from Just enough calculation (Jec) it allows players to calculate the amount of resources it takes to craft anything in jei which can help players save resources when trying to get items for philosophers stone, transmutation table, ect… it is extremely useful in kappa mode because of the cost of several things are high so if you want to craft as little dark matter as possible for the transmutation table the calculator can save you resources and makes the pack less frustrating. here is the link to the curseforge page: https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

**Comment by Cazadorsniper** [comment]
Not trying to add mods at this time unless I absolutely have to.
