### ISSUE TITLE
Electrotine Alloy ingot recipe, IE Arc Furnace

### ISSUE THREAD

**Issue by Drummerboyno** [Cazadorsniper/PO3#1331]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
 Kappa
  Singleplayer
**Description:**
In JEI there is a recipe for making red alloy ingots from projectred core in the immersive engineering arc furnace(1x copper ingot, 4x Redstone dust). There is not a recipe for electrotine. But both of these can be made in the IE ally kiln, Looking in the Kappa.immersive.zs file it looks like the recipe should exist. Is this intended, if not would you add it in the pack it would be very helpful. Would be the same recipe as in the alloy kiln.

**Comment by Cazadorsniper** [comment]
Yeah, I can do that when I can.
