### ISSUE TITLE
Ticking Entity Crash, Backups 

### ISSUE THREAD

**Issue by UndoneDestiney** [Cazadorsniper/PO3#1333]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3,3,59
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
I was playing yesterday and everything was fine, today I go to play and it closes and the crash report says there is a ticking entity, so I load up a backup and try to play but I get the same error, I tried with 3 other backups but I got the same message every time, 1 of the backups I had reloaded and started playing with a couple of days ago and it was fine, even with that same backup the problem still happened, the world doesn't even finish loading before it crashes, everything was fine yesterday I really don't know what happened. I even completely restarted my computer

**Steps to reproduce:**
load up the game, start to load the world, crash

**Crash log (use pastebin or issue will be closed):**
[crash-2020-07-29_15.12.35-server.txt](https://github.com/Cazadorsniper/PO3/files/4997239/crash-2020-07-29_15.12.35-server.txt)
[crash-2020-07-29_15.21.42-server.txt](https://github.com/Cazadorsniper/PO3/files/4997240/crash-2020-07-29_15.21.42-server.txt)
[crash-2020-07-29_15.30.16-server.txt](https://github.com/Cazadorsniper/PO3/files/4997241/crash-2020-07-29_15.30.16-server.txt)
[crash-2020-07-29_15.38.57-server.txt](https://github.com/Cazadorsniper/PO3/files/4997242/crash-2020-07-29_15.38.57-server.txt)
[crash-2020-07-29_15.48.01-server.txt](https://github.com/Cazadorsniper/PO3/files/4997243/crash-2020-07-29_15.48.01-server.txt)
[crash-2020-07-29_15.56.58-server.txt](https://github.com/Cazadorsniper/PO3/files/4997244/crash-2020-07-29_15.56.58-server.txt)
[crash-2020-07-29_16.07.19-server.txt](https://github.com/Cazadorsniper/PO3/files/4997245/crash-2020-07-29_16.07.19-server.txt)

**Comment by UndoneDestiney** [comment]
Nothing is chunk loaded by the way and I saw similar issues but nothing was exactly the same so I opened up an issue

**Comment by Caedis** [comment]
looks like a translocator is causing the issue. Do you remember what you had connected with translocators?

**Comment by UndoneDestiney** [comment]
the smeltery and crucibles should be the only ones but the had been connected for a while before all this happened

**Comment by UndoneDestiney** [comment]
I've had fluid translocators attached to the smeltery and conduits practically since I began playing
