### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by BlueOnDev** [Cazadorsniper/PO3#1334]
**Pack Version:3.3.59**
**Pack Mode Normal:**
**Multiplayer**

So we tried to start a server, on a normal world (we added Biome O'Plenty bc of the better looking biomes), first time after launching it, we didn't logged in, went to sleep, and it crash a few hours after. Now it crash after 5 minutes of it being started.
The server also crashes when we tried to launch it in 3.3.58A

**Crash log https://pastebin.com/6fjVE2s2*

**Comment by Cazadorsniper** [comment]
max-tick-time=-1
In the server.properties.
