### ISSUE TITLE
Kappa Mode Shifting Star Astral Sorcery

### ISSUE THREAD

**Issue by nanaki234** [Cazadorsniper/PO3#1335]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*3.3.59*
**Pack Mode (Normal, Titan, Kappa):*Kappa*
**Singleplayer, Multiplayer, or LAN?:*Singleplayer*

**Description:*Crafting the shifting star does not complete the quest in the quest book*

**Steps to reproduce:*Craft the shifting star inside the starlight crafting altar*

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Try crafting a new one and waiting for BQ to detect it.

**Comment by quietust** [comment]
I just crafted two of them in the Iridescent Altar and neither of them triggered the quest.
They also don't stack with each other, presumably due to special NBT (which might be interfering with the quest?).
