### ISSUE TITLE
Tomatillo and Juniperberry seeds can't be planted in crop sticks

### ISSUE THREAD

**Issue by Rseding91** [Cazadorsniper/PO3#1337]
**Pack Version:**
3.3.59

**Pack Mode (Normal, Titan, Kappa):**
Kappa

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Tomatillo and Juniperberry seeds can't be planted in crop sticks. They are missing from the agricraft config folder where all of the other harvestcraft seeds are setup to work with crop sticks.

Note: I don't know if this is intended but based off every other seed working in crop sticks this seems like an oversight? Also there's a changelog line specific to these two seeds which makes me think they got added in a point after the agricraft compatibility was added and just forgotten about.

**Steps to reproduce:**
1 Load up the game.
2. Try to place either seed in a crop stick

**Crash log (use pastebin or issue will be closed):**
No crash happens.

**Comment by Cazadorsniper** [comment]
Because they are newer seeds.
