### ISSUE TITLE
Pam's Flax Seeds in crop sticks produce string instead of flax

### ISSUE THREAD

**Issue by Rseding91** [Cazadorsniper/PO3#1338]
**Pack Version:**
3.3.59

**Pack Mode (Normal, Titan, Kappa):**
Kappa

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
When Pam's flax seeds in crop sticks they produce string instead of Pam's flax. When planted normally and harvested they still produce flax.

**Steps to reproduce:**
1. Plant Pam's flax seeds in crop sticks
2. Harvest the seed with right click
3. Observe string is harvested

Note: I'm not sure if this is intended but every other seed I have planted produces the same thing when in crop sticks vs not so I'm reporting it here.

**Crash log (use pastebin or issue will be closed):**
No crash happens.

**Comment by Cazadorsniper** [comment]
I believe that is intended.

**Comment by Rseding91** [comment]
I mention it because flax is one of the items required for the Ultimate Stew.

**Comment by Rseding91** [comment]
My bad... string *or* flax is required. If you consider this intended feel free to close it.

**Comment by Rseding91** [comment]
Actually it doesn't matter since flax only turns into string anyway so I'll close this myself :)
