### ISSUE TITLE
i can seem to pull out my dev/null from the AE2 system 

### ISSUE THREAD

**Issue by 73Salmin** [Cazadorsniper/PO3#1339]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Singleplayer, Multiplayer, or LAN?:** single player

**Description:**  it isnt 100% chance that the dev/null will get stuck but it happens most of the time and when it does happen you cant pull it out at all 

**Steps to reproduce:** simply placing the dev/null into the AE2 system

**Comment by Cazadorsniper** [comment]
Export bus with fuzzy card then it should come out.

**Comment by 73Salmin** [comment]
it worked thanks
