### ISSUE TITLE
Blood Magic: Sentient Sword Quest

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#134]
Pack Version: 3.0.38

Description: I have crafted the Sentient Sword, but the quest does not complete. You can see from the screenshot it is in my inventory, but the quest is not completed. I've tried dropping it and picking it up again as well as the "Detect/Submit" button.

Steps to reproduce: Craft Sentient Sword in Hellfire Forge and try to complete the quest.

Crash log: N/A

![2019-03-10_01 04 23](https://user-images.githubusercontent.com/19508559/54078900-35387000-42d1-11e9-980b-cba99a7da7ef.png)

**Comment by Cazadorsniper** [comment]
OG found this issue, already made an attempt to fix it next update.
