### ISSUE TITLE
Dragon egg?

### ISSUE THREAD

**Issue by LeCastor** [Cazadorsniper/PO3#1340]
hey guys!
I would like to know if there is any way to get new dragon eggs. I respawned the ender dragon few times but no egg spawned.

(I'm in kappa mode)

**Comment by Cazadorsniper** [comment]
They should be spawning on the bedrock portal.

**Comment by LeCastor** [comment]
Finally, I think there a bug that makes the dragon egg spawn beside the bedrock portal, just above a torch. That makes it drop as an item and that's why I didn't see it earlier.
Thanks for your fast answer tho!
