### ISSUE TITLE
Unable to craft items in Multiplayer kappa mode (able to craft with the same recipe and client in single player)

### ISSUE THREAD

**Issue by Remedivh** [Cazadorsniper/PO3#1342]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/files/2975771
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Unable to craft workbench or engineer's hammer in kappa mode in multiplayer (works fine in singleplayer)

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**No crash

**Comment by Cazadorsniper** [comment]
copy/paste scripts from the client to the server files.
