### ISSUE TITLE
Quests that should have gotten removed are now a question mark.

### ISSUE THREAD

**Issue by Cornflakes1** [Cazadorsniper/PO3#1344]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.3.59
Pack Mode Normal
Singleplayer

**Description:**
The Landium quest, tiny ember-crystal cell I/O quest, Mana I/O quest, Thorium armor quest, Tungsten armor quest, To Landia quest, and void mini-boss section quests all appear as question marks and I am unable to complete them. 
**Steps to reproduce:**
Open quest book in an existing world before the update that removed Landcraft
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Should read the very top of the changelog.
