### ISSUE TITLE
errors while installing Project Ozone 3

### ISSUE THREAD

**Issue by awesomeshark09** [Cazadorsniper/PO3#1346]
![Annotation 2020-08-11 140435](https://user-images.githubusercontent.com/69532412/89938147-b63d1a80-dbdb-11ea-9194-1c1c338102bd.png)
tried restarting the twitch client that didn't work, and other modpacks wont install

**Comment by andreivoinea** [comment]
Not dev or anything but been scouring the internet today for an answer to this. It's most likely a twitch thing. It happened to almost all mods. Most likely we'll have to wait for Twitch to fix it...
