### ISSUE TITLE
Can't install mod pack due to error

### ISSUE THREAD

**Issue by SwordDecoy** [Cazadorsniper/PO3#1347]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.59**
**Pack Mode (Normal, Titan, Kappa): Normal**
**Singleplayer, Multiplayer, or LAN?: None**

**Description: 
![realpain](https://user-images.githubusercontent.com/69541339/89944981-83902380-dbd5-11ea-9cec-a5120062184c.png)
This issue has been happening with PO2 also, I am installing this from the twitch launcher.**

**Steps to reproduce: install PO3**

**Crash log (use pastebin or issue will be closed):**

**Comment by andreivoinea** [comment]
Not dev or anything but been scouring the internet today for an answer to this. It's most likely a twitch thing. It happened to almost all mods. Most likely we'll have to wait for Twitch to fix it...

**Comment by SwordDecoy** [comment]
Update: I may have figured that this is probably due to Curse Forge moving to OverWolf and is no longer staying with Twitch, this can be found here: https://medium.com/overwolf/a-new-home-for-curseforge-44cbb3add844
I heard something about this problem because of the messed up IDs through Twitch and Curse Forge, so I think we are going to have to wait for twitch to say something about this or fix it.
