### ISSUE TITLE
Astral Sorcery can´t craft some recipies 

### ISSUE THREAD

**Issue by wuast94** [Cazadorsniper/PO3#135]
**Pack Version:** 3.0.38

**Description:** as shown in picture i cant craft shifting start (in this example) should be all right but it don´t show on right .. and right clicking with wand not do anything. 

![grafik](https://user-images.githubusercontent.com/16965460/54079013-e9d39100-42d3-11e9-8a31-6246b656d5d9.png)

**Comment by martinschuberteu** [comment]
The red bar means you structure is invalid. Can you please check if you have the right blocks in the right place? If you can't find any issue, post images of the structure.

**Comment by freqoutmini** [comment]
This is still an issue, the resonating gem won't craft in the starlight infuser with the right temple built around it. also the animation for the gem in the infuser and light well is right either, it looks like it's spinning in the bottom instead of rotating above it

**Comment by martinschuberteu** [comment]
> This is still an issue, the resonating gem won't craft in the starlight infuser with the right temple built around it. also the animation for the gem in the infuser and light well is right either, it looks like it's spinning in the bottom instead of rotating above it

I had no issues with creating resonating gems in the starlight infuser. Can you post screenshots of your structure? Also the spinning glitch was reported as #49

**Comment by freqoutmini** [comment]
![2019-03-10_08 07 38](https://user-images.githubusercontent.com/45827330/54085439-39ce4a00-430c-11e9-8275-9a3876ab77ab.png)
![2019-03-10_08 07 07](https://user-images.githubusercontent.com/45827330/54085440-3b980d80-
430c-11e9-9114-77652d1b08eb.png)
![2019-03-10_08 07 28](https://user-images.githubusercontent.com/45827330/54085442-3dfa6780-430c-11e9-9985-86a308c114e4.png)

**Comment by freqoutmini** [comment]
![2019-03-10_08 07 07](https://user-images.githubusercontent.com/45827330/54085451-5f5b5380-430c-11e9-90a0-cf0a21060a13.png)

**Comment by martinschuberteu** [comment]
I can't see any issue in the pictures and it looks like the right marble on the bottom and no liquid starlight missing.

**Comment by freqoutmini** [comment]
i can't figure it out either, I've done it before in other mod packs

**Comment by Kyks20** [comment]
Check that u use all astral sorcery marble and not other marbles. cos i had same problem whit altar used other mod marble and altar was red. but the shape was correct.

**Comment by billyty08** [comment]
Maybe just stating the obvious but did you click on the infuser with the wand to start the transformation?

**Comment by Ravalli03** [comment]
I had similar issues with the spinning aquamarine and not crafting, I removed itemphysics mod and it now works

**Comment by freqoutmini** [comment]
> Maybe just stating the obvious but did you click on the infuser with the wand to start the transformation?

this solved it, i thought is was a passive craft

**Comment by PlacidK** [comment]
I had a similar problem.
I placed the starlight infuser before the structure was finished and it didn't work, not even when i clicked it with the wand.
Breaking the infuser and replacing it fixed it.
