### ISSUE TITLE
Unlimited barrel upgrades too easy to get

### ISSUE THREAD

**Issue by HopefulFire** [Cazadorsniper/PO3#1351]
# Use the search function before reporting to see if the issue has been reported before.
**3.3.59**
**Kappa**
**Multiplayer**

** Unlimited barrel upgrades only require a small number of diamonds/ emeralds/ nether star which are all really easy to get early**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
so you want me to put an infinity ingot in it?

**Comment by HopefulFire** [comment]
Well maybe 8 blocks of emeralds instead of just four :) Sorry if I came off as obtuse, I really like this modpack and saw what effort went into the crafting recipes for the quantum storage and it just seemed a bit cheaty to use the barrels

**Comment by Cazadorsniper** [comment]
Let me just say that this is intended.

**Comment by HopefulFire** [comment]
OK, thanks for the consideration
