### ISSUE TITLE
Mobs are instakilling me even i have good armor

### ISSUE THREAD

**Issue by Vojta7022** [Cazadorsniper/PO3#1352]
Every mob (except skeleton) instakill me (hit me once and i am dead). I dont know why.

**Comment by Cazadorsniper** [comment]
Should probably stop killing many bosses.

**Comment by Vojta7022** [comment]
I didnt kill any boss.

Dne st 19. 8. 2020 13:06 uživatel Cazadorsniper <notifications@github.com>
napsal:

**Comment by Cazadorsniper** [comment]
then are you playing on a server?

**Comment by Vojta7022** [comment]
Yes, i am.

Dne st 19. 8. 2020 14:44 uživatel Cazadorsniper <notifications@github.com>
napsal:

**Comment by Cazadorsniper** [comment]
then someone on the server is killing too many bosses.

**Comment by Vojta7022** [comment]
Oh ok. Thanks

Dne st 19. 8. 2020 19:26 uživatel Cazadorsniper <notifications@github.com>
napsal:
