### ISSUE TITLE
 Storage bus from AE2 causes autocraft freeze.

### ISSUE THREAD

**Issue by ReturnX2** [Cazadorsniper/PO3#1353]
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I have a ME and it is connected to several storage buses that are connected to barrels from the YABBA mod. After clicking the "next" button when autocrafting any item, the server is freezes for a few seconds.

**Steps to reproduce:** 
1. Connect the storage bus to the item barrel connector (Barrels must contain millions of items.)
2. Start autocrafting any item and click on the "next" button
3. The server freezes for a few seconds.

**Crash log (use pastebin or issue will be closed):**No crashes

**Comment by Cazadorsniper** [comment]
recommend putting all items in me storage drives not barrels with storage bus attached.
