### ISSUE TITLE
Galacticraft + Waila bug

### ISSUE THREAD

**Issue by davo899** [Cazadorsniper/PO3#1354]
In HYWLA>mcp>mobius>waila>addons>capability>HUDHandlerEnergy.java, getNBTData calls getCapability on the tileEntity (what the player is looking at) with a null EnumFacing object. When called on galacticraft's TileBaseUniversalConductor, getCapability calls getTileEntityOnSide on a new BlockVec3 instance with that null EnumFacing object. Inside getTileEntityOnSide, .ordinal() is called on the EnumFacing object passed in, so the server just spams NPEs and crashes as soon as a player looks at one of these blocks.

**Comment by Cazadorsniper** [comment]
what is the version of galacticraft?

**Comment by davo899** [comment]
I have 4.0.2.280

**Comment by Cazadorsniper** [comment]
can you post your findings here? https://github.com/micdoodle8/Galacticraft/issues make sure you follow the issue template though.

**Comment by davo899** [comment]
Will do
