### ISSUE TITLE
Issue with server files #2

### ISSUE THREAD

**Issue by hdhdn** [Cazadorsniper/PO3#1355]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** Current
**Pack Mode (Normal, Titan, Kappa):**Normal
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**I had opened a previous issue about this, the newest server file download does not include any of the needed files and there is no videos to help, THe owner even messaged me and said this, there is no videos or forums dealing with how to fix this

**Steps to reproduce:**
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Current isn't a version and the files are present.
