### ISSUE TITLE
journei map lagging game

### ISSUE THREAD

**Issue by luki222555** [Cazadorsniper/PO3#1356]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.59
**Pack Mode (Normal, Titan, Kappa):**
kappa
**Singleplayer, Multiplayer, or LAN?:**
single player 

**Description:**
when i open save lerver lag and wont play normal i use 10Gb or ram . I tried reinstal game and dont wokr.  i uploaded log from console .

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/urUwqvRG

**Comment by Cazadorsniper** [comment]
When did the server start?

**Comment by luki222555** [comment]
yea from begining , only worked restore 2 hours old backup

**Comment by Cazadorsniper** [comment]
Journeymap is likely not at fault.

**Comment by luki222555** [comment]
yea , now i think that too , that ID what is mising in console log is item duct opaque and harden fluid duct opaque , but i don't know how is posible lost texture in the save files

**Comment by Cazadorsniper** [comment]
I'm unsure how long you've been playing on the server or if there are other people playing on it too.

**Comment by luki222555** [comment]
im playing on local game not server , and save is from version with ladia mod

**Comment by Cazadorsniper** [comment]
I recommend updating the pack. You could try using optifine also.

**Comment by luki222555** [comment]
I update modpack , and i found problem , too many entity in the world at the same time , that cause some estreme lag in the world , now o found it .

**Comment by Cazadorsniper** [comment]
ok
