### ISSUE TITLE
Necronomicon disappears or downgrades when logging in

### ISSUE THREAD

**Issue by zenderman333** [Cazadorsniper/PO3#1359]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.1.45
**Pack Mode (Normal, Titan, Kappa): normal
**Singleplayer, Multiplayer, or LAN?: singleplayer

**Description:**
If a Necronomicon is left on a charging pedestal when someone logs out and then logs back in, the Necronomicon will either completely disappear or will downgrade (from dreadlands to abyssal wasteland, etc.)

**Steps to reproduce:**
1) Log in to a PO3 world
2) place a Necronomicon on a charging pedestal
3) log out of the PO3 world
4) Log back into the PO3 world
5) discover that the Necronomicon is missing

**Crash log (use pastebin or issue will be closed):**
Game did not crash.

**Comment by quietust** [comment]
The current version of PO3 is 3.3.59 (and reporting bugs in old versions typically doesn't help much), but I should mention that I've seen this exact same thing happen in my Titan mode playthrough, though it only happened _once_ - after that, I made an effort to remember to remove it from the charging pedestal before saving, and eventually I switched to using a Sacrificial Altar next to my mob farm (to avoid all of the crap the statues do) and I never saw the problem again.
