### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by itsjusttriz** [Cazadorsniper/PO3#1361]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
(*Not sure if it happens on a server*)
**Description:**
Ability to dupe any stackable item to a full stack.

**Steps to reproduce:**
Advanced item collector connected to inventory.
Any stackable item in top left inv slot.
Go into Item Collector GUI.
Shift click stackable item and itll dupe once moved to bottom right of inv slot.

Proof: https://clips.twitch.tv/AthleticSteamyPistachioFUNgineer

**Crash log (use pastebin or issue will be closed):**N/A

**Comment by Cazadorsniper** [comment]
I reported it to mod github.
