### ISSUE TITLE
Ancient codex don't unlock, cant read entries

### ISSUE THREAD

**Issue by Niklassthlm** [Cazadorsniper/PO3#1362]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*latest*
**Pack Mode (Normal, Titan, Kappa):*normal*
**Singleplayer, Multiplayer, or LAN?:*single*

**Description:*im done with the gamma questline and want to enter the Twilight forest, for this i need a glimmer crystal, i'm trying to figure out how to do it by using the manual, the book Ancient codex, but i cant unlock the entries, tried rightclicking. Please advise*

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
need to right click all the correct entries to unlock.
