### ISSUE TITLE
Energy Condenser MK2 not craftable

### ISSUE THREAD

**Issue by jasperfr** [Cazadorsniper/PO3#1363]
**Pack Version:** 3.3.59 for Minecraft 1.12.2
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
![mk2](https://user-images.githubusercontent.com/22079370/91668761-6634e200-eb0f-11ea-9c4a-cd4b432c055f.png)
Adding all the items to craft an ECmk2 with JEI will not show up the crafting result. Dragging and dropping any of the items will show the crafting result, but the ECmk2 is not obtainable. Upon trying to craft, the item pops back into the result grid. Shift+clicking allows the block to be inserted into the inventory, but will disappear and everything will revert back to the crafting table upon placement.

**Steps to reproduce:**
Insert all the items required for an energy condenser mk2 into an Ultimate Crafting grid by hand or with JEI.

**Crash log (use pastebin or issue will be closed):**
(Not available as this bug causes no crash)

**Comment by Cazadorsniper** [comment]
have you've tried charging the stone?

**Comment by jasperfr** [comment]
Charging the stone worked, thanks.
I would like to suggest that the questing description of the pack states that the stone requires to be charged, to prevent further confusion.
