### ISSUE TITLE
Cant change the level type for my server

### ISSUE THREAD

**Issue by Eskilrl** [Cazadorsniper/PO3#1366]
**Pack Version: 3.3.59**
**Pack Mode (Kappa):**
**Multiplayer:**

**Description: To begin with I am sorry if this is labeled wrongly. 

I have tried to create a server for me and my friends with the botania garden of glass world type. However, I can't seem to figure out how to use the "level-type = botania-skyblock". I have tried to put it in the "server" note, deleting the world file and generating a new one but it just made another vanilla world. The mods work perfectly, but we want the skyblock experience. I have found another post to this very problem but following the steps, I couldn't get it to start using forge (which was the solution there). This is my first attempt at a server and I'm sort of just copy-pasting everything willy nilly, so a direction from someone who has a bit of experience would be greatly appreciated :)**

**Comment by Cazadorsniper** [comment]
Get server files, start it up, accept eula, start it again (to generate the rest of the files), in server.properties change the level-type there, delete default world file, restart server, use .bat file to adjust ram in needed (.bat file is used to start the server).

**Comment by Eskilrl** [comment]
Yeah, the only problem is that I cant seem to use the .bat file to start the server? It does something for a split second but nothing else happens. I have posted an image of the .bat file below in case something is written wrong. (As of now I have only been able to use the "Minecraft-server" to start the server so I guess that is the issue).
![Merknad 2020-09-03 112124](https://user-images.githubusercontent.com/70664610/92096848-aa5a0800-edd7-11ea-93bf-ad294d7cc807.png)

**Comment by Eskilrl** [comment]
Never mind I got it working, thank you so much! I added a pause to the .bat file and found out that the problem was this: "The system cannot find the file C:\ProgramData\Oracle\Java\javapath\java.exe.", unfortunately, I don't really know how I got it working since everything I did was just searching if the files were where they should be (although I did re-install Java) but if anyone else has the same problem this video should help: https://www.youtube.com/watch?v=CRw3rF4hvjk :)
