### ISSUE TITLE
World Crashes on startup

### ISSUE THREAD

**Issue by calicoh** [Cazadorsniper/PO3#1367]
I was AFK on my normal mode world that I open to LAN with my friends. I decided to close the game (that was opened to LAN) so I exited to the title screen. It took too long do exit to title screen though, so I alt-f4ed my game. When I tried to start it up again later, it crashed upon loading the world. 
Edit: backups didn't work, they all have the exact same issue.

Here's my [crash report](https://pastebin.pl/view/16432ef0).
I've tried a few things to fix it, and I haven't had any luck. I'd really appreciate it if you could find a fix.
Thanks

**Comment by DestroyerBr** [comment]
Same thing happens to me, but the thing is: my world wont load at all. After i create a new world, my minecraft stops working.
