### ISSUE TITLE
Server crashes in Twilight Forest

### ISSUE THREAD

**Issue by lvlahos343** [Cazadorsniper/PO3#1368]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 1.12.2
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** When in the Twilight Forest (multiple locations, seemingly at random) the server crashes. I found this other post regarding a potential issue with the Evolved Enderman mod, but that fix didn't solve the issue (link below).

**Steps to reproduce:** Launch server; connect on a separate device; enter the Twilight Forest; game will typically crash in short order.

**Crash log (use pastebin or issue will be closed):** https://pastebin.pl/view/d7e2dec3

Edit: I realized the crash log I previously updated might've been caused by my attempts to fix the original error. I've included the original crash log here: https://pastebin.pl/view/b8c4f4b0

**Comment by Cazadorsniper** [comment]
in serrver.properties: max-tick-time=-1
