### ISSUE TITLE
Staff of Power not crafting

### ISSUE THREAD

**Issue by DeadlyNinja771** [Cazadorsniper/PO3#1371]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.59
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
The staff of power does not show up when ingredients are placed inside of crafting table
![2020-09-05_00 42 55](https://user-images.githubusercontent.com/70790256/92297865-8569b000-ef11-11ea-85dc-5f69054039b2.png)

**Comment by Cazadorsniper** [comment]
charge all the tools that have a bar on them.

**Comment by DeadlyNinja771** [comment]
![2020-09-06_10 50 01](https://user-images.githubusercontent.com/70790256/92328432-c2779480-f02e-11ea-9426-6298c2207917.png)

**Comment by Cazadorsniper** [comment]
Try draining or making new tools that aren't charged except for the katar and morning star.

**Comment by Andre36** [comment]
Don't charge the Flux-Infused Sword.

That works for me.
