### ISSUE TITLE
Random Java Crashes In Middle Of Game, Issue Just Started Today, Logs Included.

### ISSUE THREAD

**Issue by Aternias** [Cazadorsniper/PO3#1376]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.3.59
Pack Mode: Normal
Mode: Singleplayer

Description: Just today whenever I load up the game and play for around 5-10 minutes the game with just freeze, screen wil go black, then Ill get a Java(TM) Platform SE binary has stopped working. I've tried different RAM Allocations but none seem to change anything. Usually, this error is caused by a Graphics driver issue, but I'm on the latest driver and I've uninstalled and reinstalled twice.

Steps to reproduce: Just Playing the game, I was interacting with AE2 dense smart cables. For all I know the world could have a memory leak, but I was checking my memory utilization often and it stayed at around 60% at 8gb.

Crash log: https://pastebin.com/zgJJ1ZHn

**Comment by iEatNoodlez** [comment]
Looks like your log is cut short. Do you mind reposting or uploading the txt file to a repo?
