### ISSUE TITLE
Minecraft freeze at Loading-Completing Minecraft initialization (7/7) phase

### ISSUE THREAD

**Issue by rokolix** [Cazadorsniper/PO3#1380]
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Minecraft freeze at Loading-Completing Minecraft initialization (7/7) phase and give not responding.

**Steps to reproduce:**
Press play and wait.

**What I tried:**
-Waited 1 hour at frozen screen.
-Give more  ram
-Re-install java
-Disable/Enable splash screen
-Restart Computer
-Re-installed modpack(7 times)
-Remove twitch app and re-install
**Last Log**
https://pastebin.pl/view/120d9b42

![LoadingFreeze](https://user-images.githubusercontent.com/34215148/93123194-67017280-f6d0-11ea-9491-9781ffc5a667.PNG)

**Comment by Cazadorsniper** [comment]
Have you've tried checking if any software or windows firewall is blocking it?

**Comment by rokolix** [comment]
Yes, I checked.My firewall and windows defender is offline.I dont use any anti-virus software.Also, I can play other modpacks in twitch launcher.

**Comment by rokolix** [comment]
Hi,After many days I found the solution.It is not permanent but it works and little bit absurd.

How to Fix:
-When game freezed at 7/7 ,click close(Cross) button
-Mınecraft will show not responding screen and will give you 3 choice.
-Click the first one "Try to Restore the Program" and wait 1-2 second.You are in the game.
![Solution](https://user-images.githubusercontent.com/34215148/94348680-d53a2380-0046-11eb-8386-af23d7f6cb71.png)

It is little bit weird solution but ıt works for me.I hope that solution can help other people.

**Comment by DestroyerBr** [comment]
Hello! I dont have that option. I can either close minecraft or wait the program to respond

**Comment by DestroyerBr** [comment]
Oh, i'm sorry, my issue is diferent

**Comment by Emirhan-7274** [comment]
hey did you find a solution? im having the same problem and i dont have the "restore" option when it isnt responding

**Comment by DestroyerBr** [comment]
It's been five years, I barely remember what was the issue lol
