### ISSUE TITLE
Server Close

### ISSUE THREAD

**Issue by hanfyone** [Cazadorsniper/PO3#1384]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
The server is directly close by starting. 
I think the problem is astral sorcery, than without the mod i can start the server.
I hope anyone can help us.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/62RB5kpU

**Comment by Cazadorsniper** [comment]
Try using a normal JRE and not OpenJDK private build.

**Comment by hanfyone** [comment]
hello,
i have installed java several times, different versions. After starting what feels like 100 times, it is now on. I keep an eye on it and get in touch if it happens again.
