### ISSUE TITLE
Can't craft Lord Craft amplification rods

### ISSUE THREAD

**Issue by MartsLV** [Cazadorsniper/PO3#1386]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.3.59
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer, Multiplayer

**Description:** Cant craft simple and exotic amplification rod from two wood logs(which is shown in JEI, works fine with Sticks) in Arcane, Advanced Arcane and Void workbench from Lord Craft while having the required research, JEI show that it is possible with Arcane Crafting and with Basic Crafting Table form Extended Crafting, works fine using the Basic Crafting table.

**Steps to reproduce:** 
Research Staff and Advanced Staves from Lord Craft using the Book of Knowledge, place any of the Arcane Workbenches and use the recipe provided by JEI. 
**Crash log (use pastebin or issue will be closed):** No crash
![GitHub_1 (2)](https://user-images.githubusercontent.com/39812038/94349450-1cc3ae00-004d-11eb-8442-d037cab83ed4.png)
![GitHub_2 (2)](https://user-images.githubusercontent.com/39812038/94349451-1d5c4480-004d-11eb-9103-bbed588f59e4.png)
![GitHub_3 (2)](https://user-images.githubusercontent.com/39812038/94349452-1df4db00-004d-11eb-83ee-7c714ee6d2b1.png)

**Comment by nathanfranke** [comment]
I managed to craft it with 3 sticks in a `/` shape, then 3 simple amplification rods in a `/` shape.
