### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by QuintBrit** [Cazadorsniper/PO3#1387]
My game crashes before it finishes loading. I don't know why. 
Log: https://paste.ee/p/mqktv 
The game loads with Optifine, but looks like this: https://i.imgur.com/gakFBxo.png

**Comment by Cazadorsniper** [comment]
What graphics are you using?

**Comment by QuintBrit** [comment]
I'm using fast graphics.

**Comment by Cazadorsniper** [comment]
I mean your video card.

**Comment by QuintBrit** [comment]
I'm using a ATI Radeon HD 2600 Pro 256 MB graphics card.

**Comment by Cazadorsniper** [comment]
its crashing because of your video card.

**Comment by QuintBrit** [comment]
So my only option is to replace my graphics card?

**Comment by Cazadorsniper** [comment]
Or maybe try optifine, but yeah might have to replace the graphics card.

**Comment by QuintBrit** [comment]
Welp, I'm not paying £200 to play one pack (no offence) so I guess this is over.
