### ISSUE TITLE
Intermittent Crash - "world may have leaked"

### ISSUE THREAD

**Issue by illuminoscopist** [Cazadorsniper/PO3#1389]
**Pack Version:** 3.3.59
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

Hosted in Twitch, JAR Launcher, 6144mb Ram assigned.

**Description:** Intermittent crash in a relatively unplayed map, does not appear to be related to a single action, happens after a random quantity of time, crashes either back to desktop [crashing Twitch app aswell] or to OS X Login screen.

**Steps to reproduce:** No specific action, open world, play for a period of time.

**Crash log (use pastebin or issue will be closed):**
Apologies for links but 
[debug.log](https://www.dropbox.com/t/0513v8RGt4M02XSR) too large for pastebin or to be attached as a file.
[latest.log](https://github.com/Cazadorsniper/PO3/files/5323680/latest.log) attached as too large for pastebin.

EDIT Crashed again @ 19:11
Sorry again, too big for pastebin
[latest.log](https://www.dropbox.com/t/UkSrtufCYE3ZSaLI)
[debug.log](https://www.dropbox.com/t/eIcyQ5zuCq4UK9CC)

**Comment by Cazadorsniper** [comment]
I see no crashes in the logs.

**Comment by Cazadorsniper** [comment]
Could be a hardware issue.

**Comment by illuminoscopist** [comment]
Interesting. When I get thrown from the game to OS X login screen, I log back in and Minecraft is no longer running but in activity monitor I can see the process is still active?

What is causing the "The world xxxxxxx may have leaked: seen xx times" errors?

Only happens with PO3, other modded packs run fine.

Is there any other logging that might be useful to help diagnose? 

Thank you.

**Comment by Cazadorsniper** [comment]
The game leaked messages happen because all the mods in the pack. Only thing I noticed in the first 2 logs were inventory tweaks sorting a lot. In my dev environment I noticed that the game would sometimes crash if I have it paused for a while don't know the cause of it though. 

Did you add any mods to the pack?

**Comment by illuminoscopist** [comment]
Understood.

Both instances actually I think it had been paused a while before I started playing. Will make sure to quit out to the Home Screen rather than pausing.

No none, aside from assigning more RAM in the launcher it's a clean install from a week ago.

**Comment by illuminoscopist** [comment]
Since I don't have any more info, will close the issue, I'll re-open if I find anything more useful!

Thanks for looking into the logs.
