### ISSUE TITLE
world got deleted but when i start a new one i spawn into my old world

### ISSUE THREAD

**Issue by ac31447** [Cazadorsniper/PO3#1390]
so as it says in the title my world got deleted and when i made a new world for someone reason i spawned into my deleted world with everything still there except for what was in my inventory. im not sure if this will be useful but my computer had turned off randomly through in night and when i woke up around 4am i saw it was off and i went to go turn it on and i thought it had just lcoked but i realized it didnt and so i started twitch back up and when i got in my survival world wasnt there but my creative one was. i know i didnt delete my world and im not sure how or why it happened but if someone could help that would be wonderful so it hopefully doesnt happen to anyone else.

**Comment by ac31447** [comment]
p.s. i think my "new" world may be corrupted as my pressure chamber from pnuematic craft is loking really messed up and the refinery tower i have for it has turned into heat sinks adn a buch of other stuff. so im just gonna start a new world.

**Comment by Cazadorsniper** [comment]
could try using a backup of the world.

**Comment by ac31447** [comment]
i tried to do a back up of my world and it didnt work not sure if it was because of how i was trying to do it.(dragged the backup file over to the saves file) but i also couldnt find a way to just load the backup file like it was.

**Comment by Cazadorsniper** [comment]
Have to extract/unzip the backup file then place in the saves folder.

**Comment by ac31447** [comment]
the backup file is no longer in the backup folder and i cant find any other folders that would have my world in it.

**Comment by Cazadorsniper** [comment]
Then probably have to start a new world.
