### ISSUE TITLE
Flint and Steel

### ISSUE THREAD

**Issue by jjjjkemp21** [Cazadorsniper/PO3#1392]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):*Normal*
**Singleplayer, Multiplayer, or LAN?:*Multiplayer*

**Description:**
The flint and steel recipe is taken out on purpose, to reinforce the use of the blaze and steel, but for recipes requiring the flint and steel like galaticraft rockets and mekanism flamethrower they are uncraftable. If there is an alternate way to make it let me know
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
have tried flint and steel?

**Comment by jjjjkemp21** [comment]
I dont really understand the question but as of version 3.3.59 of PO3, there is no way to craft the flint and steel item. Also steel and flint in a crafting table does not work like it did in previous versions

**Comment by Cazadorsniper** [comment]
Are you playing on some ones public server? If so, then it maybe possible they banned the creation of the item.

**Comment by jjjjkemp21** [comment]
No. This is my server. The only modification I did to it was remove the Chance Cube mod. I will attach an image showing that the crafting of flint and steel doesnt work. There is no crafting recipe for it
![2020-10-08_22 12 41](https://user-images.githubusercontent.com/72580813/95545714-84fe8200-09b3-11eb-8b4d-620533474b34.png)
![2020-10-08_22 12 25](https://user-images.githubusercontent.com/72580813/95545716-862faf00-09b3-11eb-8f9c-18bc6545c727.png)
![2020-10-08_22 12 38](https://user-images.githubusercontent.com/72580813/95545718-86c84580-09b3-11eb-86ed-ecb8abeb7a4c.png)
![2020-10-08_22 12 39](https://user-images.githubusercontent.com/72580813/95545719-8760dc00-09b3-11eb-9515-99d841706a71.png)

**Comment by Cazadorsniper** [comment]
Reinstall the chance cube mod.
