### ISSUE TITLE
3.3.60 Server Issues

### ISSUE THREAD

**Issue by Tryzermo** [Cazadorsniper/PO3#1393]
**Pack Version:** 3.3.60
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
when attempting to launch the 3.3.60 server files forge crashes and says it's missing essential library files.
**Steps to reproduce:**
Download the 3.3.60 server files from https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/files/3076937
Extract the server files from the.zip and then run the start.bat
Should be coming up with java library errors
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/H7Kg9vEM

**Comment by Sanderstarr** [comment]
I'm having the same issue on normal.

**Comment by Cazadorsniper** [comment]
go to Twitch\Minecraft\Install or wherever you have minecraft installed and copy/paste the library folder to the server folder. I'll fix it later, can't do so right now.

**Comment by beewyka819** [comment]
To fix this, I downloaded the forge installer for the appropriate version, ran it in an empty directory for a server install, then moved the generated library folder to the PO3 server folder, overwriting the old one, and it works.

**Comment by bikingllama** [comment]
I downloaded the "forge-1.12.2-14.23.5.2854-universal.jar" directly from the forge website, and put it in the server folder. It still says that it is missing one or more essential library files.
