### ISSUE TITLE
Simply jetpacks/better questing conflict

### ISSUE THREAD

**Issue by a-nano-mouse** [Cazadorsniper/PO3#1394]
Pack Version: 3.3.60
Pack Mode: kappa

It seems like because simply jetpacks had an update, it messed up the ID/metadata for the betterquesting quest lines,  this seems to effect both the eta jetpacks line and the iota armor upgrades line.
![2020-10-11_22 40 37](https://user-images.githubusercontent.com/72721260/95702825-099b0b80-0c13-11eb-9647-976f00870134.png)
![2020-10-11_22 41 40](https://user-images.githubusercontent.com/72721260/95702827-0a33a200-0c13-11eb-9284-ca91e0f91f86.png)

**Comment by BuggaNoia** [comment]
Pack Version: 3.3.61 (Direct update from 3.3.59)
Pack Mode: kappa

The bug with  ID/metadata is still in. Items of Tier 5 get converted into a Tier 3, Tier 4 into Tier 2. 
Maybe a good point for readme-WTF: "Please feel free to cheat in your original items ...."

**Comment by Cazadorsniper** [comment]
can do nothing of items that were already created.

**Comment by BuggaNoia** [comment]
Yeah, that's clear. Thought only about a changes.txt hint.
