### ISSUE TITLE
server won't start with old world 

### ISSUE THREAD

**Issue by BartMannen** [Cazadorsniper/PO3#1395]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.60
**Pack Mode (Normal, Titan, Kappa):**
**Multiplayer** 

**i used my world from version 3.3.59 in 3.3.60 and the server woudnt start a new world works just fine

**

**Steps to reproduce:**
i have no clue what to type here

**Crash log (use pastebin or issue will be closed):**
[crash-2020-10-12_12.18.25-server.txt](https://github.com/Cazadorsniper/PO3/files/5364548/crash-2020-10-12_12.18.25-server.txt) 
i have also made a paste bin
https://pastebin.pl/view/a46f867a

**Comment by Cazadorsniper** [comment]
please use https://pastebin.com/ instead.

**Comment by BartMannen** [comment]
https://pastebin.com/PKGiBmsj

**Comment by Cazadorsniper** [comment]
try removing the EpicSiegeMod mod, start server, then add it back in.

**Comment by BartMannen** [comment]
https://pastebin.com/pnusP7du

**Comment by Cazadorsniper** [comment]
ok just play without the mod.

**Comment by BartMannen** [comment]
hello first up i want to thank you for youre effort of trying to resolve the issue unfortunately removing the mod did not work. I have another pastebin but i was wondering if it helped if i send you my world folder.

https://pastebin.com/jQm8e4Mm

**Comment by Cazadorsniper** [comment]
In the Forge.cfg on the server try changing these values to true:     
# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false

**Comment by BartMannen** [comment]
it worked! but i saw that there was a new version im updating right now

**Comment by BartMannen** [comment]
It worked thank you very much!
