### ISSUE TITLE
Quests reset and unable to use bq_admin edit

### ISSUE THREAD

**Issue by Kryptor9126** [Cazadorsniper/PO3#1397]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.57
**Pack Mode (Normal, Titan, Kappa):**
normal
**Singleplayer, Multiplayer, or LAN?:**
singleplayer
**Description:**
Logged onto my world from about 2 months ago and all my quest progress has been reset, when i try to use the bq_admin edit command it says i dont have permission.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I can only suggest to load an old backup of that world.

**Comment by Kryptor9126** [comment]
oh yeah i didnt think about that, thanks and thanks for fast reply

**Comment by Kryptor9126** [comment]
and i like your mods <3

**Comment by quietust** [comment]
Opening your game to LAN with "Enable Cheats" should allow you to use the `/bq_admin` command - if you've got an NBT editor, you should be able to permanently enable those commands by editing your world's `level.dat` file and changing the `allowCommands` property from 0 to 1.
