### ISSUE TITLE
No way to cast a bucket

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Cazadorsniper/PO3#14]
**Pack Version:**
3.0.38
**Description:**
Attempts to make/cast a bucket, there doesn't seem to be any recipe that I have found using Tconstruct's casts/patterns. The recipe remains in NEI showing you that it is possible.
**Steps to reproduce:**
Try to make a stone bucket to cast. There is no pattern for it. 
**Crash log:**

**Comment by gsoxreptile** [comment]
clay bucket or make iron plates using a crushing table

**Comment by nzminecraftDOTcom** [comment]
I attempted making a bucket cast, using molten gold and a clay bucket however it just wanted to fill the bucket with gold.

**Comment by PlacidK** [comment]
Craft a stone bucket to make the cast.

**Comment by nzminecraftDOTcom** [comment]
There lies the problem doesn't it @PlacidK the reason for this bug report, it doesn't seem to have a recipe.

**Comment by PlacidK** [comment]
Do you mean for the stone bucket or the bucket cast?
And i think filling the clay or iron bucket is normal behaviour. That's why the stone version is added.

**Comment by legendaryA1** [comment]
hes right there is no recipe for the stone bucket. but it seems this is intentinal as it by default has one and the modpack maker has removed it probably as a way to get you to use the crushing table and connecting mods/items

**Comment by nzminecraftDOTcom** [comment]
Thanks @legendaryA1 I was unaware if anyone else was having the issue. I was all confused as to why I could still see the items in NEI yet the item was not craftable. Would be something to remove in future game updates.

**Comment by mihaitacgeorge** [comment]
> clay bucket or make iron plates using a crushing table
> Craft a stone bucket to make the cast.

Gotta love it when kids refuse to read a thread but also refuse to keep themselves from replying to it. Best way to be productive!
