### ISSUE TITLE
buckets gets multiplied  

### ISSUE THREAD

**Issue by puffer-wolf-12** [Cazadorsniper/PO3#1400]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.61
**Pack Mode Normal
**Singleplayer

**Description:**
if you drink milk while you have an empty bucket in your hot-bar the bucket will get multiplied 
**Steps to reproduce:**

**Crash log (use Pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
That bug is now a feature.
