### ISSUE TITLE
Intended duplication i think not

### ISSUE THREAD

**Issue by exdocious** [Cazadorsniper/PO3#1408]
I am currently playing project ozone 3 as a play through series and i have found something that should not exist where galactic craft or extra planets zombies are not blacklisted from imprisonment tools and when given an item and put into a mob duplicating machine they can duplicate exact copies so give then a white matter and u can get as many as you want give them a stack of white matter and the same thing happens but the problem is that they even accept filled shulker boxes and diamond shulker boxes meaning they can produce endless items

**Comment by Cazadorsniper** [comment]
Its intended now, stopped updating this modpack.

**Comment by exdocious** [comment]
ok thanks for the info lol

**Comment by exdocious** [comment]
please do let me know if ever you want me to do mod pack testing for you
(only condition is i will be doing it on camera)
