### ISSUE TITLE
Tungsten Armor cannot Repair

### ISSUE THREAD

**Issue by Pyario** [Cazadorsniper/PO3#141]
**Pack Version:**
PO3-3.0.38

**Description:**
Tungsten Armor from Armor Plus cannot repair on anvil and other ways..

**Steps to reproduce:**
Tungsten Armor (In Anvil) with all Tungsten(Ingots) cannot repair..

**Crash log:**

Picture: http://prntscr.com/mw0dmi

What can i do ? I do not want to recreate the armor..

Sorry for my English

Best Regards,

Pyario

**Comment by backsy** [comment]
Advanced armors can not be repaired on an anvil. You need an item repairer for that. I dont know if tungsten is one of them or not off the top of my head.
