### ISSUE TITLE
Some recipes not working

### ISSUE THREAD

**Issue by SammyZombiee** [Cazadorsniper/PO3#1415]
Hi! 

I have a server with Project Ozone 3 and some recipes I am trying to make aren't working like mirrors, buckets, and flint and steel, probably more that I haven't come across yet, hoping someone can help me with this.

Thanks
![minecraftPO3](https://user-images.githubusercontent.com/74026986/98307422-b9099a80-1f93-11eb-968f-37ab4a290e74.png)

**Comment by Richardk2n** [comment]
Make sure the settings for the packmode are the same on the client and the server, otherwise the client might show recipes that are not valid on the server.

**Comment by SammyZombiee** [comment]
When we first started the server. Recipes like the bucket and flint and steel we were able to make. All of a sudden the recipe will go In the table but no product comes out.

**Comment by Cazadorsniper** [comment]
Did you try the above solution?

**Comment by SammyZombiee** [comment]
I tried, but I’m unsure how, could you explain how to?

**Comment by Cazadorsniper** [comment]
check the client packmode.cfg file and the server packmode.cfg to see if they are the same.

**Comment by SammyZombiee** [comment]
Where do I find those files? I’m hosting through a site not my personal pc. Sorry if I’m being difficult, I’m slightly confused.

**Comment by Cazadorsniper** [comment]
config

**Comment by SammyZombiee** [comment]
So the server packmode is normal, but idk how to find the client server mode.

**Comment by Richardk2n** [comment]
In the config folder of your client.

**Comment by SammyZombiee** [comment]
Both are normal, the server and client.

**Comment by SammyZombiee** [comment]
So I just noticed a pattern. All recipes where it says “recipe by: CraftTweaker2” aren’t working.

**Comment by Cazadorsniper** [comment]
was a mod removed at all?

**Comment by SammyZombiee** [comment]
I removed the mod for chance cubes I think that’s what they are called. I didn’t think removing that mod would break anything?

**Comment by Cazadorsniper** [comment]
yeah, add that mod back.

**Comment by SammyZombiee** [comment]
Would I be able to turn the mod off? I don’t want chance cubes to spawn.

**Comment by Cazadorsniper** [comment]
don't use them? Removing the mod at all causes recipes to error.
