### ISSUE TITLE
Quest Fully Reset

### ISSUE THREAD

**Issue by Curundil** [Cazadorsniper/PO3#1416]
Hello, I have been running a server on my computer that me and two others play on. We have made a decent chunk of progress into the quest book, and we are in a party in the quest book to sync up our quests.

Everything about this seems to be working normally. However, when we got on the server tonight, we found that our quest progress had been reset to zero. I leave the server up during the day so they can hop on if they want, which has never caused issues before. That being said, there was a power surge in town while I was not home, so that is my current theory on what caused this issue: the server being forced to close by the power to my computer being cut. I also don't have backups saved from before the power surge, as I turned the server on without thinking much of it, so the server passed the time frame in which the new backups would replace the backups from before the power surge.

I've been looking for a solution to our problem. I found out about the /bq_admin edit command where I can force the commands to complete. I tried doing this after we made a new party, which completed quests for me (the server op and person running the command), but didn't update it for the other members in my party. I thought maybe having someone join the party after having used the commands might do the trick. Unfortunately, this didn't give the person who joined the party the force completed quests. We actually tried this method twice: the first time, the server crashed immediately after the player joined the party with the player who had force completed quests. The second time, we did the same thing, but tried having the party be brand new (whereas, in the first attempt, the player joining the party had previously been in the party but had been kicked out). This second attempt didn't result in an immediate crash; however, the server crashed a few minutes later, although we are unsure whether that crash is related to the attempt.

So at this point, I am wondering what the solution is. Is there any way to see player's past completed quests? Is there any way to fix this situation besides giving each player op permissions and having them manually force complete the quests and join a party together afterwards? Does anyone know what the options are?

Attached are the crash reports from today (there are three, although I only remember two; I don't see one that was at the same time as the power surge, but I'm not sure). I believe the latest two are the two crashes I mentioned earlier, although it's possible I am mistaken about that.

Any help would be greatly appreciated. Thank you for your time!

[crash-2020-11-07_04.12.31-server.txt](https://github.com/Cazadorsniper/PO3/files/5504586/crash-2020-11-07_04.12.31-server.txt)

[crash-2020-11-07_04.17.52-server.txt](https://github.com/Cazadorsniper/PO3/files/5504587/crash-2020-11-07_04.17.52-server.txt)

[crash-2020-11-07_04.29.15-server.txt](https://github.com/Cazadorsniper/PO3/files/5504589/crash-2020-11-07_04.29.15-server.txt)

Edit: I suppose I should mention my version: 3.3.59. I also just realized that the first crash report is from our first attempt that I mentioned earlier. The second crash report is from when we restarted the server and joined, it immediately crashed again, forcing us to load a backup from before our first attempt. The third crash report is the second attempt I explained above. I am happy to provide any other information or answer any questions.

**Comment by Cazadorsniper** [comment]
sadly nothing I can do about worlds corrupted by power surges, only defense against that is the backups. Might have to complete the quests again.

**Comment by Curundil** [comment]
Okay I suppose the crashes aren't really what I was wondering about. I can figure out how to get our world and items back, what I'm worried about is the questing. I can't seem to get members in a party's quests to sync after using the "/bq_admin edit" command to manually force quest completions for one player. I haven't tried it yet, but if each person forces all the same quests manually, will the party quests sync back up from there on? Or is there something else preventing the sync?

I realize that you might not know the answser, so thank you for your help and time either way.

**Comment by Cazadorsniper** [comment]
It should sync back up if they complete the same quests.

**Comment by Curundil** [comment]
Okay, so we had each player do the bq_admin edit and force complete the quests to get us back to where we were. Then we joined a party together, and it seems like the quests are synced again. Thanks for your help!
