### ISSUE TITLE
Balance around Anti Barrel

### ISSUE THREAD

**Issue by DeadlySurgeon** [Cazadorsniper/PO3#1418]
The Anti Barrel can hold an infinite amount of items and 100,000 types of items. With ME controllers, this seems to be a way better alternative to pretty much every single drive. Shouldn't it be disabled or more expensive in Kappa mode to help balance it out?

**Comment by Protheus** [comment]
it can only hold non-stackable items, other items will not be able to go in it. Yes a good alternative for armor and weapons but the rest needs to be in a different storage

**Comment by DeadlySurgeon** [comment]
@Protheus Yeah I didn't notice that until now.
