### ISSUE TITLE
Loading the modpack takes a long time and then at the end crashes.

### ISSUE THREAD

**Issue by Magmalord** [Cazadorsniper/PO3#142]
**Pack Version:**
3.0.08
**Description:**
I don't know a lot about computers or what I need to do to solve this but I would really love to play this modpack. I load up the modpack like any other but it takes a very long time and on the final step just crashes.
**Steps to reproduce:**

**Crash log:**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.1.b163.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  CoreMod (TickProfiler-1.12-0.0.7.jar)
  CreativePatchingLoader (CreativeCore_v1.9.39_mc1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  LoadingPlugin (Quark-r1.5-145.jar)
  WTPlugin (WaitingTime-1.0.1.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.6.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/10/19 7:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by Cazadorsniper** [comment]
remove the waiting time mod then try again

**Comment by Cazadorsniper** [comment]
also make sure you have enough ram allocated to the modpack.

**Comment by Magmalord** [comment]
How do I do those things? Sorry.

**Comment by Revvilo** [comment]
@Magmalord
#### To remove the waiting time mod
- Right click the modpack in Twitch and click Open Folder
- From there, open the `mods` folder
- Delete `WaitingTime-x.x.x.jar`
#### Ram allocation
- Click your name in the top right of Twitch
- Click `Settings`
- Open the `Minecraft` tab
- At the bottom, there is a slider for `Allocated Memory`
_Be careful to not allocate a lot more than half of your computers total RAM_

Hope that helps :)

**Comment by mattdamo26** [comment]
i was having a similar issue. 2 hour load time and a coin toss as to whether  it would crash or not. Deleted and reinstalled and no issues average load time is 8 minutes and 32 seconds
