### ISSUE TITLE
mekanism pipe wont be learnd by projectE

### ISSUE THREAD

**Issue by BalloS-Twok** [Cazadorsniper/PO3#1422]
**Pack Version:3.3.61**
**Pack Mode (Normal, Titan, Kappa):normal**
**Singleplayer, Multiplayer, or LAN?:LAN Server**

**Description:It seems that only the basic pipes of Mekanism can be learned by projectE. The advanced, elite and ultimate got an EMC value but cant be learned.
If you use Transmutation Chamber as storage system you cant build higher pipes.  

![Unbenannt](https://user-images.githubusercontent.com/54473809/99068810-807a4a00-25ad-11eb-98e1-90f8e5dca297.JPG)

That count also for the cable, tube and logistical transporter from mekanism **

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Some mekanism items/blocks are separated by nbt data, there is nothing I can do about that.
