### ISSUE TITLE
Tinkers smeltery not working

### ISSUE THREAD

**Issue by llhilton** [Cazadorsniper/PO3#1424]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa): Titan
Singleplayer

I have tried both the minimum version of the smeltery (1-block interior) and the usual 3x3 interior, and in neither is the smeltery "formed." Clicking on the smeltery controller doesn't open the GUI, and trying to hopper in stuff doesn't work. It's sitting up one level on cobblestone, and there are no blocks inside. I've tried restarting, but still doesn't work. Not sure if this is something different with the Titan mode, but the recipes all looked fine.

**Comment by Cazadorsniper** [comment]
can have pictures please.

**Comment by llhilton** [comment]
![2020-11-15_21 38 06](https://user-images.githubusercontent.com/3161805/99207094-13bca680-278b-11eb-9753-b05fc1c0fafa.png)
![2020-11-15_21 38 13](https://user-images.githubusercontent.com/3161805/99207095-13bca680-278b-11eb-997e-b3cf2da6a792.png)
![2020-11-15_21 38 18](https://user-images.githubusercontent.com/3161805/99207096-14553d00-278b-11eb-8a5d-9b114ec7ae15.png)
![2020-11-15_21 38 30](https://user-images.githubusercontent.com/3161805/99207097-14553d00-278b-11eb-8520-5040e70e2389.png)
![2020-11-15_21 38 43](https://user-images.githubusercontent.com/3161805/99207099-14553d00-278b-11eb-867b-327f5e65cb14.png)
Hopefully attached. I added another level of seared bricks, but they did no more than make it a taller thing that doesn't work. I tried it also with just one drain, just to see if that would do it, but it did not.

**Comment by llhilton** [comment]
Okay, never mind, I'm an idiot and didn't have the bottom layer out of seared stone.
