### ISSUE TITLE
Questbook: Water to Clay 

### ISSUE THREAD

**Issue by Kratzwurst** [Cazadorsniper/PO3#1425]
**Pack Version:*3.3.6.1*
**Pack Mode (Titan):**
**Singleplayer**

**Description:**
I start this Pack yesterday and can't go on. 1 Quest in the Alpha Section "Water to Clay"  have the false Item to detect the Quest. Ex Compressum turns off the Wodden Crucible (this was required) and the Oak Crucible don't want finished the Quest.
But, this quest is required to get to the unfired crucible and the cobblestone generator etc.

![2020-11-16_08 21 06](https://user-images.githubusercontent.com/13652826/99223468-d7b62f80-27e4-11eb-87dd-92ee3e13cd5d.png)

Edit Mode was on to change the item to get forward ;)

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Remove Ex Compressum.
