### ISSUE TITLE
Overloaded Infinity Capacitor resets RF buffer

### ISSUE THREAD

**Issue by vandr0s** [Cazadorsniper/PO3#1426]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.61
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
Infinity Capacitor from overloaded empties cyclically after reaching 2.14 billion RF (integer value).
![2020-11-16_16 01 09](https://user-images.githubusercontent.com/74546202/99257331-eb36ba00-2827-11eb-9dfd-421911bc59d6.png)
![2020-11-16_16 01 21](https://user-images.githubusercontent.com/74546202/99257335-ed007d80-2827-11eb-8975-be66d8c8ca7b.png)
Is it a bug or a normal behavior?
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
This issue is already in the changelog.
