### ISSUE TITLE
When I am playing the game some of the sounds ex. (chests opening, machines operating, eating, portals, etc.)

### ISSUE THREAD

**Issue by Dylanrhyne** [Cazadorsniper/PO3#1428]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.3.59
**Pack Mode (Normal, Titan, Kappa):**normal
**Singleplayer, Multiplayer, or LAN?:**sp

**Description:** When a sound plays it will cut out sometimes. Example. (portals, opening chests, eating, machines operating, etc.). I have tried re-installing and updating the game. I have tried updating my audio driver. I have tried F3-T and F3-S. None of these things seem to help. Thank you.

**Steps to reproduce:** happened out of nowhere.

**Crash log (use pastebin or issue will be closed):** I don't receive a crash log.

**Comment by Cazadorsniper** [comment]
Do you have a sound muffler or some kind activated?

**Comment by Dylanrhyne** [comment]
No I do not. I've tried researching and I can't find anyone else having
this issue. So I'm wondering if it has something to do with my system and
not the game but sound doesn't get cut out on anything else. I've also done:

Allocated more ram
Changed to a previous version of the mod pack and the forge launcher
Removed mekanism wind mills and enderio charger
Removed universal cables, and water trough and sprinklers
Killed all mobs in the area
Updated graphics driver
Changed mini map levels
Changed volume settings ingame

I can't really think of anything else to do, I'm not really computer savvy
lol.

Thank you for trying to help me. I really love playing this mod pack and
hopefully I can get it fixed.

**Comment by Cazadorsniper** [comment]
yeah I'm not sure what the issue could be.

**Comment by Dylanrhyne** [comment]
Okay so I just figured it out. I removed all of my Mekanism wind generators
and the sound no longer cuts out. I guess minecraft was just having too
many noises playing at the same time. Do you know of a fix for that so I
can still use the generators?

**Comment by Cazadorsniper** [comment]
move the generators far away lol.

**Comment by Dylanrhyne** [comment]
I will try that thanks, I appreciate the help. I could get anyone else to help me

**Comment by Oct0bass** [comment]
> I couldnt get anyone else to help me

Could this maybe, I don't know, have to do with the fact that you kept repeatedly spamming an issue that many people tried to explain to you had already been reported, provided no useful information, and then acted like they were the ones treating you unfairly?
