### ISSUE TITLE
Crash on using Inventory (with fix)

### ISSUE THREAD

**Issue by Sekkoth** [Cazadorsniper/PO3#1429]
**Pack Version:3.3.61
**Pack Mode (Normal, Titan, Kappa): Kappa
**Singleplayer, Multiplayer, or LAN?: Sinleplayer
**Description: 

Game crashes on opening inventory. Cant render Little Tiles Single Cable. 
Fix: Updated Little Tiles and CreativeCore

**Steps to reproduce: 
- Search for "Sin" in the JEI search (My intention was sink)
- Crash and be unable to use your inventory anymore even after reloading the game etc. as the Little Tile Single Cable render process crashes

**Crash log (use pastebin or issue will be closed): https://pastebin.com/2p9EjyUq

**Comment by Cazadorsniper** [comment]
Po3 doesn't have little tiles.

**Comment by Sekkoth** [comment]
wait whut .... i didnt add that myself now, did i? Its been a long time since ive installed PO3. I sowwy Caz!

**Comment by Sekkoth** [comment]
big dumb dumb
