### ISSUE TITLE
Free exp with crafting stations

### ISSUE THREAD

**Issue by BenjiTheViking** [Cazadorsniper/PO3#1431]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** All of them
**Singleplayer, Multiplayer, or LAN?:** All of them

**Description:**
When inserting an item into the third storage slot of a Tinkers Construct crafting station, you can then pull the item out of the output slot of the endest furnace. Giving the exp for the finished item. (As seen on the screenshots)
https://imgur.com/a/U8ZDWzH

**Steps to reproduce:**
Place Endest furnace next to Crafting Station, place item into third storage slot of crafting station. Look in the furnace and pull out the item from the output slot, giving free exp.

**Comment by Cazadorsniper** [comment]
Nice
