### ISSUE TITLE
Modular Machine auto sieve doesn't accept some blocks

### ISSUE THREAD

**Issue by Lightcx** [Cazadorsniper/PO3#1433]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.361
**Pack Mode (Normal, Titan, Kappa):**
normal
**Singleplayer, Multiplayer, or LAN?:**
singleplayer

**Description:**
auto sieve doesn't sieve certain blocks(dust,gravel,sand,crushed nether rack)
but it has nothing wrong with other blocks
JEI shows the recipes normally
config checked , nothing wrong :(

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

![2020-11-24_13 06 44](https://user-images.githubusercontent.com/74954277/100064129-15622a80-2e6d-11eb-8760-67787c46e08b.png)
![2020-11-24_13 06 48](https://user-images.githubusercontent.com/74954277/100064132-15fac100-2e6d-11eb-89f8-d19292eabdda.png)
[recipes file.zip](https://github.com/Cazadorsniper/PO3/files/5588241/recipes.file.zip)

**Comment by Cazadorsniper** [comment]
Make a larger output bus.

**Comment by Lightcx** [comment]
Fixed. Nice
