### ISSUE TITLE
project ozone 3:

### ISSUE THREAD

**Issue by nerdexdk** [Cazadorsniper/PO3#1434]
any way to optimize it?
i mean i can barely run it and i got pretty good pc
i7 6700 cpu (3.40GHz)
NVIDIA GeForce GTX 970
8GB Ram
ASUSTeK COMPUTER INC.  H110M-A (motherboard)

i have given it permission to use 8 gb ram and i have change the settings to use the java version
is there any more ways to optimize it?

**Comment by iRiceCrispy** [comment]
Running any large modpacks such as po3 is EXTREMELY heavy on your computers memory. If you open up your Task Manager, you may see that your memory is running at 100% most the time while you're running minecraft. I don't think there is any good way to increase optimization besides just upgrading your RAM.

I was lagging super hard trying to play modded mc with only 8 ram. Then after upgrading it to 16 ram, it runs really smoothly.

**Comment by MrHubert1710** [comment]
8GB of RAM is way too small for PO3, I have 16GB and its topping my memory usage to 100% with some background apps.

**Comment by Kratzwurst** [comment]
I Agreed, PO3 needs a lot of Ram to Startup.
I Look Up the Usage of them all:

Java PO3 use 8.2GB Ram to Startup a World, if is loaded need it nearly 7.4GB Ram with Optifine
The System use 5-6GB Ram  (Windows 10 and another Little Appz in the Background).
Overall Usage = 13 GB Ram

Otherwise your Moinboard can easy handle 32 GB Ram without any Problems

**Comment by Cazadorsniper** [comment]
Then I load up PO3 in 6 minutes using 6GB of Ram.

**Comment by Kratzwurst** [comment]
> Then I load up PO3 in 6 minutes using 6GB of Ram.

Have u any add or remove Arguments  to this:

-Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m ?

**Comment by Cazadorsniper** [comment]
no

**Comment by Irgendwer01** [comment]
i have 8GB in my PC installed and allocate 5GB to the pack without any problems
