### ISSUE TITLE
error java.lang.arrayindexoutofboundsexception -1

### ISSUE THREAD

**Issue by elogod1337** [Cazadorsniper/PO3#1437]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**PO3.3.3.61
**Pack Mode (Normal, Titan, Kappa):**Normal
**Singleplayer, Multiplayer, or LAN?:** LAN, but only me on when the crash occurs.

**Description:**
I press E and my game crashes.

**Steps to reproduce:**
No clue
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/4DbfWpWh

**Comment by Kratzwurst** [comment]
First Steps what u can do:

> Update your Graphicdriver to 460.79, your actually Driver is a little bit to old.
> Change the TP PureBDcraft 128x to the x64 Version.
> Your Java Version 1.8.0_51 is quit hard old, please updated it.

I've had the same Problem with the PureBDcraft 128x on GTX 1060, i see in the Task-Manager the GPU was nearly Usage 80%

Hope it fixed it.
