### ISSUE TITLE
Mod manquant

### ISSUE THREAD

**Issue by SenseiTVT** [Cazadorsniper/PO3#1438]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**Normal
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**Certains mod ne sont pas activer (comme extrau) comment faire pour les activer? merci

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Did you type @extraut in JEI?

**Comment by SenseiTVT** [comment]
Oui, mais le craft de certains item ne sont pas possible, alors que j'y ai joué il y a un an, et les crafts étaient dispo (par exemple transfer node, ou pipe)

**Comment by SenseiTVT** [comment]
Et quand je me rends dans les mod il est mis "disable"

**Comment by SenseiTVT** [comment]
QUand je dis je me rends dans les mods c'est sur l'interface minecraft ou il y a (singleplayer,....)

**Comment by SenseiTVT** [comment]
Pensez-vous que vous pourrez m'aider ?

**Comment by SenseiTVT** [comment]
D'après ce que j'ai pu voir c'est que certains craft (transfer node, pipe,...) Ne sont pas disponibles et donc on ne peut pas les craft

**Comment by Cazadorsniper** [comment]
Some items are disabled due to bugs will have to use something else.

**Comment by SenseiTVT** [comment]
Il y a une possibilité pour faire en sorte que je puisse craft les items ou pas dutout?

**Comment by Cazadorsniper** [comment]
Not at all.
