### ISSUE TITLE
Check Box

### ISSUE THREAD

**Issue by freezebladeJD** [Cazadorsniper/PO3#1439]
Me and my friend have been playing on a kappa server called po3.modrealms.net I think and he can’t check the box for the starter quest. Does anyone know a fix for this? Thanks!
It allows me to click it perfectly fine.
Version 3.3.61

**Comment by Cazadorsniper** [comment]
Are you two in a party (Better Questing Party) together?

**Comment by freezebladeJD** [comment]
We tried it with and without being in a party together and no difference unfortunately

**Comment by Cazadorsniper** [comment]
Can I get a few screenshots of what is happening? It could be the server you two are on.

**Comment by freezebladeJD** [comment]
Update: It’s only happening on servers and it’s all servers not just one
