### ISSUE TITLE
Crash when void crystal in mechanical user

### ISSUE THREAD

**Issue by Masharibzaheer** [Cazadorsniper/PO3#144]
hello  i tried to put my void crystal into mechanical user and when i select use item it crash my world now when ever i open my world it crash and i cannot remove my crystal its from lord craft

**Comment by CraftalotReloaded** [comment]
Please provide a crash report and your latest log

**Comment by Masharibzaheer** [comment]
[crash-2019-03-12_12.28.15-server.txt](https://github.com/Cazadorsniper/PO3/files/2955618/crash-2019-03-12_12.28.15-server.txt)
