### ISSUE TITLE
Game Crashes while Loading

### ISSUE THREAD

**Issue by Schilli92** [Cazadorsniper/PO3#1440]
Hallo,

My Game Crashes while Loading.

[crash-2020-12-12_23.29.11-client.txt](https://github.com/Cazadorsniper/PO3/files/5683854/crash-2020-12-12_23.29.11-client.txt)

Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 460615696 bytes (439 MB) / 2185232384 bytes (2084 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 285 mods loaded, 285 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Schilli92** [comment]
https://pastebin.com/2bPM878m

**Comment by Cazadorsniper** [comment]
Remove discordsuite mod.

**Comment by Schilli92** [comment]
I removed the discordesuite mod an the game works.
