### ISSUE TITLE
QuantumStorage and/or item translocators broke my world

### ISSUE THREAD

**Issue by Marishxen** [Cazadorsniper/PO3#1441]
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
I set up QuantumStorage multiblock as a buffer between automated sifter and YABBA storage using an item translocators, quited game and can't load the world now (all backups are broken too).

**Steps to reproduce:**
Couldn't reproduce in creative world.

**Crash log (use pastebin or issue will be closed):**
pastebin.com/6TxZYxyb

**Comment by Cazadorsniper** [comment]
Use World Edit or something like that to remove the Quantum Storage block or just remove the mod load the world then place the mod back in.

**Comment by Marishxen** [comment]
I temporarily removed Translocators. It helped to load the world, thanks.

The bug in the QuantumStorage will not be fixed by its maintainer...
