### ISSUE TITLE
PO3 Normal mode recipe 

### ISSUE THREAD

**Issue by bratthemaster** [Cazadorsniper/PO3#1442]
I'm unable to craft transfer node items or fluid nor transfer pipes either what do I do ? Thank-you :)
![2020-12-16_20 18 12](https://user-images.githubusercontent.com/36436567/102402051-24577b00-3fdc-11eb-9e92-77d122b03722.png)

sorry mod pack version 3.3.61

**Comment by Cazadorsniper** [comment]
Use a different pipe.
