### ISSUE TITLE
SoundManager crashing the game

### ISSUE THREAD

**Issue by ExZiByte** [Cazadorsniper/PO3#1445]
**Pack Version:** 3.2.54 (Cause this is the latest version the server host I use has available)
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
My friend is having an issue where after about 5 to 10 minutes of playing his game just freezes and won't recover (let it sit for 5 hours straight and it was still frozen) and the error message he gets states (see code block) multiple times 
` [Thread-14/ERROR] [minecraft/SoundManager]: Error in class 'CodecJOrbis'`
` [Thread-14/ERROR] [minecraft/SoundManager]: Error reading the header`

First time it froze on him he was in the deep dark near the void level (Y level: 5 or less)

He has tried the following attempts to fix it 

`deleting the assets folder and letting minecraft regenerate them`
`deleting the modpack entirely and redownloading it`

There is 1 extra mod that we added the "NotEnoughWands" mod (other then this there is no other additions/subtractions/modifications to configs)

The pack was downloaded using MultiMC 

I have the exact same setup as him (Method of downloading the pack and using the "NotEnoughWands" mod) but my game doesn't crash at all

**Steps to reproduce:**
Don't know how to reproduce it

**Crash log (use pastebin or issue will be closed):**
https://paste.ee/p/5f93j
//Not a true crash report this is the console logging output in MultiMC from launch to freeze
//First instance of the error that I stated is on line 9200

**Comment by Cazadorsniper** [comment]
Best to reinstall Minecraft entirely and recommend a different server host with an updated version of the pack.

**Comment by ExZiByte** [comment]
Would we/ should we restart the world when updating

**Comment by Cazadorsniper** [comment]
Yes

**Comment by ExZiByte** [comment]
Update on this. It is not the pack itself it was the launcher breaking the install using MultiMC 5. It does the same issue on other packs also
