### ISSUE TITLE
Crash during mod loading

### ISSUE THREAD

**Issue by apavlici** [Cazadorsniper/PO3#1446]
Log output too big for pastebin, here's a controlc version: https://controlc.com/7d1a93a6

Tried uninstalling Twitch, Minecraft, CurseForge, Overwolf, and the modpack itself and then reinstalling all - to no avail. 

Gets to Part 2 of mod loading and then crashes at Avaritia, or sometimes goes to Part 4 of mod loading and then crashes at Twilight Forest (but with Avaritia as most recent fatal error). Always crashes at the same points in time though, not random. 

I have allocated various amounts between 8 and 14 GB, didn't fix to add more RAM either. Any suggestions?

**Comment by apavlici** [comment]
Minecraft game launcher says Exit Code 0, while Minecraft game output says Process crashed with exit code -1073741819.

**Comment by Cazadorsniper** [comment]
Did you add or remove any mods?

**Comment by apavlici** [comment]
Not that I know of. The mod pack was working fine on the CurseForge launcher (most updated version of pack/launcher) for several weeks until yesterday when it started exiting/crashing. I even used the direct file download of the mod pack and tried MultiMC launcher, same error.

**Comment by apavlici** [comment]
Figured it out...CurseForge apparently has a known issue where if duplicate profiles exist for modpacks it will prevent the mod pack from launching until you restart your computer, no matter which launcher you use. Solution was to delete everything in the mod folder, restart computer, reinstall mod pack, and launch again.

**Comment by ThatAmazingCow** [comment]
I have this similar problem and i think i did those steps to solve it, it was also my own created modpack
