### ISSUE TITLE
Ember Rekindled Items not Upgrading

### ISSUE THREAD

**Issue by HexUnderLord** [Cazadorsniper/PO3#1447]
Pack Version: 3.3.61

Pack Mode Normal

Singleplayer & LAN Local Host

Description: Having Problems with the Inferno Forge in this modpack. When I try & upgrade my Clockwork Pickaxe which has a full Heat Level in it doesn't work. I've Put upwards of 7-64 Ember Crystals in the forge it fires but at the end nothing happens. I can confirm it's got full power via the Mechanical Core at the bottom with the Ember dial. I have a feeling it may have to do with the odd item drop mod that makes items have physics when their dropped & the Forge isn't recognizing it but I don't know for sure. Please help thanks.

Steps to reproduce: In the Ember's rekindled Mod you will need something that will power the Inferno Forge a Crystal Cell or just direct from any other power source supplying ember. Then throw an Ember tool or gear that has been tmpered with a motive core on that has a full heat level into the forge with what should be 7-10 Ember crystals it will flair up then when it is completed the item will either be upgraded with a slot or nothing would have happened & the 2 materials will still be in the Forge.

Crash log (use pastebin or issue will be closed): NO Crash
![8ufvewtvm3661](https://user-images.githubusercontent.com/58956297/102830159-ed031880-43a5-11eb-95f7-0dfadf1fb1ec.png)
![90ecb5ac3c6cb87b3c2a446af27f82be](https://user-images.githubusercontent.com/58956297/102830184-fb513480-43a5-11eb-8630-e729bdf6c00d.png)

**Comment by Hatmic98** [comment]
Having the same issue here. Doing everything right but the item simply wont upgrade. Not seeing a fix

**Comment by Cazadorsniper** [comment]
try updating the mod to see if it works correctly.

**Comment by Hatmic98** [comment]
All good, Figured it out. The upper bound for ember crystals in an upgrade
procedure is ~4
