### ISSUE TITLE
Uncraftable Leadstone Energy Cell

### ISSUE THREAD

**Issue by Dm5354** [Cazadorsniper/PO3#1449]
Version: Not the latest
Pack Mode: Normal
Mode: Singleplayer

Description: Can't craft leadstone energy cell!

There is no recipe in JEI, nor a crafting output in the crafting table, which prevents me from crafting the Fluxpack for the Flux Infused Jetplate, which gates me from DE Draconic armor, and I can't progress! I don't really wan't to cheat to get it!

I don't really know how to replicate it. I switched from Kappa to Normal after I played thru it! That's the only way it could've happend!

**Comment by Cazadorsniper** [comment]
Could try updating.

**Comment by Dm5354** [comment]
I wouldn't like to update because the update would remove Landia and I heavily rely on the Big Brother woot cheeze. I added that item in cos I almost have infinite resources with the transmutation tablet, soo one wouldn't cost much. 

And I tried to look at the issue on an another Minecraft install and i did the same loaded Kappa in than loaded Normal in and it was working fine, the recipe was there, probably a .json issue, which is wierd!

Nonetheless your modpack is Awesome, I played thru Kappa in season one of homeschooling! 
Keep up the good work our hero!

[You can close the issue]
