### ISSUE TITLE
Duplication bug involving /dank/null (only MK IV tested)

### ISSUE THREAD

**Issue by Mosent** [Cazadorsniper/PO3#145]
**Pack Version:**
3.0.38 - Private server, no modifications

**Description:**
Using the Mk IV dank/null, I was able to (somewhat consistently) duplicate the contents and the dank/null itself by using the open hotkey (not shift+right-click on hot-bar), then move the dank/null into a slot within the dank/null. It doesn't allow it to hold itself, but after placing it back into your inventory, another one usually (not always) falls onto the ground with identical contents inside.

**Steps to reproduce:**
I changed the open nearest dank/null hotkey to x. It is duplicate with Pneumatic Boots Kick (Ctrl + X) which is likely irrelevant. It is on a personal server, not tested in single player.

While the dank/null is not on your hot-bar, open it with the assigned key. With the GUI open, click and place the dank/null inside of itself. It doesn't allow it to be placed. Place it back in your inventory and close the GUI. An additional dank/null will usually fall as though it was thrown from your inventory, with all contents inside.

**Crash log:**
N/A

**Comment by CraftalotReloaded** [comment]
Similar issues have already been reported on the github page for dank/null just wait for it to be fixed by its dev
