### ISSUE TITLE
Spawn area gets regenerated by new island when a new player joins

### ISSUE THREAD

**Issue by OverlordFreddo** [Cazadorsniper/PO3#1450]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
When a new person joins the server, spawn is affected by the generation of the new player's island right there at spawn.

**Steps to reproduce:**
Remove starting island, create a spawn area  and have someone join.

**Crash log (use pastebin or issue will be closed):**
Not crash just strange behaviour so no crash log.

**Comment by Cazadorsniper** [comment]
All I can say is build around it.
