### ISSUE TITLE
Unable to create level-type=botania-skyblock  on server.

### ISSUE THREAD

**Issue by Leodil** [Cazadorsniper/PO3#1451]
packmode= all
playermode= Multiplayer
Have followed all previous threads and tried everything. level type set, world deleted, server restarted. no dice always spawns what appears to be vanilla and the quest tree is also unpopulated. Went as far as a wipe and reinstall of all minecraft files. Still no dice. Works great in single player. Im noticing DIM1 and DIM-1 not populating with forcechunk and other files you see in the single player save on GOG. Not sure if that matters or is relevant,

**Comment by Cazadorsniper** [comment]
Did you start the server using forge not minecraft server?

**Comment by Leodil** [comment]
I always started the multiplayer server via the the minecraft_server.1.12.2.exe from the PO3 server zip.

**Comment by Cazadorsniper** [comment]
use forge not that
