### ISSUE TITLE
Facade not placable

### ISSUE THREAD

**Issue by dragon011** [Cazadorsniper/PO3#1454]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**normal):**
**Game Mode: Singleplayer:**

**Description:**

I have Activate the Facade i hate when i see the Cables
Problem i can not place them why?

**Facade not placable:**

**Crash log (use pastebin or issue will be closed):**

Ps I like the Facades, why i can not place tham from Buildcraft or AppliedEnergistics2?

**Comment by Cazadorsniper** [comment]
Have you tried using the cable anchors?

**Comment by dragon011** [comment]
i have test the 2 options, craft the Facade not placable and with the cable anchors same not placable
