### ISSUE TITLE
Abyssalcraft Quest Gating

### ISSUE THREAD

**Issue by tony316123** [Cazadorsniper/PO3#1455]
**Pack Version:** 
3.3.61

**Pack Mode (Normal, Titan, Kappa):** 
Kappa

**Singleplayer, Multiplayer, or LAN?:** 
Singleplayer

**Description:**
In the "Omicron" section of the quests, the Statues quest informs the player to have lesser shoggoths form monoliths in order to obtain the several statues listed but one of the statues listed, the Cthulhu statue, is not produced via monolith generation. Either that or it is extremely rare. I have obtained 10+ statues of all other types without a single Cthulhu one forming. This blocks the player from viewing the next quests regarding progression in Abyssalcraft, specifically "Obtaining Potential Energy". I think either Cthulhu statues should generate with monoliths or that specific statue should be removed from this quest.

**Steps to reproduce:**
Have shoggoths form monoliths, cthulhu statue fails to generate.

**Crash log (use pastebin or issue will be closed):** 
N/A

**Comment by Cazadorsniper** [comment]
Keep trying.
