### ISSUE TITLE
Transfer node (items) and Transfer fluid and pipe from extrautilities2 is missing the recipe and I tested all packmodes

### ISSUE THREAD

**Issue by ruan12354** [Cazadorsniper/PO3#1456]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Normal, Titan, Kappa
**Singleplayer

**Description:**
I am new to the world of mods and I am reporting this bug that is without the recipe for these items and I would also like to know what is the difference between the Titan, Normal and Kappa packmodes.
if any english word is wrong i'm sorry. I'm brazilian :)

**Steps to reproduce:**
![2020-12-29_13 32 51](https://user-images.githubusercontent.com/75855177/103295764-69fc4680-49d3-11eb-8f42-9e83d6b4a04d.png)
![2020-12-29_13 35 38](https://user-images.githubusercontent.com/75855177/103295766-6b2d7380-49d3-11eb-96f6-4e1f40c83394.png)

**Crash log (use pastebin or issue will be closed):**
[latest.log](https://github.com/Cazadorsniper/PO3/files/5751242/latest.log)

**Comment by ruan12354** [comment]
![Uploading 2020-12-29_13.43.44.png…]()

**Comment by ruan12354** [comment]
![2020-12-29_13 43 44](https://user-images.githubusercontent.com/75855177/103295993-e5f68e80-49d3-11eb-8a30-43986645f0cb.png)

**Comment by Cazadorsniper** [comment]
Use a different pipe.
