### ISSUE TITLE
Extrautilities

### ISSUE THREAD

**Issue by ruan12354** [Cazadorsniper/PO3#1457]
in Extra Utilities 2, I don't see the Transfer Pipe or Transfer Nodes in JEI, only in the creative inventory window.

I tried uninstalling, downloading a fresh copy, and reinstalling. Nothing changed.

This originally happened when I updated my client and server to 3.2.55 version of Project Ozone 3. I was going to make Transfer nodes and noticed the recipes were gone. I tried making the recipe and it doesn't work.
How can I put the recipes back?

**Comment by Cazadorsniper** [comment]
Use a different pipe, that is the solution.
