### ISSUE TITLE
Duplication glitch in Baubley Heart Canisters

### ISSUE THREAD

**Issue by Rsl1122** [Cazadorsniper/PO3#1459]
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** normal
**Singleplayer, Multiplayer, or LAN?:** multiplayer

**Description:** 

It is possible to duplicate heart canisters with the heart amulet by moving it in the inventory while the heart amulet menu is open

**Steps to reproduce:**

Preparation:
- Obtain one heart canister (any color)
- Obtain Heart amulet
- Open the heart amulet screen by sneak + right-clicking while holding it
- Place the heart canister inside the amulet
- Close the amulet screen

Duplication:
- Open the amulet screen
- Move the heart amulet inside the inventory while the screen is open
- Take out the heart canister
- Close the amulet screen
- Open the amulet screen (The canister has been duplicated, one is in inventory, and also inside the amulet.)

**Possible fix:**

Prevent picking up open container items inside the inventory for that item (example: ProjectRed Exploration backpacks don't allow moving the backpack inside the inventory when it is open.)

**Comment by Cazadorsniper** [comment]
Dupe away, its pretty much a feature at this point.
