### ISSUE TITLE
Pack crashes during pre-init

### ISSUE THREAD

**Issue by MusicMan934** [Cazadorsniper/PO3#1460]
**Pack Version:3.3.61**
**Pack Mode (Normal, Titan, Kappa):Normal**
**Singleplayer, Multiplayer, or LAN?:Singleplayer**

**Description:** Game crashes during the pre-initialization phase.

**Steps to reproduce:** Don't know, I did add some performance mods so that it's playable

**Crash log:** [https://pastebin.com/tBTEUbH6](https://pastebin.com/tBTEUbH6)

**Comment by SilverSBH** [comment]
I have this issue too, I looked at the game output and from what little I understood it said something was initialized twice. I'm not sure what that means, but I figure red text means important. I haven't adjusted the pack at all. Sorry if it doesn't help.

**Comment by Cazadorsniper** [comment]
Get the pack off of Onedrive.
