### ISSUE TITLE
Minecraft Forge server crashes! SOLVED!

### ISSUE THREAD

**Issue by Dm5354** [Cazadorsniper/PO3#1461]
Pack Version: Latest
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?: Local server

Every time I run the server with .bat file there's an error!
https://pastebin.pl/view/dae3151e

I have downloaded the server file from curseforge.com gone thru setting up the server, agreed to eula, but every time I try to run the server with the forge server file, or the .bat file I get the same error!

**Comment by Cazadorsniper** [comment]
Can I see the log?
Also Latest isn't a Pack Version.

**Comment by Dm5354** [comment]
Server version: https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/files/3077771

Log: https://pastebin.pl/view/7fa072fb

**Comment by Cazadorsniper** [comment]
Pack Version: 3.3.61
1. Is Java installed?
2. Is it JRE or JDK? (Need JRE)
3. Change this "-Xms10G" to be lower

**Comment by Dm5354** [comment]
1. Yes Java is installed!
    I have jre1.8.0_271 and jdk-15

2. jre is added to the windows path

3. I made a fully clear server install and it still doesn't work!

**Comment by Cazadorsniper** [comment]
Can i see the contents in your server.properties?

**Comment by Dm5354** [comment]
Link to the clipp: https://1drv.ms/v/s!AlFrkPMzH007gcc4Fc6esqzQTu-yzw?e=IVobQy

Image of server.properties: https://imgur.com/a/sz0xNaN

**Comment by Cazadorsniper** [comment]
the server might be using the JDK instead of the JRE should check that.

**Comment by Dm5354** [comment]
How should I check it?

**Comment by Cazadorsniper** [comment]
You could try just deleting the JDK

**Comment by Cazadorsniper** [comment]
Can also try removing "nogui" from the batch file.

**Comment by Dm5354** [comment]
I tried it without nogui, it doesn't seem to do anything special, but removing jdk could help, i'll give it a try

**Comment by Dm5354** [comment]
Good lord it finally works! Ty so much!

**Comment by Cazadorsniper** [comment]
No problem.
