### ISSUE TITLE
Item Dupe with Mob Duplicator

### ISSUE THREAD

**Issue by Zedd34** [Cazadorsniper/PO3#1462]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
3.3.61
**Pack Mode (Normal, Titan, Kappa):** 
Kappa
**Singleplayer, Multiplayer, or LAN?:** 
Singleplayer
**Description:**
Nuclearcraft Feral Ghoul can pick up items and is not blacklisted in the mob duplicator.
**Steps to reproduce:**
**Crash log (use pastebin or issue will be closed):**

**Comment by Karthas077** [comment]
Erebus Titan Beetle as well as Erebus Black Ant are able to be granted a player-accessible inventory once tamed and are not blacklisted from the mob duplicator either.
