### ISSUE TITLE
AE2 using way more bytes to craft than it should

### ISSUE THREAD

**Issue by justino599** [Cazadorsniper/PO3#1466]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
I am using an auto crafting recipe in AE2 to make supremium ingots. I already have all of the required ingredients, so it would be expected that it would take only a handful of bytes to craft, but it says it will take 66,163 bytes. It gets more interesting because when I remove the recipes for the essences required to craft the item from my system, it calculates correctly. This leads me to believe it somehow thinks that it needs to craft the dependencies when calculating the bytes despite already having the required items in stock. **Perhaps this is due to my inclusion of the master infusion crystal in the recipes for the essence which is a funny item that is used in the recipe, but is not consumed.**

Here are some screenshots of before I removed the recipes and after, as well as my setup: [https://imgur.com/a/FrLjNS2](url)

Restarting the modpack did not solve the issue.

I first checked the AE2 issue page and found that they blame the issue on the modpack: [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4107](url)

**Steps to reproduce:**
1. Setup simple ME system (interface with molecular assembler, crafting storage, drive, controller, pattern terminal)
2. Make recipes and put them in the interfaces
3. Add the some elementium, superium ingots, and supremium essence to the system (enough to craft a supremium ingot)
3. Try crafting the Supremium Ingot with the essence recipes, then with it excluded and you will see that a different number of bytes are needed despite it only having to do one simple craft either way.

Pictures of my setup in a creative world: [https://imgur.com/a/LtbB5Ni](url)

I tried to reproduce this with compressed blocks, but it behaved in the way I would expect furthering my suspicion of the master infusion crystal.

**Crash log (use pastebin or issue will be closed):**
No crash.

**Comment by Karthas077** [comment]
Master infusion crystals have been a problem for AE2 crafting since forever. Aim an interface at an RFTools crafter and teach the crafter the recipes on ExtC mode. Create the patterns in processing mode and remove the infusion crystal from the recipe. Should have no problem queueing up 1000s of simultaneous essence upgrades.

**Comment by justino599** [comment]
Ok, will do. Thanks for the quick response! I have done that in the past, just wanted to cut down on the number of interfaces around the place. Again, thanks!
