### ISSUE TITLE
unable to do some recipes

### ISSUE THREAD

**Issue by Kingpowerfull** [Cazadorsniper/PO3#1469]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: latest
**Pack Mode  Kappa):**
** LAN:**

**Description:**
I have my packmode set to kappa both client and server but some recipes just dont work, there are also some recipes that show up as diamonds, but i wasnt trying to craft any diamonds
**Steps to reproduce:**
Unknown
**Crash log (use pastebin or issue will be closed):**
i have no crash log because game hasnt crashed

**Comment by Cazadorsniper** [comment]
whose server? Both the client and server packmode.cfg must be set to kappa and the game must be restarted.

**Comment by Kingpowerfull** [comment]
Problem is solved i had started That eorld thinking i was both client and server kappa but That was the problem acctually, which made my world also unable to reuse when settings are good so i started a new server with a new world, thnx for replying so fast
