### ISSUE TITLE
NotEnoughItems mod not letting me see recipe

### ISSUE THREAD

**Issue by LLNuke** [Cazadorsniper/PO3#147]
**Pack Version:**
latest
**Description:**
Whenever I click on an item in the sidebar it gives me it rather than showing me the recipe. Am I dumb or???
**Steps to reproduce:**
click on block
**Crash log:**
n/a

**Comment by martinschuberteu** [comment]
Set "Cheat Mode" to false in JEI config.

![2019-03-12_00 46 17](https://user-images.githubusercontent.com/19508559/54165274-48c61100-4460-11e9-891b-3ddcf2e3d5be.png)
![2019-03-12_00 46 21](https://user-images.githubusercontent.com/19508559/54165279-4b286b00-4460-11e9-8afb-df3fbf90c291.png)

**Comment by LLNuke** [comment]
Thank you !
