### ISSUE TITLE
unable to join multiplayer servers

### ISSUE THREAD

**Issue by soulbeast01** [Cazadorsniper/PO3#1470]
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** normal
**Singleplayer, Multiplayer, or LAN?:** multi

**Description:**
whenever trying to join a multiplayer server i get a lits of mods that are updated, iv tried updating the pack and re installing it but am getting the same errors

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Is it your server?
