### ISSUE TITLE
How to make on the server that players who came did not appear on my island, and appeared at home.

### ISSUE THREAD

**Issue by LeoGuys1** [Cazadorsniper/PO3#1472]
Hello there! Sorry for such a stupid question, but I couldn't find the information. If you can help, I will be very grateful. I would like players to appear on their island, so that there is a certain private.

I know that you can manually send players to your island: "/ botania-skyblock-spread <player name>". My friend and I checked it out and it worked, but when he died, he showed up on my island.I would like to be able to do this automatically. Because I won't always be on the server.

**Comment by Cazadorsniper** [comment]
This command "/ botania-skyblock-spread " gives players there own island they shouldn't be on your island unless your island is world spawn, but all you need to do is put the command in a command block to allow others to make their own island.

**Comment by LeoGuys1** [comment]
How can I write a command in the chat, and not through command blocks? Sorry for the late response. I worked ;(

**Comment by Cazadorsniper** [comment]
Others can use that same command without the command block.
