### ISSUE TITLE
Server crashing due to tiny progressions growth crystal

### ISSUE THREAD

**Issue by jamesxsc** [Cazadorsniper/PO3#1481]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
Server crashing due to tiny progressions growth crystal. Players on the server tell me the crops used with this crystal are also affected by imaginary time blocks from QuantumFlux.
**Steps to reproduce:**
 - Start server
 - Wait 1-2 mins then crash

**Crash log (use pastebin or issue will be closed):**
https://paste.xsc.co.uk/hujamixefi.rb

**Comment by Cazadorsniper** [comment]
Server is crashing because of both the growth crystals and imaginary time block, try removing one of them.

**Comment by jamesxsc** [comment]
That's fixed it thanks. We managed to break them just before the server crashed.
