### ISSUE TITLE
Actually Additions Laser upgrades not working

### ISSUE THREAD

**Issue by StarBanger69** [Cazadorsniper/PO3#1483]
**Pack Version: 3.3.61**
**Pack Mode (Normal, Titan, Kappa):Titan**
**Singleplayer, Multiplayer, or LAN?:Multiplayer**

**Description: The upgrades are taken from my inventory, but are not applied.**

**Steps to reproduce: Make an AA item laser relay, and attempt to use either the range or invisibility upgrades on the laser.**

**Comment by EpikDisko** [comment]
As I did found out, you must have extra upgrades in your hand for it to be applied, minimum of 2. Just 1 in your hand and it gets consumed without applying

**Comment by StarBanger69** [comment]
That is really annoying.
