### ISSUE TITLE
Chance Cube crash

### ISSUE THREAD

**Issue by PaLaS0** [Cazadorsniper/PO3#1484]
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?:Multiplayer

Description: Chance cubes randomly crash server every now and then. I would just remove it, but that disables certain recipies. I'll attempt to prevent them from spawning

Steps to reproduce: Not sure, people on server just keep using them till it crashes. (Can't really tell people to not to use it)

Crash log (use pastebin or issue will be closed): Most of the logs are empty, but there are 2 normal ones:
https://pastebin.com/Ynm07vje
https://pastebin.com/XySpefmd

**Comment by Cazadorsniper** [comment]
can you try them again after using a different java version that isn't OpenJDK?

**Comment by PaLaS0** [comment]
> can you try them again after using a different java version that isn't OpenJDK?

Sorry, seems like I'm forced to using OpenJDK by host provider.

**Comment by PaLaS0** [comment]
Seem to be still spawning in certain biomes despite having lowest chance possible and chest and surface spawning disabled, maybe the config isn't even used anymore

**Comment by Cazadorsniper** [comment]
try updating the mod and telling other people to update the mod
