### ISSUE TITLE
Flying in Twilight Forest

### ISSUE THREAD

**Issue by crnea** [Cazadorsniper/PO3#1485]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa):Kappa
Singleplayer, Multiplayer, or LAN?:Singleplayer

Description: Flying in Twilight Forest using Lordcraft flight

Steps to reproduce: 
1. Go to Twilight Forest
2. Cast flight (tier 4 air skill from Lordcraft)
3. Wait for effect to wear off
4. Can now fly in Twilight Forest

Crash log (use pastebin or issue will be closed): No crash

**Comment by Cazadorsniper** [comment]
Not to worried about this. Its a feature now.
