### ISSUE TITLE
Quantum Tank resetting

### ISSUE THREAD

**Issue by ColeMan328** [Cazadorsniper/PO3#1487]
Hey,
I am running this pack on a server with a friend and I am having an issue with the quantum tank. I have one connected to my mob farm to keep the experience that overflows from my normal XP tank while I am offline or just while I am off doing something else. The problem doesn't occur until I leave the server, then when I reconnect all the experience (including anything that had built up prior to me leaving) is gone from the tank. I know my friend didn't mess with it because looking at my server console I can see that nobody had logged on. Please let me know if I am doing something wrong on my end or the server end. 
Thank you in advance for your help,
P.S. I love the mod pack by the way, one of my favorites by far.

**Comment by Cazadorsniper** [comment]
Try a different tank to see if its just the quantum tank.
