### ISSUE TITLE
Server skipping ticks regularly

### ISSUE THREAD

**Issue by RiccardoBarbieri** [Cazadorsniper/PO3#1489]
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?: multiplayer

Description:
The server lags and in the console the message `Can't keep up! Did the system time change, or is the server overloaded? Running XXXms behind, skipping XX tick(s)` appears many times. If it can be helpful i noticed that the messages appear regularly: every about 20 seconds the server skips 500 or so ticks and immediately after it skips another 100 or so ticks and this repeats again 20 seconds later.

The server does not crash but I will post anyway the log of the console, notice the sequence I cited above (500 ticks, 100 ticks, repeat)

[log.txt](https://github.com/Cazadorsniper/PO3/files/6025038/log.txt)

**Comment by antcking** [comment]
Me and my friend are having the same exact issue on the launch of the server.

**Comment by Grufoony** [comment]
I have the same issue too

**Comment by Cazadorsniper** [comment]
This is a large pack, its going to skip ticks on a server.
