### ISSUE TITLE
Lord Craft Teleportation back and forth

### ISSUE THREAD

**Issue by Itskyranite** [Cazadorsniper/PO3#1490]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: PO3-3.3.61**
**Pack Mode (Normal, Titan, Kappa): Kappa**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description:**
When you teleport between the Lord Craft dim and back when you go into your inventory and click an item it drops it on the floor and won't let you move it makes me restart the game which takes ages!

**Steps to reproduce:**
1. Teleport to Lord Craft dim
2. Teleport back
3. Repeat until you cannot select items from the Inventory

**Crash log (use Pastebin or issue will be closed):** Not Crashing just having to relaunch.

**Comment by Itskyranite** [comment]
**Update**

Just had the glitch when doing any teleport, just went to the nether and it would chuck the items out, tabbed out, opened my recording software to get a clip and it disappeared after!

but still happens.

Kyran

**Comment by Cazadorsniper** [comment]
Likely lag.
