### ISSUE TITLE
Error trying to install the modpack

### ISSUE THREAD

**Issue by Woderr** [Cazadorsniper/PO3#1492]
Hey,

When I try to install the modpack. It downloads and begins to install, but then stops with the 'missing addon ID 300742" error code (see attached image).

![Project Ozone 3 Error](https://user-images.githubusercontent.com/80259891/110319202-72da4b80-8006-11eb-864e-9506c1a87859.PNG)

Any ideas?

Thanks

**Comment by Cazadorsniper** [comment]
keep trying.

**Comment by Woderr** [comment]
Thanks, tried multiple times and now works.
