### ISSUE TITLE
"Consequental Immortality"(Immortal, but unable to interact with almost anything including chests)

### ISSUE THREAD

**Issue by EpikDisko** [Cazadorsniper/PO3#1493]
After going near an active Death Generator and the doom countdown finishes, the Charm of Life II saved me, while I had OpenComputers nanomachine active with absorption. As I noticed the absorption bar is completely gone, I tried to reset the nanomachine, upon resetting, nothing happened, however, when taking out my Heart Amulet, my health bar instantly went to 0 without dying, constantly shaking my screen as if the game is trying to put me to "You died!" screen. As the result, I can't die at all, my screen constantly shakes, my character is stuck to being red, and I can't interact with anything that has to do with managing inventory items except my own inventory, which means I can't open chests, drawers and machines.
![2021-03-08_22 22 38](https://user-images.githubusercontent.com/63596935/110327266-18b8a500-805d-11eb-99a5-c03aca775b92.png)
Edit: Forgot to tell that I cannot pick up items on the ground, either.
And reconnecting and having the server to restart won't fix it at all.

Pack version: 3.3.61
MC Version: 1.12.2
Pack mode: Kappa
Multiplayer

**Comment by EpikDisko** [comment]
seems the way of making this problem is by taking fatal damage and having anything to save you such as totem of undying, and then take out the equipped maxed out Heart Amulet

**Comment by Cazadorsniper** [comment]
yeah the mod baubley hearts does that.
