### ISSUE TITLE
P03 Dungeon Locator Not working

### ISSUE THREAD

**Issue by JonFoxy** [Cazadorsniper/PO3#1494]
So i am playing on a server with my friend. Stock SP world and configs. Thing is when i went to get the Dungeon Locator from Galacticraft the item has no animation. No movement no nothing. It doesnt do anything except point south with no movement what-so-ever

**Comment by Cazadorsniper** [comment]
Have you tried going south?

**Comment by AyeItsKatieMC** [comment]
It's intended to point in the direction of the nearest dungeon from where the player is currently standing weather or not the dungeon has already been raided.

**Comment by SweetestPumpkin** [comment]
Enable animations from optifine and it will work
