### ISSUE TITLE
Game crashes on world load

### ISSUE THREAD

**Issue by ghost** [Cazadorsniper/PO3#1496]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.61
**Pack Mode (Normal, Titan, Kappa):Normal
**Singleplayer, Multiplayer, or LAN?:Singleplayer/LAN

**Description: Game crashes every time I load up my current world. If I create a new world, everything is fine and normal. It only crashes when I try to load my current world. I tried loading a backup save and that didn't work. I did a fresh install and put my save back in, but that still doesn't work. I am far enough in the pack that I have the High Tech crafting table from ArmorPlus and have been to the Moon/working on Mars.

**Steps to reproduce: Not sure, just loaded my world.

**Crash log (use pastebin or issue will be closed): [Pastebin](https://pastebin.com/bN32B5Mf)

**Comment by Cazadorsniper** [comment]
What were you doing before you crashed and did you have any chunkloaders active?

**Comment by NYfan0122** [comment]
Not sure really. I was upgrading my armors but needed more diamond blocks. I had finished adding some ME drives to my system and was working on improving my power generation.

**Comment by Cazadorsniper** [comment]
can I have a copy of your world?

**Comment by NYfan0122** [comment]
2021-03-12-17-40-00.zip
<https://drive.google.com/file/d/1kar-UxZStny78ACJlqfaJZ5oMSjRjiTV/view?usp=drive_web>
here it is.

**Comment by Cazadorsniper** [comment]
Don't have access to it, literally have to request to do so.

**Comment by NYfan0122** [comment]
try this:
https://drive.google.com/file/d/1kar-UxZStny78ACJlqfaJZ5oMSjRjiTV/view?usp=sharing

**Comment by Cazadorsniper** [comment]
Got it and from the sheer size of one of the files something is going on on dimension -12 (the moon) maybe.

**Comment by NYfan0122** [comment]
hmmm. not sure what it is. As far as i remember, I don't think I left
anything there

**Comment by Cazadorsniper** [comment]
Did you place down an arc furnace from galacticraft?

**Comment by NYfan0122** [comment]
Nope

**Comment by Cazadorsniper** [comment]
You can try using MCedit and maybe vanillafix to try and see what is crashing you (or I guess play despite the crash), but other than that I can't tell what's happening.

**Comment by NYfan0122** [comment]
Ok, I'll check it out.

**Comment by NYfan0122** [comment]
How do I go about "fixing" it through MCedit? Like how would I know if
something is wrong?

**Comment by Cazadorsniper** [comment]
well in the log it mentions a block however it doesn't mention an id of said block so might have to check each tileentity (furnaces pulverizers etc.) to find the culprit. Not sure if Lag goggles would help though.

**Comment by NYfan0122** [comment]
How would I know what block is the problem?

**Comment by Cazadorsniper** [comment]
I don't know since the log didn't tell me the id of the block

**Comment by NYfan0122** [comment]
But how do I check the block is what I'm trying to say. How would I know what to look for?

**Comment by Cazadorsniper** [comment]
Well with lag goggles mod the block would be highlighted red if its causing lag.

**Comment by NYfan0122** [comment]
But I can't physically load into the world. I have to look at things in MCedit.

**Comment by Cazadorsniper** [comment]
I believe with Vanilla fix you can.

**Comment by NYfan0122** [comment]
Update: with VanillaFix, I'm now getting [this](https://pastebin.com/TeBkspSX) crash report.
It happens after the world gets loaded, but before I can see anything. I basically see only 1 frame of the world before the crash.

**Comment by Cazadorsniper** [comment]
Try removing the Extra Planets mod.

**Comment by Cazadorsniper** [comment]
it looks like you have something in your inventory that the game doesn't like.

**Comment by NYfan0122** [comment]
Just removed Extra Planets. The new crash said "unknown," so [here](https://pastebin.com/41Piv3U1) is the new crash.

**Comment by Cazadorsniper** [comment]
Yeah, I don't know what could be wrong, it could be a corrupted chunk or something.

**Comment by NYfan0122** [comment]
Sorry for such the late response. I think it has something to do with my
Galacticraft gear that I have in my inventory. When I use MC Edit, I can't
see the extended inventory (since Galacticraft gear is in that other tab).
Not really sure what to do here.

**Comment by Cazadorsniper** [comment]
You can maybe try nbtedit and edit the stuff out your inventory.

**Comment by 4censord** [comment]
You could try to launch with the
```
# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false
```
options set to true in the forge.cfg file
it will remove anything throwing an error on loading.
Don not forget to make backups and to disable it again
