### ISSUE TITLE
Extra Utilities 

### ISSUE THREAD

**Issue by ColdtQ** [Cazadorsniper/PO3#1499]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Search in JEI "node" or "@extra utilities" and nothing shows up.

**Steps to reproduce:** Search in JEI for extra utilities mod

**Crash log (use pastebin or issue will be closed):**

**Comment by KorewaLidesu** [comment]
`@extra @util`
