### ISSUE TITLE
Robit quest not Completing

### ISSUE THREAD

**Issue by Sreolla** [Cazadorsniper/PO3#15]
Pack Version: 3.0.38 (Newest)

Description: Crafted the Robit and waited 5-10min and did nto get credit for completing it, Also charged it and still nothing.

Steps to reproduce: Craft the lil guy

https://puu.sh/CRBXz.png
https://puu.sh/CRBXc.png

**Comment by Jadoz** [comment]
I have the same problem.  Tried Robit in different places of inventory and hotter, charged and uncharged.  I did notice a spelling difference in the quest, although this should not matter: Robrit not Robit.

**Comment by Cazadorsniper** [comment]
Robrit is the moofluids mod author

**Comment by CraftalotReloaded** [comment]
Mekanism likes to store data in strange ways, for example, refined storage and inventory tweaks also have issues with mekanism items

**Comment by Jt4112** [comment]
so i still have this issue?

**Comment by lulyou** [comment]
> so i still have this issue?

Seems like it, it's happening to me right now. Really unfortunate.
