### ISSUE TITLE
How does one stop new islands from spawning?

### ISSUE THREAD

**Issue by Heroic-Brine** [Cazadorsniper/PO3#1500]
I am trying to create a server with a spawn, so people start there, then use a command block to get an new island. sorry if i missed it but cannot find it anywhere.

**Comment by Cazadorsniper** [comment]
build around the initial island

**Comment by Heroic-Brine** [comment]
Every time someone new joins it spawns a new island for them.

**Comment by Cazadorsniper** [comment]
at world spawn?

**Comment by Heroic-Brine** [comment]
Well it seems to be in the spawn chunks always a new place but you can see from one to another.

**Comment by Cazadorsniper** [comment]
What are you using to spawn the skyblock islands, garden of glass or something else?

**Comment by Heroic-Brine** [comment]
Garden of glass is set, but i have no idea what actually spawns them as i want it to stop so it will only be spawned via command (/botania-skyblock-spread)

**Comment by Cazadorsniper** [comment]
Are you using any plugins or added mods that could be affecting the server? 
Do you think there is already a command block located somewhere?

**Comment by Heroic-Brine** [comment]
No it's a completely "vanilla" server with just level-type=botania-skyblock and a higher chunk distance set. Right now command blocks are disabled as they will only be enabled once spawn has been constructed. not sure if it is botania-skyblock that does this?

**Comment by Cazadorsniper** [comment]
is it possible for you to completely reset everything?

**Comment by Heroic-Brine** [comment]
so i presume it is not supposed to spawn them? only one? I'll do some more testing, i can reset everything but the map and the player inv.

**Comment by Heroic-Brine** [comment]
So turns out some jackasses were building identical islands for fun, it only spawns in the same location every time.
Thank you for the help anyway.

**Comment by Cazadorsniper** [comment]
lol
