### ISSUE TITLE
Server install issue

### ISSUE THREAD

**Issue by M37AU** [Cazadorsniper/PO3#1501]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Server, Multiplayer

**Description:** Followed install instructions and uploaded to Hosthorde, renamed minecraft_server.1.12.2.jar to custom_server.jar, game launches with errors, only plays as vanilla server side.

**Steps to reproduce:** 

**Crash log (use pastebin or issue will be closed):**
[J3UQ.txt](https://github.com/Cazadorsniper/PO3/files/6255422/J3UQ.txt)

**Comment by Cazadorsniper** [comment]
Launch using forge not the minecraft server.jar.

**Comment by M37AU** [comment]
I did that also, it just goes into a loading and crash loop, I can post the log when I get home from work in a couple of hours...

**Comment by M37AU** [comment]
I renamed the Forge jar to custom_server.jar and ran it, this is what came back, the server tries to start then stops
[DYZA.txt](https://github.com/Cazadorsniper/PO3/files/6255893/DYZA.txt)

**Comment by Cazadorsniper** [comment]
are you using a jdk instead of a jse?

**Comment by Cazadorsniper** [comment]
yup, I see it. Try using normal Java instead if possible.

**Comment by M37AU** [comment]
I'll contact the host and get back to you, Thanks :-)

**Comment by 4censord** [comment]
I think you are using the wrong java version.
in line 16 it says `Option UseConcMarkSweepGC was deprecated in version 9.0`
so you are running java >= 9, maybe try with java 8?

**Comment by M37AU** [comment]
Absolutely on the mark folks, Joseph at Hosthorde gave me a Java 8 file to download, put it in the jar file, changed the console settings and viola, it's up and running so I was a combination of host version and my lack of any useful knowledge, Thanks for all the help, it is appreciated :-)
