### ISSUE TITLE
Server doesn't load.

### ISSUE THREAD

**Issue by Flup25** [Cazadorsniper/PO3#1506]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** PO3-3.3.61
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I open the server startup and, after a while (5-7mins), the cmd starts relaying "Can't Keep Up! Did the system time change or is the server overloaded?". I've tried twice - same result. Game works fine, but cannot start the server up.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/VMz9bN8H

**Comment by Cazadorsniper** [comment]
in server.properties put max-tick-time=-1

**Comment by Flup25** [comment]
Great! That solved the problem to some extent, but it now freezes with the same warning. Doesn't technically crash so I have no crash log :/

**Comment by Cazadorsniper** [comment]
The ticks being skipped is going to happen no matter what, PO3 has a lot of mods.
