### ISSUE TITLE
Crash because of the mod: equivalent integrations

### ISSUE THREAD

**Issue by HydraDen** [Cazadorsniper/PO3#1507]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: .3.3.61
Pack Mode (Normal, Titan, Kappa): Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: crash game (mod: equivalent integrations)

Steps to reproduce: when I drag soulbound talisman into the transmutation chamber, I have a crash game

Crash log (use pastebin or issue will be closed): sorry, but I unfortunately do not know what it is (I just Russian and do not know much)
[crash-2021-04-18_09.00.24-server.txt](https://github.com/Cazadorsniper/PO3/files/6330219/crash-2021-04-18_09.00.24-server.txt)

**Comment by HydraDen** [comment]
please help(

**Comment by Cazadorsniper** [comment]
copy/paste crash then copy/paste link to it: https://pastebin.com/

**Comment by gmdevl** [comment]
> please help(

I think the crash is related with the version of the project e or project ex, you need to have the latest version of both for the soulbound talisman to work.

**Comment by HydraDen** [comment]
Hello, it doesn’t work. Still crashed the same way.

  
>Понедельник, 17 мая 2021, 19:34 +03:00 от gmdevl ***@***.***>:
> 
> 
>please help(
I think the crash is related with the version of the project e or project ex, you need to have the latest version of both for the soulbound talisman to work.
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
--
HydraDen
