### ISSUE TITLE
Game crashes every time I load up my current world.

### ISSUE THREAD

**Issue by DireWolfXD** [Cazadorsniper/PO3#1512]
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa):Normal
Singleplayer, Multiplayer, or LAN?:Singleplayer, LAN

**Description:I start the curseForge / MultiMC and the modpack starts nicely, then I start my backup, it loads, freezes and doesn't respond.

**Steps to reproduce: I don't what i supposed to write here

**Crash log (use pastebin or issue will be closed): https://paste.ee/p/4IQZq

**Comment by Cazadorsniper** [comment]
If you are able, try updating random patches.

**Comment by DireWolfXD** [comment]
unfortunately the error still exists

**Comment by Cazadorsniper** [comment]
i don't know what it could be then, sorry.

**Comment by DireWolfXD** [comment]
:,(

**Comment by DireWolfXD** [comment]
okay
