### ISSUE TITLE
When Playing Kappa po3, a majority of the crafting recipies dont work (iron buckets, cobblestone gen upgrades, seared brick items)

### ISSUE THREAD

**Issue by FyreNeximusYT** [Cazadorsniper/PO3#1514]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by AudioRezZ** [comment]
Make sure that the server is in kappa mode aswell as your client.
