### ISSUE TITLE
Insolator won't accept AgriCraft mystical agriculture seeds.

### ISSUE THREAD

**Issue by Kimano** [Cazadorsniper/PO3#1515]
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
The agricraft mystical agriculture seeds don't work in the phytogenic insolator.  I found a bug report opened against agricraft here that seems to have addressed it, but it doesn't seem to work. https://github.com/AgriCraft/AgriCraft/issues/229

**Steps to reproduce:**
Make a normal mystical agriculture seed, put it in the insolator, and it works. Agricraft breed it to 10/10/10 and try again, and it won't go in.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Agricraft adds nbt data to the 10/10/10 seed and putting the seed in the TE machine will end up removing the nbt data (then you will have to re-10/10/10 them) there is nothin i can do about this.
