### ISSUE TITLE
Walia crash

### ISSUE THREAD

**Issue by idkimanerd** [Cazadorsniper/PO3#1519]
# EDIT: randomly stopped crashing somehow 
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** kappa
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:**
crash on last step of loading\
![image](https://user-images.githubusercontent.com/81585709/119154435-04066f00-ba07-11eb-89f7-5f0333c1f970.png)

**Steps to reproduce:**
run the game with the mods listed in the log

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/PEdBshz2

**Comment by Cazadorsniper** [comment]
Try it without Waila/hwyla.
