### ISSUE TITLE
Game stuck at 7/7 

### ISSUE THREAD

**Issue by Tisknogn** [Cazadorsniper/PO3#1524]
Last version
Kappa
Singleplayer

My game is stuck at 7/7 all the time (only on PO3), i was able to open it with:

"How to Fix:
-When game freezed at 7/7 ,click close(Cross) button
-Mınecraft will show not responding screen and will give you 3 choice.
-Click the first one "Try to Restore the Program" and wait 1-2 second.You are in the game."
But this is not working anymore. Here is my log (and there isn't any crash reports):

https://paste.minecrafthelp.co.uk/?bfe32f42202c0c59#77H7u19ZSW5uorAKoNGucKzmA4EPttuRR26vvBzSgB7E

I tried it with curseforge, gd launcher and manually installed but not worked.

**Comment by Cazadorsniper** [comment]
you can try an updated version of java 8 but that is all I can see that is wrong.

**Comment by Tisknogn** [comment]
Tried, and unfortunately haven't worked.

**Comment by Tisknogn** [comment]
I found a way if anyone has the same problem. Just disable foamfix and better fps mods, and go to your config folders and open splash.properties, set enabled=false. Then just open the game and wait around 20-30 mins. This worked for me.
