### ISSUE TITLE
Bucket Duplication

### ISSUE THREAD

**Issue by TraumaticEffect** [Cazadorsniper/PO3#1525]
Pack Version: 3.3.61
Pack Mode: Normal
Singleplayer + LAN (Tested on both)

Description: Drinking Milk buckets cause bucket to be duplicated.

Steps to reproduce: Have milk bucket in hotbar slot #2, have nothing in hotbar slot #1, drink milk.
I have a video of it, for proof, if it's needed.

**Comment by Cazadorsniper** [comment]
Duplicate of #562 #873 #911 #1037 #1145 #1209 #1400
