### ISSUE TITLE
Project Ozone 3: A New Way Forward Skyblock Problem

### ISSUE THREAD

**Issue by ThaiJam** [Cazadorsniper/PO3#1526]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 1.12.2
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** On a Server 

The string mesh recept isnt working . If I do the recept iam not getting a string mesh, iam getting a silk

**Comment by Cazadorsniper** [comment]
What pack version?

**Comment by AyeItsKatieMC** [comment]
You have to change the pack config to reflect what game mode your playing if your playing on Kappa and you don't have the config set to Kappa mode it'll show the normal mode recipes
