### ISSUE TITLE
no idea what happened

### ISSUE THREAD

**Issue by idkimanerd** [Cazadorsniper/PO3#1527]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.3.61
**Pack Mode (Normal, Titan, Kappa):** kappa
**Singleplayer, Multiplayer, or LAN?:**single
**Description:**
crash when clicking an ex nihilio creatio stone hammer, i had made a tconstruct sledge hammer, but that disappeared 
**Steps to reproduce:**
clicking an ex nihilio creatio stone hammer
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/Y4LfYQWb

**Comment by Cazadorsniper** [comment]
Clicked where?

**Comment by idkimanerd** [comment]
i grabbed it from a chest, but when i tried to put it in my inventory, it crashed

**Comment by Cazadorsniper** [comment]
Might have been something else, are you able to continue playing?

**Comment by idkimanerd** [comment]
yes, the crash was a one time thing
