### ISSUE TITLE
Overloaded Infinity Capacitor/Barrel/Tank quests

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#153]
Pack Version: 3.0.38

Description: The Infinity Capacitor, Infinity Barrel and Infinity Tank have normal crafting recipes and do not require the Ultimate Crafting Table. Not sure if this is intended?

Steps to reproduce: Check JEI

![2019-03-12_18 56 29](https://user-images.githubusercontent.com/19508559/54223801-90987700-44f8-11e9-9bf4-4978ed006120.png)

Crash log: N/A

**Comment by Cazadorsniper** [comment]
Intended for normal mode
