### ISSUE TITLE
All avaritia recipes, except for the sword and armor, are not showing up. 

### ISSUE THREAD

**Issue by artuzin** [Cazadorsniper/PO3#1530]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.61
**Pack Mode (Normal, Titan, Kappa): Titan
**Singleplayer, Multiplayer, or LAN?: Singleplayer.

**Description: When I search for avaritia items and click to see the recipe, it doesn't show up. I checked on the pack .zs files and everything was ok. I already tried reinstalling but it didn't work out.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
What avaritia recipes are you looking for?

**Comment by artuzin** [comment]
> What avaritia recipes are you looking for?

I am looking for the axe, shovel, pickaxe, hoe, cosmic meatballs, bow, skullfire sword, infinity catalyst, enhancement crystal and the asgardandelion. None of these recipes show up.

**Comment by Cazadorsniper** [comment]
They should all be available as Extended Crafting, if not do "/ct syntax" in-game to see what comes up or check "all_9x9.zs".

**Comment by artuzin** [comment]
It worked, thank you. By the way where i can find the recipe for the ultimate singularity ?

**Comment by Cazadorsniper** [comment]
Ultimate Singularity just uses all the other singularities in the 9x9.
