### ISSUE TITLE
Lord Craft quest givers bugged - won't spawn and stay up

### ISSUE THREAD

**Issue by zeklaine** [Cazadorsniper/PO3#1532]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):** kappa
**Singleplayer, Multiplayer, or LAN?:** single player

**Description:**  the lordic summoner blocks in the NEXUS from lord craft now spawn and despawn the lords at the same time. The lord pops in then pops out instantly.

**Steps to reproduce:**
I was on my way back to nexus to turn in the 4 quests for using 3rd level spells. after clicking the ascension matrix, game crashed. upon reloading I was standing in the nexus and the described behavior had begun

**Crash log (use pastebin or issue will be closed):**

**Comment by zeklaine** [comment]
Tried restarting, relogging, and removing the nexus dimension (DIM2) and having it regenerate.  They still won't stay up.

**Comment by Cazadorsniper** [comment]
Have you tried using a backup before the crash?
