### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by HAPPYGUNNER479** [Cazadorsniper/PO3#1533]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.3.61
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer on a main server through apex servers 
**Description:**
At random when player is in air the game will crash. So either from jumping or using Hang-glider. Also had a crash when closing the game. It so far has only happened to me but it has happened multiple times. After the crash I can no longer get on the server as it just says I left the game and then shows the same crash report. The only way for me to get back on the server is to delete PO3 off my PC and then reinstall and that lets me load back in.  
**Steps to reproduce:**
When character is in air from either jumping to flying or even falling. Also just quitting
 the games caused a crash. 
**Crash log (use pastebin or issue will be closed):**

[crash-2021-06-12_04.08.14-client.txt](https://github.com/Cazadorsniper/PO3/files/6642801/crash-2021-06-12_04.08.14-client.txt)

**Comment by HAPPYGUNNER479** [comment]
What paste bin? I sent the crash report file what else do I need to send? I'll send whatever I need to but that's all it says to send. I need help! Please tell me what you need to figure out what is wrong with the mod pack

**Comment by HAPPYGUNNER479** [comment]
@Cazadorsniper

**Comment by HAPPYGUNNER479** [comment]
The PasteBin Link:   https://pastebin.com/Sxx6Mc3z

**Comment by Cazadorsniper** [comment]
It maybe possible you have some type of anti flight setting on or just need to change the keybind for erebus gliders
