### ISSUE TITLE
Not able to craft a transmutation table?

### ISSUE THREAD

**Issue by AudioRezZ** [Cazadorsniper/PO3#1535]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.3.61**
**Pack Mode (Normal, Titan, Kappa):Normal**
**Singleplayer, Multiplayer, or LAN?:Multiplayer**

**Description:I have all the things needed to craft the transmutation table but it is not letting me. When i place all the materials it will pop up and when i try to take it out of the resulting craft it will disappear and leave all the items**

**Steps to reproduce:Try and craft it and it wont work?**

**Crash log (use pastebin or issue will be closed):No crash report.**

**Comment by Cazadorsniper** [comment]
Try restarting the server and client.

**Comment by masterkore** [comment]
Philosopher's stone has to be charged up to max for the recipe to work for some unknown reason. Experienced the same issue on my server.
