### ISSUE TITLE
Experiencing humongous lagspikes

### ISSUE THREAD

**Issue by autismusprime69** [Cazadorsniper/PO3#1538]
This will be a follow-up to my previous bug report.

So recently, I've been experiencing insane lagspikes over the course of my playthrough so much to the point where the game becomes borderline unplayable. To break it down, these lagspikes appear super frequently, one every 2 to 5 seconds, up to 5 to 10 seconds. I tried switching between BetterFPS algorithms but none of them changed anything. I have the lagometer turned on so that you can see the lagspikes and the frequency in which they occur:

![image](https://user-images.githubusercontent.com/74802660/123708686-d8627a00-d839-11eb-9655-0f058bc93d54.png)

Please fix this! It's straight-up game-breaking!

**Comment by DannyDan4** [comment]
You aren't allocating enough RAM. Allocate the recommended 6-8GB of RAM, and this will all go away.
