### ISSUE TITLE
Findme don't work whit a seed analyser placed

### ISSUE THREAD

**Issue by Flocon32** [Cazadorsniper/PO3#1540]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
14.23.5.2954
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
You can't use Findme With An seed analyser placed 

**Steps to reproduce:**
1/place a seed analyser
2/Use Findme (T) 

**Crash log (use pastebin or issue will be closed):**

https://user-images.githubusercontent.com/65869715/124673104-9039fc00-deb8-11eb-8cd9-3d871bdab2bb.mp4

is a video of me make the bug (you are not obligate to see it )

**Comment by Cazadorsniper** [comment]
I'm aware but there is nothing I can do about it.

**Comment by Flocon32** [comment]
Ok thx
