### ISSUE TITLE
The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by Jeff5b** [Cazadorsniper/PO3#1543]
**Pack Version:**
3.3.61
MC 1.12.2

Pack Mode (Normal)

Singleplayer & Multiplayer

**Description:**
Whenever I try to load my world it crashes with 
The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
Exit Code: -1

If I try to run the world using my dedicated server it has this error message:
The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/Fij9D5JV
this is the log from loading it in single player

**Comment by Cazadorsniper** [comment]
Try turning on the remove entities config in forge.cfg on the server and client to see if the entity crashing you will go away or you can remove Epic Siege Mod.

**Comment by Jeff5b** [comment]
Thanks removing the Epic Siege Mod did fix it and allow me to start the world
