### ISSUE TITLE
Player Tracking through Overworld and even in other Dimensions Help

### ISSUE THREAD

**Issue by gameradept** [Cazadorsniper/PO3#1544]
Player tracking me and other players through game and dimension from the beginning.  Is there anyway to do this in Ozone 3 without hacking?  I seriously have not been able to duplicate what he is doing and can call out player locations just when asked.  i don't want to accuse him of cheating without looking here first.  Thank you all in advance.

**Comment by Cazadorsniper** [comment]
I don't Know
