### ISSUE TITLE
Minecraft Modded 1.16.5.My game keeps crashing when I try to load into my world.Havent even moved or deleted any files.

### ISSUE THREAD

**Issue by rakutenjong21** [Cazadorsniper/PO3#1546]
Pack Version-Better Minecraft Mod
Pack Mode -Normal
Singleplayer

Yesterday morning I was playing the mod perfectly, no crashes or anything, and now when I tried to load my world, it crashes for some reason, even though I haven't moved or touched any files.

Crash log-https://gist.github.com/rakutenjong21/edfdb9d535f295ba0564a900ce0b1206

**Comment by Cazadorsniper** [comment]
This Issue tracker is for Project Ozone 3 which is in minecraft version 1.12.2.
