### ISSUE TITLE
Ping increasing on server

### ISSUE THREAD

**Issue by Marszpace** [Cazadorsniper/PO3#1549]
**Pack Version: Pack Mode (Normal, Titan, Kappa): ** Normal

**Singleplayer, Multiplayer, or LAN?:**  Multiplayer

**Description:** After joining the server, my (HammerCore) ping starts at around 18000ms and increases until I timeout.
On the console, any message I sent is visible to the server, anything I do on the server is recieved.

From what I see, it seems the server can receive my data, but it cannot send it back to me.
This sometimes happen to me (and my friends) at random, and it usually fixes itself.

**Steps to reproduce:** Happens quite randomly.

**Crash log (use pastebin or issue will be closed):** No crashes.

**Comment by ShiroETsuki** [comment]
Seconded. This has been an issue for me across multiple networks, multiple different computers, and multiple reinstalls. 

Doing forge /ping will show normal ping, but hammercore will display obscenely high ping rates as high as 220K. Interactions on the server will take roughly the length of the hammercore ping to complete. 

Others have reported this, and has been an issue for over a year now.
