### ISSUE TITLE
Submitting RAK causes Epeolatry to disappear from inventory 

### ISSUE THREAD

**Issue by DeadlySoren** [Cazadorsniper/PO3#1550]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.61
**Pack Mode (Normal, Titan, Kappa): Titan
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: As title says, I noticed that the sword kept vanishing from my inventory without me knowing how. Did some testing and found that submitting RAK (but not other items that I tested) to the quest for the net tier of the sword caused the Epeolatry in my inventory to instantly vanish. This seems to happen only the first time that I submitted RAK to the next tiers quest.

**Steps to reproduce: Get an Epeolatry (tested with tiers 1-4), submit RAK manually to the next Epeolatry quest (seems to only happen the very first time you submit RAK to the quest, repeatable with different tiers of the quest), the sword will then vanish

**Crash log (use pastebin or issue will be closed): N/A - no crash

**Comment by Cazadorsniper** [comment]
Quest takes the last tier of the sword too. Quest is doing exactly what its suppose to do.

**Comment by DeadlySoren** [comment]
> Quest takes the last tier of the sword too. Quest is doing exactly what its suppose to do.

The quest doesn't take the sword when it is completed, it takes the sword the very first time you submit RAK *regardless* of whether or not the quest will be completed by the submission. So if the quest takes 1000 RAK and you only insert 500, the sword in you inv is still taken despite you not finishing the quest.

**Comment by Cazadorsniper** [comment]
The Quest will take anything inside of your inventory that it needs to complete the quest whether the quest completes or not.
If you have the sword and RAK inside of your inventory the quest will take both whether it completes or not.

**Comment by DeadlySoren** [comment]
None of the quests list the Epeolatry as a requirement for the next tier which caused me to lose the first 3 of them when I started trying to get the next. If this isnt a bug then I think it needs to be changed, either take the sword last or don't take it at all.

**Comment by Cazadorsniper** [comment]
The sword is listed as a requirement.

**Comment by Cazadorsniper** [comment]
Try pressing the arrow buttons next to the Detect/Submit button.
