### ISSUE TITLE
Game crashes every time I enter/load my world.

### ISSUE THREAD

**Issue by AdamMTB** [Cazadorsniper/PO3#1551]
Pack Version: 3.3.61
Pack Mode (Normal, Titan, Kappa): Normal
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Everything works very well but when the loading to my world ends the game crashes instantly and i'm not even able to see anything on my world.

Steps to reproduce: I don't know, I'm just trying to load my world

Crash log (use pastebin or issue will be closed): [https://pastebin.com/J6GB4G0x](url)

**Comment by Cazadorsniper** [comment]
Try activating the erroring entites and tileentities configs in forge.cfg then see if that works.

**Comment by AdamMTB** [comment]
i'm still getting the same crash and error

**Comment by Cazadorsniper** [comment]
What was the last thing you did?

**Comment by AdamMTB** [comment]
I was upgrading my armor and charging it
I placed wireless charging things 
I was doing a machine to automate NuclearCraft's FourS'more QuadS'mingot food
and i think thats all i was doing before i saved my world

**Comment by Cazadorsniper** [comment]
Have any mob grinders or sieves running?

**Comment by AdamMTB** [comment]
no i only have 5 farms with seeds and 2 mob spawners that are turned off

**Comment by Cazadorsniper** [comment]
Can I have a copy of your world please.

**Comment by AdamMTB** [comment]
how do i send it

**Comment by Cazadorsniper** [comment]
Upload it to onedrive, google drive or dropbox then send me the link to it.

**Comment by AdamMTB** [comment]
https://1drv.ms/u/s!AiYzv9idR0THah6FODy2yZWUljE?e=vKacVe

**Comment by Cazadorsniper** [comment]
Did it stop happening?

**Comment by AdamMTB** [comment]
no

**Comment by Cazadorsniper** [comment]
Then why close the issue?

**Comment by Cazadorsniper** [comment]
Try using a backup of the world, it also seems you added Integrated Dynamics as well.
