### ISSUE TITLE
cant connect to publicly hosted servers

### ISSUE THREAD

**Issue by Blazier1** [Cazadorsniper/PO3#1553]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** 
I was testing out some of the servers at Complex gaming and keep gettng a disconnect screen. I talked to the staff there and abosultly nothing has worked. i tried IP flushes, ipv6 changes. dns changes.

**Steps to reproduce:** Log in. get disconnected

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/FMddJ5qY

**Comment by Cazadorsniper** [comment]
How are you starting the server?

**Comment by Blazier1** [comment]
Im not. This is a public server from Complex Gaming. im trying to connect to them.

**Comment by Blazier1** [comment]
I have used the search function, any other people reporting this issue have been the host of the server. im not the host. im trying to connect to someone elses server and getting a server error.

**Comment by Cazadorsniper** [comment]
As of right now the only thing I can think of is that this might be a connection issue. Although the log was saying you're trying to connect to the server with missing mods.

**Comment by Blazier1** [comment]
Yes exactly. I downlaoded the client from Curse and from another launcher, both give me the same error. 
the Mods are in the folder.
they said the server they are hosting is 3.3.61 and the files im downloading from curse are 3.3.61. i also changed the mode to Kappa befor ever launching it. I was in touch with the Devs and they gave me all sorts of things to work around. IPV6 using direct IPs all of it.

**Comment by Cazadorsniper** [comment]
Have you've tried other public hosted servers? maybe Mine Your Mind has one.

**Comment by Blazier1** [comment]
Yeah I have done the one from dirtcraft.net and the from craftersland. Both work just fine

**Comment by Cazadorsniper** [comment]
Something must be going on with Complex gaming's servers and there is nothing i can do about that.
