### ISSUE TITLE
EnderIO conduits disconnecting from mekansim quantum entangloporters

### ISSUE THREAD

**Issue by CaptainPlasma101** [Cazadorsniper/PO3#1557]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.3.61**
**Pack Mode (Normal, Titan, Kappa): Normal**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: title
I think this might be caused by mek quantum entangloporters only assigning sides to output after enderio conduits load since enderio conduits don't reattach to mek quantum entangloporters if sides haven't been assigned before and need to be broken and replaced

this does not happen to every one and I'm not completely sure which ones are affected

![both top and bottom should be connected but only bottom is connected](https://user-images.githubusercontent.com/58668715/130020766-b9aa5820-82d9-412e-ae4c-da09f6fa495a.png)
**

**Steps to reproduce:
1. attach enderio conduit to mek quantum entangloporter
2. wait (maybe log out, I'm not sure)
3. see that conduits have disconnected**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
AFAIK they always done this so make sure to use mekanism's universal cables.
