### ISSUE TITLE
item/fluid/energy conduits not working properly 

### ISSUE THREAD

**Issue by Alaa0Alaa** [Cazadorsniper/PO3#1560]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
PO3 3.3.61
EnderIO 1.12.2-5.2.59
**Pack Mode (Normal, Titan, Kappa):**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
I'm having this issue with all conduits (item/fluid/energy) basically they are transferring power fluids and items even if they are not supposed to transfer 
I tried basic/advanced/big/big advanced item filters and fluid filters but this issue is ignoring the filters settings 
the following picture shows that the liquid is getting extracted inside the fluid conduit even tho the source is on  insert

![2021-08-31_19 13 08](https://user-images.githubusercontent.com/89862606/131554825-2257e3a1-65c5-4ec5-b4ee-d7be23af4a14.png)

**Steps to reproduce:**
1 I place the conduits 
2 I select insert or extract with never active redstone mode on the the fluid/item/power source
3 I select insert with always active redstone mode on the other sides
4 Items/Fluids/power is transferred when it shouldn't 
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Try again in the newest version of the pack.
