### ISSUE TITLE
Can't figure out how to make a server garden of glass gamemode

### ISSUE THREAD

**Issue by Maximsuss** [Cazadorsniper/PO3#1566]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Kappa):**
** Multiplayer ?:**

**Description:**
When I am trying to go through the server files I cannot find the file that I go to in order to change the world type.
**Steps to reproduce:**
No steps just going to server files through Curse Forge
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Start the server, agree to the eula, then start the server again to get the server.properties to change world types.
