### ISSUE TITLE
VeinMiner 

### ISSUE THREAD

**Issue by MindOfNasser** [Cazadorsniper/PO3#1568]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*1.12.2*
**Pack Mode (Normal):*normal*
**Singleplayer, Multiplayer, or LAN?:*SinglePlayer*

**Description:**
So im playing Project ozone 3 & having fun but im wondering why VeinMiner Mod doesn't work with me am i not pressing the right keys or the mod is removed or the mod has another name please help me :( <3
**Steps to reproduce:**

**Comment by Cazadorsniper** [comment]
the mod is call Ore Excavator.

**Comment by MindOfNasser** [comment]
> the mod is call Ore Excavator.

is this mod available on Project ozone 3 ? when i search onm mods list i don't find the mod or i just have to use the keybinds if yes tell me what is the keybinds

**Comment by Cazadorsniper** [comment]
the keybind should be the grave key "~" next to 1.

**Comment by MindOfNasser** [comment]
Thank you so much, sorry for wasting ur time <3
