### ISSUE TITLE
Applied Energestics 2 Meteors

### ISSUE THREAD

**Issue by MindOfNasser** [Cazadorsniper/PO3#1569]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode (Normal, Titan, Kappa):*normal*
**Singleplayer, Multiplayer, or LAN?:*singleplayer*

**Description:*hi so i want to getting started in applied energestics 2 but there is problem with the engineering presser for inscriber those only can be found in applied energestics 2 meteors only is there any way else to found those presser btw im playing Garden of Glass skyblock**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):*there is no crash*

**Comment by Cazadorsniper** [comment]
Should be able to craft them using certus quartz essence i believe.

**Comment by MindOfNasser** [comment]
Oh my good i hate Mystical Agriculture i think i have to do it anyways thanks for help <3
