### ISSUE TITLE
Crash when entering Void World

### ISSUE THREAD

**Issue by GoDzViper** [Cazadorsniper/PO3#157]
**Pack Version:**
3.0.38

**Description:**
Occasionally when I enter the Void World (from simple void worlds) my game crashes. I'm pretty sure it only started happening after I set up an ME Quantum link thing in there. I'm using the void world for my mystical agriculture crops (using agricraft) to try and keep lag in the overworld to a minimum. Like i said its only occasionally but when it does happen i have to restart my game which takes a good 10 minutes.

**Steps to reproduce:**
Create an ME Quantum Link thing in both the overworld and Void world and hope when you enter that it crashes

**Crash log <use pastebin or similar>:**
https://pastebin.com/4zFDai03

**Comment by martinschuberteu** [comment]
I've had a ME quantum ring in my simple void world for about 2 weeks, and never had any issues. Are you using the portal block to enter, or something like the advanced dislocator from DE (which I'm using)?

**Comment by GoDzViper** [comment]
Sorry for the late reply mate never got a notification. I usually use the portal but have also use the /spawn command as well. Not sure why but it seems to have lessened up now

**Comment by martinschuberteu** [comment]
Can you check the block at -1159,63,-419? There is a known issue with sound mufflers causing crashes, and you crash log looks like this might be the case.

**Comment by GoDzViper** [comment]
if i can get back into the game ill remove my sound muffler and hope that works thanks. Im crashing on launch now cause of the wireless universal terminal from extra cells 2 :( Worst thing is i put it in my me system so i gotta figure out a way of deleting it from outside the game...

**Comment by martinschuberteu** [comment]
lol, I thought the wireless universal terminal does only cause a crash in a specific baubles slot. Good luck with that!
