### ISSUE TITLE
AE2 interface not working

### ISSUE THREAD

**Issue by EletroZe** [Cazadorsniper/PO3#1571]
3.3.61
normal
LAN
I m playing in my map with friends. We made an AE2 system every thing is working fine until I tried to put an interface on an molecular assembler , worked, a sag mil , didnt work, put one in an alloy smelter , didnt work, and now i tried in a chest and didnt work.
1-having an AE2 system running , having a crafting unit;
2- connect the system a molecular assembler using me interface;
3- trying to do this toturial (https://www.youtube.com/watch?v=KNTnfuVHLWw) (yes i know its in brasilian portuguese but u can still follow what he is doing just fine).

**Comment by Cazadorsniper** [comment]
try this youtuber's tutorials https://www.youtube.com/c/therealtkh
