### ISSUE TITLE
Crash on load, backups affected. - ArmorPlus

### ISSUE THREAD

**Issue by sauerkrau5** [Cazadorsniper/PO3#1572]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.3.61
**Pack Mode (Normal, Titan, Kappa):** normal
**Singleplayer, Multiplayer, or LAN?:** single

**Description:** Crash while loading world. Backups affected. Removing ArmorPlus fixes it.

**Steps to reproduce:** ArmorPlus workbench existing in world.

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/CnCieMsx

**Comment by Cazadorsniper** [comment]
All the workbenches or just 1 of them. What was near the workbench? Anything in it?

**Comment by sauerkrau5** [comment]
It was just the first tier workbench. Empty. All I used it for was to craft up to tin armor. It was above an oak wood slab, next to an oak chest and a heat sand block.

**Comment by TheOneAboveX** [comment]
having same problem

**Comment by TheOneAboveX** [comment]
From what I can see armor plus seems to be an old issue
