### ISSUE TITLE
PO3 Server crashing because single tick took 90 sec

### ISSUE THREAD

**Issue by SymoHTL** [Cazadorsniper/PO3#1574]
# Use the search function before reporting to see if the issue has been reported before.
3.3.61
Kappa
Multiplayer server, hosting on my own pc

so i have played like 200 hours on the server 1 am currently full avaritia
the server has 20 gb of ram and 8 cores 4.3 ghz cpu i start it and after ~100 - 120 seconds it crashed pls help

https://pastebin.com/hHeMj6eS

**Comment by Cazadorsniper** [comment]
Disable the ServerHangWatchdog by putting max-tick-time=-1 in the server.properties.

**Comment by SymoHTL** [comment]
ok thanks now it doesnt crash anymore but now it has a latency of 3 seconds on my local machine

**Comment by SymoHTL** [comment]
hmm cant really do that bc i need everything

**Comment by SymoHTL** [comment]
ok i did some work again and... well now i have 0.25 ticks per second


https://pastebin.com/KvzLsC1T

**Comment by Cazadorsniper** [comment]
yeah the beta version should work fine on anything Kappa mode and lower.

**Comment by SymoHTL** [comment]
well the beta doesnt start


https://pastebin.com/rSjYEyFE
