### ISSUE TITLE
Game crashing after using Farm Station from EnderIO.

### ISSUE THREAD

**Issue by Ayfri** [Cazadorsniper/PO3#1576]
**Pack Version:** PO3 -3.4.4
**Pack Mode (Normal, Titan, Kappa):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** I just crafted and used for the first time the Farm Station from Ender IO and it crashes, and the game stay frozen also.

**Steps to reproduce:** Use the Farm Station from Ender IO with mystical agriculture crops (with and without sticks) plus also cactus and wheat with sticks.

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/dnmigv5D

**Comment by Cazadorsniper** [comment]
Try using the Industrial Foregoing plant gatherer.
