### ISSUE TITLE
Mobs see through walls and blow up mobfarms

### ISSUE THREAD

**Issue by InfamouslyJaded** [Cazadorsniper/PO3#1578]
Pack Version:3.4.4
Pack Mode: Mythic (but also applies to other pack modes)
Singleplayer

Description: Since all mobs can now lay down TNT it's not even enough to not spawn creepers, the only way to get out of this is to claim chunks or possibly make a obsidian mobfarm, but there are still things you want in a mobfarm that can't be made blastproof without claiming chunks which just feels like a cop-out, especially since it also prevents wither explosions, thus invalidating wither proof blocks. Either going back to mobs not seeing through walls or removing the functionality of dropping TNT from them would solve or at least alleviate that issue.
Steps to reproduce:
Make a mobfarm, either completly blocked off or with the player's eye level being at mobs feet and get close to it after the mobs spawn.

**Comment by Lordbufu** [comment]
Pack Version: 3.4.4
Pack Mode: Kappa
Singleplayer

Can confirm this happens on other modes, accidentally updated switching launchers, the small dark room i had was a problem after that. That being said though, the overworld seems mostly doable with a bit of creative thinking imho, just no very early game mob farming. Dint really need to claim chunks, or use blast proof blocks either, though i can see this type of AI being rather problematic with wither farms yes (dint test it either).

Other dimensions though, like the nether .... could actually be considered hell now imho. And could be a problem for progression in other modes, for example netherrack options in terms of balance feels a bit off imho unless i'm missing something obvious (haven't played PO 3 a lot yet, so don't hate if i did miss something obvious).

That is my main concern with this, the rest seems very manageable even early game, that's just my 2 cents though.

Steps to reproduce: Either what InfamouslyJaded said, or open a portal and visit another dimension with plenty of hostile mob spawns.
