### ISSUE TITLE
Default Ender IO Alloy Recipes in Kappa Mode

### ISSUE THREAD

**Issue by EuphoricDreamer** [Cazadorsniper/PO3#1580]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.4.4
**Pack Mode (Normal, Titan, Kappa): Kappa
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:** The default recipes for Energetic Alloy, Vibrant Alloy, Energetic Silver, Vivid Alloy, Redstone Alloy, Conductive Iron, Melodic Alloy and Stellar Alloy Ingot appear in JEI and are useable in Kappa mode. Didn't check other modes, so potentially could be problems with them there too.

**Steps to reproduce:** Check recipes in JEI, insert default recipes into alloy smelter.

**Comment by alex2711** [comment]
EnderTweaker-1.12.2-1.2.2 Работает
