### ISSUE TITLE
Overworld Apples Crash Game

### ISSUE THREAD

**Issue by ejerram1** [Cazadorsniper/PO3#1583]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.4.4
**Pack Mode (Normal, Titan, Kappa):** Mythic
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Eating overworld apples in other dimensions crashes the game (only nether, twilight forest, and lost cities tested)

**Steps to reproduce:**
Eat an overworld apple in another dimension

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/SL66aQny

**Comment by calvissuperman** [comment]
Still having the same issue in version 3.4.9 Normal/Kappa mode single player

[pastebin](https://pastebin.com/PUbkCgxF)

**Comment by Cazadorsniper** [comment]
overworld apples don't exist in  3.4.9

**Comment by calvissuperman** [comment]
> overworld apples don't exist in 3.4.9

Ah, well the update didn't remove them from my inventory then. Thank you for the quick reply!
