### ISSUE TITLE
why did you remove the loot bag? it was great for the farms

### ISSUE THREAD

**Issue by ruan12354** [Cazadorsniper/PO3#1587]
why did you remove the loot bag? it was great for the farms.

**Comment by Cazadorsniper** [comment]
What are you talking about?

**Comment by YarlinPoe** [comment]
The "Loot Bag Storage" likely. Was a dupe bug I heard so it was disabled?
There is a setting in LootBag config about Duping if it was fixed but never readded.
Side note, i wish it was readded. I just delete the bags to avoid the hassle dealing with it. 
Kinda spoils some fun i guess. =/
