### ISSUE TITLE
Quantum Compressor Not Accepting Resources/Producing Singularities

### ISSUE THREAD

**Issue by AdamButtle15** [Cazadorsniper/PO3#1589]
Ive been trying to make singularities in my singleplayer/lan game but the Compressor is not accepting items into its buffer. Ive tried all the previous fixes that have been mentioned before: break/replace, different chunk, ive even tried different dimensions etc. but none have worked so far.
the buffer just says "empty" or "X/0" ive also toggled the "limited item" mode which usually results in the latter
![image](https://user-images.githubusercontent.com/59932954/142294814-a702c094-5a8d-4424-b49a-5063ef7e87ad.png)

![image](https://user-images.githubusercontent.com/59932954/142294846-765f584c-a9c2-4291-ae8e-7a71cfc43de8.png)

On a side note JEI still shows the number needed as 9001 rather than 1000.
![image](https://user-images.githubusercontent.com/59932954/142294990-eb73425e-0c46-4b88-839e-ac22b8edcc79.png)

Using 3.4.4 on normal mode

**Comment by Cazadorsniper** [comment]
try a new Quantum Compressor.
