### ISSUE TITLE
Xin world crash

### ISSUE THREAD

**Issue by Xetard** [Cazadorsniper/PO3#159]
**Pack Version:** 3.0.38

**Description:** Fought 2 first bosses in Xin dimension but after starting Xin fight i crash every 10 sec.

**Steps to reproduce:** Just be in the dimension , no matter where in the void i am i will crash and have to reboot the pack.

**Crash log <use pastebin or similar>:**
[crash-2019-03-14_18.18.46-server.txt](https://github.com/Cazadorsniper/PO3/files/2967668/crash-2019-03-14_18.18.46-server.txt)

**Comment by Cazadorsniper** [comment]
Don't go to that dimension is the only solution atm
