### ISSUE TITLE
Restonia tool leveling bug

### ISSUE THREAD

**Issue by purpleAn0n** [Cazadorsniper/PO3#1595]
Probably doesn't matter but Mythic mode.

Tinkers weapons with Restonia parts don't get TinkerToolLeveling XP. Probably because of the "change all damage to Magic damage and Magic piercing".
Don't know if it's pack config or mod issue, that's why reporting here.

**Comment by Cazadorsniper** [comment]
This is a mod issue not a pack issue (just confirming that its not the pack is all)
