### ISSUE TITLE
Texture pack that displays textures badly or not

### ISSUE THREAD

**Issue by aebischer** [Cazadorsniper/PO3#1599]
**Pack Version: 6.44**
**Pack Mode (Normal, Titan, Kappa):Normal and Kappa (not tested titan)**
**Singleplayer, Multiplayer, or LAN?:Multiplayer **

**Description:**
Greetings
With this version, the texture pack that I use (BDCraft) no longer or badly displays the textures of certain blocks, the most notable are the grass and the oak planks.
The texture pack is exactly the same with no additions or version changes.

**Steps to reproduce:**
Simply install the pack
https://bdcraft.net/downloads/purebdcraft-minecraft/
I did my tests with the 64X

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Have you've tried reloading the entire pack?

**Comment by aebischer** [comment]
Yes, I downloaded it again and tested it on 2 different servers, as well as solo.
when the modpack is on version 3.3.61, everything is correct, but as soon as I go to 3.4.4 the problem occurs.
quite simple to test and actually reproduce.

**Comment by Cazadorsniper** [comment]
You tried this one correct? https://bdcraft.net/community/releases-for-packs-f10/project-ozone-t5173.html

**Comment by Cazadorsniper** [comment]
Can I get screenshots, a gif or a video of it?

**Comment by Cazadorsniper** [comment]
Might have found the reason this happens.

**Comment by Cazadorsniper** [comment]
Find  "More optimized multipart model condition storage. Inspired by malte0811's research. [default: true]
    B:smallModelConditions=true"

In the Foamfix.cfg and turn it to false then reload the pack.
