### ISSUE TITLE
Crashing when loading.

### ISSUE THREAD

**Issue by MCuser87** [Cazadorsniper/PO3#16]
**Crash log:**https://pastebin.com/zPfxFqtC

Keeps crashing when trying to load reborn core on the loading screen. I am by no means good to read crash logs but after trying to figure it out for about a week now, I can see there always is the same logs and they always end on reborn core crashing. Maybe there are more errors, but not skilled enough too understand it;)

**Comment by Cazadorsniper** [comment]
Reinstall the pack and move your world over.

**Comment by MCuser87** [comment]
I have now deleted and installed pretty much everything that can be re-installed and still get crash.
https://pastebin.com/XLn3458R 
here is the newest crash log.

**Comment by Cazadorsniper** [comment]
Is it possible that your storage drive is full?

**Comment by MCuser87** [comment]
Have about 70 gb available.

**Comment by Cazadorsniper** [comment]
Did you edit a config or add a mod?

**Comment by Cazadorsniper** [comment]
This error maybe from your PC's doing.

**Comment by MCuser87** [comment]
The errors started after the update of the pack. It worked fine before that. Should I send a crash log to rebornecore maker and see if they can come up with any suggestion?

**Comment by Cazadorsniper** [comment]
sure, although its more than reborncore erroring.

**Comment by MCuser87** [comment]
Ok. Will send them a message and see if  they can figure out something more.

**Comment by MCuser87** [comment]
Seems to be a common thing to happen without a fix yet, so will check around som settings and firewalls and se if i can figure something out.
