### ISSUE TITLE
Auto-backup feature doesn't work

### ISSUE THREAD

**Issue by jazzadellic** [Cazadorsniper/PO3#160]
**Pack Version:**     
3.0.38

**Description:**
Every time an auto-backup attempts I get a message in red that says something like "failed save java exception".

**Steps to reproduce:**
Happens every time an auto-backup attempts.

**Crash log <use pastebin or similar>:**
It doesn't cause a crash

Other notes: I've had this problem with other packs on my old computer, and never found a solution to it (I just got a new pc a few days ago). So it might not be anything with your modpack specifically, but whatever mod is doing the auto-backups. Google has failed to find me a solution. Please help! I really want to play P03, but not without auto-backup. I just had my game borked and had no auto-backup to go back to (the zip files in the backup folder were empty).

**Comment by Cazadorsniper** [comment]
is it possible you ran out of memory in your drive where the backups are stored?

**Comment by jazzadellic** [comment]
Definitely not that, brand new HD with 1.5 TB of space. I actually just put together a new pc 6 days ago. Fresh install of win 10. Someone conmented on a reddit thread they got this problem when installing on twitch but not MultiMC so I’ll try that when I get home. But yeah I’ve had this problem before on my old pc as well as new. I guess it’s FTB utilities that does the backup?

**Comment by Cazadorsniper** [comment]
yes

**Comment by nzminecraftDOTcom** [comment]
Make sure the server has permission to write to the drive/folders you are attempting to back up to, java may not be allowed to write files to that location.

**Comment by jazzadellic** [comment]
> Make sure the server has permission to write to the drive/folders you are attempting to back up to, java may not be allowed to write files to that location.
> Edit: a server log showing it attempting to backup would be useful in determining the actual issue.

How would I check if the server has permission or get a server log? Thanks.

**Comment by nzminecraftDOTcom** [comment]
Latest.log or one of the other ones relating to the time when it attempted to do a backup. Look for the attempted backup occurring in the log text.

**Comment by jazzadellic** [comment]
> Latest.log or one of the other ones relating to the time when it attempted to do a backup. Look for the attempted backup occurring in the log text.
> Is this a home-hosted server or a server that is rented from a hosting company?
> If it's at home, where is the server running from - what folder path.

Actually, I'm just playing a single player game on my pc, does that mean I have a server?

**Comment by nzminecraftDOTcom** [comment]
I don't see why the auto-backup feature would be of any use in single player.. It's not as if you have a server on 24/7

**Comment by Cazadorsniper** [comment]
Singleplayer is basically a server, latest.log exists in the log folder.
