### ISSUE TITLE
spectre enrgy injector depleting draconium energy core

### ISSUE THREAD

**Issue by manhabuti** [Cazadorsniper/PO3#1600]
Pack Version: 3.4.4
Pack Mode: kappa
Singleplayer
as seen in the image, i placed the spectre enrgy injector on the cryo-stabilized fluxduct, that is attached to the draconium energy pylon and the spectre enrgy injector drained all the energy from the core, and started showing it as negative, leaving me out of energy entirely.
the second image is the core with the spectre enrgy injector still placed.
the third image is the core charging after i removed the spectre enrgy injector to show that it took all the energy.
****it seems that the bug goes away with a spectre coil placed to a machine, but it occured to me when i placed the injector with none coils placed.

![imagem_2021-12-13_161548](https://user-images.githubusercontent.com/96080434/145874004-f45413ae-21ef-428e-8ef1-10e9539e8b6d.png)
![image](https://user-images.githubusercontent.com/96080434/145874031-8cdf057b-548f-482f-9d39-641dfe981617.png)
![imagem_2021-12-13_161736](https://user-images.githubusercontent.com/96080434/145874236-ce0e8638-23e8-4938-a3be-649713e44aa8.png)

**Comment by Cazadorsniper** [comment]
Cryo-flux duct transfer rate is too high for the spectre energy injector to handle. try putting an energy cube or energy cell between the 2.
