### ISSUE TITLE
Update Forge to newer version.

### ISSUE THREAD

**Issue by Kamisoi** [Cazadorsniper/PO3#1603]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.4.4
**Pack Mode (Normal, Titan, Kappa):** All
**Singleplayer, Multiplayer, or LAN?:** Multiplayer mostly

**Description:**
Since for some time now Log4J is big issue for public servers, would it be possible to update Forge to **14.23.5.2860** or **14.23.5.2859**? That'd be great.

**Steps to reproduce:**
 -

**Crash log (use pastebin or issue will be closed):**
None.

**Comment by Cazadorsniper** [comment]
Already did just waiting on other issues that might arise before I update the pack again.
