### ISSUE TITLE
Loot Chests can't be claimed multiple times in quest.

### ISSUE THREAD

**Issue by AFlyingVillager** [Cazadorsniper/PO3#1604]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: Latest
**Pack Mode (Normal, Titan, Kappa): Mythic
**Singleplayer, Multiplayer, or LAN?: Multiplayer

**Description: Can't claim loot chests multiple times.

**Steps to reproduce: Idk

**Crash log (use pastebin or issue will be closed): None/ ingame issue.

**Comment by Cazadorsniper** [comment]
I just tried this yesterday and i was able to claim multiple fine, the cool down was being weird though.
