### ISSUE TITLE
Ender IO alloying not working since update 3.4.5

### ISSUE THREAD

**Issue by Diversion98** [Cazadorsniper/PO3#1605]
Pack Version: Pack Mode (Mythic) -> same problem in Kappa
Dedicated Server (without plugins and 1 mod added: DC Integration)

Description: Since update 3.4.5, recipes like Vivid Alloy Ingot, Energetic Silver Ingot, Energetic Alloy Ingot, ... are not working.
The recipe we see in JEI for Energetic Silver Ingot: 1x electrotine, 1x electrum ingot, 1x glowstone dust.
If we put it in the Alloy Smelter (tested all 3 of them), they just dont smelt.

I did a restart of the server, changed the packmode to kappa, restarted it and back to mythic (on both client and server).

Steps to reproduce:
1. Look in JEI for the ingredients and gather them
2. Open your Alloy Smelter
3. Put the ingredients in the Smelter or click the "+" button in jei
4. Smelting doesn't work

I temp fixed this by downgrading to version 3.4.4 again.

Do you need any other information?

edit:
I added a crafttweaker recipe myself for Energetic Alloy Ingot but is also not working so its probably something with ender io.

Cheers.

**Comment by lucalipsxstroons** [comment]
Pack Mode : Kappa

Got the same Problem :D

**Comment by Cazadorsniper** [comment]
Funny thing is that the recipes are there.

**Comment by lucalipsxstroons** [comment]
Yeah, i hope they will fix it soon.....
Can´t progress right now.....

**Comment by Cazadorsniper** [comment]
they?
