### ISSUE TITLE
(3.4.4) Incredibly glitchy/missing textures and animations

### ISSUE THREAD

**Issue by Switchblaze** [Cazadorsniper/PO3#1606]
Pack Version: 3.4.4
Pack Mode: Normal
Singleplayer, and Multiplayer.

Upon installing the modpack through curseforge and loading in, for 1 second or so everything is fine, then all my trees go weird colors, stone is see-through, some glitchy yellow seizure is coming from the distance, and animations of both myself and mobs have their limbs spaz everywhere. And that's just what I've noted within the first minute or so as I tried to fix things.

Oh, and my FPS is also tanking something fierce too. Like, 6-28 FPS when my normal is 120+ even on other brutal modpacks.

I have deleted and redownloaded the modpack multiple times, tried changing numerous graphics settings and BetterFPS settings, all to no avail. My friends that started the modpack with me have no such problem even as they are on the same server as me, so it's definitely on my end somewhere. If ya need any more info, let me know. Kinda sad that my buddies are having fun without me.

No crashing, somehow... Here's some example screenshots though:
![Screenshot_90](https://user-images.githubusercontent.com/13336389/147868565-6236e06e-21eb-4d99-8642-0fb2d2e7f8d8.png)

![Screenshot_91](https://user-images.githubusercontent.com/13336389/147868566-81a8bd2e-6d67-4ebd-89b9-f9b1c13be716.png)

![Screenshot_92](https://user-images.githubusercontent.com/13336389/147868567-1a88d63d-855a-438e-a458-5b5989f2bd74.png)

**Comment by Cazadorsniper** [comment]
Change Betterfps algorithm to something else that isn't taylor's then reload the pack.
