### ISSUE TITLE
ExtraCells2 missing from the client install

### ISSUE THREAD

**Issue by cnordbakk** [Cazadorsniper/PO3#1608]
**Pack Version:** 3.4.6
**Pack Mode (Normal, Titan, Kappa):** All
**Singleplayer, Multiplayer, or LAN?:** Client

**Description:**
The curseforge client install doesn't include ExtraCells2 (anymore). I had to add it from the server files to get a matching .jar.
**Steps to reproduce:**
* Updated 3.4.4 to 3.4.6.
* Tried repair
* Tried installing a new instance (GDLauncher)
* Tried installing "ExtraCells2 - SamLam140330's Fork" 2.6.5 but it didn't match the server .jar
* Copied the .jar from the server and that worked

**Comment by Cazadorsniper** [comment]
I just tried it and ExtraCells2 installed fine.

**Comment by cnordbakk** [comment]
Hmm... ok. Still no luck here, but I guess there's something weird on my end then.
