### ISSUE TITLE
Feature request: Add custom magneticraft crushing table recipes to the hydraulic press

### ISSUE THREAD

**Issue by laod** [Cazadorsniper/PO3#161]
**Pack Version:**
3.0.38

**Description:**

It would be very helpful to have some or all of the custom crushing table recipes available in the hydraulic press. I tested, successfully, with the following scripts/all_modes/magneticraft.zs changes:

`mods.magneticraft.HydraulicPress.addRecipe(<minecraft:iron_ingot>, <thermalfoundation:material:32>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<minecraft:gold_ingot>, <thermalfoundation:material:33>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:128>, <thermalfoundation:material:320>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:131>, <thermalfoundation:material:323>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:129>, <thermalfoundation:material:321>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:160>, <thermalfoundation:material:352>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:136>, <thermalfoundation:material:328>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:135>, <thermalfoundation:material:327>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:134>, <thermalfoundation:material:326>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:133>, <thermalfoundation:material:325>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:132>, <thermalfoundation:material:324>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:130>, <thermalfoundation:material:322>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:161>, <thermalfoundation:material:353>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:162>, <thermalfoundation:material:354>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:163>, <thermalfoundation:material:355>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:164>, <thermalfoundation:material:356>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:165>, <thermalfoundation:material:357>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:166>, <thermalfoundation:material:358>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<thermalfoundation:material:167>, <thermalfoundation:material:359>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<redstonearsenal:material:32>, <redstonearsenal:material:128>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<embers:ingot_dawnstone>, <embers:plate_dawnstone>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<nuclearcraft:ingot:4>, <immersiveengineering:metal:35>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<extendedcrafting:material:0>, <extendedcrafting:material:2>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<bigreactors:ingotyellorium>, <bigreactors:dustyellorium>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<bigreactors:ingotgraphite>, <nuclearcraft:dust:8>, 150, 0, true);
mods.magneticraft.HydraulicPress.addRecipe(<bigreactors:ingotgraphite>, <nuclearcraft:dust:8>, 150, 0, true);
`

**Steps to reproduce:**
N/A

**Crash log <use pastebin or similar>:**
N/A

**Comment by Cazadorsniper** [comment]
Or you could just use a metal press.
