### ISSUE TITLE
3.4.4 Overworld Spawns new Chunks as Vanilla Minecraft PO3 Sky is now Vanilla sky

### ISSUE THREAD

**Issue by MrAek546** [Cazadorsniper/PO3#1610]
3.4.4
Normal
LAN

Not sure what caused it, but created a NASA workbench and after that was exploring Twilight forest, upon using Overworld Apple game crashed, when relogging was in a Vanilla Minecraft chunk next to a chunk error 1000 blocks from spawn.  Flew Around in creative and noticed all new chunks are vanilla minecraft, sky is vanilla sky, when traveling in Twilight forest all new generation is new chunks that didn't line up with old chunk, almost like seed changed.  I don't know if the apple corrupted Overworld or if it was the NASA workbench.  It seems like Botonia-Skyblock was randomly turned off in the overworld?  Is there any way to patch or fix this?  

Due to afking near a spawner for drops before noticing the sky and eating the apple that sent me to a vanilla chunk all my backups are of this corrupted version of the overworld.

When I went to a 2 week old back up it wasn't corrupted, when I created a new world in the server folder it wasn't corrupted, when I created a new "region" file in the dimensions and cut my chunks into it it was still corrupted.  Not sure how to fix, of if it's possible.

Not sure if related but there was a Crash Log 2 days prior to noticing the symptoms:

https://pastebin.com/p0d0BLyT

**Comment by MrAek546** [comment]
I actually don't think the crash report is related, that was after we had already noticed the vanilla minecraft, I think that was when we were playing with server config files to try and fix it --  was actually last night - I read the date wrong.

**Comment by Cazadorsniper** [comment]
Only way to fix that is a backup of the world, I will be removing the overworld apple soon.

**Comment by MrAek546** [comment]
default backups were every 30 minutes for 6 backups, and server was running longer than 3 hours, wish the default backups were set longer!  RIP world.

So I was right in thinking it was the Overworld apple that did us in.  Guessing there was now way to MC edit my chunks into a overworld.

**Comment by Cazadorsniper** [comment]
I'm unsure of how to do edit in existing chunks into another world, sorry.

**Comment by MrAek546** [comment]
Man, that sucks, we're desperate to not lose all the seed progress. we had a manual backup that's 2 weeks (and 40+ hours of playtime) behind, going to try and pack everything into the em system, take out the disks and transfer the user profile, this way we at least don't lose the seed progress!  ugh
