### ISSUE TITLE
Screen constantly flickers with extremely white flashes

### ISSUE THREAD

**Issue by HadiSDev** [Cazadorsniper/PO3#1614]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.4.6
**Pack Mode (Normal, Titan, Kappa):**
Mythic
**Singleplayer, Multiplayer, or LAN?:**
Does not matter, it happens all the time
**Description:**
Screen constantly flickers with extremely white flashes, player is rotate around in random directions (yes). It worked before I switched to mythic
![image](https://user-images.githubusercontent.com/10367624/151221576-d6b904c2-8e79-4df6-bdde-42e3ce1210cf.png)
![image](https://user-images.githubusercontent.com/10367624/151221741-b093d18f-0127-4690-87bf-7cffed9c55bd.png)

**Steps to reproduce:**
join a mythic server but without mythics enabled on the client.
Then enable mythics while connected and restart client.

**Comment by Cazadorsniper** [comment]
Are you or the server using Taylor's algorithm in BetterFPS?
