### ISSUE TITLE
Issue: Market block npc server crash bug

### ISSUE THREAD

**Issue by PicklePirate** [Cazadorsniper/PO3#1622]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
3.4.6

**Pack Mode (Normal, Titan, Kappa):** 
Normal

**Singleplayer, Multiplayer, or LAN?:** 
Multiplayer

**Description:**
When using a golden lasso on a market block npc from farming for blockheads mod you can capture said npc. if you then go to far from location and try to place him he digs up from the ground and then the server crashes. I had this running on a server box i have through ovh and this actually crashed the entire box twice.

**Steps to reproduce:**
place the market block from farming for blockheads. 
use golden lasso on the npc.
break and replace the market block.
try to place the npc in another location.
server hangs from that point forward.

**Crash log (use pastebin or issue will be closed):**
Theres actually no crashlog as it crashed my server box so none was generated.

**Comment by Cazadorsniper** [comment]
All I say is don't do that.

**Comment by PicklePirate** [comment]
Haha that's cool. Just wanted to report it. I've since deleted the lassos containing them lol
