### ISSUE TITLE
Cant join a server from a friend 

### ISSUE THREAD

**Issue by A009i8** [Cazadorsniper/PO3#1623]
PO3-3.4.6
Normal
Multyplayer

hey 
i just want to join a friend server and i get this error what can i go ?

https://pste.ch/katomemeko.rb

thx for help

**Comment by Cazadorsniper** [comment]
IIRC this error comes up when the server and client files don't match up so make sure to ask friend what version of the pack they are using so you can install that same version.

**Comment by A009i8** [comment]
hm okey

**Comment by A009i8** [comment]
> IIRC this error comes up when the server and client files don't match up so make sure to ask friend what version of the pack they are using so you can install that same version.

its the same version so idk what shoud i do ?

**Comment by Cazadorsniper** [comment]
Try asking friend for a copy of the server config and mods folder then replace your config and mods folder with the copy.

**Comment by A009i8** [comment]
I fixed it I just needed to downloaded the Server mod file

Cazadorsniper ***@***.***> schrieb am Fr., 11. Feb. 2022,
18:45:
