### ISSUE TITLE
Main world crash

### ISSUE THREAD

**Issue by FantasmalDeathray** [Cazadorsniper/PO3#1625]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.4.6
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: When I entered my main world (garden of glass), the game crashed at the loading stage with the source code -1.

Steps to reproduce: I realized that the problem is in the region folder file: r.2.-2.mca, because if I remove it, then the world does not crash when loading, but chunks with my entire base are stored in this file

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/JZTSZxkC

**Comment by FantasmalDeathray** [comment]
![chrome_1rkKBwAoji](https://user-images.githubusercontent.com/99640561/153936728-f96bc3c9-70e7-4072-ad9f-9778268c8a5e.png)

**Comment by Cazadorsniper** [comment]
In the forge config, turn on the 2 options to remove erroring entities and tileentities.

**Comment by FantasmalDeathray** [comment]
> In the forge config, turn on the 2 options to remove erroring entities and tileentities.

I set this options to true, but world crashed in the same way. I can rebuild my base by memory (i play only 70 days), but i cant be sure that crash won`t happen in the future.

**Comment by Cazadorsniper** [comment]
Sadly, I don't know what causes that crash.
