### ISSUE TITLE
Project Ozone 3 Server RAM ballooning

### ISSUE THREAD

**Issue by Lexden12** [Cazadorsniper/PO3#1626]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.4.6**
**Pack Mode (Normal, Titan, Kappa): Normal**
**Singleplayer, Multiplayer, or LAN?: Multiplayer (2 players)**

**Description: When playing PO3 skyblock in the late-game (currently working on chaos planks) the server's RAM usage balloons endlessly. I set a max of 16GiB of RAM usage for it and it is hitting over 25GB of RAM used and then crashes due to running out of heap space.**
![image](https://user-images.githubusercontent.com/24421791/153844492-38d13e65-846f-400b-8953-ebdbd9a470d6.png)

**Steps to reproduce: Not entirely sure. I copied an old world to a new version of the modpack and am running it on my Linuxbox. If you have questions, I will do my best to provide answers.**

**Crash log (use pastebin or issue will be closed): https://pastebin.com/iA3suiSk**

**Comment by Cazadorsniper** [comment]
remove this: Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 2555476
	Entity Name: item.item.egg
	Entity's Exact location: 509.00, 74.96, -156.00
	Entity's Block location: World: (509,74,-156), Chunk: (at 13,4,4 in 31,-10; contains blocks 496,0,-160 to 511,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)

Looks like its trying to go through the twilight portal.

**Comment by Lexden12** [comment]
Thank you for the quick reply! That's interesting haha, I will try that and I should hopefully be able to update you tomorrow!

**Comment by Lexden12** [comment]
I killed the egg there and found a chicken standing right on the edge of our twilight portal, so I took care of that as well. It might have helped a bit, but the memory usage started to balloon again after some time. I cleared out the eggs again and restarted the server, but I'm afraid it might still just be a matter of time.

**Comment by Cazadorsniper** [comment]
Do you have any farms or automation going on? Items could be spilling all over in some area.

**Comment by Lexden12** [comment]
Hmm, we do have automated farms, but they are auto-harvested. When I killed all items, it only grabbed some lootbags, feathers, and eggs. The server has been running for over a day now. While the RAM usage has been between 18-23GB most of the time, it has been stable at least.
