### ISSUE TITLE
Project Ozone 3 server setup issues

### ISSUE THREAD

**Issue by AutoTTV** [Cazadorsniper/PO3#1635]
# Use the search function before reporting to see if the issue has been reported before.
**3.4.6**
**Pack Mode (Normal, Titan, Kappa):**
**Multiplayer**

**Description: When I download the server files off forge and attempt to creat a server with them it drops a spew of java on the screen and says error**

**Attempting to setup the server**

**Crash log (use pastebin or issue will be closed):**https://pastebin.com/raw/xns0i0Sd

**Comment by Cazadorsniper** [comment]
You need to edit the server bat file to point to a specific java version (must be Java 8)

**Comment by AutoTTV** [comment]
Thx so much. This seems to have worked :D

**Comment by RexMan04** [comment]
Just a note for anyone else looking at this in the future, you can also copy the java8 .exe file and paste it into the root of the server folder.
