### ISSUE TITLE
List of Sugesstions

### ISSUE THREAD

**Issue by Irgendwer01** [Cazadorsniper/PO3#1639]
Here are some Suggestions that may would help the pack and further improve it's stability:

- Add PackagedAuto and PackagedExCrafting to fully allow autocrafting of the Extended Crafting tables https://www.curseforge.com/minecraft/mc-mods/packagedauto https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting
- Replace the original Extended Crafting through the fork Extended Crafting: Nomifactory Edition, it's an continued fork that is still supported https://www.curseforge.com/minecraft/mc-mods/extended-crafting-nomifactory-edition
- Replace the original Applied Energistics 2 through the fork AE2 Unofficial Extended life, it's an continued fork that is still supported and has some bugs fixed https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life
- Replace the original Extra Cells 2 through the fork AE Additions, it's an continued fork that is still supported and has some bugs fixed https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork

**Comment by RexMan04** [comment]
Agreed, I would love to see some of these features added.

**Comment by Cazadorsniper** [comment]
Removing Extra cells broke recipes

**Comment by Cazadorsniper** [comment]
Fixed it, but not adding PackagedAuto.
