### ISSUE TITLE
Creative chest through chance cube

### ISSUE THREAD

**Issue by Ninehills42** [Cazadorsniper/PO3#1640]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
3.4.6
**Pack Mode (Normal, Titan, Kappa):**
Mythic
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
I opened a chance cube in the dreadlands, it asked for heads or tails. I picked heads, I was correct. My reward was a creative chest. Creative items should really not be in the list of item rewards. Especially not creative chest.
**Steps to reproduce:**
Open chance cube -> Get lucky
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
nice

**Comment by RexMan04** [comment]
nice
