### ISSUE TITLE
imaginary time block turns farmland into dirt

### ISSUE THREAD

**Issue by NoobPLazz** [Cazadorsniper/PO3#1643]
**Pack Mode (Normal, Titan, Kappa):**
**Singleplayer, Multiplayer, or LAN?:singleplayer

**Description: so im trying to farm agricraft eccense but it turns the farmland into dirt almost imediatly how to i fix that?

**Steps to reproduce:just use it

**Comment by Cazadorsniper** [comment]
add water near by or place the ITB last.
