### ISSUE TITLE
Forge Download not working

### ISSUE THREAD

**Issue by Indo2002** [Cazadorsniper/PO3#1649]
# Forge kicks an error when downloading.
**Pack Version: PO3-3.4.6**
**Pack Mode (Normal, Titan, Kappa): N/A**
**Singleplayer, Multiplayer, or LAN?: N/A**

**Description: When i try to download it on curse forge i get the error "missing dependency: 2707353

**Steps to reproduce: Just trying to download on curse forge**

**Crash log (use pastebin or issue will be closed):**
![curse error](https://user-images.githubusercontent.com/105451252/168133056-ff1271f9-622d-4d90-85be-a0412506d8af.png)
**

**Comment by Cazadorsniper** [comment]
That is all on Curseforge, there is nothing I can do. Keep trying to install until it works is all I can say.
