### ISSUE TITLE
different craft for the same thing in two different machines

### ISSUE THREAD

**Issue by HellFire0521** [Cazadorsniper/PO3#1651]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.4.7**
**Pack Mode (Normal, Titan, Kappa): Titan**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: The craft for the empowered emeradic crystal block and the empowered diamatine crystal block are not the same in the empowerer and the mechanical empowerer**

**Steps to reproduce: JEI shows the recipes.**
![1](https://user-images.githubusercontent.com/84965974/169002293-f1d3278e-19fc-4e19-82ee-062b8bd6cbf1.png)
![2](https://user-images.githubusercontent.com/84965974/169002297-6ac417d9-2e1a-4bd4-b57e-aaf8d0b87bcb.png)
![3](https://user-images.githubusercontent.com/84965974/169002300-ffdabfe4-86f2-4632-aadf-640d18b1ace5.png)
![4](https://user-images.githubusercontent.com/84965974/169002303-1ba17958-6887-4203-b891-52b250d7cfc6.png)

**Comment by Cazadorsniper** [comment]
Mechanical empowerer recipes are all the same throughout every mode, so for normal and titan stick with the empowerer recipes not the mechanical empowerer.
