### ISSUE TITLE
crash in 3.4.7 version

### ISSUE THREAD

**Issue by wedego943** [Cazadorsniper/PO3#1653]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.4.7
**Pack Mode (Normal, Titan, Kappa):**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
When I place the amber preservation block of erebus mod in erebus dimension, the game crash
**Steps to reproduce:**
place the amber preservation block of erebus mod in erebus dimension
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Yeah it sometimes crashes and it sometimes doesn't. IDK the cause.
