### ISSUE TITLE
graphic and audio lag upon entering world

### ISSUE THREAD

**Issue by HarryNiu** [Cazadorsniper/PO3#1654]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*3.4.6*
**Pack Mode (Normal, Titan, Kappa):**Normal
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**

I can load up the modpack properly, but whenever I enter a world (either from creating a new one or entering a existing one), my graphic will freeze and I won't be able to move anything. Just to be clear, I am not complaining about low FPS, the graphic freezes and the game simply don't register any of my input, including but not limited to mouse movement, direction key, and the esc key. I have tried other modpacks before, such as PO2, RLcraft, and Sky Factor 4, none of them has this issue. 

As far as I can tell, this is not a hardware issue. The game uses only 7GB of ram while I assigned it 8GB, the cpu usage stays at around 25-30% with no other background program. Changing the graphic setting does not help either, I tried both fast and fancy setting and got the same result. 

One more thing that might worth mention. When I first load up the modpack, the game says it is missing OMLib, so I had to install it manually, not sure if this contributes to anything. 

**Steps to reproduce:** I simply load up the modpack and create/enter a world, no idea what else contributes to it. 

**Crash log (use pastebin or issue will be closed):** No Crash Log aviable, the game don't crush, I just have to stop it manually. I can try to get one if it is required.

**Comment by Cazadorsniper** [comment]
Have you tried reinstalling?

**Comment by HarryNiu** [comment]
Sorry for the late reply. Yes I did try reinstalling, a couple times actually, and I tried it on different launcher, including PCL2, official curseforge app, and MultiMC, they all have the same issue

**Comment by Cazadorsniper** [comment]
Can you get the latest log from the logs folder?

**Comment by HarryNiu** [comment]
OK, I hate to be this guy, but the bug is fixed now, the game runs smoothly now. I don't know how I did it, but I had to reinstall some driver on my laptop as an attempt to solve some unrelated issue, which may have accidently fixed the bug. So, sorry for the false (sort of) alarm, and thank you for your patience and time. I'll close this now.
