### ISSUE TITLE
Resolving Mod Ids

### ISSUE THREAD

**Issue by coolside** [Cazadorsniper/PO3#1656]
3.4.8

Downloading from Curseforge Single Player and getting Resolving Mod IDs error while installing into MultiMC which I have never had issues with.

**Comment by Cazadorsniper** [comment]
Have you tried the Curse Forge Launcher?

**Comment by coolside** [comment]
Somehow I knew you were going to ask that.  I actually don't like
Curseforge.  Oh well.

Thanks for the response though!

**Comment by jbredwards** [comment]
I was having this problem until I updated mmc. When I did this the error changed to `Archive does not contain a recognized modpack type`, not sure how useful this is, thought it was worth mentioning though.

**Comment by wildkurt** [comment]
I ended up downloading the forge mod loader and copied the new update zip file to a new Minecraft 1.12.2 instance. Then I downloaded all the mods from Curseforge and put them in the mod folder. It worked perfectly.
