### ISSUE TITLE
Aluminium crystall seed basic crafting recepie crashes minecraft

### ISSUE THREAD

**Issue by goldengun111** [Cazadorsniper/PO3#1660]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.4.8 
**Pack Mode (Normal, Titan, Kappa): Kappa
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description:Trying to craft the aluminium crystal seed from embers rekindled in the tier 1 basic crafter from Extended crafting: Nomifactory edition crashes minecraft everytime

**Steps to reproduce:
Get a tier 1 basic crafter 
Put the [recepie](https://imgur.com/un7D0mz) added by craftweaker in it as shown in jei
Try to take the aluminium crystal seed out and you game [crashes](https://imgur.com/t8tjB7I)
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/q3eK32Y5

**Comment by goldengun111** [comment]
Fixed it. It just required taking the .reuse off of the aspectuses from the kappa_3x3.zs file 

This is the code that fixed the crashing
`//aluminum seed
mods.extendedcrafting.TableCrafting.addShaped(1, <embers:seed_aluminum>, [[<ore:ingotDesh>, <ore:ingotAlumite>, <ore:ingotDesh>], [<ore:dustAsh>, <ore:gemQuartz>, <embers:crystal_ember>], [<embers:aspectus_iron>, <embers:aspectus_silver>, <embers:aspectus_copper>]]);`

**Comment by Cazadorsniper** [comment]
If possible can you check the chaos catalyst recipe as well? That recipe also uses the .reuse transformer.

**Comment by goldengun111** [comment]
Had to test it in a creative world as i dont have access to some of the stuff on my main, but it seems to not crash when doing the chaos catalys [recepie](https://imgur.com/ySMxDoN) with [these items](https://imgur.com/UyGz3s9)being left behind. i dont know why the ethaxium while the body stone dissapears so you probably swapped around the .reuse on the 2 items

**Comment by Cazadorsniper** [comment]
yeah this is weird
