### ISSUE TITLE
PO3 Freezes on Finishing up: 6/7 when it hits Crafttweaker2

### ISSUE THREAD

**Issue by FidelsCashflow** [Cazadorsniper/PO3#1662]
**Pack Version:**
3.4.8
**Pack Mode (Normal, Titan, Kappa):**
Mythic
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
When i start up the modpack, it loads just fine until it hits Finishing up: 6/7 and then when it hits crafttweaker2 it just completely freezes, it doesn't crash the launcher like i've seen other mods do so in other packs in the past but rather just stops there. I have tried to reinstall the pack, change versions, and reinstall the mod itself, but none of those have worked. I tried looking it up to see if its client side and i cant really seem to find anything, maybe im not looking hard enough idk. This just started happening out of nowhere i haven't changed anything to curse or the modpack itself prior to this. 
**Steps to reproduce:**
Just starting up the pack from the curseforge launcher

**Crash log (use pastebin or issue will be closed):**
There is no crash log because it doesn't crash, however idk if this will help but heres my crafttweaker log 
https://pastebin.com/mHQnv5n1

**Comment by Cazadorsniper** [comment]
I need the latest.log from the logs folder.

**Comment by FidelsCashflow** [comment]
I had to split it up into multiple parts 
https://pastebin.com/turPFYaa 
https://pastebin.com/6Z4U1Hn4 
https://pastebin.com/9b5t7jHk

**Comment by Cazadorsniper** [comment]
Lower the amount of ram you allocated to minecraft and try removing the waiting time mod to see if that helps..

**Comment by FidelsCashflow** [comment]
Yup that worked just fine, i cant believe it was something as simple as that, thank you for your time and help Cazador
