### ISSUE TITLE
Server lagging/tick delay

### ISSUE THREAD

**Issue by djfaplas** [Cazadorsniper/PO3#1669]
Hi, i hope i can get some help since i have been searching for 3 days through the wide web, and tried different things and came up with nothing

My problem is that i have hosted a Project Ozone 3 server taken from curseforge version 3.4.8, the server started up fine and all, but we have this kind of lagg og delay, we are not lagging by connection, since its green with all bars full

i've tried what feels like endless tricks without luck

Java version is: jdk1.8.0_202

Start.bat look simple as this: 

"C:\Program Files\Java\jdk1.8.0_202\bin\java" -Xms6G -Xmx6G -jar forge-1.12.2-14.23.5.2860.jar -nogui
pause

Server spec:
Ryzen 7 3700x
64 Gigs DDR4 ram (8 given to MC ATM) i tried to give it 16 at first, then 12, 8, and now 6, since i got told that giving too much ram can sometimes cause issues
1TB M.2 NVMe
1 Gig up/down

To try to explain the issue further i have attached a vid to kind of show you what i mean with lagging/delay, and it has been consistent no matter what we do, its driving me insane as im trying to show my friend the pack, since i love it.

Link: https://www.youtube.com/watch?v=fidu5Lh20M4

**Comment by Cazadorsniper** [comment]
That looks like TPS lag, whatever you're doing in the world is causing that to happen. 
ex: item entities being spilled all over the ground because some storage might have gotten full.
Try turning off some farms to see if that does the trick.

**Comment by djfaplas** [comment]
Problem is that, its been doing it since day 1, the only real farm we have are 3x3 area of single harvester, a mobfarm but nothing spills there, so i just cant figure it out

I forgot to say we also tried 3 different maps, normal, skylands and a skyblock, All the same delay, its like it is locked by some setting

**Comment by Cazadorsniper** [comment]
Try switching from a JDK to a JRE.

**Comment by djfaplas** [comment]
Still does it.. im now running jre1.8.0_202 - Could it be the JRE version ?

I have now looked around the map, and we got this around:

6 bonsai (Doesnt spill anything)
1 plant gathere (stops if chests are full)
mob farm - nothing spills, everything we dont have a drawer for gets thrown in trash can
Some solar panels

Server console stats: 1 Gig is in use and 85% free, avg tick:  https://gyazo.com/a8f16a42a268d242a300f83e24c99832

**Comment by Cazadorsniper** [comment]
Try updating the modpack once the server files are up.

**Comment by djfaplas** [comment]
your doing an update today, and will i be able to download it via curseforge ?

**Comment by Cazadorsniper** [comment]
yes

**Comment by djfaplas** [comment]
I will post when i get to try the new version

**Comment by djfaplas** [comment]
yay, seems to be working so far :D

Just curious, but can you tell me what it was ?

**Comment by Cazadorsniper** [comment]
I have no idea, maybe something corrupted when you downloaded the server files from curseforge. Curse has been acting weird lately.

**Comment by djfaplas** [comment]
If its okay by you, i will keep this open for today incase something happens later when my friend get on, tomorrow i will close it

**Comment by RealKomander** [comment]
Have completely the same issue (and my specs are LITERALLY the same as yours, what a coincidence!). The weirdest thing is that the server uses exactly 1 gb of RAM, even thought I allocated 10 times more
