### ISSUE TITLE
wither bones and drop og evil removed/disabled?

### ISSUE THREAD

**Issue by djfaplas** [Cazadorsniper/PO3#1671]
**Pack Version:** 3.4.9

**Pack Mode (Normal, Titan, Kappa):** Normal

**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** 
1. I cant seem to get the wither bones for the heart canisters, i have been killing wither skeletons for about 4-5 days, and normally i would have alot of those, but doesnt have anything, not even the wither dust for crafting do i have

2. Drop of evil doesnt seem to be dropped either, as said above i have been killing those for 4-5 days, got spawners for them but still got nothing.

I have one drawer filled with 84x64 stacks of wither skull fragment, so i've been killing them alot

Can i somehow re enable it somehow?

**Comment by djfaplas** [comment]
Bump, cant get any further with some quests because of it

**Comment by Cazadorsniper** [comment]
Wither bones and drop of evil are not disabled.

**Comment by Cazadorsniper** [comment]
You could try turning normal skeletons into wither skeletons with witch water to see if that works.

**Comment by djfaplas** [comment]
Will try that and post results later

**Comment by djfaplas** [comment]
I have now been killing them for about 20 mins, got 3 diamond chests full of drops from only them, and still got no wither bones, nor dust or drop of evil, they have been converted from normale skeletons to withers and still nothing, been killing the wither boss too, but didnt get anything there too, killed it about 15 times

**Comment by Cazadorsniper** [comment]
If you can try with epeolatry its looting is through the roof.

**Comment by djfaplas** [comment]
i've been killing with epeolatry for about 15 mins now, got 4 diamond chests filled and still nothing

**Comment by Cazadorsniper** [comment]
Ok the Heart canisters should use any wither/necrotic bone and I literally just killed 1 wither skeleton and it dropped a drop of evil.

**Comment by djfaplas** [comment]
Ok, so i tried to make a singleplayer, and you were right, within 8 kills i got 2 kinds of wither bones and the necrotic bone + drop og evil, so it seems somehow something is missing on the server files..

Would i be able to download the server files again and the just copy the "World" folder right over and replace ?

**Comment by djfaplas** [comment]
I tried on the server again, and it didnt work, not even when i used spawn egg, i then tried to make a new download and server and that worked, but when i then copied my old world over, it then stopped again and didnt give me any, can it be somewhere in the world files ?

I have downloaded a skyblock and then used that as the world, i havent had any problems before

**Comment by Cazadorsniper** [comment]
If you used a random downloaded Skyblock map then yeah that might have caused the issue.

**Comment by djfaplas** [comment]
dammit.. dont wanna build all that shit again..

**Comment by djfaplas** [comment]
Thanks for helping anyways.. i might just spawn those 2 items in when needed, need to talk to my mate about restarting the whole game

**Comment by djfaplas** [comment]
No, i have tried different things, diamond spikes, gold spikes, mob masher, and awakened draconium sword, nothing gave me those items

Hent Outlook til Android<https://aka.ms/AAb9ysg>
________________________________
