### ISSUE TITLE
Fiinishup 6/7  Craftweaker2 15/291 for more than 30 minutes. 

### ISSUE THREAD

**Issue by PanameFR** [Cazadorsniper/PO3#1672]
Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.4.9
Pack Mode (Normal, Titan, Kappa): Normal 
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description:
I can no longer launch the modpack, It remains stuck on  Fiinishup 6/7  Craftweaker2 15/291 for more than 30 minutes. 
A few days ago it started very well. I run it with 10G of ram as per usual. I even deleted the instance to redownload it but no change.
It remains stuck at the same stage. 

Crash log (use pastebin or issue will be closed):
Logs : https://pastebin.com/7gcZ444m
Craftweaker logs : https://pastebin.com/kxB4BquA

Thanks in advance

**Comment by Cazadorsniper** [comment]
Try disabling the WaitingTime mod.

**Comment by Cazadorsniper** [comment]
Have you tried reinstalling the pack?

**Comment by PanameFR** [comment]
Thank you for being quick, I reinstalled everything.
I will try to start again in the evening.

**Comment by PanameFR** [comment]
After reinstalling java everything is better no more worries.
Thanks for your help though, and good luck for the future.
