### ISSUE TITLE
Outdated Erebus Version

### ISSUE THREAD

**Issue by PrimeroBestia** [Cazadorsniper/PO3#168]
**Pack Version:**
3.0.39

**Description:**
The Version of Erebus, Erebus-1.0.27.jar, currently on the pack has a game crashing bug.
Please update the mod it is quite an inconvenience while exploring Erebus

**Steps to reproduce:**
Be near a dung pile, it will definitely crash your  game once it tries to spawn something.

**Crash log <use pastebin or similar>:**
https://pastebin.com/4pUyysD5

**Comment by Cazadorsniper** [comment]
Pack Version 3.0.39 was pulled if you're still using that version then its all on you.
