### ISSUE TITLE
Server Not Starting

### ISSUE THREAD

**Issue by RusticHillBilly** [Cazadorsniper/PO3#1684]
https://pastebin.com/WE1R2k6y

I try to start the server and it says what is in the paste bin. I used a command to directly use java 8 version and have tried multiple different java 8 versions to see if that was the issue. I cant find a solution as the only solution I have seen is to direct the bat file to the java 8 version and it still doesnt work. Thank you

**Comment by RusticHillBilly** [comment]
I also double clicked the normal forge server jar and when it asked what program to use I noticed it was trying to path to java 17 for some reason? it is not even downloaded on my pc anymore and have reinstalled the mod pack and restarted my pc multiple times so that might be causing an issue but I do not know how to fix it.

**Comment by Cazadorsniper** [comment]
try this: "C:\Program Files\Java\jre1.8.0_301\bin\java.exe" -Xmx6144M -Xms1024M -jar forge-1.12.2-14.23.5.2860.jar nogui 
pause

of course replace the JRE1.8.0_301 with whatever java version you're using.

**Comment by RusticHillBilly** [comment]
Alright I will try that right now

**Comment by RusticHillBilly** [comment]
Now it says this...

https://pastebin.com/VMg9LdyQ

**Comment by RusticHillBilly** [comment]
OMG sorry im stupid thank you so much for your help it is working now.
