### ISSUE TITLE
Ender IO Remote Inventory Panel (Tier 1, The 5-chunk ranged one), will crash the client completely on subsequent use

### ISSUE THREAD

**Issue by osirisgothra** [Cazadorsniper/PO3#1687]
# Use the search function before reporting to see if the issue has been reported before.
VERSION 3.4.6
GAME MODE Mythic, Survival
GAME TYPE Multiplayer, Professionally Operated Server Network on Leased Servers

**DESCRIPTION**
Remote Standard (5 chunk ranged) Inventory Panel (Ender IO) will randomly crash, especially after a few usages, even when
close by the remote's target panel under these circumstances (and possibly others?):

**REPRODUCE BY**
- Inventory Panel is connected with data cables that connect to at least 2 different storage drawer controllers
- One of the Storage Drawer Networks is linked to the ME via storage bus (but not both)
- The "void" biome seems to exacerbate this behavior.
- All networks are within two chunks, but are also force loaded by the server
- This is a multiplayer server
- Reproduce on skyblock island
- This NEVER happens the first time I use the remote, only after subsequent uses, UNLESS optfine is not in use, 
then it CAN happen on first use (this was confirmed just recently)

**WORKAROUND**
dont use the remote panel, unless I find some other better way to work around it

  The ME in question is a simple controller-drive-2 ME chests-for storage only system with a few terminals attached
and has no more than 15 channels in total and is powered by big reactors with cryo-stabalized resonant fluxduct to guarantee constant power. 

  Each storage drawer network is within its own same chunk.  They are half cube 7-7-7 width, height of 8, controller and slaves in the middle on the bottom like this
      <-7->
+--CS--+
|            |   7 ^v

  The EIO panels are constantly fed nutrient distillation via the vat which constantly makes it (chest full of wart/skulls). It then outputs to inventory panels via ender tank. the stationary inventory panel is connected to nutrient via that ender tank, but not directly to the tank, I use an ender fluid duct to feed it from the tank, and the panel itself is connected to the other end, and never has problems. 

  The remote is always kept nearly full of nutrient distillation. I keep a reservoir of it in the bauble inventory set on autofeed. I also carry resonant flux capacitors to supply constant power to the panel, so it never loses charge. The panel has a return item duct on it, extracting (no upgrades) to an ender chest that then will infilter items to their appropriate drawer controller(s). 

  There are no entities in this island other than the ocassional pig zombie coming out of   portal, which is allowed/preferred by the server network. That about sums up the situation gameside, the crash report is included below for the rest of the precise details. 
Update: testing without optifine, seems to happen on first use, sometimes. But after the previous day, it was always happening
on first use for some reason, the last crash log is from that test run, still on multiplayer, po3m, etc. just no optifine.

**CRASH LOGS FROM PASTEBIN**
https://pastebin.com/L4XY0B3N (with optifine version=1.12.2-U G5)
https://pastebin.com/7NtQTxw8 (with NO optifine)

**DIAMETRICS**
Normally Not using TexFix, but nothing changes if I do use TexFix
Tested also while Optifine in Use, But Also Happens Without

**Comment by Cazadorsniper** [comment]
There is nothing I can do about this, updating Ender IO will break other mods. I can only suggest not using the inventory panel.

**Comment by osirisgothra** [comment]
ok i just updated that---and this information will at the least allow other players an answer or at the very least know that they are experiencing something and can work around it by not using the remote. If i come upon a workaround I'll post it somewhere.
