### ISSUE TITLE
Crash after opening the AE2 ME Crafting Terminal

### ISSUE THREAD

**Issue by calvissuperman** [Cazadorsniper/PO3#1696]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.4.10
**Pack Mode (Normal, Titan, Kappa, Mythic):** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer, and LAN

**Description:**
Crash to desktop after clicking anywhere in the ME crafting terminal from AE2 Unofficial Extended Life mod. Currently there is only a few devices on the network: Crafting terminal, Interface terminal, ME Drive with 3 64k storage cells, 1 export bus, 4 storage bus's (1 connected to crate from Actually Additions, other 3 connected to Drawer controller from Storage Drawers), energy accepter, 4 advanced inscribers, 1 crystal growth chamber. No main controller, so it's a simple system for storage and inventory management only right now.

**Steps to reproduce:**
Open the ME Crafting Terminal that is connected to an Applied Energistics network, after 5 or so seconds the game will crash. Checked other devices and objects in the world, and so far that's the only one. Everything else works, until I try to open that terminal.

[Youtube video](https://youtu.be/F6DehdmNEDQ) (sorry about the quality)

**Crash log (use pastebin or issue will be closed):**
[pastebin](https://pastebin.com/84EqcxFW)

**Comment by calvissuperman** [comment]
Somewhat solved: I noticed in the error report it mentioned pneumaticraft and custom durability bars. So I was looking in the network for something that fit that description, and didn't find anything so I just kept playing.

In my main inventory though, I had a stack of pneumaticraft PCB's that haven't been UV blasted yet, so they have empty durability bars. I removed these from my inventory, and viola, no more crashes upon opening the ME crafting terminal.

Still an issue, but now easily avoidable. Hope this is an easy solution

**Comment by JohnCOswald** [comment]
I have the same exact issue but I don't have anything related to pneumaticraft in my inventory or in the system
I don't know if I should open an issue myself because it would seem a bit redundant

**Comment by restics** [comment]
Same issue here, have nothing related to pneumaticraft

**Comment by Cazadorsniper** [comment]
This crash happens from the 53 AE2 update, downgrading to 52 solves it.

**Comment by calvissuperman** [comment]
> I have the same exact issue but I don't have anything related to pneumaticraft in my inventory or in the system I don't know if I should open an issue myself because it would seem a bit redundant



> Same issue here, have nothing related to pneumaticraft

Send your logs through pastebin and I might be able to help you find the item thats causing the issue. If not, get the downgraded AE2 file [here](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/download/3925410) Working for me with no problems so far
