### ISSUE TITLE
Quantum Entangloporter quest not completing

### ISSUE THREAD

**Issue by Sreolla** [Cazadorsniper/PO3#17]
Description: Crafted the Quantum Entangloporter and quest is Not completing

Steps to reproduce: Craft Quantum Entangloporter

https://puu.sh/CRCt1.png
https://puu.sh/CRCso.png

**Comment by devi4nt** [comment]
Think this is a known issue, and potentially already fixed :)

See https://github.com/Cazadorsniper/PO3/issues/1

**Comment by Sreolla** [comment]
Ah thank you, missed it at the bottom
