### ISSUE TITLE
Crash when using YABBA barrel with AE

### ISSUE THREAD

**Issue by ADKaster** [Cazadorsniper/PO3#170]
**Pack Version:**
3.0.38
**Description:**
Server keeps getting killed by the watchdog, trace mentions AE and YABBA barrels in the main run thread.

Seems destroying the ME controller with the barrels attached via storage bus makes it not crash. Changing the JVM back to OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12) let us destroy the ME system and not crash the server, but re-enabling that system still brings the server down to 0.7 tps.
**Steps to reproduce:**
I saw on reddit that using the OpenJ9 JVM from eclipse might increase performance, this crash started happening after switching to it.
**Crash log <use pastebin or similar>:**
https://pastebin.com/qwmacWim

**Comment by Cazadorsniper** [comment]
Have you tried removing the OpenJ9 JVM? Have you tried turning off the watchdog by turning the max-tick-time to -1?
