### ISSUE TITLE
Server crashing on open

### ISSUE THREAD

**Issue by daggontale** [Cazadorsniper/PO3#1703]
**Pack Version: 3.4.10**
**Pack Mode (Normal, Titan, Kappa, Mythic): Normal**
**Singleplayer, Multiplayer, or LAN?: Multiplayer**

**Description: Server crashes on startup, was previously working**

**Steps to reproduce: launch the server**

**Crash log (use pastebin or issue will be closed):https://pastebin.com/JPpvP2Wr**

**Comment by Cazadorsniper** [comment]
Go into the forge.cfg in the server and turn on the config that removes erroring tileentities.

**Comment by daggontale** [comment]
Same problem... 

updated crash report: https://pastebin.com/4dGc9kqF

**Comment by Cazadorsniper** [comment]
There is an item translocator causing the crash at (5126,42,9) you could try world edit or something to try and remove it.

**Comment by daggontale** [comment]
I was that those were the issue, I tried to use one but I couldn't find one that didn't say the compact machines dims were entirely empty :/ any suggestions for world editors? I've tried amulet and mcedit and neither worked

**Comment by Cazadorsniper** [comment]
https://www.curseforge.com/minecraft/mc-mods/worldedit

**Comment by daggontale** [comment]
Am I dumb, how do I use it if I cannot load the world?

**Comment by Cazadorsniper** [comment]
You can try loading the world on the client and doing the first solution i gave (forge.cfg) then copy/pasting the world onto the server.
