### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by RAM-CIEL** [Cazadorsniper/PO3#1706]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:1.12.2
**Pack Mode (Normal, Titan, Kappa, Mythic):Normal
**Singleplayer, Multiplayer, or LAN?:SinglePlayer

**Description: the quest do not complet

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Dino296** [comment]
> # Use the search function before reporting to see if the issue has been reported before.
> **Pack Version:1.12.2 **Pack Mode (Normal, Titan, Kappa, Mythic):Normal **Singleplayer, Multiplayer, or LAN?:SinglePlayer
> 
> **Description: the quest do not complet
> 
> **Steps to reproduce:**
> 
> **Crash log (use pastebin or issue will be closed):**
