### ISSUE TITLE
Quests in Rho page

### ISSUE THREAD

**Issue by Keycz1** [Cazadorsniper/PO3#1707]
Pack Version 3.4.10
Pack Mode Mythic
Singleplayer

Description:
In the Rho page (AE2 page), there are 16 quests that cannot be completed (without cheats) ----> and that's why I can't finish the Omega page

16 quests, that cannot be completed ----> ![2022-11-03_22 07 11](https://user-images.githubusercontent.com/67666580/199835944-4b6a1c19-c18e-493e-bd27-01f2947680ea.png)
Omega page ----> ![2022-11-03_22 15 43](https://user-images.githubusercontent.com/67666580/199835947-ed44f9c9-2b39-4fae-85b8-042d82454ebb.png)

**Comment by Cazadorsniper** [comment]
Have you tried /bq_admin default load?

**Comment by Keycz1** [comment]
Oh, yeah. That worked. Thanks a lot
