### ISSUE TITLE
World crashing after loading in

### ISSUE THREAD

**Issue by xoxoalone** [Cazadorsniper/PO3#1708]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.4.10
**Pack Mode (Normal, Titan, Kappa, Mythic):** Mythic
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Hard crashing while loading into world. Lets me walk around for about 3 seconds then just closes the game. I've tried upping my RAM to 20G. I believe my world is somehow corrupt and something I did made the game mad. I'm too stupid to understand crash reports, so some help would be appreciate
**Steps to reproduce:**
Starting the world.
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/mhUrKM5F

**Comment by Cazadorsniper** [comment]
Remove the farming station at (127,122,-611).

**Comment by xoxoalone** [comment]
thank you, should I try mc edit for it? or what program?

**Comment by xoxoalone** [comment]
update: I was able to remove it! You da man! Is it something that I did or is it a known bug with the farming station?

**Comment by Cazadorsniper** [comment]
likely a bug in the farming station but i can't update Ender IO or it will mess with things.
