### ISSUE TITLE
Client crashing ae2 unofficial extended life

### ISSUE THREAD

**Issue by shadins** [Cazadorsniper/PO3#1712]
I have been getting several client crashes over the last couple of hours. I use a client mod to keep the game up instead of fully closing and having to reload for like 5 mins,,, the mod is called VanillaFix-1.0.10-150. it will give me an error on what might have caused the crash I will get either "Unknown" or "AE2 unofficial Extended life, PneumaticCraft: Repressurized".  Both me and my friend have been dealing with this after finally trying to get into our server from the client crashing issues with extra Planets. Found on Discord to use the FTB launcher over Curse, which worked for us. However, we have been plagued with this new crash.

here is the latest crash report I'm getting.

I am unsure on what causes this issue and can not say how to replicate it. the crashes always happen when interacting with JEU or something within the inventory of AE2
[crash-2022-11-09_20.59.24-client.txt](https://github.com/Cazadorsniper/PO3/files/9978017/crash-2022-11-09_20.59.24-client.txt)

**Comment by shadins** [comment]
Also not sure how this happened but I'm assuming this is related
![image](https://user-images.githubusercontent.com/33010981/201019387-6da2eb6d-7109-471d-a97e-302638ea62bd.png)

**Comment by ShaneproGithub** [comment]
Having the same issue. Would be nice to see if someone has a temporary fix (that isn't just not using AE2).
