### ISSUE TITLE
Waterwheel recipe is wrong

### ISSUE THREAD

**Issue by 72Zorad** [Cazadorsniper/PO3#1715]
The basic ex nihilo waterwheel recipe isn't there.  The only water wheel recipe uses immersive engineering pieces which are infused.  Infusing seems well beyond the alpha quest page where the water wheel is created as part of the simple ex nihilo automated sifting.
Downloaded PO3 from curseforge.  Version 3.4.10

Mark

**Comment by Cazadorsniper** [comment]
Is this on a multiplayer server or singleplayer? What mode are you on?

**Comment by 72Zorad** [comment]
Single player. Not sure of the “mod”. Not sure what that means. It is Java, downloaded from curseforge and the version I indicated. Happy to provide the mod if you can tell me what that means. 

Mark

**Comment by Cazadorsniper** [comment]
I'm going to assume you're on normal mode then. If you're using the Curseforge launcher then just reinstall the pack, if not then I recommend installing the Curseforge launcher.

**Comment by 72Zorad** [comment]
Oh, sorry.  I misread that and thought you were asking the mod.  Mode is
kappa although I was a bit surprised that it's not the "skyblock" like I've
seen on other peoples' playlists.  It started in a forest biome with lots
of killer mobs, even the chickens...
To be honest I'm not sure it's the pack.  I've had issues with the hoops
you have to jump through ever since Microsoft bought them.

**Comment by Cazadorsniper** [comment]
Need to set the world type to Garden of Glass to get skyblock.
