### ISSUE TITLE
Mobs are laggy, everything else is fine

### ISSUE THREAD

**Issue by mothmaildelivery** [Cazadorsniper/PO3#1717]
Pack Version: 3.4.10
Pack Mode: Normal
Self-hosted dedicated multiplayer server:
10GB Ram (I could give it another 10-15 GB if needed)
Ryzen 5
Two players

Mobs are the only thing lagging on my server. From server start, we used cobblestone to build a path to a slime island and only a handful of skeletons spawned on the bridge and they lagged (jumped around, players couldn't register hits or see hits on themselves). We continued to progress and our machinery, items dropped on the floor, player movement are NOT lagging. We made a simple mob spawner with a small cobblestone room and only the darkness to spawn the mobs. There will only be about 5 enemy mobs and they will all lag. **It appears to be ONLY mobs that are lagging.**

Any guidance on what could be the cause?

Output of /forge tps **away from mobs**
Overworld
- Mean is 1.939 ms
- Mean TPS: 20
Overall:
- Mean tick time 2.404 ms
- Mean TPS: 20

Output of /forge tps **BY mobs, 5 zombies**
Overworld
- Mean is 2.404 ms
- Mean TPS: 20
Overall:
- Mean tick time 13.356 ms
- Mean TPS: 20

Any and all help is much appreciated. Thanks

**Comment by Cazadorsniper** [comment]
Is this still happening?

**Comment by superhealing** [comment]
> Is this still happening?

Less obviously, but i found memory leak 
https://www.curseforge.com/minecraft/mc-mods/epic-siege-mod
![image](https://user-images.githubusercontent.com/34381388/215822936-23995a65-ece3-48fa-afb8-2c71d392270d.png)

**Comment by Cazadorsniper** [comment]
Then remove Epic Siege Mobs.

**Comment by mothmaildelivery** [comment]
I removed epic siege mobs and the issue still occurred. Unfortunately, we have moved on from the server but the issue persisted the whole time.

________________________________

**Comment by jcity3** [comment]
FYI For anyone else having this issue:
make sure you are running nogui for the server. I had this same issue and the server was not using more than 1.2G of ram despite 24G allocation resulting in laggy mobs.  Seems like there is a bug (probably with 1.12.2 minecraft) where the gui messes with the server ram utilization.

**Comment by Dloksar** [comment]
@mothmaildelivery 
It's a bit late but were you able to fix it?

a single player. 12Gb ram (up to 24gb ram if needed)
I started playing yesterday and I have exactly the same problem.
It doesn't matter if I'm in Overworld, Nether or End... mobs move with lag.
I've already tried removing mods to see if any of them are the cause and can't fix anything.

**Comment by mothmaildelivery** [comment]
Unfortunately, I had already stopped the server by the time I got a response. I would definitely make sure you're doing the nogui thing. I did try it without Epic Siege Mobs but the issue still persisted
