### ISSUE TITLE
Game completely freezes when opening Akashic Tome

### ISSUE THREAD

**Issue by Roflpwnage** [Cazadorsniper/PO3#172]
Made an Akashic Tome, opened said book, got a brief animation of opening the book and than the game just instantly gave up.
Didn't even get a crash file since the game 100% froze rather than crashed, and had to force close. And couldn't find a dump file (or I just don't know where to look, or if there even is one since I forced closed.)

**Comment by Cazadorsniper** [comment]
can you give me the latest.log?

**Comment by netcore10** [comment]
I get this too, but I can't seem to debug this (As to what's causing it) 
with the log file.
[latest.log](https://github.com/Cazadorsniper/PO3/files/6473317/latest.log)

**Comment by Cazadorsniper** [comment]
The log is not from PO3.
