### ISSUE TITLE
John Cena creepers not playing music on multiplayer servers

### ISSUE THREAD

**Issue by InfernoSuperNova** [Cazadorsniper/PO3#1723]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** PO3-3.4.11F

**Pack Mode (Normal, Titan, Kappa, Mythic):** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
The sound that is supposed to play when they explode doesn't seem to play on multiplayer servers, and the sound that plays when they start to detonate seems to play very infrequently, even on singleplayer
**Steps to reproduce:**
Join a multiplayer server
Find a john cena creeper
Reconsider your life choices

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
There is nothing I can do about that, sorry.
