### ISSUE TITLE
laser gun

### ISSUE THREAD

**Issue by Gloyzt** [Cazadorsniper/PO3#1729]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.4.11F
**Pack Mode: kappa
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: i dont have the laser gun in the game cant see it in the forge. i asked other people on reddit if they have the laser gun and they did. but i dont know if it is removed or not cus i cant find it in the mod list. can someone help me?

**Steps to reproduce: open the tool forge

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Ok I found that reddit post and the version of PlusTic the person is talking about doesn't exist in 3.4.11F, it was never added after I had to remove it.
