### ISSUE TITLE
Need help getting into the discord server

### ISSUE THREAD

**Issue by Noremac2k3** [Cazadorsniper/PO3#1751]
I can view but I can't accept the invite to the OG_aristotle discord and I think it's because I'm banned, but I don't know why.
not sure if there is a better place for this.
 But I need help re-starting/updating my old server and I'm sure the answers I need are in the discord somewhere.
 
 my discord: Noremac2k3#6934
 
 if any of the moderators can help me with this, it would be greatly appreciated.

**Comment by Cazadorsniper** [comment]
all you have to do is copy/paste the updated server files into the old ones and change packmode back to what it was before.
