### ISSUE TITLE
Po3 can't start server.

### ISSUE THREAD

**Issue by Knsistaken** [Cazadorsniper/PO3#1754]
I think the mods in server files doesn't match with modpack.  I'm sure that i'm playing 3.4.11F rn and downloaded 3.4.11F server files but server crashed because of "aroma1997sdimension". I tried to delete that mod, server started, but this time i got this crash when tried to login.

Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe produces unregistered item

![Screenshot_1](https://github.com/Cazadorsniper/PO3/assets/58883042/94a53d96-6c29-4994-8f3e-873653489ad2)

**Comment by Cazadorsniper** [comment]
redownload the server files.

**Comment by Cazadorsniper** [comment]
If you haven't redownloaded the server files, I suggest waiting to do that for now because of an ongoing issue on Curseforge (malware was detected).

**Comment by Knsistaken** [comment]
I tried redownload like 10 times, it doesn't work but if there is an issue ofc i can wait . When should i try again? Like just 1-2 days or more?

Thanks for help btw.

**Comment by Cazadorsniper** [comment]
Some corruption might have happened, try deleting the mods config rather than the mod itself and of course delete the world too.

Also i need the entire crash report to really see what happened.

**Comment by Knsistaken** [comment]
I tried to delete config files, but it didn't work as well. I got same crash, here's the link:
https://pastebin.com/8FSxhnPs

**Comment by Cazadorsniper** [comment]
From what I've seen in the crash report this issue is usually solved by deleting the aroma1997 config and/or reinstalling the mods (both aromacore and the dimension).

**Comment by Knsistaken** [comment]
Unfortunately didn't work. I even tried to download other versions. Same crash everytime...

**Comment by Cazadorsniper** [comment]
The Client version works fine right? Try replacing the server configs with the ones from the client (the entire config).

**Comment by Knsistaken** [comment]
didn't work... 😔

**Comment by Cazadorsniper** [comment]
That is weird (also curseforge issue has been solved so its safe to download from there again).
Final thing, is your system using some other language other than English? Try changing it to English.

Setting these JVM arguments might help as well -Duser.country=US -Duser.language=en

**Comment by Knsistaken** [comment]
it worked, tysm!
