### ISSUE TITLE
pack reset inventory/quests after power loss

### ISSUE THREAD

**Issue by dfduarte78** [Cazadorsniper/PO3#1755]
Pack Version: 3.4.11F
Pack Mode (Normal, Titan, Kappa, Mythic): Kappa
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description: I have the multiplayer server and client running on the same PC and after a power loss i got back in the server and my inventory was gone and the quests also reset! The server part seems fine, its the same as before the crash.

I've been playing for just over a week and don't have a backup yet for the client. I tried the world backups but it didn't help, it seems like a client side thing only. Is there something like the automated world backups for the client? I looked around the instances folder but didn't find a way to restore anything. 

Although i have access to the buildings and resources i gathered so far, crafting the items worth maybe 8-10 stacks of RAK all over again would be a huge pain. Is there some kind of backup or easier solution?

Crash log (use pastebin or issue will be closed): let me know where i can find it. tks

**Comment by Cazadorsniper** [comment]
There are backups in the backup folder within the server folder.

**Comment by dfduarte78** [comment]
Wow, i guess i didn't try an old enough server backup, using the third backup available i managed to get everything back, tks!!!
