### ISSUE TITLE
Nether doesnt work

### ISSUE THREAD

**Issue by ImStitchz** [Cazadorsniper/PO3#1756]
Version PO3-3.4.11F

all forms of nether teleport do not work.

**Comment by Cazadorsniper** [comment]
Craft flint and steel then try to go.

**Comment by ImStitchz** [comment]
Made flint and steel. Just does the swirl animation likes its going to teleport me but doesnt.

**Comment by Cazadorsniper** [comment]
Send me the latest.log from the logs folder.

**Comment by ImStitchz** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/11824332/latest.log)

**Comment by ImStitchz** [comment]
i did tried it in a creative worl and nothing still

**Comment by Cazadorsniper** [comment]
Did you add/update/remove any mods?

**Comment by Cazadorsniper** [comment]
This issue seems most likely lag/tick skipping.

**Comment by ImStitchz** [comment]
the only mod i added was optifine for shaders.

**Comment by Cazadorsniper** [comment]
turn the shaders off then try again.

**Comment by Cazadorsniper** [comment]
If that doesn't work then remove optifine.

**Comment by ImStitchz** [comment]
ill try removing optifine and let you know.

**Comment by ImStitchz** [comment]
same thing. not working still.

**Comment by Cazadorsniper** [comment]
did you try the nether cake as well?

**Comment by ImStitchz** [comment]
yes nether cake doesnt work either

**Comment by ImStitchz** [comment]
nether apples dont work as well

**Comment by ImStitchz** [comment]
we're good. I crafted another flint and steel and now it works. werid.

**Comment by Cazadorsniper** [comment]
Game probably didn't realize you crafted it the first time.
