### ISSUE TITLE
Enderio fluid tank push into Vehicle charger from extra planets crash.

### ISSUE THREAD

**Issue by Meepster008** [Cazadorsniper/PO3#1757]
PO3-3.4.11F.zip
Mythic
Singleplayer

I can no longer open my world and I can open the modpack and open other worlds but I can't open the world where the glitch was happening.

Place a Vehicle charger from the mod Extra planets and place a fluid tank from ender io next to it go into the side configuration of the fluid tank and make the side touching the vehicle charger push and your game will immediately crash and the world will not reopen even if you reset the pack.

https://pastebin.com/j30fK7RM

**Comment by Cazadorsniper** [comment]
You can try turning on the forge,cfg option that removes erroring tileentities to see if that lets you get back into the world.

**Comment by Meepster008** [comment]
That worked thank you.
