### ISSUE TITLE
Lordcraft Metal Cast Bug

### ISSUE THREAD

**Issue by Etheria137** [Cazadorsniper/PO3#1759]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.4.11F**
**Pack Mode (Kappa):**
**Singleplayer:**

**Description:**
When using the tier 6 lordcraft earth spell, it won't gather Osmium ore. Don't know if this is something you can fix or if its intended.

**Steps to reproduce:**
Use lordcraft's tier 6 earth spell next to osmium ore

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I can't fix that because that is within the mod itself.
