### ISSUE TITLE
Server Crashing (not sure how to read the crash file)

### ISSUE THREAD

**Issue by Artichoke12** [Cazadorsniper/PO3#1769]
Version: 3.4.11F
Pack Mode: Mythic
Multiplayer Server

Server is crashing very quickly and out of nowhere just as me and a friend start playing on it. We've been on the server for about two months with no problems. I was having some lag issues and was looking at my server hosting control panel and saw cpu usage at 100%. memory usage was at about 4500 mb. 
Not really sure whats causing it but the cpu being at 100 is concerning.

After launching the server, it will launch but crashes within 1 minute of running. The crash report makes no sense to me, I was hoping someone could help me out to fix the issue.

Pastebin:
https://pastebin.com/ppCmxh1T

**Comment by Cazadorsniper** [comment]
Turn max-tick-time in the server.properties to -1. That will stop it from crashing but something is going wrong for the cpu to hit 100% try looking through all your machines to see if any of them is causing the issue or if any large amount of items are lying on the ground.

**Comment by Artichoke12** [comment]
ok so the server isnt crashing anymore, but when i join the server i just instantly crash. I have a feeling it's a mob farm I made yesterday and there's just a ton of items on the ground or something.

edit:
solved the problem. i figured out that it was all the particle effects causing me to crash, after lowering the particle effects it stopped lagging/crashing
