### ISSUE TITLE
AE2 Dosent seem to want to autocraft

### ISSUE THREAD

**Issue by Elpximso** [Cazadorsniper/PO3#1774]
Pack Version: 3.4.11F
Pack Mode: Normal
Multiplayer

Description: I try to craft 10 1k storage components and it crafts 4 and then stops. Although it seems to be pretty random how many it does and how many it dosent do.
Steps to reproduce: I have a setup of 1 interface and 4 assemblers, no upgrades, then i just have a pattern for 1k component on substituion, then i simply try and autocraft whatever amount i would like

**Comment by Cazadorsniper** [comment]
If you can try updating AE2 then try it again.

**Comment by Vwhbj2003** [comment]
that version is the latest one available.
