### ISSUE TITLE
Crash before pack launch

### ISSUE THREAD

**Issue by Sir-Ohms** [Cazadorsniper/PO3#1775]
# Use the search function before reporting to see if the issue has been reported before.
**3.4.11:**
**Pack Mode (Normal, Titan, Kappa, Mythic):**
**planning to play singleplayer but pack never launched :**

**game crashes before it starts up:**

**click play:**

**---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.54.19.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  HCASM (HammerLib-1.12.2-2.0.6.32.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/18/24 7:47 PM
Description: FML will not run in demo mode

java.lang.RuntimeException
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943167784 bytes (899 MB) / 1334837248 bytes (1273 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  li.cil.oc.common.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  me.superckl.biometweakercore.BiomeTweakerASMTransformer
UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  wanion.unidict.core.UniDictCoreModTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.54.19.jar)
  appeng.core.transformer.AE2ELTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  
ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  shadows.ApotheosisTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
HCASM (HammerLib-1.12.2-2.0.6.32.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.44.14 30.0.13044.14002' Renderer: 'AMD Radeon(TM) Graphics'**

**Comment by Cazadorsniper** [comment]
you need to use a paid Minecraft account.
