### ISSUE TITLE
Nether Flint and Steel

### ISSUE THREAD

**Issue by Horrific224** [Cazadorsniper/PO3#1776]
**Pack Version:** 3.4.11F
**Pack Mode (Normal, Titan, Kappa, Mythic):** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
There is no Flint and Steel recipe. JEI shows nothing on how to create it, both normal recipe and flint and STEEL recipe does not work. I've tried to go to nether by using fire charges, but it says I NEED to create a flint and steel to enter. Nether apple does not teleport me without flint and steel either.

I've removed Project E since i did not want EMC, is this related and if so, is there a way to readd the recipe without readding Project E? 

Thanks.

**Comment by Cazadorsniper** [comment]
Reinstall ProjectE and the recipe scripts will work correctly.

Of course you can keep ProjectE out, but you will need to edit the quest book and recipe scripts (which will be a lot of work).
