### ISSUE TITLE
Epeolatry is not considered a Sword for Cobwebs

### ISSUE THREAD

**Issue by slyk26** [Cazadorsniper/PO3#1779]
**Pack Version:** PO3-3.4.11F
**Pack Mode (Normal, Titan, Kappa, Mythic):** Mythic
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**

The Sword is not considered a "Sword" for Cobwebs, so breaking them takes forever

![image](https://github.com/Cazadorsniper/PO3/assets/102811034/e0bbb5b0-b990-4a1a-87ca-76236c7d7b8b)

**Steps to reproduce:**

- cheat in the sword
- place cobweb
- try to break it in survival
- wait an eternity for it to break

~~**Crash log (use pastebin or issue will be closed):**~~

**Comment by Cazadorsniper** [comment]
There is nothing i can do about this because of how contenttweaker works (at the time of creating the sword).
