### ISSUE TITLE
Frequent disconnections for friend joining a LAN Game

### ISSUE THREAD

**Issue by singularity125** [Cazadorsniper/PO3#178]
**Pack Version:**
3.0.38

**Description:**
When running a game in Lan Mode and having a friend connect, he is consistently getting disconnected within 1-5 minutes of loading in, making it unplayable for him.

**Steps to reproduce:**
Unknown, seems to happen regardless of what we're doing on the base. It also never effects me, the host.

**Crash log <use pastebin or similar>:**
This is not the full log, since it isn't a crash... this is what I see on the server side when he disconnects, and he doesn't see anything particular in his logs.
https://pastebin.com/MS2z2y0m

**We have tried:**
- Switching from Hamachi to port-forwarding, no change
- Installing RandomPatches, which DID help with initial connections but not these disconnects

**Comment by nzminecraftDOTcom** [comment]
Speedtest.net

Do a test (NOT to a local location)
Post your result
You most likey have not got enough bandwidth to handle a server type of setup. (That or you are both too far away from each other)
