### ISSUE TITLE
Lunar reactive dust recipe

### ISSUE THREAD

**Issue by lupleime** [Cazadorsniper/PO3#1781]
**Pack Version:3.4.11**
**Pack Mode (Titan)**
**Multiplayer**

**Description:**
Lunar Reactive Dust resonator recipe
i switched from kappa to titan but for some reason the lunar reactive dust recipe doesn't work anymore.
it was working on kappa mode, but after switching it disappeared from JEI and doesn't work anymore
i even tried reinstalling the modpack, and tried it in both single and multiplayer

Or is it indented that that recipe isn't available in titan mode

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by lupleime** [comment]
Just discovered that the resonator recipe is available in normal, kappa and mythic mode, But not in titan

**Comment by Cazadorsniper** [comment]
mods.extrautils2.Resonator.remove(<extrautils2:ingredients:3>);

This was done on purpose.

**Comment by lupleime** [comment]
Ah okay thats good to know then, but what machine / recipe could i use to get my first Lunar reactive dust, cause a pulverizer needs the dust for the machine frame, and i cant find any other recipe that i can use without needing the Dust
i have the ingots
