### ISSUE TITLE
Can't join discord server, assuming because of account breach.

### ISSUE THREAD

**Issue by edgars-cirulis** [Cazadorsniper/PO3#1785]
![image](https://github.com/user-attachments/assets/7347445e-a8f2-40e6-988d-0caf1cb317b1)

My discord: edgarscirulis

I am really sorry about phishing links due account breach.

**Comment by Cazadorsniper** [comment]
Recommend asking for OG about this or Discord itself.

**Comment by edgars-cirulis** [comment]
> Recommend asking for OG about this or Discord itself.

And how can I contact?

**Comment by Cazadorsniper** [comment]
Through DM or just contact Discord, I doubt I can do anything.

**Comment by edgars-cirulis** [comment]
> Through DM or just contact Discord, I doubt I can do anything.

What's his Discord?

**Comment by edgars-cirulis** [comment]
> Through DM or just contact Discord, I doubt I can do anything.

Also it has none of Discord business because they banned me because of account breach I got aka token hijack and got sent phishing links.
