### ISSUE TITLE
Sacthoth Quest #682 won't complete

### ISSUE THREAD

**Issue by SpeedSlider** [Cazadorsniper/PO3#179]
**Pack Version:**3.0.38

**Description:**Killed Sacthoth obtained Soul Reaper Sword but Quest did not complete.

**Steps to reproduce:**Did not perform a second attempt to kill as previous mob boss quests also had issues used manual complete command.

**Crash log <use pastebin or similar>:**

**Comment by SpeedSlider** [comment]
Same issue with J'zahar 689

**Comment by Gurkanan** [comment]
smae with ender dragon and Antlion Overlord

**Comment by legendaryA1** [comment]
this happens with most pack you have to kill them many times for it to work or us the command /bq_admin editto edit the quest book and make it as compleated or say kill 0 to finish the quest
