### ISSUE TITLE
Current save and every backup of my current playthrough crash with the same error, possibly a single mod issue

### ISSUE THREAD

**Issue by GucciSmartMicrowave** [Cazadorsniper/PO3#1790]
(server tick loop has been posted about but not anything about the stuff after "Error:")
Pack Version: 3.4.11F
Pack Mode Normal
Singleplayer

Description: Everything was working fine last night, after closing the game on the erebus roof only my current playthrough is bugged. Every time I open the original save, or any backups that I have used "extract here" in a seperate folder then move to my saves folder it somes up with this error message in the minecraft launcher: The game crashed whilst exception in server tick loop Error: java.lang.NoClassDefFoundError: net/minecraft/world/World$2

Steps to reproduce: Open world (backup or original save), loading world, building terrain, 0%, crash

Crash log
https://pastebin.com/053mAW2A

Based on the final lines of the crash log talking about reborncore this might be a corrupted mod issue, or maybe an alchemical bag issue, which i have pretty much all of my important items in

**Comment by Cazadorsniper** [comment]
The issue is thermal dynamics turn off or remove the mod, open the world, then place the mod back in. you will have to place all the ducts you used back.

**Comment by GucciSmartMicrowave** [comment]
I removed thermal dynamics, expansion, foundation, and innovation from the mods folder for the curseforge profile and moved them to a seperate folder, but in a seperate test world theyre all still in the game and working. Do I instead delete them off my computer, load my world, then download a new curseforge profile and copy the mods over?

**Comment by Cazadorsniper** [comment]
find this "B:removeErroringTileEntities=false" in the forge config and turn it to true then try again.

**Comment by GucciSmartMicrowave** [comment]
Thank you very much, the issue was thermal dynamics, and for energy needs i just EMC'd like a thousand draconic solar panels, all with cryo fluxducts under them which i placed with a builders wand which im guessing is what caused the issue.

I can log into my world and just need to place my fluxducts down, I couldnt remove Thermal dynamics from the game because if it was on my pc at all it would just access it ouside of the mods folder from other installations and use it in game, or when i opened the launcher it would reinstall thermal dynamics into my mod folder.

I fixed it by deleting every other installation that had thermal dynamics since i don't play them anymore, and making sure on startup the mod didnt get reinstalled to the installation and that fixed my world.
