### ISSUE TITLE
Because of extra planets update[Client thread/ERROR]:Potential problem: Galacticraft did not complete injection of bytecode into: acl (0 / 1)

### ISSUE THREAD

**Issue by flepflum** [Cazadorsniper/PO3#1791]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.4.11F
**Pack Mode (Normal, Titan, Kappa, Mythic):**Titan
**Singleplayer, Multiplayer, or LAN?:**I use essentials mod so either LAN or multiplayer idk

**Description:** **IT IS HAPPENING BECAUSE OF THE UPDATE TO EXTRA PLANETS MOD.** I Manually downloaded each mod to see what was going wrong
 It started to happen when i was originally on 3.4.11f but updated the mods which caused it to have the error/ also works when downloading version 3.4.10 and updating the mods
**Steps to reproduce:**
download version 3.4.11f then update the mod extra planets which caused it to have the error/ also works when downloading version 3.4.10 and updating the mod extra planets
**Crash log (use pastebin or issue will be closed):**
does not crash but just stays without loading anything
so hear is debug log could not fit in 1 so i put in 2 https://pastebin.com/SKqn0mWG, https://pastebin.com/qPGimv7X

**Comment by Cazadorsniper** [comment]
The only mod that is somewhat safe to update would be AE2 every other mod I didn't update because of issues.
