### ISSUE TITLE
Epeolatry 2

### ISSUE THREAD

**Issue by kotelkonrad** [Cazadorsniper/PO3#180]
**Pack Version:**
latest
**Description:**
don't get a sword
**Steps to reproduce:**
![2019-03-19_22 01 57](https://user-images.githubusercontent.com/48735640/54641506-a70f7700-4a92-11e9-87db-fa1eb7f13043.png)

**Comment by martinschuberteu** [comment]
Can you click the arrow ">" next to "Detect/Submit"? There's a second screen with requirements.

**Comment by kotelkonrad** [comment]
ok

**Comment by kotelkonrad** [comment]
> **Pack Version:**
> latest
> **Description:**
> don't get a sword
> **Steps to reproduce:**
> ![2019-03-19_22 01 57](https://user-images.githubusercontent.com/48735640/54641506-a70f7700-4a92-11e9-87db-fa1eb7f13043.png)
