### ISSUE TITLE
Grout not cooking in furnace

### ISSUE THREAD

**Issue by Crackajacka** [Cazadorsniper/PO3#181]
Version: 3.0.38
In my game, for some reason, I cannot cook grout to make seared bricks and it doesnt even show up in the recipes. All that it does say through recipes is to make seared bricks using the tinkers smelter which of course is impossible.

I can make grout no problem but grout will not go into the gold furnace I have yet will go into a regular furnace but just wont cook.

I've also reinstalled the modpack to see if that would fix the issue but the issue still occured.

**Comment by Hallowizer** [comment]
This is intentional, you're supposed to use the Melter.
