### ISSUE TITLE
Crash on Initialization 

### ISSUE THREAD

**Issue by Hibernating-Bear** [Cazadorsniper/PO3#186]
**Pack Version:** 3.0.38

**Description:** 
Pack crashes before it initializes.

This happens only with PO3, and i am able to launch other 1.12 packs and other versions of MC without issue.

All Drivers are up-to-date

**Steps to reproduce:** 
1. Launch Pack via Twitch Launcher
2. Click the "Play" button in the launcher window.
3. Pack then Crashes.

**Crash log (use pastebin or similar):**

Launcher Crash log too big for Paste Bin, so here is a link to the contents of the file 
https://github.com/Hibernating-Bear/Notes-n-Such/blob/master/PO3-Launcher%20Crash%20Log

**Comment by Cazadorsniper** [comment]
On the twitch launcher there is a setting called "Repair Minecraft'/"Repair Profile" click that and try again.

**Comment by Hibernating-Bear** [comment]
Having done that already prior to opening this issue with no luck I wasn't expecting much, but that appears to have fixed the issue.
Thanks for the help and advice
