### ISSUE TITLE
blood in seared smeltery

### ISSUE THREAD

**Issue by kotelkonrad** [Cazadorsniper/PO3#187]
![2019-03-21_11 20 57](https://user-images.githubusercontent.com/48735640/54746158-c52cc280-4bcb-11e9-91d7-8f9f0370220e.png)

**Comment by kotelkonrad** [comment]
fuck logic

**Comment by martinschuberteu** [comment]
Seriously?

**Comment by Cazadorsniper** [comment]
Maybe try getting light inside your smeltery?

**Comment by jgaines** [comment]
When life hands you lemons make lemonade or in this case, make slime balls.
