### ISSUE TITLE
Barrels not filling with water when it rains

### ISSUE THREAD

**Issue by NightRadz** [Cazadorsniper/PO3#189]
**Pack Version:**
3.0.38
**Description:**
when its raining (which it doesnt look like it rains but you can tell from the clouds/sky) my barrels wont fill up.
**Steps to reproduce:**
toggling rain and waiting for barrels to fill but dont fill
**Crash log (use pastebin or similar):**
N/A

**Comment by Cazadorsniper** [comment]
#61 But don't actually need rain.
