### ISSUE TITLE
Holograms falling through the world

### ISSUE THREAD

**Issue by NLBlacky** [Cazadorsniper/PO3#190]
**Pack Version:** 3.0.38

**Description:** Holograms are falling through the world. There was a ticket made [here](https://github.com/randombyte-developer/holograms/issues/32) which I've been using. This ticket will hopefully provide all the needed information.

**Steps to reproduce:** Just place down a hologram and you will see it. Here is an example command: `/summon armor_stand ~ ~ ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:"TEST",CustomNameVisible:1b}`

**Comment by TheFlash787** [comment]
Bump. We've tested with and without Sponge. Same issue. Please get this fixed asap.

**Comment by randombyte-developer** [comment]
Blood magic was the cause if anyone is interested.
