### ISSUE TITLE
Portal Gun (by iChun) Missing

### ISSUE THREAD

**Issue by DevilsNipple** [Cazadorsniper/PO3#194]
I see that in the Modlist it has "Portal Gun (by iChun)". 

I really enjoyed this mod in PO2, however it doesnt appear to actually be in PO3. 
The mod doesnt show in my friends or my own mod folder nor is it in the server files.

Dunno if im just somehow not on the latest version maybe, i assumed the modpack auto updates on Twitch Launcher? Couldn't see any comments about it when checking the issues page or general google search.

**Comment by Cazadorsniper** [comment]
It was removed, didn't need it in the pack.
