### ISSUE TITLE
Crash on launch: Walia causes IllegalArgumentException

### ISSUE THREAD

**Issue by Leo40Git** [Cazadorsniper/PO3#195]
**Pack Version:** 3.0.38

**Description:** The game crashes after the loading screen. (cool loading screen BTW)

**Steps to reproduce:**
1. Launch the game
2. Wait for it to load
3. ???
4. RIP Minecraft

**Crash log:** https://pastebin.com/CSEzfZfH

*Note:* I did add a mod ([Armor Toughness Bar](https://minecraft.curseforge.com/projects/armor-toughness-bar?gameCategorySlug=mc-mods&projectID=313816)), but the log isn't pointing to it.

**Comment by Leo40Git** [comment]
Oh, and I also can't upload latest.log and debug.log, because *they're so big Pastebin is refusing to upload them.*

**Comment by Cazadorsniper** [comment]
Try removing that mod then try again.

**Comment by Leo40Git** [comment]
excuse me how does a toughness bar mod cause a block info overlay mod to crash
