### ISSUE TITLE
Twilight Forest crashing server

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Cazadorsniper/PO3#196]
**Pack Version:**
3.0.38
**Description:**
Crash when player enters Twilight Forest (This has only recently started happening)
I don't believe it is a Sponge issue, as it was working fine for months.
**Steps to reproduce:**
Enter Twilight Forest 
**Crash log (use pastebin or similar):**
https://pastebin.com/MDQdsuhg

**Comment by Cazadorsniper** [comment]
That has to do with RFTools Dims not Twilight
