### ISSUE TITLE
Project ozone 3 Server set up

### ISSUE THREAD

**Issue by Lordyantman** [Cazadorsniper/PO3#197]
Server will not change to Botania skyblock

**Comment by nzminecraftDOTcom** [comment]
what does level type in server.properties say.

**Comment by Lordyantman** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/48871473/54873732-72adfa80-4db3-11e9-8d5c-9c4877223231.png)

**Comment by Lordyantman** [comment]
Islands wont spawn and it spawns a default world

**Comment by nzminecraftDOTcom** [comment]
You are deleting your generated world in between changing the level type right?

**Comment by Lordyantman** [comment]
Nope, what file do i delete

**Comment by Cazadorsniper** [comment]
world file

**Comment by nzminecraftDOTcom** [comment]
In your server.properties file look for the line level-name=[whatever you have here]
In the same folder as your forgeserver.jar file delete whatever folder came after the = in level-name

**Comment by SneakyTurtle27** [comment]
i dont have a batch file when downloading the server and whenever i try to create one it just closes upon startup how do i fix this?

**Comment by nzminecraftDOTcom** [comment]
You'll need to create a file for the server to run

```
@echo off
java -Xms1G -Xmx7G  -jar Forge.jar nogui -o true
```

Replace "Forge.jar" with whatever your forge.jar file says or edit the forge.jars name to say "Forge.jar"
