### ISSUE TITLE
Mobs not moving

### ISSUE THREAD

**Issue by Jaciii** [Cazadorsniper/PO3#198]
**Pack Version:** 3.0.38

**Description:** Mobs is just standing still on the same block, turning around and not moving around. This breakes earl-game mobfarms

**Steps to reproduce:** Just watching mobs that aren't trying to kill the player

**Comment by nzminecraftDOTcom** [comment]
You don't have any god mode, vanish, creative mode or settings that voids damage/mobs seeing you enabled by mistake? (Assuming this is on a server)

**Comment by Jaciii** [comment]
I play singleplayer

**Comment by saulysw** [comment]
Passive mobs (such as normal pigs, chicken etc) seem not to move for me in the overworld. Mobs do come after me though, once agro. It may be dimension specific? Also might be linked to another issue - where mobs disappear sometimes. They can hit you but you can't see or hit them.

**Comment by Jaciii** [comment]
For me, it's hostile mobs, that aren't agro, stands still too... I haven't tried in other dimensions, but my mobfarm is in the overworld, so that doesn't help.
