### ISSUE TITLE
game crashes when i open an inventory

### ISSUE THREAD

**Issue by darknighhta** [Cazadorsniper/PO3#199]
**Pack Version:* Version: 3.0.38

**Description:* 
hello, i made an account for help on this pack, project ozone 3, i haven't played a modpack since the 1.7 mods were around before minecraft was on twitch so i am a little discombobulate.

basically whenever i click on anything with an inventory or try and open my invo with E, the game and my whole computer freezes and then after i can close the game with task manager my game crashes.

 This modpack looks so very well made from the youtubers i have been watching play it and i am really determined to try and make it work for myself, but its been years since i have messed around with modded minecraft.

i think it could be something with NEI judging on forums i looked up with the same problem from older modpacks, but im not sure.

**Steps to reproduce:*
 i close out the game and restart it and tried opening my inventory with e, it crashed. then restarted again and tried a chest and it crashed. did this a few more times and it definitely seems to be things with inventory's (i just started the world so i dont have many things to try out) I think this because the one mod were you can switch your hotbars around with in your inventory still works so i dont think its anything specifically in my inventory.

**Crash log (use pastebin or similar):* 
i cant seem to find were to get the crash log from this pack but if instructed how i can post it asap, again sorry if this is informal or poorly posted it has been a while and im kind of lost with it all. I just want to get this to work, i am only playing single player so hopefully it shouldn't be too hard

**Comment by Cazadorsniper** [comment]
Look for where the modpack is installed on your pc (if using twitchapp can go to the modpack right-click then press open folder) and look for the crash-report folder if the game actually crashed if it didn't find the logs folder and give me the latest.log after that copy/paste to pastebin.com then send the link here.

**Comment by nzminecraftDOTcom** [comment]
C:\Users\PUT_YOUR_PC_NAME_HERE\Documents\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward

Should find a folder named crash reports or similar there (assuming the game actually stopped and didn't just send you back to the home screen - then do what @Cazadorsniper said)
