### ISSUE TITLE
Wither and Ender Dragon

### ISSUE THREAD

**Issue by Zander27** [Cazadorsniper/PO3#2]
I have killed the wither 10+ times with both the quest reward sword, base minecraft diamond sword, and a tinkers sword but no matter what it doesn't count towards the quest. Same thing for the ender dragon, I have killed it twice now with the quest reward sword and it hasn't counted towards the quest.

**Comment by Zander27** [comment]
In the mean time, is there any way for me to force complete those 2 quests? or is there some setting that is wrong which is causing it to not detect those kills? I was able to do the quest for the zombie, skeleton, creeper, etc. so idk why I cant do the bosses. It also has counted my kills for all the twilight bosses, and the spider from the erebus. So it appears like it is just the wither and ender dragon

**Comment by Chik3r** [comment]
To force complete quests:
1) Enable advanced tooltips (F3+H)
2) Go to the quest book and hover over to see the quest number.
3) Do /bq_admin complete xx , where xx is the quest number.

**Comment by Ainires** [comment]
How do I fix it if I’m on single player?

**Comment by Chaftalie** [comment]
If you have cheats disabled you can press the button "open to LAN" int the Pause menue than activate the button "allow cheats" in the top right, than just "start LAN world" in the bottom left.

With that you can use commands.

**Comment by Ainires** [comment]
You are a darling! Thanks

**Comment by WebFreak001** [comment]
this issue still persists (in multiplayer here, killed Ender Dragon twice), it doesn't seem to generate any biotite either when killing the Ender Dragon. The portal to the small islands exists, but I flew around for like 20 minutes in creative without finding any biotite at all (but plenty of the other ores), which seems to break any progression with advanced crafting
