### ISSUE TITLE
Nether star Not dropping from Wither

### ISSUE THREAD

**Issue by Masharibzaheer** [Cazadorsniper/PO3#20]
Pack Version:PO3 3.0.38

**Description:**hi in this version of PO3 3.0.38 i have killed wither 3times with thinker and diamond sword but the wither is not dropping any nether star and the quest in the book is not completing also...

**Steps to reproduce:**

**Crash log:**

**Comment by Cazadorsniper** [comment]
Did you change anything in the pack's config/scripts? that might be why you didn't get a nether star.

**Comment by Masharibzaheer** [comment]
No but my issue got solve i back up my world and force reinstall PO3 then the issue was fixed...:)
