### ISSUE TITLE
Envoker not spawning at my island

### ISSUE THREAD

**Issue by Kiriao** [Cazadorsniper/PO3#201]
**Pack Version:**
3.0.39
**Description:**
I've change my difficulty to Normal and Envoker is not spawning in, how can I even get BLUE HEARTS without Envoker spawning...

**Steps to reproduce:**
N/A
**Crash log (use pastebin or similar):**
N/A

**Comment by AndromeHyperion** [comment]
You can find them in the abyssalcraft dimensions. Thats where I've found them.
