### ISSUE TITLE
wooden crucible

### ISSUE THREAD

**Issue by ctabor511** [Cazadorsniper/PO3#202]
**Pack Version:**
Most recent Version
**Description:**
When I put leaves or saplings into a wooden crucible in order to get water so I can make clay, the first 20 mb gets duplicated making it so that there is 20mb stuck in the wooden crucible at all times, so I can't put the dust into the wooden crucible
**Steps to reproduce:**
put leaves into a wooden crucible and it does it every single time

**Comment by Cazadorsniper** [comment]
Transfer the water to a barrel, put dust in said barrel filled with water, get clay.
