### ISSUE TITLE
[3.0.39] Weird issue combining EnderIO and Mekanism

### ISSUE THREAD

**Issue by Gamertech** [Cazadorsniper/PO3#206]
**Pack Version:** 3.0.39

**Description:** I updated to the 'new' 3.0.39 version today and after loading into my world, I get greeted with a ton of explosion sounds.

I tracked it down to an EnderIO SAG mill I'm using to process ore where there's a player-damaging explosion effect appearing 1 block behind it where I have a Mek universal conduit. Getting hit by it triggered the 'Meet the Beetles!' Erebus advancement.

- If the SAG is connected to universal cable and is processing ore, then the explosions will occur 100%
- If the SAG is processing ore but not connected to the cable, then the explosions wont happen
- If the cable's connected but the SAG isn't running then no explosion

Further troubleshooting with a creative-generated SAG mill and draconic creative energy source caused it to explode rapidly as it's filling power. Testing with an EnderIO energy conduit didn't generate the explosions.

So it only seems to occur when the SAG is taking energy into itself via a Mekanism energy cable. The Alloy Smelter does the same. However Nuclearcraft machines don't have this problem.

**Steps to reproduce:**
1- Place an EnderIO SAG Mill (in this case, the middle tier)
2- Connect it to a Mekanism Universal cable (tested the basic and advanced)
3- Connect a power source such as a Draconic creative RF Source
4- Duck for cover

**Crash log (use pastebin or similar):**
No related errors showing in debug

**Comment by Cazadorsniper** [comment]
Did it break any blocks?

**Comment by Gamertech** [comment]
Nope. Only player damage.

**Comment by Cazadorsniper** [comment]
Are sure it wasn't just an Extra Utils generator?

**Comment by Cazadorsniper** [comment]
And does this happen with any other cable?

**Comment by Gamertech** [comment]
No ExUtils blocks in use, and it doesn't happen using EnderIO energy conduits. Just Mek universal conduits so far.

**Comment by Gamertech** [comment]
Ren updated and had this today as well. Mek entangloporter outputting into an EnderIO capacitor bank. Exact same explosions.

If you're interested, Mekanism was forked as the maintainer wasn't maintaining it, the fork is called Mekanica. Active devs and a much more optimised than the base mod. It's a straight mod swap for Mekanism. Can keep the same configs etc.

**Comment by Cazadorsniper** [comment]
Mekanism has been getting a lot of updates lately actually. So no I won't switch to Mekanica.

**Comment by Cazadorsniper** [comment]
Its Ender IO doing that not Mekanism, just tried several different power transfer options explosion only happened with Mekanism universal cable and Thermal Dynamics Cryo-Flux duct. Will probably happen with ExtraUtils2 generators also. Explosion did not happen with TE energy cell or Mekanism Energy Cube, only the Ender IO capacitor.

**Comment by 12manyDaves** [comment]
Also happening with capacitors connected to an Extreme Reactor. I disconnected mine and the noise stopped.

**Comment by Cazadorsniper** [comment]
Yes that is Ender IO doing that.
