### ISSUE TITLE
[3.0.38] Project Ozone unable to connect to server

### ISSUE THREAD

**Issue by mrrotijohn** [Cazadorsniper/PO3#207]
I'm a total newbie at this and I'm really unsure what went wrong.

**Pack Version:** 3.0.38

**Description:** Unable to connect to server, portforwarding done.

**Steps to reproduce:** localhost:25565 connection goes through, public address:25565 does not.

Now I have another issue. I tried connecting to this multiplayer server using the host device using the IP localhost:25565 and it works, I'm able to enter.

However on a separate device, I entered the IP using my public address with port 25565, I just can't seem to get it to connect to server.

Portforwarding has been done and checked time and time again. I've even reset my IP by restarting my router multiple times.

Please help.
**Crash log (use pastebin or similar):** No crash log.

**Comment by djoey123** [comment]
Most routers doesnt support an loop to your own ip(public ip to your intern ip).
Search for your local ip(192.168.*.*)
Use that on your other device in your own network.

You can check if your port is open on:
Canyouseeme.org

If it is true, then people outside of your network can access the server.

:)

**Comment by mrrotijohn** [comment]
Hi @djoey123,

I've tried using my local ip to connect, it does not work.
Thanks for that but I tried the Canyouseeme.org kind of websites too, it keeps telling me the port is closed.

**Comment by djoey123** [comment]
I think you didnt bind your local ip in your server settings. that could fix it

**Comment by mrrotijohn** [comment]
Aren't you supposed to leave the server-ip empty in the server setting file? Sorry, this was what I saw from some of the video tutorials on youtube.

**Comment by mrrotijohn** [comment]
Hi I included my local ip to the server settings, the port still seem to be closed. :(

**Comment by djoey123** [comment]
I think your windows firewall is blocking all the request. 

https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by mrrotijohn** [comment]
Thanks @djoey123, I just added the rules to allow the connections but it still does not open.

**Comment by djoey123** [comment]
It could be your firewall, i have no other solution :P

**Comment by mrrotijohn** [comment]
Damn... I tried with my firewall off already. The port just refuses to open for some strange reason. I've even tried using no-ip to do it since I can't set static IP.

localhost:25565 works however. That's what's really weird about this.
