### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chance Cubes

### ISSUE THREAD

**Issue by lays24mc** [Cazadorsniper/PO3#209]
**Pack Version:**
3.0.39

**Description:**

Server crashed with "Exception in server tick loop"!

**Steps to reproduce:**

**Crash log (use pastebin or similar):**

https://pastebin.com/9m98N9ym

**Comment by Cazadorsniper** [comment]
Reported to mod dev

**Comment by Khranos** [comment]
Just a heads up, by deleting the Chance Cubes mod from the server's mod files, you can run the server seemingly without issue. I assume this also works on single player. 

I'm not affiliated with the pack and can't guarantee this won't cause issues further down the line, but so far it has allowed the pack to work for my server. You won't be able to use chance blocks of course, but that's not really an issue to a lot of people it would seem.

**Comment by Cazadorsniper** [comment]
@Khranos You can do that but have fun breaking Ender IO machines.

**Comment by Khranos** [comment]
I would like to add that I fixed this issue by replacing my ChanceCubes version in both my client and server to "1.12.2-4.0.0.270". According to their issues page, the latest version of Forge was not compatible with the current version in PO3.
