### ISSUE TITLE
Quori Fragments dropping in void dream world

### ISSUE THREAD

**Issue by Tirexxg** [Cazadorsniper/PO3#212]
**Pack Version:**
3.0.39

**Description:**
You included a crafting recipe for the quori fragment but it´s not needed because you can get into the void dreamworld with the one fragment you get from the xia boss, and there the mobs are dropping them t a massive amount with the Epeolatry. 

Is that intended?
**Steps to reproduce:**
Use the quori fragment on a bed. You will be teleported to another dimension there you can kill some mobs an get stacks of the quori fragment

**Comment by Cazadorsniper** [comment]
You're able to fight the Xia boss without crashing because other people couldn't.

**Comment by Tirexxg** [comment]
yes i always were able to fight him.

**Comment by Cazadorsniper** [comment]
Yes will leave it as is for people who can't fight Xia.
