### ISSUE TITLE
[0.39] Just Updated to it and server keeps stalling because of better questing. 

### ISSUE THREAD

**Issue by 123Kappa** [Cazadorsniper/PO3#213]
**Pack Version:**
0.39
**Description:**

Just updated my server to 0.39 better quests seem to be stalling my server any clues? 

https://paste.feed-the-beast.com/view/7f2814af

**Comment by 123Kappa** [comment]
I talked with the dev and he said that he is working on it

**Comment by Cazadorsniper** [comment]
ok
