### ISSUE TITLE
crash with big reactors

### ISSUE THREAD

**Issue by mkerkdijk** [Cazadorsniper/PO3#214]
**Pack Version: PO3-3.0.39**

**Description: crash with big/extreme reactors**

**Steps to reproduce: place a dimensional transiever or vibrant capacitor directly to a powerport of  the reactor**

**Crash log (use pastebin or similar):https://pastebin.com/2Xxk4bR4**

**Comment by Cazadorsniper** [comment]
Put cable in between?

**Comment by mkerkdijk** [comment]
> Put cable in between?
gonna try that this evening, but it worked in the previous version

**Comment by Tegwen** [comment]
I loaded the update and I don't get a crash, but my vibrant capacitors were making an explosion sound.  I tore apart my mob farm, which was nearby, trying to get the sound to stop until I figured out it was the vibrant capacitor connected directly to my Reactor.  I put an energy cell on it for now but that doesn't have anywhere near the transfer capacity that a bank of vibrant capacitors will.

**Comment by Cazadorsniper** [comment]
try energy conduits if you don't want to hear the explosion sounds.

**Comment by Cazadorsniper** [comment]
or some type of wireless energy relays.
