### ISSUE TITLE
[3.0.39] Game fails to start.

### ISSUE THREAD

**Issue by DeimosMoons** [Cazadorsniper/PO3#215]
Pack Version: 3.0.39

Game doesn't start through MultiMC. Tried fresh installs and downloads, immediately goes to the console every time.

https://pastebin.com/vv9SEaYG

**Comment by Cazadorsniper** [comment]
Can it start with twitchapp?

**Comment by DeimosMoons** [comment]
I get this instead with the Twitch/Minecraft Launcher

Unable to save download. jna-4.4.0.jar
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Error details: Attempting to move successful download to D:\Games\Minecraft\Twitch\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
The file exists.


Filename on disk: 8a47-db26-3296-d987
Path: C:\Users\mivi3\AppData\Local\Temp\8a47-db26-3296-d987
Exists: file

**Comment by DeimosMoons** [comment]
Force closing the Twitch App and restarting my internet oddly seems to of fixed it for me.
