### ISSUE TITLE
(3.0.39) Game crashes on breaking EnderIO machines

### ISSUE THREAD

**Issue by Aschevogel** [Cazadorsniper/PO3#216]
**Pack Version:**
3.0.39
**Description:**
Hey there,
Whenever I break an EnderIO machine block after updating to 3.0.39 (tested with 3 kinds of Alloy Smelters, 2 kinds of SAG Mills and a wired charger and Slice and Splice) both when powered or not, and also with a Cap inside and not. This leads to a "corrupted" world that cannote be loaded into. The ticking player error persists through a restart and the game crashes instantly on load in.
**Steps to reproduce:**
Break an Ender IO machine

**Crash log (use pastebin or similar):**
1.) https://pastebin.com/8XVDeZiU
2.) https://pastebin.com/RyinUuQq (1st restart after initial crash)
3.) https://pastebin.com/wHJWJVy0 (2nd restart after initial crash)

After that, i was also reproducing the error with the same crash message with 2 old backups

**Comment by Cazadorsniper** [comment]
Does this happen if you break them in creative?

**Comment by Aschevogel** [comment]
Oh damn I totally forgot to check that, nope breaking in creative works.
Guess there is a work around until there (hopefully) is a fix.

**Comment by Cazadorsniper** [comment]
reporting to Ender IO devs now

**Comment by Aschevogel** [comment]
Thanks a ton for answering so quickly, have a wonderful day :)

**Comment by Cazadorsniper** [comment]
I get emails and I check email quite often

**Comment by Cazadorsniper** [comment]
One more thing were you on a server or singleplayer?

**Comment by Aschevogel** [comment]
Was in singleplayer

**Comment by Cazadorsniper** [comment]
Found the issue, just waiting for Botania to update.

**Comment by Xmat2000** [comment]
Yea this happens because botania ring of magnetization if you remove the ring it wont crash i also i have found that if you change botania invert ring of magnetisation in the config file you can load the world which will allow you to and unequip the ring

**Comment by Aschevogel** [comment]
Sounds good, will update to .39 on the weekend again and collaborate that
