### ISSUE TITLE
Mining AE machines crashes game

### ISSUE THREAD

**Issue by Mavrick2489** [Cazadorsniper/PO3#218]
**Pack Version:**
3.0.39
**Description:**
Game crashed when mining AE growth chamber and the inscriber
**Steps to reproduce:**
place any AE machine and mine it. I have a tinkers ghostwood pickaxe with unbreaking
**Crash log (use pastebin or similar):**
not sure how to upload sorry

**Comment by Cazadorsniper** [comment]
AE doing it too huh

**Comment by Cazadorsniper** [comment]
copy/paste crash to pastebin then put link here.

**Comment by Mavrick2489** [comment]
https://pastebin.com/VNria18k

**Comment by Mavrick2489** [comment]
https://pastebin.com/HyT77txG

2nd crash
