### ISSUE TITLE
Interacting with Ender IO Capacitor crashes game

### ISSUE THREAD

**Issue by fightmesun** [Cazadorsniper/PO3#219]
**Pack Version:**3.0.39

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or similar):**

[crash-2019-03-27_21.23.02-client.txt](https://github.com/Cazadorsniper/PO3/files/3016180/crash-2019-03-27_21.23.02-client.txt)

**Comment by Cazadorsniper** [comment]
#216
