### ISSUE TITLE
Disconnects on first connect after restarting the game.

### ISSUE THREAD

**Issue by Streamcyper** [Cazadorsniper/PO3#22]
**Pack Version:**
3.0.38

**Description:**
Disconnects on first connect after restarting the game.
This happens every time for everyone trying to connect the server, after launching the game. No problems after going back to server screen and reconnecting.

**Steps to reproduce:**
1. Start the game.
2. Connect to a server.
3. Get disconnected with error "Internal Exception: java.io.IOException: An Exsisting connection was forcibly closed by remote host"
4. connect again and everything is fine.

**Crash log:**
Game does not crash to desktop so no crash log.

**Comment by Blackcatz1911** [comment]
https://minecraft.curseforge.com/projects/randompatches

With this mod the timeouts will be longer and you will be connected on the fist time.

**Comment by Streamcyper** [comment]
So changing the connection timeout delay will help in this case?

**Comment by Blackcatz1911** [comment]
Set the read timeout to 90 seconds and the login timeout to 900 seconds and the problem will be solved. Both are the default values from the mod.
