### ISSUE TITLE
Project Ozone 3

### ISSUE THREAD

**Issue by Shamma9111** [Cazadorsniper/PO3#221]
Hi.  I'm setting up a new server and I'm somewhat new to this.  My issue is there are so many monsters in the spawn area and everywhere on the map and they don’t move at all.  I need to change how many monsters spawn and what types.  I would appreciate any help with this.  Thanks.

**Comment by Shamma9111** [comment]
Really...  no response at all!

**Comment by Cazadorsniper** [comment]
Because we are doing things to the pack at the moment.

**Comment by nzminecraftDOTcom** [comment]
Is it a blood moon by any chance
If so, i'd suggest you edit the config file for the bloodmoons and disable them. They will tear a server to its knees.

**Comment by Shamma9111** [comment]
I disabled blood moon before.  What config file is the default mob spawns?

**Comment by nzminecraftDOTcom** [comment]
The bloodmoon cfg file had the option to adjust it, disabling the blood moon should stop the increased spawns.

**Comment by Shamma9111** [comment]
But what is the file to limit the default spawn rate and if I don’t want the black skeletons to spawn in the overwold

**Comment by nzminecraftDOTcom** [comment]
I don't think there is one, you would need to find a mod that will modify the spawn rates and limit what worlds mobs can spawn in.

**Comment by Shamma9111** [comment]
Would you happen to know of one that is compatible with PO3?

**Comment by nzminecraftDOTcom** [comment]
You will need to find one yourself, I have never looked for one that does something like that.

**Comment by Shamma9111** [comment]
Thanks for the help.  I think I fixed the issue and I’m pretty sure it was my fault.  I do have another question and that involves the astral sorcery mod.  Can I remove that from my server or will it mess up other mods?

**Comment by Cazadorsniper** [comment]
It will mess up the pack, yes.

**Comment by Shamma9111** [comment]
Thanks.  Any thoughts on how to increase the amount of loaded chunks from the default of 64?

**Comment by Cazadorsniper** [comment]
nope.
