### ISSUE TITLE
Item Translocators will not push to a storage drawer with a void upgrade

### ISSUE THREAD

**Issue by dbridle** [Cazadorsniper/PO3#222]
Pack Version: 3.0.38

Description:

Items will not transfer through an item translocator, to a basic 2x2 storage drawer, when there is a void upgrade installed.  Removing the void upgrade will immediately continue the transfer of items.

Steps to reproduce:

Add a storage crate.  Attach an item translocator to it, with a filter set to flint and gravel.  Add a 2x2 drawer, with flint and gravel in.  Set the item translocator to start pulling items from the crate.

Add a few stacks of each and notice the items transferring.  Add a void upgrade template to the 2x2 drawer, and notice that items immediately stop transferring.

Crash log (use pastebin or similar):
No crash log generated.

**Comment by Swag123Star** [comment]
hey do you know how to get a crash log?

**Comment by dbridle** [comment]
Generate a crash report when something doesn't crash? Not sure I understand Swag?

**Comment by Swag123Star** [comment]
No when a crash happens

**Comment by mFIND** [comment]
I had the same issue, nothing crashes, translocators are just not working with void upgrades...

Issue should be already known to @Drawer and @Translocator authors

@dbridle, you can bypass this problem just by adding new EMPTY and locked drawer (locked so it will remain empty). For some bizarre reason that's enough.. it's still a bug tho..

**Comment by sixlettervariables** [comment]
I'm still seeing this issue on 3.1.44 with translocators or EnderIO conduits. Item's that cannot be inserted into storage drawers with void upgrades:
- Baubles
- Conduit probe
- Fire water buckets
- Loot bags
These items can be inserted manually.

I've ensured the drawers are in the same chunk as the conduits, filters, priorities, intermediary chests, etc.

Thoughts?

**Comment by sixlettervariables** [comment]
Looks like this may be the issue: https://github.com/jaquadro/StorageDrawers/issues/722

**Comment by Cazadorsniper** [comment]
Add an empty locked drawer to the network of drawers.

**Comment by sixlettervariables** [comment]
I've tried that (both a 1x1 and a 2x2) and unfortunately that does not work. I've removed the low priority "trash" chest from the network as well, without any change.
