### ISSUE TITLE
3.0.39 Minecraft Window Wont Open

### ISSUE THREAD

**Issue by Swag123Star** [Cazadorsniper/PO3#223]
**Pack Version:**
3.0.39
**Description:**
When I click on open game on the minecraft launcher the game doesnt open but instead crashes!
**Steps to reproduce:**
Open the luancher click play, my game crashes
**Crash log (use pastebin or similar):**
https://pastebin.com/QiV90Yqn

**Comment by Cazadorsniper** [comment]
on twitchapp there is button to repair minecraft/repair profile try pressing that. Located next to the get more content button.

**Comment by Swag123Star** [comment]
Didn't work

Do i need to delete a mod? why is this only happining to me and not other poeple?

**Comment by Cazadorsniper** [comment]
try re-downloading the pack.

**Comment by Swag123Star** [comment]
I Did that already and it played but then how do i get my world in?

**Comment by Swag123Star** [comment]
So I clicked the repair button in the re installed pack and ity opened, to get my world in i have to put it in the saves folder right?

**Comment by Cazadorsniper** [comment]
yes
