### ISSUE TITLE
Epeolatry V: quest requirements

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#224]
Pack Version: 3.0.39

Description: Epeolatry V quest does not require Epeolatry IV, but Epeolatry III.

![image](https://user-images.githubusercontent.com/19508559/55178157-27b22f80-5185-11e9-9a39-6216dc36509e.png)

**Comment by PlacidK** [comment]
And Epeolatry IV requires Epeolatry IV :(

**Comment by Cazadorsniper** [comment]
Already fixed.
