### ISSUE TITLE
Builders Wands Crash Game when taken out of ProjectE Tablet

### ISSUE THREAD

**Issue by freaksdesign** [Cazadorsniper/PO3#226]
**Pack Version:**
3.0.39
**Description:**
If you have builders wands taught to your emc tablet and try to take it out and use it, it will crash your game when in hand. Has been tested with Unbreakable, Iron and Diamond wands. Same result happens if you have AE2 linked to your emc knowledge and try to use the wand from the computer.

**Steps to reproduce:**
Make ProjectE Learn Wand
Retrieve Wand from ProjectE Tablet/Table or AE2 computer that is linked to EMC
Scroll to wand so it is in your hand which should crash the client 

**Update**
Tried manually making a wand in regular crafting table and trying to use wand crashes the game.

**Crash Report**
https://pastebin.com/LNJpvBAC

**Comment by Nonsanity** [comment]
Are you trying to build with blocks that are in a Dank/Null? I found that, while builder wands will pull blocks from a Dank/Null just fine, they will crash for some block types. For me, I had BlockCraftery halfslabs in mine and the wand would crash when trying to pull them out. With no Dank/Null, the same halfslabs worked fine out of my inventory with the wands. Full-size BlockCraftery frames work fine both ways, so it seems to be specific blocks.
