### ISSUE TITLE
Server pack .39

### ISSUE THREAD

**Issue by MbTvHolyWreckingBall** [Cazadorsniper/PO3#228]
I know y'all are very busy working on the pack. Was just curious if there's an estimation of when the serverpack will be available.

**Comment by djoey123** [comment]
When it is done

**Comment by MbTvHolyWreckingBall** [comment]
No shit?! Fucking slap my tits and call me sally, I thought it'd be released before it was done solely because I asked about it.

**Comment by Cazadorsniper** [comment]
.39 won't have server files because it has too many problems that we didn't expect until it was too late so we will go right to .40 just waiting for botania to update now.

**Comment by MbTvHolyWreckingBall** [comment]
ahh okey doke
