### ISSUE TITLE
Can't find minerals in LandCraft's world

### ISSUE THREAD

**Issue by JackMeds** [Cazadorsniper/PO3#23]
**Pack Version:**
PO3-3.0.38
**Description:**
Can't find minerals in LandCraft's world
**Steps to reproduce:**
I went to lordworld and found no minerals about this mod.And I use spongeforge on my server
**Crash log:**
Game event has no log

**Comment by jag0k** [comment]
Lordcraft doesn't have a dimension, does it? (Except for the one you go to to get quests, but nothing is supposed to be minable there.)
Did you mean LandCraft?

**Comment by JackMeds** [comment]
emm，He is a portal made up of a egg

**Comment by Cazadorsniper** [comment]
twilight

**Comment by JackMeds** [comment]
> twilight

i see

**Comment by nzminecraftDOTcom** [comment]
If running spongeforge (Like most people including me) There's something in the world generator that Landcraft and Spongeforge don't agree on. See: 
https://github.com/SpongePowered/SpongeForge/issues/2597

**Comment by Quest79** [comment]
Please close this and dont use this place as a self-help repository, goto the PO3 discord if you need things answered. This is for bug reporting on understood issues.
