### ISSUE TITLE
Crafting the capturing enchant books from the mod Apotheosis

### ISSUE THREAD

**Issue by Darkarcher14** [Cazadorsniper/PO3#231]
**Pack Version:** 3.0.39

**Description:** checking to see if anyone knows why the enchant book "Capturing I to V"  from the mod apotheosis doesn't appear through the enchanting table using the tome of weaponry?

**Steps to reproduce:** place enough hell-infused bookshelves to get a level 130+ enchant and use a tome of weaponry in enchant table

**Crash log (use pastebin or similar):**

**Comment by Darkarcher14** [comment]
Also, scavenger III doesn't ever appear, i'm thinking that these certain books have been disabled?

**Comment by Cazadorsniper** [comment]
They have not been disabled.

**Comment by Darkarcher14** [comment]
strange, any idea why i couldn't get them to appear? was i doing something wrong?

**Comment by Cazadorsniper** [comment]
Probably just mod incompatibility.
