### ISSUE TITLE
Crash when u try to remove a Ender IO machine 

### ISSUE THREAD

**Issue by TheDragonMaster1** [Cazadorsniper/PO3#232]
**Pack Version:**

**Description:**Crash when u try to remove a Ender IO machine 

**Steps to reproduce:** I removed a Alloy Smelter with a yeta wrench and the pack crashed

**Crash log (use pastebin or similar):**https://pastebin.com/0ExUxdHv

**Comment by Cazadorsniper** [comment]
#216
