### ISSUE TITLE
Game crashes on launch or while loading

### ISSUE THREAD

**Issue by TheOriginalRage111** [Cazadorsniper/PO3#233]
**Pack Version:**3.0.39

**Description:**Game Crashes on launch, sometimes loads start screen but crashes on world screen

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
[Crash Log.txt](https://github.com/Cazadorsniper/PO3/files/3025046/Crash.Log.txt)

**Comment by Cazadorsniper** [comment]
maybe try using the repair minecraft/profile button on twitchapp? I don't think the pack is causing that crash.

**Comment by TheOriginalRage111** [comment]
It didn't work any other suggestions?

**Comment by nzminecraftDOTcom** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/2158104-exception_access_violation-0xc0000005-at-pc

Does that look at all similar? Perhaps you have no permission to run the game on the user account you are on?

**Comment by TheOriginalRage111** [comment]
Nope its different, and I can play other modpacks. However whenever I press play it crashes when it loads.

**Comment by nzminecraftDOTcom** [comment]
Tried removing the pack and re-installing it.

**Comment by TheOriginalRage111** [comment]
Yes, removed the pack and reinstalled, I have removed my save file (I have been playing for like a week now), I have played with my twitch settings, and I have repaired the pack. Nothing has worked so far.

**Comment by Hoojjy** [comment]
Have you tried allocating more ram for the modpack?

**Comment by TheOriginalRage111** [comment]
It is set all the way up

**Comment by TheOriginalRage111** [comment]
Update: I deleted and reinstalled the pack and got it to work for a few hours. However, when I tried to reopen the game it started crashing again.

**Comment by Draylynn** [comment]
I'd recommend updating your Java build, and running a RAM test (just to make sure your RAM isn't failing).
Intel graphics (is the driver stable and up to date)?
