### ISSUE TITLE
Unknown reason for crash

### ISSUE THREAD

**Issue by The1redstoneman** [Cazadorsniper/PO3#235]
**Pack Version:**
PO3-3.0.39	

**Steps to reproduce:**
Installed and tried to open

**Crash log (use pastebin or similar):**
[crashlog.txt](https://github.com/Cazadorsniper/PO3/files/3025720/crashlog.txt)

- [ ]

**Comment by Cazadorsniper** [comment]
Update Chancecubes or wait for new pack update.
