### ISSUE TITLE
Crafting certain items bugged

### ISSUE THREAD

**Issue by 808InsideCat** [Cazadorsniper/PO3#236]
**Pack Version:**
3.0.39
**Description:**
Trying to craft Engineer's hammer from Industrial Engineering, or basic/silver capacitors from EnderIO not working. Recipie exists in JEI, and transfers to crafting table, but there is no output.
**Steps to reproduce:**
Place items for recipie in crafting station.
**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
server?

**Comment by 808InsideCat** [comment]
Yes, on a StickyPiston Server.

**Comment by Cazadorsniper** [comment]
then you need to make sure server scripts and client scripts are the same.

**Comment by 808InsideCat** [comment]
oh, okay. I'll look into it. Thanks
