### ISSUE TITLE
Cannot craft String Mesh

### ISSUE THREAD

**Issue by DrakeOStorm** [Cazadorsniper/PO3#237]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
Server

**Description:**
Everytime I try to craft a String Mesh for one of the base quests, the output is Silk Block. JEI says the 3x3 string works for String Mesh. 

I've also searched all over for a solution to this problem, even found an earlier report which said to ensure server and client script files were the same, which I did, and still didn't work. I also completely reinstalled PO3 on my server, and that didn't work either.

**Steps to reproduce:**
Fill each spot in the 3x3 crafting table with string

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Need to make sure server and client scripts are the same. Delete the ones on the server then copy/paste client ones to the server.

**Comment by DrakeOStorm** [comment]
I did ensure they were the same, by both deleting server and copying client, and vis versa. I said that briefly in my description.

**Comment by Cazadorsniper** [comment]
Sadly that is my only solution to this problem maybe possible that the scripts didn't download completely.

**Comment by GreatSnowman** [comment]
Just to jump onto this thread, not much point in creating a duplicate thread,but this is occurring when I'm just playing single player, I got no external server to play on.

**Comment by mothbooty** [comment]
Adding to this thread since I figure it's better than making a duplicate thread. I've tried reinstalling the pack, installing older versions, then updating them to the current version, and none of these methods have fixed the problem, 3x3 string continues to craft into Erebus Silk.

**Comment by Cazadorsniper** [comment]
do you see "recipes.remove(<erebus:silk>);" at line 47 in the all_recipes.zs script?

**Comment by Cazadorsniper** [comment]
you may need to also wipe the old profile and installed a fresh up to date one and move your world over.

**Comment by mothbooty** [comment]
> 
> 
> do you see "recipes.remove(erebus:silk);" at line 47 in the all_recipes.zs script?

It's in the file, but doesn't seem to be registering on my end.

**Comment by Cazadorsniper** [comment]
then you will need to do the other suggestion.

**Comment by mothbooty** [comment]
> 
> 
> then you will need to do the other suggestion.

I've already tried doing that, it's stated in my original post in this thread.

**Comment by DrakeOStorm** [comment]
I figured out why my server doesn't work, I just don't know how to fix it. The server host I'm using, Nitro, is deleting all that data when I start the server. 

I move the files from client to the server as suggested, check to see the file is fine. Once I start the server and check the file again, it removed all the changes I made.

**Comment by Cazadorsniper** [comment]
That is between you and Nitro then.
