### ISSUE TITLE
Hunting Dimension Quest not completing

### ISSUE THREAD

**Issue by BullZEye0506** [Cazadorsniper/PO3#239]
**Pack Version: 3.0.39**
**Singleplayer, Multiplayer, or LAN?: Single Player**

**Description: I'm sorry, I saw this issue reported earlier, but it did not have a solution. When creating the hunting dimension frames, the quest does not register as complete. Performed the task twice, built the portal, activated it, and went into the hunting dimension and returned, after that I attempted the "Detect/Submit" button, nothing worked.**

**Steps to reproduce: creating 4 recipes of frames using standard arrows and oak log blocks**

**Crash log (use pastebin or similar): N/A**

**Comment by Cazadorsniper** [comment]
Probably because nbt data, maybe.

**Comment by BullZEye0506** [comment]
Sorry Cazador, I'm a super newbie at the intricacies of modded minecraft. You may absolutely be right. Is there a fix/work around for it? P.S. I appreciate your hard work. This modpack is INSANELY good.

**Comment by Cazadorsniper** [comment]
will need a fix on my side , I will attempt to fix it no guarantees though.

**Comment by BullZEye0506** [comment]
All good. Press on friend
