### ISSUE TITLE
my server is very laggy

### ISSUE THREAD

**Issue by JackMeds** [Cazadorsniper/PO3#24]
**Pack Version:**
PO3-3.0.38
**Description:**
TPS is less than 10
**Steps to reproduce:**
Use sponge'spark to get timings
**Crash log:**
https://sparkprofiler.github.io/#BW92HpL3yt

**Comment by nzminecraftDOTcom** [comment]
Specifications of the server?
Ram allocations
CPU clock speed
CPU cores allocated
What are you storing the files on - SSD HDD etc
How many processors are you using and are you using one or both etc.

**Comment by JackMeds** [comment]
> Specifications of the server?
Intel(R) Xeon(R) Gold 6154 CPU @ 3.10GHz
> Ram allocations
10G
> CPU clock speed
3.1Ghz
> CPU cores allocated
6
> What are you storing the files on - SSD HDD etc
ssd
> How many processors are you using and are you using one or both etc
one

**Comment by nzminecraftDOTcom** [comment]
How many players and do you have a tick monitoring plugin/mod such as Tickprofiler or Lag goggles to see what is causing the issues?

**Comment by JackMeds** [comment]
> How many players and do you have a tick monitoring plugin/mod such as Tickprofiler or Lag goggles to see what is causing the issues?

12

**Comment by nzminecraftDOTcom** [comment]
Sorry, edited the comment and you didn't see it, reposting it here:

Running a server with only 1 core dedicated and I only get low TPS issues when people sit there at their bases and have excessive items left on the ground. Sounds like you may not be using all the cores? Are you able to view a command prompt/utilization graph etc.

**Comment by JackMeds** [comment]
![image](https://user-images.githubusercontent.com/38741783/53402603-024ace00-39ed-11e9-94a6-86bedea0957a.png)

**Comment by nzminecraftDOTcom** [comment]
Looks like a lot of it is sitting on one core, how have you told it to use 6?

**Comment by nzminecraftDOTcom** [comment]
[img]https://i.imgur.com/igsa6Vr.png[/img]
I'd be expecting something more like that with multiple cores being utilised

**Comment by nzminecraftDOTcom** [comment]
What Java arguments are you running in your launch file?

**Comment by JackMeds** [comment]
java -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=60 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -XX:+UseLargePagesInMetaspace -jar forge-1.12.2-14.23.5.2808-universal.jar nogui

**Comment by nzminecraftDOTcom** [comment]
Try add -XX:ParallelGCThreads=6

**Comment by JackMeds** [comment]
![image](https://user-images.githubusercontent.com/38741783/53404526-d0d40180-39f0-11e9-9afd-e1fcb61ceba1.png)

**Comment by nzminecraftDOTcom** [comment]
Presuming that screenshot means that didn't solve the issue. 
On to the next major factor of laggy servers.
How many loaded chunks, do you have chunk loading enabled.

**Comment by Pertzaa** [comment]
Server files downloaded from curse where very laggy for me also, but i tried ones from here and it worked perfectly: https://www.reddit.com/r/feedthebeast/comments/ama4z9/project_ozone_3_server_files/efm0m9o/

**Comment by nzminecraftDOTcom** [comment]
Just occurred to me, have you turned off blood moons, they kill servers very fast.
