### ISSUE TITLE
[3.0.39] Wireless RF transmitter not working with EnderIO machines

### ISSUE THREAD

**Issue by DefectiveBunny** [Cazadorsniper/PO3#240]
**Pack Version:** 3.0.39
**Singleplayer**

**Description:**
When trying to use wireless RF transmitters (Extra Utilities 2) with enderIO machines like the SAG mill or alloy smelter, it wont recognize the machine. It works just fine with other non enderIO machines, or if connected to energy conduits/fluxducts.

**Steps to reproduce:**
- Use lava dynamo to make RF and water mills to make GP
- Put RF into a basic capacitor bank (enderIO)
- Put a wireless RF battery (Extra Utilities 2) on top, with the bank output into the battery
- Put down a wireless RF transmitter next to enderIO machine

![2019-03-31_13 49 47](https://user-images.githubusercontent.com/49119757/55289126-713b8e00-53c2-11e9-905b-354c50769765.png)
![2019-03-31_13 50 00](https://user-images.githubusercontent.com/49119757/55289127-713b8e00-53c2-11e9-8d70-08c529a92910.png)
![2019-03-31_13 54 38](https://user-images.githubusercontent.com/49119757/55289128-713b8e00-53c2-11e9-9343-a03aa3d62f0b.png)

**Crash log (use pastebin or similar):**
No crash log

**Comment by Cazadorsniper** [comment]
maybe have the capacitor push power into the wireless fe transmitter.

**Comment by Cazadorsniper** [comment]
could be possible that ExU2 transmitters aren't compatible with Ender IO machines.
