### ISSUE TITLE
duplication glitch using bag opener next to crafting station. 

### ISSUE THREAD

**Issue by Skrrtle** [Cazadorsniper/PO3#241]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**singleplayer(multiplayer and lan unkown but im pretty sure it will work.)

**Description:**Using the bag opener next to a crafting station when having a full inventory and placing a recipe with an item in the crafting table by shift clicking it in with jei it moves the item from the crafting station into the top slot of the bag opener which infinitely duplicates it

**Steps to reproduce:** 1. expensive item in any slot of crafting station.(with bag opener to the side
2. shift click a recipe into the crafting station with a full inventory (using a block recipe makes this easiest e.g compressed cobblestone) as long as the recipe uses a slot that the item you want to dupe is in itll work.
3. done. item moves into the top slot of the bag opener and it just keeps "opening" the item into the bottom slots of it... kind of op and too easy... this duplicates items very very quickly.

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
should be fixed next update since TConstruct just updated.
