### ISSUE TITLE
Power storage only goes to 2.14 Billion, then resets

### ISSUE THREAD

**Issue by DriftinFool** [Cazadorsniper/PO3#243]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:** After building a tier7 Draconic energy core, I noticed it never seem to fill up. After watching it , I found that the moment the core gets more than 2,147,483,647, it discharges almost instantly then starts refilling from zero. I've tried the tier 6 energy core as well and had the same issue. After looking for solutions with no luck, I just built an infinite capacitor from Overloaded. It does the same exact thing. On both the infinite capacitor and Draconic energy pylons, WAILA shows them as having the 2.147 billion RF amount as their max RF storage. Whenever they hit that mark, they reset to zero stored RF.

**Steps to reproduce:** Tried tier 6 and 7 Draconic core as well as Overloaded infinite capacitor with the same outcome. I was feeding 109k RF into the energy pylon with Melodic conduits from Ender IO. The power was coming from a mekanism steam turbine. The only connection to the output energy pylon was directly into a Random things spectre energy injector. I disconnected for the sake of testing, and even with no output connected, the power just disappeared and reset every time it hits that number. The infinite capacitor was alos hooked up the same way with no output and still has the issue. 

**Crash log (use pastebin or similar):** No crash log available.

**Comment by DriftinFool** [comment]
[url=https://imgur.com/4nOQJ6J][img]http://i.imgur.com/4nOQJ6J.png[/img][/url]
Shows the energy core just before it resets.
[url=https://imgur.com/fe8VKEb][img]http://i.imgur.com/fe8VKEb.png[/img][/url]
The energy core discharging after it hits the 2.14 billion amount
[url=https://imgur.com/7dkNzcy][img]http://i.imgur.com/7dkNzcy.png[/img][/url]
Shows the infinite capacitor also resetting at the 2.14 billion mark
[url=https://imgur.com/i7yg3fv][img]http://i.imgur.com/i7yg3fv.png[/img][/url]
What WAILA shows for the max amount of RF. The same value that causes the, both to reset back to zero

**Comment by Cazadorsniper** [comment]
can you give me the latest.log when it was resetting.

**Comment by mFIND** [comment]
Really looks like 2^31 :D

**Comment by Nonsanity** [comment]
Sounds like the mod authors didn’t add any tests for integer roll-over.

Pseudocode: (If adding X would result in the value becoming less than what it currently is, then instead set the value to its maximum.)

**Comment by mFIND** [comment]
And in addition to that, the value is not unsigned.. however I wouldn't think that the problem is ACTUALLY with mass power storage, I think it's more of a problem with power storage controlers from other mods (RFTools, Overloaded) (From screenshots).. Unless of course those mods do something weird and somehow force storage to overwrite its energy stored variable with incorrect value...

**Comment by Cazadorsniper** [comment]
So far we have found that it was Random Things wireless power transfer doing it some how.

**Comment by DriftinFool** [comment]
I'll remove the wireless power from the main storage and see what happens. I'm going to try putting a buffer between the mass storage and the wireless controller, so it sees a smaller max RF. Maybe that could be used as a work around.

**Comment by DriftinFool** [comment]
Thank you so much for your help. Simply placing a Thermal foundation energy cell between the Draconic energy pylon and the spectre energy injector allowed it to pass the 2.14 billion mark.
