### ISSUE TITLE
Growth Crystal recipe doesn't work

### ISSUE THREAD

**Issue by grantopher** [Cazadorsniper/PO3#244]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** 
Multiplayer
**Description:**
The crafting recipe for 1st tier Growth Crystal from Tiny Progressions does not appear to work.
**Steps to reproduce:**
Here is the shown recipe in JEI:
![image](https://user-images.githubusercontent.com/5903084/55294791-020e6b80-53bb-11e9-9ea2-bc729dd3dafc.png)
Recipe does not work (using vanilla crafting table, Tinker's crafting table, and AE2 crafting table):
![image](https://user-images.githubusercontent.com/5903084/55294800-1d797680-53bb-11e9-8d3e-d0cf0093d135.png)

I've crafted this before in an earlier version of the pack.
**Crash log (use pastebin or similar):**
N/A

**Comment by Cazadorsniper** [comment]
that means the scripts didn't download completely, reinstall the pack.

**Comment by grantopher** [comment]
Could it possibly be something to do with the server files? I've reinstalled the pack several times now on my client and on my server and none of the custom recipes are working. Reverting to 3.0.38 fixed the issue.
