### ISSUE TITLE
YABBA and AE

### ISSUE THREAD

**Issue by KnightofNight12** [Cazadorsniper/PO3#245]
**Pack Version:** 3.0.38 (have yet to update due to the removal of anti-barrels, sorry if this issue has already been fixed)
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Empty YABBA barrels are automatically filled with items despite being locked when connected to an ME system via storage bus.

**Steps to reproduce:** Set up some YABBA barrels (mine had infinite storage), lock the barrels, and have an item barrel connector connected to an ME system via a storage bus. When you put items into the system (via both a crafting terminal and wireless crafting terminal) they go into the barrels despite the lock. I originally had no priority on the connector (but I also didn't have a priority on anything else in the system) and the issue was present; when I increased the priority, the issue persisted.

**Crash log (use pastebin or similar):** N/A

**Comment by Mitsuma** [comment]
Not a direct solution but I would set the ME Storage Bus to only allow one time, the item you want in there. 
Easiest way is to put the item in and then press the 2nd button top left to "format" the Storage Bus to only allow the current content in there.

**Comment by Nonsanity** [comment]
If putting a hopper on the barrel controller and feeding it items that way does the same thing, then it’s an issue with the barrel mod itself.
