### ISSUE TITLE
Server not using the alocated RAM

### ISSUE THREAD

**Issue by olle-pojk** [Cazadorsniper/PO3#250]
**Pack Version:**
3.0.38
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I downloaded the server files and launched the server from the forge-2808. After a long time of initializing the server allowed me to connect. Once in game i could break blocks just fine but throwing items, punching mobs and flying in creative mode all happend with delay. i got the "warning. Cant keep up" messages as well so i drew the conclution to try and give the server more RAM by making a .bat file with the following code;

java -Xms6g -Xmx6g -jar forge-2808.jar

When executed. the cmd window launches the server yet the issue with lag presists. in the memory used tab it says that its only using 1200-1500 mb and that like 80% is free. 
**Steps to reproduce:**
Launching the server with the .bat file as well as the java one
**Crash log (use pastebin or similar):**
Game dosnt crash

**Comment by nzminecraftDOTcom** [comment]
It only uses as much as it needs and won't use more than required. Allocated, yes. Used, no.
Think of it like a table. The whole table is your allocated ram to the server. You put some boxes on the table, that is what the server is using, however you still have space on the table for more boxes should the server need to use more.
What are the other specifications of the machine the server is running on
Ram speed
CPU clock speed (GHz)
CPU model/make

**Comment by nzminecraftDOTcom** [comment]
Also, Xms at 6g is probably also causing your issues. You don't need it anywhere near that high. 512M or 1G would be way more than enough.
