### ISSUE TITLE
PO3 3.0.39 crash on world load

### ISSUE THREAD

**Issue by Batou222** [Cazadorsniper/PO3#251]
Pack Version: 3.0.39

Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Pack loads fine, about 50% of the time it crashes on loading the world

Steps to reproduce: Load World, in this case the questbook sound played but that is not the case on other crashes.

Crash log (use pastebin or similar): https://pastebin.com/ZDcAvfXv

**Comment by Batou222** [comment]
I've now tested loading a new world first successfully then my world and it crashes. However my existing world will load eventually, so not sure what in it is causing the crash..?

**Comment by Cazadorsniper** [comment]
at com.rwtema.extrautils2.blocks.BlockSoundMuffler.supressSound(BlockSoundMuffler.java:59)
 Block coordinates: World: (-116,84,105)

**Comment by Batou222** [comment]
![2019-04-03_13 20 47](https://user-images.githubusercontent.com/44129675/55448436-793e3c80-5613-11e9-934c-dfd1a5e70954.png)

So I saw that in the error log, but I hadn't previously used Sound Mufflers. I do hear a sound play before the crash, often it is a splash potion sound for what ever reason. I checked -116,84,105 and can see the above AE cable. I've broken and replaced it so that hopefully the save updates. Will report back.

**Comment by Batou222** [comment]
Still the same issue, pointing to the same block which is an AE cable??
com.rwtema.extrautils2.blocks.BlockSoundMuffler.supressSound
Block coordinates: World: -116,83,105
https://pastebin.com/3cYTwUBa

**Comment by Batou222** [comment]
Another 6 crashes today, took me an hour to get the save to load, again references:
com.rwtema.extrautils2.blocks.BlockSoundMuffler.supressSound(BlockSoundMuffler.java:59)
Block coordinates: World: (-114,78,95)
Again it is an AE fluix cable at that location
Do I need to bug this with RWTema?

**Comment by Cazadorsniper** [comment]
Very likely, wouldn't be surprised if its already there.

**Comment by Batou222** [comment]
Done, yes it is! https://github.com/rwtema/Extra-Utilities-2-Source/issues/275

**Comment by Batou222** [comment]
Worked around the issue with Extra Utilities by disabling the Sound Muffler in the Extra Utils config file
