### ISSUE TITLE
(3.0.39) Crash upon entering the nether

### ISSUE THREAD

**Issue by Khranos** [Cazadorsniper/PO3#252]
**Pack Version:**
3.0.39

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Whenever a player falls off their island and enters the nether, the console starts spitting out tons of red errors. They then start to lag out, and it causes lots of server lag. More often than not it'll crash the server and requires I delete their playerdata as when they spawn in, it proceeds to repeat the process.

I understand this may be an issue with my server's implementation, but on the off-chance it's pack related, I'd love to see it solved.

I did end up deleting chanceblocks because it was causing issues with starting the server, so maybe that's related?

**Steps to reproduce:**
Jump off an island in a multiplayer world, proceed to lag the server out in the nether and ruin your playerdata.

**Crash log (use pastebin or similar):**
https://pastebin.com/8QPiTT3s

**Comment by Cazadorsniper** [comment]
Turn max-tick-time to -1 in the server.properties.

**Comment by Khranos** [comment]
This completely solved the issue it would appear. Thanks for such a fast response, aside from this issue, been loving the pack so far.

**Comment by Khranos** [comment]
Sadly, it appears this is still causing crashing. I personally am able to fall and enter the nether without crashing (even with other people on the server), but whenever anybody else falls, it still ends up crashing. It ends up stating "(player) joining dimension -1"like 10 times a second until the server keeps trying to catch up, until it appears it runs out of memory and crashes. (the paging file is too small)

Running the server on a near-dedicated PC with an i7-8700k with 2gb min/14gb max of allotted ram, so I'd have to assume this is causing some sort of data leak? Have attempted reinstalling my client, the server's client, and even some of the other player's clients multiple times. The only mod I've removed/tampered is ChanceCubes, which was required for the server to run in the first place. (also see: issue #209)

Here's the memory crash log, hopefully it helps something or at least sheds light on the potential issue: https://pastebin.com/pV7amd5a .

**Comment by Cazadorsniper** [comment]
did you try any of the presented solutions? `# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.`

**Comment by NLBlacky** [comment]
We're having the same issue but still haven't been able to find the solution for it. If anyone has a fix, please tell us here! Thank you!

**Comment by KialDaDial** [comment]
This is occurring for me in 3.0.40. On a local sever when entering the nether by falling into the void sometimes the teleport spawns the player under the nether, causing the sever to spawn them again but it rarely tries to go above a negative y value. this causes the player to reload the nether over and over until the server can't respond anymore.

**Comment by Cazadorsniper** [comment]
see #332
