### ISSUE TITLE
OreExcavation not working "Fixed"

### ISSUE THREAD

**Issue by Hoojjy** [Cazadorsniper/PO3#253]
**Project Ozone 3 A New Way Forward**
**Singleplayer**

Started a new singleplayer playthrough and the OreExcavation mod isn't  "excavating anything". I changed the default button that it was bound to, now when i "shift press it", It shows the excavation shape in chat box, but that's all it does.

![Capture](https://user-images.githubusercontent.com/49187006/55386628-c40d6680-54e4-11e9-8ee9-621b0bf91e53.PNG)
![Capture2](https://user-images.githubusercontent.com/49187006/55386630-c40d6680-54e4-11e9-8ee1-8d2b6be0f89f.PNG)
![Capture3](https://user-images.githubusercontent.com/49187006/55386631-c4a5fd00-54e4-11e9-8261-6dabba58866e.PNG)
![Capture4](https://user-images.githubusercontent.com/49187006/55386861-3c742780-54e5-11e9-9902-078d0b53d119.PNG)

**Comment by Cazadorsniper** [comment]
try binding it to something else.

**Comment by Hoojjy** [comment]
> try binding it to something else.

Already tried

**Comment by Cazadorsniper** [comment]
have you tried pressing and holding the button to excavate?

**Comment by Hoojjy** [comment]
> have you tried pressing and holding the button to excavate?

Yes, doesn't help

**Comment by Hoojjy** [comment]
Just got it working by binding it back to "GRAVE".
