### ISSUE TITLE
Crashes when loading

### ISSUE THREAD

**Issue by conor1233333** [Cazadorsniper/PO3#254]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**
when i press play it starts downloading mods then crashes
**Steps to reproduce:**

**Crash log (https://pastebin.com/E8grgJge):**

**Comment by Cazadorsniper** [comment]
PO3 is not a small pack, not enough ram.

**Comment by Lemon665** [comment]
I have 8GB of Ram is that enough?
