### ISSUE TITLE
wheat exception error? 

### ISSUE THREAD

**Issue by ravclaw** [Cazadorsniper/PO3#256]
**Pack Version:**
3.0.39
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
After replacing the normal configs with the PO3 override server configs, Players joining in will get kicked and given a "internal excpetion error" involving wheat Id's
**Steps to reproduce:**
Update configs using PO3 override server configs.
**Crash log (use pastebin or similar):**
https://pastebin.com/9WKYg27p

![Screenshot (14)](https://user-images.githubusercontent.com/49217398/55446836-39754780-5576-11e9-8e55-2681b96bccd3.png)

**Comment by Cazadorsniper** [comment]
Update server configs with the client configs.

**Comment by ravclaw** [comment]
Thank you for the fast reply. Now it's back to the crafting error. As in, can't make silk mesh or the inscription tile so far. Has there been a fix found for this? I completely redid the world and server files and made sure the client and server configs were the same.

**Comment by Cazadorsniper** [comment]
Do the same with scripts.
