### ISSUE TITLE
Woot and Demonic Will Quests can't be accepted

### ISSUE THREAD

**Issue by freaksdesign** [Cazadorsniper/PO3#258]
Pack Version: Singleplayer, Multiplayer, or LAN?:
3.0.39 SP & Multiplayer
Description:
Woot Multi-Block #888 and Demonic Will #924 can not be accepted. NBT tags are applied when creating Factory Controller and Killing mobs to receive Raw Demonic will, better questing is not set to ignore nbt tags.

Manually setting quest to ignore nbt tags allowed the quests to be accepted.

**Comment by 123zane321** [comment]
Can confirm this, the Woot quest that requires a bunch of blocks from the multiblock structure (including the factory controller) isn't completing, and I've tried making the controller with several different mob shards.
