### ISSUE TITLE
Cannot Find addon Dependency 74610

### ISSUE THREAD

**Issue by Boflar** [Cazadorsniper/PO3#262]
I've been trying to install since yesterday, it gave me a different error yesterday but someone already reported it (Object reference not set to an instance of an object) and then I tried today but it keeps giving me this error.

![assf](https://user-images.githubusercontent.com/49245439/55493676-632a7f00-5607-11e9-9465-cdb87713c850.PNG)

**Comment by Cazadorsniper** [comment]
That is twitchapp doing that, contact them for support.
