### ISSUE TITLE
3.0.39 ChanceCube causes server crash on load.

### ISSUE THREAD

**Issue by Mitsuma** [Cazadorsniper/PO3#263]
**Pack Version:**
3.0.39

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Just wanted to let you guys know that the current version of ChanceCubes (1.12.2-4.0.0.268) in the 3.0.39 pack has an issue if you try to run this pack on a server.

The fix for this is to update ChanceCubes to the latest version, which is 1.12.2-4.0.0.270 (as of writing this).
The error was fixed in either 269 or 270, not sure.

I'm not sure how much of a priority this is, as there is no official server files for the current version anyways but other people might find this.

**Comment by Cazadorsniper** [comment]
You talking about the issue that I reported to the dev a while ago and he has then fixed it and we're waiting on another mod to update to fix other bugs?

**Comment by Mitsuma** [comment]
Not sure, didn't look to deep into besides looking if there was a similar report here already. 
Just wanted to report that an updated version of ChanceCubes fixes an issue with running it on a Server.

If that crash was already know and planned to be fixed then just disregard this report.
