### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by iTryFrosty** [Cazadorsniper/PO3#266]
**Pack Version:**latest beta 
**Singleplayer**

**Description:**
It’s not your normal skyblock it’s loading a legit world with actual structures trees animals..etc

**Comment by iTryFrosty** [comment]
I’ve downloaded previous versions and same thing has happened maybe it’s the twitch launcher?

**Comment by Cazadorsniper** [comment]
latest beta is not a version. You need to choose the garden of glass world type.

**Comment by legendaryA1** [comment]
or sky islands in advanced options when making a world
