### ISSUE TITLE
crash and continual restart 

### ISSUE THREAD

**Issue by VaporBeast88** [Cazadorsniper/PO3#268]
**3.0.38**
**Multiplayer server:**

Don't know what to do Please help.
also have add refined storage which never gave me any issues before.
Crash Report
https://pastebin.com/EifMkPPf

I have also removed the world and loaded a new one and it worked fine put the old world back in and it crashes again

**Comment by VaporBeast88** [comment]
ok thank you very much for the help

**Comment by VaporBeast88** [comment]
its not like people don't add things that they think would make the pack better.

**Comment by Cazadorsniper** [comment]
Once you change something, it becomes Project Ozone "whatever" edition (in your case Project Ozone 3 VaporBeast88 Edition) therefore its no longer "Project Ozone 3: A New Way Forward" made by Team Ozone.

You will have to troubleshoot yourself or ask somewhere else. If I were to give you a solution it would be to remove Refine Storage entirely.

**Comment by VaporBeast88** [comment]
thank you for the response that was all I was looking for instead of getting ignored. I did read through it again and finally figured out the issue.
