### ISSUE TITLE
[PO3] Crash while loading a map

### ISSUE THREAD

**Issue by Driiv** [Cazadorsniper/PO3#269]
Hello guys,

I am doing this post knowing that I am probably not the only one with this problem and having already tried the majority of possible things to fix the problem.
I also made a post on a big forum where many people have already tried to help me, unfortunately without success.

The problem occurs with the latest version of Project Ozone 3, which is 3.0.39.
The game crash systematically when loading the map, after the "question of backup", no matter the answer given, and no matter the choice of generation.

I tried with 6GB, 8GB, 10GB and the maximum: 12GB of RAM.
Java is up to date, Twitch too, and modpack too.

**Screen of "question of backup":** [click here](https://image.noelshack.com/fichiers/2019/14/4/1554399903-crash.png)
**Crash report:** https://paste.ubuntu.com/p/jQgY9QShHs/

Thank you for your answers, and sorry if the question has already been asked.

**Comment by Cazadorsniper** [comment]
Did you change any configs or added/removed any mods?
Is this on a server or single-player?

**Comment by Driiv** [comment]
No, I didn't change anything, no configuration, or add any mods, I only wanted to play the third edition of my favorite modpack

**Comment by Cazadorsniper** [comment]
Try installing a separate instance of the pack then moving your world over.

**Comment by Driiv** [comment]
Ok, I try that as soon as possible.

But I admit I don't know how to do it, do I have to create the modpack by myself ?Moving forge first then all the folders in a brand new Minecraft vanilla profile ? 
Because I don't have a world to move because I haven't been able to play on this modpack.

**Comment by Cazadorsniper** [comment]
nope just install the pack again the same way you did the first time.

**Comment by Driiv** [comment]
Oh ! Ok, i will try that when Im come back at home and I'll let you know
