### ISSUE TITLE
[Suggestion] Pressure pipes

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Cazadorsniper/PO3#270]
it will be really useful for Mekanism reactor and turbine but also useful for others machines that need a huge input rate.

I hope i can actually suggest mods and sorry if it's not allowed :/

**Comment by Cazadorsniper** [comment]
You can add it in your instance, it will not be in the pack itself.

**Comment by ReiDaTecnologia** [comment]
sad because i would like it in the servers that i play but it's fine. But it's still a good suggestion imo :D
