### ISSUE TITLE
Need help getting Garden of Glass

### ISSUE THREAD

**Issue by weird272** [Cazadorsniper/PO3#271]
**Pack Version:**.
.38
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I'm having problems getting my world to become the Garden of Glass. I have my server properties right here, it would be nice if anyone could help.

#Minecraft server properties
#Fri Apr 05 21:01:33 UTC 2019
spawn-protection=16
max-tick-time=60000
generator-settings={"profile"\:"nodamage"}
force-gamemode=false
allow-nether=true
gamemode=0
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=botania-skyblock
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
use-native-transport=true
motd=A Minecraft Server
enable-rcon=false

**Steps to reproduce:**

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
1. max-tick-time=-1
2. Make sure you delete the world folder, then try again.

**Comment by weird272** [comment]
yes but even when i load up with those server properties it just loads me on the overworld

**Comment by Cazadorsniper** [comment]
how about generating a new server.properties.

**Comment by Gurkanan** [comment]
did you start the server with forge.jar(or i bat file linked to it) or mincraft_server.jar. the minecraft one will generate a vanilla world. also if you have others on the server i would suggest getting rid of spawn protection.
