### ISSUE TITLE
Error when trying to joining PO3 server

### ISSUE THREAD

**Issue by TVachal** [Cazadorsniper/PO3#272]
Version 3.0.38

Running PO3 on a hosted server for the last month or so without problem.  Now any players that try to join the server get the same error code and it returns to server select screen.  This issue started 2 days ago.  I have tried reloading the client and even started the server from scratch and uploaded world file. 
 World can be loaded in single player and runs fine.  Hopefully someone has a solution because right now I'm being told it is corrupted and a world reset.  My buddies and I have too much time sunk into this to restart.  Thanks in advance.

Crash log: https://pastebin.com/embed_js/wWjfd7VS

**Comment by nzminecraftDOTcom** [comment]
Are both server and client;
mod lists
configs
scripts

all the same?
The quick look through the log i saw an NBT data issue. Someone may have a corrupt item in their inventory making it impossible to log in. Check their player data in an NBT editor.
