### ISSUE TITLE
cant do abyssal craft in void worlds

### ISSUE THREAD

**Issue by legendaryA1** [Cazadorsniper/PO3#273]
Pack Version: latest
Singleplayer

so in void worlds and partal void worlds you cant do byssal craft cause you cant get the ores or statues you need. in the ky islands world type you can get the ores and statues but you still cant get liquid antimatter without cheating it in. could you make a crafting recipie for all of theres for a graden of glass run too? such as letting the laser mine the ores needed for the mod  know anti cows can spawn but this is very very rare (as well as a ritual to get it but you need antimatter for that). and you have to keep murding all the cows and animals that do spawn to get them. but then there is still the issue with the colium ore not being craftable or any way to get it other then the crystalizer with is late game abssal craft and need the ore to get to it.

**Comment by Cazadorsniper** [comment]
Latest isn't a pack version.
Ores: Landia
Statues: Can make biomass
Antimatter: Check pneumaticcraft pressure chamber recipes

**Comment by legendaryA1** [comment]
ah i missed the pneumaticcraft recipe but ive been exploring landia for a while and never found any. which biome and level do they spawn at?

**Comment by Cazadorsniper** [comment]
Should spawn anywhere in Landia can also try the deep dark.

**Comment by legendaryA1** [comment]
alright thank you
