### ISSUE TITLE
Trying to automate Lordcraft has broken my save

### ISSUE THREAD

**Issue by Jloenw** [Cazadorsniper/PO3#274]
Pack Version: 3.0.38
Singleplayer

Description:

Placing a mechanical user, with a dense (earth) crystal in it, next to a void interface to attempt to automate mana cause my game to crash and I can no longer load it.

Steps to reproduce:

Place a mechanical user with a dense crystal in it pointing at a void interface.
Have a earth siphon in the void interface so it accepts earth mana.
Set the mechanical user to activate block with item and the game freezes in a few moments.

Crash log (use pastebin or similar):
https://pastebin.com/gMCgc3Ea

**Comment by Cazadorsniper** [comment]
Solution: Load the world from a backup and don't try to automate the void interface.

**Comment by Jloenw** [comment]
solution: don't do that .

thanks
