### ISSUE TITLE
Metallurgic Infuser quest not completing

### ISSUE THREAD

**Issue by Camatin** [Cazadorsniper/PO3#275]
Pack Version: 3.0.39
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: When holding a Matallurgic Infuser from Mekanism in the player's inventory, the quest book will not detect it as a completion for the quest.

Steps to reproduce: Have the Metallurgic quest unlocked under Tau, craft a Metallurgic Infuser, attempt to complete the quest

There is another bug report on it, where it says fixed, but I still cant complete it. I have tryed to press Detect / Submit too, but nothing happens and Have made 5 so fare, and realy dont need any more of them.

**Comment by L0af** [comment]
seems to be a problem with the face that ignoreNBT is off on this quest, when it should be on, other quests might have the same problem as well
