### ISSUE TITLE
Quests not showing in SMP

### ISSUE THREAD

**Issue by KouyaAo** [Cazadorsniper/PO3#276]
**3.0.38:**
**Multiplayer:**

**I am trying to set up a server for me and my friends to play. I have gotten the server to work and they can join, however the quests are not working. The quest book is completely blank. I cant use any of the commands that the guide tells me to use either. Have I missed something setting the server up? The server version is 3.0.38 as well:**
![2019-04-07_12 48 48](https://user-images.githubusercontent.com/49365128/55683115-00512480-5934-11e9-925a-0f5f25a2e62f.png)

Many thanks for any help.

**Comment by Cazadorsniper** [comment]
/bq_admin default load

After that you need to manually complete the quests you already did.

**Comment by KouyaAo** [comment]
Hi, thanks for the quick reply.

I have just tried that and it comes up with Unknown command. Try /help for a list of commands.
![2019-04-07_22 01 23](https://user-images.githubusercontent.com/49365128/55689786-c5291280-5980-11e9-8bed-700a6f7927f5.png)

**Comment by Cazadorsniper** [comment]
that means you started the server with minecraft.jar when you need to start it with forge.jar.

**Comment by KouyaAo** [comment]
Ah! Thank you very much, everything seems to be working. 
Really appreciate the help and the quick replies! I'm looking forward to playing this modpack with some friends.
