### ISSUE TITLE
Industrial foregoing harvester throws off item translocator when paused

### ISSUE THREAD

**Issue by BFTB** [Cazadorsniper/PO3#278]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
Industrial Foregoing harvester turns item translocator into entity when paused. (Throws item translocator off of machine)
**Steps to reproduce:**
1. Place item translocator onto fully charged Industrial Foregoing harvester
2. Pause Industrial foregoing harvester
**Crash log (use pastebin or similar):**

**Comment by Nonsanity** [comment]
It is a “feature” of that mod that, when paused, the machines stop registering their inputs and outputs. This breaks a number of item transport mods, but would need to be addressed by the mod author. I think it was done to prevent items from continuing to enter when the machine was paused. It would be better, however, if they just act like a furnace that’s out of fuel—no work, but items can still flow in and out as usual.

**Comment by BFTB** [comment]
Thank you for the clarification
