### ISSUE TITLE
Early game duplicate anything feature

### ISSUE THREAD

**Issue by Nonsanity** [Cazadorsniper/PO3#281]
**Pack Version:** 3.0.38
**Singleplayer, Multiplayer, or LAN?:** Any

**Description:** There is a fairly early-game (power, some machines) way to duplicate anything without too much effort. It’s not due to a bug in a particular mod, it’s more of an unintended feature, and it can be disabled with some config changes, though at a cost of a loss of some flexibility in other areas of the pack. I’m hesitant to post it publicly as I haven’t seen any mention of it in my google searches, though I’m sure it’s out there.

There is a known late-game “duplicate anything” feature in this pack, but there are gates in place that keep it from being used too early. (Though many would argue that any high-volume duplication without an equally high cost is still a serious balance problem, even late-game.) This could also be disabled with config changes, though again with a significant change to how the pack has been played.

**Steps to reproduce: REDACTED**
**Crash log (use pastebin or similar):** N/A

**Comment by Cazadorsniper** [comment]
Gonna need details.

**Comment by Nonsanity** [comment]
It’s pretty simple. Take a tame llama, slap it with a chest, put your items to duplicate in it, poke-ball it, and pop it in a mob duplicator set to exact copy. If the item is an infinity barrel packed with emerald blocks... well, it’s a bit silly. Imagine the EMC shenanigans.

Later, with the animation wand, people can do the same trick with animated chests. But llamas allow for cloning items as soon as you can make the mob duplicator. It breaks so many aspects of the pack—like, dupping RAK?

Turning off exact copy in the Industrial Foregoing config will prevent this, but it will also prevent all animated blocks from working in it, as well as things like wither skeletons—which would default to normal skeletons. I personally use the exact mode to duplicate “ready” fluid cows, so that would go away too.

I suggest anyone running a public server, at the very least, should turn it off. Whether it should get turned off in the pack is up to you. I just wanted to report it.

**Comment by Cazadorsniper** [comment]
Can you try this again in 3.0.39?

**Comment by Nonsanity** [comment]
I see that the llama is blacklisted in 3.0.39, as is donkey. Good, good. :)

I’m guessing the wand animated chests will still work since they are endgame, or are all animated containers blocked too?

**Comment by Cazadorsniper** [comment]
I will have to find out which are blacklisted

**Comment by Cazadorsniper** [comment]
I blocked zombies too

**Comment by BlacklightsC** [comment]
Some of our server players have found the same problem. I think it's the cause of the attack by voidcraft:herobrine. (The player died in the phase 3)
Sometimes that will happen, but it has already happened to some users.
I did blacklist all the voidcraft entities and am now monitoring them.

**Comment by Cazadorsniper** [comment]
What?

**Comment by PraiseSatan** [comment]
I thought I should comment here as it is the same issue.
You currently don't have zombie villagers in the blacklist, so if you can find a zombie villager that can pick up items then you can duplicate any item with it.

**Comment by Cazadorsniper** [comment]
I know, X33N told me.

**Comment by SextupleTap** [comment]
I would like to bring further attention to this as the same things can be done with Husks and the Dweller mob from Quark and if you decide to update Quark in the next release(s) beyond 3.0.40 then you'll have to blacklist the "Stonelings" as well, which when tamed can hold any item you want it to hold.

Also it would be worth mentioning that I read somewhere that wither skeletons can also spawn with the "CanPickUpLoot:1b" nbt tag, normally this isn't a problem since they hold swords and won't trade them for normal items, yet I bring this up because of the randomly spawned overworld wither skeletons that don't have anything in their hands, I haven't tested this mob yet but I would probably be a good thing to look into.
