### ISSUE TITLE
Crashing when loading

### ISSUE THREAD

**Issue by Holdster** [Cazadorsniper/PO3#285]
pack verison 3.0.39
my crash log thing: 
[crash-2019-04-09_20.29.18-client.txt](https://github.com/Cazadorsniper/PO3/files/3061846/crash-2019-04-09_20.29.18-client.txt)
The game crashed whilst initializing game
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

computer spec: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
ram 16GB

**Comment by Cazadorsniper** [comment]
-Xmx3072m  not enough ram

**Comment by Holdster** [comment]
But it says 6GB of ram required on the launcher

**Comment by Cazadorsniper** [comment]
You're only giving it 3.

**Comment by Holdster** [comment]
oh how do i change that?

**Comment by Cazadorsniper** [comment]
In Twitchapp settings.

**Comment by Cazadorsniper** [comment]
just press ctrl + comma

**Comment by Holdster** [comment]
Thank you, i found it, I'll see if that helps

**Comment by Holdster** [comment]
it's working great now, thank you
