### ISSUE TITLE
Mod pack crashing upon launch

### ISSUE THREAD

**Issue by Fury421** [Cazadorsniper/PO3#287]
The modpack continues to crash upon launch despite allocating 6gbs of ram my specs allow me to play this pack and has been verified. If anyone has any idea how to fix this please let me know.
EDIT:
The following is the file it gives me when it crashes, and the twitchapp allows me to play other modpacks as well.
[latest.log](https://github.com/Cazadorsniper/PO3/files/3064692/latest.log)

**Comment by Cazadorsniper** [comment]
Go to file:/C:/Users/Cole/Twitch/Minecraft/Install/versions/1.12.2 and delete it.

**Comment by Fury421** [comment]
Thank you!! it works now.
