### ISSUE TITLE
Karat Carrots quest does not complete

### ISSUE THREAD

**Issue by repo-alt** [Cazadorsniper/PO3#288]
**Pack Version:**
3.0.39
**Singleplayer, Multiplayer, or LAN?:**
SSP
**Description:**
Have grown all the initial carrots, but the quest does not complete.
![image](https://user-images.githubusercontent.com/23512002/56006008-e3be3f00-5cdb-11e9-815b-5e552419bec9.png)
![image](https://user-images.githubusercontent.com/23512002/56006015-ea4cb680-5cdb-11e9-97eb-111a2f2cc57e.png)

**Comment by Cazadorsniper** [comment]
can you get those carrots again and put them in your inventory?

**Comment by repo-alt** [comment]
You mean grow a new set? I'll try it this evening.

**Comment by repo-alt** [comment]
Ok, I tested growing on the ores instead of blocks and it does work. Also I noticed that the carrots grown on the blocks have "Plus" appended to their name, and they glow like enchanted, so I technically should have been able to do the quest, if I was more attentive, sorry for the false alarm.
