### ISSUE TITLE
game not responding when loading/creating new world

### ISSUE THREAD

**Issue by JonasMLRS** [Cazadorsniper/PO3#289]
pack version: 3.0.39
Singleplayer

Every time I make a new world the game stops responding when it starts to load. Note it does create the world but when I start it, the same problem occurs.
No crash log is given.
Also it takes near 2 hours to load the pack, is this normal.

**Comment by Cazadorsniper** [comment]
The pack taking that long to load is normal until 3.0.40 comes out.

**Comment by Cazadorsniper** [comment]
For your first issue, Can you give me the latest.log from the logs folder, that might tell me if something is wrong. 

Did you tamper with the pack at all (add mods/removed mods/mess with configs)?

**Comment by JonasMLRS** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/3076060/latest.log)
 
also this seems to happen on every modpack.

**Comment by JonasMLRS** [comment]
no, I didnt change any mods or configs. besides some controles and sounds in the options menu.

**Comment by Cazadorsniper** [comment]
Have you tried just letting it load? And change the amont of ram you're using from 9G to 6G, PO3 doesn't need that much.

**Comment by JonasMLRS** [comment]
ok ill trie that

**Comment by JonasMLRS** [comment]
Waiting longer worked, it loaded the world. but then it stopped responding. ill trie again and wait even longer.

**Comment by JonasMLRS** [comment]
doesnt work.

**Comment by Cazadorsniper** [comment]
give me the log now.

**Comment by JonasMLRS** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/3077395/latest.log)

**Comment by Cazadorsniper** [comment]
You can try reinstalling the pack on a different drive maybe. 
Other than that it maybe something in your pc going bad like the cpu for example.

As far as I can tell the only issue I see is likely where the pack is installed at.

**Comment by JonasMLRS** [comment]
ok ill trie that then

**Comment by JonasMLRS** [comment]
reinstalling the pack on the c drive instaid of the d drive doesnt seem to change a thing.

though the first time I started it up on the c drive I got a crach raport say it didnt find the save files?

**Comment by Cazadorsniper** [comment]
Then I don't know what the issue is.

**Comment by JonasMLRS** [comment]
ok no problem, no modded for me then
