### ISSUE TITLE
Alot of recipe's aren't working

### ISSUE THREAD

**Issue by royalcandle** [Cazadorsniper/PO3#290]
**Pack Version:**
3.3.0.39

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Many recipe's fail to work, i've so far found: Bucket, String mesh, chrushing table.

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
No crash

**Comment by Cazadorsniper** [comment]
I didn't know we had a version: 3.3.0.39.

That means that whoever setup the server didn't set it up right, make sure the client and server script folders match.
