### ISSUE TITLE
Enrichment Chamber Quest not detected

### ISSUE THREAD

**Issue by SudzBud** [Cazadorsniper/PO3#291]
**Pack Version: 3.0.39**
**Singleplayer, Multiplayer, or LAN?: SP**

**Description: Crafted Enrichment Chamber and Cheated in but still doesn't detect, Manual detect button also does nothing.**

**Steps to reproduce: Craft and/or Cheat Enrichment Chamber from Mek**

**Crash log (use pastebin or similar): No Crash**

**Comment by Cazadorsniper** [comment]
I went through all of mekanism, for 3.0.40 so should be good next update.

**Comment by OrbitStudios** [comment]
This issue is still present on 3.0.40 for Single player and multiplayer

**Comment by Cazadorsniper** [comment]
Are you sure?

**Comment by Cazadorsniper** [comment]
Did you make sure to /bq_admin default load?
