### ISSUE TITLE
Passive mobs won’t spawn

### ISSUE THREAD

**Issue by WogMafia** [Cazadorsniper/PO3#292]
**Singleplayer**
passive mobs won’t spawn in over world. I am playing garden of glass and in other worlds it won’t either

**Comment by Cazadorsniper** [comment]
What biome are you in?

**Comment by Thistlestar** [comment]
I have this same problem, but I'm aware that in most cases passive mobs won't spawn in ocean biomes. I came to ask if this was ever going to change so that players wouldn't have to travel who knows how many blocks to find a different biome, specifically when playing on garden of glass.

**Comment by stevenv5360** [comment]
Just wanted to say that I have this problem as well, but only on the current (3.0.39) version. Had some animals, updated, no more spawns in overworld. Thought maybe they broke when I updated, but a fresh install also doesn't have passive spawns. Did a fresh install of .38, waited a couple minutes, and half a dozen cows popped up.
