### ISSUE TITLE
Crashing Twilight Forest

### ISSUE THREAD

**Issue by LungFailure** [Cazadorsniper/PO3#293]
**Pack Version:**
3.0.38
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
We've been having crashing issues in the twilight forests, and now every single time we load into the server it crashes us
**Steps to reproduce:**
Wander around the twilight forest 
**Crash log (use pastebin or similar):**
https://pastebin.com/DK2s0MqZ

**Comment by Cazadorsniper** [comment]
that is an crash caused by embers not twilight forest, Block location: World: (675,77,-282)

**Comment by LungFailure** [comment]
How can I resolve the issue?

**Comment by Cazadorsniper** [comment]
maybe try using world edit if you can't get there yourself.
