### ISSUE TITLE
Builder's wand causing crash

### ISSUE THREAD

**Issue by bradley21** [Cazadorsniper/PO3#294]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** Multi-player

**Description:** World crashes when a builder's wand (the white one) is focused on an object, such as a line of stones. Doesn't crash when just holding, or when looking at a non-building object.

**Crash log (use pastebin or similar):** https://pastebin.com/fK2t6GFi

**Comment by Cazadorsniper** [comment]
Removed EMC values from builder's wands
