### ISSUE TITLE
Crash on launch TileTick

### ISSUE THREAD

**Issue by mirawu1** [Cazadorsniper/PO3#295]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** Singleplayer 

**Description:** After breaking Enhanced Combustion Generator with World Breaker the game crashed. It was in pick mode, not the "Hammer".

**Steps to reproduce:** 

**Crash log (use pastebin or similar):** https://pastebin.com/hhXfkCQR

**Comment by mirawu1** [comment]
UPDATE: The game only when i break any block from enderio. I can break conduits!

**Comment by Cazadorsniper** [comment]
Remove the Botania magnet from inventory.
