### ISSUE TITLE
PO3 server Friends cant join internal exception: java.io.ioexception: an existing connection was forcibly closed by remote host error

### ISSUE THREAD

**Issue by Shadder-1-5** [Cazadorsniper/PO3#298]
I have got a PO3 server working, i (the server host) can connect to it, but my friend cannot, he can see it has full bars and mods are compatible but gets this error after 20-40 seconds of loading, internal exception: java.io.ioexception: an existing connection was forcibly closed by remote host
Server logs
![SERVER CODE](https://user-images.githubusercontent.com/49696709/56241170-0ccb3080-604a-11e9-88b0-e9f709993541.PNG)

**Comment by Cazadorsniper** [comment]
Version?

**Comment by Shadder-1-5** [comment]
Thanks you, but it was just my McAfee firewall, sorry for the inconvenience

**Comment by Cazadorsniper** [comment]
lol
