### ISSUE TITLE
Modular machines No structure found 

### ISSUE THREAD

**Issue by elimination79** [Cazadorsniper/PO3#299]
**Pack Version:** 
3.0.39
**Singleplayer, Multiplayer, or LAN?:**
single player
**Description:**
any of the modular machines that I've tried making say no structure found  
**Steps to reproduce:**

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Because you built it wrong some how.

**Comment by elimination79** [comment]
for the center blocks is it casing, mob masher, air space, and casing on top or am i missing something

**Comment by Cazadorsniper** [comment]
hovering over the space in JEI will tell you.
