### ISSUE TITLE
Quori Fragment Recipe

### ISSUE THREAD

**Issue by kewkew73** [Cazadorsniper/PO3#300]
Im playing version 3.0.39 and you cant enchant the bookshelves with the correct enchant for the quori fragments

**Comment by Cazadorsniper** [comment]
Are you sure?

**Comment by Cazadorsniper** [comment]
Its very much possible, I just did it. All you need to do is use the normal Hell-infused Bookshelves and surround the enchanting table with them, then slowly enchant each bookshelf until you reach "X" level.
