### ISSUE TITLE
Crash while in erebus dimension

### ISSUE THREAD

**Issue by chrisisonwildcode** [Cazadorsniper/PO3#301]
**Pack Version:**
3.0.39

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
Crash occured while in erebus dimension while exploring the the area.

**Steps to reproduce:**
uncertain.

**Crash log (use pastebin or similar):**
https://pastebin.com/uVkU1ukc

**Comment by Cazadorsniper** [comment]
Can you get back into the world? You may have just been moving too fast is all.
