### ISSUE TITLE
Game doesn't respond when loading my world

### ISSUE THREAD

**Issue by ToxicLama** [Cazadorsniper/PO3#302]
Hi!
Title says all. When i try to enter my world, minecraft doesn't respond and after a while it crash.
I don't understand why. Here is my crash report:

https://pastebin.com/TJs8vL7n

**Comment by Cazadorsniper** [comment]
Go into PO3's Extrautilities2 config and turn off sound mufflers.

**Comment by ToxicLama** [comment]
Sorry for my late reply, but the problem seems to be fixed.
Thank You very much for the support!!!!
Love your packs!
