### ISSUE TITLE
Quori Fragment Recipe not crafting

### ISSUE THREAD

**Issue by AmonGorloth** [Cazadorsniper/PO3#304]
**Pack Version:**
Latest 3.0.39

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
The Ultimate Crafting table shows that I have all items to build the Quori Fragment and I can even click the plus sign to move all required items for the recipe into the table.
But once there nothing happens.

Also noticed something weird, in the screenshots you'll see it, in the recipe it says the Hell-Infused Bookshelves should be enchanted to Nightvision X but I could only get Hell Infusion X to enchant the Bookshelves.

Don't know if this is why I can't craft it but I'm unsure about that.

**Steps to reproduce:**
I don't know if there are any.

**Crash log (use pastebin or similar):**
In JEI:

![quori1](https://user-images.githubusercontent.com/49737483/56367113-311b3e80-61fd-11e9-93f9-af9be430d00b.PNG)

In the crafting table:

![quori2](https://user-images.githubusercontent.com/49737483/56367156-4db77680-61fd-11e9-819f-327e27928154.PNG)

**Comment by Cazadorsniper** [comment]
where do you see night vision at?

**Comment by AmonGorloth** [comment]
Here:
![quori3](https://user-images.githubusercontent.com/49737483/56401333-f0551100-6260-11e9-9bd5-1e5084edf06f.png)

**Comment by Cazadorsniper** [comment]
well I wonder how that happened LUL

**Comment by AmonGorloth** [comment]
but what does it mean? ;)

**Comment by Cazadorsniper** [comment]
`mods.extendedcrafting.TableCrafting.addShaped(0, <voidcraft:quorifragment>, [[<projectex:matter>, <voidcraft:voidcloth>, <apotheosis:hellshelf>.withTag({ench: [{lvl: 10 as short, id: 69 as short}]}), <voidcraft:voidcloth>, <projectex:matter:8>, <voidcraft:voidcloth>, <apotheosis:hellshelf>.withTag({ench: [{lvl: 10 as short, id: 69 as short}]}), <voidcraft:voidcloth>, <projectex:matter:6>], [<projectex:matter:1>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <projectex:matter:9>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <projectex:matter:7>], [<voidcraft:voidcloth>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <voidcraft:voidcloth>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <voidcraft:voidcloth>], [<ore:runeGreedB>, <ore:plateMithril>, <ore:runeGluttonyB>, <lordcraft:runestone:216>, <voidcraft:voidstar>, <lordcraft:runestone:216>, <ore:runeGluttonyB>, <ore:plateMithril>, <ore:runeGreedB>], [<ore:runeWrathB>, <ore:runeLustB>, <ore:runeSlothB>, <minecraft:spawn_egg>.withTag({EntityTag: {id: "voidcraft:wraith"}}), <projectex:colossal_star_omega>, <minecraft:spawn_egg>.withTag({EntityTag: {id: "voidcraft:voidwrath"}}), <ore:runeSlothB>, <ore:runeLustB>, <ore:runeWrathB>], [<ore:runePrideB>, <ore:plateMithril>, <ore:runeEnvyB>, <lordcraft:runestone:216>, <voidcraft:voidstar>, <lordcraft:runestone:216>, <ore:runeEnvyB>, <ore:plateMithril>, <ore:runePrideB>], [<voidcraft:voidcloth>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <voidcraft:voidcloth>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <voidcraft:voidcloth>], [<projectex:matter:2>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <projectex:matter:5>, <voidcraft:voidcloth>, <ore:plateMithril>, <voidcraft:voidcloth>, <projectex:matter:10>], [<projectex:matter:3>, <voidcraft:voidcloth>, <apotheosis:hellshelf>.withTag({ench: [{lvl: 10 as short, id: 69 as short}]}), <voidcraft:voidcloth>, <projectex:matter:4>, <voidcraft:voidcloth>, <apotheosis:hellshelf>.withTag({ench: [{lvl: 10 as short, id: 69 as short}]}), <voidcraft:voidcloth>, <projectex:matter:11>]]);` this is the script for the fragment, and I see no issue, the hell infused bookshelves should all be the same.

**Comment by AmonGorloth** [comment]
alright, uhuh. saw that there was an update to 40, should I update and see if it does anything?

**Comment by Cazadorsniper** [comment]
you can try.

**Comment by AmonGorloth** [comment]
nope, still just an empty box where the fragment should be as a finished crafting product.

I'm leaning towards just cheating one fragment in and travelling to that voidcraft dimension where the mobs that drop the fragments are and kill some to get more, unless you have conjured up something?
