### ISSUE TITLE
Other players and some entities are invisible.

### ISSUE THREAD

**Issue by JMZED** [Cazadorsniper/PO3#305]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Other players, and sometimes mobs, are completely invisible (not like a potion effect with particles). Seems like a resource issue. Tried relaunching, relogging, reloading resource packs, the only thing that seems to work is if that player relogs. 

**Steps to reproduce:** Not sure how to replicate, it just happens occasionally but they do reappear after *they* relog. 

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Dimension?

**Comment by NLBlacky** [comment]
Just wondering, are you using GriefPrevention with the enter-claim set to false? When players try to enter and get "pushed back", they tend to be invisible (and a few other things like unable to teleport). Just to confirm it is the modpack.

**Comment by JMZED** [comment]
> 
> 
> Dimension?

Overworld, they appear in other dimensions but go back to invisible when returning to the overworld.


> 
> 
> Just wondering, are you using GriefPrevention with the enter-claim set to false? When players try to enter and get "pushed back", they tend to be invisible (and a few other things like unable to teleport). Just to confirm if it is the modpack.

I do not believe GriefPrevention is present.
