### ISSUE TITLE
heart canisters can't be equipped

### ISSUE THREAD

**Issue by salanga** [Cazadorsniper/PO3#306]
**Pack Version:**3.0.40
**Singleplayer**

**Description:**I updated the pack and when i came online i lost my orange heart canisters(logical seeing how they changed to yellow) but i also didn't see the red heart canisters i had in my bauble slot before updating. i killed myself to try and get them back and that worked but now i can't equip them.
i tried right clicking them and placing them in my bauble inventory(only slot the fit is my offhand slot of the 8 slots in the baubles inventory)

**Steps to reproduce:**wear orange and red heart canisters in your bauble inventory and update from 3.0.39. you get in the world with 20 hearts (10 normal and 10 from the red canisters) 

**Crash log (use pastebin or similar):**no crash log because i don't crash

**Comment by saulysw** [comment]
Same with me -- died and now can't reequip the red heart canisters. Also, in the quests I seem to have a "?" placeholder.

**Comment by salanga** [comment]
To get rid of the '?' you have to refrssh the quest book with /bq_admin default load.

**Comment by Cazadorsniper** [comment]
Need the amulet to equip the canisters now.

**Comment by Firesparq** [comment]
Can confirm, cazadorsniper has the solution.

**Comment by Terrapirate** [comment]
I have the heart amulet and the containers but i can't do anything,

**Comment by lachlanapple** [comment]
where do you put the heart canister?
