### ISSUE TITLE
Glimmer cristal, embers

### ISSUE THREAD

**Issue by Asterionik** [Cazadorsniper/PO3#308]
**Pack Version: 3.0.40
**Singleplayer, Multiplayer, or LAN?: Singleplayer

I can't make a glimmer crystal. The ritual starts but it always does alchemical waste. Made about 50 attempts.
![2019-04-19_20 35 23](https://user-images.githubusercontent.com/49792769/56435885-bc223480-62e2-11e9-89fb-c97b00edbad1.png)

**Comment by Firenyth** [comment]
the alchemical waste should give you a number on the tool tip, that shows how much more powder is needed in the tower things. so (say you put 64 in one of them you will guarantee to get waste, 64 + the number on the waste and bam it should work)
