### ISSUE TITLE
Missing Gem of Eternal Density and Harvest Goddess Band Recipe

### ISSUE THREAD

**Issue by c0ldk453** [Cazadorsniper/PO3#309]
**Pack Version:** 3.0.40

**Singleplayer, Multiplayer, or LAN?:** Multiplayer: po3.dirtcraft.gg confirmed - mods can confirm that the items are not disabled as I opened a support ticket with them first

**Description:**
Missing Gem of Eternal Density and Goddess Harvest Band recipe and thus Void Ring and Ring of Arcana cannot be produced either.

**Steps to reproduce:**

- This applies to both items.

- Unable to craft using the recipe given online.  JEI shows no recipe except for Stamper.  This bug applied to 3.0.38 as well.  Before pack update from 3.0.38, it wasn't even showing in the stamper.  And it shows as _Renamed Item_ in JEI as a result from the stamper now.  I would assume this is an issue related to draconic revolution, but I can't really say.  ProjectEX was updated today, so it may also be related to that.  Finally could also be missing recipes from Ultimate Crafting as many advanced items in PO3 are crafted through advanced crafting.

![2019-04-20_01 04 51](https://user-images.githubusercontent.com/19635392/56454103-467d8f00-6309-11e9-96d9-7dec7625fd4a.png)
![2019-04-20_01 05 04](https://user-images.githubusercontent.com/19635392/56454105-4aa9ac80-6309-11e9-84fd-e57742df3f1c.png)
![2019-04-20_01 05 09](https://user-images.githubusercontent.com/19635392/56454106-4aa9ac80-6309-11e9-914f-1cf515bacddc.png)
![2019-04-20_01 05 32](https://user-images.githubusercontent.com/19635392/56454107-4b424300-6309-11e9-9bf3-21b5d42dc564.png)
![2019-04-20_01 05 37](https://user-images.githubusercontent.com/19635392/56454108-4b424300-6309-11e9-9a4e-f5f53c92a7f6.png)
![2019-04-20_01 11 06](https://user-images.githubusercontent.com/19635392/56454109-4b424300-6309-11e9-8aae-0211e479c8d6.png)

**Comment by c0ldk453** [comment]
So, just another one to note: All Energy Collectors appear to be missing their crafting recipes as well.  Seems to be in SP as well.  No one on my server was even aware they existed in ProjectE still until I mentioned it was weird that they were missing in this pack.  I hopped into creative, and sure enough - there they are.  In fact, all items not craftable in projectE are still in creative.  Anti-Matter Relays, Energy Collectors, Gem of Eternal Density, and Watch of Flowing Time all appear here when they don't in JEI.  
![2019-05-18_14 23 35](https://user-images.githubusercontent.com/19635392/57974620-91c2a600-7978-11e9-8a9a-eb7a71213c38.png)
![2019-05-18_14 21 37](https://user-images.githubusercontent.com/19635392/57974621-94250000-7978-11e9-90e5-d1828baaeae5.png)

**Comment by Cazadorsniper** [comment]
Because I hid them from JEI, Go back to every Project Ozone except maybe 1 and you'll notice the energy collectors/relays are all disabled through recipe removal.
