### ISSUE TITLE
Astral Sorcery: Fosic Resonator quest

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#31]
Pack Version: 3.0.38

Description:
The Fosic Resonator required by the quest (Ichosic+Domic) does not exist. The item is shown in JEI because it contains 3 different crafting recipes (Fosic Resonator, Fosic Resonator Ichosic and Fosic Resonator Domic. I have crafted both the Fosic Resonator Ichosic and Fosic Resonator Domic and was not able to complete the quest
![2019-02-27_18 08 29](https://user-images.githubusercontent.com/19508559/53509108-7489e400-3abb-11e9-945b-ca3c97036a66.png)
![2019-02-27_18 08 30](https://user-images.githubusercontent.com/19508559/53509109-7489e400-3abb-11e9-8dcf-c6b4909e9b70.png)
![2019-02-27_18 08 50](https://user-images.githubusercontent.com/19508559/53509110-7489e400-3abb-11e9-80bb-d6417832e4ac.png)

Steps to reproduce: Try to complete the quest with the craftable Fosic Resonators

**Comment by Cazadorsniper** [comment]
Removed said quest
