### ISSUE TITLE
Missing creatures from rftools config

### ISSUE THREAD

**Issue by Firesparq** [Cazadorsniper/PO3#310]
Project Ozone 3 V3.0.40

Tested in Singleplayer

Some modded creatures still need to be added properly to the rftools spawner config list. I know for certain that both the void wraith and chained spectre (both from voidcraft) aren't functioning properly.

Steps to reproduce:
1. Setup a rftools spawner
2. Punch voidcraft wraith/chained spectre with a syringe (rfTools)
3. Plug full syringe into spawner
4. Receive nullrf error in spawner GUI
5. ...
6. Profit?

**Comment by Cazadorsniper** [comment]
That is because no modded creatures are in the list at all, the list was made on its own when I generated the config and wasn't edited by me at all.

**Comment by Cazadorsniper** [comment]
Have you tried using the mob duplicator?

**Comment by Firesparq** [comment]
I mean sure. There are plenty of alternatives (Woot has been my goto so far), but I wanted to setup an rftools spawner specifically. Shouldn't there be a means of pre-creating a config in a Modpack so that users aren't forced to generate their own lists?

**Comment by Cazadorsniper** [comment]
You mean editing a config? I can probably edit it to take modded mobs, but 1. it will take a while to do, 2. I won't be able to update the pack again until about a month later because of the person who makes the server files is moving.

**Comment by Firesparq** [comment]
That's fine. I can find work arounds for myself, but I think it'd be a good idea to do for others 😊

**Comment by Cazadorsniper** [comment]
Maybe, but most others will stick with Ender IO and/or Industrial Foregoing
