### ISSUE TITLE
Barrel composting does not accept sawdust from Thermal Expansion

### ISSUE THREAD

**Issue by Landmaster** [Cazadorsniper/PO3#311]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** When trying to put sawdust from the Thermal Expansion pulverizer into the barrel to make dirt, the barrel does not accept this dust. Only the Mekanism dust, which can be obtained via a hammer, will work in the barrel. Is this intended behavior?

**Steps to reproduce:** Put some wood into the Thermal Expansion pulverizer. Try to use the sawdust on the barrel to compost into dirt, and it will not work.

**Crash log (use pastebin or similar):** N/A

**Comment by Landmaster** [comment]
I also found that Thermal Expansion and Mekanism sawdust are interchangeable using the Forge Lexicon, which makes this bug all the more strange.

**Comment by Cazadorsniper** [comment]
That is because both saw dusts oredict with each other so the lexicon can see that, but in exnihilo's compost registry can only use registry names not ore dictionary as far as I know.

I can have them both work in next update though.
