### ISSUE TITLE
Game Crash right when loading finishes?

### ISSUE THREAD

**Issue by DJayCubbz** [Cazadorsniper/PO3#312]
Pack Version: Latest? Twitch says unknown

Description: I press play and it crashes after 7/7 is reached

Steps to reproduce: I press play and it crashes after 7/7 is reached

Crash log: https://pastebin.com/aSpvpnzv

**Comment by DJayCubbz** [comment]
This is a fresh install, never played before.

**Comment by Cazadorsniper** [comment]
Add more ram
