### ISSUE TITLE
Problem with task

### ISSUE THREAD

**Issue by Suripe** [Cazadorsniper/PO3#313]
**Pack Version:** 3.0.40
**Multiplayer**

**Description:**
Upgrade from 3.0.39 to 3.0.40, this problem occurs when the task is updated.

**Steps to reproduce:**
Start Server
/bq_admin default load

![image](https://user-images.githubusercontent.com/23328935/56468267-902abe80-645c-11e9-8ea0-205440b3b818.png)
![image](https://user-images.githubusercontent.com/23328935/56468271-9ae55380-645c-11e9-953f-6b122815ffc7.png)

**Comment by Cazadorsniper** [comment]
Not sure why there is an issue with BQ and Contenttweaker right now...

**Comment by Suripe** [comment]
Ok, now I am re-extracting the server and there is no such problem.

**Comment by Cazadorsniper** [comment]
That is weird...
