### ISSUE TITLE
Chance cube - unplayable lagg

### ISSUE THREAD

**Issue by royalcandle** [Cazadorsniper/PO3#314]
**Pack Version:**
3.0.38

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
When I used about 16 chance cubes and 16 chance Ociosahedron (obtained from RAK/Chest) the server became unplayable, anyone playing the server would have a permanent 1/2 FPS.
I'm not sure which one of the 2 caused it, but a restart of the server does not fix it, need to rollback to an earlier save.

**Steps to reproduce:**
Place down and use chance cubes/chance iciosahedron.

**Crash log (use pastebin or similar):**
No crash

**Comment by Cazadorsniper** [comment]
Have you tried updating?

**Comment by royalcandle** [comment]
Haven't tried updating, but will do so now (Version 3.0.40), will try to simulate the same scenario and let you know.
