### ISSUE TITLE
Mekanism quests not being detected.

### ISSUE THREAD

**Issue by OrbitStudios** [Cazadorsniper/PO3#315]
Pack Version: 3.0.40
Singleplayer, Multiplayer, or LAN?: MP or SP

Description: Mekanism machines are not being detected by the quest book.

Steps to reproduce: Craft or pickup an Enrichment Chamber, Crusher or PRC and the quest book doesn't detect it.

Crash log (use pastebin or similar): No Crash

**Comment by Cazadorsniper** [comment]
#291
