### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by BreadtheRipper** [Cazadorsniper/PO3#316]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** The launcher doesn't begin to load the game at all. Hitting play on the twitch launcher brings up the main launcher, then I press play on that, the log opens then.. Nothing, it comes to a hard stop. This only started happening once I updated from 3.0.39

**Steps to reproduce:** N/A?

**Crash log (use pastebin or similar):** Wasn't generating a crash log, but can provide the latest log if it helps; https://pastebin.com/j2Rt9QMc

**Comment by Cazadorsniper** [comment]
Try repairing the profile.

**Comment by BreadtheRipper** [comment]
Still does the same thing
Here is the latest log in case anything is different that I can't see; https://pastebin.com/JuxBZjDJ

**Comment by Cazadorsniper** [comment]
Try reinstalling the whole pack or try removing the 1 from Josh1

**Comment by BreadtheRipper** [comment]
Reinstalling the pack seemed to work, thankfully
Wasn't sure how I would've removed the number from the path cuz it's the user path
