### ISSUE TITLE
Crashes with Liteloader

### ISSUE THREAD

**Issue by RanosFox** [Cazadorsniper/PO3#317]
Pack Version: 3.0.40
I tried to add a liteloader mod but it keeps failing. This crash only seems to show up when the liteloader.jar file is in the mods folder. The Apotheosis seems to be the one conflicting with Liteloader. 

Crash log:
https://pastebin.com/mswLq70Z

I don't expect you to do anything about this, since it's not part of the mod pack, but I would greatly appreciate any help you could give me so I can solve the problem on my end.

**Comment by Cazadorsniper** [comment]
Have you tried not having liteloader? All jokes aside, Have you tried reporting to Shadows(the Apotheosis developer)?

**Comment by RanosFox** [comment]
It works just fine without Liteloader ^-^ and not yet, I'll message them soon.

**Comment by RanosFox** [comment]
Found out the reason why it happened, and to quote Shadow: "LiteLoader is known to be broken with registry replacements (which apotheosis uses heavily)." It's all fine now tho, because it turns out the liteloader mod I wanted to install now has a forge version.

I rally like this mod pack so far. Thank you very much for putting it together.
