### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by jomakoto1** [Cazadorsniper/PO3#319]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:** 
singleplayer
**Description:**
gamecrash when hitting play in the minecraft launcher
i was able to access the game earlier today, and tried to make a world that ended up crashing the game, after that i was not able to start it anymore, so i reinstalled and it still doesnt work.
i have allocated 12GB of ram from my 32GB and it still crashes.
**Steps to reproduce:**
crashes when hitting play in the launcher
**Crash log (use pastebin or similar):**
https://pastebin.com/F3RjuqXj

**Comment by Cazadorsniper** [comment]
1. Pack Version?
2. Can try and make sure windows firewall and/or antivirus software isn't blocking minecraft.
3. Can try and make sure your drivers are up to date.
4. Update Java
5. Turn ram beck down to 6gb, PO3 doesn't need more than that.
6. You could try deleting the 1.12.2 folder located here: \Jo\Twitch\Minecraft\Install\versions\1.12.2

**Comment by jomakoto1** [comment]
updated the drives and that ended up working, at least so it didnt crash from the laucher, but now it crashes while im on the mojang screen, it did work a few times yesterday, but now it just crashes while its loading 
https://pastebin.com/wReL5W6K

**Comment by jomakoto1** [comment]
and now the pc blue screened with the bluescreen "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED"...

**Comment by Cazadorsniper** [comment]
It may be possible that a part in your pc is going bad now.

**Comment by jomakoto1** [comment]
yeah, i did a memory test and found out that there was something wrong with my RAM, so gonna get a replacement tomorrow and check if it works properly then.

**Comment by jomakoto1** [comment]
but thank you for the help anyways :)
