### ISSUE TITLE
VoidCraft Mob quests

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#32]
Pack Version: 3.0.38

Description: I have killed multiple Void's Wraths in a Fortress as well as multiple Chained Spectres but both quests won't complete.

Steps to reproduce: Kill mobs and try to complete quests.

**Comment by ukdyl94** [comment]
Same issue, can be reproduced in Single Player mode as well.

**Comment by martinschuberteu** [comment]
> Same issue, can be reproduced in Single Player mode as well.

Thank you for confirming. I was not sure if I broke it somehow because I was using Ender IO Soul Vial + Powered Spawner to farm the drops before I started actually killing them myself.
