### ISSUE TITLE
Transmutation table not crafted

### ISSUE THREAD

**Issue by KirillPUH** [Cazadorsniper/PO3#321]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Transmutation table not crafted

**Steps to reproduce:** Just lay out the transmutation recipe table and try to pick it up.

**Crash log (use pastebin or similar):** 
![2019-04-24_19 09 05](https://user-images.githubusercontent.com/28572464/56675777-9cfe1b00-66c5-11e9-8834-f4a3e70c513f.png)

![2019-04-24_19 09 08](https://user-images.githubusercontent.com/28572464/56675761-94a5e000-66c5-11e9-9034-1245ce1e0f3d.png)

**Comment by Cazadorsniper** [comment]
Have you tried charging it?

**Comment by KirillPUH** [comment]
What means "charging"?

**Comment by Cazadorsniper** [comment]
You can charge the philosophers stone using a  keybind, I believe its either c or v by default.
