### ISSUE TITLE
creative ember source can't be craft due to missing items

### ISSUE THREAD

**Issue by jaront2008** [Cazadorsniper/PO3#323]
**Pack Version:3.0.39**
**Singleplayer, Multiplayer, or LAN?:both **

**Description:when crafting the creative ember source you need the Inscription tiles for b,w,e, and r  letters but they are not craftable anymore they were in previous versions but they're not anymore and blank tiles do not work.
**

**Steps to reproduce:always does it**

**Crash log (use pastebin or similar):NA**

**Comment by jaront2008** [comment]
is no one going to look at this or fix it the quest book is not completable because this bug

**Comment by Cazadorsniper** [comment]
Are you sure the inscription tile W is there?

**Comment by jaront2008** [comment]
B,E,E,M,R

**Comment by Cazadorsniper** [comment]
I was able to make the inscription tiles fine. E.M.B.E.R.

**Comment by jaront2008** [comment]
how?

**Comment by Cazadorsniper** [comment]
didn't you make the inscription table from Lord Craft?

**Comment by jaront2008** [comment]
i was confused because there was nothing called  inscription table in the mod it is called the arcane inscriber. it doesn't show you the recipe in JEI to make the tiles that's what confused me

**Comment by Cazadorsniper** [comment]
Yeah I just forgot the name.
