### ISSUE TITLE
Quantum Entangloporter

### ISSUE THREAD

**Issue by CakeYay** [Cazadorsniper/PO3#324]
Pack Version:3.0.39.
Singleplayer.

**Description:**
The quantum entangloporter doesn't seem to be working. It's not receiving energy or sending it. I didn't change anything with it. I logged in and it just stops working.
**Steps to reproduce:**

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
try breaking it then setting it back down.
