### ISSUE TITLE
Mislabeled Quest info.

### ISSUE THREAD

**Issue by Slytherite** [Cazadorsniper/PO3#327]
Version 3.0.40
Single Player

Quest descriptions are incorrect. For example the Thermal Solar descriptions displays incorrect RF/tick to what they actually produce, (e.g. Quest says the Tier 3 Solar Panel says 64 RF/tick when it actually generates 300 RF/tick, as well as the rest of the Thermal solar and lunar panels)
Another incorrect quest description says that Ender IO Dark Steel is made with Iron + Obsidian + Silicon, when the actual crafting recipe is Iron + Coal powder + Obsidian.

Steps to reproduce, just reading the quest descriptions for the listed quests.

**Comment by Cazadorsniper** [comment]
About the solar panels, that is their default generation I just raised their values later. That is why they're wrong now.

**Comment by Cazadorsniper** [comment]
For example the quest descriptions for the furnaces in Alpha are likely wrong too.
