### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lirannl** [Cazadorsniper/PO3#328]
**Pack Version:**PO3-3.0.40 
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**The game just suddenly crashed

**Steps to reproduce:**Play the game on an Ubuntu 19.04 derivative with a profile created via MultiMC. (Nvidia mode)

**Crash log (use pastebin or similar):** I can't use pastebin because the file is over 512kb. Here's a GDrive link to the txt. https://drive.google.com/file/d/1i0k2oGpzCrE-g61BdZjmI-zTWF0orTt5/view?usp=sharing

**Comment by Cazadorsniper** [comment]
Did you run out of space in your storage space?
Can you try using a normal JRE not OpenJDK?
