### ISSUE TITLE
Hydra won’t unlock after killing every other boss.

### ISSUE THREAD

**Issue by JoeBan598** [Cazadorsniper/PO3#329]
**Pack Version:**3.0.40
Multiplayer - my own server

**Description:** i have gone through the twilight forest mod and killed every single boss but the hydra and the dark tower. In the quest book i have all of the quests done and have all of the trophies of the bosses, but the green particles still show up at the hydra lair. I have tried damaging the hydra anyways but no luck.

**Steps to reproduce:**go through the twilight forest mod.

**Crash log (use pastebin or similar):**no crash log because i don't crash

**Comment by Cazadorsniper** [comment]
try redoing what comes before the Hydra

**Comment by JoeBan598** [comment]
I have tried that and still no success. Any other ideas?

**Comment by Cazadorsniper** [comment]
What boss comes before the Hydra can't remember right now? xD

**Comment by JoeBan598** [comment]
Lol the ur-ghast and the ice queen.

**Comment by Cazadorsniper** [comment]
Killing the Minoshroom, and eating some of his Meef Stroganoff will allow you to enter the Fire Swamp without being burnt.

**Comment by JoeBan598** [comment]
It works thanks so much !
