### ISSUE TITLE
Astral Sorcery Minor Constellations not showing on Paper

### ISSUE THREAD

**Issue by RuinPrime** [Cazadorsniper/PO3#33]
**Pack Version:**
3.0.38
**Description:**
I have the 5 major constellations discovered, but no matter what I can't get the rest of them to show up. The constellation papers all say "There is nothing here". 

I even tried manually crafting them and while I did get credit in the form of the "You memorize a drawing of Lucerna!" message and it shows up in the book now, the constellation paper reverted to the default "There is nothing here" version (shown in screenshot).
![2019-02-27_15 19 47](https://user-images.githubusercontent.com/42121163/53523912-b1e27780-3aa3-11e9-9972-340b30ed8c45.png)
![2019-02-27_15 23 49](https://user-images.githubusercontent.com/42121163/53523922-b575fe80-3aa3-11e9-91e4-60338ad8f377.png)

**Steps to reproduce:**
Discover all 5 major constellations (get paper and map on telescope), get more constellation paper and it stays blank. 

**Crash log:**
No crash.

**Comment by jag0k** [comment]
You need to be attuned to one of the major constellations in order to find the minor ones, did you do that? Also I think you need to use a telescope or observatory rather than a looking glass.

**Comment by RuinPrime** [comment]
You were absolutely correct about not being attuned, I completely missed that step. Thanks so much that fixed it.
