### ISSUE TITLE
I updated the pack and it won't start cause its missing items

### ISSUE THREAD

**Issue by Boflar** [Cazadorsniper/PO3#330]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** When I try to open my world it says items are missing and I don't know if its a twitch thing or not but I haven't found a way to fix it

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
![ozone](https://user-images.githubusercontent.com/49245439/56758498-cc179980-6764-11e9-90f9-1a5739f4b6cb.PNG)

**Comment by Cazadorsniper** [comment]
It won't start because of other reasons that I don't know. Try starting the world.

**Comment by Boflar** [comment]
That's what I get when I start the world. The pack loading screen is normal, I only get this message when I try to open my world

**Comment by Boflar** [comment]
https://media.giphy.com/media/3kyuXGTqVXC7cDVkyc/giphy.gif

**Comment by Cazadorsniper** [comment]
Try starting the world.

**Comment by Boflar** [comment]
What do you mean? Watch the giphy, that's what I am doing.

**Comment by Cazadorsniper** [comment]
You never clicked yes to continue to load the world.

**Comment by Boflar** [comment]
It loaded in fine. I tried redownloading the version before starting but I guess it did nothing

**Comment by Boflar** [comment]
I guess everythings ok? I had 2 sound mufflers next to my mob farm but that's the only impact it had

**Comment by Cazadorsniper** [comment]
Make sure to do /bq_admin default load

**Comment by Boflar** [comment]
ok, thank you :)
