### ISSUE TITLE
Walking makes the world flip away.

### ISSUE THREAD

**Issue by Im-Brandfall** [Cazadorsniper/PO3#334]
3.0.40 Project Ozone 3 through Twitch App

Singleplayer

Walking in any direction causes the world and character to disappear until I come to a stop. After a second everything returns flipping then the game proceeds normally. I have tested on a vanilla game of Minecraft and it did not reproduce, so far seems to be only modded Minecraft.
I have taken a video to show its effects: https://imgur.com/TjCTc9C

Walking in any direction

https://zerobin.net/?6265b50945929084#He1YbuKyQ4q/BwppCUV22RZ8Db2iErKKlv5iJtK9tTo=

**Comment by Cazadorsniper** [comment]
Have you tried messing with BetterFPS settings? Did you mess with any configs? Add any mods? Remove any mods?

**Comment by Im-Brandfall** [comment]
I adjusted BetterFPS to Taylor's algorithm, set to fast beams and did not remove or add any mods.

**Comment by Cazadorsniper** [comment]
Taylor's algorithm... Yeah don't use that, switch to another and the problem will stop.

**Comment by Im-Brandfall** [comment]
What algorithm do you recommend?

**Comment by Cazadorsniper** [comment]
I use Rivern Full
