### ISSUE TITLE
Agricraft Crops not Upgrading

### ISSUE THREAD

**Issue by rvazarkar** [Cazadorsniper/PO3#335]
**Pack Version:** 3.0.39
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Agricraft crops are not upgrading, and won't spread to cross sticks either.

**Steps to reproduce:** See image, these crops have been sitting under 4x sprinklers for about 10 minutes without ever going to the cross stick

![image](https://user-images.githubusercontent.com/5720446/56838857-c0ec6880-684d-11e9-8aac-b7ded9adf97a.png)

**Comment by Cazadorsniper** [comment]
Have you tried using watering can? Sometimes it takes awhile.

**Comment by rvazarkar** [comment]
I cheated in a watering can and attempted to water the crops for 5 minutes, along with the sprinklers running on top, still nothing. I even switched to 1/1/1/1 melon seeds just in case the earth seeds were bugged. Still no dice.

![image](https://user-images.githubusercontent.com/5720446/57201625-94c99980-6f69-11e9-928e-d625238d9df5.png)

Perhaps this is linked to this bug on the agricraft git?

https://github.com/AgriCraft/AgriCraft/issues/1217

**Comment by Cazadorsniper** [comment]
hmm it likely that a forge update caused that issue. Will need to wait for the mod to update for a fix.

**Comment by ImJustJoshin** [comment]
They sometimes take a while. While frustrating, I don't believe this to be a bug. You can see the instances of long wait times using the imaginary time block (powered) as that block grows crops in a 5x5 radius almost instantly, way faster than any crop growth system I have ever played with.

**Comment by rvazarkar** [comment]
Just as an update, it took about 10 minutes with an infinite time block to get a single cross crop mutation upgrade. I don't know if the values on cross crops are set way too low or I have incredibly bad luck, but I'm not sure how mystical agriculture is viable if that's how long it takes to upgrade seeds in basically ideal conditions, unless you just stick to 1/1/1/1

**Comment by Iomrais** [comment]
I stopped using the crossbars on the crop sticks, and the crops seems to spread at a more reasonable pace now with no sprinklers. Try just using the upright sticks.

**Comment by zenekron** [comment]
The bonemealer ability seems to be a decent workaround. Combined with a watering it takes less than a minute to have crops grow on cross sticks (where a minute is more of an upper bound than an average).
