### ISSUE TITLE
Visual Issues

### ISSUE THREAD

**Issue by Thistlestar** [Cazadorsniper/PO3#336]
Version 3.0.40
Singleplayer

For some reason, ever since I updated the pack, all blocks I break cycle through different textures before it breaks. First, it inverses the colors, then it uses a furnace texture, after that a cobble and compressed cobble texture, then glass, then a very dark cobble texture, then it breaks. Not a huge issue, but I find it a bit obnoxious.

Steps to reproduce: Not really sure if there are any specific steps. It just started happening when I loaded up my world, and it won't stop. This doesn't happen for all blocks, mostly full blocks. Anything that doesn't count as a full block doesn't seem to be affected. Just for note, I use the default minecraft textures.

**Comment by Cazadorsniper** [comment]
Reload the whole pack, It doesn't do well switching resource packs ingame.
