### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by RatchetButter** [Cazadorsniper/PO3#338]
**Pack Version:**
PO3-3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
Crashes when launched
**Steps to reproduce:**
Im not entirely sure what this means to be honest but I see other reports saying this so...
"Play the game on an Ubuntu 19.04 derivative with a profile created via MultiMC. (Nvidia mode)"
**Crash log (use pastebin or similar):**
https://pastebin.com/LuPLuSE3

**Comment by Cazadorsniper** [comment]
remove waiting time
