### ISSUE TITLE
Xia dimension

### ISSUE THREAD

**Issue by raulAcero** [Cazadorsniper/PO3#340]
**Pack Version:**
3.0.40 and 3.0.38

**Singleplayer, Multiplayer, or LAN?:**
singleplayer

**Description:**
I started fight against Xia, I won and when you have to take his armor minecraft crash

**Steps to reproduce:**
Go fight Xia and won, later when you have to fly it crash

**Crash log (use pastebin or similar):**
https://pastebin.com/zN1SEGR1

**Comment by Cazadorsniper** [comment]
Then don't fight him. I can't fix this at all.
