### ISSUE TITLE
Pyrotheum no working as fuel source for crucible

### ISSUE THREAD

**Issue by Boflar** [Cazadorsniper/PO3#342]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Wiki (updated a month ago) says I can use pyrotheum to increase cooking speed and it won't work for some reason, even the source block.

**Steps to reproduce:** Place Blazing Pyrotheum under crucible with cobble piping into it

**Crash log (use pastebin or similar):**
![2019-04-28_21 08 41](https://user-images.githubusercontent.com/49245439/56872818-1ade6100-69fb-11e9-8130-b281b50826e3.png)

**Comment by Cazadorsniper** [comment]
That wiki is likely for "Ex Nihilo" not "Ex Nihilo Creatio", crucible heat sources are what I have it configured to be, just look into JEI.
