### ISSUE TITLE
Crash on the loading screen "Mojang Screen"

### ISSUE THREAD

**Issue by Driiv** [Cazadorsniper/PO3#343]
Pack Version: 3.0.40

Singleplayer, Multiplayer, or LAN?:  Singleplayer and Multiplayer

Description:
Hello.
I have, again, a crash problem on the modpack.
I don't know if I need to give more information, I updated java, my drivers are up to date too, I have uninstalled and reinstalled several times without success. 
The modpack worked fine until I tried to get on a server. Since all modpack twitch crash systematically

Steps to reproduce:

Crash log (use pastebin or similar): https://paste.ubuntu.com/p/FBBb2qshcT/

Thanks for your help.
(Sponsored by google translation .. sorry :') )

**Comment by Cazadorsniper** [comment]
Are you sure your graphics driver is up to date?
It may be possible that the graphics is dying in your pc.

**Comment by Driiv** [comment]
Hmm maybe but my pc is not so old, it would surprise me a little. I will check the drivers as soon as possible in doubt.
Would it be the only cause of the crash?

**Comment by Cazadorsniper** [comment]
Try reinstalling the pack.
