### ISSUE TITLE
Party is not getting Rewards/ No "Share loot" option?

### ISSUE THREAD

**Issue by gumbass** [Cazadorsniper/PO3#344]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I saw on some Youtube Videos that Party member get the rewards too if someone picked like a loot chest or something. Thats not the case for me and my friends. Is it something i have to edit/enable or what do i have to do? I also dont see any "share loot" option while creating or in a party

**Comment by Lord-Klaw** [comment]
am having the same issue
