### ISSUE TITLE
Wireless Crafting Terminal in Baubles Slot Upon Death

### ISSUE THREAD

**Issue by ethanhlc** [Cazadorsniper/PO3#346]
Pack Version: 3.0.40
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Wireless Crafting Terminal moves into baubles slot upon death

Steps to reproduce: Die with a wireless crafting terminal in inventory.

The first few times, I thought the crafting terminal had disappeared but found them (made new ones each time) in baubles slots.
This also happens even with a Spectral Anchor on the crafting terminal.

**Comment by Gabbleducky** [comment]
Yeah this happens to me as well, it's because the wireless crafting terminal (as well as the thermal reservoirs) are listed as baubles for some reason
