### ISSUE TITLE
sakanade spores 

### ISSUE THREAD

**Issue by jinkhya** [Cazadorsniper/PO3#348]
Hello, 

how does one get the spawn eggs needed for the quori fragment extreme recipe? To get an egg you need capturing enchant which needs sakanade spores from random things but those are turned off in world gen.

Thanks in advance.

**Comment by Cazadorsniper** [comment]
Sorry about that. Fixed for next update.

**Comment by jinkhya** [comment]
thank you !

**Comment by jinkhya** [comment]
Did you add a recipe for those or enable the generation in world? That way I can possibly temp fix our server?

**Comment by Cazadorsniper** [comment]
recipes.addShapeless(<randomthings:ingredient>, [<minecraft:brown_mushroom>,<exnihilocreatio:item_material:3>]);

add to all_recipes.zs

**Comment by jinkhya** [comment]
Awesome, thank you very much !

**Comment by jinkhya** [comment]
I think you meant 
recipes.addShapeless(<randomthings:ingredient>, [<minecraft:brown_mushroom>,<exnihilocreatio:item_material:3>]);
;) I wondered why some recipes were not working anymore

**Comment by jinkhya** [comment]
oh I see the "<" ">" don't get written

**Comment by Cazadorsniper** [comment]
yeah because github.
