### ISSUE TITLE
DE Info Tablet Freeze

### ISSUE THREAD

**Issue by Propellant1** [Cazadorsniper/PO3#349]
**Pack Version:** 

3.0.40

**Singleplayer, Multiplayer, or LAN?:** 

Multiplayer

**Description:**

When attempting to open the Draconic Evolution Information Tablet my client freezes. Client is sometimes able to recover from the freeze. However the recipes in the tablet cause additional freezes and thus more possible unrecoverable freezes. 

**Steps to reproduce:**

Simply open the Draconic Evolution Information Tablet

**Crash log (use pastebin or similar):**

https://pastebin.com/Mcg8gpzW  -  Redacted due to size limit on pastebin.

[full log here](https://github.com/Cazadorsniper/PO3/files/3139931/2019-05-02-2.log)

Relevant lines in log file are 10815-10870

[latest.log](https://github.com/Cazadorsniper/PO3/files/3139936/latest.log)

Latest.log might be irrelevant as it simply ends at the error, included just in case.

**Comment by OrbitStudios** [comment]
Same here, game is running with 8GB of RAM and still freezes (In case maybe it was related to RAM).

@Cazadorsniper do you know if it's related to the mod? The log doesn't seems to give that much information.

**Comment by Cazadorsniper** [comment]
Its DE that is causing that freeze.

**Comment by BeardedGamer0** [comment]
Yeah DE is opening in Pi for some reason... they dont like each other

**Comment by Cazadorsniper** [comment]
Should be fixed next update.
