### ISSUE TITLE
HELP!!!!! Something really bad is happening.

### ISSUE THREAD

**Issue by Cazitron** [Cazadorsniper/PO3#35]
**Pack Version:**   3.0.38

**Description:** First the screen started bugging out which i posted about already then when i log into the world this happens:

https://giphy.com/gifs/37qahp7zYOnbWhcoFR

**Comment by Cazitron** [comment]
WHAT THE HECK IS HAPPENING??? 

https://giphy.com/gifs/6CBFgwg1ZAYauMfnDI

**Comment by nzminecraftDOTcom** [comment]
Update your graphics drivers perhaps.

**Comment by iKurama** [comment]
Remove optifine.

**Comment by Cazitron** [comment]
My graphics card is up to date and i cant remove any mods but i did discover what cause it it was one of the better FPS algorithyms

**Comment by Cazitron** [comment]
And also removing a mod should never be your first option in troublshooting

**Comment by Cazadorsniper** [comment]
yeah try not to use certain algorithms
