### ISSUE TITLE
Jumping into the nether in creative gets you stuck in nether portal loop

### ISSUE THREAD

**Issue by sal69** [Cazadorsniper/PO3#350]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer. dedicated server

**Description:** So basically when you jump into the nether in creative mode, you get stuck in a nether portal loop, where you cant type, move, or do anything, besides look at the nether portal texture on your screen. Leaving the server and joining back just disconnects me and gives an "Internal server error". I've had to reset my playerdata like 3 times now because of this 

**Steps to reproduce:** 1. Go to creative. 2. Jump into nether

**Crash log (use pastebin or similar):** Game doesnt crash when this happens.

**Comment by pgudge** [comment]
I am getting something similar in adventure mode, when one of the players falls off the platform the player loads in a weird state with a red teleport mask. When the player disconnects and rejoins it just constantly disconnects.

The only way (other than deleting their userdata) was for me to go to the nether and jump on the server and /tp <user> <me> just as the player joins the game. I can see loads of exceptions, and ultimately the player was teleported confirmation, the user is that disconnected, re connect again they get an Internal Server Error, 2nd reconnect, joins as if nothing has happened!

**Comment by Cazadorsniper** [comment]
#332
