### ISSUE TITLE
[Suggestion] Not hide Creative Items from the JEI

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Cazadorsniper/PO3#351]
For testing reasons, like if i want to know if AE2 will autocraft correctly a X item. would be useful if i had an infinite source of X item and the Drawer creative upgrade is perfect for it.
Btw why u hided it?

**Comment by Cazadorsniper** [comment]
There is no recipe for it.

**Comment by ReiDaTecnologia** [comment]
ofc it's a creative item, and i will test it in the creative mode.

**Comment by Cazadorsniper** [comment]
There is no recipe for it therefore I will keep it hidden.

**Comment by ReiDaTecnologia** [comment]
so is just to show only the ones with the recipes that u make? at least exist a way to not hide it from the creative tab or only hide it in the survival mode? i can still get it if i use the /give command?

**Comment by Cazadorsniper** [comment]
If you can get it, good for you, the pack itself will continue to keep the ones without recipes hidden.

**Comment by ReiDaTecnologia** [comment]
Sad. U are a really different modpack dev with strange ways to do your modpacks.
