### ISSUE TITLE
[3.0.40] Crash upon loading into given dimension

### ISSUE THREAD

**Issue by MadsBTobiasen** [Cazadorsniper/PO3#352]
Usally happens the 4th time a dimension is loaded in my game, usally this happens if I:

Go to the End (1) -> Return to the OW (2) -> Return to the End (3) -> And Return to the OW and crash (4)

https://pastebin.com/Zzpb8pt1

**Comment by Cazadorsniper** [comment]
How fast are you changing dimensions?

**Comment by MadsBTobiasen** [comment]
Anywhere from 30 seconds to 2-5 minutes. However since reporting the issue, sometimes it seems to happen everytime i return to the overworld.

The crash logs are identical

**Comment by MadsBTobiasen** [comment]
If you'd like. I can throw my world into a zip and upload to Gdrive.

**Comment by Cazadorsniper** [comment]
You can

**Comment by MadsBTobiasen** [comment]
https://drive.google.com/open?id=1fW7GOPFU9KrnrtBPpKuuWtOsvrUZUK93

**Comment by Cazadorsniper** [comment]
Sorry this took a while, 
1. I like your world
2. I think you have too many entities in the overworld, that is why it may be crashing.
Had a lot of chickens and stuff was falling out of the water in your auto-sieving setup.

**Comment by MadsBTobiasen** [comment]
Thank you, so you reckon reducing the amount of entities would ultimately prevent the crashing?

**Comment by Cazadorsniper** [comment]
It might.
