### ISSUE TITLE
Unknown power/Unable to turn turn off new ability

### ISSUE THREAD

**Issue by fightmesun** [Cazadorsniper/PO3#353]
I think it's from Lordcraft but whenever I jump and land, it sends out a shock wave and hurts any mob around me. Not an ideal ability when I'm trekking through the neather. I've checked the enchantments both on my armour and the everlasting abilities and found nothing that would indicate the shockwave power.

**Comment by Cazadorsniper** [comment]
Try looking at your passive powers in the lordcraft book.

**Comment by fightmesun** [comment]
oh god it is. thank you so much!
