### ISSUE TITLE
Server opening crash

### ISSUE THREAD

**Issue by anilorex** [Cazadorsniper/PO3#354]
**Pack Version:** 
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
its trying to open server but at the end its crash and its exiting java 
**Steps to reproduce:**
Download server files --> launch forge-2836.jar --> edit server file to change the IP --> launch forge-2836.jar again
**Crash log (use pastebin or similar):**
https://hastebin.com/uwojibafes.rb

**Comment by Cazadorsniper** [comment]
Set max-tick-time to -1 in server.properties.

**Comment by anilorex** [comment]
Thank you, solved :)
