### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by TwigChaos** [Cazadorsniper/PO3#356]
Just recently, couldn't open up my game because it immediately crashes while ticking a block entity.
I updated my graphic card and drivers, so I don't know what to do. 
https://pastebin.com/SjdGgr2b

EDIT
Reinstalled the mod pack, still crashed while opening, https://pastebin.com/HzUXM258. new pastebin in case anything changed

EDIT EDIT
removed waiting time, and game wouldn't crash properly so I didn't get a crash report

**Comment by Cazadorsniper** [comment]
remove this block industrialforegoing:potion_enervator_tile some type of industrial foregoing machine is acting up.

**Comment by TwigChaos** [comment]
worked, thanks
