### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by Chickensate** [Cazadorsniper/PO3#357]
**Pack Version:**
3.0.40

**Singleplayer, Multiplayer, or LAN?:**
all of the above

**Description:**
i have been playing ozone 3 for about 10 days through the twitch app without a problem. all of a sudden when i tried to load the game it crashed. Now i cant seem to load the game in any way. Ive located enough ram, updated my java, updated my drivers and tried to uninstall and reinstall everything. Its stuck at 1/7 (constructing mod) 3/285(forge mod loader).
It is probably something easy so sorry in advance if im missing something stupid.

**Steps to reproduce:**
press play in the launcher.

**Crash log (use pastebin or similar):**
not really sure which one you need so im just going to post what i think is usefull, again sorry.

[crash_report_ozone_3.txt](https://github.com/Cazadorsniper/PO3/files/3145961/crash_report_ozone_3.txt)

**Comment by Cazadorsniper** [comment]
Can't tell what is wrong from that.

**Comment by Chickensate** [comment]
O sorry. Did i deliver the wrong file? How do i go about aquiring the right form of crash file?

**Comment by Chickensate** [comment]
Is this the right way to share it?
https://pastebin.com/Zzpb8pt1

**Comment by Chickensate** [comment]
I see i posted a txt file. Is that the problem is did give the wrong information altogether. This is the latest session log after a identical crash.

https://pastebin.com/LTbvPSgt

**Comment by Cazadorsniper** [comment]
What happens if you just try to let it load?

**Comment by Chickensate** [comment]
Nothing, had is sit when it says not responding for about an hour. The launcher log output is stating that FML found non-mod files AutoConfig-1.12.2-1.0.1.jar and AutoSave-1.12.2-1.0.10.jar which will cause severe stability issues and should be removed. However, when i remove they will just re appear. Is that something I should look into?

thanks for the help btw

**Comment by Cazadorsniper** [comment]
No, something else is happening, maybe check the memory in your storage device (HDD or SSD).

**Comment by Chickensate** [comment]
I let windows do a diagnostic on my storage device. no problems were detected

**Comment by Cazadorsniper** [comment]
can you go to your logs folder and give me both the debug.log and latest.log? Can try pressing the repair profile button on twitchapp too.

**Comment by Chickensate** [comment]
Tried the repair profie, didnt work. I see now that the launcher tells me there already is a version of minecraft running. I dont get a loading screen when I press play the first time in the loader as well.
In regards to the log files, there is no debug.log in my Ozone3 folder. Here is the latest.log
https://pastebin.com/nx7NEV1b

**Comment by Cazadorsniper** [comment]
Ok, go to your task manager then end the task called Java SE Binary (or whatever its called) then try to load again.

**Comment by Chickensate** [comment]
That doesnt work. everytime i restart my computer the first attempt to load minecraft doesnt result in anything. no java in my task manager but the launcher still gives the warning that the game is already running.

**Comment by nzminecraftDOTcom** [comment]
> Tried the repair profile, didnt work. I see now that the launcher tells me there already is a version of minecraft running. I dont get a loading screen when I press play the first time in the loader as well.
> In regards to the log files, there is no debug.log in my Ozone3 folder. Here is the latest.log
> https://pastebin.com/nx7NEV1b

Just looking at that log, Are you loading the pack properly? 
"[17:48:50] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, additionalresources, creativecoredummy, itemphysic, micdoodlecore, openmodscore, biometweakercore, foamfixcore, opencomputers|core, randompatches, acintegration, abyssalcraft, actuallyadditions, ae2stuff, ae2wtlib, agricraft, akashictome, apotheosis, applecore, appleskin, appliedenergistics2, armorplus.....[list continues] "

**Comment by Chickensate** [comment]
soo, turns out task manager wasnt showing the other minecraft in progress. i ended that isntance of it and it loaded. so now i just do that on ever start up. thanks for all the help!

**Comment by Cazadorsniper** [comment]
Ok, but may want to look up why that instance stayed open, I have no clue.
