### ISSUE TITLE
Lordcraft uplift spell crashes game

### ISSUE THREAD

**Issue by iwanami** [Cazadorsniper/PO3#358]
Pack Version:
3.0.40

Singleplayer, Multiplayer, or LAN?:
LAN  (I'm hosting, 2 players)

Description:
game crashes when I use Lordcraft's uplift spell, apparently only on another player character. 

Steps to reproduce:
use uplift spell on a mate, and/or the quest guys in Lordcraft's nexus

Crash log (use pastebin or similar):
https://pastebin.com/PdUKsYst

**Comment by Cazadorsniper** [comment]
So using the spell on players and the Lordcraft npc's causes this? Have you tried not using it on those entities?

**Comment by iwanami** [comment]
well duh  xD
still signaling the bug ^^
