### ISSUE TITLE
Sugar and cactus grow to max build height

### ISSUE THREAD

**Issue by pacman1983** [Cazadorsniper/PO3#359]
**Pack Version:** 3.0.40
**Single Player**, **Multiplayer**, **LAN**: Multiplayer

**Description:** The cactus and sugar cane plants grow to max build height. See attached picture.

**Steps to reproduce:** Plant some cactus or sugar cane and watch it grow. I have a chunk loader to grow sugar.

**Crash log (use pastebin or similar):**

![2019-05-05_18 05 32](https://user-images.githubusercontent.com/43517048/57218889-7fce2400-6fc4-11e9-8fbe-fea0ed5da386.png)

**Comment by ImJustJoshin** [comment]
Apotheosis is the mod that does this. In case you were wondering.
