### ISSUE TITLE
Anti-Barrel broken

### ISSUE THREAD

**Issue by FaveAsian** [Cazadorsniper/PO3#36]
**Pack Version:**
3.0.38
**Description:**
The anti-barrel won't let me take things out of the barrel. It goes into my inventory. When I click on it it disappears and returns to the barrel. It requires an conduit or node to remove the items. 
**Steps to reproduce:**
absorption hopper pumps non stackable item to anti-barrel. Try to remove and bug appears. 
**Crash log:**

**Comment by martinschuberteu** [comment]
I have the same issue with a Soulium Dagger that is "stuck" in the anti-barrel of my mob farm. Thank you for the tip with removing it with a conduit. I did not think about that...

**Comment by sLpFhaWK** [comment]
I have this issue with some wand that lets you fly with chicken feathers, I forget the name at the moment but when you use the item it crashes the server, and even though i've tossed it into the void it still remains in the anti barrel. and I Cannot remove it, will try this later.

**Comment by quietust** [comment]
Somebody reported this exact same issue on the old CurseForge tracker, and one workaround (which I've personally confirmed to work) was to place the anti-barrel on top of a vanilla Hopper
