### ISSUE TITLE
Enderman can break machines/drawers even when griefprotected

### ISSUE THREAD

**Issue by zeromic** [Cazadorsniper/PO3#360]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
SP
**Description:**
Enderman can break blocks when aggro, even on griefprotected/claimed chunks(ftbutils).
They even can break drawers with 1000+ stacks of items spilling them and crash/ lag the game into obilivion.
**Steps to reproduce:**
aggro enderman, hide behind filled drawer > boom!
**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Don't hide behind drawers?

**Comment by ImJustJoshin** [comment]
Enderman Evolution prevents players from cheesing enderman by hiding behind blocks or cowering in two block high spaces by allowing the Enderman to destroy blocks if aggro'd. So yeah, don't hide behind drawers.

**Comment by zeromic** [comment]
if the behavior is intended thats good for me. Hope nobody use it to grief on MP.
