### ISSUE TITLE
World leakage problem

### ISSUE THREAD

**Issue by pokermanx** [Cazadorsniper/PO3#361]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Everything seemed to be fine at the start, and after few hours hunting dimension started to lag crazy and crash the game (only the hunting world)
**Crash log (use pastebin or similar):**
debug: https://pastebin.com/FEW0qtKj
log: https://pastebin.com/Lr7DPkTL

**Comment by pokermanx** [comment]
Temporary solution - delete the `DIM14` folder from save folder (backup first)

**Comment by pokermanx** [comment]
Update: Twilight Forest now leaks too

**Comment by Cazadorsniper** [comment]
Well there is a lot going on in the Twilight Forest.

**Comment by pokermanx** [comment]
> Well there is a lot going on in the Twilight Forest.

Will allocating more RAM help?

**Comment by Cazadorsniper** [comment]
Most likely no.

**Comment by Cazadorsniper** [comment]
Best to figure out why its happening, could be too many entities.

**Comment by Cazadorsniper** [comment]
Or you could be generating too many chunks.

**Comment by pokermanx** [comment]
Nope, just going through the stronghold, like 15 mins on game start and the game completely hangs,  chunks stop rendering, mobs stop moving, i can`t do anything. Exiting just freezes the game so i have to force close it. Looked into debug - saw the world leakage logs

**Comment by Cazadorsniper** [comment]
can i see the debug and latest log?

**Comment by pokermanx** [comment]
log: https://pastebin.com/Gh9peFu7
debug: https://pastebin.com/3mhP41Sh

**Comment by Cazadorsniper** [comment]
try turning on the forge.cfg options on line 59 and 62.

**Comment by pokermanx** [comment]
Seems to be fixed now, ty!
