### ISSUE TITLE
Tau Questline - Metallurgic Infuser - Issue not resolved.

### ISSUE THREAD

**Issue by lauchlinmac** [Cazadorsniper/PO3#363]
3.0.40 (Happened in 39 as well)
Singleplayer

Found this issue closed multiple times.   Tau questline - Metallurgic Infuser crafted but quest not detecting (even when I click on detect/submit).   

Crafted multiples.  Broke, picked up.   
Restarted from Main Game Screen.
Completely closed and restarted from Twitch launcher.

No crash involved.

**Comment by lauchlinmac** [comment]
I realize this is a duplicate issue, though none of the previous issues were explained nor resolved.

**Comment by saulysw** [comment]
I had this issue too, but it detected the Metallurgic Infuser in 3.0.40 for me. There is a prerequisite (sorry, I can't recall exactly what) - have you done that first? If you hover over the quest item it tells you in red text.

**Comment by lauchlinmac** [comment]
I'm not familiar with that, though this is what it shows 
![image](https://user-images.githubusercontent.com/8878872/57460827-dbf2ab80-7243-11e9-8408-e165a0b5dda3.png)

**Comment by Cazadorsniper** [comment]
can you try "/bq_admin default load" without the quotes for me?

**Comment by lauchlinmac** [comment]
I did.  Once I put it in my inventory, it cleared it.  Thank you.  How often should this be run??
![image](https://user-images.githubusercontent.com/8878872/57471757-e15af080-7259-11e9-898e-4c1adcd23b2c.png)

**Comment by Cazadorsniper** [comment]
Should only need to be run once, after updating the pack from a previous version.
