### ISSUE TITLE
Aroma1997 is crashing game on load up

### ISSUE THREAD

**Issue by Holdster** [Cazadorsniper/PO3#364]
issue: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aroma1997's Dimensional World (aroma1997sdimension)

**Comment by Holdster** [comment]
Pack Version: 3.0.40

Singleplayer, Multiplayer, or LAN?: singlelayer

Description: World crash upon game at stage 2

Steps to reproduce: starting game

Crash log (use pastebin or similar): crash-2019-05-09_10.49.46-client

**Comment by Holdster** [comment]
[crash-2019-05-09_10.49.46-client.txt](https://github.com/Cazadorsniper/PO3/files/3163675/crash-2019-05-09_10.49.46-client.txt)
how do i fix the aroma1997 mod from crashing my game?
pastebin: https://pastebin.com/GPSxdAvT

**Comment by Holdster** [comment]
i did try taking out the aroma mod and that fixed it but i didnt open a world

**Comment by Cazadorsniper** [comment]
Have you tried :

1. Going into the world file and removing DIM-6 folder
2. Removing Optifine

**Comment by Holdster** [comment]
i just tried both and that did not work

**Comment by Cazadorsniper** [comment]
reinstall the pack then move your world save over.

**Comment by Holdster** [comment]
report on reinstalling the mod pack, everything is working, thank you!
