### ISSUE TITLE
[3.0.40] Crash while generating tree

### ISSUE THREAD

**Issue by Ghost942** [Cazadorsniper/PO3#365]
**Pack Version:** 3.0.40

**Singleplayer, Multiplayer, or LAN?:** Multiplayer Server

**Description:** World crash upon attempting to generate a tree

**Steps to reproduce:** Unknown

**Crash log (use pastebin or similar):** [Pastebin Link](https://pastebin.com/ArUeLNvz)

**Comment by Cazadorsniper** [comment]
Can you try again with "Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation" and not "OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation"?

**Comment by Ghost942** [comment]
Working on it, will get back once we get it fixed

**Comment by Ghost942** [comment]
Changing versions did not help

**Comment by Cazadorsniper** [comment]
This crash might be due to skylands.
