### ISSUE TITLE
Actually Additions Fluid Cows Not Spawning

### ISSUE THREAD

**Issue by BananaTassium** [Cazadorsniper/PO3#366]
I've been trying to get all the possible fluid cows as a bit of a mini sidequest, but when I was comparing my list of cows to the config I noticed that the four actually additions oil cows were supposedly listed but not actually spawnable, as I spawned several hundred and never found a single one. I also noticed that there was a slight grammatical difference before listing all the options of said fluid cows, but supposedly that doesn't mean anything. Putting an issue here because I'd presume this is an actual error, but it is possible that it might not be.

**Comment by Cazadorsniper** [comment]
I turned off all but the canola oil cow for next update, not sure if it will spawn or not though.
