### ISSUE TITLE
[3.0.40] Exception in Server Tick Loop

### ISSUE THREAD

**Issue by Ghost942** [Cazadorsniper/PO3#367]
**Pack Version:** 3.0.40

**Singleplayer, Multiplayer, or LAN?:** Multiplayer Server

**Description:** Server crash, unknown cause, possible due to Nether generation

**Steps to reproduce:** Unknown

**Crash log (use pastebin or similar):** [Pastebin Link](https://pastebin.com/tX94NLwi)

**Comment by Cazadorsniper** [comment]
Does it work without sponge?

**Comment by Ghost942** [comment]
Indeed it does. We've been trying things out, but a lot of things happens behind my back and I'm not able to see what actually happened. For now, I'll just keep posting crash reports in case something is actually broken and does require fixing

**Comment by Cazadorsniper** [comment]
Have you tried a Java version that isn't "OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation"?

**Comment by Ghost942** [comment]
Trying to work on it, hitting a few roadblocks. Will get back to you when we find an alternative

**Comment by Ghost942** [comment]
Tried changing, still crashing sometimes

**Comment by KindarConrath** [comment]
Also on the server, we are investigating. Possibly related to #332

**Comment by Cazadorsniper** [comment]
Could be an issue with Skylands then. Can you try default world or Garden of Glass?

**Comment by Cazadorsniper** [comment]
Do you have something that causes anvils to become chunkloaders?

**Comment by Ghost942** [comment]
Not that we're aware of. This is a fresh install that is doing this

**Comment by KindarConrath** [comment]
Confirmed, Anvil is the name of the world generator, its caused by the same issue as #332

**Comment by Ghost942** [comment]
Closing ticket, refer to ticket #332
