### ISSUE TITLE
Quibit Cluster quest line in Theta tab - Issue with detection

### ISSUE THREAD

**Issue by Naschen** [Cazadorsniper/PO3#368]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Having an item that chargers items in your inventory while crafting Quibit clusters results in the quest book not detecting that you have the item. (tested levels 1 -3).
**Related:** Quibit cluster with charge will not auto-fill into crafting grids from JEI.

**Steps to reproduce:** Have a spectre charger in your inventory and craft Quibit cluster level 1.

**Crash log (use pastebin or similar):** No crash

**Comment by Cazadorsniper** [comment]
This is because the data changes within the block when its charged, can't do anything about it not auto-filling, might be able to do something about the quests though.

**Comment by Naschen** [comment]
I would have thought that maybe there would be some way to fuzzy match/ignore some of the block data if you so chose. though on further thought I guess I'm just getting confused with the way ore dictionary items work in game.

The vibrant capacitor bank quest in the Eta tab can detect the item with some charge.
Was clicking about in the quest book for other things that might have the same problem and noticed that that tool tips for capacitor banks had partial charges on them and was able to quickly check if that one worked.

The rftools charged porter is the same in that it doesn't auto-detect a charged item. The jetpack quests and any of the armour quests that accept power will probably also need to be looked at.
Even if for some reason you can't make the auto-detect work, some sort of warning text in the quest itself might be useful.

**Comment by Cazadorsniper** [comment]
Or just don't charge the armor before the quest detects it.

**Comment by Naschen** [comment]
You can say that about the other things as well.
From the view point of some one just playing the pack, they wouldn't see why there would be any real difference between an item with charge and same item with out charge.

It's just a minor annoyance if you know it can happen, hence my suggestion of some warning text.

**Comment by Cazadorsniper** [comment]
No warning text, but I did fix it.
