### ISSUE TITLE
[3.0.40] Furnace overhaul - Ore processing upgrade (unexpected smelting result)

### ISSUE THREAD

**Issue by Naschen** [Cazadorsniper/PO3#369]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** smelting Umbercobble from the Erebus mod or kepler 22b cobblestone from extra planets from extra planets in a Furnace overhaul furnace with the ore processing upgrade in it results in the output of 2 minecraft stone and the furnace stopping.
Removing the ore processing upgrade results in the expected results of Umberstone and kepler 22b stone respectively.

**Steps to reproduce:** have a Furnace overhaul furnace with the ore processing upgrade in it and attempt to smelt Umbercobble

**Crash log (use pastebin or similar):** No crash

**Comment by Cazadorsniper** [comment]
They both ore dict with minecraft stone.

**Comment by Naschen** [comment]
Ok, so you've found out why it's doing it.

The issue being both varieties of cobble have smelting recipes to turn into the stone version of that block, which the ore processing upgrade break.

and not only that, smelting them with the upgrade results in the furnace cooking one Umbercobble and outputting 2 stone. Then it stops and you need to remove the stone before it will do anything.

Honestly the more I think of it, the more it sounds like a mod bug. Rather than a pack bug and I probably should have posted it over there instead. 
Especially considering every other method I've tried cooking umbercobble with, including the furnace overhaul furnace without the upgrade. Results in the correct output and it's only the ore processing upgrade that breaks the smelting recipe, by apparently doing it's own thing and ignoring the smelting recipe.

**Comment by Cazadorsniper** [comment]
The ore processing upgrade uses ore dict to process items and double them.
