### ISSUE TITLE
Can not Enchant Hell-Infused Bookshelf with Night Vision X

### ISSUE THREAD

**Issue by rrcharles** [Cazadorsniper/PO3#370]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
  "name": "PO3",
  "version": "3.0.40"

**Description:**
Mod: Apotheosis

1) The first bug it that Apotheosis has an incorrect setting:
in the config/apotheosis/enchantments.cfg

"astralsorcery:enchantment" {
    as {
        nightvision {
            # The max level of this enchantment. [range: 1 ~ 127, default: 1]
            I:"Max Level"=1
    }
Should be
---> I:"Max Level"=10

2) The Hell-Infused Bookshelf will not take the enchantment of Night Vision at any level.
JEI show Night Vision 1 to X as a Recipe but the Anvil will not allow it.
I also tried using Industrial Forgoing Enchant Applicator and
Botania Enchanting ritual.

**Steps to reproduce:**
Get a Night Vision X book and a Hell-Infused Bookshelf and put them in the Anvil.

**Crash log (use pastebin or similar):**
No crash,  Game Play BUG

Good Pack Thank You, Robert

**Comment by Cazadorsniper** [comment]
That config is correct and that recipe is the result of enchantment ids switching around in your instance.

**Comment by rrcharles** [comment]
I don't understand, is the recipe wrong in the pack ?
What do you mean by "enchantment ids switching around in your instance"?
How can I get a level 10 enchantment that is restricted to level 1?
And, how can I apply it to an item that is restricted from enchanting ?

I am glad you took the time to answer, but that is not an answer.  Where should I start looking to fix the problem, a file name, anything other than "your problem is not a problem"

Thank you, Robert

**Comment by rrcharles** [comment]
I have found the ISSUE...  Quori Fragment Recipe not crafting #304 https://github.com/Cazadorsniper/PO3/issues/304

The enchantment ID .withTag({ench: [{lvl: 10 as short, id: 69 as short}]})
69 is meant to be "Hell Infusion" not "Night Vision", this is the issue....

Trying to find out how to tell minecraft to use id:69 for "Hell Infusion" ???

**Comment by rrcharles** [comment]
I could not find a way to switch the ID back, my instance is calling "Hell Infusion" id:75
I adjusted the recipe and everything works fine.

This can be closed as a DUPLICATE
