### ISSUE TITLE
tinkers item rack recipe produces planks

### ISSUE THREAD

**Issue by chrisisonwildcode** [Cazadorsniper/PO3#371]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** single player

**Description:**
When trying to produce a tinkers item rack (2 wooden slabs side by side) in a crafting table the result is planks, even if using JEI recipe.

**Steps to reproduce:**
Place a crafting table, place 2 wooden slabs side by side (or select tinkers item rack via jei while wooden slabs in inventory). Tested with vanilla and tinkers crafting table.

**Crash log (use pastebin or similar):**
NA (no crash)

**Comment by Cazadorsniper** [comment]
Likely just a recipe conflict.

**Comment by Cazadorsniper** [comment]
I can fix it, but you will likely only be able to make oak item racks afterwards, is that fine?

**Comment by chrisisonwildcode** [comment]
that's fine with me, not sure about anyone else. I'm not sure how to check but if the planks from slabs recipe is shapeless, making it shaped instead would help. IE: one slab on top of another in a crafting table be a plank, one slab beside another be a rack.

**Comment by Cazadorsniper** [comment]
The problem is that the plank recipes are done by config from Ender Core I believe (so I don't mess with this definitely considering that there is a lot of different woods in the pack), and the different item racks are separated by nbt data.

**Comment by tyler489** [comment]
The tinkers drying rack is 3 slabs
