### ISSUE TITLE
[3.0.40] Returning/Being in Landia causes "Exception ticking world" causing server crash

### ISSUE THREAD

**Issue by michaelasper** [Cazadorsniper/PO3#372]
**Pack Version:**

3.0.40 

**Singleplayer, Multiplayer, or LAN?:**

Multiplayer

**Description:**

Not sure exactly, but it seems like *randomly* being and/or returning from landia likes to crash the entire server. Server crashed on 3 instances, two of them a player was returning to the overworld from landia. The third one someone was just exploring it and that one even made the entire client crash

**Steps to reproduce:**

Expore Landia?

**Crash log (use pastebin or similar):**

[crash-2019-05-12_09.26.49-server.txt](https://pastebin.com/qHHzagXD)
[crash-2019-05-12_09.38.14-server.txt](https://pastebin.com/5tCfvC3k)
[crash-2019-05-12_09.49.59-server.txt](https://pastebin.com/HjfSDeNL)

**Comment by michaelasper** [comment]
There are three pastebin links on the bottom of the issue, do they not work for you?

**Comment by Cazadorsniper** [comment]
Best not to rename links in the future, just keep the link unedited.
Now what exactly are you doing in Landia and the Overworld?

**Comment by michaelasper** [comment]
So far, we've basically explored ravine and haven't done much. We found a few ores we've been trying to get Kelline and Racheline, but couldn't mine em yet (lack of tools)

Crash is very consistent upon return

**Comment by Cazadorsniper** [comment]
What are you using to get back?

**Comment by michaelasper** [comment]
Sorry for delay, but I came back using the default way. The little blue egg portal light

**Comment by Cazadorsniper** [comment]
Do you have a lot of entities in the Overworld? (Like sieve setup overflow, mob drop overflow or a lot of chickens cows or pigs.)
