### ISSUE TITLE
Server crash only when I load in.

### ISSUE THREAD

**Issue by KillerJWB86** [Cazadorsniper/PO3#374]
Multiplayer

**Description:** Everytime I load into my server it crashes,Its just me,everyone else can log into the server just fine.I think it is the chuck I am in but im not sure.I have removed my playeyer dat and then I can log in jsut fine but if i head south from my base it happens again.I can uplaod the world if someone wants to test it.

**Steps to reproduce:**It happens only when i log into the world

**Crash log (use pastebin or similar):**
https://pastebin.com/tSmBsW8W

EDIT: another crash just happend,not sure if this has something to do with the other crash
https://pastebin.com/kAHvN3U1

**Comment by Cazadorsniper** [comment]
The first crash, did you fall off your platform into the nether?
The second crash, in server.properties turn max-tick-time to -1.

**Comment by KillerJWB86** [comment]
about the first crash,no.I am playing this pack on a normal generated world so we cant fall off the world.
about the second crash, I will set my config to that now,thx

**Comment by Cazadorsniper** [comment]
It maybe possible that an item in your inventory is bugged and needs to be removed.

**Comment by KillerJWB86** [comment]
> It maybe possible that an item in your inventory is bugged and needs to be removed.

I dont think so cause it is happening to anyone that goes south of our base.I can upload the world in about a hour when everyone gets off of the server.

**Comment by Cazadorsniper** [comment]
you can try using the delete erroring entities/tileentity config in forge.cfg

**Comment by KillerJWB86** [comment]
I have not done that before.Can you link me to somewhere that will tell me how to do that or can you give me a quick run down.
Here is the link the the whole server files

Here is the link to just the world folder
Our base it at x -744  z -864  y 67
If you head south from our base you will cross two rivers,as soon as you hit the desert the server will crash and every time that person that went there logs it the server will crash again.
Here is a link to the screenshot of where it happens
http://prntscr.com/no632d

**Comment by Cazadorsniper** [comment]
you go to the config folder then scroll until you see forge.cfg.

**Comment by KillerJWB86** [comment]
> you go to the config folder then scroll until you see forge.cfg.

I knew that but what lines do i turn to true.I did not see any of them that said entities/tileentity.

**Comment by Cazadorsniper** [comment]
lines 59 and 62
