### ISSUE TITLE
Chunk Generator crash

### ISSUE THREAD

**Issue by ARennex** [Cazadorsniper/PO3#375]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Exploring the world (cities in a bubble type world), entered a new bubble and minecraft instantly crashed to desktop. View distance was set quite high, so it may hav ebeen a distant chuck causing the issue?
**Steps to reproduce:**
Floating bubble city world gen. World was created several patches ago (early march), and no previous world gen crashes have been observed. Exploring new areas and game suddenly crashed to desktop. Attempts to repair profile had no effect.
**Crash log (use pastebin or similar):**
https://pastebin.com/qBsfK8ij

**Comment by Cazadorsniper** [comment]
try updating Lost Cities and other associated mods and try again.

**Comment by ARennex** [comment]
Updating Lost Cities did not help initially, but updating Lost Cities and deleting the existing chucks with MCEdit did fix the issue.
