### ISSUE TITLE
AE2 Crafting storage blocks not duplicating correctly

### ISSUE THREAD

**Issue by saulysw** [Cazadorsniper/PO3#376]
**Pack Version: 3.0.40**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: MINOR SPOILER AHEAD**
When trying to duplicate a 64K crafting storage block via wand of animation / mob duplicator, the resultant block has a black/purple texture. While the normal block can be crafted back to a 64K component (even though it is not actually in JEI as a recipe, it works on a crafting table), the duplicated block does not. The duplicated block also does not have an EMC value. When duplicated block is placed however, it reverts to the correct texture and acts as a 64K crafting storage block ok. Breaking it again with a pick reverts it back to purple/black.  I have only tried with a 64K block, but it may well be the same for other sized storage blocks.

**Steps to reproduce:**

1. Use the Wand of animation on a placed 64K storage block.
2. Capture mob with a Mob imprisonment Tool
3. Put in a mob duplicator, kill mobs
4. Blocks dropped have purple/black texture and do not craft to components or have EMC, like the original block does.

**Crash log (use pastebin or similar): No crash, so no crash log**

**Comment by Cazadorsniper** [comment]
That is a block you can't duplicate without its data becoming screwy.

**Comment by saulysw** [comment]
Pity. I thought I was being a little bit clever by trying. Doesn't happen often!
