### ISSUE TITLE
Server crash when players login in 

### ISSUE THREAD

**Issue by Feszubial** [Cazadorsniper/PO3#377]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer in OMGServ 

**Description:** Server crash when players login in. No touch blocks for the crash server

**Steps to reproduce:** Launch server, login in and Tadammm ! It's a crash #ironiclaughterandembarrass

**Crash log (use pastebin or similar):**   https://pastebin.com/k6thKs3c

**Comment by Cazadorsniper** [comment]
in server.properties turn max-tick-time to -1

**Comment by nzminecraftDOTcom** [comment]
Something is overloading your server. Check for items on the ground, machines running, people moving too fast etc.
