### ISSUE TITLE
Ender IO makes my forge freeze during 4/7 initialization phase

### ISSUE THREAD

**Issue by Moni5** [Cazadorsniper/PO3#378]
**Pack Version:**
3.0.40

**Singleplayer**

**Description**
So i've been trying to launch the modpack for an eternity now, and it keeps crashing on 4/7 on mod number 32 which is Ender IO or it loads Ender IO but then crashes before i see the title screen at 7/7. I have tried disabling the splash screen, allocating more ram , reinstalling the pack and even the twitch app but it just does the same thing. Also my drivers and Java are fully up to date
I have never gotten to play the pack or even seen the title screen it makes me wanna pull my hair out

**Steps to reproduce:**
Open twitch, install pack, launch pack and wait until it inevitably crashes

**Crash log**
https://gist.github.com/Moni5/b41f87b2750b81e8cd28f117c1da2031

**Comment by Moni5** [comment]
there, it was too big for pastebin so used github gist

**Comment by Cazadorsniper** [comment]
can you try loading it up again? If it crashes then get the crash report.

**Comment by Moni5** [comment]
https://gist.github.com/Moni5/d470c37586475a833a61213021041f2b

**Comment by Moni5** [comment]
it stops responding at the moment in the picture
![crash](https://user-images.githubusercontent.com/50676028/57805753-3e790980-7766-11e9-9945-54b6c6c428f2.png)

**Comment by Cazadorsniper** [comment]
can you try installing the pack using multimc? I don't know much about multimc so I can't walk you through it.

**Comment by Moni5** [comment]
everything even the crash log is the exact same when i try it with multi mc

**Comment by Cazadorsniper** [comment]
Have you tried letting it load?

**Comment by Moni5** [comment]
wait it doesnt stop ressponding anymore it actually loaded multi mc works! Thank You!
