### ISSUE TITLE
world freezing

### ISSUE THREAD

**Issue by vicrules97** [Cazadorsniper/PO3#380]
project ozone 3 Version 3.0.40
single player
Hello love your project ozone modpacks but when i try to leave my po3 world it freezes and i have to open task manger to end game i was wonder why it's freezing when i leave it?

**Comment by Cazadorsniper** [comment]
I have no idea without a log.

**Comment by vicrules97** [comment]
Hello again here is a copy of my last crash report and a pix of what i get when i have to us task manger.

[crash-2019-05-16_05.21.28-server.txt](https://github.com/Cazadorsniper/PO3/files/3189577/crash-2019-05-16_05.21.28-server.txt)

![Minecraft Launcher 5_16_2019 8_40_17 PM](https://user-images.githubusercontent.com/36473132/57897564-fc5dcf80-781a-11e9-8a01-2c929344d1df.png)

**Comment by Cazadorsniper** [comment]
What armor were you wearing? That is the cause, try to find a way to remove the armor.
