### ISSUE TITLE
World not on Skyblock

### ISSUE THREAD

**Issue by starwars02823** [Cazadorsniper/PO3#381]
I changed the level type to botania-skyblock, but I spawned into a default world. I am new to making servers, and help would be greatly appreciated.

**Comment by starwars02823** [comment]
I've tried deleting the world file, deleting the sever.properties, and remaking them, but that hasn't worked. Here are the properties:
#Minecraft server properties
#Thu May 16 17:45:39 EDT 2019
spawn-protection=16
max-tick-time=-1
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=botania-skyblock
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=(My server ip)
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
motd=DLM PO3
enable-rcon=false

**Comment by Cazadorsniper** [comment]
Did you start the server using the forge.jar?
