### ISSUE TITLE
Extreme reactor duplication bug

### ISSUE THREAD

**Issue by gravy1333** [Cazadorsniper/PO3#383]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Single player
**Description:**
Use of a builder's wand on any extreme reactor block that can be used in the multi block stuctures duplicates it without the item even needing to be in your inventory. This allows for easy infinite emc and extreme reactrors block. It will duplicate for every block in your inventory that belongs to that mod.
**Steps to reproduce:**
Have extreme reactor blocks in inventory
Place one down
throw blocks into transmutation table
use builders wand on block
**Crash log (use pastebin or similar):**

**Comment by gravy1333** [comment]
Ignore this I was wrong. Builder's wand just pulls from you personal emc to create the blocks.

**Comment by Cazadorsniper** [comment]
lol
