### ISSUE TITLE
Can't connect two Ender IO alloy smelters to AE2 system

### ISSUE THREAD

**Issue by MartsLV** [Cazadorsniper/PO3#385]
**Pack Version:**Project Ozone 3 A New Way Forward 3.0.40.
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
I wanted to connect a second enhanced alloy smelter to my AE2 auto crafting system using ME Interfaces. When I put a ME Interface on the second enhanced alloy smelter and a regular alloy smelter the first ME Interface on the first alloy smelter goes offline and  in tooltips saying "Device missing channel" but it has 6 channels available.
**Steps to reproduce:**
Make an Applied Energistics 2  system, connect 2 alloy smelters

**Comment by fightmesun** [comment]
I'm having a similair issue to this as well though mine is more spread wide. Random buses or interfaces go offline when I add another machine or attachment to the system. Sometimes removing and changing the location of connection helps but not always. I've attached some pictures of my layout so hopefully that helps. 
![Annotation 2019-05-18 124211](https://user-images.githubusercontent.com/46666382/57974345-9d5ba000-796b-11e9-8921-a6e4917d7f5b.png)
![Annotation 2019-05-18 124303](https://user-images.githubusercontent.com/46666382/57974346-9d5ba000-796b-11e9-80ac-7c7576394ea7.png)
![Annotation 2019-05-18 124601](https://user-images.githubusercontent.com/46666382/57974347-9d5ba000-796b-11e9-84c3-4e281274b56a.png)
![Annotation 2019-05-18 124652](https://user-images.githubusercontent.com/46666382/57974348-9d5ba000-796b-11e9-8a5f-660923f0c6ed.png)
![Annotation 2019-05-18 124730](https://user-images.githubusercontent.com/46666382/57974349-9df43680-796b-11e9-8332-c9ac822f5363.png)
