### ISSUE TITLE
Forge Freeze during load

### ISSUE THREAD

**Issue by LordFizban** [Cazadorsniper/PO3#386]
**Pack Version:3.0.40**
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer \ Multiplayer
**Description:**
Forge launcher freezes during load. Used to work fine a couple of days ago but now it keeps freezing and eventually going into not responding mode at precisely 4/7 on mod enderio (number 32)

Thought it was related to issue #378 as we have the launcher freezes at precisely same point however, following all the steps there and eventually switching to multimc did not help. 
**Steps to reproduce:**
Either with twitchlauncher or multimc, install modpack and just load it.
**Crash log (use pastebin or similar):**
https://gist.github.com/LordFizban/56ab2d11ce235467ab92b3c20c8919bd

**Comment by nzminecraftDOTcom** [comment]
Tried re-installing it?
Got any sort of crash reports from the game?

**Comment by LordFizban** [comment]
So far I have tried the following:

Reinstall modpack
Reinstall Mc

Still no result. As the launcher freezes instead of crashing there is no crash log per se. I have to manually kill the process myself.

**Comment by Cazadorsniper** [comment]
Have you tried just letting it load?

**Comment by LordFizban** [comment]
Yes, for about 30 minutes after the Ender IO phase. Afterwards I gave up since this pack used to load under 15 (with no freezes in between). By the way, I see absolutely no cpu usage in task manager while it is trying to load ender io. Removed waitingtime mod to see if there is a difference, no difference so far.

However, I have noticed something different in crash log this time:

[18:29:04] [Client thread/INFO] [draconicevolution]: Finished Initialization
**Exception in thread "VoidCraft Contributor Loader"**  (This did not appear before)
Process crashed with exitcode -805306369.

**Comment by Cazadorsniper** [comment]
Do you have discord open when starting minecraft? I searched that error code up and it mentioned something about Discord's Game Overlay.

**Comment by Cazadorsniper** [comment]
Also can you try updating Ender IO and other related mods.

**Comment by LordFizban** [comment]
I don't have discord but did shut down steam thinking it also has a game overlay. This time error code changed to -1. 

Will try updating Ender IO and other mods soon.

**Comment by LordFizban** [comment]
Tried updating Ender IO and Draconic Evolution (Since this is the last item in log), issue remains.

**Comment by Cazadorsniper** [comment]
It may be possible that the pack isn't downloading completely at the time you're downloading it. Or a setting on your pc is preventing it from starting (gpu setting, windows firewall, antivirus software).

**Comment by LordFizban** [comment]
Here is what I did:

1. Shut down AV
2. Disabled FW
3. Manually downloaded modpack from Curse (Used to grab it via Multimc)

The result is the same. Although further testing reveals that I seem to have the same issue in some other modpacks (but not all).

**Comment by Cazadorsniper** [comment]
So its not pack specific then which means something on your pc doesn't want you to play, Have you tried updating Java?

**Comment by LordFizban** [comment]
I am using the latest java version (.211). So far reinstalling it did not resolve the issue. What's strange is I can run some packs (i.e stone block 1) but can't run others. Unable to find a pattern here...

**Comment by Cazadorsniper** [comment]
I really don't understand what the problem could be.

**Comment by LordFizban** [comment]
I seem to have solved this problem by doing the following:

Fixed MC resolution to my Desktop resolution,
Reduced Max memory to 8GB.

It works now, thank you for your support.
