### ISSUE TITLE
[Game Crash] Game crashong upon loading

### ISSUE THREAD

**Issue by irondragon12** [Cazadorsniper/PO3#387]
Pack Version:3.0.40
Singleplayer

Description: once game finishes launching the launcher it crashes

Steps to reproduce: just launch the game

[BGiS29MR.txt](https://github.com/Cazadorsniper/PO3/files/3194648/BGiS29MR.txt)

**Comment by irondragon12** [comment]
i cant figure out how to put my crash report in pastebin

**Comment by Cazadorsniper** [comment]
copy and paste

**Comment by irondragon12** [comment]
> copy and paste the link here.

oh ok

**Comment by irondragon12** [comment]
https://pastebin.com/BGiS29MR

**Comment by Cazadorsniper** [comment]
Do you have any armorplus armor on or looking at one of it's armors tolltips?

**Comment by irondragon12** [comment]
i dont think so. why? btw i cant even click on singleplayer to get to any worlds i cant even get the the main menu.

**Comment by Cazadorsniper** [comment]
Try reinstalling the pack.

**Comment by irondragon12** [comment]
how do i install another one without deleting my other one?

**Comment by Cazadorsniper** [comment]
If using Twitchapp just find PO3 on the list of packs, click on it, then go to versions.

**Comment by Cazadorsniper** [comment]
Ok found what was causing this issue. I reported it to the mod dev.

**Comment by WarlenSilveira** [comment]
I have the same problem... 
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)"

**Comment by Cazadorsniper** [comment]
that is not the same issue.

**Comment by irondragon12** [comment]
thx!! but which mod was it?

**Comment by Cazadorsniper** [comment]
Armor+

**Comment by WarlenSilveira** [comment]
> that is not the same issue.

Well. It crashes on loading... 

I will delete the mode and reinstall that to try again and, if I receive other error message. I'll make a new comment.

**Comment by WarlenSilveira** [comment]
Here are the new crash report...
[crash-2019-05-26_08.17.10-client.txt](https://github.com/Cazadorsniper/PO3/files/3220246/crash-2019-05-26_08.17.10-client.txt)

**Comment by Cazadorsniper** [comment]
please make a new issue, don't hijack someone elses.

**Comment by irondragon12** [comment]
so when is the update? got an ETA yet?

**Comment by Cazadorsniper** [comment]
Working on Titan Mode atm.

**Comment by irondragon12** [comment]
ok

**Comment by irondragon12** [comment]
so it will have been 2 months starting tomorrow since the pack stopped working, so when is this update gonna happen? Or did you just give up on the pack?

**Comment by Cazadorsniper** [comment]
Look at my previous post.

**Comment by irondragon12** [comment]
Well ya ik but is it really that hard? what am i saying of course it is. srry im just impatiant

**Comment by irondragon12** [comment]
![image](https://user-images.githubusercontent.com/30564310/60745792-a65efb80-9f30-11e9-81ae-1897d9ec0c7a.png)

**Comment by irondragon12** [comment]
that happens when updating the pack.

**Comment by irondragon12** [comment]
P.S. this only happens on my laptop. And yes i just tried reinstalling it.

**Comment by irondragon12** [comment]
https://pastebin.com/

**Comment by irondragon12** [comment]
https://pastebin.com/FgNAVwSQ
i crashed while playing

**Comment by Cazadorsniper** [comment]
yeah won't happen next update turned off a config.
