### ISSUE TITLE
Can't craft Transmutation Table

### ISSUE THREAD

**Issue by OsisNie** [Cazadorsniper/PO3#39]
**Pack Version: 3.0.38**

**Description:**
Here you can see that it wont show up in the output despite having all the materials.
![table1](https://user-images.githubusercontent.com/48079212/53541891-e547f500-3ae9-11e9-920f-765d5fd3affe.png)
If however you replace any single material it will magically show up.
![table2](https://user-images.githubusercontent.com/48079212/53541892-e547f500-3ae9-11e9-802b-68cb11240f25.png)
If you try to left click it in the output to pick it up, it'll just disappear leaving the materials in the grid. If you shift-click it into your inventory this happens:
![table3](https://user-images.githubusercontent.com/48079212/53541893-e547f500-3ae9-11e9-9506-267edf119dfb.png)
However, if you try to do anything with the table, such as place it down, it'll just disappear and all the materials will reappear in the crafting table.

**Comment by DangerHSW** [comment]
Craft something or transmute something with the Stone, a freshly new crafted one, that wasn't used won't work.

**Comment by martinschuberteu** [comment]
I had the same issue and if I remember correctly I charged my stone and then it worked.

**Comment by OsisNie** [comment]
I'd used the stone within my ME system but not in a normal crafting table if that matters. I also had no idea it could be charged. This is the first time I've tried out ProjectE. I'm booting up the pack now and we'll see if I can get it to chooch.
