### ISSUE TITLE
Can't Craft Armor

### ISSUE THREAD

**Issue by TwentyGX** [Cazadorsniper/PO3#390]
**Pack Version:**
3.0.40

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
I can't craft any vanilla armor, the item just doesn't come up when I place the material. Boutta check if it's a rotated crafting table issue but it was absent in the recipe list on Just Enough Items.
**Steps to reproduce:**
Try crafting

**Crash log (use pastebin or similar):**
The game did not crash, I just cannot craft any type of regular armor. Whenever I look up the recipe for any type of armor it doesn't show the vanilla one with the ingots/leather/diamonds.

**Comment by Cazadorsniper** [comment]
have you tried using the armor workbench from armorplus?
