### ISSUE TITLE
Falling down into void

### ISSUE THREAD

**Issue by Malkovitz** [Cazadorsniper/PO3#391]
**Pack Version:** 3.0.40

**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Happened to me twice. Whenever player falls into the void, game teleports him to the Nether. When player is being teleported into the Nether, game is teleporting him randomly. When bugged player exits the server, server is crashing.

**Steps to reproduce:** Just jump into the void.

**Crash log (use pastebin or similar):**
[2019-05-19-2.log](https://github.com/Cazadorsniper/PO3/files/3195560/2019-05-19-2.log)

**Comment by Cazadorsniper** [comment]
#332
