### ISSUE TITLE
no batch file

### ISSUE THREAD

**Issue by SneakyTurtle27** [Cazadorsniper/PO3#392]
when i download the server file it doesnt come with a batch file whenever i try to create one the server shuts down upon startup any known way to fix this?

**Comment by nzminecraftDOTcom** [comment]
You'll need to create a file for the server to run

```
@echo off
java -Xms1G -Xmx8G  -jar Forge.jar nogui -o true
```

Replace "Forge.jar" with whatever your forge.jar file says or edit the forge.jars name to say "Forge.jar"
Replace the memory amounts to suit your requirements.

**Comment by SneakyTurtle27** [comment]
whenever i create the batch file and launch it even though i changed everything according to instructions it instantly closes the file and doesn't boot the server

**Comment by SneakyTurtle27** [comment]
it also doesn't give me a crash log

**Comment by nzminecraftDOTcom** [comment]
Do you have java installed on your computer, check that. Java 8 is recommended.
