### ISSUE TITLE
EverlastingAbilities losing abilities on death

### ISSUE THREAD

**Issue by Danapel** [Cazadorsniper/PO3#393]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:** 
Multiplayer
**Description:**
I can use my everlasting abilities but upon dying, I lose the ability and the experience. 
**Steps to reproduce:**
really just die and you'll see the ability isn't there, I also want to add, if there is an option to disable you from losing the abilities how would I go about doing that?
**Crash log (use pastebin or similar):**
doesn't crash the game,

**Comment by Cazadorsniper** [comment]
That is a part of the pack.

**Comment by Danapel** [comment]
alright, was unaware since EverlastingAbilities by default is you keep it. Thank you!
