### ISSUE TITLE
Step Assist won't turn off

### ISSUE THREAD

**Issue by Boflar** [Cazadorsniper/PO3#395]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** My Step Assist randomly turned on, like I didn't get any notification or press anything (I have the button disabled) but I just started having permanent step assist and I tried turning it off by asigning the button but it doesn't do anything when I toggle it

**Steps to reproduce:** I don't know

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
See if something from Lord Craft or Astral Sorcery is causing it.

**Comment by Boflar** [comment]
I've only done the first 2 quests for Astral Sorcery, and I'm at the part in Lord Craft where you do quests for the people but I haven't like used any item or done anything that I know of that would cause it

**Comment by Boflar** [comment]
Also if I shift right click anything (even air)  i get haste 2 and resistance 2 for like a second

**Comment by Cazadorsniper** [comment]
try checking your everlasting abilities and the Lord Craft Passive abilities.

**Comment by Boflar** [comment]
It was Lord Craft passive, thank you <3
