### ISSUE TITLE
Items disappear when broken

### ISSUE THREAD

**Issue by R3kandH4V0k** [Cazadorsniper/PO3#397]
**Pack Version:**
3.0.40

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
any time i mine a block, (wood, dirt, torches etc.) the item will show that it drops but when it touches the ground it totally disapears.

**Steps to reproduce:**
mined blocks in existing and created new worlds and the same thing happens

**Crash log (use pastebin or similar):**
no crash log given

**Comment by Cazadorsniper** [comment]
Are you experiencing tps drops?

**Comment by R3kandH4V0k** [comment]
No tps drops at all,

**Comment by R3kandH4V0k** [comment]
At first i thought it was because the tool i was using on the marble from
astral, but it also happened with an empty hand with the grass and dirt

**Comment by Cazadorsniper** [comment]
Do you have any item collectors near you that maybe picking things up?

**Comment by R3kandH4V0k** [comment]
No, this is happening even with brand new worlds

**Comment by R3kandH4V0k** [comment]
I even tried reinstalling the pack and it still happens.

**Comment by Cazadorsniper** [comment]
Do any other packs do this?

**Comment by R3kandH4V0k** [comment]
No

**Comment by Cazadorsniper** [comment]
Have you tried reinstalling the pack?

**Comment by R3kandH4V0k** [comment]
Yes, twice

**Comment by Cazadorsniper** [comment]
can you try removing Itemphysics?

**Comment by R3kandH4V0k** [comment]
I will give that a try and see if that fixes the issue
