### ISSUE TITLE
Filled Clay Bucket (any fluid) not able to be removed from ME system

### ISSUE THREAD

**Issue by VanishThee** [Cazadorsniper/PO3#398]
**Pack Version: 3.0.40**
**Singleplayer, Multiplayer, or LAN?: didn't try LAN, but on both singleplayer and multiplayer the bug persisted**

**Description: The clay bucket from Ceramics when filled with any liquid (tested with a multitude of things, water, lava, gelid cryotheum, bucket of blood, essence of knowledge) and when they are place into an ME system filled you cannot pull them back out. You can't pick them up normally, I tried removing them with an export bus, wouldn't work. They do appear in the ME system and take up a type on the storage cells as well as byte space.**

**Steps to reproduce: for a simple test, set up an ME chest with a drive inside(they need to be powered)
Then grab any fluid (for recreation of tests I preformed use one of the fluids listed above) and bucket it inside a clay bucket.
Then place the clay bucket with the fluid you picked up in the ME chest and you should have the exact same result as described above**

**Crash log (use pastebin or similar): As this does not crash client or servers to my knowledge( never crashed me when testing) I have no logs to provide.**

**Comment by Cazadorsniper** [comment]
Try Export Bus with a fuzzy card.

**Comment by VanishThee** [comment]
Yeah That seems to work, still no idea why this happens, I will close it anyways though
