### ISSUE TITLE
Ur-Gast Spawn Crashing Server  Twilight Forest

### ISSUE THREAD

**Issue by darck467** [Cazadorsniper/PO3#402]
**Pack Version:**
Ozone 3 1.12.2 Forge 14.23.5.2836
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I was starting the Ur-gast fight where he spawns and it spawned and crashed the server, repeatedly 
**Steps to reproduce:**
use Erebus chest piece to fly up there and get close to the spawer which said naga
**Crash log (use pastebin or similar):**
https://pastebin.com/jtVTKJsi

**Comment by Cazadorsniper** [comment]
max-tick-time=-1
