### ISSUE TITLE
Error on load the game

### ISSUE THREAD

**Issue by WarlenSilveira** [Cazadorsniper/PO3#403]
Pack Version: PO3-3.0.40
Singleplayer, Multiplayer, or LAN?: Not the case

Description: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

Steps to reproduce: Start the Game

Crash log (use pastebin or similar): 
[crash-2019-05-26_21.50.48-client.txt](https://github.com/Cazadorsniper/PO3/files/3221396/crash-2019-05-26_21.50.48-client.txt)

**Comment by Cazadorsniper** [comment]
Add more ram

**Comment by WarlenSilveira** [comment]
But I have 16gb of Ram. What I need to do do force the game read all Ram memory?

**Comment by WarlenSilveira** [comment]
I found where I change the amount of allocated memory. This is changed on profile config. I define manually the amount. Works. Thanks a lot.
