### ISSUE TITLE
My games crash as I go an action in the world.

### ISSUE THREAD

**Issue by kryptonusia** [Cazadorsniper/PO3#404]
Hello, in the beginning my game works very well but I wanted to craft a laser gun as soon as I wanted to use the game to crash, since the game no longer wanted to refunction, correctly I deleted the project Ozone and I reinstalled them entirely whether it is on the server or on my client, as soon as the game and to charge and that launches the world the game works but as soon as I move or that I open a game the game crash direct, that this be in multi or solo, others can play normally on my server.

[crash-2019-05-26_15.49.24-client.txt](https://github.com/Cazadorsniper/PO3/files/3221976/crash-2019-05-26_15.49.24-client.txt)

**Comment by Cazadorsniper** [comment]
Check if a keybind is conflicting with anything, or try removing Toast Control.

**Comment by kryptonusia** [comment]
I thank you for your help, I delete the toast control and everything works again again thank you, I have more than optifine to work because when I but it loads more the game
