### ISSUE TITLE
Game Not Launching

### ISSUE THREAD

**Issue by ABiohazard** [Cazadorsniper/PO3#406]
While the modpack is loading, it keeps crashing for me. I have tried this multiple times, even deleting the pack and reinstalling it again. I have plenty of RAM on my computer (+20) that is unused and up-to-date processor. My CPU only reaches 100% before it crashes, but never hits that mark beforehand.

When going back to the client it says this, which may be the problem: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

This is the full crash report if that is not enough information:

[crash-2019-05-27_20.12.18-client.txt](https://github.com/Cazadorsniper/PO3/files/3225550/crash-2019-05-27_20.12.18-client.txt)

**Comment by Cazadorsniper** [comment]
#403
