### ISSUE TITLE
Can't craft 4 Plastics in plastic melter

### ISSUE THREAD

**Issue by Leachim95** [Cazadorsniper/PO3#408]
**Version: 3.0.40:**
**Singleplayer:**

**I can't craft Light blue, Magenta, White or, Orange plastics :**

**1. Fill plastic mixer with molten plastic and dyes. 2 click on Light blue, Magenta, White or, Orange plastics. 3. Nothing is made.  :**

**Comment by Cazadorsniper** [comment]
I just made those plastics fine.

**Comment by Leachim95** [comment]
I have been trying for days. I click nothing happens.

**Comment by Cazadorsniper** [comment]
Do you have lock selection on?

**Comment by Leachim95** [comment]
No I do not.

**Comment by Cazadorsniper** [comment]
Also the machine will tell you if there are issues.

**Comment by Leachim95** [comment]
It says that it's good.

**Comment by Cazadorsniper** [comment]
Can you post screenshots?

**Comment by Leachim95** [comment]
I'm working on a video to show you. One second.

**Comment by Leachim95** [comment]
https://youtu.be/IaA6hpzfizM

This is the link

**Comment by Cazadorsniper** [comment]
Try updating pneumaticcraft.

**Comment by Leachim95** [comment]
Doing it now

**Comment by Leachim95** [comment]
Nope. still not working.

**Comment by Cazadorsniper** [comment]
Try a new mixer, that one may have broken, the GUI doesn't look right.

**Comment by Leachim95** [comment]
new mixer nothing. going to try adding heat to new one.

**Comment by Cazadorsniper** [comment]
Did you add any mods to the pack? 
What BetterFPS algorithm are you using?
It maybe possible that the pack didn't download completely from the twitchapp.

**Comment by Leachim95** [comment]
I'm not using any extra months I don't know what my better fps algorithm is I'm using the one that comes standard. and I'm 99% sure it downloaded completely from the twitch app I've not had any other issues except for this one issue.

**Comment by Cazadorsniper** [comment]
Well you're the only one with this issue have you tried to do this in a new world for testing it out?
