### ISSUE TITLE
Game Crashes when creating Iron Ores with Combining Factory

### ISSUE THREAD

**Issue by fightmesun** [Cazadorsniper/PO3#409]
**Pack Version:**3.0.40 Singleplayer

**Steps to reproduce:**
Create Iron Ores with Combining Factory.
Cobblestone in the speacial slot and pulverized iron in the input slots. 

**Crash log (use pastebin or similar):**
[latest.log](https://github.com/Cazadorsniper/PO3/files/3233962/latest.log)

**Comment by Cazadorsniper** [comment]
I have an updated version of Mekanism in my dev environment so this should be fixed next update since it doesn't occur.
