### ISSUE TITLE
Wireless crafting terminal causing crash when equipped in bauble slot

### ISSUE THREAD

**Issue by LordVulc4n** [Cazadorsniper/PO3#41]
Pack version:
3.0.38

Description:
It would appear that having a wireless crafting terminal in the fifth bauble slot causes a crash when trying to render the player model (so whenever you open your inventory or go into F5). I've had the terminal auto equip to the head bauble slot when opening a gravestone before and it does render on the player fine.

Steps to reproduce:
I guess your best bet would be to fill your bauble slots apart from the 5th one and have a wireless crafting terminal in your inventory, then die and open the grave, try to view your player.

Crash report:
https://pastebin.com/iPisMBbn

**Comment by RNADNA47** [comment]
+1 ... this happened to me too. There's a worse thing, but I'll paste that into a different issue.

Crash Report: https://pastebin.com/6hetrAde

**Comment by Zapstur** [comment]
Since the game crashes when your character has to be rendered, then there is a simple solution that DOES NOT REQUIRE SAVE DATA EDITING.
Just open the Mod Options, search for the Baubles mod, go into the config, and disable the only option there.

**Comment by LordVulc4n** [comment]
The bauble data can be found in your playerdata file,
D:\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward\saves\New World\playerdata(your UUID).dat

![image](https://user-images.githubusercontent.com/13063413/53797667-88579f00-3f2e-11e9-8473-ddf21ebe40de.png)
