### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by fightmesun** [Cazadorsniper/PO3#413]
**Pack Version:**3.0.40
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:**
Game crashes while loading. Crash report mentions there being duplicates or something about a talisman 

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
https://pastebin.com/ycxWVXmN

**Comment by Cazadorsniper** [comment]
it seems the Soulbound Talisman from Equivalent Integration is acting up try loading the pack without the mod then open the world. After the world opens, close minecraft and add the mod back and reopen the pack.
