### ISSUE TITLE
Game crashes when joining to nether

### ISSUE THREAD

**Issue by Twillo** [Cazadorsniper/PO3#414]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer. dedicated server

When I jump into the nether, I get stuck in a nether portal loop, where you cant type, move, or do anything. And after few minutes client side is disconnecting with error "Time out. Connection lost". Server side is also stops without error, doesn't appear as online and unable to join.

Crash log: [https://anonfile.com/l6eaA2tene/2019_06_01_1_log](url) (couldn't use sites like pastebin because of the log size)

Server specs:
Intel Xeon Platinum 8175M (24C 48T)
32 GB DDR4
1 TB SSD

**Comment by Cazadorsniper** [comment]
#332
