### ISSUE TITLE
Randomly fall from the platform in skyblock

### ISSUE THREAD

**Issue by Baba-Ganoush** [Cazadorsniper/PO3#417]
**Pack Version:** 3.0.38
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I do not know the actual source of this issue but whenever i veinmine something or just spam click sprint ctrl I randomly get knocked of my platform similar to what happens to items upon holding down Q and throwing them. This is extremely frustrating and idk what is going on.

**Steps to reproduce:**

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Can you update the pack?

**Comment by Baba-Ganoush** [comment]
We attempted to run the server on 3.0.40 but the server files were a mess so we just went with .38.
