### ISSUE TITLE
Can't Install Modpack

### ISSUE THREAD

**Issue by tlitookilakin** [Cazadorsniper/PO3#42]
**Pack Version:**
3.0.38
**Description:**
Cannot install the modpack. Attempting installation from curseforge through any launcher (including twitch app) immediately fails. Downloading the zip and importing it via twitch app results in it downloading about 1/2 the mods before crashing the launcher and not creating a new pack entry. 3 other modpacks were tested and installed successfully. Situation has persisted for 2 days at writing.
**Steps to reproduce:**
Attempt to install a fresh copy of the pack.
**Crash log:**
N/A
**Notes:**
Honestly I doubt there's anything you can do about it but I thought it wouldn't hurt to make a post about it.

**Comment by Cazadorsniper** [comment]
Try contacting Twitchapp support

**Comment by nzminecraftDOTcom** [comment]
Do you have enough space on the drive where the download is attempting to be stored?

**Comment by tlitookilakin** [comment]
Yes there is plenty of space
Ive mailed twitch but who knows when theyll get back to me
thanks again for your time

**Comment by tlitookilakin** [comment]
well its working now

**Comment by ShakesNH** [comment]
> well its working now

What did you do because mine is currently having the same issue

**Comment by tlitookilakin** [comment]
nothing it just started working again
curse has been weird lately so I would just update the launcher and then wait it out
