### ISSUE TITLE
lagg spikes trubble loading

### ISSUE THREAD

**Issue by kevinvanbr** [Cazadorsniper/PO3#420]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** problem 1: when i am trieing to load the game it takes about 1 whole our to load, im using at the moment about 12gb ram of the 64 avalible. when i loaded the game in for the first time it worked within 10 minuts. (im using twitch) problem 2: when the game is finally loaded my it is working for about 20 seconds and after that i get framedrops from 100 fps to 17 and sometimes even framedrops to 0 fps for whole minuts or longer. (im using the Nvidia geforce gtx980 (gpu) and the intel core 17-5930k (cpu) (3.50Ghz)) i hope someone knows how to solve those problems i have asked the twitch support team but they cant help me. i have tried another modpack (all the mods 3) and that one is working fine. 

**Steps to reproduce:** (i dont know what i did wrong)

**Crash log (use pastebin or similar):** here is the crash log and the log i dont know what you will need to help me
[crash-2019-06-05_15.43.15-client.txt](https://github.com/Cazadorsniper/PO3/files/3262862/crash-2019-06-05_15.43.15-client.txt)
[latest.log](https://github.com/Cazadorsniper/PO3/files/3262864/latest.log)

pastebin crash report https://pastebin.com/iVGWkBej
pastebin log https://pastebin.com/Dn4pdT05

**Comment by Cazadorsniper** [comment]
Allocate 6gb of ram to the pack (through the twitchapp), 12 is too much and the pack is only detecting 3.

**Comment by kevinvanbr** [comment]
i will try (how do i make a pastebin link?)

**Comment by Cazadorsniper** [comment]
got to pastebin.com, copy/paste crash to the site, make the paste, then send link of it here.

**Comment by kevinvanbr** [comment]
done

**Comment by kevinvanbr** [comment]
i changed it to 6 gb ram and its loading a lot faster now but i still have the laggspike issue any idea how to solve that one?

**Comment by Cazadorsniper** [comment]
can you give me the latest.log/debug.log after the lag spike happens? (Don't use pastebin for logs, logs are too large for it)

**Comment by kevinvanbr** [comment]
here is the latest log. the laggspikes/framedrops happen each 3 second after eachother.

[latest.log](https://github.com/Cazadorsniper/PO3/files/3266590/latest.log)

**Comment by Cazadorsniper** [comment]
I can't see anything going on with the latest.log try the debug.log.

**Comment by Cazadorsniper** [comment]
Can also make sure you're starting the world as Garden of Glass world type.

**Comment by kevinvanbr** [comment]
i did all those things in the Garden of Glass world type and i cant find the debug.log file in the project ozone 3 map.

**Comment by kevinvanbr** [comment]
the only thing i notice in game is when im walking my whole screan turnes gray/dark red (depend on if im in nether or not)

**Comment by kevinvanbr** [comment]
and sometimes i see some strange cloud beneath me or something like that and when that happens my whole game starts lagging

**Comment by kevinvanbr** [comment]
![2019-06-07_18 40 45](https://user-images.githubusercontent.com/51456788/59119745-d926cb80-8953-11e9-8e9f-8a3c99cffc54.png)
this cloud is what im seeing (whats now above my head) this is causing a big part of the lagg but whats it

**Comment by kevinvanbr** [comment]
and another thing is all creatures including me are swinging verry weird with their arms

**Comment by Cazadorsniper** [comment]
What BetterFPS Algorithm are you using?

**Comment by kevinvanbr** [comment]
i just changed it to vanilla and thats working now only the long loading time is back

**Comment by kevinvanbr** [comment]
i think i found out what the lagg problem was i think its the botania mod (the sky thing) and the better fps algorithm but the loading time is still a little thing it just took something between half an hour and one whole hour to load the game thats still not the time its suposed to take right?

**Comment by Cazadorsniper** [comment]
Remove the Waiting Time mod.

**Comment by kevinvanbr** [comment]
i dont know yet if the waiting time is less now but i noticed there is still a lagg problem in 2 sec after eachoter i get a bit of lagg no matter if im in single player normal map or skyblock or if im at my server so any other idea for this?

**Comment by Cazadorsniper** [comment]
Have you tried waiting for the world to load completely (which allows for the worldgen lag to go away)?

**Comment by kevinvanbr** [comment]
waiting doesnt work i have waited about 20 minuts and its still lagging

**Comment by kevinvanbr** [comment]
so any other solution because it laggs still to much to play

**Comment by Cazadorsniper** [comment]
I need the debug.log (located in the same place the latest.log is located) it might tell me something.

**Comment by kevinvanbr** [comment]
there is no debug.log 
![no debug](https://user-images.githubusercontent.com/51456788/59148172-9b827b00-8a05-11e9-80f2-6c65dc7ca055.png)

**Comment by Cazadorsniper** [comment]
You can try a different betterfps algorithm (I use Rivern's full)

**Comment by kevinvanbr** [comment]
also not working

**Comment by Cazadorsniper** [comment]
You  can try the "Force threaded chunk rendering" in the forge.cfg in the config file

**Comment by Cazadorsniper** [comment]
You can also try adding the mods Vanillafix and/or Optifine.

**Comment by kevinvanbr** [comment]
i already putted optifine in the modfile but i didnt notice a change

**Comment by Cazadorsniper** [comment]
If that doesn't work can also try updating Java; however, after that I don't know.

**Comment by kevinvanbr** [comment]
i cant find the "Force threaded chunk rendering" in the forge.cft file

**Comment by kevinvanbr** [comment]
and i have the newest java version

**Comment by Cazadorsniper** [comment]
# Enable forge to queue all chunk updates to the Chunk Update thread. May increase FPS significantly, but may also cause weird rendering lag. Not recommended for computers without a significant number of cores available.
    B:alwaysSetupTerrainOffThread=false

**Comment by Cazadorsniper** [comment]
Try some other modpacks, if the same lag happens then something is happening on your pc.

**Comment by kevinvanbr** [comment]
while its loading i have another small question when i fall of skyblock (on my server) it keeps saying loading demension -1 and crashes if i restart the server i cant join but the server isnt crashing anymore i fixed this once by deleting the player file but i cant keep doing that do you know a way to solve this ?

**Comment by kevinvanbr** [comment]
i already tried another modpack wich was working the technick launcher also worked and manually installed mods worked too(most of them)

**Comment by Cazadorsniper** [comment]
Then your pc doesn't like PO3... I have no other solution.

**Comment by kevinvanbr** [comment]
xD maby this works or select another forge launcher but any idea how to solve my server problem or do i really have to make another issue report for that?

**Comment by Cazadorsniper** [comment]
server problem?

**Comment by kevinvanbr** [comment]
yea the crash when i fall of the skyblock

**Comment by Cazadorsniper** [comment]
remove unforgining void mod or don't fall.

**Comment by kevinvanbr** [comment]
hey now there are debug logs at the log file

**Comment by kevinvanbr** [comment]
nvm i was looking at my server

**Comment by kevinvanbr** [comment]
alright i THINK i figured it out i just had to restart my pc i probably had launched mc to many times xxD

**Comment by kevinvanbr** [comment]
tnx the lagg and loading time is fixed but that server thing didnt help now it says loading demension -2 after i deleted the unfogiving void mod and now my mc crashes when i fall
