### ISSUE TITLE
MP Server wont start

### ISSUE THREAD

**Issue by Aznkid** [Cazadorsniper/PO3#421]
**Pack Version: 3.0.40
**Singleplayer, Multiplayer, or LAN?: MP

**Description: Server would load up halfway and then crash saying something like server tick took 60 seconds. forced to shut down.

**Steps to reproduce: not sure

**Crash log (use pastebin or similar):

[crash-2019-06-07_04.07.52-server.txt](https://github.com/Cazadorsniper/PO3/files/3263338/crash-2019-06-07_04.07.52-server.txt)

**Comment by Cazadorsniper** [comment]
server.properties > max-tick-time =-1
