### ISSUE TITLE
server crash wen falling in void (garden of glass)

### ISSUE THREAD

**Issue by kevinvanbr** [Cazadorsniper/PO3#424]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** each time i fall of my Island the server crashed and my minecraft sais timed out while loading the nether. the server sais its loading demension -1. anyone know how to fix this. ( ive already tried to delete the un…. void mod and that made my minecraft crash)

**Steps to reproduce:** step 1 jump of Island 
step 2 fall
step 3 load nether 
step 4 crash

**Crash log (use pastebin or similar):**
crash report https://pastebin.com/asQvc81f
[debug-5.log.gz](https://github.com/Cazadorsniper/PO3/files/3268839/debug-5.log.gz)
[latest.log](https://github.com/Cazadorsniper/PO3/files/3268840/latest.log)

**Comment by Cazadorsniper** [comment]
#332
