### ISSUE TITLE
Crashing when clicking "Singleplayer"

### ISSUE THREAD

**Issue by Proppern** [Cazadorsniper/PO3#427]
**Pack Version: 3.0.40**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: Ever since a power outage happened I can't seem to play anymore. Whenever I click the "Singleplayer" button the screen freezes and then crash. I have tried uninstalling the modpack, the twitch launcher and java and it still doesn't work. **

**Steps to reproduce:**

**Crash log (use pastebin or similar):https://pastebin.com/X1723t2w**

**Comment by Cazadorsniper** [comment]
All I can say is that it may be possible that the power outage screwed something up in your pc. I can only say reinstall the pack.

**Comment by Cazadorsniper** [comment]
Could of corrupted minecraft itself too.

**Comment by Proppern** [comment]
I fixed it, turns out it was because my save file got corrupted. i tried removing the save file and it doesn't crash anymore whenever i click singleplayer. i still don't get why it broke the singleplayer button though...

**Comment by Proppern** [comment]
closing the issue
