### ISSUE TITLE
Mystical Agriculture Infusion Crystal

### ISSUE THREAD

**Issue by VyseGolbez** [Cazadorsniper/PO3#430]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:** 
Singleplayer

**Description:** 
The Infusion Crystal from Mystical Agriculture can only be crafted with a full durability Supremium Infusion Crystal but still only uses one durability on that Crystal. I would assume from the previous recipies that you're supposed to craft it with less durability on the Supremium Infusion Crystal as well; or if you're supposed to need a full one, that the Supremium Crystal would be completely used up in that recipe.

**Steps to reproduce:**
Try to craft the Infusion Crystal with a partially used up Supremium Infusion Crystal.
**Crash log (use pastebin or similar):**
Not a crash, therefore no log.

**Comment by ByteTemplar** [comment]
I think it is intended mechanic, just enchant the crystal with Mending and repair it that way. Or make a new one, but you will need quite a few of em...

**Comment by wendictive** [comment]
neither mending or unbreaking works on the crystal ... have both on  imperium uses left does not change
