### ISSUE TITLE
Titanium Hammer/Torch 

### ISSUE THREAD

**Issue by planetx31** [Cazadorsniper/PO3#431]
PO3 Version 3.0.40 Forge 14.23.5.2836
Single Player

Game crashes when trying to place a Torch from my offhand on the ground while holding a "Titanium Hammer."

Reloaded the game, put torches in my off hand, held the Titanium Hammer in my main hand, tried to place the torch again from my offhand and the game crashed, again with the same error.

Paste Bin : https://pastebin.com/r4WKSmSk

**Comment by Cazadorsniper** [comment]
Removed Thermal Solar tool recipes next update.
