### ISSUE TITLE
Mekanism Crushing Factory converts into Smelting Factory

### ISSUE THREAD

**Issue by SpuddzMC** [Cazadorsniper/PO3#433]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?: 
Multiplayer
**Description:**
I made the Elite Crushing Factory twice, and both times when I placed the block down, it would change into an Elite Smelting Factory. Very frustrating wasting materials.
**Steps to reproduce:**
- Craft Crusher from Mekanism, then upgrade it to Basic Crushing Factory, Advanced Crushing Factory, and finally Elite Crushing Factory
- Place down Elite Crushing Factory (both times I had it connected to an Ender Energy Conduit)
- Turns into Elite Smelting Factory

**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
Likely fixed in a recent Mekanism update.
