### ISSUE TITLE
Game Crashing after 90% Loaded

### ISSUE THREAD

**Issue by Anarchon-D** [Cazadorsniper/PO3#436]
**Pack Version:**
PO3-3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Loads halfway no problem, then around 75% it slows down _Severely_. The program stops responding a couple times momentarily, then at around 95% complete, it fully crashes.
**Steps to reproduce:**
Opened Twitch Apps, Clicked on Minecraft, went to the Mods sections, downloaded the current version of PO3, installed it and clicked play. I have never gotten past the ping pong challenge.... do I have to beat the opponent in order to play the game? lol kidding. But yeah, 3 times in a row tonight exact same thing. Takes around 15-20 minutes loading to get to the point that it crashes. 
**Crash log (use pastebin or similar):**
**Details:** The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Crash Report:** _(txt file below)_
[crash-2019-06-15_04.42.11-client.txt](https://github.com/Cazadorsniper/PO3/files/3292894/crash-2019-06-15_04.42.11-client.txt)

Hope that helps. and JSYK I'm running 16G ram, so thats definitely not an issue. 

Thanks,
   Scott

**Comment by Cazadorsniper** [comment]
Needs more allocated ram for minecraft to use.

**Comment by Cazadorsniper** [comment]
#403

**Comment by Anarchon-D** [comment]
> #403

so how do I fix it. just like that other post i have 16G of ram. but just linking that other post isn't enough for me.... I don't have any clue where this profile config file is.

**Comment by Anarchon-D** [comment]
nevermind i think i found it. it's on the Twitch program itself.
