### ISSUE TITLE
Yellorium bucket duplicating when trying to put in drawer.

### ISSUE THREAD

**Issue by goonie123123** [Cazadorsniper/PO3#437]
Whenever i try to put a Yellorium bucket into a drawer it puts one in but doesn't take any out of my inventory.

The drawer is locked, there's no items being pulled from it currently but items are being put into it.
It also has full emerald upgrades in them.

**Comment by Cazadorsniper** [comment]
Can you explain exactly what is happening? So far I can't reproduce this.

**Comment by goonie123123** [comment]
Since I last played it has fixed itself and no longer happens so I don't have any idea what caused it.
