### ISSUE TITLE
Crash with Ender IO Electric Light and Reliquary Cauldron

### ISSUE THREAD

**Issue by ToMe25** [Cazadorsniper/PO3#438]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I have lighted my Base on a PO3 Server with EnderIO Electric Lights(Inverted) and now after some time of mostly working as intended i just crash if i load my base and the Crash Log also says something about the Reliquary Cauldron.

**Steps to reproduce:** Place a Reliquary Cauldron and two or three complete circles of Active Electric Light around it.

**Crash log (use pastebin or similar):** [Crash-Report](https://pastebin.com/mQVRkWWK)

**Comment by ToMe25** [comment]
Seems like i got a different Crash retrying what i have written to reproduce it so maybe you will need to place more lights. also i have powered them with DE Wireless Relay Crystals and the New Crash i got this new try was: [Crash-Report](https://pastebin.com/p225FX0D)

**Comment by Cazadorsniper** [comment]
I've gotten your first crash so far and it only crashed when I tried to go into my inventory, reliquary seems to have an issue with particles for some reason.

**Comment by ToMe25** [comment]
For me it crashed without going to the Inventory.
Just a few Seconds after placing the Stuff.
