### ISSUE TITLE
Constant crashes and lags

### ISSUE THREAD

**Issue by MadnessTM** [Cazadorsniper/PO3#439]
**Pack Version:**
3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Mutliplayer
**Description:**
https://gyazo.com/01b53598e0cca0e492dcdc4d32e9fcc7
I don´t know why it cant keep up. Ryzen 1800x used with 16gb ram.
On Windows 10 but the Server ist the only thing that is running.
This is happening while just 3gigs are being used so no ram issue and 
just 7% cpu usage so i dont know why it is happening.
The next thing is only with one of my m8s.
https://gyazo.com/a973e9375f505d1bc21e23c3fa046094
if he falls down so he gets tpd to hell this happens and the server crashes.
Though with the normal hell portal he just can go through and enters hell and its not crashing.
**Crash log (use pastebin or similar):**
https://pastebin.com/wHJuBEnp

**Comment by Cazadorsniper** [comment]
server.properties Max-tick-time=-1 on the crash and #332 for the issue with falling to the nether.
