### ISSUE TITLE
Yellorium Ingot Conflict Double Output Upgrade

### ISSUE THREAD

**Issue by DangerHSW** [Cazadorsniper/PO3#44]
Pack Version:.38

Description: I had an automated sieving system setup and everything went fine as it all got put into barrels. I had the Ex-Nihilo Yellorium Ingots in Barrels, since the Furnace make them with the Ore Doubling Upgrade. But after changing to the Double Output Upgrade it changed the Yellorium to The Extreme Reactors one and backlogged my Production.

Steps to reproduce:change Ore Double Upgrade to Double Output Upgrade

Crash log: /

**Comment by Ravalli03** [comment]
You can run your production through a storage drawer with a conversion upgrade to the version you want to use.

**Comment by DangerHSW** [comment]
It's not that I don't want to use something different, more of a notice that it shouldn't output a different version of the ingot in the same process. I know about the drawers very well.
