### ISSUE TITLE
Game is not opening (initialization ender io eror)

### ISSUE THREAD

**Issue by Mooreaoth** [Cazadorsniper/PO3#440]
**Project ozone 3**
**Singleplayer:**

**game is not opening**

**Steps to reproduce:**

[crash-2019-06-22_08.48.32-client.txt](https://github.com/Cazadorsniper/PO3/files/3316580/crash-2019-06-22_08.48.32-client.txt)
**

**Comment by Cazadorsniper** [comment]
fml will not run in demo mode, you need to use a paid Minecraft account.

**Comment by Mooreaoth** [comment]
soryy I threw the wrong file
[crash-2019-06-22_08.59.32-client.txt](https://github.com/Cazadorsniper/PO3/files/3316723/crash-2019-06-22_08.59.32-client.txt)

**Comment by Mooreaoth** [comment]
not demo buy account but is not opening

**Comment by Cazadorsniper** [comment]
not a crash report that is a log.

**Comment by Cazadorsniper** [comment]
use pastebin too
