### ISSUE TITLE
Mod Pack crashes

### ISSUE THREAD

**Issue by Arnsee** [Cazadorsniper/PO3#442]
-Project Ozone 3, Downloaded on twitch app

After starting my launcher it crashes at the end of the loading... i don't know why and i can't solve it cause i don't understand shit.
if someone could help me i'd be glad!

Here what it tells me and the crash log

**The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

[crash-2019-06-25_20.22.57-client.txt](https://github.com/Cazadorsniper/PO3/files/3326785/crash-2019-06-25_20.22.57-client.txt)
**

**Comment by ByteTemplar** [comment]
First of all, update your Java (you are running ancient 1.8.0_51). 

Next give it more memory, you are only giving it 3Gb, when minimum is 6Gb to even run it and this is why its crashing on loading for now...

**Comment by Arnsee** [comment]
> First of all, update your Java (you are running ancient 1.8.0_51).
> 
> Next give it more memory, you are only giving it 3Gb, when minimum is 6Gb to even run it and this is why its crashing on loading for now...
Thank you very much! i'll try it out and i'll tell you the outcome!

**Comment by Arnsee** [comment]
> First of all, update your Java (you are running ancient 1.8.0_51).
> 
> Next give it more memory, you are only giving it 3Gb, when minimum is 6Gb to even run it and this is why its crashing on loading for now...



So basically i ran minecraft and it all went good, but i have one last big problem, when i tried to play i was stuck with 1 fps, what should i do?

**Comment by ByteTemplar** [comment]
This really should be asked in Reddit and I recommend checking
https://www.reddit.com/r/projectozone3/

for future reference...

You probably have AMD graphics? You need to disable animated textures in foamfix config. Check this out:
https://www.reddit.com/r/feedthebeast/comments/96k5ud/01_fps_any_modpack_on_twitch_launcher/ebqznj1/

**Comment by Cazadorsniper** [comment]
Ah you mean the random reddit that was made by someone else that isn't part of Team Ozone.

**Comment by ByteTemplar** [comment]
> Ah you mean the random reddit that was made by someone else that isn't part of Team Ozone.

Oh, never thought of that, but it is place where you can get answers to these kinds of questions. Maybe create an official one then, I really dont think github is best place for common problems...

**Comment by Cazadorsniper** [comment]
the old PO2 reddit is it although we still don't really pay attention to it.

**Comment by Arnsee** [comment]
thanks guys!
