### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by Noskyy** [Cazadorsniper/PO3#443]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:** often when I rejoin my world after quitting it I spawn at my bed in the overworld with my inventory from several hours before, so it doesn't save my inventory and position. 
I also tried do to a backup right before clicking "save and quit", but when I rejoined I spawned at my bed with an old inventory. Putting my backup in "saves" folder doesn't resolve the issue

**Steps to reproduce:** 
![photo5807837915512943247](https://user-images.githubusercontent.com/52218335/60127603-e7b51580-9790-11e9-838b-fd7742fb3258.jpg)
![photo5807837915512943248](https://user-images.githubusercontent.com/52218335/60127609-ec79c980-9790-11e9-88bb-b8e6bd69b9bc.jpg)
![photo5807837915512943249](https://user-images.githubusercontent.com/52218335/60127613-ee438d00-9790-11e9-80d8-26cd71ef7ee3.jpg)

This was my inventory during my last backup (I also was in the Twilight Forest) but when I reopened the game I only had a few things (and I was in the overworld)

**Crash log (use pastebin or similar):** The game didn't crash

**Comment by Cazadorsniper** [comment]
I don't know what would cause this, maybe possible corruption?

**Comment by Noskyy** [comment]
I don't know, I posted on this forum because I don't know the issue
