### ISSUE TITLE
Mekanism and fluxducts issue.

### ISSUE THREAD

**Issue by MadWomen** [Cazadorsniper/PO3#444]
mekanism power generators, in my case a turbine, doesn't output into fluxducts but machines do accept energy from fluxducts.

**Comment by Cazadorsniper** [comment]
The steam Turbine?

**Comment by MadWomen** [comment]
the industrial steam turbine, yes.

i have a max size size turbine fed by a max size boiler which in turn is heated up by a fusion reactor, this combo produces 240 MRF/t, the only way to transport that kind of power is the cryo-stabilized fluxduct, but the turbine doesn't want output into any of the fluxducts from thermal dynamics.

all these machines are all from mekanism.

**Comment by Cazadorsniper** [comment]
Have to use universal cable to take out the power sadly.

**Comment by MadWomen** [comment]
in this case, i have used ender io conduits since they can transfer more power than the ultimate universal cables.

its not optimal but it works for now, hopefully sometime in the future this issue will be fixed by mekanism themselves or you if its pack related.

**Comment by Cazadorsniper** [comment]
its definitely not pack related.

**Comment by MadWomen** [comment]
thank you for your time, i'll shall also open an issue with mekanism for this and maybe we'll see an update for this.
