### ISSUE TITLE
Translocator doesn't push Patient bags into and out of Bag Openers

### ISSUE THREAD

**Issue by StefanosM** [Cazadorsniper/PO3#445]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:** Tested both on SP and MP

**Description:** Item Translocators used to be able to push the Patient bags into and out of the Bag Openers in 3.0.38 however, this doesn't work anymore.

**Steps to reproduce:** I have an 8 Bag Opener 3 by 3, connected by Translocators going clockwise.

![2019-06-27_16 11 16](https://user-images.githubusercontent.com/19763745/60269051-65466600-98f6-11e9-8ca7-fab9eab9b692.png)

**Comment by Cazadorsniper** [comment]
Maybe possible that it was done on purpose.

**Comment by Gabbleducky** [comment]
Change it to conduits/itemducts then

**Comment by Wip-Sama** [comment]
translocator in this version is full of bugs, maybe we can exchange translocator with tesslocator
https://www.curseforge.com/minecraft/mc-mods/tesslocator
is more faster and lag friendly
