### ISSUE TITLE
Game crashes on world load, Null pointer

### ISSUE THREAD

**Issue by alexxo97** [Cazadorsniper/PO3#448]
**Pack Version:** 3.0.40
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Game crashes on world load 100% of the time
**Steps to reproduce:**
Happens for every world I have tried. (happens following a random crash in game)
**Crash log (use pastebin or similar):**
https://pastebin.com/R8Zm1Bgb

**Comment by Cazadorsniper** [comment]
1. turn down your max dedicated ram to 6 not 10.
2. Did you add any mods?
3. Did you change any configs?
4. Do you use any type of resourcepack?
5. Did you graphics card drivers update at some point ( I've seen weird crashes dealing with AMD graphics cards)?

**Comment by alexxo97** [comment]
For what is of RAM I started at 6G and increased it over 4 attempts to try and see if it would help. 
I did not change the pack in any way. I even deleted it and reinstalled the modpack to make sure it wasn't that.
I did not upgrade my driver's halfway through but, I can check tomorrow evening if they are maybe out of date.

**Comment by ByteTemplar** [comment]
You are using very old Java version (1.8.0_51), update it!
https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by alexxo97** [comment]
SO I updated my Java, set the ram to 6G and updated my graphics drivers and it seems that the game has stabilised. No random crashed after a while of playing and was able to load my previous world, 

thanks for the quick replies :)
