### ISSUE TITLE
Still no way of making bucket

### ISSUE THREAD

**Issue by mihaitacgeorge** [Cazadorsniper/PO3#449]
Pack Version:
3.0.40
Description:
There is currently no way to get the iron bucket, as casts cannot be made from clay buckets (they are just being filled), and the iron bucket itself is made from much more advanced iron plates.
Just like in the previous report:
"Attempts to make/cast a bucket, there doesn't seem to be any recipe that I have found using Tconstruct's casts/patterns. The recipe remains in NEI showing you that it is possible.
Steps to reproduce:
Try to make a stone bucket to cast. There is no pattern for it.
Crash log:"

link to it 
https://github.com/Cazadorsniper/PO3/issues/14

That report was closed WITHOUT being solved, after being offered a few inane & useless replies by individuals who are unable to read the issue they are replying to.

**Comment by Cazadorsniper** [comment]
Probably because they figured out how to get the bucket without the smeltery at all, you should try looking at all the possibilities of making iron plates.
