### ISSUE TITLE
Cardboard boxes stuck in ME system

### ISSUE THREAD

**Issue by raistlin335** [Cazadorsniper/PO3#45]
**Pack Version:**

**Description:** Using cardboard boxes to move my base, i filled several and dumped them into an ME system. Went to remove them, and they are stuck. Will not come out of the system. Exporting them via export bus did not seem to do anything other than remove the unfilled boxes. Left click/drag and shift-right-click had no results.

**Steps to reproduce:** Right click empty cardboard box on anything, break box and drop into ME system via crafting terminal. Attempt to remove.

**Crash log:**

**Comment by Cazadorsniper** [comment]
Attempt to remove them using the export bus with a fuzzy card.

**Comment by raistlin335** [comment]
I found out later that a me i/o port worked as well. Thank you for the
response.

**Comment by wtfaatp** [comment]
I'm having this problem right now and none of the above seems to have solved this for me.
