### ISSUE TITLE
Quest Book Bug

### ISSUE THREAD

**Issue by Someperson1112** [Cazadorsniper/PO3#451]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
I went off of the game for a day and when i came back on i went to look at my quests and theyve reset and i have none completed i was about 25% into it 
**Steps to reproduce:**
Idk
**Crash log (use pastebin or similar):**
Didnt crash

**Comment by Cazadorsniper** [comment]
Likely corruption try getting a backup of your world.
