### ISSUE TITLE
Lost game save after updating the modpack

### ISSUE THREAD

**Issue by Mallyanke** [Cazadorsniper/PO3#452]
I've just updated the PO3 modpack to version 3.0.41 and lost my world saved in version 3.0.40 (even though the version is still playable),there was no advice at all that it could happen...I was very advanced in the quests and really want to now where did my save go...

**Comment by Cazadorsniper** [comment]
I wouldn't know, think it maybe in the recycle bin? The update doesn't mess with the saves file at all.

**Comment by Mallyanke** [comment]
It was not there,fortunely the modpack creates a backup itself (thank you
for that).I already got my world back :) Just one question,after the update
when I opened the world,it Said that "armorplus:abilities" were
missing,what was it?(I tried to load the world anyway and there was no
difference at all)
Awesome modpack btw,I'm really enjoying the challenge :D

Em qui, 4 de jul de 2019 04:10, Cazadorsniper <notifications@github.com>
escreveu:

**Comment by Cazadorsniper** [comment]
Just turned off the experimental stuff is all.
