### ISSUE TITLE
Mob Masher, reproduce Error: Ticking block entity

### ISSUE THREAD

**Issue by Sotigeor7** [Cazadorsniper/PO3#453]
**Pack Version:** 3.0.41

**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Mob Masher, reproduce Error: Ticking block entity

**Steps to reproduce:**
Just by loading the chunk which contains the Mob Masher from @mob_grinding_utils

**Crash log (use pastebin or similar):**

http://dpaste.com/2XBRD24

**Comment by maicol07** [comment]
@Cazadorsniper if this helps here a pastebin link to my log (it's the same issue): https://pastebin.com/xXzJEPpG
The issue occurs only after the update to last version

**Comment by Cazadorsniper** [comment]
Reported to mod developer.

**Comment by Karl-Markkus** [comment]
I was playing my singleplayer world, and I am actually having the same problem with the mob masher. after letting it run for a while, my game crashes and the error says it was because of a ticking block entity.

**Comment by Touc4nx** [comment]
From what I can see, it crashes whenever an evolved enderman is killed by a block (grinder, spike etc.)

**Comment by Cazadorsniper** [comment]
Waiting for update from Twilight Forest now.

**Comment by climber59** [comment]
My temporary fix was to open EndermanEvolution.cfg and set all the spawning numbers to 0.
