### ISSUE TITLE
Modular Machines Auto sieve only sieving specific materials.

### ISSUE THREAD

**Issue by jetforces** [Cazadorsniper/PO3#454]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Only specific items seem to work according to the machine controller. I've ofund that only 1x Compressed Dust, Compressed sand, and Crushed Endstone are accepted for sieving.

**Steps to reproduce:** Construct an auto sieve as per the blueprint. Insert any materials other than the ones listed above to see it fail to work despite being recipes.

**Crash log (use pastebin or similar):** N/a

**Comment by Cazadorsniper** [comment]
make the output hatch bigger.
