### ISSUE TITLE
Random Server Crash

### ISSUE THREAD

**Issue by yoyoyogurt** [Cazadorsniper/PO3#455]
[crash-2019-07-05_13.29.57-server.txt](https://github.com/Cazadorsniper/PO3/files/3362543/crash-2019-07-05_13.29.57-server.txt)

my server crashes really often with the new .41
i am using an older world from .40

**Comment by jaredstone1982** [comment]
[crash-2019-07-05_08.48.23-server.txt](https://github.com/Cazadorsniper/PO3/files/3362953/crash-2019-07-05_08.48.23-server.txt)

Having same issue, less than a minute into playing freshly-updated world.

**Comment by Cazadorsniper** [comment]
#442
