### ISSUE TITLE
Freeze of the game due to evolved enderman

### ISSUE THREAD

**Issue by Touc4nx** [Cazadorsniper/PO3#456]
Pack Version: 3.0.41
Singleplayer

Description
The game randomly freeze and does't allow me to do anything. I'm forced to kill Minecraft process.
The crash report tels it's when an evolved enderman from p455w0rd mod collides with a spike in my case a diamond spike from extra utilities 2.
It's a new bug in version 3.0.41, as I hadn't any troubles before updating, and my mob farm was working constantly.

Steps to reproduce:
Summon an evolved enderman in a diamond spike from extra utilities 2.

Crash log :
https://pastebin.com/jkgUqYGF

**Comment by Cazadorsniper** [comment]
#453
