### ISSUE TITLE
Random crash after update - Illegal Argument Exception

### ISSUE THREAD

**Issue by Gabbleducky** [Cazadorsniper/PO3#459]
So I updated the modpack today, I had a couple of the crashes with the endermen but I just disabled my mob farm.

I have now just had 2 crashes that talk about an IllegalArgumentException. Pastebin link to crash report is here https://pastebin.com/L4f2sLCR.

It talks about being unable to identify the direction property of a spectre coil.

The crash is seemingly random, I was just building an island for my Astral Sorcery setup when it crashed.

**Comment by k4ssilver** [comment]
I think I have a similar issue on server
[crash-2019-07-06_21.11.54-client.txt](https://github.com/Cazadorsniper/PO3/files/3365000/crash-2019-07-06_21.11.54-client.txt)

**Comment by Cazadorsniper** [comment]
Already fixed for next update just turned off a config.
