### ISSUE TITLE
1 fps on start up

### ISSUE THREAD

**Issue by pyruxen** [Cazadorsniper/PO3#46]
So when I load up the game and start up my world every once and a while I will only get 1 fps and nothing I do will fix it (f3+a, etc...). So to try to work around this I restart the game and reload the world. sometimes this works some times it doesn't.
I'm running a MacBook Pro (Retina, 15-inch, Late 2013) 2.6 GHz Intel Core i7 16 GB 1600 MHz DDR3 NVIDIA GeForce GT 750M 2048 MB Intel Iris Pro 1536 MB and I have 7234 MB of ram allocated
I know my computer kinda old but I run big mod packs like this all the time with no problems.
I'm attaching my world to see if that's the issue.
[Gatun.zip](https://github.com/Cazadorsniper/PO3/files/2917794/Gatun.zip)

**Comment by Zapstur** [comment]
Confirmed, the issue is not your world, your computer's CPU isn't quite able to handle all those mods.  The reason why, is that Minecraft's coding isn't perfect, and has some "leaks".  In other words, the only advice I can give you, is to occasionally quit game, and COMPLETELY restart Minecraft from the launcher.  Given that your CPU runs at only 1.6 GHz, I would recommend for you to do that about once every hour.

The reason I know this works?  I have to do the same thing on my Windows 10 laptop with a 2.5 GHz CPU and 10 GB of ram allocated.

**Comment by TheTrueForce** [comment]
It's worth noting that giving minecraft more than 4 gigs is suboptimal. 6 GB (6144 MB) is the most any pack should ever need.
As you give java more and more RAM, the garbage collector does its thing less and less often, and thus has to stop everything for longer. It might not fix your problem, but it's worth pointing out.

**Comment by Zapstur** [comment]
> It's worth noting that giving minecraft more than 4 gigs is suboptimal. 6 GB (6144 MB) is the most any pack should ever need.
> As you give java more and more RAM, the garbage collector does its thing less and less often, and thus has to stop everything for longer. It might not fix your problem, but it's worth pointing out.

On concept, that is true.  However, the PO3 modpack (on my system) can't get past Forge's set up if it has anything less than 7 GB, the program just goes "not responding" and locks up my computer.  And once I do get it to boot up, the Java process is already using most of that, and suffers some performance issues more often with less RAM.  So, I just set it to 10 GB, and only have to restart Minecraft every 5 hours or so.

**Comment by Jarohdan** [comment]
I am also having this issue I have been playing this mod pack for about 25 hours, when i loaded in my game yesterday I have 1 to 0 fps around my spawn area all other dimensions are fine and I get around 90 to 110 fps there if unlimited but around where my main hub is terrible. I have tried re downloading Java, Minecraft and the pack but nothing seems to work. I am running an I7-6700 a 1080 and have allocated 9 gig of ram to Minecraft.
