### ISSUE TITLE
Mod  downloaded but wont start

### ISSUE THREAD

**Issue by MCModNoob** [Cazadorsniper/PO3#462]
**Pack Version:**
i  tried  3.0.40  and 3.0.41  on MC 1.12.2
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer. my  friends's server
**Description:**
I downloaded the  mod  on twitch  app.The first time i download it it  stopped half way and say a mod(forgot the name) out of 240 cannot be downloaded  for some reason and stopped, but the second attempt was a success.However when i click play it flashes sentences of verifying versions and stuff  but  just doesnt respond no matter how many times or how fast i click it. re-installing and run twitch app on administrator didnt help. 
**Steps to reproduce:**
Download, wait, and click play,  then nothing  
**Crash log (use pastebin or similar):**
twitch app didnt even tell me is this a crash or not, it just doesnt respond.

**Comment by Cazadorsniper** [comment]
I recommend going to twitchapp support for this issue.
