### ISSUE TITLE
crash of po3 while doing not much

### ISSUE THREAD

**Issue by Thomsn22** [Cazadorsniper/PO3#463]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
[crash-2019-07-07_22.14.17-server.txt](https://github.com/Cazadorsniper/PO3/files/3366085/crash-2019-07-07_22.14.17-server.txt)

**Comment by Matthew-McIntyre** [comment]
Version: 3.0.41 Minecraft Version: 1.12.2
Multiplayer Private Server

10 out of 10 Times I would hover my pointer over the iron shulker box and My game would crash out. I have enough power to run on fancy with decent stats. I dedicate 6 GB of ram to the game exclusively. i dont think its the Iron shulker I have it's the obsidian shulker, but thats under the iron shulker box rules. You know the white shulker boxes with the color along the edges marking them. Vic the co owner and the one who set up the server installed thies mods as well. He gets a little mod happy when he sees something he likes.
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/2715314
https://www.curseforge.com/minecraft/mc-mods/security-craft/files/2683645
https://www.curseforge.com/minecraft/mc-mods/buildcraft/files/2702041
https://www.curseforge.com/minecraft/mc-mods/vending-block/files/2614896
https://www.curseforge.com/minecraft/mc-mods/foamflower/files/2489397

this is the screen shot
![Screenshot (3)](https://user-images.githubusercontent.com/52640306/60777011-97757600-a0f5-11e9-8588-5e3b9bf8cd84.png)

And this is the crash file.
[crash-2019-07-07_20.01.48-client.txt](https://github.com/Cazadorsniper/PO3/files/3366363/crash-2019-07-07_20.01.48-client.txt)
