### ISSUE TITLE
[Bug] Can not equip heart canisters in Latest version.

### ISSUE THREAD

**Issue by irondragon12** [Cazadorsniper/PO3#465]
**Pack Version:3.0.41
**Singleplayer

I can not equip my heart canisters to my baubles slots and my old canstiers that were equipped are gone but i still have the extra hp.

**Steps to reproduce:**
No idea how to reproduce.
**Crash log (use pastebin or similar):**
It doesnt cause a crash so there is nothing to paste.

**Comment by Cazadorsniper** [comment]
Look at pinned issues.
