### ISSUE TITLE
crash with extra utilities 2

### ISSUE THREAD

**Issue by pyruxen** [Cazadorsniper/PO3#47]
3.0.38
**Description:**
game crashes after shift clicking into an extra utilities 2 block that has a partially filled stack.
**Steps to reproduce:**
open either a mechanical user or a furnace generator and try to shit click in additional items when the slots already have some items but not a full stack.
**Crash log:**
I don't have one sry

**Comment by juanitierno** [comment]
This happened to me too, I had 10 stacks of gravel (to be filled in a mechanical user that was sieving).
While filling the first 9 stacks some material was sieved, and when I clicked the 10th stack it crashed.

If it helps, this happened to me too on enigmatica 2, while loading some item into the resonator, so it could be mod related.
