### ISSUE TITLE
PO3 Server crash

### ISSUE THREAD

**Issue by kartalas1** [Cazadorsniper/PO3#470]
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or similar):**
[crash-2019-07-09_15.28.16-server.txt](https://github.com/Cazadorsniper/PO3/files/3372981/crash-2019-07-09_15.28.16-server.txt)

**Comment by Cazadorsniper** [comment]
Remove the second BrandonsCore (the 1.12.2-2.4.16.207-deobf.jar)

**Comment by kartalas1** [comment]
deleted it but this error then lul help pls
[latest.log](https://github.com/Cazadorsniper/PO3/files/3373537/latest.log)

**Comment by Cazadorsniper** [comment]
reinstall the pack.

**Comment by kartalas1** [comment]
same crash :( 
[latest.log](https://github.com/Cazadorsniper/PO3/files/3373796/latest.log)

**Comment by ByteTemplar** [comment]
In the crash log (first message) it shows you only allocate 4Gb memory, thats not nearly enough, up it to 6Gb first.
Second, why on earth did you install it on Desktop?! That will create all kinds of problems with Windows systems in general.

Just by Googling the error, there was mention about localization, that has somehow affected the naming and suggested adding to Java arguments this:
`-Duser.country=US -Duser.language=en`

**Comment by kartalas1** [comment]
nope didn't work. tried all same crash again

**Comment by kartalas1** [comment]
https://pastebin.com/XNfjskLG

**Comment by Cazadorsniper** [comment]
Try updating brandons core and draconic evolution

**Comment by kartalas1** [comment]
https://pastebin.com/sFad1aWk same error again ...

**Comment by Cazadorsniper** [comment]
I can only think that the 207-deobf.jar you had screwed something up. Only thing I can think of is to delete that whole profile then get a new one.

**Comment by kartalas1** [comment]
I don't see that jar file. What do you mean ?

**Comment by kartalas1** [comment]
oh i realized what do you mean sorry :D trying get a new profile

**Comment by kartalas1** [comment]
https://pastebin.com/y7ynXNwW i get same crash again i think its caused by my computer. What do you suggest me to do ?

**Comment by kartalas1** [comment]
[23:21:21] [Server thread/ERROR] [FML]: The mod moofluids is expecting signature @FINGERPRINT@ for source MooFluids-1.12.2-1.8.12.02a.jar, however there is no signature matching that description
[23:21:21] [Server thread/ERROR] [MooFluids]: No fingerprint found!

At the beginning of all console saying this what does it mean ?

**Comment by Cazadorsniper** [comment]
can ignore that.

**Comment by Cazadorsniper** [comment]
Small suggestion use only 6gb of ram not 8.

**Comment by kartalas1** [comment]
https://pastebin.com/GQu6CD3w nope same and same

**Comment by kartalas1** [comment]
can i run without this mods

**Comment by Cazadorsniper** [comment]
no because you'll get a lot of errors concerning Draconic Evolution.

**Comment by kartalas1** [comment]
Oh ok. Then any idea to do

**Comment by Cazadorsniper** [comment]
You can try using Multimc to start the pack.

**Comment by kartalas1** [comment]
how do i open server with multimc ?

**Comment by Cazadorsniper** [comment]
Can google that and there are loads of youtube videos on it.

**Comment by kartalas1** [comment]
didn't work as well same and same crash again

**Comment by kartalas1** [comment]
i tried another modpacks with brandonscore it gives same crash i think this mod don't like me

**Comment by Cazadorsniper** [comment]
hm, seem like something is on your computer that is preventing you from playing then and I don't know what it is.

**Comment by kartalas1** [comment]
ty for your help then have a nice day i gave up ;(

**Comment by Cazadorsniper** [comment]
Sorry
