### ISSUE TITLE
Cannot install on Twitch, Depenency missing

### ISSUE THREAD

**Issue by ctholm** [Cazadorsniper/PO3#472]
**Pack Version:** 
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
Cannot download
**Description:**
Downloading gives this error: This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 293702
**Steps to reproduce:**
Got the error first upgrading from 3.0.40. Error reappears when installing from scratch.
Everything downloads, but give the error during validation.
**Crash log (use pastebin or similar):**

**Comment by ctholm** [comment]
Seems to work running Twitch again as administrator.

**Comment by Nate2826** [comment]
same just decided to download to try this modpack and it kept failing on a dependency but it was a different number. closed twitch app and ran as admin and it actually got past the point of error and now installing the mods.
