### ISSUE TITLE
Philosopher Stone not able to craft

### ISSUE THREAD

**Issue by DarkDon** [Cazadorsniper/PO3#473]
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer and Multiplayer
**Description:**
Ultimate crafting of philosopher stone not working
**Steps to reproduce:**
try making the philosopher stone in ultimate crafting table
**Crash log (use pastebin or similar):**

**Comment by Cazadorsniper** [comment]
charge it.

**Comment by DarkDon** [comment]
Cant craft it ! The ingredients are in the ultimate crafting table but in the output there is nothing

**Comment by DarkDon** [comment]
[https://gyazo.com/31e453295586014a6acdb26bb92b0217](url)

**Comment by Cazadorsniper** [comment]
there is nothing in the middle

**Comment by DarkDon** [comment]
JEI doesnt say that something is suppose to go in the middle, what ingredient am i missing?

**Comment by Cazadorsniper** [comment]
look for ore:starEnder in JEI: $starEnder

**Comment by DarkDon** [comment]
[still not working see this](https://gyazo.com/e29c47895927bca46126da18d9d64817)

[recipe in JEI](https://gyazo.com/6b10126a4b75805bc136904b3e95d9d4)

**Comment by Cazadorsniper** [comment]
Ok, try redownloading the pack then moving your world over.

**Comment by DarkDon** [comment]
Same Problem on the new downloaded pack. And the Armor recipe for Dark Matter Helm is also Broken it shows just the supremium helmet with nothing around in a champion table.

**Comment by Cazadorsniper** [comment]
It seems twitchapp isn't downloading all the scripts.

**Comment by DarkDon** [comment]
can u upload the right scripts?

**Comment by Cazadorsniper** [comment]
This isn't us that is the problem.

**Comment by Cazadorsniper** [comment]
Did you remove Endermen Evolution by any chance?

**Comment by DarkDon** [comment]
Yeah because mobgrinding utils and evolved enderman keept crashing with ticking block exception

**Comment by Cazadorsniper** [comment]
that is why this error was happening then lol the script holding the ore dictionary additions was erroring due to the removal of that mod.

**Comment by gabewhatsupguy** [comment]
Just wanted to say thanks! I was having this same issue and had removed enderman evo aas well

**Comment by D-Pterano** [comment]
Whats the fix, aside from re-adding a mod that causes the server to crash?
