### ISSUE TITLE
Unable to complete quest "Lord's forge"

### ISSUE THREAD

**Issue by lucasvanhalst** [Cazadorsniper/PO3#474]
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
multiplayer
**Description:**
The betterquesting quest "Lord's Forge" (under "Mu" https://i.imgur.com/TnxiIsJ.png) cannot be completed as it requires you to craft the "Arcane Forge (Old)" which isn't craftable anymore. https://i.imgur.com/xXkTYXA.png
It should probably be changed to require you to craft the "Arcane Forge" (without the old)

**Comment by Cazadorsniper** [comment]
Was reported on discord so already fixed for next update.

**Comment by lucasvanhalst** [comment]
Ok, thanks.

**Comment by bachtok** [comment]
The new update just came out, built a Arcane forge, the quest still didn't registered as done. Even waited 5 min, pressed the detect button, waited, but still nothing. Am I just building the wrong thing, recipe contain 6x iron, 1x lava bucket, 1x furnace, 1x of that blue dust that i don't remember the name of, off hand, or do I have to do something else with the Arcane forge that I'm oblivious of.

**Comment by Cazadorsniper** [comment]
Did you do /bq_admin default load?

**Comment by bachtok** [comment]
That did the trick, thanks

**Comment by dr-toast** [comment]
is it possible to force complete it in 3.0.41 ?
