### ISSUE TITLE
Crash Stack overrun- Mob Slaughter Block

### ISSUE THREAD

**Issue by WickedBowie** [Cazadorsniper/PO3#475]
Game crashes about 15 seconds after load.

I believe the crash report is telling me the Slaughter Factory is at fault.

[crash-2019-07-09_20.18.11-server.txt](https://github.com/Cazadorsniper/PO3/files/3375239/crash-2019-07-09_20.18.11-server.txt)

**Comment by WickedBowie** [comment]
Nope, went in through MCEdit and removed Slaughter.

played fine for a couple minutes. turned the Mob Masher on and instant crash.
probably related to the mobfarm crash shown in other reports.

**Comment by Cazadorsniper** [comment]
#469 Always search before making the issue.
