### ISSUE TITLE
UncheckedExecutionException on login (wheat mismatch on registry)

### ISSUE THREAD

**Issue by merak69** [Cazadorsniper/PO3#476]
**Pack Version:** 3.0.41 - Multiplayer

**Description:** Updated server and client from 3.0.40 to 3.0.41.  Now every user gets a "fatally missing registry entries" on first login followed by an UncheckedExecutionException everytime after that (screenshot below).  I've compared all of the config, mods, and scripts between clients and server and they're basically identical.  I've also reinstalled the client from scratch to no avail.  I've hosted 20+ servers over the last several years and I'm at a loss.

This is identical to these two previous issues but the resolutions do not work here:
[https://github.com/Cazadorsniper/PO3/issues/256](url)
[https://github.com/Cazadorsniper/PO3/issues/267](url)

**Steps to reproduce:** Update to 3.0.41 and login.

**Crash log (use pastebin or similar):**

![po3issue](https://user-images.githubusercontent.com/11600344/60937455-11dcfc00-a296-11e9-8c6f-e038c862df94.png)

**Comment by Cazadorsniper** [comment]
That means something on the server or client isn't the same maybe added/removed a mod or tampered with the configs.

**Comment by merak69** [comment]
I used both Beyond Compare 3 and WinDiff to compare all of the files and they're the same for the config, mods, and scripts folders.  I did find a difference in the server configs vs the client configs for the released packs (aka what's on Twitch/Curseforge) but making them the same did not fix it.  The only way I found to fix this was to remove the world folder on the server and start over (obviously not a good option).

**Comment by Cazadorsniper** [comment]
So it works with a new world? if so that is odd.

**Comment by merak69** [comment]
I can't get it to work now with a new world either, so I'm guessing that was a fluke.  I tried a completely fresh install of the server files as uploaded on curseforge (+new world) and a fresh install of the 3.0.41 client from twitch and it does not work.

**Comment by merak69** [comment]
Deleted my prior comment... Apparently once the exception happens on the client side it's stuck there unless you restart the client.  Still can't get old world to work.  Is there any way to debug this in more detail?

**Comment by merak69** [comment]
I guess I'll stay on 3.0.40.
