### ISSUE TITLE
Hunting Dimension portal not working.

### ISSUE THREAD

**Issue by rexbattler** [Cazadorsniper/PO3#477]
**Pack Version: 3.0.41**
Single-player, Multiplayer, or LAN?: SP

**Description:**
Hunting Dimension portal not working.
**Steps to reproduce:**
Make the portal and it will not take you to the Hunting Dimension.
**Crash log (use pastebin or similar):**
Its not crashing just not working.
![2019-07-10_02 09 15](https://user-images.githubusercontent.com/52735387/60948198-026eaa80-a2b8-11e9-8126-9157e6a4130d.png)

**Comment by linpengasd** [comment]
Shift join

**Comment by rexbattler** [comment]
Thank you.
