### ISSUE TITLE
Missing FTB files in download

### ISSUE THREAD

**Issue by skwisgaar618** [Cazadorsniper/PO3#479]
I'm not sure how to start a server without the serverstart bat and I wasnt sure if any other files were missing from the server download for 3.0.41.  Any help would be greatly appreciated.  Mainly I'm not sure how to add mem without that file.

**Comment by Cazadorsniper** [comment]
Can make the file yourself just a quick google.

Also know that those files aren't FTB at all.

**Comment by coleslaw01gamer** [comment]
I made my own start.bat file for the pack. Ill add what my code was after this: 

_@ECHO OFF
java -Xms2G -Xmx4G -jar forge-2838.jar nogui
pause_

The -Xms2G is the minimum amount of memory you want your server to have cached, and likewise, -Xmx4G is the maximum you want your server to use.
