### ISSUE TITLE
equivalent integration crash?

### ISSUE THREAD

**Issue by ExoVengeance** [Cazadorsniper/PO3#48]
**Pack Version:**
3.0.38
**Description:**
just cant launch the game
**Steps to reproduce:**
hit play on the modpack
**Crash log:**
https://pastebin.com/Vgvnw3AU

**Comment by Cazadorsniper** [comment]
Reinstall the pack and try again.

**Comment by ExoVengeance** [comment]
I fixed the crash by not opening my inventory and using these commands  /baubles view {Name} find the slot it was in and then /baubles clear {name} [slot#] and cleared it i think it should crash i put it back it

**Comment by ExoVengeance** [comment]
So you can spread the word of the workaround if they get the same problem

**Comment by ExoVengeance** [comment]
its fixed thanks
