### ISSUE TITLE
Crash when Evolved Enderman dies on Golden Spike

### ISSUE THREAD

**Issue by tomisanhues2** [Cazadorsniper/PO3#480]
> Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** LAN and Singleplayer

**Description:** Server crashes when enderman evolved dies from Golden spike. Restarting game works but as soon as the enderman spawns the world recrashes. Almost unsaveable world

**Steps to reproduce:** Make a mobfarm and add golden spikes at the botton -> Crash

**Crash log (use pastebin or issue will be closed):** 
https://pastebin.com/K45jmAVi

**Comment by Cazadorsniper** [comment]
Did you use the search function before reporting? #469
