### ISSUE TITLE
PO3 3.0.41 beta current - Several Recipes are broken needs check on crafttweaker recipes

### ISSUE THREAD

**Issue by DarkDon** [Cazadorsniper/PO3#482]
> Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
Project Ozone 3.0.41 Beta current
**Singleplayer, Multiplayer, or LAN?:**
both
**Description:**
Several recipes 9x9 armor crafting are broken. Downloaded the pack several times from different sources to get the right scripts but still not working. 
**Steps to reproduce:**
try crafting for example dark matter helmet in champion workbench
**Crash log (use pastebin or issue will be closed):**

**Comment by DarkDon** [comment]
[Energy Condenser JEI](https://gyazo.com/0e7b5dcf2c3f28ca2733798b34270922)

[Energy Condenser Ultimate Crafting Table](https://gyazo.com/fc04435c366139e2fc17457263f37fbd)

[Dark Matter helmet JEI](https://gyazo.com/8d1418732a2a4db74e2e3c717adb5069)

I looked up the recipe scripts but im not an expert, maybe there is some " , " missing or "." or some "[]" 
dont know. Pls check the recipes

**Comment by Cazadorsniper** [comment]
`//energy condenser mk1
mods.extendedcrafting.TableCrafting.addShaped(0, <projecte:condenser_mk1>, [[null, null, null, null, null, null, null, null, null], [null, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, null], [null, <ore:matterRed>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <appliedenergistics2:material:38>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:matterRed>, null], [null, <ore:matterRed>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <appliedenergistics2:material:38>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:matterRed>, null], [null, <ore:matterRed>, <appliedenergistics2:material:38>, <appliedenergistics2:material:38>, <projecte:alchemical_chest>, <appliedenergistics2:material:38>, <appliedenergistics2:material:38>, <ore:matterRed>, null], [null, <ore:matterRed>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <appliedenergistics2:material:38>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:matterRed>, null], [null, <ore:matterRed>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <appliedenergistics2:material:38>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:matterRed>, null], [null, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, <ore:matterRed>, null], [null, null, null, null, null, null, null, null, null]]);`

**Comment by Cazadorsniper** [comment]
That recipe was pulled from Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward\scripts\normal\normal_9x9.zs at line 40 for the energy condenser mk1.

This was also done on a separate instance of PO3 that I updated to 3.0.41 yesterday. Which means that something wrong must of happen when you downloaded the pack since the recipes are there with no errors.

**Comment by Cazadorsniper** [comment]
I will make an attempt to fix this next update so it "shouldn't" happen.

**Comment by Cazadorsniper** [comment]
Deleted 2 of my comments because I found out why you're having this issue.

**Comment by Cazadorsniper** [comment]
It looks like in your installation the all_oredict.zs script isn't loading for some reason.

**Comment by ByteTemplar** [comment]
Yup, I can concur, that there is a problem on his installation. I just loaded my world in .41 and those recipes are showing correctly for me. 

Twitch seems to have quite a lot of problems and lotsa people think its the modpack, but in reality, its the launcher that is having problems installing.

**Comment by Cazadorsniper** [comment]
I put a priority preprocessor in the script so it will load before all other scripts do.

**Comment by freaktusend** [comment]
I have the similar issue, many Extended crafting recipies dont work like the ProjectE stuff and also ArmorPlus.
