### ISSUE TITLE
Constantan ingot does not have EMC value anymore in .41

### ISSUE THREAD

**Issue by ByteTemplar** [Cazadorsniper/PO3#483]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Title pretty much says it all. In .40 Constantan ingot had EMC value, cause I had Energy Condenser MK2 feeding to Quantum Compressor for Singularity in .40 and it was working fine. Is this a mistake perhaps? 

**Steps to reproduce:** Look at Constantan ingot tooltip :)

**Crash log (use pastebin or issue will be closed):** Non crash issue

**Comment by ByteTemplar** [comment]
Would it be possible to know how you added it? I tried with the command, it added it in config file, but still ingame after restart, no EMC value.

Command used (while holding Constantan ingot in hand):
`/projecte setEMC 576`
Value is calculated from copper and nickel and should be correct too.

**Comment by Cazadorsniper** [comment]
Because of Titan mode I had to switch to pregenerated EMC values.

**Comment by ByteTemplar** [comment]
Adding the line to "pregenerated_emc.json" file seems to work now indeed, will be adding the few missing ones there myself for now.

Should have read the ProjectE wiki bit more, as it is said there, if "pregenerated_emc.json" file exists, you cant use the commands anymore.
