### ISSUE TITLE
Wireless Universal Terminal

### ISSUE THREAD

**Issue by Dampen59** [Cazadorsniper/PO3#484]
**Pack Version:**
3.0.41

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
After crafting a Wireless Terminal, I decided to make a Wireless Universal Terminal.
Just after that, I placed it in the Charger and instant crash. I can't join the game anymore.

**Steps to reproduce:**
Place a Wireless Universal Terminal in a Charger.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/LZdqcKsC

**Comment by Cazadorsniper** [comment]
try to remove the universal terminal from your player and don't use extracells terminals.

**Comment by ByteTemplar** [comment]
I would also recommend updating your Java (Java Version: 1.8.0_51), its very old and known to have problems.
https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
(and yes, you need to have account to download from Oracle unfortunately)

**Comment by Dampen59** [comment]
Hello,
I think it is placed in the world and not in the inventory now..
I can't find it with NBT Explorer in my inventory

**Comment by ByteTemplar** [comment]
Did you check, if it is in Bauble slot in NBTexplorer?
Im guessing you have access to server files then?

**Comment by Dampen59** [comment]
Of course, it is my server.
This is what I have

![Capture](https://user-images.githubusercontent.com/13560162/61128262-b5eebf00-a4b1-11e9-8ffa-baa6a2cb0c17.PNG)

**Comment by Dampen59** [comment]
I removed the charger block using MCEdit

It's fixed by now
