### ISSUE TITLE
Wand of animation

### ISSUE THREAD

**Issue by jobaq007** [Cazadorsniper/PO3#486]
hello
I just have a question. I placed whatever block i animated into the mob duplicator and i only get stone copies. I had a diamond block and it only produce stone copies. 
Is this a bug? Lol or it is made of purpose?
**Pack Version: 3.0.40
**Singleplayer

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by ByteTemplar** [comment]
Activate Exact copy mode, button next to slot you put the pokeball. 
This is also for issues of the modpack, not for common questions. Next time try:
https://www.reddit.com/r/feedthebeast/
