### ISSUE TITLE
EndermenEvolution causing multiple crashes interacting with several mods

### ISSUE THREAD

**Issue by Samsei** [Cazadorsniper/PO3#487]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.41 (and 3.0.40 before updating)
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** EndermenEvolution causing crashes when interacting with other mods (Tinker's Construct and MobGrindingUtilities)

**Steps to reproduce:** Hit a Frienderman with a Tinker's Shuriken 
Have a Frienderman slain by the MobGrinder

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/5ucPBirM - Interacting with tinker's
https://pastebin.com/VkBwhxsN - Interacting with MobGrinding

**Comment by ByteTemplar** [comment]
Known issue: https://github.com/Cazadorsniper/PO3/issues/469

**Comment by ZeBrasa** [comment]
Have the same issue

**Comment by TheCoolOof** [comment]
I'm having the same problem as well crashes with even spikes

**Comment by ZeBrasa** [comment]
Has @Cazadorsniper, this will be fixed when they update the specified mod
