### ISSUE TITLE
extra utilities 2 

### ISSUE THREAD

**Issue by Dreamshinie** [Cazadorsniper/PO3#488]
Hello I have a problem in project ozone3 and although the mechanical user no longer works not in multiplayer and not him singel player

**Comment by Cazadorsniper** [comment]
What are you trying to use the mechanical user on?

**Comment by sharkbite3105** [comment]
if you are trying to automate your sieves, you have to go into the config for ex nihlio and set the fakeplayer to true, it is defaulted to false.

**Comment by nicros22** [comment]
Me too, with sieve. Mod is activate block with item and right click, I tried to place it all sides and still didn't work.

**Comment by sharkbite3105** [comment]
Not sure why my comment was deleted, however for the mechanical user, the mod configuration for ex nihlio creatio has a setting under mechanics called fakeplayercansieve, the default for this pack is set to false, changing that to true will allow you to automate sieving.
