### ISSUE TITLE
Crafting some ProjectE items doesn't work in multiplayer

### ISSUE THREAD

**Issue by lucasvanhalst** [Cazadorsniper/PO3#489]
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
multiplayer, works fine in singleplayer
**Description:**
Attempting to craft some stuff from ProjectE doesn't seem to work in multiplayer. Tried with philosopher's stone and transmutation table. The recipe shows up, but when you attempt to take the item it doesn't work. It just briefly flashes.
**Steps to reproduce:**
See this video, the part where it briefly shows up in my inventory is when I shift-click, but that doesn't work either.
https://streamable.com/hg38o

**Comment by Wip-Sama** [comment]
this problem is also in single player but only for transmutation tablet in 3.0.42

**Comment by Eragon20103** [comment]
Hey I also had the problem, did you disabled any mod? Because this was the cause for me I disabled ender an evolved and after I re-enabled it, it worked fine

**Comment by lucasvanhalst** [comment]
Yeah I had but I didn't test it after that. It's probably fixed in the latest version anyway.
