### ISSUE TITLE
botania skyblock server cannnot convert any liquid experience

### ISSUE THREAD

**Issue by jacob236** [Cazadorsniper/PO3#490]
Using the level botania-skyblock on a server the experience obelisk, xp drain, and experience rod all seem to be unusable. The xp drain will turn but will not dispense xp orbs when placed on a tank. The experience rod does not take out experience from a tank, and the experience obelisk does not even take in any experience from a pipe.

These things work fine in single player on a normal world, however, skyblock botania seems to break them all. Any suggestions?

**Comment by jacob236** [comment]
Using pack 3.0.41

**Comment by jacob236** [comment]
I also disabled the enderman evolution mod from the server and client side if that makes a difference

**Comment by Cazadorsniper** [comment]
Is this your server or someone elses that you're playing on?

**Comment by jacob236** [comment]
This is my own server

**Comment by jacob236** [comment]
https://imgur.com/a/IYwLrVA

this is the problem that I am experiencing so that you have a better idea of whats going on

**Comment by Cazadorsniper** [comment]
That is mob essence not liquid xp that is why.

**Comment by jacob236** [comment]
Welp, that's awkard.
Thank you for the help
