### ISSUE TITLE
Keep Randomly Crashing 

### ISSUE THREAD

**Issue by skydazable** [Cazadorsniper/PO3#492]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:** Singleplayer 

**Description:** I keep randomly crashing. Just updated my Java. 

**Steps to reproduce:** 

**Crash log (use pastebin or issue will be closed):** 
[crash-2019-07-13_22.26.40-server.txt](https://github.com/Cazadorsniper/PO3/files/3389399/crash-2019-07-13_22.26.40-server.txt)

**Comment by ByteTemplar** [comment]
Known issue: https://github.com/Cazadorsniper/PO3/issues/469
