### ISSUE TITLE
PO3 3.0.41 Server will not start

### ISSUE THREAD

**Issue by pacman1983** [Cazadorsniper/PO3#493]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Server gets stuck in a reboot loop. Will not load. I have started this pack from the beginning. I've done the updates from the start. With the latest pack the server was working for a day or so, then started to get into this reboot loop.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
[PasteBin crash report](https://pastebin.com/BtkHUFUw)

**Comment by Cazadorsniper** [comment]
Remove block at these coordinates (306,62,365), might be a translocator, if so then someone must of right clicked an iron ingot on the translocator.

**Comment by pacman1983** [comment]
Sorry for being a n00b, but how can I remove that block if I can't start the server?😓

**Comment by Cazadorsniper** [comment]
Believe by using Worldedit.

**Comment by pacman1983** [comment]
Thank you sir. Will try that and let you know

**Comment by pacman1983** [comment]
I ended up using this amazing program called [Universal Minecraft Editor](https://www.universalminecrafteditor.com/) 

Thank you sir for your help. This issue can be marked **CLOSED**!
