### ISSUE TITLE
Random crashes PO3 3.0.41

### ISSUE THREAD

**Issue by hibernatox** [Cazadorsniper/PO3#495]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.0.41**
**Multiplayer**

**I have the pack on my server and the pack crash when i stay more than 5 minutes**

**Steps to reproduce:**

**https://pastebin.com/iLS0UQ9a**

**Comment by ByteTemplar** [comment]
Dont people ever search first?! This is known issue: https://github.com/Cazadorsniper/PO3/issues/469

**Comment by hibernatox** [comment]
> Dont people ever search first?! This is known issue: #469

i will try it, but i m on a new game i didn t even open TF
