### ISSUE TITLE
PO3 randomly crashes due to the enderman evolution mod

### ISSUE THREAD

**Issue by TheCoolOof** [Cazadorsniper/PO3#496]
Pack Version:3.0.41

Singleplayer, Multiplayer, or LAN?: SinglePlayer

Description: My game randomly freezes then crashes ever since i updated to the new version of the pack. I have a mod farm and i use Iron spikes from the mob grinding mod and the game crashes saying entity collision evolved enderman. This bug has made me stop my mob farm and Hopefully this bug will be fixed in the next update

Steps to reproduce:

: https://pastebin.com/PhZkGcaq

**Comment by ZeBrasa** [comment]
Know issue: #469
