### ISSUE TITLE
Can't go through blocks while in spectator mode

### ISSUE THREAD

**Issue by jinkhya** [Cazadorsniper/PO3#5]
Hello, 
when you go into spectator mode you cannot go through anything. Is there a config or a mod causing that and is it possible to allow it again? 
Thanks in advance,
Jin

**Comment by Cazadorsniper** [comment]
Put on multi armor and activate no clip mode with the keybind.

**Comment by jinkhya** [comment]
That works, not very practical though as an admin on a server to have to cheat in an armor set and use keybind when vanilla minecraft has that feature. Any idea what's causing this? Never seen that issue  before on other packs.

**Comment by Cazadorsniper** [comment]
Nope, have no idea.
