### ISSUE TITLE
Autojump disabled but still working (no ability totem)

### ISSUE THREAD

**Issue by Emax220x** [Cazadorsniper/PO3#50]
**Pack Version:**
3.0.35
**Description:**
I don't know why, but i got autojump randomly. In controls is disabled and i don't have Step Assist from Ability Totem, any idea about the possible cause?
**Steps to reproduce:**

**Crash log:**

**Comment by Ar4093** [comment]
Check your keybinds. By default, Quark binds the autojump toggle to B.

**Comment by Emax220x** [comment]
> Check your keybinds. By default, Quark binds the autojump toggle to B.

Already done that, when i press B (only one keybind) this shows up and nothing changes
![image](https://user-images.githubusercontent.com/31655629/53641197-83dd6e80-3c2e-11e9-8b59-368d424eff4e.png)

**Comment by s1mples** [comment]
What boots you weared on?

**Comment by Emax220x** [comment]
> What boots you weared on?

Not wearing any armor atm, i'm using resistence 5 ability totem, regeneration and 40 heart canisters
