### ISSUE TITLE
Chance cube modmaker deliberately griefing

### ISSUE THREAD

**Issue by Githerax** [Cazadorsniper/PO3#500]
This mod is destructive and doesn't contribute to anything related to the mod progression or the player's creativity or work.  Just the opposite, it destroys what players make and do.  I removed it from my version, I suggest you remove it from the pack to avoid new players losing interest due damage or loss.

**Comment by ByteTemplar** [comment]
This really doesnt belong here, you cant just push your opinion to other people like that, its pointless...
