### ISSUE TITLE
Crashing when loading old world

### ISSUE THREAD

**Issue by Oakmontowls** [Cazadorsniper/PO3#501]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Game crashes upon attempting to load world that worked fine in 3.0.40
Making and loading a new world works fine.
**Steps to reproduce:**
Load my world
http://www.mediafire.com/file/s2pa17nbkg1h59u/New_World--restore.rar
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/vnZJE44S

**Comment by Cazadorsniper** [comment]
"EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\oakmo\Documents\Curse\Minecraft\Instances\Project Ozone 3 A New Way Forward (2)\saves\New World--restore\EnderStorage and start the server again."

**Comment by Oakmontowls** [comment]
It now gets further in loading but spits out a new error. I'm guessing since it says the game crashed when loading nbt data that it is a specific block that is causing this new crash
https://pastebin.com/Egdv3TL1

**Comment by Oakmontowls** [comment]
Using Mcedit and deleting the transmutation chamber and transmutation disassembler let me load the world.
