### ISSUE TITLE
Mechanical user doesn't work with sieve

### ISSUE THREAD

**Issue by nicros22** [Cazadorsniper/PO3#503]
Pack Version: 3.0.41

Singleplayer, Multiplayer, or LAN?: Singleplayer

Description:
Mod is activate block with item and right-click, I tried to place it all sides and still doesn't work.

Steps to reproduce:
Crash log (use pastebin or issue will be closed):

**Comment by sharkbite3105** [comment]
go into the config file for ex nihlio and change the fake player setting to true, they do still work.

**Comment by sharkbite3105** [comment]
the mod configuration for ex nihlio creatio has a setting under mechanics called fakeplayercansieve, the default for this pack is set to false, changing that to true will allow you to automate sieving.

**Comment by ByteTemplar** [comment]
It wont work, because it is disabled in the configs of the modpack.

`B:fakePlayersCanSieve=false`
