### ISSUE TITLE
Pebble crafting to blocks bugged

### ISSUE THREAD

**Issue by Adamo55f** [Cazadorsniper/PO3#506]
Pebble crafting for Diorite block, Granite block , and Andesite block from Ex Nihilo: Creatio defaulting to Cobblestone on crafting output. PO3 Version 3.0.41 (Modded) Forge - 14.23.5.2838 Singleplayer.

![2019-07-20_14 15 05](https://user-images.githubusercontent.com/53107282/61583240-fb873980-aafa-11e9-9dcb-708a6549322f.png)
![2019-07-20_14 15 18](https://user-images.githubusercontent.com/53107282/61583249-08a42880-aafb-11e9-9fd8-1d4d2d92a699.png)
![2019-07-20_14 15 29](https://user-images.githubusercontent.com/53107282/61583250-0c37af80-aafb-11e9-968c-f80d824d0a83.png)
![2019-07-20_14 16 24](https://user-images.githubusercontent.com/53107282/61583251-0e9a0980-aafb-11e9-8ef5-9452d5656ad3.png)
![2019-07-20_14 16 36](https://user-images.githubusercontent.com/53107282/61583254-122d9080-aafb-11e9-9010-9e893d15be92.png)
![2019-07-20_14 16 47](https://user-images.githubusercontent.com/53107282/61583255-148fea80-aafb-11e9-8fcf-91a81a60a256.png)

**Comment by Cazadorsniper** [comment]
can go to another dimension to get the other stones.

**Comment by Adamo55f** [comment]
So it's intentional? I've tested it on all crafting table variants and the same issue occurs.

**Comment by Cazadorsniper** [comment]
yes, I oredicted the pebbles for Titan mode.

**Comment by Adamo55f** [comment]
Okay, thank you for clarifying.
