### ISSUE TITLE
EnderIO lag spike

### ISSUE THREAD

**Issue by NiallDoherty** [Cazadorsniper/PO3#508]
**Pack Version:** 3.0.41

**Singleplayer, Multiplayer, or LAN?:** Multiplayer and Singleplayer

**Description:** Every time I open an EnderIO machine I get a huge lag spike.

**Steps to reproduce:** Right click an EnderIO machine, alloy smelter, sag mill etc.

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by sharkbite3105** [comment]
I noticed this as well, I play only in single player.

**Comment by ByteTemplar** [comment]
Never had this problem myself.
Trying to find what does it can be challenging though. How is the server TPS? Maybe check with LagGoggless if the machines are having problems.

**Comment by NiallDoherty** [comment]
Update: Project intelligence is causing this.

**Comment by kbekir** [comment]
Hi, 
How could you solve this problem or could you solve?

**Comment by IgnisFlamme** [comment]
I can confirm it has something to do with project intelligence. Every Ender I/O machine lags like crazy whenever I right click on them. LagGoggles make them show up as red and do about 78ms of delay on my end which is kinda insane.

**Comment by tyler489** [comment]
78 MS of lag is absolutely nothing.. that's less than one second of delay

**Comment by devomaa** [comment]
..788ms?
