### ISSUE TITLE
Mob Crusher Crash

### ISSUE THREAD

**Issue by scoterbd** [Cazadorsniper/PO3#509]
3.0.41
Multiplayer

I am currently playing on a server hosted by BisectHosting. The server contains 4gbs of ram and has so far run perfectly fine. When using the mob crusher block, it is able to run for a limited period of time before the server crashes. I've used item conduits from Ender IO to make sure no items or entities are left in the mob spawner room in order to prefect crashing from this issue. After consulting with the BisectHosting support system, they assured that more ram would not fix the problem and it is a problem with the mod itself. Everytime the server crashes I simply get a "Server Closed" message and have to wait for it to restart.

**Comment by Silverstray** [comment]
I have had the same crash it is being worked on, it's related to/because of the same issue as #469
