### ISSUE TITLE
Using ProjectE's Tome of Knowledge causes some learned transmutations to disappear, and cannot be relearned

### ISSUE THREAD

**Issue by Zapstur** [Cazadorsniper/PO3#51]
Specifically, one thing I noticed is that most of the "Quantum Bags" from QuantumStorage are prone to this:  The only one that stays in the menu after using the Tome of Knowledge is the "Quantum Bag Orange"

**Comment by martinschuberteu** [comment]
You have to charge the Philosopher's Stone. There was also issue #39 opened for this and a charged Philosopher's Stone worked for the author.
