### ISSUE TITLE
Unable to upgrade tinker's construct tools

### ISSUE THREAD

**Issue by ZeBrasa** [Cazadorsniper/PO3#511]
**Pack Version:** 3.41
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Can't upgrade a tool since last update. Worked before
**Steps to reproduce:**
Tool forge, use "old" tool, then use head (this case is axe head) to upgrade
**Crash log (use pastebin or issue will be closed):**
No crash, but screenshot attached http://prntscr.com/oin89v

**Comment by ZeBrasa** [comment]
I missclicked and committed the issue before I finnished it. Can you reopen it please? @Cazadorsniper

**Comment by Cazadorsniper** [comment]
does this happen with new tools?

**Comment by ZeBrasa** [comment]
I will try when i get home and report back.

**Comment by ZeBrasa** [comment]
I can upgrade a weapon that I just made. Even if I had modifiers it seems. But can't add mending moss. It is probably that that is causing the issue.
http://prntscr.com/oj36l9

**Comment by Cazadorsniper** [comment]
How about just making it unbreakable?

**Comment by ZeBrasa** [comment]
Yeah, i know. But before i didn't, and my tools before the update all have that. I see that you disabled ir, so I guess I just reactivate Mending Moss for a bit
