### ISSUE TITLE
Unable to craft ProjectE´s Tome of Knowledge

### ISSUE THREAD

**Issue by draXalia** [Cazadorsniper/PO3#512]
Pack Version: Singleplayer, Multiplayer, or LAN?:
Singleplayer/V3.0.41

Description:
The Title says it all ^^
I did no chages which could affect this recipe, it is shown in JEI

Steps to reproduce:
Well, clickin i guess?

Crash log (use pastebin or issue will be closed):
no crash

**Comment by ByteTemplar** [comment]
I crafted it few days ago in .41 without any problems. What seems to be the problem then, details would be nice...

**Comment by draXalia** [comment]
Well, idk what you mean. It isn’t shown in the output slot, simply not craftable, though shown in JEI (which shouldn’t show any wrong recipes)

**Comment by Cazadorsniper** [comment]
screenshots would help.

**Comment by ByteTemplar** [comment]
Does the plus sign add all the resources to the crafting table from JEI? It will highlight if there are something wrong and not add them...

**Comment by draXalia** [comment]
Sorry for letting you waiting that long, but i have good news: i found the problem.
Enhanced Ender Ingot (EC) was not shown in JEI! Though i dont know why it does now, i changed exactly nothing...
And @ByteTemplar it did, i´m not new to all of this ;)

**Comment by Cazadorsniper** [comment]
ah
