### ISSUE TITLE
Server crashes randomly 

### ISSUE THREAD

**Issue by georgen2003** [Cazadorsniper/PO3#515]
I have this issue . My server crashes randomly and I cannot figure out why .my server provider company told my to contact the developer .
This is a pate bin of the console https://pastebin.com/UJLn8fyd
Thank you in advance

**Comment by Cazadorsniper** [comment]
Duplicate of #469

**Comment by georgen2003** [comment]
Do you know when this update will be availiable

**Comment by cmousoula** [comment]
As per georgen2003, any indication when this fix will be released? Thanks
