### ISSUE TITLE
[Mod Request] ComputerCraft

### ISSUE THREAD

**Issue by NiallDoherty** [Cazadorsniper/PO3#516]
Link: https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

This is the updated version of ComputerCraft for 1.12+, hopefully you'll consider adding it.

**Comment by Cazadorsniper** [comment]
Not planning on adding any mods.

**Comment by NiallDoherty** [comment]
Ok man, just thought I'd suggest since I noticed in Hypno's play through the closed beta had the old version of CC.
