### ISSUE TITLE
Sorry, found the duplicate issue too late, advise the workaround?

### ISSUE THREAD

**Issue by dr-toast** [Cazadorsniper/PO3#517]
**Pack Version:**
3.0.41

How do i disable a mod on my server for the temp work around for my mob farm?

edit because i eventually spotted the one on the twilight forest evolved endermen+charm of life thread and compared the reports so i repurposed the new issue

**Comment by Cazadorsniper** [comment]
By removing the mod from the server. its the same way as the client.

**Comment by dr-toast** [comment]
I'd normally use the in launcher disable button? Sorry

**Comment by Cazadorsniper** [comment]
Can just remove the mod.
