### ISSUE TITLE
Asper Fences everywhere

### ISSUE THREAD

**Issue by dutchsmurf** [Cazadorsniper/PO3#520]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
3.0.41
**Singleplayer, Multiplayer, or LAN?:** 
Singleplayer

**Description:**
The edges of the Overworld (like 32 chunks from the starting point) and the complete Hunting Dimension are filled with asper fences from Erebus. Like filled from bottom to top and as far as the eye can see. In the Overworld it is only a minor issue, but it means the Hunting Dimension and possibly other dimensions too basically don't exist. Any way to fix this?

**Steps to reproduce:**
I tried reproducing with a random seed. That however didn't create the same problem.
Tried again with the same seed of my bugged world, but that didn't reproduce the problem either. So no idea how I managed this.

**Crash log (use pastebin or issue will be closed):**
The game doesn't crash, so I don't have a crash log.

**Comment by Cazadorsniper** [comment]
Did you add/remove a mod at some point?

**Comment by dutchsmurf** [comment]
I didn't add or remove mods.

After posting I tried deleting the hunting dimension and letting it reform on its own. This worked for a couple seconds. I could see a red dot on the mini-map, but before the game fully loaded, everything got replaced with fences again.

**Comment by Cazadorsniper** [comment]
This usually happens when the item/block ids shift or when the world is corrupted (and its best to start a new world).
