### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Eng3llus** [Cazadorsniper/PO3#522]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.41
Singleplayer/ LAN

**Description:**
mostly when opening or closing a chest, once when using the armor table
**Steps to reproduce:**
takes about 30 mins or more 

[crash-2019-07-27_21.31.55-server.txt](https://github.com/Cazadorsniper/PO3/files/3440176/crash-2019-07-27_21.31.55-server.txt)

**Crash log (use pastebin or issue will be closed):**

**Comment by primax** [comment]
Looks like the same crash problem i had.
i disabled EndermanEvolution and no more crashes.
