### ISSUE TITLE
Evlolved Emdermand and MobUtilities Iron Spikes Crash

### ISSUE THREAD

**Issue by wmcmillenjr** [Cazadorsniper/PO3#525]
**Pack Version:**
3.0.14
**Singleplayer, Multiplayer, or LAN?:**
Single Player world
**Description:**
An Evolved Enderman being killed with the MobUtilities Iron Spikes crashes game. 
**Steps to reproduce:**
Place Mob Utilities Iron spikes in a mob farm and let an Evolved Enderman die on them. 
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/r1LgHgkK

**Comment by Cazadorsniper** [comment]
Duplicate of #469
