### ISSUE TITLE
Crash from Waila. PO3 3.0.41

### ISSUE THREAD

**Issue by FirefighterKyle** [Cazadorsniper/PO3#526]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Did a three hour stream no problem, did some offline stuff (off camera) then started having problems (first crash) Now it crashes right away after it gets 7/7 done.
**Steps to reproduce:**
Load game, first crash I got was putting stone block in iron furnace
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/7EQwGh3t

**Comment by Cazadorsniper** [comment]
All I can say is try reinstalling the pack then move the world over.

**Comment by FirefighterKyle** [comment]
Alright will try that, thank you.
