### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by PexonTV** [Cazadorsniper/PO3#530]
Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.0.41
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Game crashes after a few seconds ingame

Steps to reproduce: 16 Spectrecoils in Simple Void

Crash log (use pastebin or issue will be closed):
https://pastebin.com/wqSLgVRj

**Comment by Cazadorsniper** [comment]
Duplicate of #469
