### ISSUE TITLE
Magneticraft hammers not making doubleplates after first use

### ISSUE THREAD

**Issue by sharkbite3105** [Cazadorsniper/PO3#531]
*searched to see if this was a known issue*
Pack Version: Singleplayer, Multiplayer, or LAN?: Singleplayer 3.0.41

Description: Magneticraft hammers get only one use when making doubleplate iron

Steps to reproduce: use a fresh hammer from magneticraft to make doubleplate iron multiple times

Crash log (use pastebin or issue will be closed): not a crash

**Comment by Cazadorsniper** [comment]
There is a doubleplate iron?

**Comment by sharkbite3105** [comment]
yes, the recipe is a magneticraft hammer and two iron ingots, other metals can also be used.

**Comment by Cazadorsniper** [comment]
solved for next update, removed the crafting recipe just use the crushing table.

**Comment by sharkbite3105** [comment]
so does this also mean the recipes for the water generator, thermopile and wind turbine are going to be fixed? they all use the doubleplate items.

**Comment by Cazadorsniper** [comment]
I can't fixed those: please look at their recipes.

**Comment by sharkbite3105** [comment]
ok, that's fine there's the alternate recipes too that use the immersive eng stuff its all good.
