### ISSUE TITLE
Server making Issue

### ISSUE THREAD

**Issue by GCPleb** [Cazadorsniper/PO3#537]
Pack Version:Project Ozone 2 2.4.0 Singleplayer, Multiplayer, or LAN?: Server

Description: Whenever I try to start the server it would seem like it is loading 

Steps to reproduce: Download the server files and delete the server ip in settings and delete hardcore questing then attempt to start up the server( This is also on mac and on project ozone 2)

Crash log (use pastebin or issue will be closed): https://pastebin.com/DLUSVB0v

**Comment by ByteTemplar** [comment]
First, this is Project Ozone 3 issue tracker, so wrong place!

Second, why are you trying to run client side only mods on a server (ResourceLoader in this case)? I checked and the server download **does not** include it (obviously) but your crash log shows its installed in your case. So you have messed something up. Reinstall everything and try not to mess with things you dont understand...
