### ISSUE TITLE
Can't launch pack with optifine.

### ISSUE THREAD

**Issue by austin1346** [Cazadorsniper/PO3#539]
My game without optifine takes abour 6m50s on average to launch. However, after installing optifine it takes about 55 minutes and then just crashes.

I've tried OptiFine 1.12.2 HD U E3    &    OptiFine 1.12.2 HD U C5
They are the earliest and latest versions for 1.12.2 (Optifine ultra).
It seems to get stuck on the ModelManager and ModelLoader parts for Minecraft Engine Init which is 3/7 in the loading screen.
I've looked around and nobody seems to have this issue, a lot of threads say people are using optifine just fine. I'll try to get one of my friends to run it and see what happens. Thanks in advance.

**Comment by Cazadorsniper** [comment]
Then remove optifine?

**Comment by austin1346** [comment]
I can't run the pack anymore above ~30fps... contstantly stuttering/micro freezes. When I started my world I was getting around 180fps. Optifine usually fixes this for me. I've tried a few other performance mods but the pack already has almost all of them.

**Comment by Cazadorsniper** [comment]
What do you have in your world right now?

**Comment by TehPotFarmer** [comment]
IMO and just my opinion you need to allocate more Ram dude, I was giving it 6gig as advised in the pack's description and was just crashing with fast flight,  stutters while walking, 9gig is more like it

**Comment by MichalPetryka** [comment]
For me it loads fine with optifine.

**Comment by austin1346** [comment]
> For me it loads fine with optifine.

What version of optifine and PO3?

**Comment by IgnisFlamme** [comment]
Optifine probably increases the amount of ram needed so I suggest allocating about 8 to 10 gigs of RAM.

**Comment by DeeJayHarrison** [comment]
I'm running Version: 3.1.43 and OptiFine still doesn't work in the pack even when you up the RAM to 10GB

**Comment by TehPotFarmer** [comment]
isn't OptiFine_1.12.2_HD_U_E3 the one for the version of forge.......

**Comment by JackMeds** [comment]
Version: 3.1.43
OptiFine:F1
RAM:12G
cannot launch

**Comment by JackMeds** [comment]
and my cpu is i9-9900kf

**Comment by JackMeds** [comment]
i9-9900kf
java RAM:12G
OptiFine_1.12.2_HD_U_F4
Version: 3.1.44
cannot launch

**Comment by JackMeds** [comment]
Very slowly
cpu usage just 5%
