### ISSUE TITLE
how to start abyssal in .38?

### ISSUE THREAD

**Issue by DoomSquirter** [Cazadorsniper/PO3#54]
**Pack Version:**
3.0.38
**Description:**
in 3.0.38 you disabled shoggoths from spawning in overworld and I don't see shoggoth's spawning anywhere I go.  Where am I to find them to start collecting PE for abyssal?

**Steps to reproduce:**

**Crash log:**

**Comment by Zapstur** [comment]
Lesser Shoggoths will spawn on Shoggoth Biomass, which can be crafted easily.  Or, if you actually want to find them, go to a Swamp biome.  There are structures set into the ground which have that Shoggoth Biomass in them.

**Comment by DoomSquirter** [comment]
oh ok, didn't know the biomass was craftable.  that's def an option.

for clarification tho, when you say go to a swamp biome, you mean in the void overworld?

**Comment by DoomSquirter** [comment]
duh, biomass is even a quest lol  *feels dumb man*    thanks
