### ISSUE TITLE
crash randomly after world is loaded

### ISSUE THREAD

**Issue by 73Salmin** [Cazadorsniper/PO3#541]
Pack Version:
3.0.41

Singleplayer, Multiplayer, or LAN?:
Singleplayer

Description:
when i started playing the game everything was just fine and then after i started in abyssalcraft mod my game crashed every 5-7 min into the world.

Steps to reproduce:
even if i afk the game crashes

Crash log (use pastebin or issue will be closed):
https://pastebin.com/XTQLrpD3

**Comment by Cazadorsniper** [comment]
Duplicate of #469
