### ISSUE TITLE
Crash due to an interaction between a mob and mob masher

### ISSUE THREAD

**Issue by CloudSerpentSR** [Cazadorsniper/PO3#543]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Getting a crash from supposedly killing an evolved enderman with a mob masher from mob_grinding_utils (my guess).

**Steps to reproduce:** Wait for an evolved enderman to spawn in my mob farm, and let it get killed by the mob masher.

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/C5hzWLp2

**Comment by BuffaloCarnivore** [comment]
i've been having the same problem, from what i've been able to see, when ever an evolved enderman is hit by a mob masher the game crashes
[crash-2019-08-08_12.34.28-server.txt](https://github.com/Cazadorsniper/PO3/files/3479596/crash-2019-08-08_12.34.28-server.txt)
