### ISSUE TITLE
Better Questing Book, has no quests

### ISSUE THREAD

**Issue by svalokin** [Cazadorsniper/PO3#544]
**3.0.41**
**Multiplayer**

**When the server launches, players do not spawn with quest book, when book is given through creative mode the book is empty.**

**Just joining the server and giving book to player.**

**Comment by Cazadorsniper** [comment]
start the server using forge.jar.

**Comment by svalokin** [comment]
I did....

**Comment by Cazadorsniper** [comment]
do you have the config folder in the server folder?

**Comment by svalokin** [comment]
yep

**Comment by Cazadorsniper** [comment]
try /bq_admin default load and /bqs_loot default load
