### ISSUE TITLE
Crash on startup from multimc

### ISSUE THREAD

**Issue by ebobram** [Cazadorsniper/PO3#546]
PO3 3.0.41
singleplayer

when launching the pack, after 5 minutes, the pack crashes, I updated my drivers and installed the modpack from downloading the zip file from the curse forge website

launch the game

https://paste.ee/p/5PcMI

**Comment by ByteTemplar** [comment]
You have extremely old Java version (1.8.0_05), update!
https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by ebobram** [comment]
it seems to get further into startup now but it is still crashing
https://paste.ee/p/0cotf

**Comment by Cazadorsniper** [comment]
try updating ex nihilo in that instance.

**Comment by ByteTemplar** [comment]
According the new log, you are STILL using the old Java version to launch the game...

**Comment by ebobram** [comment]
i deleted all my old versions of java and reinstalled the pack. it is working now, thank you very much
