### ISSUE TITLE
Collision crashes

### ISSUE THREAD

**Issue by dretax** [Cazadorsniper/PO3#551]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: Latest version**
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**

**Steps to reproduce:**
No idea, but seems like a spike issue with an enderman entity.
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/VVzKRTTa

**Comment by Cazadorsniper** [comment]
Use the search function before reporting to see if the issue has been reported before.
