### ISSUE TITLE
World Loading and Unloading

### ISSUE THREAD

**Issue by MWRK1** [Cazadorsniper/PO3#552]
3.0.40 and 3.0.41
Singleplayer

Saw a related issue, but it isn't quite the same as the other. I'm having an issue with the void dimension loading and unloading which causes severe lag, but no crashing. I tried putting a chunk loader in the dimension to stop the unloading but it didn't work, I also tried removing any mobs I had caught, but that also didn't work. I deleted the dim -2 world folder as well to try to reset it but nothing. 

Not sure if it is reproducible, though it happens every time I start the world

Couldn't add to pastebin since I only have the log and it is too large, I've attached it here though.
[latest.log](https://github.com/Cazadorsniper/PO3/files/3494530/latest.log)

**Comment by Cazadorsniper** [comment]
Do you have any pink slimes at all?

**Comment by MWRK1** [comment]
Nope

**Comment by Cazadorsniper** [comment]
Anything using industrial foregoing machines?

**Comment by MWRK1** [comment]
Yeah, I have an auto rubber system, some ranchers for fluid cows, and bunch of mob duplicators, but nothing that relates to the void dimension.

**Comment by Cazadorsniper** [comment]
try removing them and seeing if it fixes the issue.

**Comment by preceptor-teeth** [comment]
I'm getting this as well:  https://pastebin.com/EDTpf3gt

I am using a slaughterhouse to generate pink slime, but not duplicating pink slimes.  I use mob duplicators on animated blocks though.

I tried adding a chunk loader into Landia, but it didn't help.
