### ISSUE TITLE
Extra Utilities Cursed Earth

### ISSUE THREAD

**Issue by timmbobb** [Cazadorsniper/PO3#555]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:** I know this problem has been reported, but I think this is a little bit different. To prevent Evolved Enderman from spawning, I used an Ender IO aversion obelisk. It worked fine until I put cursed earth in my mob farm to increase spawn rates. It seems that cursed earth from extra utilities 2 does not pay attention to the aversion obelisk. I went into the EU2 config files and there is a blacklist entity option to stop a specific entity from spawning. I tried blacklisting the Evolved Enderman, but it would just create an error config file and then make a new one. I tried doing it with a vanilla spider as well, and it still didn't work. 

**Steps to reproduce:** Enderman Evolution/Aversion Obelisk/Cursed earth

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/fmPPWhDH

**Comment by IgnisFlamme** [comment]
To prevent the Evolved Enderman from spawning, I simply removed the mod for it and just continued on. I've progressed just fine throughout the modpack without it. Easy solution.

**Comment by ElysianHellkite** [comment]
I just deleted the enderman evolution jar file, no more crashing
