### ISSUE TITLE
Improper fluid transfer leads to permanent crash-loop

### ISSUE THREAD

**Issue by Heavyy05** [Cazadorsniper/PO3#556]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.41

**Singleplayer, Multiplayer, or LAN?:**
Single player

**Description:**
Attempted to do a fluid transfer that is not the intended method.  Posting in hopes of getting a resolution for the person that is as stupid as me that doesn't have a back-up that happened to be less than two hours old.

Had a Mekanism Fluid Tank with lava in it and attempted to use an Ender IO Pressurized Fluid Conduit to transfer the fluid directly in to an Applied Energistics 2 ME Chest that had an Extra Cells 2 4096k Fluid Storage Cell.  This caused the game to immediately crash and then crash on load of world every time thereafter.

*NOTE: I have removed EndermanEvolution-1.12.2-1.0.29 from the pack entirely and per [this post](https://github.com/Cazadorsniper/PO3/issues/469#issuecomment-518226442) deleted line 43 of all_oredict.zs*

**Steps to reproduce:**
1. Fill and place a Fluid tank with lava
1. Place ME Chest and insert 4096k Fluid Storage Cell
1. Connect pressurized fluid conduit to each block
   1. Conduit on fluid tank set to extract only, redstone mode always active
   1. Conduit on ME Chest set to insert only, redstone mode always active

**Attempted Troubleshooting:**
1. Reboot of PC
1. Removing level.dat, level.dat_old, session.lock and replacing them with freshly generated files
1. Changing Ender IO Settings in Ender IO Configuration -> enderioconduits -> conduit -> fluid
   1. Set all values to 0 prior to loading in to world

Results: No change, still crashes

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/7YQtvV5S

*Search Visibility*
~extracells.inventory.cell.HandlerItemStorageFluid.persist(HandlerItemStorageFluid.java:420)~
~extracells inventory cell HandlerItemStorageFluid persist (HandlerItemStorageFluid java 420)~
~extracells inventory cell Handler Item Storage Fluid persist (Handler Item Storage Fluid java 420)~

**Comment by Cazadorsniper** [comment]
Only solution I can give is to use worldedit to remove the me chest from the world.
