### ISSUE TITLE
Embers Issue?

### ISSUE THREAD

**Issue by RealTrueDeviL** [Cazadorsniper/PO3#557]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:** Embers seems bugged, no 'ember power'

See here: https://youtu.be/UYM8-jlezD4 (ingore the 'couple' remark, I found the problem with the second issue)

**Steps to reproduce:** Nothing special, I followed 3 different tutorials, and they all say the same, it seems to be just not working.. What have I don'e wrong?

**Crash log (use pastebin or issue will be closed):** There is no crash log

**Comment by Cazadorsniper** [comment]
Shift-click the receptor and right click the emitter.

**Comment by RealTrueDeviL** [comment]
Oh so you don't shift-click the emitter? ok.. I'll try it, maybe I just misheard the instructions.. Thanks

**Comment by Cazadorsniper** [comment]
No problem.
