### ISSUE TITLE
Drinking milk duplicates bucket (again?)

### ISSUE THREAD

**Issue by OuiGH** [Cazadorsniper/PO3#562]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**Latest
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**I can't see what the previous fix was as I am sure I introduced this issue myself.

**Steps to reproduce:**Milk Cow, Drink Milk

**Comment by itanshi** [comment]
confirm, version 3.1.44

**Comment by Cazadorsniper** [comment]
Some mod is adding milk as a liquid that can be placed in the world and sadly that is what is causing the issue. Oh well free buckets lol.
