### ISSUE TITLE
Can't get clay from water barrels

### ISSUE THREAD

**Issue by RadGH** [Cazadorsniper/PO3#563]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** You can't make clay in a crucible (anymore?) so you need to transfer water to a barrel. You get two bottles from the first quest (to remedy the problem?). But using the glass bottles provided from the first quest, you can't fill the barrel.

It's been 7 days without rain in a "Deep Ocean" biome without a bed/sleeping so I appear to be stuck :(

**Steps to reproduce:**
1. Create a wooden crucible
2. "Melt" leaves into water
3. Use bottles to transfer water to wooden barrel
4. Notice it adds 333 units of water per bottle, up to 999/1000
5. You need 1000 water to make clay

**Crash log (use pastebin or issue will be closed):**
n/a

**Comment by RadGH** [comment]
Forgot to mention, hopefully it was obvious, but this was the garden of glass skyblock map. I realized I don't need water to get iron I just had to make a flint mesh.

The quest book "Water to clay" description should probably be improved though, it doesn't have enough information :/

**Comment by Cazadorsniper** [comment]
Ex nihilo tends to bug out sometimes with glass bottles and barrels. This doesn't happen often. Try making a bucket.

**Comment by IgnisFlamme** [comment]
I agree the water bottles tend to be a bit buggy, try making a clay bucket with the first clay that you manage.

**Comment by IgnisFlamme** [comment]
I couldn't use bowls to pick up water from the wooden crucibles. I have no idea why but it doesn't seem to be working in this pack. I know it works in other packs like PO2

**Comment by RadGH** [comment]
Yeah can't use bowls on crucibles or pretty much any unusual water sources. I was able to get infinite water bowls from the starting water source on the gardens of glass map. Without that I don't think there is a way to get water except for waiting for rain. Seems like a pretty big oversight to me!

**Comment by Cazadorsniper** [comment]
Make a bucket.

**Comment by RadGH** [comment]
Ohhhh, I was stuck thinking that iron production was gated behind needing a tinker's smeltery. You can totally just sieve iron and smelt it in a normal furnace and then make a bucket. No clay (thus water) required!

My bad for not making that connection sooner :)
