### ISSUE TITLE
Project Ozone Server not Starting on Linux Systems

### ISSUE THREAD

**Issue by NadeoWolf** [Cazadorsniper/PO3#564]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** PO3-3.0.41.Server
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
I can't start the Server. On my local Windows it starts most of the times. BUT on my vServer i can't start it. I tried the following configs:

- Ubuntu Host, Alpine Docker Container, OpenJDK8-amd64, minecraft as new created minecraft user
- Ubuntu Host, Alpine Docker Container, OpenJDK8-amd64, minecraft as root
- Ubuntu Host, Ubuntu Docker Container, OpenJDK8-amd64, minecraft as new created minecraft user
- Ubuntu Host, Ubuntu Docker Container, OpenJDK8-amd64, minecraft as root
- Ubuntu Host, OpenJDK8-amd64, minecraft as root.
- Windows Host, OracleJDK_1.8.0_191_x64, Minecraft as Admin

Ubuntu Host = vServer, 8GB Ram (6 for Minecraft), Quadcore VCPU
Windows Host = PC, 32GB Ram (6 for Minecraft), Intel i7-8700K

Starting on Windows is the only config that is starting, but i can't start the Client at the same time.... 

FAQ: Why Docker? Because i want to keep my vServer clean.

**Steps to reproduce:**
For the Ubuntu Host with Ubuntu Docker:

1. Install Docker
2. Copy the Dockerfile + eula.txt + server.properties files in one folger
3. cd  to that Folder in Terminal
4. run `docker build --tag i_mc_ozone3_server .`
5. run `docker run -dit  -p 25565:25565 --name mc_ozone3_server i_mc_ozone3_server`
   to prevent the container from Terminating i set the Entrypoint on "bin/bash" so i need to start the Minecraft Server by hand. 
6. run `docker attach mc_ozone3_server`
7. Check permissions and ownership with `ls -la` 
8. run the Server with `java -Xms4G -Xmx6G -jar forge-2838.jar`

**Crash log (use pastebin or issue will be closed):**
latest.log https://pastebin.com/TXLaVg0R
debug.log to big for pastebin

[debug.log](https://github.com/Cazadorsniper/PO3/files/3514905/debug.log)

DockerFiles in a Zip: 
[Minecraft-Ozone3-Server-ubuntu.zip](https://github.com/Cazadorsniper/PO3/files/3515238/Minecraft-Ozone3-Server-ubuntu.zip)

**Comment by Cazadorsniper** [comment]
Maybe having problems finding the server? /srv/minecraft/./mods 
The "." before mods is what I mean.

**Comment by NadeoWolf** [comment]
/srv/minecraft/ is the root folder of the server.
. is the workingdirectory, what in that case is /srv/minecraft/

`ARG server_dir=/srv/minecraft`
`WORKDIR ${server_dir}`

that means ./mods/ is equal to /srv/minecraft/mods/

but i can try to change everything to absolute paths.

**Comment by NadeoWolf** [comment]
it doesn't work changing it to absolute paths. i installed it now outside of docker directly on my vServer with debian OS and it works. maybe a future version is able to run in a docker ;)

**Comment by Cazadorsniper** [comment]
I doubt it.
