### ISSUE TITLE
Permanent Fluxomagnet Attraction

### ISSUE THREAD

**Issue by Disarster** [Cazadorsniper/PO3#566]
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** My Fluxomagnet disappeared from my inventory and now i have Permanent Attraction, tried switching it off with another Magnet but that did nothing. I dont know if it happend because of my last crash or something else because i only noticed it a while after it.

Last crash: 
https://pastebin.com/WsywFmet

**Comment by Cazadorsniper** [comment]
The magnet has nothing to do with that crash, have you tried clicking around your inventory or checked your baubles?

**Comment by Disarster** [comment]
As it turns out im stupid and checked literally everything 10 times  except the baubles because i didnt realize it could go there. 

A bit later i got another crash that happened every time i loaded my world. It was because of the throwable dragons breath option from Quark which i disabled to get around that crash. Dont know if its helpful or not but im just gonna leave the crashlog here. 

https://pastebin.com/190gGLMj
