### ISSUE TITLE
Laser Gun Missing in Tool Station

### ISSUE THREAD

**Issue by TheWyldePython** [Cazadorsniper/PO3#567]
When I go to the Tinkers' Tool Station to make a Laser Gun, the option on the left side for the preset tool layouts isn't there. There is no image of a laser gun and no option to click one, and trying to place the parts in the "Repair and Modify" section doesn't do anything either. 
Do I need to update my modpack or anything like that? I'm currently on Minecraft 1.12.2 with PO3 3.0.41

**Comment by Noskyy** [comment]
You have to use a Tool Forge

**Comment by TheWyldePython** [comment]
Oh, I'm just dumb lol. Thanks
