### ISSUE TITLE
Server Crashing when attempting to load enderio

### ISSUE THREAD

**Issue by Kan9010** [Cazadorsniper/PO3#572]
# Use the search function before reporting to see if the issue has been reported before.
**3.0.41:**
**Multiplayer,:**

**When starting up the server fails to get past enderio, I've checked elsewhere and either been too stupid to see the issue elsewhere or it's just not anywhere else, also computer running the server has 16gb of ram and a ryzen 7:**

**Downloaded server files and attempted to run locally on two separate computers and received the same error:**

**https://pastebin.com/XM5U2LmA:**

**Comment by ByteTemplar** [comment]
In the log file, there is quite obvious error:
_Caused by: java.lang.OutOfMemoryError_

And bit down:
_Memory: 131776 bytes (0 MB) / 259522560 bytes (247 MB) up to 259522560 bytes (247 MB)_

There is something wrong in your launch script, and only allocating 256Mb to the server. Fix that and it probably will work...
