### ISSUE TITLE
Sieve can't do 8x8

### ISSUE THREAD

**Issue by nurdism** [Cazadorsniper/PO3#574]
**Pack Version:**
3.0.41

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Quest states that the sieves can do an 8x8 to sieve a stack, but only seems to be able to do 8x8
https://i.imgur.com/fpbAhqY.png

**Steps to reproduce:**
8x8 sieves, only 5x5 fill up

**Crash log (use pastebin or issue will be closed):**
n/a

**Comment by Cazadorsniper** [comment]
That is because the config was reset recently.
