### ISSUE TITLE
Game Crashing On Load

### ISSUE THREAD

**Issue by Cubicalman** [Cazadorsniper/PO3#575]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.041
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
When attempting to load into my save, it shows the loading screen, but once it loads, it shows the background of the nether and then immediately crashes.
**Steps to reproduce:**
I have not been able to replicate this issue
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/T46CRBUZ

**Comment by Cubicalman** [comment]
Is there any way i can fix my game so it doesn't constantly crash?

**Comment by Cazadorsniper** [comment]
Wait until tomorrow that is when the update is coming.
