### ISSUE TITLE
Project Ozone 3 Server Crash

### ISSUE THREAD

**Issue by TheSmilingApe** [Cazadorsniper/PO3#579]
So some Friends of mine and I are playing project Ozone 3 using the Zap-hosting server. They only added 2gb ram to the server which was kinda low and we added 2 more having 4gb ram. 
But now the server is crashing after a few minutes.
This is the Crashlog
[crash-2019-08-25_20.09.54-server.txt](https://github.com/Cazadorsniper/PO3/files/3545763/crash-2019-08-25_20.09.54-server.txt)
Can anyone please help or does anyone know why the server crashes?

**Comment by rickadead** [comment]
Pate Bin
https://pastebin.com/d7Lj6VRA

**Comment by Cazadorsniper** [comment]
Looks like the issue is from the embers furnace
