### ISSUE TITLE
J'zahar and Cha'Garoth

### ISSUE THREAD

**Issue by Souleater207** [Cazadorsniper/PO3#58]
**Pack Version:**3.3.38

**Description:** J'zahar and Cha'Garoth quest didn't complete when i killed them

**Steps to reproduce:**can't because i can't kill J'zahar again

**Crash log:**

**Comment by booblebobble** [comment]
Boss kill quests are broken atm.  There should be a ritual that resets the last castle in the necronomicon if you want to fight jzahar again.

**Comment by martinschuberteu** [comment]
There is a ritual you can perform to reset. I had to do it a few times because I didn't get the drop.

**Comment by Souleater207** [comment]
That's not really a fix I killed both of them got what I needed for the
next quest and that should be it neither of the quest completed I shouldn't
have to fight them over and over. I got the thing for the last book and
made it and that quest completed so idk
