### ISSUE TITLE
Blocks in the Nether have changed drastically. 

### ISSUE THREAD

**Issue by VoxLongstride** [Cazadorsniper/PO3#581]
![2019-08-27_16 09 45](https://user-images.githubusercontent.com/54566041/63810233-e071cb80-c8e9-11e9-9be0-8b00c6287a2f.png)

Blocks for the Nether have changed into Me Terminals, Dark Matter Furnaces, and other strange blocks. I'm assuming this has to do with ID number changes?

**Comment by ByteTemplar** [comment]
Have you done any changes to the pack for this to happen? Revert those and load a backup before that...
