### ISSUE TITLE
Server won't boot

### ISSUE THREAD

**Issue by georgen2003** [Cazadorsniper/PO3#583]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:2.0.42**
**Singleplayer, Multiplayer, or LAN?: Multiplayer**

**Description: The server won't start or this is what the client says. Server still starting **

**Steps to reproduce: I don't know**
 
**Crash log (use Pastebin or issue will be closed):https://pastebin.com/rBpec2zT**

**Comment by georgen2003** [comment]
It didn't work

**Comment by georgen2003** [comment]
Nothing changes i just get a message that the server auto-saves but i still can't join

**Comment by Cazadorsniper** [comment]
And that paste link is all that shows up?

**Comment by georgen2003** [comment]
Yes

**Comment by Cazadorsniper** [comment]
Try to redo the server
