### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by david132590** [Cazadorsniper/PO3#585]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.41
**Singleplayer, Multiplayer, or LAN?:**
LAN (by hamachi)
**Description:**
Random crashes after we build mob farm. Used only mob grinding utils and storage drawers
**Steps to reproduce:**
Restarted world. Turning off the farm solved problem, but we need mob farm!
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/XKyuKKtC

**Comment by Cazadorsniper** [comment]
update
