### ISSUE TITLE
Master Infusion Crystal consumed when crafting Creative Essence

### ISSUE THREAD

**Issue by Jyrath** [Cazadorsniper/PO3#587]
Pack Version: Singleplayer 3.0.42

Description: When crafting a Creative Essence, the Master Infusion Crystal is consumed. In previous versions of the modpack, the Master Infusion Crystal remained in the crafting grid.

Steps to reproduce: Craft a Creative Essence in the Extended Crafting Basic Crafting table.

Crash log (use pastebin or issue will be closed): None

**Comment by Cazadorsniper** [comment]
It seems the philosopher's stone is doing the same thing.

**Comment by Cazadorsniper** [comment]
Extended Crafting update changelog: Fixed container items not breaking when used in Extended Crafting Tables

**Comment by Jyrath** [comment]
Downgrading to ExtendedCrafting 1.5.4 fixes the issue, so it's definitely that latest change to ExtendedCrafting that is causing the bug.

**Comment by Cazadorsniper** [comment]
yes
