### ISSUE TITLE
Nether turning into a place with purple slime and molten gold.

### ISSUE THREAD

**Issue by AwesomeBroDude** [Cazadorsniper/PO3#589]
**Pack Version:**
3.0.42
**Singleplayer, Multiplayer, or LAN?:**

Multiplayer using hamachi so technically LAN

**Description:**

I went to the nether after exploring VoidCraft and my nether terrain changed drastically

**Steps to reproduce:**

Not really sure if void craft caused it just looking for an answer. I went to the void from VoidCraft, came back to the overworld and then to the nether.

I also understand there is a Reset Nether button on the single player screen. I would like to know why this button is there and if this is the reason why.

**Crash log (use pastebin or issue will be closed):**

No crash
![2019-08-29_20 16 59](https://user-images.githubusercontent.com/53064129/63986692-b14e8c00-ca9a-11e9-828a-dace5abd3fa7.png)

**Comment by RealTrueDeviL** [comment]
I think it;s the mod Nether EX, which was updated & changed name..

Similar issue, 1st time going to nether after update..

https://youtu.be/3PBS3vhBnhQ

**Comment by Cazadorsniper** [comment]
On the world select screen there is a reset nether button at the top.
