### ISSUE TITLE
Reinforced Blast Brick quest only requires 9

### ISSUE THREAD

**Issue by gsmith2885** [Cazadorsniper/PO3#590]
Pack Version: 3.0.42
Singleplayer

Description: In the quest book only 9 reinforced blast bricks are required to be made to complete the quest. However, it takes 27 of them to make the multiblock.

Steps to reproduce: Open the quest book.

Crash log (use pastebin or issue will be closed): None required.

**Comment by Cazadorsniper** [comment]
9 crafts
