### ISSUE TITLE
Evolved Enderman make server crash by tick or block collision

### ISSUE THREAD

**Issue by Arno989** [Cazadorsniper/PO3#591]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.41
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**  
Whenever an Evolved Endermans spwans in my mob farm and hits the spikes down below the server crashes, this happened with stone spikes and the mobgrindingutils spikes, then recently with no spikes on the server it crashed again because of a tick.

**Steps to reproduce:**  Create mob spawner, when evolved enderman spawns and hits spikes or gets ticked the server crashes by NullPointerException

**Crash log (use pastebin or issue will be closed):**  
Block collision crash: https://pastebin.com/vJiUmG7Q
Tick entity crash: https://pastebin.com/2x4ctJEv

**Comment by ByteTemplar** [comment]
This was known issue in version .41
https://github.com/Cazadorsniper/PO3/issues/469

Update to new .42 to fix the problem.
