### ISSUE TITLE
Game crash when leaving void

### ISSUE THREAD

**Issue by Affe36963** [Cazadorsniper/PO3#593]
Pack Version: 3.0.42
Singleplayer

Description: Game crash when leaving void

Steps to reproduce: Entering void and then leaving void

Crash log https://pastebin.com/xLC1XWQv

**Comment by Cazadorsniper** [comment]
I fixed this is 3.0.42.

**Comment by Affe36963** [comment]
I play on 3.0.42 or what do you mean?

**Comment by Cazadorsniper** [comment]
at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:150)
    at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)

This issue happens when the p455w0rd's lib config has the shader stuff on.

**Comment by Affe36963** [comment]
ok I have disabled that and it seams to be working. thank you 😃
