### ISSUE TITLE
Purple Slime/Molten Gold overflow nether

### ISSUE THREAD

**Issue by kmgooey** [Cazadorsniper/PO3#594]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.0.42
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Updated to the latest version and went into the nether. A huge number of blocks were converted into liquid purple slime and molten gold which fell from the ceiling, walls, and floors. It seems to only have happened in a 5x5 chunk area around the nether portal. You have to swim through the slime and avoid molten gold until you get out of the affected area.
**Steps to reproduce:**
After update, the nether is in a constant state of purple slime.

**Crash log (use pastebin or issue will be closed):**
None

**Comment by ByteTemplar** [comment]
You need to reset the Nether:
https://github.com/Cazadorsniper/PO3/issues/589
