### ISSUE TITLE
iron hammer duplication glitch and during xia fight chickenchunks makes the pack crash

### ISSUE THREAD

**Issue by Saturnion83** [Cazadorsniper/PO3#595]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*latest*
**Singleplayer, Multiplayer, or LAN?:*singleplayer*

**Description:*iron hammer duplication glitch and during xia fight chickenchunks makes the pack crash (unfortunately i don't have a crash report for the xia fight but i saw on internet lots of people are reporting it)*

**Steps to reproduce:*combine 2 iron hammers from "magneticraft" in the crafting grid (like when you try to combine 2 broken swords) and you will get a new repaired iron hammer+ the 2 before iron hammers (it seems like they are acting like buckets in cake recipe)*
https://www.youtube.com/watch?v=rTs9-RB4Tl8&feature=youtu.be
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I'm aware of the chicken chunk issue which is why the Xia fight isn't required.
I'm also aware of the hammer duplication.

**Comment by Saturnion83** [comment]
ok thx for the respond, btw can i ask why did you remove the /dank/null  mod :c

**Comment by Cazadorsniper** [comment]
It was broken
