### ISSUE TITLE
Recipes not loading

### ISSUE THREAD

**Issue by FIRExSCOUT** [Cazadorsniper/PO3#597]
**Pack Version:**
PO3-3.0.42

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
I cant craft some items. I see that in the server console it says unknown recipe and i don't know how to fix it. I tried to do some research to no avail.

**Steps to reproduce:**
Launch server on my computer

**Crash log (use pastebin or issue will be closed):**
No crash but here is the server log
https://pastebin.com/t6S8zTHN
https://pastebin.com/XMrVxLks

**Comment by Cazadorsniper** [comment]
What recipes?

**Comment by FIRExSCOUT** [comment]
i try to make armor but it it doesnt show up in the output. if i look at the recipe helper it only shows complete armor pieces combined with im guessing mods to make an upgraded version

**Comment by FIRExSCOUT** [comment]
i can provide screenshots if needed

**Comment by Cazadorsniper** [comment]
Please provide screen shots

**Comment by FIRExSCOUT** [comment]
![00726381ee04528ed2a9b141880431c4](https://user-images.githubusercontent.com/54760510/64088484-eb1fcc80-ccfe-11e9-8198-0f59f5fbf447.png)
![eed5bfdde146655cbe6cf4fd2cfbc545](https://user-images.githubusercontent.com/54760510/64088485-eb1fcc80-ccfe-11e9-8762-654a79230488.png)
![7bb8b7c48908bea036a82d716009e42d](https://user-images.githubusercontent.com/54760510/64088486-eb1fcc80-ccfe-11e9-8e1e-0792f3c9086d.png)
![3ce2c8b2fe9bf1c3be2de317c396b2cb](https://user-images.githubusercontent.com/54760510/64088487-eb1fcc80-ccfe-11e9-8219-e3b52a37be16.png)

**Comment by Cazadorsniper** [comment]
You must make the armors through the armor+ workbenches.

**Comment by FIRExSCOUT** [comment]
I am trying on the armorplus workbench as well but nothing happens. I even tried changing the gamemod of armorplus in the config for easier recipes but nothing. I can't make basic vanilla armor or the armorplus armor.

**Comment by FIRExSCOUT** [comment]
I tried it in singleplayer as well and it doesn't work there either.

**Comment by Cazadorsniper** [comment]
Have you looked through what you need to make the armor?

**Comment by FIRExSCOUT** [comment]
ive tried using jei for the crafting recipes and i went through mod showcases to find them, jei doesnt give me anything it was just like the above screenshot. when i put in the materials there is no output.

**Comment by Cazadorsniper** [comment]
Start from leather armor then work your way up to iron armor. PO3 has an armor progression.

**Comment by FIRExSCOUT** [comment]
makes sense to me, im pretty sure that was my problem i could make the leather armor just need to progress. thank you, i couldnt find any info on that anywhere else. i guess i just didnt understand the mod.
