### ISSUE TITLE
buckets lost with zenith furnace

### ISSUE THREAD

**Issue by gsmith2885** [Cazadorsniper/PO3#599]
Pack Version:3.0.42
Singleplayer, Multiplayer, or LAN?: Single(maybe others also)

Description: When holding a stack of lava buckets and clicking on the zenith furnace to fill it the furnace receives 1 bucket of lava and consumes all but 1 of your buckets. I assume this is due to normally not being able to stack buckets and so the furnace is deleting what you give it and giving you 1 empty bucket back.

Steps to reproduce: click a zenith(maybe other tiers) furnace that has a liquid furnace upgrade with a stack of lava buckets.

Crash log (use pastebin or issue will be closed): No crash

**Comment by Cazadorsniper** [comment]
Because mods doesn't expect the lava/water buckets to be stacked when clicking on tileentities so that is the result (you losing 63 buckets).

**Comment by Cazadorsniper** [comment]
Only 1 way to fix this, and that is to remove the ability to stack them.

**Comment by gsmith2885** [comment]
For me personally, I would rather keep the stacked buckets but maybe put a warning in the quest book With either the furnaces or the part with the upgrades so at least most people will read it.

**Comment by gsmith2885** [comment]
I was just going to post the issue with the mod author for the furnaces but I see that is you also. Is it possible to add a check for the number of buckets, decrement that number by 1 then return the new number plus 1 empty bucket? This would be more of a mod compatibility update than I bug.

**Comment by Cazadorsniper** [comment]
I could but what of other mods that do the same thing as the furnaces, although I stopped working on the mod.
