### ISSUE TITLE
Anti Barrel Crashes server

### ISSUE THREAD

**Issue by Cazitron** [Cazadorsniper/PO3#6]
I'm on the current build which can be found on twitch, and we had an anti-barrel collecting items from a chunk loaded mob farm, an absorption hopper picked up the items and managed to put more items in the barrel than there was allocated memory. Now the server is impossible to log into without rolling back or deleting the anti-barrel via MC Edit. Please fix this issue for the next twitch release, much appreciated.

-Cazitron

**Comment by Cazadorsniper** [comment]
It will be fixed by removing the antibarrel itself.
