### ISSUE TITLE
infinite meef stroganoff

### ISSUE THREAD

**Issue by Saturnion83** [Cazadorsniper/PO3#601]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*latest*
**Singleplayer, Multiplayer, or LAN?:*singleplayer*

**Description:*you can eat infinite times the meef stroganoff from twilight forest*

**Steps to reproduce:*just eat it*

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Yeah, not an issue.

**Comment by Flassie** [comment]
Same problem.
How to access hydra if it is not consumable?
