### ISSUE TITLE
PO3 3.0.42 freezing / crash during loading

### ISSUE THREAD

**Issue by FirefighterKyle** [Cazadorsniper/PO3#604]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.0.42
**Singleplayer, Multiplayer, or LAN?:** Singleplayer 

**Description:** When 0.42 first came out everything worked great played for at least 6 hours one day and another day played a good 4, took 4 days off cause of work and now it loads very slow definitely at 3/7 then at 6/7 it freezes and I can't get it to come back. Not sure since my java updated 9/3/19 where that is giving it issues or not but I am unsure where to look on why it's taking 31 minutes to load when I was loading it between 5-6 minutes. (Also I am using 7 GB of ram)

**Steps to reproduce:** loading screen

**Crash log (use pastebin or issue will be closed):**(File log no crash report since it freezes and I force close it) https://pastebin.com/BhrKPCYz
Where it keeps getting frozen at http://prntscr.com/p208r9

**Comment by ByteTemplar** [comment]
Well, 5th line tells immediately, that you are using old Java version to run Minecraft (version 1.8.0_51). Twitch uses it as default.

Are you using high resolution texture pack? Try disabling it.

**Comment by FirefighterKyle** [comment]
So if twitch uses that version how do I make it so twitch uses the latest? Because Java says it is up to date when I look at it? Sorry kind of noobish for Java stuff. Also nothing for high resolution texture packs unless PO3 has it by default but it doesn't seem like it did.

**Comment by ByteTemplar** [comment]
I don't use that bloatware, but this should help:
https://help.twitch.tv/s/article/How-to-Play-Minecraft-with-Twitch-App?language=en_US#Settings

What Ive read, I think you need to change the Launch method so you can choose your own Java from drop down menu, hope you find it...

**Comment by FirefighterKyle** [comment]
Hmm I will try and mess with it more and see what I can do to fix it. Seems like even with changing the twitch settings it doesn't change it. Thanks anyways all
