### ISSUE TITLE
Crashes Client - Server lags but stays up

### ISSUE THREAD

**Issue by jw890890** [Cazadorsniper/PO3#605]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
Multiplayer

**Description:**
Minecraft client side crashes. It appears to crash only when entering a particular part of the map? Java throws a java.lang.NullPointerException: Unexpected error.

I believe the bug could be due to a block that has been placed that is "bugged"

How would I go about fixing this.

Appreciate any help!

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
[crash-2019-09-05_17.43.37-client.txt](https://github.com/Cazadorsniper/PO3/files/3577618/crash-2019-09-05_17.43.37-client.txt)

**Comment by ByteTemplar** [comment]
Just by comparing the mod versions, its obvious you are using at least 2 versions older than current one, why not just list it.

I would recommend updating the pack to newest version first, make backups etc... ofc as usual before. Especially, cause you are going up multiple versions.
