### ISSUE TITLE
Abyssalcraft Transmutator Fuel – Quest book inconsistency

### ISSUE THREAD

**Issue by twsx** [Cazadorsniper/PO3#606]
**Pack Version:**
.42

**Singleplayer, Multiplayer, or LAN?:** 
Single player

**Description:**
Quest "Omicron > Transmutator" states that the Transmutator wants a bucket of Liquid Coralium as fuel.
Liquid Coralium Bucket isn't a registered fuel for the machine however, and doesn't work. 
The Transmutator DOES however accept Blaze Rods and even Blaze Powder as fuel, which seems a little too easy.

HTH

**Comment by Cazadorsniper** [comment]
Its not entirely wrong really. I removed the bucket part but it can use liquid coralium.

**Comment by twsx** [comment]
Oh, okay. But how do you get it in there? Doesn't seem to accept any piping?
