### ISSUE TITLE
Breaking the placeable crafting grid with an ex nihilo creatio hammer gives 4 crushed netherrack

### ISSUE THREAD

**Issue by Xynain** [Cazadorsniper/PO3#607]
Version: 3.0.42
Singleplayer

If the crafting grid that is placed on a block (button "c" by default) and broken (left-clicked) by an ex nihilo creatio hammer, 4 ex nihilo creatio crushed netherrack are dropped. This works with all iterations of the hammer.

**Comment by Cazadorsniper** [comment]
Nothing I can do about this.
