### ISSUE TITLE
unlock item

### ISSUE THREAD

**Issue by Wip-Sama** [Cazadorsniper/PO3#608]
please unlock arcane transmutation from projectex, like an end game item

**Comment by Cazadorsniper** [comment]
arcane transmutation?

**Comment by Wip-Sama** [comment]
![image](https://user-images.githubusercontent.com/47224042/64531277-5d9c3800-d30f-11e9-8e2b-87e8535191d5.png)
that

**Comment by Cazadorsniper** [comment]
Likely won't happen.
