### ISSUE TITLE
NetherEx crash

### ISSUE THREAD

**Issue by deepfoundLava** [Cazadorsniper/PO3#610]
Pack Version:

3.0.42

Singleplayer, Multiplayer, or LAN?:

Singleplayer

Description:

After starting PO3 from launcher, crashes while loading, report says it is netherEx related

Steps to reproduce:

Load up PO3, crash after a while

Crash log: https://pastebin.com/7Y08irgr

**Comment by deepfoundLava** [comment]
added template and link

**Comment by Cazadorsniper** [comment]
Try removing the added mods then load the pack again.

**Comment by deepfoundLava** [comment]
Resolved thanks
