### ISSUE TITLE
World crashing. Wont load at all

### ISSUE THREAD

**Issue by AwesomeBroDude** [Cazadorsniper/PO3#611]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**

3.0.42

**Singleplayer, Multiplayer, or LAN?:**

Technically multiplayer with hamachi. LAN

**Description:**

World wont load. Just gives me a crash report

In the crash report I see a lot about the Electric Furnace (From Galacticraft core I believe)

**Steps to reproduce:**

Load up PO3. Load up the world. You dont get to see terrain before it crashes.

**Crash log (use pastebin or issue will be closed):**

https://pastebin.com/xJUvBuWT

**Comment by Cazadorsniper** [comment]
Use World Edit to remove that block or remove the tileentity with the forge config.

**Comment by AwesomeBroDude** [comment]
Is there a more detailed way on understanding how to mess with config files an what not. Maybe you can point me in the right direction?

**Comment by Cazadorsniper** [comment]
Line 61 in the forge.cfg

**Comment by ByteTemplar** [comment]
If you do this, **make sure you have backups first!** And after changing that config setting, run the game and if the world loads, then shutdown and change the config setting BACK to its original value! Otherwise this might have bad effects in future...

Now, start the game and see if everything is OK and hope for the best :)

**Comment by AwesomeBroDude** [comment]
Thank you both! This did work but when changing it back it goes back to how it was. Is this a change that can be a permanent one?

**Comment by ByteTemplar** [comment]
Are you sure the game is properly shutdown, when you changing it back? It should not revert the config files, unless game is running and you try to edit it...

**Comment by AwesomeBroDude** [comment]
I am properly shutting the game down. I'm editing the .cfg file and hitting save. I reopen the game and join the single player world and I get the same crash report. However with the value on true I am able to join the world and play like normal. In the crash report it says a lot about an Electric Furnace that I have, maybe I just have to change the cfg, get rid of the furnace, and then change the cfg back and see if it loads?

**Comment by Cazadorsniper** [comment]
Yes, do that.
