### ISSUE TITLE
Auto-Sifter doesn't work

### ISSUE THREAD

**Issue by Azure08** [Cazadorsniper/PO3#612]
Pack Version: 3.0.42
Single Player

Description: When I place a Sieve above an Auto Sifter, nothing happens. Isn't the Auto Sifter supposed to connect to the Sieve? 

Image: https://imgur.com/IhOtUcL

Steps to reproduce: Place a Sieve above an Auto Sifter

**Comment by Cazadorsniper** [comment]
does it have a mesh in it? And have you tried placing the auto sifter back down?

**Comment by Azure08** [comment]
Yes, it have a mesh.

**Comment by Cazadorsniper** [comment]
And the second question?

**Comment by Azure08** [comment]
Oh, sorry. English is not my first language, i didn't understand it.

**Comment by Cazadorsniper** [comment]
Pick up the auto sifter then place it back down.

**Comment by Azure08** [comment]
I already did it

**Comment by Cazadorsniper** [comment]
have you tried rebuilding the whole thing? Don't understand why it wouldn't work.

**Comment by gsmith2885** [comment]
Are the water wheels moving?
I don't know if it matters but it looks like you have a block in the path of the wheel.

**Comment by udooles** [comment]
Not sure if you figured it out but your axels appear to be backwards.  Build the axels and wheels from the shifter out.
