### ISSUE TITLE
Extra Planets, Tier 10, Electric Launchpad not craftable

### ISSUE THREAD

**Issue by twsx** [Cazadorsniper/PO3#614]
**Pack Version:**
.42

**Singleplayer, Multiplayer, or LAN?:** 
Single player

**Description:**
The "Powered Rocket Launch Pad" which is needed for the Electric Tier 10 Rocket currently requires the mod's own Platinum Ingots, which can't be crafted in any way.

A similar (though solvable) issue exists with Tungsten; You need the mod's own ingots to craft the Ultimate Machines (Ultimate Oxygen Compressor etc.) and the only way to get them is to smelt LandCore Tungsten (e.g. in Smeltery, or NuclearCraft's Melter) and use a NuclearCraft Ingot Former to turn it into the Extra Planets ingot.

HTH

**Comment by AyeItsKatieMC** [comment]
Or you can use the Forge Lexicon provided by Thermal Expansion to convert into any ore dictionaried Tungesten Ingot

**Comment by BuggaNoia** [comment]
Pack Version: 3.3.61/Kappa

(Still the) same issue with the Tungsten Singularity: Need the Extra Planets variation, but ores/chunks give the MagneticCraft one, what the Factorizer also turns into MagneticCraft blocks. (As @AyeItsKatieMC mentioned: Forge Lexicon can solve this.)
