### ISSUE TITLE
Marble bricks for astral sorcery not craftable

### ISSUE THREAD

**Issue by XLgaminginc** [Cazadorsniper/PO3#615]
**Pack Version:** 3.0.42

**Singleplayer, Multiplayer, or LAN?:**
Single player

**Description:**
There are two different types of marble in this pack, one of which is astral sorcery marble. For crafting recipies and the like, these two are treated as one and the same. In order for the starlight infusing buildings you need to use the astral sorcery marble bricks. Crafting these overlaps with another crafting recipe, resulting in the wrong item being produced and starlight infusion being impossible.

**Steps to reproduce:**
-Put four astral sorcery marble in a crafting table
-Expected result: astral sorcery marble bricks
-Actual result: marble bricks of another mod

**Crash log (use pastebin or issue will be closed):**
no crash

**Comment by ByteTemplar** [comment]
Use chisel to change the blocks...

**Comment by XLgaminginc** [comment]
That is indeed the solution, thanks for replying
