### ISSUE TITLE
Can't farm mobs

### ISSUE THREAD

**Issue by SteveNoobGeek** [Cazadorsniper/PO3#617]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.0.42
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** I can't clear the quest "Mob Farming", which is required for all the other quests, because mobs don't spawn in Garden Of Glass and I can't take the Hunting Dimension because I need arrows, and to do so I need feather and to do I need a chicken or an egg, which I don't find any recipe available

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
1. Mobs do spawn in Garden of Glass
2. Look at all the possible recipes to make arrows

**Comment by SteveNoobGeek** [comment]
Thanks but I think you should indicate that because the recipe of the leaf Fetching is not written in the book and not implemented in JEI with Tinkers.
