### ISSUE TITLE
Seeds missing in quest book.

### ISSUE THREAD

**Issue by gsmith2885** [Cazadorsniper/PO3#618]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.0.42
**Singleplayer, Multiplayer, or LAN?: all

**Description: Magnesium and HOP graphite seeds are not in the quest book. This may be intentional and is not having any effect on the game.

**Steps to reproduce: Open the quest book

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I'm pretty sure HOP graphite seeds are there.

**Comment by gsmith2885** [comment]
I went through 1 by 1 and they are both not in the quest book. But like I said it doesn't have any effect on the gameplay. You can still make them and use them just no quest reward.
