### ISSUE TITLE
Can't craft Transmutator (Abyssalcraft)

### ISSUE THREAD

**Issue by Emax220x** [Cazadorsniper/PO3#62]
**Pack Version:**
3.0.35
**Description:**
Wrong bucket required in the recipe, can't craft the required bucket and can't find it in lootbag (opened more than 2k bags)
![image](https://user-images.githubusercontent.com/31655629/53682575-62948500-3cf7-11e9-9536-99e9395a1431.png)

**Steps to reproduce:**

**Crash log:**

**Comment by Emax220x** [comment]
Found the issue, is a JEI issue, the correct recipe is with a liquid coralium bucket.
![image](https://user-images.githubusercontent.com/31655629/53682726-b6ec3480-3cf8-11e9-90b1-1e7fc15faa50.png)

**Comment by DangerHSW** [comment]
Update to the newest version this is already fixed
