### ISSUE TITLE
https://pastebin.com/s7eHnEML

### ISSUE THREAD

**Issue by Cubicalman** [Cazadorsniper/PO3#622]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.0.42
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
When trying to load into my save file, My character model and hotbar appear, but immediately freeze and crash.
**Steps to reproduce:**
Unknown
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/s7eHnEML

**Comment by Cazadorsniper** [comment]
https://www.reddit.com/r/Minecraft/comments/835uz4/help_with_modded_client_crash/
