### ISSUE TITLE
Crash on selecting Wireless Crafting Terminal (any)

### ISSUE THREAD

**Issue by Aschevogel** [Cazadorsniper/PO3#623]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.0.42**
**Singleplayer, Multiplayer, or LAN?: Multiplayer (own server though)**

**Description: Whenever I craft or spawn in any wireless crafting terminal and then select it in the hotbar, the game instantly crashes out. This does not happen, when using a non crafting wireless terminal. I can normally upgrade the Wireless universal terminal until the "crafting" portion**

**Steps to reproduce: See above. Craft wireless crafting terminal, scroll to it or just hotkey it and game crashes out**

**Crash log (use pastebin or issue will be closed):
https://pastebin.com/9mM7H73d
https://pastebin.com/XP16Sgi3
https://pastebin.com/9PhCBm7Y (Here I spawned in a "Wireless Ultimate Terminal" after Spawning in a AE2 Wireless Terminal and using that without a problem)
https://pastebin.com/55UD1Zcx (Server Console Output for above crash)
**
As always, thank you for your time

**Comment by Cazadorsniper** [comment]
Turn off the simply jetpack item charging ability then try it.

**Comment by Cazadorsniper** [comment]
This has been reported to the simply Jetpacks dev already: https://github.com/Tomson124/SimplyJetpacks-2/issues/143

**Comment by Aschevogel** [comment]
Yep, that seems to be it, thanks a ton for the quick answer and excuse my poor google skills

**Comment by Aschevogel** [comment]
Addendum: After turning that off, game now crashes reliably when loading back into the overworld from the hunting dimension (with and without the crafting terminal in the inventory)

https://pastebin.com/gZxrRefE (with)
https://pastebin.com/tP0GkA7S (without)

Too my untrained eye. it does not look related, but better safe than sorry, maybe it helps

**Comment by Cazadorsniper** [comment]
In the p455w0rd's library config turn off anything having to do with lighting and shaders.

**Comment by Aschevogel** [comment]
Just found that, thats why I deleted, thanks
