### ISSUE TITLE
Infinite Industrial Hemp with bone meal on mature half height crop

### ISSUE THREAD

**Issue by sixlettervariables** [Cazadorsniper/PO3#624]
**Pack Version:** 3.0.42
**Singleplayer, Multiplayer, or LAN?:** LAN

**Description:**
While spreading my industrial hemp farm I noticed that bone-mealing half height industrial hemp plants did not use up a bone meal.

**Steps to reproduce:**
1. Plant industrial hemp
2. Bone meal to full height
3. Knock off top half
4. Bone meal bottom half

![image](https://user-images.githubusercontent.com/8238690/65096231-38a06880-d992-11e9-9fcf-7a088c600dd9.png)

![image](https://user-images.githubusercontent.com/8238690/65096252-540b7380-d992-11e9-8269-70da5762b25a.png)
Note bone meal count stays at 21.

**Comment by Cazadorsniper** [comment]
How come you're not using crop sticks?

**Comment by sixlettervariables** [comment]
I did not consider that hemp may be compatible with crop sticks.
