### ISSUE TITLE
Explosion Sound

### ISSUE THREAD

**Issue by pauloelr** [Cazadorsniper/PO3#625]
**Pack Version:** Lan
**Singleplayer, Multiplayer, or LAN?:**

**Description:** I started to Play PO3 and i noticed that when I go into zone with a few mobs i can hear explosions sounds, like a creeper exploding, but no without creepers, and it is just the sound, nothing really breaks, but after a while playing I noticed that everytime this happens there is a Mob that fly of the ground with a few particles, It is becoming really annoying, is this a bug? or is something expected? is there a way to change it?

**Steps to reproduce:** Just go to a place where there is mobd

**Crash log (use pastebin or issue will be closed):** It is not a crash

**Comment by Cazadorsniper** [comment]
What pack version?
Can you identify the mobs that fly off the ground?
Are you using sometime of tinkers weapon, if so what materials does it use?

**Comment by daddy77gaming** [comment]
Hail Hydra (from tinkers tools kelline for example) does cause that

**Comment by pauloelr** [comment]
It was exactly that, sorry for bother, closing
