### ISSUE TITLE
Infusion crystal recipe doesn't work

### ISSUE THREAD

**Issue by puffinmasta** [Cazadorsniper/PO3#627]
https://i.imgur.com/rTFcYiI.png

There's the recipie on my client

https://i.imgur.com/5V3ZslS.png

That's me trying to craft it. 

It works if you use a fresh supremium infusion crystal. It only uses one charge to do so, and after that charge is used it no longer works.

**Comment by puffinmasta** [comment]
It works if you use a fresh supremium infusion crystal. It only uses one charge to do so, and after that charge is used it no longer works.

**Comment by ApolloRR** [comment]
I had this issue too with the new pack.
Make sure you go to the pack modes config file "PO3\config\packmode.cfg" then change  the pack mode back to "S:packMode=normal" from "S:packMode=kappa". (Server and client)

For some reason the server pack mode ships with it set to kappa... but the client with normal.

**Comment by Cazadorsniper** [comment]
I can't fixed this issue sadly.
