### ISSUE TITLE
Placeholder quests problem (Ghast Gueen and Rime Crystals)

### ISSUE THREAD

**Issue by itsAqua** [Cazadorsniper/PO3#629]
Pack Version: PO3 3.0.42
Singleplayer (superflat world (preset: 1 bedrock layer, 50 stone layer) mode: Creative, Cheats: on)

The Ghast Gueen quest and the rime crystals in the Epeolatry V reward quest are still set to place holder meaning they cannot be completed. Also meaning the end of the normal quest in the Omega tab cannot be completed.

![queen ghast](https://user-images.githubusercontent.com/55614897/65369105-13b02d80-dbfe-11e9-994e-2277b7927389.JPG)

![rime crystal](https://user-images.githubusercontent.com/55614897/65369106-1743b480-dbfe-11e9-81aa-83973d8d7aab.JPG)

**Comment by Cazadorsniper** [comment]
Already fixed this.
