### ISSUE TITLE
Hardened Leather Armor, Ender Armor and Lapis Armor aren't part of upgrade Crafting

### ISSUE THREAD

**Issue by ToMe25** [Cazadorsniper/PO3#63]
**Pack Version:**
3.0.38

**Description:**
The Pam's Harvestcraft Hardened Leather Armor is not used for other Armor and is not crafted out of another Armor.

**Steps to reproduce:**
Open Inventory,
Search for Hardened Leather,
Click on any Part of the Armor,
See default Recipe

**Crash log:**
Not a Crash

**Comment by Zapstur** [comment]
Uh... How is that a problem?  If you are trying to make a suggestion, maybe actually suggest something?

**Comment by ToMe25** [comment]
It is the only Armor i know about that isn't in the upgrade crafting and as i sometimes had problems with CraftTweaker being unable to change Mod Crafting Recipes i reported it as Bug.
I am not sure if that is a Bug but i think it is some kind of a Bug.
If not someone from the Modpack Team can tell me that than i will close this Issue.

**Comment by ToMe25** [comment]
The EnderIO Armor also isn't Part of the Upgrade crafting but i think that might be intended.
