### ISSUE TITLE
Nether Amethyst Ore affected by Fortune (Dupe)

### ISSUE THREAD

**Issue by Sebaz2000** [Cazadorsniper/PO3#631]
**Pack Version:3.0.42
**Singleplayer, Multiplayer, or LAN?:Multiplayer

**Description:If you place down nether amethyst ore and mine it it will drop more nether amethyst ore, essentially being an endless dupe.

**Steps to reproduce: Fortune enchanted pickaxe, place and mine nether amethyst ore, You'll get more ore blocks than you started with. It also gives xp.

**Crash log (use pastebin or issue will be closed): N/A

**Comment by Cazadorsniper** [comment]
I think this has been fixed in today's update, make a new issue if it hasn't.
