### ISSUE TITLE
PO3-3.1.43 Server Pack Unavailable for download

### ISSUE THREAD

**Issue by rgbalex** [Cazadorsniper/PO3#632]
Hi,
Have been using pack with server for friends
Many have updated their clients yet I cannot yet find the server release for this version and am hesitant to make one myself before I cause issues for clients!
Kind regards, 
  Alex

**Comment by Cazadorsniper** [comment]
As soon as curse approves it. It was uploaded at the same time of the client version. Also this is for pack issues. This question could easily be asked on some forum.
