### ISSUE TITLE
Engineer's Hammer quest Hammah! not completing in titan mode

### ISSUE THREAD

**Issue by udooles** [Cazadorsniper/PO3#633]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.1.43
**Singleplayer, Multiplayer, or LAN?: Singleplayer

**Description: The quest Hammah! doesn't recognize crafting the Engineer's Hammer in Titan mode.

**Steps to reproduce: Try and complete quest Hammah! by crafting a Engineer's hammer while in Titan Mode.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Wait for it to complete, that quest works fine.

**Comment by udooles** [comment]
I tried it on a new world and it completed this time without issue.  Not sure what happened last time.

Sorry for the false report.

**Comment by Cazadorsniper** [comment]
Not really false report, its just that BQ is sometimes slow.
