### ISSUE TITLE
Titan Mode Missing Recipes

### ISSUE THREAD

**Issue by hubblebubble17** [Cazadorsniper/PO3#635]
**Pack Version: 
 
   3.1.43 Titan Mode

**Singleplayer, Multiplayer, or LAN?: 

    singleplayer

**Description:

     after i updated the mod pack i changed the pack mode to titan before opening minecraft and 
     then i opened it and i started a new world. the first thing i noticed is that there is no recipe to 
     get planks from logs but i thought it was my fault i didn't know how, but then i wanted to 
     make drawer upgrades and the recipes wont show up on JEI. i also thought this was my fault 
     so i deleted the pack and reinstalled it to see if this fixes it but the problem persisted.
     i also tried to make the Metallurgic Infuser but the recipe doesn't make sense but again this 
     could be my fault  (maybe i didn't look into it more).
     the game is not crashing so there is no crash log.
     i am using the twitch launcher.

**Steps to reproduce: 

     just click on the drawer upgrades in JEI to view the recipe (the diamond or the emerald ones 
     because there is no problem with the first 2 drawer upgrades)
     also look at the Metallurgic Infuser recipe it just looks weird.
     there might be more recipes which don't work/show up but those were the ones i noticed.

**Crash log (use pastebin or issue will be closed): 

    no crash log as the game didn't crash.

**Comment by Cazadorsniper** [comment]
try 3.1.44

**Comment by hubblebubble17** [comment]
i just tried 3.1.44 and the issue is still there.

**Comment by hubblebubble17** [comment]
any suggestion?

**Comment by Cazadorsniper** [comment]
All I can say is try reinstalling it, maybe its not downloading completely.

**Comment by hubblebubble17** [comment]
ok thanks man...
by the way... love this pack...
thank you for your hard work and i'll try reinstalling it again.
