### ISSUE TITLE
wireles crafting terminal crashes 

### ISSUE THREAD

**Issue by AlexByMas** [Cazadorsniper/PO3#636]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:PO3 A New Way Forward**
**Singleplayer**

**Description: Wireles crafting terminal crashes the game, it`s impossible to play because when you open it 1 time the next time to open something crashes 
either the inventory or a furnace**

**Steps to reproduce: when you open it 1 time the next time to open something crashes 
either the inventory or a furnace **

**Crash log (use pastebin or issue will be closed):
-
[crash-2019-09-22_20.15.40-client.txt](https://github.com/Cazadorsniper/PO3/files/3644228/crash-2019-09-22_20.15.40-client.txt)
[crash-2019-09-21_21.54.10-client.txt](https://github.com/Cazadorsniper/PO3/files/3644230/crash-2019-09-21_21.54.10-client.txt)

**

**Comment by number65259** [comment]
This is the Wireless Universal Terminal crash. Don't use extracells terminals - they crash when trying to render in the bauble slot. To fix your char, download NBT explorer, browse to the bauble slot containing the terminal, and delete the tag. If you want a universal terminal, install the missing pieces from p455w0rd's series. [Fluid](https://www.curseforge.com/minecraft/mc-mods/wireless-fluid-terminal), [Interface](https://www.curseforge.com/minecraft/mc-mods/wireless-interface-terminal), [Pattern](https://www.curseforge.com/minecraft/mc-mods/wireless-pattern-terminal). These can then be combined into a working universal terminal.
