### ISSUE TITLE
Titan Mode: Furnace Doesn't Craft (Quest: Riteclicking)

### ISSUE THREAD

**Issue by Targren** [Cazadorsniper/PO3#638]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.44 Server
**Singleplayer, Multiplayer, or LAN?:**  MP

**Description:** JEI shows the usual square of 8 cobble recipe, but putting those cobble into a crafting table or crafting station doesn't let me craft the furnace. I tried clicking on the empty spot in case it just wasn't rendering the result, but no dice. 

Screenshots: https://imgur.com/a/tTc19E2

**Steps to reproduce:** 
1. Run Server in Titan Mode
2. Put furnace recipe in crafting interface. 

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Is the server on titan mode?

**Comment by Targren** [comment]
Yes.

**Comment by Cazadorsniper** [comment]
how about the client?

**Comment by Targren** [comment]
Yep, I was just testing that. Dumbass attack on my end. It really helps to set it on both sides.
