### ISSUE TITLE
Titan Mode: Can't Craft Stone Crook

### ISSUE THREAD

**Issue by Targren** [Cazadorsniper/PO3#639]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.44 Server
**Singleplayer, Multiplayer, or LAN?:** MP

**Description:**

The stone crook recipe (4 stone pebbles in the crook shape) returns cobblestone instead, because the pebbles->cobblestone recipe is unshaped. 

**Steps to reproduce:**
1. Run In Titan Mode
2. Lay out pebbles in crook recipe shape, results in cobblestone.

**Comment by Cazadorsniper** [comment]
make a tinkers crook.
