### ISSUE TITLE
HONEST QUESTION:  How to obtain AgriCraft Potato Seeds?

### ISSUE THREAD

**Issue by Zapstur** [Cazadorsniper/PO3#64]
I set up a farm to try and get them from grass drops (by using bonemeal and old-fashioned redstone, as well as the mechanic that causes grass to break when the block beneath it is moved), but they just aren't dropping, even after using over 60 stacks of bonemeal.  Am I just extremely unlucky, or was that part of the AgriCraft mod changed?  If so, I need to figure out another way to get them.

**Comment by Zapstur** [comment]
Another thing to note, is that they can't be crafted, at least according to JEI.

**Comment by Zapstur** [comment]
Nevermind.  Figured it out.  Turns out you have to get a potato by killing a Zombie (not an easy task since what little zombies you get in Garden of Glass are usually killed by the Abyssal variant, or burn in the sun.  Once you get that crucial potato, plant it on AgriCraft's crop sticks, then break it to get the seeds.

**Comment by iagainey** [comment]
Side note: Sieve Dirt in a String Mesh, this will produce an array of seeds. Look in-game helper for more details.
