### ISSUE TITLE
Returning from Landia with the portal spawned a new portal and deleted the part of the base portal spawned at.

### ISSUE THREAD

**Issue by daddy77gaming** [Cazadorsniper/PO3#641]
Project Ozone 3: Titan mode - v3.1.44 -
Multiplayer

Returning home from Landia using the portal spawned in a new portal and deleted the part of the base it spawned at..

![2019-09-25_16 28 02](https://user-images.githubusercontent.com/31905330/65616142-d6abb880-dfba-11e9-9ef4-a3cc9dc5cff5.png)

Not exectly trying to reproduce since i'm not OP on the server, not happy to have more of my base be deleted..

**Comment by daddy77gaming** [comment]
![2019-09-25_16 38 30](https://user-images.githubusercontent.com/31905330/65616431-5174d380-dfbb-11e9-9a86-6ec8c0ef12b5.png)

 It also generated a second portal in Landia itself

**Comment by Cazadorsniper** [comment]
You can try using portality or waystones to get there instead.

**Comment by tjsd** [comment]
Great with alternatives, but this is a base destroying bug. It cant stay like this!

**Comment by Cazadorsniper** [comment]
Its likely doing the same thing as a nether portal would do sometimes.

**Comment by daddy77gaming** [comment]
![2019-09-27_23 38 34](https://user-images.githubusercontent.com/31905330/65806166-a6197980-e188-11e9-8e75-553d353b8251.png)
 same issue with twilight portal

**Comment by Cazadorsniper** [comment]
There is nothing I can really do about that.

**Comment by Cazadorsniper** [comment]
Could also be a sign of corruption.
