### ISSUE TITLE
Inertia Cancellation

### ISSUE THREAD

**Issue by number65259** [Cazadorsniper/PO3#642]
Love this pack. Nearing the end of normal mode and I notice that DE armor inertia cancellation makes it significantly more tolerable than Multi Armor/Infinity Armor for general use. It'd be nice to have Draconic Additions included in the pack, if for no other reason than the inertia cancellation ring. This will allow a somewhat smoother progression from DE->Multi->Infinity. Player can gain noclip, but won't lose inertia cancellation that is necessary for building/fine movement with high movement speed flight.

**Comment by Cazadorsniper** [comment]
Don't plan on adding any mods.
