### ISSUE TITLE
Crashing on Pneumaticraft manual

### ISSUE THREAD

**Issue by catcrazy9** [Cazadorsniper/PO3#643]
Pack Version: Singleplayer

Description:Every time I try to look at the air compressor or heat entries in the Pneumaticraft manual it crashes the game

Steps to reproduce:Look at air compressor or heat entries in the manual, there may be more I didn't want to check

Crash log (use pastebin or issue will be closed):Version: 3.1.44

https://pastebin.com/rXPFf9NM
and 
https://pastebin.com/8VBfmph9

**Comment by Aiduino** [comment]
While I'm here, also happened with me, when trying to access the "Oil" Section of the Patchouli book. I'm sure it's pretty similar, but here's a crash log [https://pastebin.com/6GH9hfpX](url)

**Comment by Cazadorsniper** [comment]
Try updating Java.

**Comment by MineplayerHDYT** [comment]
Got the same problem

**Comment by Cazadorsniper** [comment]
Removed the manual for next update.
