### ISSUE TITLE
Philosopher's Stone craft doesn't work

### ISSUE THREAD

**Issue by VBodrov** [Cazadorsniper/PO3#644]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Problem similar to 
https://github.com/Cazadorsniper/PO3/issues/489
But, we have all mods enabled on server, still Philosopher's Stone reciept doesn't work

**Steps to reproduce:**
Use reciept of Philosopher's Stone on extended crafting table. It doesn't work neither with manual craft, nor with autocrafting.
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I have already reported this to the Extended Crafting dev, only solution is to restart the server.

**Comment by VBodrov** [comment]
I am afraid, restart have not helped either.
Well, will wait 'till Extended Crafting will find out something.

**Comment by XLgaminginc** [comment]
My solution for this was fully charging the stone, after that the recipe did work for me

**Comment by Cazadorsniper** [comment]
Can't charge the stone if it doesn't come out the table in the first place.

**Comment by Necromangel** [comment]
All the crafts, coming out of the ultimate crafting table are impossible to get out despite all the ingredients

**Comment by Cazadorsniper** [comment]
Not all of them.

**Comment by VBodrov** [comment]
Crafts on Champion's bench of ArmorPlus have the same issue.
