### ISSUE TITLE
Can't craft crushing table from magneticraft

### ISSUE THREAD

**Issue by enarkay** [Cazadorsniper/PO3#646]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  - 3.1.44
**Singleplayer, Multiplayer, or LAN?:** - Multiplayer

**Description:** - Even if I put in all the recipes correctly, manually OR automatically with JEI, you just can't make the crushing table from magneticraft.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Is the packmode the same on client and server?

**Comment by JeanBilski** [comment]
we have the same problem, the mod pack is the same on client and server

**Comment by enarkay** [comment]
I haven't touched anything with the packmode, so unless I somehow have to manually set a packmode for either or both the client and server, I would suppose they're the same at their defaults.

**Comment by Cazadorsniper** [comment]
If left as default on server then change it to normal, I accidentally left kappa there as default.

**Comment by enarkay** [comment]
Ah, oki doki - will do and return with the results
