### ISSUE TITLE
Wolf AI bug

### ISSUE THREAD

**Issue by tyler489** [Cazadorsniper/PO3#649]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 1.44 Titanmode
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
Tamed Wolfs Hostile to other Tamed Wolfs
**Steps to reproduce:**
Tame 2 wolfs and the fight eachother making it impossible to breed wolfs
**Crash log (use pastebin or issue will be closed):**
n/a

**Comment by Cazadorsniper** [comment]
Likely due to ESM maybe.

**Comment by ReiDaTecnologia** [comment]
> Likely due to ESM maybe.

Adding "minecraft:wolf" in the ESM mob blacklist fix the issue.
