### ISSUE TITLE
AE2 Substitutions not working

### ISSUE THREAD

**Issue by cwilkinsvi** [Cazadorsniper/PO3#65]
**Pack Version:**
3.0.38
**Description:**
AE2 Autocrafting is incapable of pulling in substitutions for quartz dust or fluix crystals when autocrafting recipes. Recipes seen in quartz glass, only can use certus dust when recipe allows for all quartz dust, ME cable not allowing use of pure fluix when recipe allows subs with regular fluix.

Single player world. 

**Steps to reproduce:**
Setup autocrafting of quartz glass/ME glass cable with regular items, put alternatives in system with subs allowed.

**Crash log:**
N/A

**Comment by TheKleopiNetwork** [comment]
can confirm

**Comment by Artemis-E** [comment]
During pattern creation there is a very small icon that looks like an eraser at the top right of the 3x3 field. That toggles exact match or substitution.

**Comment by cwilkinsvi** [comment]
And when you set it to allow subs, it does not.

**Comment by cwilkinsvi** [comment]
Unless it's the backwards logic where when it says "allow subs" it's actually the opposite and does not.

**Comment by Artemis-E** [comment]
I see what you’re talking about. For me it’s only affecting some recipes. Like quartz glass. I thought I had it working for something else on the world I lost when the twitch launcher died on me a few day ago.
