### ISSUE TITLE
Better Questing Quests Reset

### ISSUE THREAD

**Issue by Lestraa** [Cazadorsniper/PO3#651]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.44
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Upon logging into the game, my progress in the Better Questing questbook has been completely reset. Is there a way to reload it back? If I have to I can manually complete the quests again but i'd rather not if i don't have to

**Steps to reproduce:** I had to force close the game while it was "saving the internal server" after I went to "save and exit the game" because it was frozen. I have a feeling that that was probably the issue
 
**Crash log (use pastebin or issue will be closed):** It doesn't look like there's a crash report to attach.

**Comment by Cazadorsniper** [comment]
Can manually complete them or load a backup world.
