### ISSUE TITLE
Server defaults to Kappa

### ISSUE THREAD

**Issue by MissPotato** [Cazadorsniper/PO3#652]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
The PO3/Config/PackMode.cfg pack mode string for the server is set to Kappa mode by defualt. 
**Steps to reproduce:**
Download PO3-3.1.44server from curseforge 
**Crash log (use pastebin or issue will be closed):**
N/A due to nature of issue.

**Comment by Cazadorsniper** [comment]
I know

**Comment by MissPotato** [comment]
Ah, sorry I wasn't certain because there was no bug report about it.

**Comment by Cazadorsniper** [comment]
It was an accident, when I made the files is all.
