### ISSUE TITLE
Tinkers Sharpening Kit cant be used to upgrade mining level on your tool.

### ISSUE THREAD

**Issue by MickGeraerds** [Cazadorsniper/PO3#653]
# Use the search function before reporting to see if the issue has been reported before.
PO3 3.1.44
Multiplayer
Titan mode

**Description:**
Sharpening kit doesn't work to upgrade mining level (only tried with garfax)

**Steps to reproduce:**
create a garfax sharpening kit, try to upgrade your pickaxe in the tool forge by putting the pickaxe in the middle slot and the sharpening kit on any side

**Crash log (use pastebin or issue will be closed):**
No crash

**Comment by Mordaii** [comment]
Did you also a flint that is required to upgrade mining levels?

**Comment by Targren** [comment]
@MickGeraerds Works fine. You need to put flint along with the sharpening kit

**Comment by MickGeraerds** [comment]
Oh snap, i completely forgot.
