### ISSUE TITLE
Steel Casing Recipe doesn't appear to be working after updating to PO3-3.1.44

### ISSUE THREAD

**Issue by aivass** [Cazadorsniper/PO3#654]
![Screenshot (1)](https://user-images.githubusercontent.com/25469916/66033276-cc5a5480-e4bb-11e9-8310-a4ab4fc0b5f3.png)

**Comment by Cazadorsniper** [comment]
Are you playing on a multiplayer server?

**Comment by aivass** [comment]
yes, run locally on the same machine

**Comment by Cazadorsniper** [comment]
change the server packmode to whatever mode you're playing.

**Comment by aivass** [comment]
fixed, thank you
