### ISSUE TITLE
Game crashes going to Mercury

### ISSUE THREAD

**Issue by w3ricardo** [Cazadorsniper/PO3#655]
Pack Version: 3.1.44
Singleplayer

Game crashes when I tried to go to Mercury. 

Steps to reproduce: Launch rocket, choose Mercury, then click on Launch. I didn't try going to other planets, not even teleporting there.

`Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@597ce5b8: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.util.CompatibilityManager.forceLoadChunks(Lnet/minecraft/world/WorldServer;)V at com.mjr.extraplanets.planets.Mercury.TeleportTypeMercury.onSpaceDimensionChanged(TeleportTypeMercury.java:56) at micdoodle8.mods.galacticraft.core.util.WorldUtil.teleportEntity(WorldUtil.java:1017) at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:746) at micdoodle8.mods.galacticraft.core.util.WorldUtil.transferEntityToDimension(WorldUtil.java:716) at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onServerTick(TickHandlerServer.java:281) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3859_TickHandlerServer_onServerTick_ServerTickEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:745)`

**Comment by maginator** [comment]
Same Problem Here but on Server: https://pastebin.com/CdPK3UEs Crash Report from Server
