### ISSUE TITLE
Inscription Tile Multiplayer

### ISSUE THREAD

**Issue by BlueZtar** [Cazadorsniper/PO3#657]
Pack Version : PO3-3.1.44
Multiplayer
Description: I am at the mission: Inscription but it is impossible for me to craft the Inscription Tile. How to fix the problem without going through the give?

**Comment by Cazadorsniper** [comment]
Should be possible to craft the tile.

**Comment by BlueZtar** [comment]
I don't understand why i can't craft the tile. :( ( https://prntscr.com/pe3hi9 )

**Comment by Cazadorsniper** [comment]
Is the server on Kappa mode?

**Comment by BlueZtar** [comment]
hum i looked in the packmode file and i saw that the S: packMode = kappa so yes it is good in kappa mode but i have not seen craft in the file

**Comment by BlueZtar** [comment]
I just passed the server in normal mod and craft function well: D thank you very much Cazadorsniper

**Comment by Cazadorsniper** [comment]
No Problem
