### ISSUE TITLE
Visual bugs and being thrown of the island

### ISSUE THREAD

**Issue by maart999** [Cazadorsniper/PO3#658]
1.12.2
Singleplayer

Description: I am experiencing weird visual bugs such as bright lights and other weird textures.
if i stare at them for too long i will get thrown of the island. as you can see from the pictures im getting thrown of really far and the weird texture when im in the end but every other dimension aswell

i dont know how to reproduce the issue

it didnt crash so i cant attach anything
![2019-10-03_15 53 23](https://user-images.githubusercontent.com/56122910/66133525-1bf16b00-e5f7-11e9-84df-34b6abb2f8a9.png)
![2019-10-03_15 53 26](https://user-images.githubusercontent.com/56122910/66133526-1bf16b00-e5f7-11e9-8fdb-afd0fbd772e0.png)
![2019-10-03_15 52 51](https://user-images.githubusercontent.com/56122910/66133527-1bf16b00-e5f7-11e9-948f-6f3818ba8c59.png)

**Comment by maart999** [comment]
A few more weird things also my controls are all weird when is press w i go the the right etc.
![2019-10-03_16 06 25](https://user-images.githubusercontent.com/56122910/66134009-e7ca7a00-e5f7-11e9-8355-8440820bbdec.png)
![2019-10-03_16 06 30](https://user-images.githubusercontent.com/56122910/66134010-e7ca7a00-e5f7-11e9-8a44-02ad63553baa.png)

**Comment by Cazadorsniper** [comment]
What betterfps algorithm are you using?

**Comment by maart999** [comment]
> 
> 
> What betterfps algorithm are you using?

the standard one but i pressed it a few times becuz i heard it would improve lag, then it said something about restarting but i accidentaly pressed esc.

**Comment by Cazadorsniper** [comment]
Which one they all have a name?

**Comment by maart999** [comment]
> 
> 
> Which one they all have a name?

okay i doesnt matter anymore because its fixed
