### ISSUE TITLE
Crash when lauching to Mercury and Jupiter

### ISSUE THREAD

**Issue by LynxieVice** [Cazadorsniper/PO3#660]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
PO3-3.1.44 -(beta)

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
when visiting planets that require tier 3 and above rockets game crashed when lauching upon reload of pack i load into the planet i selected falling as it normally would

**Steps to reproduce:**
crafted tier 3 rocket and launch to Mercury
crafted tier 4 rocket and launch to Jupiter
(i havent tried any of the other higher planets yet)
Tier 1 and 2 went smoothly

**Crash log (use pastebin or issue will be closed):**
Mercury crash: https://pastebin.com/SkmpC8Ca
Jupiter crash: https://pastebin.com/h2y9dUaQ
Saturn: https://pastebin.com/2RD1Jf00 (just went to Saturn same crash)

**Comment by Cazadorsniper** [comment]
Can you update MJRLegends Lib and ExtraPlanets to see if that fixes the problem?

**Comment by LynxieVice** [comment]
@Cazadorsniper i have updated mods to version
MJRLegendsLib-1.12.2-1.1.9
ExtraPlanets-1.12.2-0.5.8

before updated created a new test world and went to Mercury and crashed after update i went to Jupiter and loaded right in (both first time visits)

seems updating fixes the issue

Thank you
