### ISSUE TITLE
Game freeze at mod initialization Phase 2- Ender IO

### ISSUE THREAD

**Issue by sixper** [Cazadorsniper/PO3#663]
Hi everyone,

I was trying to install PO3. I am using twitch launcher.

When i launch the game, it freeze at  mod phase 2.
i see ender IO then stuck.

Game Version PO3-3.1.44
Forge Version forge- 14.23.5.2838

Here is the latest.log

[latest.log](https://github.com/Cazadorsniper/PO3/files/3692876/latest.log)

İ could not copy it to pastebin due to 512 kb limit.

![Untitled](https://user-images.githubusercontent.com/32885218/66250091-7a792f00-e746-11e9-9b60-a2822a9d3608.png)

**Comment by Cazadorsniper** [comment]
Can you try updating Java?

**Comment by sixper** [comment]
My java version up to date i think :/

![ascxc](https://user-images.githubusercontent.com/32885218/66257211-ba6c0080-e79e-11e9-942b-4395a03a21c1.png)

**Comment by Cazadorsniper** [comment]
Then you need PO3 to use that version.

**Comment by sixper** [comment]
Sorry, i didnt get what you said

**Comment by Cazadorsniper** [comment]
https://www.youtube.com/watch?v=-uUr1VAnkcs
