### ISSUE TITLE
Quests won't be valid

### ISSUE THREAD

**Issue by TerMinaTeur548** [Cazadorsniper/PO3#666]
la quêtes de Beta Empowerer ne veut pas se valider pourtant je l ai remplie pourriez vous m aider s il vous plait

**Comment by TerMinaTeur548** [comment]
Beta Empowerer's quests don't want to be validated yet I filled it out could you help me please

**Comment by Cazadorsniper** [comment]
You mean the quest won't update?

**Comment by imweez** [comment]
![Jre-legacy Screenshot 2021 04 02 - 14 05 16 69](https://user-images.githubusercontent.com/81811187/113414332-0d873980-93bd-11eb-9da0-4329f873029c.png)
![Jre-legacy Screenshot 2021 04 02 - 14 10 12 24](https://user-images.githubusercontent.com/81811187/113414380-28f24480-93bd-11eb-94f6-d30558e2faed.png)

j ai craft le premium power cell mais la quête ne c'est pas valider.
