### ISSUE TITLE
Unable to craft the crushing table from Magneticraft 

### ISSUE THREAD

**Issue by Kerellian** [Cazadorsniper/PO3#667]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Pack Mode:**
normal
**Singleplayer, Multiplayer, or LAN?:**
multiplayer
**Description:**
when trying to craft the crushing table on normal mode it will not craft
**Steps to reproduce:**
fresh install to server. try to craft the crushing table with both tinkers crafting table and the vanilla crafting table. it will not work
**Crash log (use pastebin or issue will be closed):**
n/a

**Comment by Cazadorsniper** [comment]
Set server pack mode to normal.
