### ISSUE TITLE
Crash when veinmining red gem blocks in The Erebus

### ISSUE THREAD

**Issue by PlacidK** [Cazadorsniper/PO3#67]
**Pack Version:** 3.0.38

**Description:** Game crashes when veinmining red gem blocks in The Erebus with a Tinkers pickaxe with the Global Traveller trait (the one you can bind to an inventory) mining them 1 at a time does not crash.

**Steps to reproduce:** Make a tinkers pickaxe (mine is platinum head, copper binding, wood handle) bind it to a medium crate in the overworld (chunkloaded with FTB utils and chicken chunks)
Travel to the Erebus and veinmine red gem blocks.

**Crash log:**  https://pastebin.com/RUZY0Bbb

**Comment by Cazadorsniper** [comment]
does this happen with other blocks?

**Comment by PlacidK** [comment]
Not that i know.
Tried umberstone, ores, jade ores. all ok.

**Comment by Zapstur** [comment]
Replicated the crash on my end.  Luck III and Unbreakable don't affect it.

(VeinMining = OreExcavation)

So here's a few things I've noticed:

1.) VeinMining the Redgem blocks using a Pickaxe that has PlusTiC's "Global Traveler" trait seems to ALWAYS mine two blocks before crashing, other picks, however, seem to be able to VeinMine the Redgem blocks correctly and NOT crash.

2.) PlusTiC's "Global Traveler" trait functions correctly on Redgem blocks when not using VeinMiner, even in a different dimension from the target inventory (as intended).

3.) The crash (as described by the original poster) still happens even while located in the same Dimension and Chunk as the container, even in the Overworld.

4.) Decreasing the speed of VeinMining in OreExcavation to as low as 1 Block per Tick does not prevent a crash.

All of that said, it seems like this is a weird three-way conflict between the OreExcavation mod, PlusTiC's Global Traveler trait, and Erebus's Redgem block.  So, other than blacklisting the Redgem block from being VeinMined at all, I can't imagine a solution being found anytime soon.  

That said, even if it is blacklisted in the configurations by default until a solution is found, guaranteed there will be people who remove it from the blacklist, get a crash, and then submit a bug report without even looking for similar issues here on GitHub first.

**Comment by Zapstur** [comment]
Please keep in mind that I have no experience with how exactly any of those mods work, so I could be wrong about what is causing the crash.
