### ISSUE TITLE
Cannot create Crushing Table so No Buckets!!

### ISSUE THREAD

**Issue by JpPhysics** [Cazadorsniper/PO3#673]
**Pack Version: 3.1.44
**Pack Mode: botania-skyblock
**Singleplayer, Multiplayer, or LAN?: Multiplayer

**Description:  Quite simply cannot craft the Crushing Table**

**Steps to reproduce:Place stone slabs, aluminum and wood in crafting table.**

**Crash log (use pastebin or issue will be closed): No**

**Comment by Cazadorsniper** [comment]
set packmode on the server to normal.

**Comment by JpPhysics** [comment]
Set PackMode to Normal, still not working.  Also cannot craft Machine Frame.  Do I need to re-boot server when I change the PackMode?

**Comment by JpPhysics** [comment]
Set packmode to normal and re-booted server.  Works great, thanks!!
