### ISSUE TITLE
Iridescent altar, empowerer are not working properly on Multiplayer(server)

### ISSUE THREAD

**Issue by Isagoarth** [Cazadorsniper/PO3#675]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Pack Mode:**
normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
1st issue)When using extended recipes in the astral sorcery (ones using iridescent altar and spectral relays), when you place items in altar and r-click on it with resonating wand, crystal does not show where to place additional items in spectral relays. Because of that most of items from this crafting are impossible to make

2nd issue)Empowerer does not accept items other than ones from the mod "Actually Additions". Because of that player can't craft double-layer capacitor and better.

**Steps to reproduce:**
1st issue)
1. Have Radiance bookmark accesible in the astral tome
2. Have Crystal attuned to Lucerna 
3. Have iridescent altar multiblock constructed
4. Place 8 astral relays around iridescent altar
5. Make sure that you can access enough starlight
6. Try any extended recipe for example Observatory
7. After placing item in altar r-click on it with resonating wand
8. Observe

Altar does not show where to place additional items in spectral relays.

2nd issue)
1. Have Empowerer placed in world
2. Try to use on it item needed to craft one of capacitor for example Glowstone block
3. Observe

Player can't insert item into empowerer.

**Crash log (use pastebin or issue will be closed):**
n/a

**Additional Information:**
I have tried resetting and changing difficulty to titan about 2-3 times and none of it helped, I also checked that if this issues are multiplayer only and yes, they are multiplayer only.

**Attached videos:**
https://www.youtube.com/watch?v=P_bhIrPwazQ
https://www.youtube.com/watch?v=3vdKDfAKs9E

**Comment by Cazadorsniper** [comment]
are you changing the packmode on the server too?

**Comment by Isagoarth** [comment]
If writing "/packmode <modename>" in chat as OP changes it so yes. If you have to change server files then no.

**Comment by Cazadorsniper** [comment]
did you restart the server each time you changed packmode?

**Comment by Isagoarth** [comment]
Ofcourse i did, in accordance with instructions shown after confirming the command.

**Comment by Cazadorsniper** [comment]
is the client also on the exact same packmode?

**Comment by Isagoarth** [comment]
Yes.

**Comment by Cazadorsniper** [comment]
Well if you go back to normal mode then the second issue should stop.

**Comment by Isagoarth** [comment]
Can't test it now but as soon as i will be able to I'll do it and reply.

**Comment by Cazadorsniper** [comment]
The capacitor shouldn't be in the empowerer in the first place, thats only in Titan and Kappa mode.

**Comment by Isagoarth** [comment]
Well that was weird for me too. I made auto crafting of Octadic Capacitor one day and it worked fine, and the day after it was displayed as invalid recipe in the AE system and NEI started showing recipe that required Empowerer, also as far as i know no one was changing server packmode
