### ISSUE TITLE
Game Crashing Mid Play

### ISSUE THREAD

**Issue by Aiduino** [Cazadorsniper/PO3#676]
Pack Version: 3.1.44 Pack Mode: Singleplayer

Description: After playing the game for anywhere between five to twenty minutes, the game will just close. It doesn't produce a Minecraft crash log, but (to my understanding) Java is logging a memory dump(?) as a file with the name `/hs_err_pidxxxxx`.  I have zero experience with Java, or looking at memory dumps, so this is all kinda Greek to me. I understand that there is a possibility this is not a Project Ozone 3 issue, and if it isn't please feel free to brush this to the side, but any input from anyone on what's causing this would be a blessing. Thanks!

Steps to reproduce: Extremely hard to say, as I mentioned it can happen anywhere from 5 minutes mid play, to 20 or 30 minutes. I haven't been able to find any correlation between crashes. I will say, I believe it started just after implementing an ME system.

Crash log (use pastebin or issue will be closed):
[https://pastebin.com/iM4TkEw7](url)
(I have a few more, this has happened consistently for the last week)

Edit: I found the Issue Template

**Comment by Cazadorsniper** [comment]
Try updating Java

**Comment by Aiduino** [comment]
Updated, will be trying to play tonight.

**Comment by Aiduino** [comment]
Just double checked, and I'm on the most recent version of Java. Updating Java seemed to fix the issue for a while, didn't experience any sudden crashes until this morning. Here's another pastebin, although it is probably very similar to the first: [https://pastebin.com/SEaYQe6h](url)

**Comment by Cazadorsniper** [comment]
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)

That says you're still using the same old Java version.

**Comment by Aiduino** [comment]
Turns out, the Twitch app is forcing me to use that build of Java, even though it doesn't look like I even have that build installed on my computer. Time to set up MultiMC I guess
