### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by mikroskeem** [Cazadorsniper/PO3#677]
**Pack Version:** 3.1.44
**Pack Mode:** N/A
**Singleplayer, Multiplayer, or LAN?:** N/A

Additional info (can be seen from the log, but brought that out):
**Java version:** 1.8.0_222 (AdoptOpenJDK)
**OS:** Mac OS X Catalina

**Description:**
Game crashes on load

**Steps to reproduce:**
1) Install MultiMC
2) Grab PO3 zip from Curseforge and import it
3) Set max memory to 6144MB
4) Try to launch
5) Play pong
6) Sudden crash

**Crash log (use pastebin or issue will be closed):**
https://paste.ee/p/Q9I3s

**Comment by Cazadorsniper** [comment]
Something to do with Ultimate Armor.
