### ISSUE TITLE
Server has started randomly crashing even while everything seems to be fine.

### ISSUE THREAD

**Issue by Connorakis** [Cazadorsniper/PO3#679]
# Use the search function before reporting to see if the issue has been reported before.
**1.12.2**
**Normal**
**Multiplayer**

**Server has started crashing randomly after I mined up to the top of the Erebus dimension. I get the "ServerHangWatchdog detected that a single server tick took 60.01 seconds (should be max 0.05)"**

**Crash log: https://pastebin.com/cjhDHJ7R**

**Comment by Cazadorsniper** [comment]
server.properties > max-tick-time=-1
