### ISSUE TITLE
Digital Miner Stops working when leaving dimension

### ISSUE THREAD

**Issue by ixanza** [Cazadorsniper/PO3#680]
Pack Version: 3.1.44
Pack Mode: Titan
Singleplayer, Multiplayer, or LAN?: Multiplayer Server

The Mekanism Digital Miner stops mining for ore when I leave the dimension. The dimension is chunkloaded and the digital miner works fine while I'm in the dimension

Here's the digital miner setup with the spot loader
![2019-10-26_11 02 20](https://user-images.githubusercontent.com/5535758/67613480-a422f480-f7e0-11e9-9436-9691c1709071.png)

Screenshot showing its working
![2019-10-26_11 02 33](https://user-images.githubusercontent.com/5535758/67613485-adac5c80-f7e0-11e9-9fc0-c2ab636b0fcd.png)

Screenshot after coming back into the nether
![2019-10-26_11 03 18](https://user-images.githubusercontent.com/5535758/67613487-b69d2e00-f7e0-11e9-980c-1b06d3b43cb4.png)

**Comment by Cazadorsniper** [comment]
Have you tried the chunkload upgrade?

**Comment by ixanza** [comment]
I have to admit I never knew such an upgrade existed. It works as intended now. Thank you Cazador
