### ISSUE TITLE
Violent Shaking when using Hydraulic Platforms from Galacticraft

### ISSUE THREAD

**Issue by ROMVoid95** [Cazadorsniper/PO3#682]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.44
**Singleplayer, Multiplayer, or LAN?:** Public Multiplayer Server

**Description:**
Player gets stuck in a violent shaking motion when either interacting with the top lift to go down, or when coming close to the top lift when started at the bottom of the lift.
Happens on MP & SP
**Steps to reproduce:**
make a 2 lift system with the Hydraulic Platforms from Galacticraft. Then just use the lift
on a multiplayer server, if you get someone to try and kill you while stuck, any hits do not register for 15 seconds, when you die. it apparently thinks your in Spectator Mode as doing a command give you a "cannot do that command while in Spect. Mode"

I test a lot of Galacticraft related bugs and compatibility for the mod and have not been able to reproduce this in a test instance. Not sure if its caused by another mod other than Galacticraft or its addons.
I posted a video to better show the issue
https://youtu.be/iw8tOEpA-Wg

**Crash log (use pastebin or issue will be closed):**
no crash log, and latest.log file shows no output of anything during this bug

**Comment by Cazadorsniper** [comment]
what happens if you stand in the exact middle of it? Also that is funny.

**Comment by ROMVoid95** [comment]
the effect is the same regardless of the position/direction player is standing on the platform. As long as the platform is green the platform performs the move

**Comment by Cazadorsniper** [comment]
lol I'll see what i can do.

**Comment by Cazadorsniper** [comment]
I couldn't reproduce this.
