### ISSUE TITLE
Crashes on first load up

### ISSUE THREAD

**Issue by Dracus1283** [Cazadorsniper/PO3#683]
Pack Version: 3.1.44
Pack Mode: n/a
Singleplayer, Multiplayer, or LAN?: n/a

Description: I've tried loading the mod multiple times, and every time it gets to a point and stops responding. I have a brand new ASUS ROG G731GWXB74, with an Intel core i7 9th Gen, and 16 gigs of ram. It maxes out my CPU while loading.

Steps to reproduce: n/a

Crash log (use pastebin or issue will be closed):
https://pastebin.com/embed_js/p11tbeYm

**Comment by Cazadorsniper** [comment]
Minecraft is using Intel(R) UHD Graphics 630 GL version 4.5.0 as the graphics card might want to switch that.

**Comment by Dracus1283** [comment]
I have both that Intel uhd graphics and a Nvidia geforce rtx 2070. So I dont believe it's that that's causing the problem

**Comment by Cazadorsniper** [comment]
You want it to use the RTX 2070, not the Intel graphics.

**Comment by Dracus1283** [comment]
How would I be able to make it use the RTX?

**Comment by Cazadorsniper** [comment]
There are videos on youtube to learn how to do that.

**Comment by Dracus1283** [comment]
I made the switch, and now the loading screen doesn't come up. Its a black screen for about 30 seconds, then it changes to a Mojang logo, and then after 5 minutes it crashes. Here is the crash report:
https://pastebin.com/embed_js/Mn5jXKgy

**Comment by Dracus1283** [comment]
I uninstalled and reinstalled,  and its working

**Comment by Dracus1283** [comment]
I spoke too soon. The load screen did come up, but it ran into the same problem. It seems to be catching on the Just Enough Items mod. Here is the crash report:
https://pastebin.com/embed_js/WeuUeE4f

**Comment by Dracus1283** [comment]
It gets to loading- finishing up 6/7, Load complete- just enough items 18/287, And loading recipes 6545/139504 on the loading screen when it crashes

**Comment by Cazadorsniper** [comment]
Give it more ram to use your only giving it -Xmx3228m, best to be -Xmx6144m
