### ISSUE TITLE
bad recipe in lord craft and maybe others. 

### ISSUE THREAD

**Issue by Lazersgm** [Cazadorsniper/PO3#684]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.1.44**
**Pack Mode:normal**
**Singleplayer**

**Description:**
wrong recipe for inscription tile
**Steps to reproduce:**
no known steps
**Crash log (use pastebin or issue will be closed):**
no crash 
image of recipe. https://gyazo.com/31e89e308a76cba7d3017b5fc2d5fbe5

fresh clean reload of pack did not fix it.

**Comment by Lazersgm** [comment]
i was watching a streamer running the same mod pack and his was much easier. i showed him mine and him and many other ppl in the stream said it was bugged. i am playing on normal mode btw. i think the normal recipe is some stone and stuff. not  mana infused ingots and monster drops.

**Comment by Lazersgm** [comment]
i tried to play on a dedicated server i set up and i get this "java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe lordcraft:188 (com.cobbs.lordcraft.Utils.Recipes.VoidShapelessRecipe@168f425d) produces unregistered item lordcraft:anchor_ignisb (net.minecraft.item.ItemBlock@5acbcbae)" another error about the lord craft mod?

**Comment by Cazadorsniper** [comment]
The streamer is likely playing titan mode where the recipe wasn't changed for that mode.
In normal mode the recipe is changed to fit progression.
Only change I can do for that recipe is to replace titan's with normal's.
Does the lordcraft recipe exception actually crash the game?

**Comment by Lazersgm** [comment]
ya he was on titan mode. thought the recipe would be easier on the lower setting. guess i was wrong. that error went away after the 3rd? time i reinstalled the pack. not sure why that was happening. thanks for your help. think i am all set now.

**Comment by Cazadorsniper** [comment]
ok
