### ISSUE TITLE
Client Crash with Wand of Animation 

### ISSUE THREAD

**Issue by MissPotato** [Cazadorsniper/PO3#685]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.1.44

**Pack Mode:**Kappa
**Singleplayer, Multiplayer, or LAN?:**Singleplayer, Multiplayer but only crashes the clients

**Description:** Animating a ME drive-bay causes the client to crash during rendering, however, the server-end is fine. 

**Steps to reproduce:** Place ME Drive-bay, right-click with wand, crash. 

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/pZd4ps8J

Side Note: Other people who are experiencing a similar issue running "/kill @e[type=erebus:erebus.animated_block]" from the console will fix it. Don't use quotation marks.

**Comment by Cazadorsniper** [comment]
Use the wand of animation on Blocks not Tile Entities.
