### ISSUE TITLE
Craft does not work 

### ISSUE THREAD

**Issue by TooikLeChevalier** [Cazadorsniper/PO3#689]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Pack Mode:**
Kappa
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer 

**Description:**
There is a lot of craft that does not work and for example all the craft that we have to do the extended crafting table does not work (the item is displayed in the craft release but we can not take) another example of the steel casing that can not be crafted either (this time if the item does not show up even in the craft release) and there are many other examples like that. Which is a shame because we are on a multiplayer server and everyone does not op so can not give it to continue to move forward. 
Thank you for finding a solution if there is one.

**Comment by Cazadorsniper** [comment]
Make sure server is also on normal mode.

**Comment by Blubb12343** [comment]
Same problem. 
Server and Client are on Titan Mode. 
Cant craft double-layer capacitor (cant place coal powder on empowerer) and cant craft draconium seeds in the extended crafting table.

**Comment by TooikLeChevalier** [comment]
Yes my server si in normal mode for exemple the layer capacitor (simple double and octadicte) we can craft in a workbench

**Comment by Cazadorsniper** [comment]
Yeah just need to switch that to normal.

**Comment by TooikLeChevalier** [comment]
ok but if i change the mode the craft will change?  and the quest book will be buggy?

**Comment by Cazadorsniper** [comment]
no
