### ISSUE TITLE
Grains of Infinity not dropping 

### ISSUE THREAD

**Issue by sciber-underscore** [Cazadorsniper/PO3#690]
**Pack Version: 3.1.44 (playing through the twitch launcher)**
**Pack Mode: Garden of glass(Normal Mode)**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

Grains of Infinity is not spawning in skyblock (garden of glass). I'm in early game trying to craft the basic alloy furnace so I'm using the bedrock at the middle of spawn. I have tried setting the drop rate to 1 (from 0.5, in enderio config) and also the mintime to 1. It is simply not dropping no matter what. Any idea on how I can solve it?

**Comment by Cazadorsniper** [comment]
By not messing with the configs.

**Comment by sciber-underscore** [comment]
I only tried messing with the config because there was no drops. Nobody changes configs if everything is working. Thanks for the brilliant solution though.

**Comment by Cazadorsniper** [comment]
Your welcome (as I was trying to find a solution).
