### ISSUE TITLE
Client does not accept kappa mode

### ISSUE THREAD

**Issue by nikidino8** [Cazadorsniper/PO3#691]
**Pack Version:**
3.1.44
**Pack Mode:**
normal/titan
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Client only accepts normal or titan mode, while server also accepts kappa mode.

**Steps to reproduce:**
Install pack version 3.1.44 in the twitch launcher and look up the "packmode.cfg".

**Comment by nikidino8** [comment]
`
# Configuration file

general {
    S:acceptedModes <
        normal
        titan
     >
    S:packMode=normal
}
`

That's how the client packmode.cfg looks like and if I set it to kappa it will crash

**Comment by Cazadorsniper** [comment]
Kappa mode is not available for the public.
