### ISSUE TITLE
Mystical Agriculture infusion crystals

### ISSUE THREAD

**Issue by mmastrocinque** [Cazadorsniper/PO3#693]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
PO3-3.1.44
**Pack Mode:**
Kappa
Multiplater

**Description:**
Mystical Agriculture infusion crystals can't be made with insanium, supremium infusion crystal and prosperity shards, Used creative to spawn it in, and its recipes are not working with any tier essence to up-tier.

**Steps to reproduce:**
Attempt to create second highest infusion crystal. Full supremium crystal is being used.
**Crash log (use pastebin or issue will be closed):**
No crash

**Comment by Cazadorsniper** [comment]
packmode?

**Comment by mmastrocinque** [comment]
Ah, it might be the packmode. The default that comes with server files is kappa mode not normal mode.

**Comment by mmastrocinque** [comment]
Server files ship with mode set to kappa, this causes the issue.
