### ISSUE TITLE
Ticking entity issue compressed enderman

### ISSUE THREAD

**Issue by Bguerra111** [Cazadorsniper/PO3#694]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.0.41
**Pack Mode:** A new way forward, i believe its the normal mode
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:**  Whenever i use the mob masher it will crash and say that its a ticking entity issue and i found that it could be the compressed enderman and i wanted to know hoaw to fix this if its even possible to fix. Thank you

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Update
