### ISSUE TITLE
Visual Glitch moving drawer icons and chests

### ISSUE THREAD

**Issue by mfriedrich74** [Cazadorsniper/PO3#695]
Search Other Issues: No similar found
Pack Version: 3.1.44 (Twitch version)
Pack Mode: Titan
Mode: Multiplayer
Client OS: Windows 10 64-bit Pro 1903 (18362.418)
Launcher: Native Launcher via Twitch
Assigned Java memory: 10GB
Total Memory: 64GB
Graphics: Nvidia GeForce GTX 1080 Ti 11GB
Server: Nitrado 6144MB RAM

I seem to have a visual glitch or bug where after a while when looking horizontally all vanilla chests and the icons of drawers, the (e.g. creeper) trophies swing back and forth on the screen. There hitbox stays at the right spot.

The amplitude of the swinging model/icon is depending on the vertical and horizontal camera angle. Looking straight down makes them stop moving around. Looking somewhat south (a about 90 degree range towards south) makes its stop too. All other angles have a strong move of icons over the half of the screen in elliptical curves.

The issue occurs in Windows and Fullscreen mode.

The best way to show this is a short video:
https://youtu.be/dPe4HQzToaA

Steps to reproduce: No idea. It occurs only after a while after the client got restarted.
I have not figured out what this is triggered by.

I could provide access to the server, but i cannot guarantee the problem shows for you as i believe its a client-side issue with mods or minecraft (i have not seen it with any other mod-pack yet.

Crash log: No crashlog as there is no crash

**Comment by mfriedrich74** [comment]
O full java client restart helps for maybe 10 to 15 minutes, then it occurs again.
A simple logoff and logon without restarting the client does not fix the issue, the problem is seen again right after logon.

**Comment by mfriedrich74** [comment]
I am able to reproduce the issue in singleplayer by downloading and starting a world backup. A new world with just some drawers and a chest does not show the issue.
I can provide the world-backup (280MB) or a server-login if needed.

**Comment by Cazadorsniper** [comment]
What Betterfps algorithm are you using?

**Comment by mfriedrich74** [comment]
The default one that comes preconfigured. When switching to Native it still occurs.

**Comment by Cazadorsniper** [comment]
Hate it when github starts having issues

**Comment by mfriedrich74** [comment]
Yes, the default setting is one of those, maybe Taylor's. But I switched it on client side to Native and still occured. I will verify again to make sure.

Let me ask: Is this setting client side only or to be changed on server and client? If on server, how?

**Comment by Cazadorsniper** [comment]
Try Riverns

**Comment by mfriedrich74** [comment]
I am back from work and just checked it.

The twitch modpack defaults to "rivens".

The problem occurs with:
* Riven's: Yes
* Riven's Full: Yes
* Riven's Half: Yes
* Taylor's: Totally Broken, artifacts all over the screen, game freezing
* Random Math: Broken too, not as bad as Taylors, but still also game
* Vanilla: Yes
* Without BetterFPS: ?
(i am not trying Java Math, too slow)

**Comment by Cazadorsniper** [comment]
Any added mods?

**Comment by mfriedrich74** [comment]
No, just what comes with the pack. Nothing added, nothing removed (I added BetterFPS back on my client because that seems not to be the cause).
Which other mods included in the pack do graphical things?

**Comment by Cazadorsniper** [comment]
Can I have a copy of your world?

**Comment by mfriedrich74** [comment]
Here:
https://1drv.ms/u/s!AlDxpguEY2H5jGPDatX3nih1HnZz?e=s33oAa

**Comment by Cazadorsniper** [comment]
Using any plugins? I notice the death counter. That is a lot of storage drawers too.

**Comment by mfriedrich74** [comment]
Plugins? Not that I know of.

The death counter is built-in, ftb utilities I think. Just needs to be enabled. I can verify this tomorrow to be sure.
The drawers, that's not alot. I expect the system to grow about 10 times as it is now, planning for a big ME computer system.

But the size shouldn't have anything to do with the issue unless a mod has a bug.

Any ideas so far?

**Comment by Cazadorsniper** [comment]
I have no idea however I did notice that the items in the storage drawers disappeared for a second when I walked pass them. I remember seeing this issue before just don't remember the solution.

**Comment by mfriedrich74** [comment]
So, this seems to be a rendering issue with a particular block.
When i change the render distance to min 2 chunks, the problem goes away.

Its just a matter finding the offending mod/block that is causing it. Any idea how to locate it?
I don't really want to use such low render distance.

**Comment by Cazadorsniper** [comment]
maybe lag goggles?

**Comment by mfriedrich74** [comment]
Hmm, the render distance might be a red herring. trying lag goggles soon anyway.

**Comment by mfriedrich74** [comment]
Its the Spector illuminator

**Comment by Cazadorsniper** [comment]
lol

**Comment by ttechr** [comment]
The server I play on is having the same issue but it just started happening. I am trying to track down why it just started though.

**Comment by khthe8th** [comment]
I just had this same issue on my server and removing all the spectre illuminators made it go away as well
