### ISSUE TITLE
Project Ozone 3 Server 3.1.45server

### ISSUE THREAD

**Issue by WhyyyCarlll** [Cazadorsniper/PO3#696]
When trying to start a Project Ozone 3 server on my pc through the download, the pack wont load correctly and always crashes.

[crash-2019-11-07_16.12.56-server.txt](https://github.com/Cazadorsniper/PO3/files/3821724/crash-2019-11-07_16.12.56-server.txt)

**Comment by HazardEST** [comment]
PO3 server 3.1.45 is missing EnderCore, just get one from the client for now.
