### ISSUE TITLE
Armor workbench quests are no longer in order

### ISSUE THREAD

**Issue by Cipheus** [Cazadorsniper/PO3#698]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Regular
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** With the new update to the Armor Workbench Mod, quests are no longer in order. For example, after the tin quest, the next crafting material is void crystals, but in the quest book states it should be electrum.

**Steps to reproduce:** Check recipes in game for armor workbench

**Crash log (use pastebin or issue will be closed):** No crash

**Comment by Cazadorsniper** [comment]
Read the top of the changelog please.

**Comment by LingASDJ** [comment]
> # Use the search function before reporting to see if the issue has been reported before.
> 
> **Pack Version:** 3.1.45 **Pack Mode:** Regular **Singleplayer, Multiplayer, or LAN?:** Singleplayer
> 
> **Description:** With the new update to the Armor Workbench Mod, quests are no longer in order. For example, after the tin quest, the next crafting material is void crystals, but in the quest book states it should be electrum.
> 
> **Steps to reproduce:** Check recipes in game for armor workbench
> 
> **Crash log (use pastebin or issue will be closed):** No crash

Hi,[Cipheus](https://github.com/Cipheus)
