### ISSUE TITLE
Slimey Generator Recipe

### ISSUE THREAD

**Issue by gsoxreptile** [Cazadorsniper/PO3#699]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode:**
**Singleplayer, Multiplayer, or LAN?:**
multiplayer
**Description:**
Slimey Generator Recipe is missing the slime block in the middle
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Pack Version:?
Pack Mode:?

**Comment by RealGh0st** [comment]
Pack Version : 3.1.45
Mode: Titan
JEI does'nt show Slime block in the middle.
Recepie still work as intented. JEI is at fault
