### ISSUE TITLE
Magneticraft's Refinery multiblock accepting all fluids for steam input

### ISSUE THREAD

**Issue by pepijn777** [Cazadorsniper/PO3#7]
**Version:**
3.0.38

**Discription:**
You are supposed to feed Magneticraft's Refinery multiblock Hot Crude, Heavy/Light Oil from the back and Steam from the sides. The sides however seem to accept all fluids including the Hot Crude and Heavy/Light Oil and will work as if you fed it with steam. Feeding it these fluids on accident and thinking it's normal is easy to do if you don't carefully read the guidebook, it's GUI and JEI say nothing about steam being required. The fluid you used instead of steam will be used at the same rate steam would be used up, resulting in losing a lot of said fluid.

**Steps to reproduce:**
-Build Magneticraft's Refinery.
-Feed it Hot crude, Heavy/light oil from the back.
-Feed it any fluid from the side instead of steam/
-Open it's GUI and look at it work as if it had received steam.

**Crash log:**
Example picture using Liquid XP instead of steam:
http://oi66.tinypic.com/24y8t2s.jpg

**Comment by Cazadorsniper** [comment]
I can't do a thing about this besides removing the refinery, Magneticraft is no longer being developed.
