### ISSUE TITLE
Dank Null crashes on slab placement

### ISSUE THREAD

**Issue by Flutterdashie** [Cazadorsniper/PO3#70]
**Pack Version:**
PO3 Version 3.0.38
**Description:**
Hard crash when attempting to place a cobblestone slab from dank/null. One instance froze my computer and then blue screened it. Has happened about 4 times now, 3 of which were intentional for logging/testing.

**Steps to reproduce:**
Attempt to place a cobblestone slab onto the side or top of another cobblestone slab through dank/null (emerald version)

**Crash log:**
3 instances of the same crash:
https://pastebin.com/aMqi62d3
https://pastebin.com/yeMQ1WMa
https://pastebin.com/5BQuFrFX

**Comment by elbim** [comment]
Same here when trying to place a stone slab.

**Comment by ifficles** [comment]
I am having the same problem as well.  This has been reported to the Mod dev as a bug.
