### ISSUE TITLE
Absorption perk not staying on.

### ISSUE THREAD

**Issue by Lazersgm** [Cazadorsniper/PO3#700]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Pack Mode:**
normal
**Singleplayer, Multiplayer, or LAN?:**
Single
**Description:**
Absorption totem only lasting for 7 seconds with 2 shields at lvl 2. then it is off for a few seconds and comes back. unsure if this is normal?
**Steps to reproduce:**
unsure 
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
This is normal afaik

**Comment by Lazersgm** [comment]
ok thanks.
