### ISSUE TITLE
tier 1 Armor progression broken

### ISSUE THREAD

**Issue by Vulture74** [Cazadorsniper/PO3#701]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.1.45
**Pack Mode:**normal
**Singleplayer, Multiplayer, or LAN?:**singleplayer

**Description:**updated the pack to 3.1.45 from 3.1.44. now the tier 1 armor progression is broken. for instance I had the tin tier finished the next stage in the quest book is electrum. The electrum armor now requires silver armor to complete and silver requires gold armor to complete and so on. It appears that the quest book progression is reversed.

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Didn't read the changelog?

**Comment by Vulture74** [comment]
Yes I read the change log. I figured out the problem the update did not change my quest book tree. I started a new world and that has the correct progression chain. 

Now I just need to figure out how to reset or update my quest book after the update. Is there an in game command that can be used?

**Comment by Cazadorsniper** [comment]
at the top of the changelog
