### ISSUE TITLE
PackMode ... Updating pack always resets to normal

### ISSUE THREAD

**Issue by SephirothWS** [Cazadorsniper/PO3#702]
I'm not sure if its related to this pack or a specific mod, but I have noticed that every time my pack updates, I've got to go in and re-set the packmode.cfg file back to titan for my Titan mode playthrough. If there is a way to set that outside of the config directory and/or not reset to default on pack upgrade, that would make updating a bit smoother for me.

**Comment by Cazadorsniper** [comment]
I can't do anything about that.
