### ISSUE TITLE
chisels connected textures have just stopped working?

### ISSUE THREAD

**Issue by dansproject** [Cazadorsniper/PO3#703]
im using sphax and the textures used to be fine with it but after this recent update all the blocks from chisel wont use connected textures. did you update the version of chisel or ctm?

**Comment by Cazadorsniper** [comment]
yes

**Comment by tyr0wl** [comment]
There is already a fix for the new chisel version and sphax here:
https://bdcraft.net/community/releases-for-mods-f9/chisel-t1681-s570.html
