### ISSUE TITLE
Skylands - Where's the bedrock?

### ISSUE THREAD

**Issue by PerksPrisoner** [Cazadorsniper/PO3#704]
I couldn't find anything specifically talking about bedrock missing. But there is no available way or at least nothing my hour of research has found to help identify what I am to do for infinity grain. Without bedrock, it can not happen and I tried searching lower parts of the map to no avail. I see this as a bug as how are you meant to make the Alloy Smelter which apparently is the only device that can make Quite Clear Glass

**Comment by Cazadorsniper** [comment]
Have you've tried a different dimension?

**Comment by PerksPrisoner** [comment]
I have... Wait..... I forgot about the hunting dimension 🤦‍♂  Thank you!
