### ISSUE TITLE
Can't craft any capacitor that uses empowerer 

### ISSUE THREAD

**Issue by kenturkey** [Cazadorsniper/PO3#707]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version:3.1.45
Pack Mode:Titan
Singleplayer, Multiplayer, or LAN?:Singleplayer

Description:When trying to craft any capacitor that uses the empowerer it will not craft, There is power going to the stands, I can place the items down needed, but it will not craft. I've tried both the double layer and endergized.

**Comment by Cazadorsniper** [comment]
Try reloading the pack.

**Comment by kenturkey** [comment]
I have restarted the mod pack several times, I've changed the pack to normal for now so I could craft them. Maybe I should reinstall the mod pack?

**Comment by Cazadorsniper** [comment]
maybe
