### ISSUE TITLE
[3.1.45] Quests not synching in Party

### ISSUE THREAD

**Issue by JohanniklasLp** [Cazadorsniper/PO3#708]
Pack Version: 3.1.45
Pack Mode: Titan
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description: Questprogress won't get synced in a party

Steps to reproduce:
- Join on a server with at least one other person
- One of you has to create a party
- The other(s) have to join the party
> Progress won't get synced here, even if you have done some questing on the server beforehand
- Let another person finish a quest
> The quest won't get synced for you

**Comment by ZeBrasa** [comment]
If you had already joined the server, and you updated from a previous version, do /bq_admin default load

**Comment by oesi94** [comment]
Have the same issue, i have a new server. But its not syncing the progress for all

We are 4 in a party

**Comment by DrDerpensteinMD** [comment]
Party syncing was disabled in the latest version of better questing. If you want to re-enable it, install these older versions of the mod together instead:
BetterQuesting-3.5.300
StandardExpansion-3.4.159

**Comment by oesi94** [comment]
Are u sure, i mean why there is a party option. Maybe there is a setting to enable/disable it ?

**Comment by JohanniklasLp** [comment]
DrDerpenstein is right. The armor quests were in the right order already, it's the dev of BQ/SE who disabled party syncing (but iirc will enable it in a later version again [making it toggable via config], most likely due to public backlash)
