### ISSUE TITLE
Cannot Respawn or Reconnect in Server

### ISSUE THREAD

**Issue by DrDerpensteinMD** [Cazadorsniper/PO3#709]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**Latest (PO3-3.1.45)
**Pack Mode:**Normal
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**I am hosting the server and running my own client on the same pc. When I join the server alone, everything works perfectly. When at least 1 other person joins, I can no longer join the server. Also, if I'm already on and another person is with me, I cannot respawn when I die. The button clicks like it is going to respawn but then nothing happens.

**Steps to reproduce:**Host the latest version of PO3 server and join it. Invite at least one other person to the server. Kill character in any way. Try to respawn or rejoin the server.

**Crash log (use pastebin or issue will be closed):**
https://gist.github.com/DrDerpensteinMD/75046a6ffbfd4b9d36c0f021e5900bd5

**Comment by DrDerpensteinMD** [comment]
Ok, I finally fixed it by deleting the tombstone folder in the world directory and every file containing the problematic player's username and/or UUID in the entire server directory at once. I don't know specifically what caused the issue or which file was the problematic one, but I clearly got rid of it by doing this. I hope this helps anyone who has a similar problem in the future. (Note: The player did lose all his gear, even those parts saved in chests --- a small price to pay for salvation.)

**Comment by Cazadorsniper** [comment]
That is weird.
