### ISSUE TITLE
World crashed while using Extra Utilities, Biblio craft and Actually Additions

### ISSUE THREAD

**Issue by Ticskter** [Cazadorsniper/PO3#710]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Single Player

**Description:**i was attempting to duplicate an enchanted book using the extra utilities transfer node and pipes. i couldnt get the automation to work. Ihad the transfer node's UI open and shift clicked or "click and drag" an enchanted plate into the nodes slot, the item appears to have been moved from the node into the Actually additions repairer but crashed the game. now upon loading said world it crashes the second i can see the hot bar and UI space.

**Steps to reproduce:** Put Actually Additions repairer down with power supplied. place biblio craft printing press (the one that makes the anvil noise when placed). then use transfer node on Printing press and hook to repairer. the set up i was using was in a 4 space set up (checker board) with the repairer being on the top left, and the printing press on the bottom right. i had the transfer node and pipe connecting the two on the bottom left, as well as the top right, but with the transfer node connected to the repairer. i had a filter set with the printing chase set to pull out after the second book was copied. the chase was not taken out automatically and i placed it in the bottom left transfer node manually and game crashed.

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/MFb2SauU

**Comment by Ticskter** [comment]
Could this be easily fixed by removing the extra utilities mod from the mod list, load world, remove the Repairer save and exit, re-activate Extra utilities, and then reload the world?

**Comment by Ticskter** [comment]
Ok i just did a quick test in a creative world. the crash occurs when i attempt to use the transfer node to pull the repaired chase out of the Repairer and put it into the Printing Press.

**Comment by Cazadorsniper** [comment]
yeah don't automate bibliocraft stuff

**Comment by Ticskter** [comment]
@Cazadorsniper is there a way to fix this without having to restart my world? i just tried to remove the bibliocraft mod and starting the world up and other mods have dependencies in biblio craft so it wont load. any other ideas on how to fix my world without restarting?

**Comment by Cazadorsniper** [comment]
Try using worldedit to remove the ExU pipes.
