### ISSUE TITLE
file content differs from what was expected

### ISSUE THREAD

**Issue by JonasMLRS** [Cazadorsniper/PO3#711]
I load up the pack and when I click play in the launcher I get this message:

Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: D:\4 modded minecraft\Twitch\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

What do I do?

**Comment by Cazadorsniper** [comment]
I don't know, I recommend contacting Twitchapp support.

**Comment by JonasMLRS** [comment]
ok thx

**Comment by JonasMLRS** [comment]
> I don't know, I recommend contacting Twitchapp support.

ok thx

**Comment by HyPnOoO** [comment]
@JonasMLRS I should be able to help as I had the same issue.
What you need to do is follow the file path shown in your original post:
D:\4 modded minecraft\Twitch\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar in your case.

then you need to go to that URL:
https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
and replace the file in the aforementioned file path.

This worked for me but if it doesn't then go to twitch app support.

-Hypno

**Comment by JonasMLRS** [comment]
@HyPnOoO thanks it worked
