### ISSUE TITLE
[3.1.45] Crash on first launch. MMC 0.6.7-1375

### ISSUE THREAD

**Issue by AlgerT2019** [Cazadorsniper/PO3#712]
**Pack Version:** 3.1.45 
**Pack Mode:** default
**Singleplayer, Multiplayer, or LAN?:** N/A

**Description:** exit with -1/ First launch. Memory - 7.5 Gb

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/baxjvpWH

**Comment by Cazadorsniper** [comment]
F:/my games/MultiMC/instances/PO3_3145/minecraft
Can you remove the underscore between PO3 and 3145?

**Comment by AlgerT2019** [comment]
no. It did not help. ((

**Comment by Cazadorsniper** [comment]
can you remove the space between my games too?

**Comment by AlgerT2019** [comment]
It did not help.

but i reload instance on another comp. adn copy in F:/my games/MultiMC/instances/PO3_3145

its work! ) 
IMHO antivirus or proxy problem.


Thank you! 
PS: sorry. my english so bad.
