### ISSUE TITLE
Huge lags while playing on a sever on PO3

### ISSUE THREAD

**Issue by jakasc** [Cazadorsniper/PO3#713]
**Pack Version:** 3.1.44 & 3.1.45
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Hey. I've been encountering some weird things on PO3. In fact, what is happening is that when i'm playing on a server, i'm having huge lags for some reasons. First of all, this is not performance issues towards my PC or the server itself. Secondly, I've been running some cmd commands and speedtests while having those "lags" on the server, and this is not nor my connection. Then, the server itself is not lagging (TPS is constantly 20). But for some reasons, it sometimes starts lagging on my side which means I have high ping on the server, and eventually get timed out, whereas I'm having absolutely no lags everywhere else with my connection (on internet etc, my ping is good). That's weird because it only happens on PO3, and seems to not be linked to either my connection or the server. 

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):** I'm not suffering any crashes, but if you need any file then I can send.

**Comment by Cazadorsniper** [comment]
I will need the latest,log from the logs folder it "might" tell me what is wrong.

**Comment by jakasc** [comment]
Since i experienced no lags today on my session, I'll send you the logs from Sunday (I had lags here).

PS : I couldnt use pastebin since the file is exceeding the 512 KB for free accounts, so im sending the rar, hope it is okay
[2019-11-17-1.log.gz](https://github.com/Cazadorsniper/PO3/files/3865779/2019-11-17-1.log.gz)
`

**Comment by Cazadorsniper** [comment]
From what I've seen it looks like you're running plugins, Java on the server should be updated, and it seems that world is very old which can also cause lag too.

**Comment by jakasc** [comment]
Thanks, i'll see what i can do
