### ISSUE TITLE
So party dont syncing, and armour quests are weirdo.

### ISSUE THREAD

**Issue by GabrielAriel1337** [Cazadorsniper/PO3#714]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** LAN

**Description:** Party quests dont syncing. As i understand that because Better Questing has been updated to last version. In last version Party not sync. and another bug with armor. The point it is armor chaotically located in the quest book.  For example, electrum armor wants silver, but silver wants gold and gold armor dont coming before silver. And this happens with all armour quests.

**Steps to reproduce:** Just use updated BetterQuesting-3.5.316 ;)

**Crash log (use pastebin or issue will be closed):**

**Comment by Endur1el** [comment]
#708 and you're very unclear as to how the armors are out of order?
