### ISSUE TITLE
Quests don't sync in same party

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Cazadorsniper/PO3#715]
**Pack Version:** 
PO3-3.1.45

**Pack Mode:** 
Titan

**Singleplayer, Multiplayer, or LAN?:** 
Multiplayer, server I host myself. (Ubuntu server 18.04, fully updated and most recent java 8 version)

**Description:** 
I am in a party with a friend and some quests he completes are still locked for me. Some quests do unlock properly, others don't. It seems that when I am offline and he completes quests none of those are unlocked for me.

**Steps to reproduce:** 
Complete a quest

**Crash log (use pastebin or issue will be closed):** 
No crash log to show, since there is none.

**Comment by MathiasDeWeerdt** [comment]
@Cazadorsniper Any reason why you closed this?

**Comment by Cazadorsniper** [comment]
just need to update BQ is all.

**Comment by MathiasDeWeerdt** [comment]
> just need to update BQ is all.

Ah ok, thanks!
