### ISSUE TITLE
Extended Crafting recipe bugs in titan mode and above

### ISSUE THREAD

**Issue by Vinictus** [Cazadorsniper/PO3#716]
**Pack Version:** 3.1.45
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** First off, thank you for the great work on the pack! I'm a huge fan. Secondly, after advancing to the more difficult recipes using the 5x5, 7x7, 9x9 crafting tables from **ExtendedCrafting** I have noticed that sometimes the recipe doesn't work(as in, you receive no item and no items are consumed). First time this bug occured was with the **_Wand of Animation(Erebus)_**![Wand of animation nonbug](https://user-images.githubusercontent.com/57992275/69239333-40e77080-0b9a-11ea-9ca8-c87f02580305.PNG)
![Wand of animation bug](https://user-images.githubusercontent.com/57992275/69239373-5492d700-0b9a-11ea-8542-82ec88679bc3.PNG)
...and now it occured with the **_Imaginary Time Block(QuantumFlux)_**.
Something to note with this bug is that my save was started accidentally with the pack launched in _normal mode_ and then relaunched in _titan mode_. Saying that, I believe this is what caused the bug to occur by looking at the contents of the "Crafttweaker" text document that describes how the recipes are loaded. 

When the bug first occured I delved deeper into trying to solve it on my own which resulted in opening the script files of the pack with notepad and this is where I realised that some of the items had a script to remove the recipe first and then to add it, while others didn't. E.G **_titan_7x7.zs_**:
![BugPO3](https://user-images.githubusercontent.com/57992275/69240300-71300e80-0b9c-11ea-86c8-246e4bff2058.PNG)
Using this template, I added a "remove tag" to the recipe for the for the **_Wand of Animation_**:
![BugPO3_2](https://user-images.githubusercontent.com/57992275/69240755-70e44300-0b9d-11ea-8b61-c16c45059f1d.PNG)
Then I saved the file and launched the pack again to find out that the recipe worked.
When the same bug occured with the Imaginary Time Block, I reproduced the "solution" I had for the wand but this time in the **_titan_5x5.zs_** file, launched the pack again and "Et Voila!" it worked.

Now, I'm not 100% that the scripts was the cause of the issue or the way they loaded but if it was.. why didn't all of your "titan" scripts requiring **_ExtendedCrafting_** have a "remove tag" attached to them?

Thanks in advance!

**Steps to reproduce:**
1. Launch the pack in normal mode
2. Create a save in normal mode and enter the world.
3. Close the pack and re-launch it in titan mode
4. Open the save(now in titan mode) and attempt to craft either the Wand of Imagination or Imaginary Time Block

**Comment by Cazadorsniper** [comment]
The recipes worked only because you restarted the pack.

**Comment by Cazadorsniper** [comment]
Crystaltine had an extended crafting recipe that needed to be removed before putting a new one in.
Wand of Animation has a normal crafting table recipe that was already removed in another script, so basically the remove script you added is actually doing nothing.

**Comment by Vinictus** [comment]
I see, thank you Cazador.
