### ISSUE TITLE
Nether Crash - Liquid Seared Stone

### ISSUE THREAD

**Issue by SerDancelot** [Cazadorsniper/PO3#718]
Pack Version:  3.1.45

Pack Mode: LAN

Description: Client hangs whenever myself or players on LAN hosted server attempt to go to nether dimension through portal in our skyblock base. The server/world is pretty old. 8 months or so and we recently started playing on it again. Everything has functioned as expected but whenever we attempt to load into the nether from our portal that used to work the dimension never loads and the game needs to be force closed. Teleporting to a different part of the nether via admin command seems to work fine and the only thing near that portal I can imagine having an effect on the client is 

1) The Landia portal?
2) There are massive waterfalls of liquid seared stone covering enough space to most likely lag the client into oblivion as it calculates the block physics
![cancer](https://user-images.githubusercontent.com/52559061/69303116-9b032880-0bd0-11ea-9e01-5653e65736f1.png)

Steps to reproduce: I suppose load into Nether and fly around. It's incredibly laggy wherever there is massive waterfalls of seared stone mixing with lava.

Crash log (use pastebin or issue will be closed): Not generating crash logs. Will keep attempting to force the game to generate one. Typically the client just hangs indefinitely, never loading the nether and I have to force close.

**Comment by Cazadorsniper** [comment]
reset the nether dimension buy deleting that dimensions folder in the world, dimension ID is -1.

**Comment by SerDancelot** [comment]
Thanks, testing that now.

**Comment by SerDancelot** [comment]
Worked! Thanks. Apologies if I missed this amongst the other issues.
