### ISSUE TITLE
rf exciter not working.

### ISSUE THREAD

**Issue by Lazersgm** [Cazadorsniper/PO3#719]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.44
**Pack Mode:**
normal
**Singleplayer, Multiplayer, or LAN?:**
singleplayer
**Description:**
after placing the rf entangler with power in it and putting down a rf exciter the exciter says 0/0 rf and does not provide power. i have tried placing the rf entangler many times. just cant get this to work. 
**Steps to reproduce:**
place a rf entangler and rf exciter.
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
The RF exciter won't say they have power in them, they only transfer not store.

**Comment by Cazadorsniper** [comment]
Use exciter upgrades to increase transfer rate.
