### ISSUE TITLE
All tinkers tools at 1 durability

### ISSUE THREAD

**Issue by TKnight0** [Cazadorsniper/PO3#722]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.1.45
**Pack Mode:titan
**Singleplayer, Multiplayer, or LAN?:SP

**Description: I've just got into the tinkers part (I just started the pack) and I've tried to make a full stone mattock but it only had 1 durability which I thought might just be because its on titan mode. Then I tried to make a pick with an obsidian head and it still only has 1 durability. Am I being dumb or is this a bug?

**Steps to reproduce: Just create a tinkers tool such as a pick or mattock

**Crash log (use pastebin or issue will be closed):N/A

**Comment by Cazadorsniper** [comment]
Did you add any mods?

**Comment by TKnight0** [comment]
only optifine if you'd count that

**Comment by Cazadorsniper** [comment]
Changed the parts to something else.
