### ISSUE TITLE
Extra utilities 2 enchanter duplication bug

### ISSUE THREAD

**Issue by ios777** [Cazadorsniper/PO3#723]
Pack Version:3.1.45
I tried to enchant some diamond meshes and it gave me more meshes.
Maybe the reason is that the encahnter doesn't expect stacked items inside , but since meshes have a high emc value this bug could be a abused to produce emc. Sometime for 1 mesh used it gave me 64 enchanted version.
 
Way to reproduce: place 64 meshes inside the enchanter and use 64 nether star or lapislazuli in the second slot. also i suggest to use 64 upgrade speed (ultimate) to finish quckly. remove manually the enchanted meshes. when i used it at the beginning i got like 2/3 for 1 mesh, then the resoult insanely increased.

**Comment by Cazadorsniper** [comment]
This probably happens due to the meshes stacking, when they normally don't.
