### ISSUE TITLE
[3.1.45] Ember Rekindled Aspectus Recipe (Titan Mode)

### ISSUE THREAD

**Issue by xGarionx** [Cazadorsniper/PO3#724]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.1.45**
**Pack Mode:Titan**
**Singleplayer, Multiplayer, or LAN?:Mulitplayer**

**Description: Rekindled Aspectus using Ember Shard + 200 mb liquid metal. However ingot is 144mb **

**Steps to reproduce: Check Recipe and roll eyes**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I don't the issue here.

**Comment by xGarionx** [comment]
For a 'wasteless' recipe you need 144 mb (1 ingot) x 200 mb (1 ingot 3 nuggets and 8 mb liquid) = 
28800 mb (200 ingots) 
and i didnt see any recipes that would require these amounts of aspects, so it just becomes a waste of ressources for no apperent reason.
