### ISSUE TITLE
Grains of Infinity in Ender Crafter

### ISSUE THREAD

**Issue by Hallowizer** [Cazadorsniper/PO3#725]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Garden of Glass
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** The quest book says grains of infinity can be obtained by burning bedrock or with an ender crafter recipe, but there is no ender crafter recipe.

**Steps to reproduce:** Reach the "Grains of Bedrock" quest, then open it to see the text. To see the recipe not there, search "Ender Crafter" in JEI, and right click the ender crafter.

**Crash log:** Nothing crashed.

**Comment by Cazadorsniper** [comment]
Garden of glass isn't a packmode

**Comment by Cazadorsniper** [comment]
I'm assuming you're on Titan mode not normal mode, The recipe exists for normal not for Titan.

**Comment by Hallowizer** [comment]
Where do you see the mode?

**Comment by Cazadorsniper** [comment]
In the config or /packmode

**Comment by Hallowizer** [comment]
I'm actually on normal mode.

**Comment by Cazadorsniper** [comment]
might have removed it then
