### ISSUE TITLE
Discord Suite crash

### ISSUE THREAD

**Issue by Angelos33** [Cazadorsniper/PO3#726]
The game crashes while loading the mods. The crash report says it's netherexs' mod fault but at the loading screen of the game when it crashes, it shows that it gets stuck at the discord suite mod.
Removing it seems to solve the problem.
I looked for a solution and found a similar issue someone else had but it was closed without a specific fix. That's why i make a new issue to help others and to report the problem.
Sorry for not posting a crash report, didn't have a lot of free time
Here it is: https://pastebin.com/argMWGCN

**Comment by Cazadorsniper** [comment]
Can't determine what the issue is if no crash report.

**Comment by Cazadorsniper** [comment]
This issue was caused by netherex

**Comment by Angelos33** [comment]
Should i report it to NetherEx mod developer then?
