### ISSUE TITLE
Ore Lava Crystal

### ISSUE THREAD

**Issue by occelot666** [Cazadorsniper/PO3#728]
I am unable to find Ore Lava Crystal anywhere so afer checking the config it says it is disabled in all worlds is this correct.

https://pastebin.com/KQ14yj92

**Comment by Cazadorsniper** [comment]
Have you checked the nether?

**Comment by occelot666** [comment]
Yes I have vein mined the nether for about 2 hours and nothing that's why I
checked the config which says nether spawn false was wondering if that was
correct

**Comment by Cazadorsniper** [comment]
Have you checked the magma blocks?
