### ISSUE TITLE
All The Sudden, I am deaf.... Is Steve loosing his hearing?

### ISSUE THREAD

**Issue by PerksPrisoner** [Cazadorsniper/PO3#729]
Journal Entry 11/28/2019

Today is the 28, Thanksgiving for the Americans..... I fear that I am loosing my hearing, perhaps I contracted a rare disease in my travels to these dimensions, maybe some of the strange food or animals I have consumed. Perhaps something with the cooked apples, I have ate several stacks of them over the past months. But I find while I am standing idle for any time while day dreaming or just completely asleep I stop being able to hear my surroundings unexpected. Perhaps I should study this more. But if I go to sleep and awake again all is fine which seems like it is days at a time, perhaps fatigue!

**OK Just in case the animated bug report wasn't clear:  When I leave my PC while the game is running in the pause menu or even at the title screen, the sound stops entirely and I have to restart the entire MC from the launcher. Spend the 7 mins loading the mods again to fix it. I have searched around but I can't seem to find anything titled what makes sense to my issue.**

**Comment by Cazadorsniper** [comment]
Might want to check your sound driver or something on your pc, just in case. This doesn't happen to me, I just crash instead lol.

**Comment by PerksPrisoner** [comment]
Yea. I don't crash much. Just weird, it is just this that does it. Not sure why! #WaitingSimulator #ItsNotABugIfTheWholeThingStopsWorking
