### ISSUE TITLE
Reward Suggestions (Flux-Infused JetPlate/Oxygen Mask)

### ISSUE THREAD

**Issue by martinschuberteu** [Cazadorsniper/PO3#73]
Pack Version: 3.0.38

Description: I noticed two instances where I had to go through armor progression again to craft items, that felt unnecessary to me: 

1.) The Flux-Infused JetPlate is consumed in armor progression, but you still need it in dimensions that have flight disabled (at least I was not able to fly with draconic armor). 

2.) An iron helmet is required for the Oxygen Mask (Galacticraft)

I feel like the Flux-Infused JetPlate should be a reward or should not be consumed in armor progression and you should get an iron helmet or the Oxygen Mask as a reward in a Galacticraft quest.

Steps to reproduce: N/A

Crash log : N/A

**Comment by Cazadorsniper** [comment]
I see no issues with this and already made a feature request regarding the flight in specific dimensions.
