### ISSUE TITLE
moo fluid cows not spawning

### ISSUE THREAD

**Issue by irondragon12** [Cazadorsniper/PO3#730]
**Pack Version:** 3.1.45
**Pack Mode:** survival
**Singleplayer**

**Description:**
I've been going around the world and havent seen a single moo fluid cows, but i have seen a ton of normal cows.
**Steps to reproduce:**
start a new world?
**Crash log (use pastebin or issue will be closed):**
none since it isnt crashing

**Comment by irondragon12** [comment]
also are rock crystal ores supposed to spawn in the overworld now?

**Comment by irondragon12** [comment]
plus are blood moons gone?

**Comment by Cazadorsniper** [comment]
Try Lost Cities dimension.
Yes they are suppose to spawn in the overworld.
Bloodmoons are gone and have been gone for a long time.

**Comment by irondragon12** [comment]
what is lost cities dimension

**Comment by irondragon12** [comment]
nvm

**Comment by irondragon12** [comment]
nvm again. i dont know how to get there.

**Comment by irondragon12** [comment]
nvm again. i found a vid that shows it
