### ISSUE TITLE
Internet too slow

### ISSUE THREAD

**Issue by Mexld** [Cazadorsniper/PO3#732]
**Pack Version:** None
**Pack Mode:** None
**Singleplayer, Multiplayer, or LAN?:** None

**Description:** Can't download modpack. I assume my internet is too slow. Looking for a workaround or bypass.

**Steps to reproduce:** Running computer off tethered phone data, try downloading modpack.

**Crash log (use pastebin or issue will be closed):** Timeout attempting to download: https://edge.forgecdn.net/files/2823/588/PO3-3.1.45.zip

**Comment by Mexld** [comment]
Tried downloading the PO3-3.145 file manually and extracting it to a custom profile. Didn't work. only loads up 7 mods and I'm pretty sure its missing a lot of files.

**Comment by Cazadorsniper** [comment]
I can't help with this at all.

**Comment by Mexld** [comment]
I figured. Was hoping that there would be a way to download the modpack outside twitch and then install it to twitch but from my testing its not going to work.
