### ISSUE TITLE
Quest updating, Multiplayer

### ISSUE THREAD

**Issue by Call-Ep3** [Cazadorsniper/PO3#733]
So me and my friends has been playing PO3 recently and the quest book doesn't update without the people being online on the server that are in the party. For example: My friend made a resonant furnace and placed it down, I then connected and the quest had not been complete. In this case its an easy fix for us cause I just pick it up and get it done. But my other friend joined a little bit later and he is behind on 20-30 quests and of what we've found they has to be redone for him to claim them

**Comment by pacman1983** [comment]
I'm having the same issue. We just updated the server from 3.0.42 to 3.0.45a. We also updated the questing book with the '/bq_admin default load' commands. 
 
For us we have to be on at the same time for us both to get the quests.
