### ISSUE TITLE
Questbook Iota chapter

### ISSUE THREAD

**Issue by itayporezky** [Cazadorsniper/PO3#734]
If you take a look at the armor chapter in PO3 latest update, the armors are in the wrong order.
For example you have tin armor and the quest after that is electrum armor which is actually 3-4 steps after tin armor.

Have a nice day

**Comment by itayporezky** [comment]
Welp, last time i try to help with this pack.
This issue is real and others confirmed it in my server.

**Comment by itayporezky** [comment]
@Cazadorsniper

**Comment by Cazadorsniper** [comment]
have you tried doing /bq_admin default load?

**Comment by itayporezky** [comment]
not a server i own: PO3.DIRTCRAFT.GG

**Comment by itayporezky** [comment]
you mean its something the server owner did?

**Comment by Cazadorsniper** [comment]
then ask the server owner to do that command, armor progression was adjusted to make better sense.

**Comment by itayporezky** [comment]
owner said he tried the command and nothing changed

**Comment by Cazadorsniper** [comment]
replace the server config with the client config

**Comment by Cazadorsniper** [comment]
then try command again.
