### ISSUE TITLE
Crash when crafting compressed cobble?

### ISSUE THREAD

**Issue by semkreuze** [Cazadorsniper/PO3#735]
Hello everyone! 

I ran into a crash when attempting to create compressed cobble... Here is the log of the crash https://paste.dimdev.org/tefazuluhe.mccrash

Also, I have the mods advised in this reddit post installed (except for optifine) https://www.reddit.com/r/feedthebeast/comments/alcl6g/how_to_play_po3_on_a_laptop/

If anyone could have a quick look, I would be very grateful for your time!

Kind Regards,
semkreuze

**Comment by Cazadorsniper** [comment]
Are you using transfer nodes? If so, try using worldedit or something like that to remove any transfer nodes.
