### ISSUE TITLE
Crash when checking Mekanism in JEI

### ISSUE THREAD

**Issue by FlyingThunder** [Cazadorsniper/PO3#736]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: PO3-3.1.45
**Pack Mode: Titan
**Singleplayer, Multiplayer, or LAN?: Multiplayer

**Description: Entered "Mekanism" in JEI, game crashed

**Crash log (use pastebin or issue will be closed):
https://pastebin.com/4rr9fY73

detailed error log:
https://pastebin.com/3BsVsuCE

**Comment by Cazadorsniper** [comment]
That is a Java crash, I can't do anything to fix that.
Just restart the pack and it should work fine.
