### ISSUE TITLE
Game crashed after breaking a ambered creature in erebus dimension.

### ISSUE THREAD

**Issue by irondragon12** [Cazadorsniper/PO3#738]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** survival
**Singleplayer, Multiplayer, or LAN?:**
singleplayer
**Description:**
i veinmined a amber cluster thingy in the erebus and saw a butterfly like thing in an amber, broke it, and game completely crashed.
**Steps to reproduce:**
i dont know how to reproduce it. it might have just been the mob i released.
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/QJw9rePs

**Comment by Cazadorsniper** [comment]
I think that is just a random crash because I can't reproduce it.

**Comment by Cazadorsniper** [comment]
Literally went around the Erebus breaking Amber with mobs in them.

**Comment by irondragon12** [comment]
k thx

**Comment by BrianEdmonds** [comment]
Breaking amber crashed on me too. I don't recall anymore if it was just a client crash, or my server crashed as well, but I think it may have been just client. The item that was in the amber was in my inventory after I restarted the game. I just figured it was a weird ViveCraft interaction.
