### ISSUE TITLE
Recipe doest work how do fix it ?

### ISSUE THREAD

**Issue by Thomsn22** [Cazadorsniper/PO3#739]
**Pack Version:** 
3.1.45
**Pack Mode:** titan
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
Cant craft the piston recipe is in but i cant get the item
**Crash log (use pastebin or issue will be closed):**
no crash caused
 Is there a way i can fix recipes myself when i have access to the server data?

**Comment by Thomsn22** [comment]
![Piston](https://user-images.githubusercontent.com/31596641/70906583-050fc180-2007-11ea-913d-953929181b8f.jpg)

**Comment by Cazadorsniper** [comment]
Make sure the client and server packmodes are the same.

**Comment by Thomsn22** [comment]
Thank u ill try

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Thomsn22** [comment]
Changing gamemode in Server/Client did work, but play titan did not work with server, so hope i some recent Time, it will be possible to make an Command like in Po2

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Cazadorsniper** [comment]
That is impossible for 1.12.2.

**Comment by Thomsn22** [comment]
Thank you for the answer, nice to know

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
