### ISSUE TITLE
Can't see smart cables channels

### ISSUE THREAD

**Issue by BloodWolf89** [Cazadorsniper/PO3#74]
**Pack Version:**
3.0.38
**Description:**
I am not able to see the channels when looking at smart cables. It is enabled and still nothing.
**Steps to reproduce:**
Look at a smart cable?

**Comment by Zapstur** [comment]
I'm not running into the same issue.  Do you by chance have Optifine, or some Texture Packs or Shaders installed?  If so, try moving those files out of the install directory, and see if that solves the problem.  If it does, please try to narrow down which of those three types of things is the problem, and say so here.  That way other people won't have to ask the same question.

Of course, if that doesn't solve the problem, just say so here.

**Comment by Cazadorsniper** [comment]
make sure Hwyla/wawla is on the server and client
