### ISSUE TITLE
Every tier above basic universal cables don't show up in ME system with transmutation chamber

### ISSUE THREAD

**Issue by Inurta** [Cazadorsniper/PO3#741]
I have my ME system hooked up to the transmutation chamber so I can pull items out using EMC and everything seems fine except for these items.  They include Advance, Elite, and Ultimate Universal Cables from Mekanism.  If I disconnect the chamber from the system, I can make them, put them in the system, take them out, etc. But when I try to put the cables in the system to learn the recipe or even just put them into the transmutation tablet makes them disappear with nothing happening.  The transmutation isn't learned and when the system method is used, the item just gets deleted.  Strangely enough, the basic cables work just fine and I can take them out and the EMC and all of that works.  Only the cables above them don't.

**Comment by Cazadorsniper** [comment]
The cables are the same block just separated by nbt data, there is nothing I can do about this.

**Comment by Inurta** [comment]
Ah I see, thanks anyway!
