### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RaiseMod** [Cazadorsniper/PO3#745]
Project Ozone 3
Version 3.1.45
Singleplayer mode

While starting the pack from the launcher,the game opens for a few second and closes causing the error reported in the image

![Screenshot_7](https://user-images.githubusercontent.com/59030960/71118902-45269e00-21d9-11ea-9255-64caf340dda0.png)

**Comment by RaiseMod** [comment]
https://pastebin.com/Kw89CevN

**Comment by Cazadorsniper** [comment]
Can you pastebin the crash report? All that paste tells me that is failing to I guess download something.
Are you using twitchapp?

**Comment by RaiseMod** [comment]
http://pastebin.com/UM7CE0Yd
Yup,i'm using twithcapp and launching the game with the JAR launcher option beacouse with the native launcher didn't start

**Comment by Cazadorsniper** [comment]
-Xmx3840m, give it more ram in the twitchapp settings
