### ISSUE TITLE
Dank/null AE2

### ISSUE THREAD

**Issue by goldengate2** [Cazadorsniper/PO3#746]
# Use the search function before reporting to see if the issue has been reported before.
**3.1.45:**
**normal:**
**Singleplayer:**

**/dank/null doesn't leave the AE2 system after accidentally adding it to the system:**

**Added a /dank/null to a AE2 system with an ME controller:**

**no crashes:**

**Comment by Cazadorsniper** [comment]
Try using an export bus then use a fuzzy card upgrade to filter it out.

**Comment by BrianEdmonds** [comment]
When I accidentally stored my /dank/null, I did this, and it worked. I had to craft another to match against, but that wasn't terribly hard when you're at EMC stage. Also a perfectly fine time to just cheat one in if you can. (Then throw it away, of course. :)

Anyone know if there's an open or fixed AE2 bug for this issue?

**Comment by Cazadorsniper** [comment]
I think P455w0rd is aware of this issue.
