### ISSUE TITLE
VoidCraft Avatar of Herobrine Fight Crash

### ISSUE THREAD

**Issue by Jetlaw** [Cazadorsniper/PO3#747]
[crash-2019-12-20_19.46.22-server.txt](https://github.com/Cazadorsniper/PO3/files/3989980/crash-2019-12-20_19.46.22-server.txt)

Avatar of Herobrine fight in VoidCraft crashes in the 3rd phase - The one where it summons Wither Skelebobs and TNT crates. It never reaches the point where you can right click on the NPCs, so I think this is crashing it.

Does this have something to do with VoidCraft being a dead mod now as per the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/voidcraft)?

**Comment by Cazadorsniper** [comment]
You don't need to "fight" any of those bosses in that dimension. They can be ignored.

**Comment by ZeroMemes** [comment]
>Does this have something to do with VoidCraft being a dead mod now as per the CurseForge page?

Yes, and the owner of it decided to completely delete it from GitHub. As a result, the mod is no longer able to pull the file listing the various ghosts that appear during the fight.

## 1: Create a [gist](https://gist.github.com/)
Have it be formatted as such: (This can be any set of usernames and Minecraft UUIDs),
```
name1=uuid1
name2=uuid2
...
```

Then we have to take the Raw Gist URL and modify the bytecode of the mod using [Cafebabe](https://github.com/GraxCode/Cafebabe) ...

## 2: Open the VoidCraft jar in Cafebabe
Use the `File > Open Jar File` tab along the top bar.

## 3: Locate the class that needs to be modified
![image](https://user-images.githubusercontent.com/24485393/72233449-16f46e00-358d-11ea-8d55-50df42330ebb.png)

## 4: Select `void run()` in the method view, and press "Edit Code"
![image](https://user-images.githubusercontent.com/24485393/72233503-5ae77300-358d-11ea-83e6-2fba64447f34.png)

## 5: Scroll down until you find the `ghost.properties` URL

Ensure that it is selected

![image](https://user-images.githubusercontent.com/24485393/72233528-85393080-358d-11ea-9186-b0ac5285b6f0.png)

## 6: Modify the URL to be the Raw Gist URL

The field to modify the value is in the back window where `void run()` was originally selected.

![image](https://user-images.githubusercontent.com/24485393/72233580-ccbfbc80-358d-11ea-8cf0-1205b0b3979b.png)

## 7: Close the window and save
Use the `File > Save Jar File` tab along the top bar.
