### ISSUE TITLE
Massive TPS Lag if 2 players are Online

### ISSUE THREAD

**Issue by Julien310** [Cazadorsniper/PO3#748]
Pack Version:3.1.45
Pack Mode:Survival, Botania garden of Glass
Multiplayer

If i play alone on the server the tps is very good, but if there is a second player then the tps drops under 8. Tried many things. No farms there no automation.

![2019-12-20_23 33 49](https://user-images.githubusercontent.com/59101982/71296968-d173c500-2381-11ea-971d-fe98f33facf6.png)
![2019-12-20_23 34 02](https://user-images.githubusercontent.com/59101982/71296971-d5074c00-2381-11ea-85a3-33ebca43e7c3.png)

**Comment by Cazadorsniper** [comment]
Are there any added mods?
Are you using any sponge plugins?
Does the same thing happen when the other player is alone and you join?
Have you tried restarting the server?

**Comment by Julien310** [comment]
No, we didnt added any mods.
No, we didnt added any plugins.
Yes, if he is alone server has around 16TPS.
Yes daily Autorestart.

**Comment by Cazadorsniper** [comment]
Then I'm not sure what would cause that.

**Comment by Cazadorsniper** [comment]
Try removing more machines.
