### ISSUE TITLE
install disappears

### ISSUE THREAD

**Issue by crunchynut609** [Cazadorsniper/PO3#75]
while installing the pack on the twitch app, it disappears mid way through and then I have to try and reinstall and it does the same thing. at the moment I have not successfully downloaded the modpack and I have been trying to figure out why all day.

please let me know what you think is the issue. but ever since the update for the twitch app I haven't successfully downloaded ANY modpack at all.

**Comment by Zapstur** [comment]
Just searching online, I think I may have found a solution:  Try running Twitch as an Administrator, and then try downloading the modpack again.  If that works, feel free to say so and then close the thread.  If it doesn't work, then there has to be a different solution.

**Comment by crunchynut609** [comment]
I have no idea how to run twitch as an admin

**Comment by Zapstur** [comment]
> I have no idea how to run twitch as an admin

Right-click on the shortcut when Twitch isn't running, and select the "Run as Administrator" option.  That is for Windows, dunno how to do it with MacOS or Linux

**Comment by crunchynut609** [comment]
so I've tried that and it still isn't working. I can install other modpacks like stone block 2 and stuff but project ozone seems to be the only one I'm having trouble with.

**Comment by Cazadorsniper** [comment]
this may require twitchapp support
