### ISSUE TITLE
Enderium Upgrade #183 No Reward

### ISSUE THREAD

**Issue by Speecker** [Cazadorsniper/PO3#750]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** SP

**Description:** As the title says the Quest "Enderium Upgrade #183" on Page Eta is not giving you any kind of reward. Guess it is supposed to give you 5 RAK else its meh if its intended to NOT give reward ... .

**Steps to reproduce:** If its a Bug you may reproduce it by directly finish/craft the Conversion before handing in the quest.

**Crash log (use pastebin or issue will be closed):** No Crash occured.

**Comment by Cazadorsniper** [comment]
Already fixed.
