### ISSUE TITLE
game crashing when loading map

### ISSUE THREAD

**Issue by JustprogramerMaximvaluevich** [Cazadorsniper/PO3#751]
Pack Version:3145
Pack Mode: titan
Singleplayer, Multiplayer, or LAN?:singleplayer
Description:
the game loading normal but when I trying to create new world in singleplayer mode it crashed 
p.s. I didn't add or deleated mods from mudpack and in config I just changed to titan mod I tryed to create a new GoG world.
and I playing on last version of modpack.
last I wanted to say I use 9gb memory for minecraft
Steps to reproduce: create new world
Crash log (use pastebin or issue will be closed): https://pastebin.com/6LzY3y7Z

**Comment by Cazadorsniper** [comment]
Did you add any mods?
Have you tried reinstalling the pack?

**Comment by JustprogramerMaximvaluevich** [comment]
i didnt add any mods and tried reinstall the pack and it didn't helped and morever on other version of java i tryed to run and it didn't helped too

**Comment by Cazadorsniper** [comment]
Try updating Java and making sure its 64bit not 32.

**Comment by JustprogramerMaximvaluevich** [comment]
I playing on java 8 231 x64 tried reinstall it and it didn't help

**Comment by Cazadorsniper** [comment]
Maybe try turning off animations in the foamfix config.
Make sure anti-virus software and windows firewall aren't blocking it from running.
Running out of ideas what it could be.

**Comment by JustprogramerMaximvaluevich** [comment]
hi I fix it I was needed to run game with jdk's jre not original jre and also I need allocate less memory to not get out of memory exception also  thank you for creating this modpack
