### ISSUE TITLE
Modpack won't even run past the launcher

### ISSUE THREAD

**Issue by raymondlucifer66** [Cazadorsniper/PO3#752]
All it says is

"ERROR

Game Crashed

An unexpected issue occurred and the game crashed. We're sorry for the inconvenience."

**Comment by Cazadorsniper** [comment]
Then there is a crash-report.

**Comment by raymondlucifer66** [comment]
okay here it is
[2019-12-21-5.log](https://github.com/Cazadorsniper/PO3/files/3991725/2019-12-21-5.log)

**Comment by Cazadorsniper** [comment]
Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.

Reinstall Minecraft, not the pack, Minecraft itself.

**Comment by raymondlucifer66** [comment]
ill let you know id that works

**Comment by raymondlucifer66** [comment]
Alright it took some ingenuity on my part but I got it working by redownloading forge on my normal mc and yoinking the directory and all the mods from the twitch launcher and putting i into a different configuration on the mc launcher
