### ISSUE TITLE
Ender IO - Thermal Expansion Incompatibility Crash

### ISSUE THREAD

**Issue by BeastlyNinja11** [Cazadorsniper/PO3#753]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.1.45**
**Pack Mode: Titan**
**Singleplayer, Multiplayer, or LAN?: Multiplayer**

**Description: The game crashes upon trying to break a Simple-tier EnderIO machine with a Crescent Hammer.**

**Steps to reproduce:
1. Get a crescent hammer
2. Place down a Simple Alloy Smelter
3. Shift-Click the Alloy Smelter with the Crescent Hammer**

**Crash log (use pastebin or issue will be closed):** pastebin.com/sMdLGXm8

**Comment by Cazadorsniper** [comment]
I can't reproduce this, so it might of been fixed during an update.
