### ISSUE TITLE
ExtraCells2 - 1024k  and 4096k fluid cells dont fill 

### ISSUE THREAD

**Issue by amanzno** [Cazadorsniper/PO3#754]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  3.1.45
**Pack Mode:** TITAN
**Singleplayer, Multiplayer, or LAN?:** SINGLEPAYER

**Description:**
applied energistics 2 don't recognize 1024k and 4096k fluid cells as valid containers to import fluids. 

**Steps to reproduce:**
put some fluids cells in ME DRIVE and import fluids, only 1024k and 4096k fluids cells don`t work.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
I can't fix this and the mod this comes from is not really being worked on.
