### ISSUE TITLE
Portal to Lost Cities not working

### ISSUE THREAD

**Issue by IyaTaisho** [Cazadorsniper/PO3#755]
Pack Version: 3.1.45
Pack Mode: Skylands
Singleplayer, Multiplayer, or LAN?: Single player

Description: I followed the steps to create a portal to The Lost Cities, but nothing happens.

**Steps to reproduce:

1. Set 2 diamond blocks.
2. Put a bed down on the diamond blocks.
3. Surround bed by skeleton skulls.
4. Step up onto the end of the bed and right click.

And then nothing...  I stood there for a few minutes but nothing happened.

I did research it and someone said use emerald blocks instead.  Another suggestion was use wither skeleton skulls.  One other suggestion was wait until dark and click the bed.  None of the above mattered.

**Comment by Cazadorsniper** [comment]
lava crystal blocks.

**Comment by ziroau** [comment]
totally useless resolution
