### ISSUE TITLE
Universal Cables (Energy) - Mekanism (EMC and Transmutation Tablet)

### ISSUE THREAD

**Issue by Terminex19** [Cazadorsniper/PO3#756]
**Pack Version:** PO3-3.1.45
**Pack Mode:** Normal Mode
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** While making the Universal cables (for energy) from Mekanism, i noticed that the 'Elite', 'Advanced' and 'Ultimate' versions, besides having the same amount of emc, they're not saving on the transmutation tablet individually, only the basic universal cable is able to stay on the saved recipes.

**Steps to reproduce:** Made the 'Basic Universal Cable', then procedeed to do the 'Advanced Universal Version', afterwards made the 'Elite Universal Cable' and finally 'Ultimate Universal Cable'. Tried saving the different versions on transmutation tablet (portable) but only the basic tier version of it was saved, the rest of them weren't there when tried to look for them by name nor by page.

**Comment by Cazadorsniper** [comment]
They are the same block with different nbt data, I can't fix that.

**Comment by Terminex19** [comment]
Thanks for taking the time to reply. Sorry for being a noob :c
