### ISSUE TITLE
crashing when loading world, little knowledge so need help

### ISSUE THREAD

**Issue by BoontyBoxCreator** [Cazadorsniper/PO3#757]
https://pastebin.com/zsxfDXpT

singleplayer

load game, try to load world, crashes after loading terrain ends

on version 3.1.45 titan mode

not really sure what's going on, maybe a chunk loading issue

**Comment by Cazadorsniper** [comment]
What were you doing before it crashed?

**Comment by Cazadorsniper** [comment]
You could also try updating Java.

**Comment by BoontyBoxCreator** [comment]
just loading the world itself, nothing to do before that

updated java, tried again, same thing, pack loads fine, world gets to "loading world, building terrain" and then then it crashes, same log

**Comment by BoontyBoxCreator** [comment]
https://pastebin.com/LRT2t5tY

**Comment by Cazadorsniper** [comment]
According to the crash-report you haven't updated Java, Did you update/remove/added any mods? Can you give me the latest.log from the logs folder?

**Comment by Cazadorsniper** [comment]
Also does it crash in a new world?

**Comment by BoontyBoxCreator** [comment]
Not sure how to update java in twitch launcher, only have options for 1.8.0.51 64 bit native launcher, which is what i am on now, and 1.8.0.231 32 bit on JAR launcher, which makes me install minecraft and everything else from scratch. I assume updating java would fix it, but even java on my pc says it is updated to the latest version.

 No mods have been edited/updated/removed/added, only thing changed in config file was from normal to titan mode.

Latest log: https://pastebin.com/DLDKMV5V

Loaded a new world up, played for 10 minutes, didn't crash at all.

**Comment by Cazadorsniper** [comment]
That log is the one where it has crashed before you made a new world right?
On twitchapp, switch to Jar Launcher then change Java version. Reinstall Java to get the 64 bit version or you'll have ram issues.

**Comment by Cazadorsniper** [comment]
Also the new world worked fine, which means what were you doing in your old world before it crashed.
Did you connect an electric furnace from Galacticraft to a power source for example?
