### ISSUE TITLE
Launch crash at 2/7

### ISSUE THREAD

**Issue by NicolaiLundP** [Cazadorsniper/PO3#758]
Pack Version:3.1.45
Opened in jar launcher from twitch

Description: I tried to load the game but crashed though preinitialsation. 2/7

Gave it 8G´s of ram
Java Version: 1.8.0_231
graphics card updated

[crash-2019-12-27_03.25.50-client.txt]
(https://github.com/Cazadorsniper/PO3/files/4003898/crash-2019-12-27_03.25.50-client.txt)

Thank you

**Comment by NicolaiLundP** [comment]
https://pastebin.com/2AQEfny8

**Comment by Cazadorsniper** [comment]
Can try removing Patchouli then adding it back later.

**Comment by NicolaiLundP** [comment]
Isnt that important? i tried to remove it and start it up, but i just got an internal error when:
 . i finally opened the game
 . created a world
 . and tried to open the book :)
https://pastebin.com/XNpnvjTb

**Comment by Cazadorsniper** [comment]
What book are you opening?

**Comment by NicolaiLundP** [comment]
OpenComputers manual.

Its funny that if i use native launcher to startup the PO3 it just not responding at  1/7 Mekanism

**Comment by Cazadorsniper** [comment]
You can try reinstalling the pack.

**Comment by NicolaiLundP** [comment]
Wich pack?

**Comment by Cazadorsniper** [comment]
Yeah, this is the PO3 issue tracker.

**Comment by NicolaiLundP** [comment]
i can try again, but i have done this about 8 times now.

**Comment by Cazadorsniper** [comment]
also don't open the book.

**Comment by NicolaiLundP** [comment]
I can live with no manuals in the game. They might be on a website anyway. :) 
I think its all manuals that gets it to crash. i used cheat to try opening other manuals.

**Comment by NicolaiLundP** [comment]
Find out that after i reinstalled my pc i finally work with all the mods. Dont know what got wrong

**Comment by Cazadorsniper** [comment]
Probably some random corruption.
