### ISSUE TITLE
Reward Suggestion rewards tab

### ISSUE THREAD

**Issue by Punkenstein** [Cazadorsniper/PO3#76]
I think you should be able to buy the swords again in case you lose it or delete it.

**Comment by Zapstur** [comment]
You can already do that.

**Comment by Punkenstein** [comment]
may i ask how because i have tried it and can not seem to figure it out

**Comment by Zapstur** [comment]
On the rewards tab, after you buy any of the rewards, it completes normally.  After that, close the Quest Book, reopen it, got back to the Rewards Tab, and look at the item you just bought (not just the swords).  If you have the requirements (some RAK and 100 Blaze Rods for the first one), the quest should appear blue, in other words, ready to complete (again).

**Comment by Punkenstein** [comment]
it does not for me here is a screen shot and i have plenty of both for the tier 1 sword.
![2019-03-03_09 36 48](https://user-images.githubusercontent.com/37779138/53697580-3d0b8800-3d98-11e9-9e61-e2c76225bde4.png)

**Comment by Zapstur** [comment]
That doesn't look at all like what I have on my end (can't provide a screenshot due to being on a different system).  There should be at least twice that number of options, most of them being Ability Totems (about 20 (twenty) of them, not 2 (two)

**Comment by Zapstur** [comment]
That said, did you start playing on an earlier version of the pack?  If so, you might want to enter the following command:

/bq_user refresh

If that solves the issue, then all's good.

**Comment by Punkenstein** [comment]
yes i did and it must has something to do with the server i went into single player and it has a lot more stuff in it. So i will have to talk to the server owner and see if he can figure it out.
