### ISSUE TITLE
Crescent Hammer Shift-Breaking Simple SAG Mill Causes Client to crash

### ISSUE THREAD

**Issue by CitrusSuicide** [Cazadorsniper/PO3#760]
I shift right clicked a simple sag mill (Ender IO) with a crescent hammer (Thermal Expansion) and it caused my client to crash. I'm not sure if there were items in the SAG mill or not but it's very likely there were.

Upon reentering the world I see that the side I hit was configured to input items so I'm thinking trying to break the block and set a face to input was the cause.

Making this post in case others have the same issue. Let me know if you'd like more info or if I should post it elsewhere. For now I'll just remove the block with a pickaxe

Crash log below
https://pastebin.com/f8ftjmsP

**Comment by Cazadorsniper** [comment]
I believe this is fixed since I don't experience it when I tried.

**Comment by CitrusSuicide** [comment]
Interesting. I should mention that I'm running version 3.1.45 of the modpack
