### ISSUE TITLE
Quest Completion Sound

### ISSUE THREAD

**Issue by Ticskter** [Cazadorsniper/PO3#761]
ok i know this may not be the proper place for this but i have searched for a few hours now and cant find any information on this.
Is there a way to change the volume of the Quest Completion Sound within the game via mod options? if there isnt a way to do this could it be possible to "request" this option? 
i know i can modify the .ogg file myself, which i have done, however like an idiot i didnt write down the file location before i moved it and edited it. what i did to find the file was used the twitch launcher to open the file folder for Project Ozone 3 and searched for ",ogg" i can no longer find the file since i removed it and placed in on the desktop. would anyone here be willing to do this same search and post what the file patch is so i can replace my edited, more quiet .ogg file into the proper location please?
Again i know this is more of an issue reporting forum, but now that i dont have the completion sound in my mod pack folder i get a really lengthy completion sound that is pretty damn weird to say the least.

**Comment by Cazadorsniper** [comment]
PO3\resources\minecraft\sounds\music\menu

**Comment by Cazadorsniper** [comment]
sorry its actually: PO3\resources\minecraft\sounds\records

**Comment by Ticskter** [comment]
awesome thank you Cazadorsniper!!

**Comment by DatRatVS** [comment]
yeah thanks, i was willing to turn that up, it is amazing.
