### ISSUE TITLE
Launcher crashes when I press the play button

### ISSUE THREAD

**Issue by Arthurthecool** [Cazadorsniper/PO3#762]
Pack Version: PO3-3.1.45
Pack Mode = normal
**Singleplayer, Multiplayer, or LAN?:**
^ none of the above

Description: I turn on the launcher and when pressing play I have to wait for some seconds for it to kick me back into the launcher and tell me it crashed without details. I have reinstalled it several times and also gave it 11GB ram. But nothing seems too work 

https://pastebin.com/w70ADyFT

**Comment by Cazadorsniper** [comment]
Does it do this with other packs?

**Comment by Arthurthecool** [comment]
No, never

**Comment by Cazadorsniper** [comment]
If it crashed can you give me the crash-report?

**Comment by Arthurthecool** [comment]
Isent it what I did with the pastebin stuff?

**Comment by Cazadorsniper** [comment]
that "looks" like a log not a crash-report.

**Comment by Arthurthecool** [comment]
lmao true, but could we like screenshare and stuff xd 
Makes things prob easier

**Comment by Cazadorsniper** [comment]
All you need to do is pastebin the crash-report.

**Comment by Arthurthecool** [comment]
I couldn't find no crash report anywhere in the files in the PO3 folder but I can send the logs same is this https://pastebin.com/cYGUcyhY

![explorer_vwQE7tW3nh](https://user-images.githubusercontent.com/59321431/71579016-d90e3900-2afa-11ea-946c-dd0d0352eebd.png)
And heres a picture of the PO3 file

**Comment by Cazadorsniper** [comment]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.

Just need to reinstall the minecraft portion of the Twitchapp, or replace the 1.12.2.jar in the Curse\Minecraft\Install\versions\1.12.2 folder.

**Comment by Arthurthecool** [comment]
Yea did that, tourns out that it was the launcher from twitch that were the problem. Thanks for all the help :D
