### ISSUE TITLE
Server won't start after updating from 3.1.44 to 3.1.45

### ISSUE THREAD

**Issue by Mr-Bobby** [Cazadorsniper/PO3#763]
Pack Version: 3.1.45 server
Pack Mode: garden of glass/botania-skyblock, easy
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description:  I'm hosting a multiplayer project ozone 3 server for my friends using shockbyte but after I just updated the server to 3.1.45 it won't start anymore. The server crashes as i try to start it, when it starts it disables the command terminal for some reason, saying that it is an unsupported environment. Then eventually it comes up with warnings about the mods being newer than the world save, then an error about the armorplus:arena biome being missing and then the browser freezes and I have to refresh, but even after I refresh it won't go any further and is stuck at that error. Please help.

Steps to reproduce: kept journey map, world save, and server properties files from version 3.1.44, and replaced rest of files with updated 3.1.45 files, then start server.

Crash log (use pastebin or issue will be closed):
[debug.log](https://github.com/Cazadorsniper/PO3/files/4010336/debug.log)

**Comment by Cazadorsniper** [comment]
Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**Comment by Mr-Bobby** [comment]
Thanks, that fixed it. 👍🏼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
