### ISSUE TITLE
Project Ozone 3 A New Way Forward error

### ISSUE THREAD

**Issue by hellsystem666** [Cazadorsniper/PO3#767]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** Project Ozone 3 A New Way Forward
**Singleplayer, Multiplayer, or LAN?:**

**Description:**
got ist from twitch and when i pres play it gave me the lower named error

**Steps to reproduce:**
just got it from twitch and pressed play. 

**Crash log (use pastebin or issue will be closed):**

Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\Robin\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

**Comment by Cazadorsniper** [comment]
Could press the link to download that file, this is not the pack at all, its just Twitchapp having its own issues.

**Comment by marvnrawley** [comment]
In the URL named "URL" go and manually download the file and overwrite the file in "Path".

It'll probably give you another file immediately after. Do the same.

This is a common Minecraft Launcher error.
