### ISSUE TITLE
Extanded crafting, Imaginary time block not crafting

### ISSUE THREAD

**Issue by Samplada** [Cazadorsniper/PO3#768]
Pack Version: 3.145
Pack Mode: Titan Mode
Singleplayer

Description:

I tried to craft the Imaginary time block in the Advanced Crafting Table from Extended Crafting.

But the craft is not working.

![image](https://user-images.githubusercontent.com/40838198/71832231-d25b6500-30aa-11ea-984b-a53a9967124b.png)

So i tried to pick up the block to craft it and the block doesn't craft.

![image](https://user-images.githubusercontent.com/40838198/71832289-ef903380-30aa-11ea-917b-0c196c4f1119.png)

i though it was a problem with some NBT or something so i've tried with the different speed upgrade from Extra Utilities 2 and different Energy cube from Mekanism but that don't seem to work too.

![image](https://user-images.githubusercontent.com/40838198/71832453-4138be00-30ab-11ea-9d62-3edd14a30497.png)

So after that i've tried to craft with the Automatisation Interface from Extended Crafting using the recipe from before but the same happened.

I tried with another Advanced Crafting Table it's not working too.

So after that i tried to restart the game, but it's the same result as before.

**Comment by Cazadorsniper** [comment]
Probably fixed for next update.
