### ISSUE TITLE
Missing Recipe's

### ISSUE THREAD

**Issue by Ticskter** [Cazadorsniper/PO3#769]
Pack Version: 3.1.45
Pack Mode: Single Player, normal
Description: i am currently following along the early pages of the quest book and i have ran into a small snag. there are several quests that require items that do not have a recipe!! the main ones so far are the Growth Crystals from the "ALPHA" page of the quest book and also the Epsilon Page. from the Epsilon page i have been able to craft a few items from this page. when searching JEI for the mods that are on the Epsilon Page i find that very few items from Magneticraft and Modular Machinery have recipes.

only reason that i am posting this is that ive seen on Hypnotizd Kappa Mode play through of PO3 he is able to craft the Growth Crystals. is there a manual update that i could do with a command to fix this or just sit back and wait for a pack update? i have tried the /bq_admin_default load or what ever the command is to see if that fixed it but it hasnt.

Also, there is no recipe for Buckets anymore. use to be 3 iron plates in bucket shape on crafting table. They now have to be made, from what ive seen, from the Tinkers Smeltery, but in order to get the bucket cast, you need a stone bucket... which does not have a recipe either.

**Comment by Ticskter** [comment]
Also want to add the Solar Flux Reborn mod to this list as well. earlier in my play through i was able to create the first two tier solar panels, however, now i cannot complete the quest progression due to the mirror recipe being removed or disabled.

**Comment by Cazadorsniper** [comment]
I recommend you reinstall the pack and move your world over.
