### ISSUE TITLE
Kappa mode recepites not works 

### ISSUE THREAD

**Issue by petrbix** [Cazadorsniper/PO3#770]
Please help i have a server wthout kappa mode and client and recepites not working please help

**Comment by petrbix** [comment]
pleasee

**Comment by marvnrawley** [comment]
Which recipes? Some are supposed to be disabled. A list or screenshot will help the mod maintainers.

**Comment by petrbix** [comment]
ok one minit

**Comment by petrbix** [comment]
creative items and sripts folder not have a kappa files ?
how to fix this

**Comment by petrbix** [comment]
please

**Comment by marvnrawley** [comment]
Kappa mode is in a closed beta. I'm just a random guy, I have no idea how you apply for it.I don't think you even CAN apply for it, I think it's invite only. If your problem is that you set kappa mode and you aren't in the beta.... then you have to wait for release.
