### ISSUE TITLE
Armour - found some duplicate armor sets which bypass the armour progression tree

### ISSUE THREAD

**Issue by marvnrawley** [Cazadorsniper/PO3#772]
**Pack Version:** 3.1.45
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Multiplayer 

**Description:** The following armour sets are duplicate and allow players to get higher-end armour without following the progression tree.

- "Knight Slime" (space) armour from ArmorPlus (in the progression tree) vs "Knightslime" (no space) armour from Tinkers Complement (directly craftable)
- Steel armour from Thermal Foundation (in the progression tree) vs Steel armour from Immersive Engineering and Steel armour from Tinkers' Complement (both directly craftable)
- "Lapis" armour from ArmorPlus (in the progression tree) vs "Lapis Lazuli" armour from Mekanism (directly craftable)

In the case of Knightslime I'd suggest the Tinkers' Complement recipe be disabled as it's weaker.

The steel armor is similar but not identical. Might be a good idea to pick one and disable the other two, and probably easier to follow the one already in the progression tree?

The Mekanism Lapis Lazuli set is noticeably lower-tier than the ArmorPlus set, so could be disabled.

**Steps to reproduce:** Search for them in JEI and compare the recipes

**Crash log (use pastebin or issue will be closed):** n/a

**Additional information provided by OP:** I also note that the following can be crafted in the crafting grid without supplying the inferior armour as per the progression tree. I would suspect some could be brought into the quest tree.

- The botania armour, manasteel, terrasteel, elementium, seems that this could just be included somewhere since the Mystical Agriculture stuff is in?
- Erebus Jade, Exoskeleton, Rhino, Bamboo, Glider, Powered Glider armour sets, asssume this was intentional since it's fairly late game
- All the Extra Planets armour items, none of which are a huge problem since they are pretty endgame, except the Zinc set, because you can get Zinc from sieving, and it's a pretty strong set, so might be worth adding the Zinc set somewhere accordingly, maybe under the first tier Workbench recipes slotted in according to power.
- Project Red Exploration Ruby, Sapphire and Peridot can be made directly despite the fact you can get the mats from Sieving, and they're all relatively strong

**Comment by Cazadorsniper** [comment]
I purposely left armors out.
