### ISSUE TITLE
Modpack crash: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Bibliotebarbarian** [Cazadorsniper/PO3#774]
**Version 3.1.45**
**Pack Mode: Normal**
**Singleplayer**

**Description:**
After changing my RAM from 2x4G to 2x8G i experience this crash. For more info check the post I made on stackexchange: https://gaming.stackexchange.com/questions/362635/minecraft-crashes-with-exception-access-violation

I already tried reinstalling both the pack and java, and drivers are updated. Vanilla minecraft loads up fine, but other modpacks seem to experience the same problem.

PC specs
Intel i5 750 quad core 2.67 GHz
Nvidia GeForce GTX 950
Intel SSD 256 G
HDD 1T (shouldn't mattter, nothing relevant is installed here)

**Steps to reproduce:**
Just load up the game.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/4XV9reu0 this log is from an attempt at loading PO3

**Comment by Cazadorsniper** [comment]
All I can say is that seems to be a Java crash not a pack crash.
