### ISSUE TITLE
TITAN MODE: Lunar Reactive Dust not obtainable

### ISSUE THREAD

**Issue by Nick-Nickname** [Cazadorsniper/PO3#775]
**Pack Version:**
PO3-3.1.45

**Pack Mode:**
TITAN

**Singleplayer, Multiplayer, or LAN?: **
Multiplayer

**Description:**
The recipe for Lunar Reactive Dust has been removed, so the only way to get it is through Lunar Reactive Ore. This can only be obtained with the laser, but I need Lunar Reactive Dust to manufacture the laser.

I hope I have not overlooked the possibility of making Lunar Reactive Dust. If so please correct me.

**Comment by marvnrawley** [comment]
Put Lunar Ore or Lunar Ingot into a Extra Utilities 2 Crusher or Double Crusher. Works fine for me in Titan mode.
