### ISSUE TITLE
Angel Ring(/Wings) Player Placemen Bug?

### ISSUE THREAD

**Issue by Kobatz** [Cazadorsniper/PO3#777]
**Pack Version:** _PO3-3.1.45_
**Pack Mode:** _Normal_
**Singleplayer, Multiplayer, or LAN?:** _Multiplayer_

**Description:**
Had the bug since I started playing the pack at the 2nd version release. Basically the wings from the Extra Utilities 2 Angel Wings are offset off the player. Wasn't sure what caused it so decided to update from 3.0.40 to 3.1.45. I realized if I take off the enderman head the wings go back to how they are suppose to. Looks like the Enderman Evolution head causes it. If I take it off and relog, the bug doesn't occur, but if I restart my minecraft and relog then it happens again. 

**Recorded the bug.** (*below*)
http://www.gmodsc.com/angelwings.webm

**Comment by Cazadorsniper** [comment]
I was able to replicate this, not sure whose fault though. Gonna send to P455w0rd.
