### ISSUE TITLE
Extended crafting recipes (wand of animation)

### ISSUE THREAD

**Issue by Drsnaki96** [Cazadorsniper/PO3#778]
**Pack Version:** 3.1.45 
(manually added: 
- integrated dynamic and updated cyclops core for it
- project red-integrations)

**Pack Mode:** Titan

**Singleplayer**

**Description:**

Pretty sure it's the same thing as issue #716 

The recipe for the wand of animation seems to not work properly. The wand does not appear in table (crafted item slot) when shift clicked with JEI. The wand appear when you place anyone of the items by yourself in the table but once you pull it out of the table close and re open the items are back to the places and the wand is gone. If you do not close the crafting table inventory after crafting and you just click where the recipe items used to be the wand disappears and the items "come back"

I have accidentally launched the pack in normal mode 2-3 times when i was trying to get the herobrine fight not to crash

So far i have tried 

- binding the sigil to my player before trying to craft
- activating the sigil before trying to craft
- cheating in the rending staffs (both of mine had essence)

none of these seem to have worked

**Steps to reproduce:**

- Try to craft the wand of animation in titan mode

**Comment by Cazadorsniper** [comment]
Yes, still trying to solve this.

**Comment by Cazadorsniper** [comment]
Does this still happen in the new version?

**Comment by davepatelbn2** [comment]
Hi, i also just came across the same issue in poz3 titan on 3.2.51

**Comment by usernamenull-1** [comment]
I found a post on reddit detailing this issue and can correct it by removing the recipe in the scripts prior to the new recipe.

//philosopher's stone
recipes.remove(<projecte:item.pe_philosophers_stone>.withEmptyTag());
mods.avaritia.ExtremeCrafting.remove(<projecte:item.pe_philosophers_stone>.withEmptyTag());

**Comment by Cazadorsniper** [comment]
Crafttweaker would error if I used that.

**Comment by Cazadorsniper** [comment]
I added a priority preprocessor so this should stop happening if the crafting removal/addition location is the reason why it has trouble crafting.

**Comment by Cazadorsniper** [comment]
Is this still an issue on version 3.2.52?
