### ISSUE TITLE
[Mod Request]

### ISSUE THREAD

**Issue by angryce** [Cazadorsniper/PO3#78]
Tinker I/O 
Useful mod and usually doesn't create issues

https://minecraft.curseforge.com/projects/tinker-i-o

**Comment by Zapstur** [comment]
Seems like that could create a lot of balancing issues in regards to duping.  Those can be fixed, yes, but ultimately require a lot of work.

**Comment by Cazadorsniper** [comment]
We had that mod in before then we removed it.
