### ISSUE TITLE
Solidified experience spawn in my inventory

### ISSUE THREAD

**Issue by rivoalrivoal** [Cazadorsniper/PO3#781]
**Pack Version:** 3.1.45
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Multi on Server
**Description:**
I have a strange bug. There are "Solidified Experience" that spawn in my inventory.
Video: https://www.youtube.com/watch?v=i4vevDIy2LA
**Steps to reproduce:**
These objects appear when a mob crusher kills mobs (mob grinding / industrial foregoing). Only me have this 'bug' on server.
**Crash log (use pastebin or issue will be closed):**
No log in my console

**Comment by Cazadorsniper** [comment]
Do you have a magnet on?

**Comment by rivoalrivoal** [comment]
Look at my inventory.  The items that I drop do not return inside.

**Comment by rivoalrivoal** [comment]
That's why I made a video. Maybe I can send you my backup? But it is linked to my player UUID .... Even if I delete my player data it still does.

**Comment by Cazadorsniper** [comment]
I can't replicate, maybe an update fixed it or you might have some type of enchant or passive skill on you.

**Comment by rivoalrivoal** [comment]
Thank you for your reply.
Since yesterday I no longer have the bug (no restart since then) ... We can close issue for now.
