### ISSUE TITLE
Possible unintended recipe for Inscription Tile

### ISSUE THREAD

**Issue by tempme123** [Cazadorsniper/PO3#782]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**Version: 3.1.45
**Pack Mode:**Titan (GOG)
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
![Capture](https://user-images.githubusercontent.com/46273906/72823777-d4d8c580-3c39-11ea-9de3-ef04710ac446.PNG)
These tiles in normal mode had a much harder recipe compared to titan mode's 5 stone, 4 sandstone. If this recipe was intended feel free to ignore this report

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Likely intended.
