### ISSUE TITLE
Server crashes at startup

### ISSUE THREAD

**Issue by TheHittMann** [Cazadorsniper/PO3#783]
**Pack Version:** 3.1.45
**Pack Mode:** Multiplayer

**Description:**
I start the server, it runs for a good 15-20 minutes. then at some point it crashes and shuts down.

**Steps to reproduce:**
everytime I start the server it happens

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/0Y4NAq3d

**Comment by Cazadorsniper** [comment]
In server.properties at max-tick-time put -1
