### ISSUE TITLE
Beginning quest, impossible to complete.

### ISSUE THREAD

**Issue by SlimGrim602** [Cazadorsniper/PO3#784]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.1.45
**Pack Mode:** All Modes
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
The beginning quest that requires you to make a wooden crucible is impossible because the wooden crucible recipe is disabled and you have to use the oak crucible instead. The quest requires the wooden crucible to be created.
**Steps to reproduce:**
Open questbook, go to the quest titled "Water to Clay," and you can see that it requires the wooden crucible which is disabled.
**Crash log (use pastebin or issue will be closed):**
Doesn't crash the game, no log to be had.

**Comment by Cazadorsniper** [comment]
Did you add any mods, add a resource pack, or mess with the scripts/config folder? I see the quest requires the wooden crucible and there is no such thing as oak crucible.

**Comment by SlimGrim602** [comment]
I didn't add any mods or anything, but I fixed it when I deleted and reinstalled the pack.
