### ISSUE TITLE
Auto Sifter Proper setup not working

### ISSUE THREAD

**Issue by flyingwizarddragon** [Cazadorsniper/PO3#785]
https://ibb.co/PgJvXRH
I'm using the version of PO3 on twitch app titan mode.

The stone axel isn't spinning I tried all sorts of configurations, and the sifter isn't gaining rotation.

The water wheel is spinning though.

**Comment by Cazadorsniper** [comment]
Have you tried turning the axel and making sure that water is flowing to the correct side?

**Comment by flyingwizarddragon** [comment]
i just reloaded broke the original setup rebuilt it in a different spot
then it started working. The setup was exactly the same as the old one
though i guess it just decided it wanted to work.

**Comment by udooles** [comment]
The axel is attached backwards to the shifter in that picture.  You need to build the multiblock from the shifter outwards for everything to connect right.   I can tell because the bulgy parts shouldn't touch each other to connect right.
