### ISSUE TITLE
Nether Cake Broken

### ISSUE THREAD

**Issue by SlimGrim602** [Cazadorsniper/PO3#787]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  3.1.45
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer
**Description:**
Whenever I place down a nether cake it only appears as one slice of the cake and is inedible. I haven't tried it with any other cakes but I know this happens to the nether cake.
**Steps to reproduce:**
Place nether cake on the ground.
**Crash log (use pastebin or issue will be closed):**
Doesn't crash game no log to be had.

**Comment by Cazadorsniper** [comment]
Feed it obsidian.
