### ISSUE TITLE
Project Ozone 3 A New Way Forward Not opening

### ISSUE THREAD

**Issue by Invixy** [Cazadorsniper/PO3#788]
Every time I try to open Project Ozone 3 A New Way Forward or just Minecraft in general, I get into the launcher. Press the play button, the launcher closes and nothing happens. What to do? Please and thank you

**Comment by Cazadorsniper** [comment]
Do you have a crash report or log? If its what I think it is, then its probably the crash that tells you to download a file and put it into a specific path.

**Comment by Invixy** [comment]
17:11:40.145
Preparing to launch minecraft client for forge-14.23.5.2847
17:11:40.161
Prepared asset index
17:11:40.197
Have 1347 total files to check or download
17:11:40.209
Waiting for 1347 futures
17:11:42.061
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847.jar
17:11:42.105
Have local file C:\Users\invix\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2847\forge-1.12.2-14.23.5.2847.jar but don't know what size or hash it should be. Have to assume it's good.
17:11:42.112
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
17:11:42.115
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
17:11:42.120
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/org/jline/jline/3.5.1/jline-3.5.1.jar
17:11:42.123
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
17:11:42.146
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/com/typesafe/config/1.2.1/config-1.2.1.jar

**Comment by Invixy** [comment]
17:16:11.441
ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
17:16:13.292
Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.world.World, patches=[Patcher.PatchDescriptor(methods=func_72939_s()V, patch=clone), Patcher.PatchDescriptor(methods=func_72939_s()V, patch=insertCodeBefore), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall)])
17:16:13.299
Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.play.server.SPacketCustomPayload, patches=[Patcher.PatchDescriptor(methods=, patch=addMethod)])
17:16:13.299
Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.NettyPacketEncoder, patches=[Patcher.PatchDescriptor(methods=encode(Lio/netty/channel/ChannelHandlerContext;Lnet/minecraft/network/Packet;Lio/netty/buffer/ByteBuf;)V, patch=replaceMethodCall)])
17:16:13.313
Coremod plugin class CoreMod run successfully
17:16:13.315
Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
17:16:13.316
Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
17:16:13.316
Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
17:16:13.469
Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
17:16:13.503
Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
17:16:13.524
Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
17:16:13.529
Injection complete
17:16:13.529
Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
17:16:13.530
Running coremod plugin FMLCorePlugin

**Comment by Cazadorsniper** [comment]
Use pastebin or something similar to it to post the log.

**Comment by TheBestCube** [comment]
I have the same problem. I don’t have an enormously powerful pc and I just downloaded the pack toady, tried to load it but kept getting “not responding”. So, not sure if this is while loading or at lode complete, anyway while reading forums I tried to follow the advice of disabling splash.properties and what I get in result is that the “not responding” actually lasts shorter BUT now I get black screen.
