### ISSUE TITLE
Weird client side lag spikes

### ISSUE THREAD

**Issue by jinga986** [Cazadorsniper/PO3#789]
# Weird client side lag spikes
Pack Version: 3.1.45
Pack Mode: Titan
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: I have a weird sort of "latency" issue when I play on my single player world. Sometimes I'll get massive lag spikes when trying to access an inventory such as my AE System or a chest. It also effects my player's abilities as it acts like I'm lagging on a server with about 350 ping but I'm on my singleplayer world. Examples include pausing before block updates, acting likeI didn't mine a block I just mined, acting like I didn't place a block I just placed. 

Steps to reproduce: I assume it has something to do with the sprinklers and my heavy focus on completing the agricraft of my Mystical Agriculture seeds but I removed them and tried my hardest to put the new farms way out of render distance 

Crash log (use pastebin or issue will be closed): No Crashlog available as it isn't a crash But I do have a recording of the issue if it could help

**Comment by Cazadorsniper** [comment]
Have you checked anything else that can cause lag? Like a mob farm.

**Comment by jinga986** [comment]
That was my second thought after clearing the sprinkler but it even happens on Peaceful. The weird part is that it's all client side. TPS is normal, FPS is normally ~100, it just suddenly started and didn't stop

**Comment by jinga986** [comment]
If it helps, I added Integrated Dynamics/Tunnels early on in my world for easier automation of Celestial Crystals, and Tesslocators to try to reduce the lag

**Comment by Cazadorsniper** [comment]
Try removing those mods.

**Comment by jinga986** [comment]
I removed those mods but the lag spikes are still there

**Comment by jinga986** [comment]
I just finished redownloading the pack and the issue still persists

**Comment by Cazadorsniper** [comment]
With the same world? Can you give me the download for the world?

**Comment by jinga986** [comment]
Sure, How would i go about doing that?

**Comment by jinga986** [comment]
I just oopsied with a spawner causing a massive amount of entity lag and it fixed the problem. if that makes sense to you then yay, if not, idk

**Comment by Cazadorsniper** [comment]
lol ok closing the issue.
