### ISSUE TITLE
Can't get a server to work

### ISSUE THREAD

**Issue by WoIIo** [Cazadorsniper/PO3#79]
**Pack Version:**
3.0.38
**Description:**
I installed the server files, ran it like any other minecraft server. But the world type is not working, it's just loading a normal world and also i get no quest book or ability bottle. When i give them to myself in creative, it doesn't work.
**Steps to reproduce:**
Download server files --> launch minecraft_server.1.12.2 --> edit server file to change the IP --> launch minecraft_server.1.12.2 again(bat file)
**Crash log:**
/ server doesn't crash

**Comment by Kobatz** [comment]
It sounds more like your not loading forge and just starting with the minecraft jar. What OS are you running it on? Try setting up shortcut to your forge file like: `-jar forge-2808.jar`
