### ISSUE TITLE
Went to the End and when I got back my completed quest and showing not completed.

### ISSUE THREAD

**Issue by kattmc3** [Cazadorsniper/PO3#791]
# Use the search function before reporting to see if the issue has been reported before
Version 31.45
**Pack Mode:**
Singleplayer

Went to End and have now lost all completed task. Quest book shows that I haven't completed any task. 

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
You can try loading a backup.

**Comment by kattmc3** [comment]
I don't have a backup. I am playing it off of twitch and it doesn't have any backups. I checked under saved games but it is empty.

**Comment by Cazadorsniper** [comment]
Curse\Minecraft\Instances\PO3\backups

**Comment by kattmc3** [comment]
Cazadorsniper, thank you. I found a backup but I had to redo the dragon quest. Not a big deal and now I can move on. Thank you again.
