### ISSUE TITLE
Stopped during start at loading Craft Tweaker 2 (with the newest Version)

### ISSUE THREAD

**Issue by LeMetios** [Cazadorsniper/PO3#798]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** see title

**Steps to reproduce:** 

**Crash log (use pastebin or issue will be closed):**

**Comment by Chew** [comment]
I had this problem too. It took forever to get past it, but it still loaded. Patience isn't their issue, it's yours.

**Comment by Cazadorsniper** [comment]
@Chew Was that towards me?

**Comment by Chew** [comment]
@Cazadorsniper Wdym? I was telling OP that the problem was patience.

**Comment by Cazadorsniper** [comment]
Ok, I just didn't understand.

**Comment by LeMetios** [comment]
The problem wasn't my patience. Optifine was the problem :)
