### ISSUE TITLE
Bad Tick Lag

### ISSUE THREAD

**Issue by Rithenar** [Cazadorsniper/PO3#799]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:**Titan
**Singleplayer, Multiplayer, or LAN?:**Single

**Description:**
High tick lag that is affecting machine processing and crafting
**Steps to reproduce:**
I have been playing PO3 Titan mode for a while now with minor problems. Starting this afternoon, however, I started to get major tick lag to the point that enderIO machines like an Enhanced Sag Mill with a Stellar capacitor, for example, will stutter sometimes for up to 10 seconds at the time when processing ores. Extraction from several machines to AE2 is almost impossible and the processed products sit in the machines for a while. My mob farms as well as my essence farms are backing up because conduits can't extract the contents.

I updated to the new version of PO3 and still getting these issues

You can see in the debug pie that my tick is at over 30%

![debug pie](https://user-images.githubusercontent.com/9939332/73854218-c1138e80-47f7-11ea-8219-24996ecb7001.png)

Also here is my F3 info in case it shows something that helps

![Debug Info](https://user-images.githubusercontent.com/9939332/73854246-cffa4100-47f7-11ea-9546-ff1be4abcea5.png)

The logs below are from the game launcher and the debug profiler

**Crash log (use pastebin or issue will be closed):**

Game Launcher Log - https://paste.ubuntu.com/p/Dt85r4RjdB/

Profiler Log - https://paste.ubuntu.com/p/zJX5YxspXv/

**Comment by Cazadorsniper** [comment]
Were you using Computercraft?

**Comment by Rithenar** [comment]
Originally I was, but I removed it when I installed the latest pack version
