### ISSUE TITLE
Crash upon joining a world

### ISSUE THREAD

**Issue by ZitherBai** [Cazadorsniper/PO3#8]
After the last update 3.0.38, I was able to play the game once, and starting from the second time after the update, the game crashes after I join the world for 1 second.

The latest log file has been attached, very much appreciated!
[latest.log](https://github.com/Cazadorsniper/PO3/files/2898291/latest.log)

**Comment by nzminecraftDOTcom** [comment]
You need to post a crash log, not your latest.log. Also please paste it into pastebin or a similar format of website rather than having people download files.
