### ISSUE TITLE
Analog Crafter shift click crash

### ISSUE THREAD

**Issue by darth2232** [Cazadorsniper/PO3#80]
**Pack Version:**

3.0.38

**Description:**

The client crashed when trying to shift click items into an analog crafter with sticky and spread items enabled. More specifically when trying to shift click in grains of infinity essence for the grains of infinity recipe.

**Steps to reproduce:**

Fill up an analog crafter with enough material so that a full stack can't be inserted into a single slot.

**Comment by Flutterdashie** [comment]
Hi, just so you know: That's a known issue with all Extra Utils inventories, overfilling them causes a crash. It's at the bottom of the current version's notes.
