### ISSUE TITLE
the Elusive Bucket cast

### ISSUE THREAD

**Issue by Chris-FireFox** [Cazadorsniper/PO3#800]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.50
**Pack Mode:**Kappa
**Singleplayer, Multiplayer, or LAN?:**Single Player

**Description:** cannot make bucket cast with clay bucket as instructed by JEI

**Steps to reproduce:** pour gold onto a clay bucket with either porcelain smelter or smeltery and you get a bucket filled with gold instead of a cast. also tried with aluminum brass and got the same result
**Crash log (use pastebin or issue will be closed):**

**Comment by Slyklaw** [comment]
I also tried with a full bucket hoping that would trigger the casting process, but nope, can't make a bucket cast.

There is a JEI entry for a stone bucket, but no craftable recipe.
