### ISSUE TITLE
[Lordcraft] Bug - Loss of Mana crystals on craft.

### ISSUE THREAD

**Issue by itsjusttriz** [Cazadorsniper/PO3#802]
Mod Version: 1.0.0
Modpack: Project Ozone 3 v3.2.51server (Titan Mode)

I place a crystal in the Voidinterface
Open the arcane forge and spam the craft button. 
The first craft doesnt finish but takes the mana anyways.
Takes mana for craft anyways.
Place more mana in, do the same as above.
Losing mana = Losing crystals.

Recording - https://youtu.be/Dy7qo3NBCBA

**Already Filed a report to Mod Dev on Curseforge site.**

**Comment by Cazadorsniper** [comment]
ok
