### ISSUE TITLE
YABBA/BQ Hammer Quest Failed Trigger

### ISSUE THREAD

**Issue by itsjusttriz** [Cazadorsniper/PO3#805]
I have a Yabba Hammer and my quest wont trigger. The hammer in the Quest book has no NBT tags but the one in my inventory DOES.

https://imgur.com/a/UroASC8
https://i.imgur.com/tuP7Ccr.png
https://i.imgur.com/QohgUgU.png

**Comment by Cazadorsniper** [comment]
What nbt data is on it?

**Comment by itsjusttriz** [comment]
> What nbt data is on it?
Model:Block

**Comment by Cazadorsniper** [comment]
Ok the Hammer doesn't have NBT data on it when you craft it the first time. Will be an easy fix.
