### ISSUE TITLE
No Diamond recipe in Titan Mode

### ISSUE THREAD

**Issue by Sleipnir322** [Cazadorsniper/PO3#807]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.51**
**Pack Mode: Titan**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: can't craft Diamonds from diamond essence, fixed in Normal Mode but not in Titan Mode.**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by JTGginger** [comment]
Same issue.  Brand new install of 3.2.51, only changed the packmode.cfg to titan.

**Comment by kenturkey** [comment]
Same issue here, tried to make diamonds and was quite confused.
