### ISSUE TITLE
Crash when loading PO3 

### ISSUE THREAD

**Issue by SavBunni** [Cazadorsniper/PO3#810]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**Title

NOTE: I have 16GB RAM in my PC

**Steps to reproduce:**
1. Download the modpack from the Twitch app.
2. Click the settings icon and adjust to my profile settings.
My twitch mod profile before loading: 
![dfffff](https://user-images.githubusercontent.com/59836577/74076759-fbd81b00-49df-11ea-91b2-c4029bb14879.PNG)
3 .Launch the modpack from the Twitch app and wait for the game to load.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/3pV0ZMik

**Comment by SavBunni** [comment]
Additonal Notes:

When I was running an this modpack in a older version 3.1.45, the Memory Used/Total bar shows that the game have 7177MB of RAM space to load on. However, when I am running the current version (3.2.51), the bar shows the game have 2869MB to load on.

Loading on 3.1.45
![ghsadgaga](https://user-images.githubusercontent.com/59836577/74077295-3b086b00-49e4-11ea-8520-40fd7a476b3a.PNG)

Loading on 3.2.51
![sfhrdsthdsh](https://user-images.githubusercontent.com/59836577/74077296-3c399800-49e4-11ea-9fc1-f8fc5c793a13.PNG)

**Comment by Cazadorsniper** [comment]
Increase dedicated ram for the pack to use in the twitchapp settings, not individual profiles.

**Comment by SavBunni** [comment]
Thank you. This solves this issue.
