### ISSUE TITLE
Needed Removal of VoidCraft Quests?

### ISSUE THREAD

**Issue by SavBunni** [Cazadorsniper/PO3#812]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**
Title
VoidCraft quests are now basically question marks.
![2020-02-08_15 54 50](https://user-images.githubusercontent.com/59836577/74092623-37302380-4a8c-11ea-835c-efe6e3052354.png)

**Steps to reproduce:**
Open the quest book and go to Omicron.

**Comment by Cazadorsniper** [comment]
Solution to this is at the top of thew changelog.
