### ISSUE TITLE
Unable to craft Mob Duplicator - Titan Mode - v3.2.51

### ISSUE THREAD

**Issue by pacman1983** [Cazadorsniper/PO3#814]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** v3.2.51
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Unable to craft the mob duplicator in Titan mode on the advanced table. Both server and client are set to Titan Mode. Have tried manually inputting the items to the table, as well as let JEI insert them into the Advanced Table.  Neither work. 

**Steps to reproduce:** Try to craft the Mob Grinder

**Crash log (use pastebin or issue will be closed):**

**Comment by SavBunni** [comment]
Can you insert images of the JEI crafting recipe and you crafting it?

**Comment by pacman1983** [comment]
JEI will put the items into the crafting table, but it will not produce the mob duplicator. Please see below.


![image](https://user-images.githubusercontent.com/43517048/74242719-09252c00-4ca4-11ea-81da-a45a58bbacd8.png)

**Comment by smmailik** [comment]
Same problem here  : / ... (I've just trashed the items and gave myself 3 Mob Duplicators ) BTW the recipe for Pink Slime Ingots is a pain in the ass (i have 3 farm 13*13 and I've needed a day to collect all the slime )

**Comment by pacman1983** [comment]
I'm glad you also stayed on titan. Seems like most people jumped to kappa. This should work though. I shouldn't have to give it to myself in creative.

**Comment by smmailik** [comment]
Actually I don't have a problem to give it myself as long as I've crafted all the other components and then trashed them and took the item for JEI .. BTW I couldn't craft the Animation Wand as well ..

**Comment by Cazadorsniper** [comment]
Extended Crafting...

**Comment by SavBunni** [comment]
I am also having the same issue as you guys after I reached the same level as you are.

![2020-02-18_21 05 08](https://user-images.githubusercontent.com/59836577/74798137-89462580-5292-11ea-8192-c745104eb0c8.png)

**Comment by ghzdude** [comment]
I've been having the same problem too, but I think I've found a solution or at least part of it.

In `titan_7x7.zs` and `titan_9x9.zs` for the Philosopher's Stone, Mob Duplicator, and the Wand of Animation, I have noticed the recurrence of a `.WithEmptyTag()` method on certain items in the script file. Removing these methods allowed me to craft the items mentioned before by both spawning in and _manually_ crafting the required ingredients. The `.WithEmptyTag()` method causes a problem because spawning in the item adds an empty NBT, when manually crafting them has no NBT.

**Comment by Cazadorsniper** [comment]
the .WithEmptyTag() was added by me not Extended Crafting because of this issue. The recipes some times works and sometimes doesn't.

**Comment by ghzdude** [comment]
It seems that more investigation is needed.

**Comment by gregoirechauvet** [comment]
I was able to craft the mob duplicator. I had to place the gas generators in the world, and break them. Then the recipe works.

**Comment by Cazadorsniper** [comment]
I changed this recipe for next update so hopefully its fixed.
