### ISSUE TITLE
Strange lag appears on the server

### ISSUE THREAD

**Issue by JackMeds** [Cazadorsniper/PO3#816]
**Pack Version:**PO3-3.2.51
**Pack Mode:**kappa
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**
when player join the server，server will lag
Detected by spark :
https://sparkprofiler.github.io/#a5xVeKzD4Y
I try 3 serverfile to fix this
forge,sponge,[catserver](https://github.com/Luohuayu/CatServer)
There is no significant improvement in this test even on I9-9900（my own PC）
The main thread has not reached 100% utilization.
**Steps to reproduce:**
player join the server
**Crash log (use pastebin or issue will be closed):**
https://sparkprofiler.github.io/#a5xVeKzD4Y

**Comment by Cazadorsniper** [comment]
I noticed 3 things in that profiler link, 2 are from Quark which I have already turned off for next update,  the third is from xReliquary something to do with the lantern of paranoia.
