### ISSUE TITLE
Helpppp Pls:)

### ISSUE THREAD

**Issue by EmirhanGamer71** [Cazadorsniper/PO3#817]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:Project Ozone 3
**Pack Mode:normal I guess I didnt changed it
**Singleplayer
**Description:**
Help me pls game is stuck at 7/7 sometimes and when itsnt at 7/7 it gets stuck at mojang screen after 7/7

**Steps to reproduce:**
I dont know 
**Crash log (use pastebin or issue will be closed):**
https://paste.ubuntu.com/p/WpnKGJVzWy/

**Comment by Chew** [comment]
How long have you waited? I ended up waiting 15-20 mins before it finally loaded

**Comment by EmirhanGamer71** [comment]
so I have to wait WHİLE its at the mojang or 7/7 screen?

**Comment by Chew** [comment]
Yep, as as long as it's not crashed, it's not a problem. It usually takes 30-40 mins for mine to boot and I've given it 8 gb of RAM

**Comment by EmirhanGamer71** [comment]
thx I have 8gb on my pc and 16gb of ram is on the way to me I will give it 12gb of ram because I will have 24gb of ram :) and its gonna take long to arrive because I am in turkey And its coming from America and btw I have given it 6.9 gb but it says 6.1gb on the ingame ram meter

**Comment by Chew** [comment]
Yeah, when you "give it 8gb of ram" you're really setting how much it can allow. Won't necessarily use all you give it especially if ram is used elsewhere

**Comment by EmirhanGamer71** [comment]
so Should I give it 8gb now and 12 gb when my ram arrives

**Comment by ken-long** [comment]
In doing my own searching regarding loading issues, people have reported extreme reductions in loading time by disabling WaitingTime (the mod that adds pong to the loading screen)

And when I say extreme, I mean some people reduced their loading times from **literal** hours to several minutes

**Comment by Chew** [comment]
6 mins now, how much before?

Also, Unrelated but what mod adds the loading times in the top left

**Comment by ken-long** [comment]
oh, sorry, meant to provide that detail also.  time dropped from ~7:30 to somewhere in the 6-6:30 range, so not _extremely_ significant for me, but definitely worth a try for others with crazy long loading times.

**Comment by Cazadorsniper** [comment]
@Chew Waiting Time adds that.

**Comment by Chew** [comment]
Yeah, mine went from 30-40 minute wait time to sub 7 minutes. WaitingTime more like WaitingForALongTime
