### ISSUE TITLE
Kappa mode AE2 Stuff issue

### ISSUE THREAD

**Issue by Linus222** [Cazadorsniper/PO3#820]
Pack Version: Newest release
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description:
The Crystal Growth Chamber and the Advanced Inscriber is missing their functionality. They can be crafted but not be used.

**Comment by Cazadorsniper** [comment]
"Pack Version: Newest release" isn't a version.

**Comment by Cazadorsniper** [comment]
Crystal growth chamber works fine.

**Comment by Cazadorsniper** [comment]
Advance Inscriber also works fine.
