### ISSUE TITLE
Game crash using flat transfer node, crate and seed analyser

### ISSUE THREAD

**Issue by Quichabichen** [Cazadorsniper/PO3#821]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 
Version: 3.2.51
**Pack Mode:**
Normal
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**
Game crash when using flat transfer nodes to shift seeds from a crate to a seed analyser.
2 crash logs. The first from when it originally happened. The second from when i attempted to reload game and it crashed again. Crash happened when I put some melon seeds into crate.

**Steps to reproduce:**
Place crate, flat transfer node set to either push or pull....(i dont really know what im doing with them) into seed analyser. I had another crate on the other side with a flat transfer node between crate and analyser to pull seeds out. Put melon seeds into crate. Could be with other seeds also. 

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/39rxqhzS
https://pastebin.com/N9tJ6LnA

**Comment by Cazadorsniper** [comment]
Don't automate the seed analyser.
