### ISSUE TITLE
Electrotine Recipe Missing

### ISSUE THREAD

**Issue by TrackStar117** [Cazadorsniper/PO3#822]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.2.51**
**Pack Mode:Kappa**
**Singleplayer, Multiplayer, or LAN?:**
Single player
**Description:**
There is no recipe for electrotine alloy in the immersive engineering arc furnace. Unlike the red alloy. Making only the more expensive version of electrotine automate-able
**Steps to reproduce:**
Search electrotine in Jedi
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Didn't know PO3 had Jedi.

**Comment by Cazadorsniper** [comment]
Try the Alloy Smelter/ kiln in IE.

**Comment by TrackStar117** [comment]
Dear Cazadorsniper,

Sorry about that autocorrected JEI to Jedi
