### ISSUE TITLE
Wireless Crafting Terminal Disappears when you regain your inventory after dying.

### ISSUE THREAD

**Issue by Fleepy** [Cazadorsniper/PO3#823]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Normal (or default if "normal" isint what its called)
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** If you die or get killed while holding a Wireless Crafting Terminal (From Wireless Crafting Terminal 2), It disappears when you get your inventory back.

**Steps to reproduce:**
Have a Wireless Crafting Terminal in your inventory, get killed by something or /kill yourself
and go back to your grave and retrieve your inventory. The crafting terminal is now gone.
The normal Wireless Terminal from AE2 does NOT disappear when you die, its only the Wireless Crafting Terminal that disappears.

Video: https://www.dropbox.com/s/787v9uj7tyk21c8/uZ7DGv5GhB.mp4?dl=0

**Crash log (use pastebin or issue will be closed):**
No Crash Log

**Comment by Cazadorsniper** [comment]
Check your baubles.

**Comment by Fleepy** [comment]
i never could have known that it would go there.
im stupid.
