### ISSUE TITLE
Mobs on server too powerful

### ISSUE THREAD

**Issue by What-The-Fox** [Cazadorsniper/PO3#824]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
All Erebus and Twilight-exclusive mobs seem to be hitting for around 20-30 hearts of damage on our server. (estimate based on how much xp is used when attacked with last stand). Attempts to change the "Boss Kill Modifier" in the config of Epic Siege Mod didn't work. 

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Try having the server owner delete ESM.dat in the world file.
