### ISSUE TITLE
Party Reward Sharing not working - Kappa mode Ver.3.2.51

### ISSUE THREAD

**Issue by JoellenTrollen** [Cazadorsniper/PO3#826]
**Pack Version:** 3.2.51
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Only one player can retrieve rewards from the rewards quest tab. **Just making sure this is intended you know**.

**Steps to reproduce:** switch to kappa mode from normal, Co-op, party invite other player, one player submits RAK for a reward. 

**Crash log (use pastebin or issue will be closed):**No crash Log

**Comment by Cazadorsniper** [comment]
Likely intended, I can't find any settings that will allow me to change it so it must of been changed in the mod itself.
