### ISSUE TITLE
Advanced Inscribers keep dropping into items every now and then.

### ISSUE THREAD

**Issue by flleeppyy** [Cazadorsniper/PO3#828]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
Recently my Advanced Inscribers have been dropping on the ground as if broken by a player,
and then they disappear because of natural despawning.
Heres what my current ME System setup is, incase it has something to do with my configuration. https://www.dropbox.com/s/02dhq0tr72j7aav/1gyTvHJWPp.mp4?dl=0

I have no Idea as to what could be causing it.

**Comment by Fleepy** [comment]
Found out a way to prevent it from happening: Place a chunk loader down where the Inscribers are.
