### ISSUE TITLE
Astral Tome Recipe 

### ISSUE THREAD

**Issue by sreekrishn** [Cazadorsniper/PO3#830]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.51
**Pack Mode:**kappa
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**
The default recipe for the astral tome is working and breaks quest progression and lets easy access to creative flight through the mantle of stars attuned to vicio and having the correct perk tree
the make it that "no lordcraft" is required to get into astral upto irridesnt altar with ease
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
This shouldn't happen, in "PO3\scripts\all_modes\all_recipes" do you see "recipes.remove(<astralsorcery:itemjournal>);" at the top?

**Comment by sreekrishn** [comment]
S it is there at the top

**Comment by Cazadorsniper** [comment]
Then, yeah it shouldn't happen.
