### ISSUE TITLE
[Twilight Forest] Portals not linked

### ISSUE THREAD

**Issue by mvdstam** [Cazadorsniper/PO3#832]
**Pack Version:** 3.2.51
**Pack Mode:** Kappa GoG
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Teleporting _from_ the Twilight Forest back to the overworld _for the first time_ results in a new portal being spawned in a seemingly random place.

**Steps to reproduce:** In a game with Kappa mode, create a Twilight Forest portal in a claimed and chunkloaded chunk. Go to the Twilight Forest. Go back to the overworld. Find yourself on a newly created portal, floating in the sky, away from your base. This portal _does_ seem to link up fine with its counterpart in the Twilight Forest dimension by the way -- its the primary portal we've started that doesn't seem to link up correctly.

**Additional information:** I've been able to reproduce this 100% of the time. All chunks in my base are _claimed_ and _chunkloaded_, including the chunk in which I create the Twilight Portal. I've tried this in multiple locations within my base, and on multiple Y-levels with the same result.

**Comment by Cazadorsniper** [comment]
There is nothing I can do about that, unless you want to end up in a twilight biome that you're not "allowed" to be in because you haven't killed that bosses. 

Note: You have the chunks claimed not chunkloaded through FTBUtils, that has been turned off.

**Comment by mvdstam** [comment]
Hey @Cazadorsniper, thanks for your quick response.

I think you were too fast to close this one, or I'm not understanding you correctly. It's not that I'm ending up in different Twilight Biomes, but it's the fact that there isn't any way for me to get back to my base without cheats the moment I enter the Twilight Forest:

> In a game with Kappa mode, create a Twilight Forest portal in a claimed and chunkloaded chunk. Go to the Twilight Forest. Go back to the overworld. Find yourself on a newly created portal, floating in the sky, away from your base. 

I have reproduced this several times now, in which the portals in the Twilight Forest sometimes get spawned almost next to each other. All in the correct starting biome. In my overworld dimension, I now have 6 floating Twilight Forest portals, hundreds of blocks away from my base.

Lastly, I turned on chunk loading in FTBUtils in my world so my cursed earth-based mob grinder would keep on running in my absence. Could _that_ have lead to this issue?

**Comment by Cazadorsniper** [comment]
# Determines if new portals should be pre-checked for safety. If enabled, portals will fail to form rather than redirect to a safe alternate destination.
    # Note that enabling this also reduces the rate at which portal formation checks are performed.
    B:checkPortalDestination=false

This means a new portal may spawn going back to the overworld which basically makes sure you will spawn in a biome that is safe. I can only suggest to start killing the bosses there and see if your portal will work correctly afterwards.

**Comment by Cazadorsniper** [comment]
The chunkloading "shouldn't" do that but no harm in testing.

**Comment by Traveydius** [comment]
I have literally the exact same problem. My Portal from my Base does not link up with the Twilight Forest Portal.

A build the portal on my base (properly), hoped in to get to the forest. So far so good.
Generation and loading is done.
However when i try to hop into the portal in the Twilight Forest (the one i just came out of) to get to my base in the OVerworld, it just generates a completely new Portal several chunks away from my OW base.
These 2 portal however seem to be linked up fine, no problem. It just ignores my initial Portal on the OW base upon first return... which is annoying.

I tried the above mentioned solutions, but with no luck on fixing the issue...

I use the same version as user mvdstam who opened the issue: 3.2.51 and I am also in Kappa Mode.
However i play on Singleplayer.

**Comment by mvdstam** [comment]
Glad to know I’m not crazy haha. I’ve also created a fresh SP world, with the exact same issue.

I’ve “worked around” the problem simply by not using the portal to go back to the overworld anymore, but using overworld apples instead. Another possible way is to use the `/spawn` command (I believe as part of the FTB utilities mod) to teleport back to the overworld.

Op 3 mrt. 2020 om 17:49 heeft Traveydius <notifications@github.com> het volgende geschreven:

﻿

I have literally the exact same problem. My Portal from my Base does not link up with the Twilight Forest Portal.

A build the portal on my base (properly), hoped in to get to the forest. So far so good.
Generation and loading is done.
However when i try to hop into the portal in the Twilight Forest (the one i just came out of) to get to my base in the OVerworld, it just generates a completely new Portal several chunks away from my OW base.
These 2 portal however seem to be linked up fine, no problem. It just ignores my initial Portal on the OW base upon first return... which is annoying.

I tried the above mentioned solutions, but with no luck on fixing the issue...

I use the same version as user mvdstam who opened the issue: 3.2.51 and I am also in Kappa Mode.
However i play on Singleplayer.

**Comment by Cazadorsniper** [comment]
I can only suggest to use overworld apples/cake, portality, waystones, draconic evolution's teleportation option, or /spawn.

**Comment by mvdstam** [comment]
Cheers @Cazadorsniper. Thanks again for your timely response and the incredible work you've put into the modpack.

**Comment by Traveydius** [comment]
Well thank you for that quick response, to both of you.

Interesting though how rare this issue seems to be.

**Comment by omerbadawy11** [comment]
> 
> 
> I have literally the exact same problem. My Portal from my Base does not link up with the Twilight Forest Portal.
> 
> A build the portal on my base (properly), hoped in to get to the forest. So far so good.
> Generation and loading is done.
> However when i try to hop into the portal in the Twilight Forest (the one i just came out of) to get to my base in the OVerworld, it just generates a completely new Portal several chunks away from my OW base.
> These 2 portal however seem to be linked up fine, no problem. It just ignores my initial Portal on the OW base upon first return... which is annoying.
> 
> I tried the above mentioned solutions, but with no luck on fixing the issue...
> 
> I use the same version as user mvdstam who opened the issue: 3.2.51 and I am also in Kappa Mode.
> However i play on Singleplayer.

I have the same issue exactly how you discribed it.
