### ISSUE TITLE
Game Crash On Launch

### ISSUE THREAD

**Issue by purple6418** [Cazadorsniper/PO3#833]
**Pack Version:**3.2.51
**Pack Mode:**Normal
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**Had issues with non-full sized blocks acting glitchy. The blocks seemed to move around visually although they never actually moved. After restarting computer, the games crashes on launch now and says ContentTweaker is to blame.

**Steps to reproduce:**Launch the game. (I don't know how to make the blocks act weird like they were doing.)

**Crash log (use pastebin or issue will be closed):**https://pastebin.com/6RtdKPcn

**Comment by Cazadorsniper** [comment]
Did you use any spectre illuminators?

**Comment by purple6418** [comment]
Yes, I did. Is there a way to go about resolving the issue by removing them remotely? Or will I just have to restart?

**Comment by Cazadorsniper** [comment]
You can try reinstalling the pack then moving the world over.
World Edit might work.
