### ISSUE TITLE
Project Ozone 3 Minecraft Forge incorrect

### ISSUE THREAD

**Issue by usljess** [Cazadorsniper/PO3#835]
# Use the search function before reporting to see if the issue has been reported before.
**PO3-3.2.51:**
**1.12.2:**

Will post a screenshot of the error i am getting below

![image](https://user-images.githubusercontent.com/61167782/74770795-93483400-5252-11ea-943e-a30e73370d3a.png)

**Comment by Cazadorsniper** [comment]
Have you tried updating forge? PO3 comes with 14.23.5.2847.
