### ISSUE TITLE
Intem apear in inventory

### ISSUE THREAD

**Issue by anthonyL05** [Cazadorsniper/PO3#836]
**Pack Version:** 3.2.51
**Pack Mode:** ozone 3 kapa mod
**Singleplayer, Multiplayer, or LAN?:** Single player

**Description:** 
Since some day  i dont stop to get 4 item in inventory. I try to stay without moving item keep coming. In all the world i have test its the same ( nether landia twilight end). 
- coal ( even if i have a /dank/null with it inside it goes in inventory directly so its not a drop of item around) 
- melon slice with unroconize item texture
- saddle
- emerald slice with unroconize item texture
In something like less than 10 hour with the bug i get 500 saddle and 60 emerald 200 slice and lot of coal ( cant get the number because i already have a lot before) 

Its realy boring to have to clear inventory so often because of that...
I dont know if someone know what can happend.

**Steps to reproduce:**
I try to reproduce it in a new word but not happend.

**Crash log (use pastebin or issue will be closed):**
I have no idea of wich log can help. If some is need ask me i will try to put them.

**Comment by Cazadorsniper** [comment]
This is a similar issue that someone else had and still have no idea what causes it.

**Comment by SongHout** [comment]
It is the friscon ingot from landium modifier on tinker tools, it give trash when you select it, change the tool part and it will be gone!
