### ISSUE TITLE
Redstone alloy can be crafted from Redstone blocks in the factorizer-split

### ISSUE THREAD

**Issue by griffster** [Cazadorsniper/PO3#837]
Not sure if intentional but Redstone allot can be created from Redstone blocks using the factorizer.

**Comment by Cazadorsniper** [comment]
and it takes redstone alloy to craft the redstone blocks right.

**Comment by griffster** [comment]
My bad, I totally assumed that Redstone blocks would be craftable through normal redstone. Just stumbled upon this.

**Comment by Cazadorsniper** [comment]
no problem
