### ISSUE TITLE
Server Launch Issue

### ISSUE THREAD

**Issue by MrDrStevenson** [Cazadorsniper/PO3#838]
I ran the server using a slightly modified command line, but I get the same error when I run it with the stock command.  I don't know exactly what this means, but I know that the server machine broke.  Please let me know if you need any other information.

The only settings that were changed is a EULA=TRUE and the pack was set to kappa mode.

![PO3 Server Error](https://user-images.githubusercontent.com/49931662/74867392-97dc1d80-5322-11ea-8223-818b3c0ce211.JPG)

**Comment by Cazadorsniper** [comment]
Try updating Java or at least using a JRE not JDK.

**Comment by MrDrStevenson** [comment]
Yeah that solves the problem! I forgot that my laptop had died at one point and I had to wipe the hard drive and then I never installed Java again.
