### ISSUE TITLE
Gros bugs de crafts

### ISSUE THREAD

**Issue by ppierrer** [Cazadorsniper/PO3#843]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.51
**Pack Mode:**
**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:Il y a un grand nombre de problème avec les crafts, parfois une fois un craft finit dans la case où on récupère le craft l'objet reste plusieurs fois, cela duplique la recette sans utiliser plus de ressources, Ensuite je ne peux pas utiliser le shift clique ou rester appuyé sur le clique droit sinon je suis presque sûr de voir mes items disparaître totalement ou en partie.**

**Steps to reproduce:**
craft 
**Crash log (use pastebin or issue will be closed):**
http://pastebin.fr/61032

**Comment by Cazadorsniper** [comment]
Remove XCPatch from mods folder.
