### ISSUE TITLE
Latex processing unit 2 recipes (Not sure if this is a bug, a mistake or something like that, but it looks like it)

### ISSUE THREAD

**Issue by Lolicon2110** [Cazadorsniper/PO3#844]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Both the modified and standard recipe for the latex processing unit are available

**Steps to reproduce:** Looking on JEI

**Crash log (use pastebin or issue will be closed):**

**Comment by BellKiller** [comment]
Looks like the same thing is happening to the mob crusher

**Comment by Cazadorsniper** [comment]
This is likely an issue between the config adding the recipes and a script removing them.

**Comment by NeosGhost** [comment]
I was looking at the script files and it seems that the removal is only  run in the kappa mode script..should that be in the all modes scripts instead?

**Comment by Cazadorsniper** [comment]
no

**Comment by Cazadorsniper** [comment]
actually yes
