### ISSUE TITLE
Spectre Energy Injector Glitching Out

### ISSUE THREAD

**Issue by SavBunni** [Cazadorsniper/PO3#847]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.51
**Pack Mode:**Titan
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**
I was putting energy into the Spectre Energy Injector and it just randomly gets negative billion RF.
![2020-02-22_16 49 33](https://user-images.githubusercontent.com/59836577/75100527-58b50300-5594-11ea-9a5f-68d38e90ee8f.png)

**Steps to reproduce:**
Insert energy into the spectre energy injector (preferably with a creative generator).

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Probably too much energy at 1 time.
