### ISSUE TITLE
Conflicting Interaction Between the Angel Ring and Ender Dragon Armor

### ISSUE THREAD

**Issue by SavBunni** [Cazadorsniper/PO3#848]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.51
**Pack Mode:**Titan
**Singleplayer, Multiplayer, or LAN?:**Single player

**Description:**
I was wearing a full Ender Dragon armor set and an angel ring. When flying, removing one of the armor pieces from the set cancels flight, even if I have the angel ring on.

I have more than enough GP for the Angel Ring to work.

**Comment by Cazadorsniper** [comment]
That is mod interactions, there nothing I can do about that except suggest using 1 type of flying capable item.
