### ISSUE TITLE
Void tear in AE ME System

### ISSUE THREAD

**Issue by Cronos4** [Cazadorsniper/PO3#85]
**Pack Version:** newest (3.0.38)

**Description:** when you fill a void tear with items and throw them in the ME System you cant get them out again. 
Does not matter if it is activated or deactivated. 
Happens since the last patch (with the deactivation of the crafting of the void tear)

**Steps to reproduce:** put items in a void tear and store it in a me-system

**Crash log:** Game did not crash

**Comment by Pival81** [comment]
Do you have a barrel or a drawer with a void tear in it connected to your me network? maybe it's trying to put the tear there and voiding its nbt data in the process.

**Comment by Cazadorsniper** [comment]
remove void tears using the export bus and a fuzzy card.
