### ISSUE TITLE
[Suggestion] Flat Colored Blocks

### ISSUE THREAD

**Issue by Elrol** [Cazadorsniper/PO3#850]
I was hoping to see if you would add Flat Colored Blocks. For people like me, having them along with Chisel & Bits, provide an amazing amount of possibilities for building and decorating things. 

I am playing on a server that runs the pack, and as I was playing I kept finding myself wishing there were more blocks and colors that I could use to make decorations for my base. 

Either way, thanks for reading, and keep up the good work.

**Comment by Cazadorsniper** [comment]
We're not planning on adding any mods, sorry.
