### ISSUE TITLE
disconnect 

### ISSUE THREAD

**Issue by dityareborn** [Cazadorsniper/PO3#851]
Pack Version:3.2.51
Pack Mode:kappa
Singleplayer, Multiplayer, or LAN?:Multiplayer with Hamachi

Description: Some time after start we started issuing disconnect problems after starting lord craft i think not totally sure what makes it happen. I(host) play with 3 my friends and all achieved this bug couple times the game just disconnecting from the server. Here is examples of it https://youtu.be/fdOLWQVpufk?t=2387Y   https://youtu.be/fdOLWQVpufk?t=3705
it dont aper in another worlds 

Steps to reproduce: dont rly know how to reproduce it 

Crash log (use pastebin or issue will be closed):We have no crash log

**Comment by Cazadorsniper** [comment]
Do you have a latest.log when the disconnects were happening?

**Comment by dityareborn** [comment]
https://pastebin.com/BMhVUuAZ  hosts 
https://pastebin.com/ErJBtHAN who crashed

**Comment by Cazadorsniper** [comment]
Is the server using any plugins or anything added to the pack at all?

**Comment by dityareborn** [comment]
its clear pack no plugins. 
i lied a bit we are playing with with open to lan function with hamachi

**Comment by Cazadorsniper** [comment]
All I can see is that its a connection issue.

**Comment by dityareborn** [comment]
we havent got it on another modpacks

**Comment by Cazadorsniper** [comment]
can you post the entire log here?

**Comment by dityareborn** [comment]
no right now maybe later or tommorow rn we are checking maybe its rly connection problem

**Comment by dityareborn** [comment]
[latest.log](https://github.com/Cazadorsniper/PO3/files/4250319/latest.log)
[latest (1).log](https://github.com/Cazadorsniper/PO3/files/4250327/latest.1.log)

cant post on paste bin to huge for it

**Comment by Cazadorsniper** [comment]
From the first log all i can see is that someone might be exploring twilight forest quite a bit and that you should remove the translocator block from lordcraft.

**Comment by dityareborn** [comment]
[latest (4).log](https://github.com/Cazadorsniper/PO3/files/4251693/latest.4.log)
[latest.log](https://github.com/Cazadorsniper/PO3/files/4251694/latest.log)
deleting it didnt helped. rn we got 5 disconnects in a row it dont rly depend on connection i was pinging my friend through cmd and it was pretty stable

**Comment by dityareborn** [comment]
it doesnt disconnect in another worlds

**Comment by Cazadorsniper** [comment]
Maybe a mod issue then, have you've tried a proper server not lan?

**Comment by dityareborn** [comment]
no

**Comment by dityareborn** [comment]
so that is lord craft problem after removing all blocks from lord craft it stopped disconnecting
(if u want u can close )

**Comment by hlevine9** [comment]
To host a server without lan, try port-forwarding, and then set up a domain to your IP. This is so that when you set up the server, you provide your IP for other people to connect to, and instead, they can use the domain you created. This should solve your issue.
