### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by marathonishalo6** [Cazadorsniper/PO3#852]
when i try to run the server .bat command prompt closes right away, and dosent do anything. when i try to run the forge file itself, dosent have the ram needed to run it. i have no idea why cmd prompt is closing like this, but i cant run the server at all. can someone please help me?

**Comment by Cazadorsniper** [comment]
Edit the .bat to start the minecraft server .jar, accept eula, delete the world save that pops up, edit the .bat to start forge.jar.

**Comment by marathonishalo6** [comment]
> Edit the .bat to start the minecraft server .jar, accept eula, delete the world save that pops up, edit the .bat to start forge.jar.

when i try this, an error pops up saying invalid or corrupt jarfile

**Comment by Cazadorsniper** [comment]
re-download the server files.

**Comment by marathonishalo6** [comment]
> re-download the server files.

i redownloaded the files and tried to open the start .bat file, and it still opens then closes right away with nothing happening afterwards.

**Comment by Cazadorsniper** [comment]
Did you try doing what I said before? I recommend you look up on youtube how to start a modded server.

**Comment by marathonishalo6** [comment]
> Did you try doing what I said before? I recommend you look up on youtube how to start a modded server.

i followed what a video did, and tried what you said. the .bat still just brings up a cmd prompt window for less then a second then nothing. when changing to .jar it says its invalid or corrupted

**Comment by Cazadorsniper** [comment]
You're not changing the .bat to .jar. 
Right-click the .bat then press edit.
Change forge-1.12.2-14.23.5.2847-universal.jar to minecraft_server.1.12.2.jar.
Start server (it should stop soon after).
Accept the Eula (the .txt file that shows up).
Change minecraft_server.1.12.2.jar back to forge-1.12.2-14.23.5.2847-universal.jar.
Then wait a long time for everything to load, if you're trying to do skyblock then put botania-skyblock where it says level-type= in the server.properties (erase the default world before starting the server again to regenerate the world).

**Comment by marathonishalo6** [comment]
> You're not changing the .bat to .jar.
> Right-click the .bat then press edit.
> Change forge-1.12.2-14.23.5.2847-universal.jar to minecraft_server.1.12.2.jar.
> Start server (it should stop soon after).
> Accept the Eula (the .txt file that shows up).
> Change minecraft_server.1.12.2.jar back to forge-1.12.2-14.23.5.2847-universal.jar.
> Then wait a long time for everything to load, if you're trying to do skyblock then put botania-skyblock where it says level-type= in the server.properties (erase the default world before starting the server again to regenerate the world).

i did all that but cmd prompt still closes as soon as it pops up and does nothing afterwards. window (and program itself) just seems to crash as soon as its used no matter what i do to it. at this point i might just say screw it and ether find a server running it or maybe paying to run one. since this seems to fail every time.

**Comment by marathonishalo6** [comment]
update: i added "pause" on the second line of the start .bat and now it stays up, and shows this error:

`The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

**Comment by Cazadorsniper** [comment]
You can try updating java (make sure its 64bit).
How much ram does your PC running the server have?

**Comment by marathonishalo6** [comment]
> You can try updating java (make sure its 64bit).
> How much ram does your PC running the server have?

my java is 64bit (im pretty sure anyway dont know how to check) and is updated. the ram my computer has installed is 12GB

**Comment by Cazadorsniper** [comment]
you can try this solution: https://www.youtube.com/watch?v=Yr9S1kOmWPk

**Comment by marathonishalo6** [comment]
> you can try this solution: https://www.youtube.com/watch?v=Yr9S1kOmWPk

i did what the video showed and it sadly gives the same error

**Comment by Cazadorsniper** [comment]
Then I have no idea.

**Comment by marathonishalo6** [comment]
ahh ok, thx for your help anyway. love your modpacks!
