### ISSUE TITLE
Deep dark portal not working

### ISSUE THREAD

**Issue by Tekomishi** [Cazadorsniper/PO3#854]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.51
**Pack Mode:**Normal
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
Deep dark portal not working.
**Steps to reproduce:**
I creat the deep dark portal place and down and when I click on it nothing happens. I don`t crash, and it doesn`t teleport me.
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
stand on it.
