### ISSUE TITLE
End spawn in the center

### ISSUE THREAD

**Issue by anthonyL05** [Cazadorsniper/PO3#856]
**Pack Version:**
ozone 3  3.2.51
**Pack Mode:**
kappa mode
**Singleplayer, Multiplayer, or LAN?:**
Single player

**Description:**
I spawn in the end in the center where the dragon die first time i take the end cake. Its make obsidian in midle and no dragon eggs can spawn ( no litle tower) 

I think its possible to disable the midle spawn.

**Steps to reproduce:**
Unlucky spawn

**Crash log (use pastebin or issue will be closed):**
image du spawn
https://ibb.co/0nGMbCY

**Comment by hlevine9** [comment]
I'm sure this was intended. A way to avoid this is to, as soon as you can obtain Draconium, craft a dislocator, and a pedestal. Set up the Dislocator to teleport you to the edge of the island, so that you do not destroy any Dragon Eggs when teleporting.
