### ISSUE TITLE
Metal press duplicate recipes

### ISSUE THREAD

**Issue by GodlyIdea** [Cazadorsniper/PO3#857]
**Pack Version:** 3.2.51
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer
**Description:**
Metal press has some duplicate recipes.
Iron Ingot to Iron Plate (Immersive Engineering)
Gold Ingot to Gold Plate (Immersive Engineering)
The plates work with other recipes, but should still be removed as this is the only machine that makes that version of the plate.
(In every other place only the Thermal Expansion plates are shown in JEI)
**Steps to reproduce:**
Build Metal Press.
Input either Iron Ingot or Gold Ingot to get corresponding Plate (Immersive Engineering).
OR
Look Metal Press recipes from JEI to see them.
**Crash log (use pastebin or issue will be closed):**
Not a crash so no log.

**Comment by Cazadorsniper** [comment]
There is no need to remove them.

**Comment by GodlyIdea** [comment]
Having them doesn't break stuff but in overall those plates are blacklisted in JEI and because Metal Press makes the Immersive Engineering Plates not the Thermal Expansion Plates that's why I opened the issue.

Though it seems lines in "\scripts\all_modes\all_immersive.zs" or "\scripts\kappa\kappa_immersive.zs":
mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:39>);
mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:40>);
won't remove the recipes.

**Comment by Cazadorsniper** [comment]
This is a Unidict/Instantunify pack so that is why they are hidden from JEI and even if the metal press makes the IE plates they will turn into TE versions because of Instantunify.

**Comment by GodlyIdea** [comment]
Small correction on my part that the plates are actually Thermal Foundation (TF) ones not Thermal Expansion (TE).
Turn into TE/(TF*)? Feeding Iron Ingots to the Metal Press yield the IE version of plates (Look image. On the ground is the TF version of plate):
![image](https://user-images.githubusercontent.com/61575892/75570968-eeeb9c00-5a60-11ea-9cd7-c61cb500ba1e.png)

**Comment by Cazadorsniper** [comment]
see previous comment.
