### ISSUE TITLE
chunk loading

### ISSUE THREAD

**Issue by Cronos4** [Cazadorsniper/PO3#86]
**Pack Version:** 3.0.38

**Description:** chunks are not loaded when you change the dimension
realised on my end tour, that the items are not beeing sucked into the me system 

**Steps to reproduce:** i have no idea
i placed an ender chest from "EnderStorage" next to my system and let put an Importbus onto it. 
While i was in the overworld it worked as soon as i entered the end the items stayed inside of the chest/pouch

**Crash log:**game did not crash

**Comment by billyty08** [comment]
Ftb chunk loading is disabled in the configs--# Enables chunk loading. If chunk_claiming is set to false, changing this won't do anything.
    B:chunk_loading=false
You need to use chicken chunks

**Comment by billyty08** [comment]
A suggestion for Cazador- It might be a good idea to have a quest to make the chicken chunk loader to inform people about the ftb being off
