### ISSUE TITLE
Unable to Craft Overloaded's Energy Core

### ISSUE THREAD

**Issue by Yolopanther12** [Cazadorsniper/PO3#860]
**Pack Version:** 3.2.51
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** I am unable to craft Overloaded's Energy Core. I put the items in the crafting grid of the Basic Crafting Table but the result will either not appear or it will appear, but taking trying to take the result will not work. This obviously hampers some recipes in the game that require the Energy Core, namely the Multi Armor Set.

![asdf](https://user-images.githubusercontent.com/6549826/75604460-a5657600-5a8d-11ea-87fc-5f568fd740bc.gif)

**Steps to reproduce:** Try crafting an Energy Core. The result either does not appear or is not claimable from the crafting bench.

**Crash log (use pastebin or issue will be closed):** N/A

**Comment by Cazadorsniper** [comment]
The dense energy cell is doing that, ok.

**Comment by Yolopanther12** [comment]
Based on your reply I tried **charging the dense energy cell (and picking it up with a wrench so it keeps its charge)** and using that in the crafting recipe. It successfully let me craft the Energy Core.
Thanks.
