### ISSUE TITLE
Astral Sorcery Floating Crystal

### ISSUE THREAD

**Issue by MineplayerHDYT** [Cazadorsniper/PO3#861]
The generated Floating Crystals in the Landia Dimension are broken. They can not transmute Blocks. Only when I break the generated ones and replace then with one from the creative inventory. 

Modpack Version: 3.2.51

**Comment by Cazadorsniper** [comment]
What are you trying to make?

**Comment by hlevine9** [comment]
This is probably because the naturally spawned crystals have a tag associated with them telling it to not transmute blocks, or to be able to be broken.
