### ISSUE TITLE
Problem with obtaining Singularity of Rock Candy and Dark Iron

### ISSUE THREAD

**Issue by xsun2001** [Cazadorsniper/PO3#863]
**Pack Version:** 3.2.51
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** MultiPlayer

**Description:**
Every Singularity needs 9001 blocks to compress. As a result, I found the rock candy singularity and dark iron singularity are extremely hard to make. There's no candy ore and the only way to get it is to use a legacy sieve of Ex Creatio. Dark Iron is rare in its planet without any other method to get it. I wonder if it is too hard for normal mode or if my server has corrupted recipes.

**Comment by Cazadorsniper** [comment]
Rock Candy ore does exist. Can use the Wand of Animation for Dark Iron.

**Comment by xsun2001** [comment]
But I cannot find the candy ore anywhere. I used the chunk scanner in actually addictions but no luck. BTW, my server crashed when I scanning chunks in erebus dim.

**Comment by Cazadorsniper** [comment]
Have you've tried Lost Cities Dimension or Deep Dark (Landia might have it too)?

**Comment by xsun2001** [comment]
Not yet...... I forgot them...... (Landia has no candy ore)
