### ISSUE TITLE
Translocators not working properly

### ISSUE THREAD

**Issue by 1Puma12** [Cazadorsniper/PO3#864]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 5-2-2020
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:**When hooking up a translocator to a drawer, it won't recognise the void upgrade. full is full and the translocator won't push more in even with a void upgrade.

**Steps to reproduce:**
Translocator to drawer/drawercontroller. full drawer with void upgrade
**Crash log (use pastebin or issue will be closed):**
No crashes

**Comment by Cazadorsniper** [comment]
Add an empty, locked drawer to the network
