### ISSUE TITLE
Po3 Crash on start up

### ISSUE THREAD

**Issue by fclemo** [Cazadorsniper/PO3#865]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: Current build**
**Pack Mode:Titan**
**Singleplayer:**

**Description:Updated some of the mods and the pack crashes on start up (during the constructing mods phase) due to modular machinery. It says: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail. Error: net.minecraftforge.fml.common.LoaderException:java.lang.NoClassDefFOundError: hellfirepvp/modularmachinery/common/crafting/ComponentType$ComponantRegistryEvent**

**Steps to reproduce: Happens everytime I try to load the pack**

**Crash log https://pastebin.com/wrwpuDcG :**

**Comment by Cazadorsniper** [comment]
Reinstall the pack and don't update mods.
