### ISSUE TITLE
internal exception java.nio.channels.closedchannelexception

### ISSUE THREAD

**Issue by villi1996** [Cazadorsniper/PO3#869]
I was playing my survival modpack "Project Ozone 3 A New Way Forward" yesterday , and today, when I try to open the world it doesnt finally opens, it just only appears sometimes like a frame of my map an after that, it returns to world loading screen.

I can open other map if I create but this not.
I had to separate in 4 parts.... sry for the incoveniences..

https://paste.ubuntu.com/p/KYcB7qdmGP/

https://paste.ubuntu.com/p/xNGPcZqVtt/

https://paste.ubuntu.com/p/CJsdZNVk4X/

https://paste.ubuntu.com/p/HjDNWhn69H/

**Comment by Cazadorsniper** [comment]
What were you doing before it stopped loading?

**Comment by villi1996** [comment]
I was just looking minecraft screen.. with other stuffs open but nothing special

**Comment by Cazadorsniper** [comment]
You can try reinstalling the pack then move over your world, but I'm not sure if that will fix the error.

**Comment by villi1996** [comment]
I tried to reinstall and give the map to a friend and he tried also to open and neither..

**Comment by Cazadorsniper** [comment]
Have you tried restarting the world from a backup? location: Curse\Minecraft\Instances\PO3\backups

**Comment by villi1996** [comment]
oooh thx it works.. it wasnt last I had but its better restart of 0... So muchs thx!
