### ISSUE TITLE
Killing quests

### ISSUE THREAD

**Issue by Cronos4** [Cazadorsniper/PO3#87]
**Pack Version:**3.0.38

**Description:** no matter where or how often i kill the wither or ender dragon i never get the quests and therefore not the quests that follow this one 

**Steps to reproduce:** kill dragon or wither and see that you are still not able to detect/submit the quest :)

**Crash log:**

**Comment by Zapstur** [comment]
This is a known issue, you should have searched for other open issues before creating a new thread.

 The temporary solution uses commands to manually complete the quest; here's the steps to do so:

1.) Activate advanced tooltips by pressing the key combination "F3+H"

2.) Open the quest book, and hover over the problematic quests, there is a number in the title of the quest that you need for the following step

3.) Enter the command "/bq_admin complete ###"

If you can't use commands in your world, open it to LAN temporarily, and enable cheats for that session.
