### ISSUE TITLE
Draconic staff of power not crafting

### ISSUE THREAD

**Issue by jcplayer524** [Cazadorsniper/PO3#870]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode:**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by jcplayer524** [comment]
I have all the material for it but it’s not crafting 

Version:kappa mode

**Comment by Cazadorsniper** [comment]
pack version?

**Comment by jcplayer524** [comment]
Pack version:3.2.51
Pack mode:kappa
Multiplayer

**Comment by Cazadorsniper** [comment]
try updating

**Comment by jcplayer524** [comment]
What are the items data for it? How do I craft it? Is it the same as transmutation table with the philosopher stone where it needed to be charged?

**Comment by jcplayer524** [comment]
Nvm managed to craft it

**Comment by gafusss** [comment]
3.3.59, Singleplayer, Kappa
<details>
<summary>GIF</summary>

![staff](https://user-images.githubusercontent.com/17786071/89675021-e5107380-d8f1-11ea-99b2-c913436b9edf.gif)

</details>

Replacing the table, "+" from JEI, manually placing items, charged/non-charged draconic tools/flux-infused sword, removing enchantment from Fiery Sword - non of that helps.
