### ISSUE TITLE
In Agricraft when mutating crops I am getting overrun with weeds

### ISSUE THREAD

**Issue by bigmaciraq** [Cazadorsniper/PO3#871]
I am doing a **singleplayer** **playthrough** in **Titan**, and in 3.2.51 I had no problems when getting seeds to 10/10/10.  After the latest upgrade (3.2.52) though, I am getting overrun with weeds.  I don't have a problem with the weeds game mechanic if that was implemented, but I turn my back for a few minutes and everything with cross crop sticks is weeds.  

To replicate: Place a few cross crop sticks on some farmland and watch for a minute.  It doesn't take long.

**Comment by Cazadorsniper** [comment]
go to PO3\config\agricraft\json\defaults\vanilla\plants > weed_plant.json then disable the weed_plant then restart the pack
