### ISSUE TITLE
Angle Block in Dank Null deletes it when placed

### ISSUE THREAD

**Issue by calvissuperman** [Cazadorsniper/PO3#872]
Pack Version: 3.2.52
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: Put some angel blocks in my dank null and tried to place them. They work, but it immediately deletes the dank null from my hand. Everything in the dank null and itself is gone, even after a full reload of the world.

Steps to reproduce: Open a Dank Null > Place Angel Blocks inside > Select them with alt+click > Press right click while looking at open air to place them > Angel block is placed, but dank null and all its contents are deleted.

**Comment by Cazadorsniper** [comment]
There is nothing I can do about this.
