### ISSUE TITLE
PackMode Reset

### ISSUE THREAD

**Issue by sreekrishn** [Cazadorsniper/PO3#874]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.52
**Pack Mode:**kappa
**Singleplayer, Multiplayer, or LAN?:**singleplayer

**Description:**
On update the packmode file got changed and was reset to normal mode from kappa mode...
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Should read the the changelog.
