### ISSUE TITLE
Woot (unintentionally?) triggering ESM scaling.

### ISSUE THREAD

**Issue by Jimmy469** [Cazadorsniper/PO3#875]
---
name: Woot (unintentionally?) triggering ESM scaling.
about: Cross-mod interaction causing problems
title: ''
labels: ''
assignees: ''

---

# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.51 & 3.2.52 
**Pack Mode:** Personal Experience in Kappa, should affect all modes.
**Singleplayer, Multiplayer, or LAN?:** Personal Experience on MP, should affect all modes.

**Description:** I noticed that multiple patches have reduced ESM scaling because it feels rather ridiculous at times.

I think this is largely due to an unintended interaction between Woot and ESM. Namely, when Woot goes to generate it's loot tables, it spawns and kills the target mob 500 times (see woot.cfg)
`# Number of mobs to kill to learn from - higher is more accurate
    I:sampleSize=500`

When spawning bosses without a fixed loot table (such as the dragon), each time woot goes to "learn" what drops should be generated, it triggers 500x ESM scaling ticks. At an additive 0.6% damage per tick, that's +300% damage each time. You can see how this would cause mob damage to get insane relatively quickly.

Unfortunately I don't know a way to make this interaction less crappy. Perhaps using fixed loot tables for all bosses in Woot could do it, but that is a very clunky solution.

**Steps to reproduce:** Look at ESM.dat and record initial value. It is binary encoded but the values after "BossModifier" and before the last NULL byte are of interest. Build a woot factory and set it to a boss that hasn't had it's loot table generated yet (wither, big brother, etc). Do not use a boss with fixed loot (dragon) or a boss that you've already generated the loot table for (by previously building 
a factory for). Check ESM.dat again after saving and note how the value has changed.

Note that '/woot flush <mob>' can be used to clear Woot's loot table cache, and thus force 500 re-kills next time the factory of that type is used.

**Crash log (use pastebin or issue will be closed):** No crash.

**Comment by Cazadorsniper** [comment]
We were aware of what ESM does with Woot farms ever since normal mode.

**Comment by Jimmy469** [comment]
Any plans for a fix? At a glance, it could be possible to offer ESM a PR or feature request to add a dimension blacklist to it's death checker (https://github.com/Funwayguy/Epic-Siege-Mod/blob/1.12/src/main/java/funwayguy/epicsiegemod/handlers/entities/GeneralEntityHandler.java#128) but there hasn't been activity on the mod in 2 years. Is it still active?

**Comment by Cazadorsniper** [comment]
No plans for a fix.
