### ISSUE TITLE
Freeze on Boot (Hammer Core)

### ISSUE THREAD

**Issue by LeChikito** [Cazadorsniper/PO3#876]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
We have a PO3 Kappa server, but since the last update (3.2.52), the server freeze on boot (it didn't on 3.2.51). We have spend some time on searching which mod cause it, and we have found that it was Hammer Core. Is there a way to correct it or tell us a way to bypass it?

**Steps to reproduce:**
- Launch the server
- See it freeze after 16 seconds with the logs in the link below.

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/GrU24jyD

**Comment by Cazadorsniper** [comment]
Are you running Sponge?

**Comment by LeChikito** [comment]
Yes

**Comment by Cazadorsniper** [comment]
Sponge could be the reason.

**Comment by LeChikito** [comment]
Wait, sponge didn't change since the last update, and it is the reason? I know it is the reason of some problems, but there everything works perfectly in 3.2.51 and hammercore cause freeze in 3.2.52 but sponge don't change, so please, i am pretty sure to know where the problem is coming from 😁

**Comment by Cazadorsniper** [comment]
I did say it "could" be the reason and the only thing I can do is downgrade the mod lol. https://gitlab.com/DragonForge/HammerLib/issues/122

**Comment by Cazadorsniper** [comment]
Whomever owns the server tell them to find the asm folder, click on hammercore.xml then turn "<entry key="World.ITickable.Override">true</entry>" to false.

**Comment by LeChikito** [comment]
That works! Thank you very much for this fast and efficient answer 🤗
