### ISSUE TITLE
Left over recipe items break automation (Searing Crystals & Automation Interface)

### ISSUE THREAD

**Issue by pepijn777** [Cazadorsniper/PO3#877]
**Pack Version: 
3.2.52
**Pack Mode: 
Kappa
**Singleplayer, Multiplayer, or LAN?: 
Single

**Description: 
When crafting Searing Crystals in an Arcane Construct, the lava buckets used in the recipe will turn into empty buckets and will stay in the input slot. It appears to be impossible to extract items out of Modular Machine input slots so when automating these crystal, the input slot will become filled with empty buckets blocking any futher items from being inserted.
The same kind of problem happens when making Automation Interfaces in the Advanced Crafting Table. The recipe asks for a 64K Crafting Storage, and when the recipe completes, a Crafting Unit will take its place. When trying to automate this recipe with an Automation Interface of its own, this left over Crafting Unit will block any further recipes from being completed. It also does not seem possible to automaticly extract this left over item.

**Steps to reproduce: 
Build an Arcane Construct and an Advanced Crafting Table and try the mentioned recipes.

**Comment by Cazadorsniper** [comment]
I fixed the arcane construct recipes but not the crafting table recipe.

**Comment by pepijn777** [comment]
Nice, thanks! Is the other one intended?

**Comment by Cazadorsniper** [comment]
I fixed both, the 64k crafting storage not so much.

**Comment by Cazadorsniper** [comment]
Not sure if I fixed the 64k crafting storage, but we'll see.

**Comment by mkaito** [comment]
> Not sure if I fixed the 64k crafting storage

Nope, this is still a thing in 3.3.59.

Would you consider adding Packaged Auto to the pack as a workaround, or was its omission a design choice?
