### ISSUE TITLE
Epic Siege Mod causing server watchdog timeouts

### ISSUE THREAD

**Issue by Anaerin** [Cazadorsniper/PO3#878]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52 (also present in 3.2.51)
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer server

**Description:**
Epic Siege Mobs is causing watchdog timeouts, so the server crashes every so often

**Steps to reproduce:**
No idea, have a multiplayer server running?

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/uusdHsJM

**Comment by Cazadorsniper** [comment]
In server.properties max-tick-time=-1

**Comment by LemonTea19** [comment]
My friend and I also encountered the same issue, but after he set the max-tick-time=-1 the world's latency is significantly high (nearly 60-100s per tick)
