### ISSUE TITLE
HELP ubuntu pastebin because pastebin doesnt work 

### ISSUE THREAD

**Issue by EmirhanGamer71** [Cazadorsniper/PO3#880]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**latest which is 3.2.52
**Pack Mode:**normal I didnt change it
**Singleplayer, Multiplayer, or LAN?:**single

**Description:**
help it opens once than it gets stuck at 7/7 
**Steps to reproduce:**
idk
**Crash log (use pastebin or issue will be closed):**
https://paste.ubuntu.com/p/BgVSRS2xWb/ I used ubuntu paste because it doesnt work in turkey even with vpn

**Comment by Cazadorsniper** [comment]
Can you load the pack up again using less memory 6G should do fine and give it time to load?
