### ISSUE TITLE
Avaritia: Crystal Matrix block to Crystal Matrix Ingot

### ISSUE THREAD

**Issue by TheGriffer99** [Cazadorsniper/PO3#881]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** You did it on purpose that you have to use the factorizer in split mode to get the Crystal Matrix Ingot from the Crystal Matrix block or it's a missing recipe? 
Thanks for the answer

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Are you sure you're in normal mode?

**Comment by TheGriffer99** [comment]
Yes. I am.
This is my packmode.cfg

# Configuration file

general {
    S:acceptedModes <
        normal
        titan
        kappa
     >
    S:packMode=normal
}

I've never changed it since i started playing the pack.

**Comment by Cazadorsniper** [comment]
ok
