### ISSUE TITLE
Lordcraft Magnetic spell

### ISSUE THREAD

**Issue by pawkac06** [Cazadorsniper/PO3#882]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52 and below
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Singleplayer, LAN

**Description:** 
Issue 1: can't disable Magnetic spell in Lordcraft
Issue 2: Items get deleted when you mine something while crouching (crouching triggers Magnetic spell)

**Steps to reproduce:**
1. Learn magnetic in research
2. Enable magnetic in spells page of Lordcraft Knowledge Book
3. Mine anything while crouching
4. Item gets deleted

**Crash log (use pastebin or issue will be closed):**
no crashlog

**Comment by cjhwick** [comment]
This was frustrating me so I did some messing in the nbt data, I was able to basically lower my Earth skill level to 4 (which is before magnetize is available).

Log out of the game, stop the server (if playing on a server), then restart the server after nbt changes.

First navigate to your world folder in an nbt explorer > playerdata > Your UUID > ForgeCaps > lordcraft.level > set level_1 to 4 > Save NBT. Should fix it until it's sorted by the LordCraft dev.
