### ISSUE TITLE
Enable ExU2 filter again

### ISSUE THREAD

**Issue by UnPure** [Cazadorsniper/PO3#883]
I know that transfer nodes are disabled because of potential lag but the filter have more uses than just for item/fluid transfer. They are super important for easy use of item/fluid trashcans through cascading filter. It would be nice if the filter could be enabled again. Or are there any other reasons why they are disabled?

**Comment by Cazadorsniper** [comment]
I believe it was the filters that were causing the lag while the cables would occasionally crash. Recommend using a different way to trash things like Ender IO conduits.
