### ISSUE TITLE
Creeper explosions

### ISSUE THREAD

**Issue by Lionile** [Cazadorsniper/PO3#884]
This isn't really an immediate issue, and I'm sure a lot of people are familiar with it not just from PO3 but previous versions of PO, but it would be nice to get it resolved anyway.

So.. creepers when they "triggered" don't stop exploding when you step away from them and from what I got there isn't a way to not trigger them, for example making a half block gap so they can't see you, placing the mob farm above your head, placing the mob farm below, ext.

Now I know that a lot of people will want to answer "Just turn off mob griefing", which is what I did in PO2 because I just couldn't be bothered to fix it. While that is effective I feel as tho I'm cheating, since messing up and getting a creeper to explode something you made is a part of minecraft and removing it feels like I'm basically turning on creative.

This problem has been around for quite a while, and even tho I don't make minecraft mods, and I don't really know java I feel like it shouldn't be too big of a problem to fix it, so if anything could be done about that it would be real nice. That's it from me, cya.

**Comment by Cazadorsniper** [comment]
All you need to do is one shot them. Try using a Certus Quartz cleaver from Tinkers' Construct.
