### ISSUE TITLE
KAPPA lord will reset after unlocking

### ISSUE THREAD

**Issue by zdd233** [Cazadorsniper/PO3#887]
Pack Version: Po3 3.2.52
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description:
Lord after the unlocking and continuous viewing exit, it will reset itself. If it is unable to unlock the book, it will consume but not unlock according to the solution required by him. It will exit the book connection reset.

**Comment by Cazadorsniper** [comment]
What?

**Comment by zdd233** [comment]
> 什么？

In the kappa server, when the lordcraft mod uses insciription to unlock those, it will reset every time after unlocking, and the 26 letters will even reset after exiting the book. Now the next stage cannot be performed, and all are stuck.

**Comment by zdd233** [comment]
> 什么？

This kappa is a server using cat

**Comment by zdd233** [comment]
> 什么？

what happen

**Comment by Cazadorsniper** [comment]
Something wrong with researching or the Lord characters?
