### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XxRagingKillerX** [Cazadorsniper/PO3#889]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by XxRagingKillerX** [comment]
https://pastebin.com/bcQ9wdEL

**Comment by Cazadorsniper** [comment]
Dedicate more ram

**Comment by XxRagingKillerX** [comment]
how much does it need ive given it 10 gbs

**Comment by XxRagingKillerX** [comment]
also howdo i get the sklk wrld

**Comment by XxRagingKillerX** [comment]
sky block world

**Comment by Cazadorsniper** [comment]
garden of glass world type.
