### ISSUE TITLE
AE2 only giving channels via dense cable

### ISSUE THREAD

**Issue by sreekrishn** [Cazadorsniper/PO3#890]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.52
**Pack Mode:**kappa
**Singleplayer, Multiplayer, or LAN?:**singleplayer

**Description:**
When connecting a dense cable directly or through p2p is only giving 8 channels..
**Steps to reproduce:**
1.connect a dense cable from me controller
2.only 8 devices is getting channels and not the rest
**Crash log (use pastebin or issue will be closed):**

![2020-03-09_21 47 29](https://user-images.githubusercontent.com/36627174/76235375-04c34300-6251-11ea-88ef-0192339cc441.png)
![2020-03-09_21 47 33](https://user-images.githubusercontent.com/36627174/76235381-07259d00-6251-11ea-8190-7cb3211d025b.png)
![2020-03-09_21 47 36](https://user-images.githubusercontent.com/36627174/76235385-07be3380-6251-11ea-9769-0213dd3768c3.png)
![2020-03-09_21 47 50](https://user-images.githubusercontent.com/36627174/76235389-0856ca00-6251-11ea-8d6b-93bc3f9b3117.png)

**Comment by Cazadorsniper** [comment]
Are you using smart cables that are connected to the dense cable?

**Comment by sreekrishn** [comment]
No direct dense cable line

**Comment by Cazadorsniper** [comment]
Try normal smart cable connected to the dense cable or try tearing everything down and remaking it.

**Comment by sreekrishn** [comment]
Tried tearing everything and remaking it and there was no change

**Comment by newt111** [comment]
Me Interfaces only transmit 8 channels. You need to redo the cube with more cables. Cables all along the bottom should work, put cable anchors on the assemblers. If you still have issues, tear down the whole cube and redo it.

**Comment by sreekrishn** [comment]
Ohhhh kk
