### ISSUE TITLE
Found Possible source of previous client only lag issue, but idk how to properly describe the source

### ISSUE THREAD

**Issue by jinga986** [Cazadorsniper/PO3#891]
3.2.52
Titan Mode
SinglePlayer

Description: Non-stackable items stacking and clogging up tps and Sorting System. Video link provided because a single picture can't properly do this issue justice

Steps to reproduce: I would also love to know because this is just confusing me

Crash log (use pastebin or issue will be closed): No crash log (Yet) but here is a link to the video of the issue
https://youtu.be/fooiCz-ljH0

**Comment by Cazadorsniper** [comment]
I recommend trashing all of that

**Comment by GodlyIdea** [comment]
Weird behaviour indeed.
As for steps you could specify how your sorting stuff is set up.
From the video the bag count goes up with just 1 second like 1 million - feels like they get duplicated somehow.

If you don't open them just dump all the bags to "bag chest" (or whatever its called) or if you open them then just overflow send to the "bag chest".
The "bag chest" allows bag conversion as well.

**Comment by jinga986** [comment]
Phantom interfaces connected to barrel controller, the small crate, and the bag chest. previously had transfer node with filter pulling out unwanted items into a trash can, now using item conduit with filtered can. Translocators were used to transfer stacks at a time to the bag chest and barrel controller. Removed everything and overflow stacking (idk what else to call it) stopped but assuming it's still gonna happen haven't wanted to touch it again. Client side lag still happens, even on Peaceful too

**Comment by Cazadorsniper** [comment]
Maybe the bag chest causing the dupe.

**Comment by itsjusttriz** [comment]
Can confirm, theres an issue with using EIO conduits to transfer lootbags causing them to duplicate mid-transfer. I used to have a setup purposed for this and my console was being spammed to high heavens with dupe errors.
