### ISSUE TITLE
Singularity recipes

### ISSUE THREAD

**Issue by TheGriffer99** [Cazadorsniper/PO3#893]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** Quantum Compressor not accepting diamond block, lead block, titanium block, ardite block, knightmetal block, lunar block, idk if i'm doing something wrong..

![2020-03-10_02 05 04](https://user-images.githubusercontent.com/49167096/76269971-ef134500-6273-11ea-87af-a7f42b8cc091.png)
![2020-03-10_02 40 35](https://user-images.githubusercontent.com/49167096/76271438-cd688c80-6278-11ea-8676-5dd99ab9561e.png)
![2020-03-10_02 41 36](https://user-images.githubusercontent.com/49167096/76271441-d0637d00-6278-11ea-88b0-89db59e2e72f.png)
![2020-03-10_02 41 47](https://user-images.githubusercontent.com/49167096/76271445-d22d4080-6278-11ea-883d-5122165e66fe.png)
![2020-03-10_02 52 21](https://user-images.githubusercontent.com/49167096/76271911-3ac8ed00-627a-11ea-89f9-cbcc9cc05ce8.png)
![2020-03-10_02 55 04](https://user-images.githubusercontent.com/49167096/76272065-9abf9380-627a-11ea-8483-551ad0759dd5.png)

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
break it then place it back down.

**Comment by TheGriffer99** [comment]
Titanium one still not working, the rest works fine. I think it's a recipe issue, cause in the recipe there's the titanium from Thermal Solars but when you have it in you inventory it automatic transform into the Galacticraft one, but i'm not sure about it.

**Comment by Cazadorsniper** [comment]
already fixed it.

**Comment by TheGriffer99** [comment]
Thanks
