### ISSUE TITLE
Dank Null duplication

### ISSUE THREAD

**Issue by Kontajo** [Cazadorsniper/PO3#894]
When holding the Dank null in inventory and right clicking the Dank null docking station and then proceeding to shift + right click the Dank null docking station again duplicates the Dank null.

In this zip file you will find a short video of how i did it.
I hope this helps and it can be fixed

[DankNullDuplication.zip](https://github.com/Cazadorsniper/PO3/files/4312195/DankNullDuplication.zip)

**Comment by Kontajo** [comment]
When holding the Dank null in inventory and right clicking the Dank null docking station and then proceeding to shift + right click the Dank null docking station again duplicates the Dank null.

In this zip file you will find a short video of how i did it.
I hope this helps and it can be fixed


[DankNullDuplication.zip](https://github.com/Cazadorsniper/PO3/files/4312183/DankNullDuplication.zip)

**Comment by Cazadorsniper** [comment]
https://github.com/p455w0rd/DankNull/issues/262
