### ISSUE TITLE
Server keeps crashing 

### ISSUE THREAD

**Issue by Riptide825** [Cazadorsniper/PO3#895]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
Before update server tick would gradually go up through out the day until finally hitting 60 seconds a tick and crashing since the update the server tick goes up quickly after launch to 5-15 seconds then crashing shortly after.

**Steps to reproduce:**
Happens each time we launch the server 

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/9tsx7Daw

**Comment by GodlyIdea** [comment]
Similar issue:
https://github.com/Cazadorsniper/PO3/issues/679
server.properties > max-tick-time=-1
