### ISSUE TITLE
Post pack update recipe failures

### ISSUE THREAD

**Issue by mechtech2010** [Cazadorsniper/PO3#896]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**  3.2.52
**Pack Mode:**  kappa
**Singleplayer, Multiplayer, or LAN?:**  multiplayer server

**Description:**  The following recipes no longer work after server and client updates today.
Smeltery controller, smeltery seared tanks, table, and casting basin.
Crushing table recipe no longer completes either.

**Steps to reproduce:**
Deleted server files and reinstalled.
Deleted client files and reinstalled

**Crash log (use pastebin or issue will be closed):**
No crash, recipes will not complete.

**Comment by Cazadorsniper** [comment]
is the client and server on Kappa mode?

**Comment by mechtech2010** [comment]
yes

**Comment by Cazadorsniper** [comment]
are you sure?

**Comment by mechtech2010** [comment]
yes. 1 log gets me 1 plank, etc, etc

**Comment by Cazadorsniper** [comment]
after changing modes both the client and server need to be restarted.

**Comment by mechtech2010** [comment]
The server was put into kappa in the config prior to server start up. Client was put into kappa as well. I will perform restarts and report back to be sure.

**Comment by Cazadorsniper** [comment]
You can copy over the scripts folder from the client to the server and try that.

**Comment by mechtech2010** [comment]
Restarts did not fix the issues. I will try the scripts folder now.

**Comment by mechtech2010** [comment]
![2020-03-11_20 27 16](https://user-images.githubusercontent.com/62085740/76484399-edae5d80-63d6-11ea-98a1-49499c2b0442.png)

![2020-03-11_20 27 37](https://user-images.githubusercontent.com/62085740/76484412-f7d05c00-63d6-11ea-958a-d0abd4dea159.png)


![2020-03-11_20 27 47](https://user-images.githubusercontent.com/62085740/76484421-fc951000-63d6-11ea-841e-b1e9c50c4b01.png)


![2020-03-11_20 28 15](https://user-images.githubusercontent.com/62085740/76484432-0159c400-63d7-11ea-98c3-fb0ff98d7793.png)

**Comment by mechtech2010** [comment]
Script files from client were uploaded to the server. kappa has been verified on both server and client. Restarts have been done.

Everything worked fine until I allowed the server and client to update today. The porcelain smeltery and many other recipes work fine, but these are some of the ones I have found so far.

**Comment by Cazadorsniper** [comment]
Look at the recipes again, they should require the porcelain versions in their recipe.

**Comment by mechtech2010** [comment]
![2020-03-11_20 40 50](https://user-images.githubusercontent.com/62085740/76485804-bd68be00-63da-11ea-9049-b83f7c196e03.png)


reconfirmed all in kappa, but it is clearly not a kappa recipe as you said.

Config file says Kappa in server files and client. Not sure what to do here.

**Comment by mechtech2010** [comment]
![2020-03-11_21 02 11](https://user-images.githubusercontent.com/62085740/76486099-9fe82400-63db-11ea-8e4c-13a26807f90a.png)

**Comment by mechtech2010** [comment]
![2020-03-11_21 04 10](https://user-images.githubusercontent.com/62085740/76486195-e3db2900-63db-11ea-815d-61ed73d61e36.png)

**Comment by mechtech2010** [comment]
Issue is resolved.

Prior to launching the client the pack had been set to kappa under config packmode file as instructed. After running the command in game and then restarting again everything works.

Even though the pack mode file said kappa, I was not in kappa for some reason. Sorry to send up false alarms and wasting your time.
