### ISSUE TITLE
Transmutation Table Recipe Consumes Philosophers Stone

### ISSUE THREAD

**Issue by Jimmy469** [Cazadorsniper/PO3#898]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer (Local server, single user)

**Description:** When crafting the transmutation table, the philosophers stone is consumed (instead of left behind like a bucket). This could be intentional, but there's no indication that the stone is used up and it's never used up in any other recipe, making it somewhat of a shock.

**Steps to reproduce:** Craft a transmutation table.

**Crash log (use pastebin or issue will be closed):** No crash.

**Comment by Jimmy469** [comment]
I checked the scripts, and saw that the philo stone is explicitly marked .noReturn() in kappa_9x9.zs so I presume this is intentional behavior.

In that case, a warning would be nice when breaking from convention (philo stone is never consumed elsewhere). Perhaps just a line of text in the quest book would help.

**Comment by Cazadorsniper** [comment]
I can do that.
