### ISSUE TITLE
[Game Breaking](Video) Drawn vector entities or multiblocks all moving around on screen at once

### ISSUE THREAD

**Issue by KINGJOJO7086** [Cazadorsniper/PO3#899]
[Bug Video](https://youtu.be/17Jo86NBmcA)

Video above shows movement of many drawn structures which do not exist physically in the world. Hasn't crashed... yet. Hope this gets fixed. I have reset my client and server and would like to not lose my world. Any help would be much appreciated.

**Comment by Cazadorsniper** [comment]
That is hilarious every time i see it lol, Should probably stop using spectre illuminators.

**Comment by KINGJOJO7086** [comment]
Will do. Is there another light source similar to wraith lamps in the pack I haven't seen yet?

**Comment by Cazadorsniper** [comment]
I have no idea.
