### ISSUE TITLE
high network usage

### ISSUE THREAD

**Issue by Chaftalie** [Cazadorsniper/PO3#9]
Hi!

We are playing PO3 for 366 ingame Days (70 to 85% AFK time) since 2 hours playtime my friend incountered unusual high internet traffic. PO3 uses my whole upload of 6 to 10 mbit/secound.
thats unusual high for minecraft, even for modded. normal usage would be about 0.1 to 0.4 mbit/s I think.

It only occurs if he in the base, that means some block/mod thats used in our base is the cause of this problem.

I will attach our map as an zip file and a wireshark capture file (I only recorded the Port MC used.)
I also zipped the world with 7zip, with that its 50MB smaller.
(they are to big for github, I will upload them to mega.nz)
[mega.nz Link](https://mega.nz/#F!Ss9WSAha!Hn1bzehj9VI65zDBK7SHxw)
SHA256 hashes for
high_network_traffic.7z
0658D92B21EC7230E99DA5800B3AB38805E882AAA8795673CE6972C77A9EF6C5
high_network_traffic.zip
6990F4EA9C3776923A1BE7E50F8ABCACFC9EC53072C3E136560EBD6FFC38A02E
PO3_high_network_traffic.pcapng
DB407C3D843B365837A836D4AA0C0280D22BC059E24F8868E3EAAE7D6E69FD26

If you need something else like Log files ore other information I'll be happy to provide them to you.

EDIT:
PO3 Version 3.0.38

EDIT2:
We broke block by block testing what causes the problem.
After several disconnects of my friend we got to our 64 quantum storages (from the mod quantum storage) after breaking all of them and he reloading all his chunks the network traffic normalized  (0.3mbit/s) We also tried empty quantum storages (our quantumstorage had an average of 300k items) which had the same effect.

Conclusion:
Quantum storage is clearly the problam here. (as far as I can tell at least)

Side note:
PO3 is a really cool modpack, even though its a new modpack its really stable congrats to you (;

**Comment by gigabit101** [comment]
Fixed in next build of QuantumStorage
