### ISSUE TITLE
My buddy is (server) lagging until disconnect whenever the amount of people goes over 3 nearby, any reason for this? The rest of us do not have this prob

### ISSUE THREAD

**Issue by shinyleapfrog** [Cazadorsniper/PO3#904]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.52**
**Pack Mode: Titan**
**Singleplayer, Multiplayer, or LAN?: Multiplayer**

**Description:**
Lagging out when 3 or more people are nearby
**Steps to reproduce:**
Solo, just fine
2 people, just fine
3, cant open anything, player doesn't move.
**Crash log (use pastebin or issue will be closed): just a disconnect, no hard crash.**

**Comment by GodlyIdea** [comment]
It feels like the connection download speed is low.
As I have slow connection and when it goes under certain speed then everything action starts to get delayed and eventually may get disconnected.
Movement is blocked when changing map or using any sort of teleportation with require client and server to get synced to allow any further movement.
Not currently in this pack (As I player SP) but have had that issue in other modpacks aswell when I played in server.
Mod RandomPatches increases timeouts to allow slow computer/connection speed players to connect.
