### ISSUE TITLE
Project Ozone 3 crashes upon entering main menu

### ISSUE THREAD

**Issue by TheBestCube** [Cazadorsniper/PO3#905]
Pack Version: 3.2.52

Pack Mode: Normal

Singleplayer, Multiplayer, or LAN?: Singleplayer

Description: I'm a noob in modpacks and curse/twitch and I tried installing modpack PO3. I've had so much problems but I finally managed to get it to launch on my potato pc through changing jre to a jdk using OpenJ9 and now it runs faster. From now on I have another problem, I guess it's not an exessive RAM usage because I figured out how to use less while in the loading screen but as soon as I enter the main menu the game freezes for some seconds and then crashes and closes without saying anything in the launcher. (btw I'm using original twitch's launcher with the following arguments:
-XX:+UseG1GC -Xmx6G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=25 -XX:G1HeapRegionSize=32M and also I set max perm size to 512mb)
I don't know what to do because it seems not to be a problem of memory but from what I've read from the latest log I saw problems regarding textures may have caused the crash(?)

My PC specs: Windows 10 Pro 64bit
Intel Core i7-2630QM 2GHz 
with Nvidia graphic card GeForce GT 555M, drivers updated to the latest
6GB RAM
Steps to reproduce: Everytime I open Minecraft

Crash log (use pastebin or issue will be closed):

[latest.log](https://github.com/Cazadorsniper/PO3/files/4337225/latest.log)
Sorry I'm not able to get pastebin pro for now

Thanks <3

**Comment by GodlyIdea** [comment]
It is most likely RAM issue. Allocate more and see if that helps.

**Comment by TheBestCube** [comment]
Well I did the best I could, I also went and closed every other program in the background, even the launcher but man, people say you should not try to give it virtual memory as it could get worse... actually I followed the advice of disabling splash.properties for the animations in the forge loading screen and I managed to get it to the Main Menu but as soon as I tried to load the PO3 resources in the resourcepack section it crashed and closed and I could never get to the menu again. now that I'm thinking... is the pack really needed or you can just play without it?

**Comment by GodlyIdea** [comment]
Virtual memory makes things slower as hard drive is used to get that extra memory. (And operating system doesn't know how to properly use it)
In your case you can enable it to see if that fixes the crashes.

For me the resource pack is disabled and there isn't any issues.

To free more memory you can close the twitch client after the game has started to load.
