### ISSUE TITLE
AE2 Autocrafting takes too long to queue

### ISSUE THREAD

**Issue by hlevine9** [Cazadorsniper/PO3#907]
**Pack Version:** 
3.2.52

**Pack Mode:** 
Normal

**Singleplayer, Multiplayer, or LAN?:** 
Singleplayer

**Description:**
Whenever I try to queue up an auto craft, it takes a while for the GUI to switch to the auto crafting GUI. Even when I hold shift, it just sits there for a while. I have plenty of CPU storage, and 27 co-processors per CPU.

**Steps to reproduce:**
No idea what causes it, but it's just an auto craft that is slow to queue up

**Attempts at resolving this issue:**
1. Removing most, or all automation.

Video of issue that I am having - https://youtu.be/F3KgX515pvQ

**Comment by GodlyIdea** [comment]
AE2 is known to have some limits. It isn't mod pack dependant - just more complex recipes cause it occur faster.
You sort of need to start checking in which part of the chain the slowdown occurs.
And then sort of optimize it. Like making process patterns and let some other machines (ex. crafters) do the job.

**Comment by hlevine9** [comment]
I really don't have any complex recipes at all. If anything, they are mostly simple recipes, like converting mystical agriculture essence. Like I showed in the video, it was just a simple craft, but for some reason, it was just lagging behind.

**Comment by GodlyIdea** [comment]
Check how AE can make the ingot if there is some other method as well then AE still calculates it.
Like how you first make it through Fusion Crafting and such.
If you want AE to prioritize the essence crafting then you need to increase that interface priority where the recipe is located.
Also for essence I suggest to make some crafters to convert all the essence to corresponding ingots as there is no other use for the essence.

**Comment by hlevine9** [comment]
I really don't think it has to do with the system itself. I truly think this is a bug. I even tested removing almost all of my automation, leaving a few to test the speed, and it still didn't fix.

**Comment by CHG1731** [comment]
FYI, recursive recipes takes a long time to "calculate"

**Comment by hlevine9** [comment]
Just a quick question, is the world file supposed to be over 1GB? Because that's becoming the biggest reason why I can't upload it. I looked through my world file and there are a lot of Dimension files that almost all have over 100MB of .mca files. World file is now reaching a whopping 2GB.

**Comment by Cazadorsniper** [comment]
Have you tried zipping your world file?

**Comment by hlevine9** [comment]
Yes. It is still over 1GB. https://imgur.com/cH3ivZS

**Comment by GodlyIdea** [comment]
The size sort of depends how much you have explored. (Created a new world and that was about 4MB)
If your autocrafting is in overworld then you can leave other dimensions out of the zip.
Map data is located in region folder. Overworld one is in the root, other maps data is in corresponding DIM folder.

**Comment by hlevine9** [comment]
Ok. Here is the world file, just without the other dimension folders. http://www.mediafire.com/file/yu3r88oubwkgwru/Onward.zip/file

**Comment by GodlyIdea** [comment]
Disconnected the essence YABBA barrel controller from ME and the crafting lag dissappeared.

**Comment by hlevine9** [comment]
That does fix it, but why does it occur? Would it be possible to still use YABBA barrels for storage without the crafting lag? I've watched Hypnotizd's videos, and he has a really large YABBA barrel network, far larger than mine is.

**Comment by hlevine9** [comment]
At the point in this mod pack that I am, I can easily just place a bunch of ME drives with 16384k drives, then transfer everything over. But can we still render this as an issue, so that someone else doesn't make the mistake I did?

**Comment by GodlyIdea** [comment]
You could try converting the essence to corresponding items and store them in storage drawers. Maybe this is less laggy.

**Comment by hlevine9** [comment]
That is another solution. I'll close the issue. Hope YABBA and AE2 will figure something out with why the mods are not cooperating.
