### ISSUE TITLE
it crashes while loading

### ISSUE THREAD

**Issue by YEEET42069** [Cazadorsniper/PO3#909]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.52
**Pack Mode:**normal
**Singleplayer, Multiplayer, or LAN?:**singleplayer

**Description:** when I change allocated RAM to 6gb and try to launch it crashes

**Steps to reproduce:** change allocated RAM to 6GB then start pack

**Crash log (use pastebin or issue will be closed):**13:12:44.609
13:12:44.609
FML
main
Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
13:12:44.672
FML
main
Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
13:12:44.690
FML
main
Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
13:12:44.702
FML
main
Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
13:12:47.089
FML
main
The minecraft jar file:/C:/Users/Marco%20Miranda/Twitch/Minecraft/Install/versions/1.12.2/1.12.2.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
13:12:47.089
FML
main
For your safety, FML will not launch minecraft. You will need to fetch a clean version of the minecraft jar file
13:12:47.090
FML
main
Technical information: The class net.minecraft.client.ClientBrandRetriever should have been associated with the minecraft jar file, and should have returned us a valid, intact minecraft jar location. This did not work. Either you have modified the minecraft jar file (if so run the forge installer again), or you are using a base editing jar that is changing this class (and likely others too). If you REALLY want to run minecraft in this configuration, add the flag -Dfml.ignoreInvalidMinecraftCertificates=true to the 'JVM settings' in your launcher profile.
13:12:47.416
FML
main
Java has been asked to exit (code 1)
13:12:47.651
FML
main
Exit trace:
13:12:47.651
FML
main
    net.minecraftforge.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:164)
13:12:47.651
FML
main
    net.minecraftforge.fml.common.asm.FMLSanityChecker.call(FMLSanityChecker.java:46)
13:12:47.652
FML
main
    net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165)
13:12:47.652
FML
main
    net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
13:12:47.652
FML
main
    net.minecraft.launchwrapper.Launch.main(Launch.java:28)
13:12:47.749
launcher
main
 
13:12:47.749
monitor
Process Monitor
Process crashed with exit code 1 

paste bin link https://pastebin.com/MWNVED4G

**Comment by Cazadorsniper** [comment]
delete 1.12.2.jar in /C:/Users/Marco%20Miranda/Twitch/Minecraft/Install/versions/1.12.2/1.12.2.jar then reinstall it. Also try removing the %20 between Marco and Miranda.

**Comment by YEEET42069** [comment]
I did it but it still doesnt work

**Comment by Cazadorsniper** [comment]
Can try a complete reinstall of the twitchapp.
