### ISSUE TITLE
Twilight Porartal not lighting

### ISSUE THREAD

**Issue by purestone9** [Cazadorsniper/PO3#91]
**Pack Version:** PO3-3.0.38

**Description:** Twilight Portal wont light

**Steps to reproduce:** Throw Glimmer Crystal into twilight portal frame

**Crash log:** No crash, but I do have video showing the issue https://youtu.be/n_YIfYzBDB8

**Comment by Slyklaw** [comment]
Are you using slabs as the floor of the pool?

**Comment by purestone9** [comment]
Thanks, after changing the floor to full blocks it worked
