### ISSUE TITLE
Switching back from Kappa mode

### ISSUE THREAD

**Issue by Dragon0211** [Cazadorsniper/PO3#910]
After i played Kappa mode with some friends, i tried to switch back to normal, so i created a new profile and switched it back to normal.. But now i still have the Kappa mode recipes (Somewhere both of them, or just only the Kappa) I would like to know how to solve this!

**Comment by Cazadorsniper** [comment]
Client and Server must be switched back to normal then the client and server must have the pack restarted.

**Comment by Dragon0211** [comment]
Its already done, everything... But the Recipes wont disapear, and a few of normal recipes got deleted

**Comment by Cazadorsniper** [comment]
Try reinstalling the pack then move the world over.
