### ISSUE TITLE
Docked dank/null got into a state where it grinds the game to a halt whenever I look at it

### ISSUE THREAD

**Issue by Lopdo** [Cazadorsniper/PO3#912]
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Single

**Description:**
Whenever I placed dank/null in a dock, the game got a bit laggy until it emptied itself a bit. Now it got into a state where I can't play the game while I look at it. There is about 16k items in it and I can't empty it because the game doesn't recognise that I pressed ctrl because of the lag. I can't pick it up either, because game doesn't recognise pressed shift either. Lag is horrendous, about 0.2 fps. I tried on multi3 different machines, with same results.

**Steps to reproduce:**
Unknown. I will try to delete it and create new one to see if I can find out what happened
I have a save folder, I can upload it somewhere if it helps. I know the description itself is not very useful

**Comment by Cazadorsniper** [comment]
Sadly, I don't know if /dank/null is being updated anymore.

**Comment by Lopdo** [comment]
That's shame. I checked their github and there is a lot of issues related efficiency. I will try to post it there, but it looks like it isn't maintained as you said
