### ISSUE TITLE
Permanent Health Decrease after visiting Mars 

### ISSUE THREAD

**Issue by jthe111** [Cazadorsniper/PO3#913]
Pack Version 3.2.52
Pack Mode Titan
Server

After updating the server from 3.2.51 to current, and visiting mars, I noticed a permanent health decrease that I cannot correct with either sleeping, dying, logging off, restarting server, etc. I even tried using the cryochamber thinking it could be radiation but I cheated in the Geiger counter and saw i had zero radiation. Now when I visited mars I only had the tier 1 thermal padding until i was able to get some desh and made the tier 2. 

I would like to have the full blue hearts and would like any help trying to resolve this issue. 
![Hearts without container](https://user-images.githubusercontent.com/28276010/76910840-820c3a80-6885-11ea-8e95-61f145f31e35.PNG)
![Heart Canister](https://user-images.githubusercontent.com/28276010/76910847-86385800-6885-11ea-917a-ca5792e1f33f.PNG)
![Hearts with canister](https://user-images.githubusercontent.com/28276010/76910855-889ab200-6885-11ea-8fd0-55ecf8efb276.PNG)

**Comment by ItsEnder** [comment]
Wierd

**Comment by jthe111** [comment]
So... i solved this issue. I had a perk from astral sorcery that decreased my health by 25%. Going to close this issue.
