### ISSUE TITLE
Game crashes in other dimensions

### ISSUE THREAD

**Issue by connor3428** [Cazadorsniper/PO3#914]
The game crashes almost immediately after entering another dimension. It says something about java 32bit not being enough, but I just start it up from the twitch launcher and it doesn’t give me other options...anyone know of a solution?

**Comment by reaperstech** [comment]
I've experienced this as well. I've had to use MCEdit to move my character back to the overworld. and then delete the dimension folder to reset it. Don't know if there are any other solutions as I don't know the cause of the freeze. I've so far had it happen with the Nether and Erebus.

**Comment by Cazadorsniper** [comment]
Update to 64bit java.
