### ISSUE TITLE
Cannot place sprinklers on the covered (full block) irrigation channels

### ISSUE THREAD

**Issue by SweetestPumpkin** [Cazadorsniper/PO3#915]
You can place the sprinklers on the normal small irrigation channels but not on the covered ones that are supposed to be less laggy and are full block .

I dont know if this is a bug but im pretty sure you should be able to place them on the covered ones too.

**Comment by Cazadorsniper** [comment]
I've always seen them placed on the small ones, not the full block ones, but even so there is nothing I can do about it. I haven't seen Agricraft update in a long time.
