### ISSUE TITLE
Disconnecting shortly after joining

### ISSUE THREAD

**Issue by lemonbeard** [Cazadorsniper/PO3#919]
When joining a friends server, I will be able to connect freely and do anything for a few seconds before players around me freeze, and I disconnect giving me only the message "Disconnected"

**Comment by Cazadorsniper** [comment]
Do your friends have any lordcraft blocks setup?

**Comment by lemonbeard** [comment]
Sorry for the late response, the issue had fixed itself but it has returned again. No, we do not have any lordcraft blocks set up but through further research it may be something along the lines of the disconnect timer being too short for me to load everything, and it disconnects me.
