### ISSUE TITLE
Blood moon causing tps lag

### ISSUE THREAD

**Issue by Slyklaw** [Cazadorsniper/PO3#92]
**Pack Version:**
1.0.38

**Description:**
With just a few players, as soon as Blood Moon starts, the tick performance drops roughly in half. E/TE/C counts appear unchanged. The second it becomes "daytime", time performance instantly returns to normal.

**Steps to reproduce:**
Check "/tps" and "/forge tps" before and after Blood Moon

![blood moon](https://user-images.githubusercontent.com/44900062/53774634-e467f680-3f21-11e9-80d5-3f41edf2581f.png)

**Comment by Zapstur** [comment]
The most likely cause?  The sheer increase in the number of monsters in the world.  If you don't want the TPS to be so low, just change the config for that mod so that less monsters spawn.

**Comment by Saereth** [comment]
this is massively worse on skyisland as well. With 10~12 active players in skylands generation when a bloodmoon kicked in the server would actually crash about 30% of the time with a beefy dedicated xeon and 16gb ram dedicated to the server.

**Comment by Slyklaw** [comment]
As you can see from the screenshot, there is not an increase in the number of mobs.

**Comment by nzminecraftDOTcom** [comment]
I'd suggest disabling the blood moon on any server with more than 2 people playing. It's a massive drain on resources.
