### ISSUE TITLE
Caught exception from Minecraft Forge(forge) (Pastebin w/ link)

### ISSUE THREAD

**Issue by RedSnowball** [Cazadorsniper/PO3#920]
**Pack Version:** 3.2.53
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Upon joining playing as usual, had to relog for an issue and came up with the issue "Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge(forge)"

**Steps to reproduce:** Reinstalled pack..... disconnected myself and game crashed resulting in error, constantly not able to join getting same issue each time

**Crash log (use pastebin or issue will be closed):**

https://pastebin.com/FvWPHNNJ

**Comment by Cazadorsniper** [comment]
Did you play 1.13+? If so then that is why its crashing, it seems to be having some trouble with a keybind.

**Comment by Cazadorsniper** [comment]
Are you using an erebus Glider?

**Comment by RedSnowball** [comment]
Yeah, I found if I either shift click it or play with it in my inventory
too fast it will crash. But it did it before I had the glider on me and was
from something in Erebus
And the only way to play again is to redownload the whole pack.

**Comment by Cazadorsniper** [comment]
For now I removed the gliders.

**Comment by RedSnowball** [comment]
Yeah awesome, I found that just having the armour set caused me to have
some very bad fps issues with no reason, taking it off instant relief,
joyfully  it was just the glider, I will try the others and get back to you

Cheers for your hard work on this pack it has really shown

Brad
