### ISSUE TITLE
Thermopneumatic Processing Plant not producing plastic

### ISSUE THREAD

**Issue by CobblePlunderer** [Cazadorsniper/PO3#921]
3.2.53
Kappa
Singleplayer

The Thermopneumatic Processing Plant will not produce plastic even though it has heat, pressure(not sure if necessary), coal, and LPG.  I've tried breaking/replacing, voiding the tank of LPG, and requiring redstone to no avail.  "No Problems" it says with a green checkmark.  It was working in a previous version(one of the first releases), but now does not work in versions  3.2.53.  I haven't yet tried downloading a previous version to see if that fixes it.

Steps to reproduce:  
Start world in one of the first few versions, starve system of pressure and leave it for many, many game days, then update to 3.2.53

**Comment by SongHout** [comment]
Do you put the dye in? It requires the dye and you need to press the plastic sheet color that you want

**Comment by CobblePlunderer** [comment]
> Do you put the dye in? It requires the dye and you need to press the plastic sheet color that you want

It sounds like you're talking about the Plastic Mixer, which is working just fine for me.  My issue is that the Thermopneumatic Processing Plant isn't producing the liquid plastic.

**Comment by Ninehills42** [comment]
I can confirm too that the Thermopneumatic Processing Plant is not working, it doesnt produce plastic from LPG and coal.

**Comment by CobblePlunderer** [comment]
Edit:  Oh ya know what?  Now that I think about it, I hadn't even checked if it worked in 3.2.52.  I think I just *assumed* it didn't.  It definitely doesn't work for me in 3.2.53 (the most recent version).

**Comment by Ninehills42** [comment]
Someone found out that the bug is actually that the TPP requires negative pressure to make plastic from LPG.

**Comment by Cazadorsniper** [comment]
Will update the pack as soon as pneumaticcraft updates.

**Comment by dityareborn** [comment]
it isnt possible to play right now without plastic, isn't it possible to get previous version of pneumatic ?

**Comment by CobblePlunderer** [comment]
> Someone found out that the bug is actually that the TPP requires negative pressure to make plastic from LPG.

> it isnt possible to play right now without plastic, isn't it possible to get previous version of pneumatic ?

> Will update the pack as soon as pneumaticcraft updates.

In that case, I'm gonna do the only Kappa thing there is to do:  Pull a vacuum on that SOB until Pneumaticcraft is updated.

**Comment by Chibu68** [comment]
I had this issue too, and I filed a bug report.
https://github.com/TeamPneumatic/pnc-repressurized/issues/437
desht updated the mod and it's available on the curse/twitch site now.
