### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by freundlich** [Cazadorsniper/PO3#923]
**Pack Version:** kappa
**Pack Mode:** 3.2.53
**Singleplayer, Multiplayer, or LAN?:** LAN

**Description:**
The 3.2.53 server does not launch for me.
Java version is (if it matters):
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (Gentoo icedtea-3.15.0)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

The minecraft-server and forge files are identical to the ones from 3.2.52, which still works fine. Any help would be appreciated.

**Steps to reproduce:**
Just try to start the server.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/FJEpiquc

**Comment by freundlich** [comment]
I'm just noticing that the server download for 5.2.53 has disappeared...

**Comment by Cazadorsniper** [comment]
Use the server link in the description.
