### ISSUE TITLE
Minecraft not starting

### ISSUE THREAD

**Issue by TheGriffer99** [Cazadorsniper/PO3#924]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.53
**Pack Mode:** Normal
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** After pack update i keep getting this error when trying to open minecraft. I already tried to uninstall and reinstall but it gave me the same error.

The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: Pixel format not accelerated

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/4eB7ig4D

**Comment by Cazadorsniper** [comment]
Maybe using the wrong graphics card or need to update video card drivers.

**Comment by TheGriffer99** [comment]
Fixed, i had to roll back nvidia drivers. Now it's working fine.
