### ISSUE TITLE
server cant start

### ISSUE THREAD

**Issue by destoyer910** [Cazadorsniper/PO3#925]
İ cant start server on my computer but when i want start a server ,got randomly errors
bow server wont start what İ need to do ?
[error.txt](https://github.com/Cazadorsniper/PO3/files/4364820/error.txt)

sorry for bad english

**Comment by Cazadorsniper** [comment]
can you place that file in pastebin?

**Comment by destoyer910** [comment]
unfortunately, pastebin banned in my country and i have already used vpn but it didn't open

**Comment by TheSnowyChickens** [comment]
Hello,
we also can't start the server and I only have 2 logs for you:

[debug.log](https://github.com/Cazadorsniper/PO3/files/4372077/debug.log)
[latest.log](https://github.com/Cazadorsniper/PO3/files/4372078/latest.log)

**Comment by Cazadorsniper** [comment]
What version of PO3?

**Comment by destoyer910** [comment]
you updated po3 and im useing right now (seriously right now) and V3.2.54

**Comment by destoyer910** [comment]
[crash-2020-03-24_02.52.43-server.txt](https://github.com/Cazadorsniper/PO3/files/4372430/crash-2020-03-24_02.52.43-server.txt)
@Cazadorsniper i think aroma1997 dimesion mod is broke af

**Comment by destoyer910** [comment]
@TheSnowyChickens can you send crash raport in server folder it's like above post

**Comment by TheSnowyChickens** [comment]
Yes, but not now, because I don't have access to the Server. (it is the server from a friend)

Calculate with the crash log in round about 15h.

**Comment by Cazadorsniper** [comment]
Try reinstalling the pack then move your world over.

**Comment by Cazadorsniper** [comment]
Also try a clean install of the server files.

**Comment by destoyer910** [comment]
I tried almost everything one of them delete aroma1997 dimension mod and its almost worked but satill got crash

**Comment by TheSnowyChickens** [comment]
We notized now, the server doesn't create a crash report and also with a clean install, still the same error :/

**Comment by destoyer910** [comment]
ohh okay :|

**Comment by Cazadorsniper** [comment]
Are you both on the same server?

**Comment by destoyer910** [comment]
no

**Comment by destoyer910** [comment]
we don't know each other

**Comment by TheSnowyChickens** [comment]
We found our problem, it was so easy to fix, but we were soo blind.

**Comment by destoyer910** [comment]
What was your problem?

**Comment by Cazadorsniper** [comment]
Try resetting the world by deleting the dimension folder in your world (which is -6).

**Comment by destoyer910** [comment]
now server can not keep up

**Comment by TheSnowyChickens** [comment]
@destoyer910 Just putting the new mods folder in the old one(without deleting anything), is not a clever move ^^

**Comment by destoyer910** [comment]
nope still not working
