### ISSUE TITLE
ExtraPlanets Magnesium Ingot does not exist.

### ISSUE THREAD

**Issue by Explosivee** [Cazadorsniper/PO3#926]
**Pack Version:** 3.2.53
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Both SP and MP.

1-) Get a Magnesium Ore from ExtraPlanets
2-) Smelt it into a ingot in a furnace
3-) Get the Magnesium Ingot (ExtraPlanets) into your inventory

Result; It'll turn itself into Magnesium Ingot (NuclearCraft) and it can not be used in GalactiCraft/ ExtraPlanets crafting recipes.

**Comment by Chibu68** [comment]
I don't know if these 2 ingots have the same ore dictionary, but if they do, you can try using the Forge Lexicon from Thermal Foundation to turn the ingots into the GalactiCraft ones.

**Comment by Explosivee** [comment]
> I don't know if these 2 ingots have the same ore dictionary, but if they do, you can try using the Forge Lexicon from Thermal Foundation to turn the ingots into the GalactiCraft ones.

The problem is even if i take those ingots from creative mode they became into NuclearCraft ones instantly.

**Comment by Cazadorsniper** [comment]
What are you trying to make?

**Comment by Explosivee** [comment]
> What are you trying to make?

Compressed Magnesium but there are few more uses for it.

**Comment by Cazadorsniper** [comment]
a block of magnesium?

**Comment by Explosivee** [comment]
> a block of magnesium?

- Block of Magnesium
- Magnesium Sword
- Magnesium Shovel
- Magnesium Pickaxe
- Magnesium Hoe
- Magnesium Axe
- Magnesium Helmet
- Magnesium Chestplate
- Magnesium Leggings
- Magnesium Boots
- Magnesium Tiled Floor
- Advanced Oxygen Decompressor
- Advanced Oxygen Compressor
- Compressed Magnesium
- Compressed Magnesim

**Comment by Cazadorsniper** [comment]
Fixed it.

**Comment by Explosivee** [comment]
> Fixed it.

Can you tell how can we fix it too as a temp fix till we have the new update?

**Comment by Cazadorsniper** [comment]
wait until the new update.
