### ISSUE TITLE
Java Problem

### ISSUE THREAD

**Issue by ToxicFool** [Cazadorsniper/PO3#927]
I can't load up the mod-pack at all. And this is the message that pops up.
<img width="892" alt="Screen Shot 2020-03-22 at 1 11 02 PM" src="https://user-images.githubusercontent.com/62515765/77255853-e1c96380-6c40-11ea-8aeb-c8215f03dc0a.png">

**Comment by Cazadorsniper** [comment]
Can you give me the crash-report (using pastebin.com) or give me the latest.log?

**Comment by ToxicFool** [comment]
I solved the problem by switching an older version of Java
