### ISSUE TITLE
Translocators breaks from smeltery's output when starting server or coming from another dimension.

### ISSUE THREAD

**Issue by OrbitStudios** [Cazadorsniper/PO3#928]
**Pack Version:**
- 3.2.53

**Pack Mode:**
Normal

**Singleplayer, Multiplayer, or LAN?:**
Single player server - localhost

**Description:**
Sometimes, when coming from another dimension or after starting the server, translocators attached to the outputs of smeltery drains will break and will be dropped, I had to place an item collector to pick them up

**Steps to reproduce:**
-Start server/ tp back from the Nether or The End

**Crash log (use pastebin or issue will be closed):**
N/A

**Comment by Cazadorsniper** [comment]
Are they chunk loaded? Someone else had this issue too and that was the issue for them.

**Comment by OrbitStudios** [comment]
Yeah, I'm using FTButils chunk loader to prevent explosion damage and ChickenChunks to actually chunk load the chunks

**Comment by OrbitStudios** [comment]
Ok so after some more testing, I was able to replicate the issue every time the server and the modpack are loaded the first time and it seems to be affecting only if the smeltery is chunk loaded. Hope that helps

**Comment by Cazadorsniper** [comment]
Can you try other transfer methods in order to see if its only translocators.

**Comment by OrbitStudios** [comment]
So it seems that the issue is with the smeltery drain itself, I've tried with conduits, liquid retrievals, fluid extractors (Embers) and translocators and they always break/disconnect from the drain when the server and the pack are started.

**Comment by koczka** [comment]
I'm having the exact issue, my translocators missing from my smeltery drains after each restart, I researched for a while, and I found it might be related to chunk unloading, found this issue, that might help the developement

https://github.com/TheCBProject/ForgeMultipart/issues/29

**Comment by VoidedOut** [comment]
I have this issue as well, specifically when changing dimensions. Everything is chunkloaded and claimed

**Comment by Cazadorsniper** [comment]
Chunk loaded using chicken chunks?

**Comment by VoidedOut** [comment]
Yes

**Comment by chef109** [comment]
I've had a similar issue twice only it's crashed my server on startup.
[crash-2020-05-02_15.40.01-server.txt](https://github.com/Cazadorsniper/PO3/files/4568050/crash-2020-05-02_15.40.01-server.txt)

**Comment by Ralsch** [comment]
I have a complete server folder (PO3 3.3.59, Kappa) where each time the server is started all translocators are popped from the smeltery drains (tried 3 times). Some were active and some inactive, but all of them popped. I could pick them up before they despawned. Maybe this server backup will help in finding the issue? If so, where can I upload the zip (3.7 gb), or send a link for you to download?

**Comment by Chawpmaster** [comment]
Im having the same issue. Is there a fix yet?
