### ISSUE TITLE
.54 Lunar Singularity Recipe broken

### ISSUE THREAD

**Issue by itsjusttriz** [Cazadorsniper/PO3#931]
Just updated our server to 3.2.54 and now the Lunar Singularity has been changed to using blocks rather than ingots, BUT now creates a dummy singularity rather then the Lunar singularity.

https://i.imgur.com/pUVqXCL.png
https://i.imgur.com/gVFvJqm.png

**Comment by Cazadorsniper** [comment]
Remove line 63 in all_extended.zs

**Comment by reaperstech** [comment]
Fixed it for me in SP Normal. I would like to mention that people that use notepad/etc make sure word wrap is off or the line count will be incorrect. Had to reload pack for it to take effect ofc. Thanks @Cazadorsniper. And sorry for the duplicate. :P
