### ISSUE TITLE
Unable to make plastic

### ISSUE THREAD

**Issue by FailToSurvive** [Cazadorsniper/PO3#932]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.53
**Pack Mode:** kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer 

**Description:**
With the latest update I cannot make plastic from LPG in the Thermopneumatic Processing Plant machine. It worked in version 3.2.51.

**Steps to reproduce:**
Make a Thermopneumatic Processing Plant, add LPG, add Coal, add heat, and nothing happens.

**Crash log (use pastebin or issue will be closed):**
(not a crash)

**Comment by FailToSurvive** [comment]
Looks like they have a hotfix for it available: https://github.com/TeamPneumatic/pnc-repressurized/blob/master/Changelog.md

**Comment by Cazadorsniper** [comment]
3.2.54
