### ISSUE TITLE
Smelting chiseled stone gives Porcelain Bricks

### ISSUE THREAD

**Issue by Rams59** [Cazadorsniper/PO3#933]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.2.5.1
**Pack Mode:Kappa**
**Singleplayer, Multiplayer, or LAN?:Server

**Description:**
When Smelting chiseled Cobblestone(i did it with dent) a Goldfurnace (i didnt test other furnaces) will give Porcelain bricks as output
**Steps to reproduce:**
See above
**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Either update the pack or update furnace overhaul.
