### ISSUE TITLE
twilight forest bosses error

### ISSUE THREAD

**Issue by PaternoX** [Cazadorsniper/PO3#935]
**Pack Version:3.2.54
**Pack Mode:kappa
**Singleplayer, Multiplayer, or LAN?:SP

**Description: Twilight forest boss spawners in incorrect place - namely, the naga spawner is at the top of the lich tower.

![2020-03-23_17 37 13](https://user-images.githubusercontent.com/28237849/77346697-95f4e800-6d2e-11ea-84e4-66f53bb6113c.png)

**Steps to reproduce:travel to top of lich tower in twilight forest

**Crash log (use pastebin or issue will be closed):n/a

**Comment by Cazadorsniper** [comment]
Is it every lich tower?

**Comment by PaternoX** [comment]
checked 2 so far, both have same issue

**Comment by PaternoX** [comment]
yup, looks like its everyone, checked 4 and all have the same issue

**Comment by Cazadorsniper** [comment]
I'll look into it.

**Comment by PaternoX** [comment]
well reloading fixed it. and i derped! my mob farm was overflowing n affecting fps, so went into peaceful to resolve issue, and never went back into hard mode afterwards!!

**Comment by Cazadorsniper** [comment]
lol
