### ISSUE TITLE
Industrial foregoing recipes in titan?

### ISSUE THREAD

**Issue by Dinip** [Cazadorsniper/PO3#937]
**Pack Version:** 2.3.54
**Pack Mode:** Titan
**Singleplayer, Multiplayer, or LAN?:** Server

**Description:**
Should the machines from industrial foregoing have 2 recipes in titan mode? I don't see the point of having a harder recipe if the easier recipe was not removed. On kappa seems to have only the "harder" recipe.

**Steps to reproduce:**
Set pack mode to titan and see the recipes from industrial foregoing:
![image](https://user-images.githubusercontent.com/8941012/77371765-fb130280-6d5b-11ea-8adc-72b29d098647.png)
![image](https://user-images.githubusercontent.com/8941012/77371819-154ce080-6d5c-11ea-9a91-dcdd9ef6c66b.png)
![image](https://user-images.githubusercontent.com/8941012/77371849-272e8380-6d5c-11ea-98c3-490a58e152ae.png)

**Comment by Strimblaster** [comment]
I dont see a point in having this 2 recipes either
![image](https://user-images.githubusercontent.com/35038384/77445681-4ae9dc00-6de5-11ea-90c6-9e5f2fb68f9e.png)
