### ISSUE TITLE
Can't get plastic from pneumatic craft 

### ISSUE THREAD

**Issue by Tomasz-Tabis** [Cazadorsniper/PO3#938]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*3,2,53*
**Pack Mode:*Normal*
**Singleplayer, Multiplayer, or LAN?:*Multiplayer and single*

**Description:**
Can't create a plastic in Thermopneumatic processing plant.
The temperature is more than 100 celcius but steel can't produce it :(
See the image

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
![image](https://user-images.githubusercontent.com/25965787/77380661-f6f6dd00-6d7b-11ea-9a62-d3bbc59e24db.png)

**Comment by Cazadorsniper** [comment]
update
