### ISSUE TITLE
Can't craft items required to complete quest (3.2.54 | Titan | Furnace Overhaul)

### ISSUE THREAD

**Issue by MarvTigre** [Cazadorsniper/PO3#939]
**Version: 3.2.54**
**Mode: Titan | Singleplayer**

**Issue:**
Missing recipes for **Electric Fuel Upgrade** and **Liquid Fuel Upgrade** from **Furnace Overhaul** mod.

Unable to complete **Furnace Upgrades** quest in **Alpha quest line**.

**Comment by Cazadorsniper** [comment]
Either update the mod or wait for an update.
