### ISSUE TITLE
Fuel Upgrades Furnace Overhaul recipes missing

### ISSUE THREAD

**Issue by Strimblaster** [Cazadorsniper/PO3#941]
Pack Version: 3.2.54
Pack Mode: Titan
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description: Liquid fuel and Electric fuel upgrades don't have a recipe

Probably it's a problem from the mod because it was updated for this version but i'll leave this here anyway.

**Comment by Cazadorsniper** [comment]
Update the mod or wait for a pack update.
