### ISSUE TITLE
Server crashed and wont start anymore

### ISSUE THREAD

**Issue by si0x** [Cazadorsniper/PO3#942]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.54
**Pack Mode:**Kappa
**Singleplayer, Multiplayer, or LAN?:**Multiplayer

**Description:**
Server suddenly crashed when my Friend was afk on it for 1 hr.
Cant start the server anymore
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/WRyQNAcn

**Comment by Cazadorsniper** [comment]
Try removing the arc furnace or whatever multiblock that is from IE.
