### ISSUE TITLE
latex processing recipe broken

### ISSUE THREAD

**Issue by lustigsw** [Cazadorsniper/PO3#945]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.54
**Pack Mode: survival
**Multiplayer on a server

**Description: the recipe does not allow for the latex processor to be built..

**Steps to reproduce: put recipes in various crafting tables and none seem to work

**Comment by Cazadorsniper** [comment]
pack mode?

**Comment by lustigsw** [comment]
If pack mode isnt survival.. then where would I find that?

**Comment by Cazadorsniper** [comment]
normal, titan, or kappa?

**Comment by lustigsw** [comment]
Normal

**Comment by Cazadorsniper** [comment]
I crafted it fine.

**Comment by lustigsw** [comment]
Strange.. myself and my players couldnt..

**Comment by Cazadorsniper** [comment]
Maybe next update will fix it.
