### ISSUE TITLE
[Lordcraft] Quest bug

### ISSUE THREAD

**Issue by Honobe** [Cazadorsniper/PO3#946]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:3.2.53
**Pack Mode: Normal
**Singleplayer, Multiplayer, or LAN?: Multiplayer

**Description: Whenever I accept a quest from on of the gods (I only have the water one unlocked), they usually say to kill a certain number of mobs. However, I have found that I have only had to kill one mob for the quest to say complete instead of like 13.

**Steps to reproduce: IDK. 

**Crash log (use pastebin or issue will be closed): Game didn't crash

**Comment by Cazadorsniper** [comment]
I don't see an issue with that.
