### ISSUE TITLE
Pack crashes

### ISSUE THREAD

**Issue by sreekrishn** [Cazadorsniper/PO3#947]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.54
**Pack Mode:**Kappa
**Singleplayer, Multiplayer, or LAN?:**singleplayer

**Description:**
Pack crashes on launch
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/ezhV7v3k

**Comment by Cazadorsniper** [comment]
What were you doing before it crashed?

**Comment by Cazadorsniper** [comment]
Only mod that crash mentions is HammerCore.

**Comment by sreekrishn** [comment]
Nothin juz opening the mod pack gave this crash but now it is working

**Comment by Cazadorsniper** [comment]
lol
