### ISSUE TITLE
pack won't update

### ISSUE THREAD

**Issue by MatteoAzze** [Cazadorsniper/PO3#949]
the pack wont update it says "cannot update.files are already in use.please exit any application that may be using the files in this profile folder", but only twitch is open. i am play on mac.thank you

**Comment by Cazadorsniper** [comment]
Something is using the files, take a look in task manager.

**Comment by MatteoAzze** [comment]
i checked and nothing is using the file

**Comment by Cazadorsniper** [comment]
Try restarting your entire pc.

**Comment by MatteoAzze** [comment]
did that a lot of times.this issue has been happening for a while

**Comment by MatteoAzze** [comment]
i am in the latest beta version

**Comment by Cazadorsniper** [comment]
Maybe an antivirus software is blocking it or windows firewall.

**Comment by MatteoAzze** [comment]
i checked and nothing is blocking it.i read something on reddit, and apparently it happened on other pack.to fix it it mentioned some readonly option in the files but i cant find it.

**Comment by Cazadorsniper** [comment]
oh that, twitchapp is having issues. Go to the instance folder right-click on the PO3 folder then go to properties. You should see it at the bottom.

**Comment by MatteoAzze** [comment]
there is no properties thing.thank you anyway

**Comment by Cazadorsniper** [comment]
You don't see the Properties button under rename after right-clicking the PO3 folder?

**Comment by MatteoAzze** [comment]
i found it but it still wont update

**Comment by ZeBrasa** [comment]
Go to project ozone folder location, right click on it and press properties. Try to check/uncheck "Read only" option

**Comment by MatteoAzze** [comment]
it didn't work so i just deleted and reinstalled the pack.Thank you anyway to both of you
