### ISSUE TITLE
Nuclearcraft fuels base power values

### ISSUE THREAD

**Issue by lyuben-todorov** [Cazadorsniper/PO3#950]
Nuclearcraft config values have been touched, which is really good and makes for different reactor designs than the standard, together with base power values for all the uranium fuels. I don't know if this is intended but a 3x3 basic reactor is pushing 6m RF/t with minimal investment( this is after the 30x multipler to powergen and the x1800 of the base value for LEU-235). This is kind of fine I guess? Because it goes in line with the pack's ramped up power gen but the rest of the fuel values have been left out. However the only fuels changed are the uranium variants. This ruins fuel progression and leaves no incentive to go for higher-grade fuel. 

So I think base fuel values should either be reverted to the default ones (making the 6m RF/t base reactor output only 33k RF/t) or all should be ramped up. Reactors come at a point where your base is already pretty developed (good ME system, etc.), but 6m with the first fuel you get is just dirty.

**Comment by Cazadorsniper** [comment]
I messed with it a bit.
