### ISSUE TITLE
(JEI Issue) Not able to auto-complete crafting recipe

### ISSUE THREAD

**Issue by Tubby737** [Cazadorsniper/PO3#952]
Pack Version:3.2.54
Pack Mode: Kappa
Single player, Multiplayer, or LAN?: Multiplayer

Description: So i just started playing POZ3 Kappa mode on multiplayer. When i go to craft the furnace recipe or piston recipe, using the little + symbol from JEI to auto-complete and put all the crafting materials into the crafting table it doesn't let me craft it. I found it only does for it for certain recipes. Not sure how to fix or this is a bug. What i've been doing to get a work around is cheating the items in and just trashing the crafting materials, but i don't want to keep doing that every time i need a furnace or piston. Any help would be greatly appreciated.

Steps to reproduce: Not sure. I've tried restarting the pack and still doesn't work. Tried rebooting the server and does nothing. I tried doing the minetweaker reload but it was removed in version 1.12.

Crash log (use pastebin or issue will be closed):None since it doesn't cause a crash.

**Comment by Cazadorsniper** [comment]
Is the client and server on kappa mode?

**Comment by Tubby737** [comment]
> 
> 
> Is the client and server on kappa mode?
will take a look give me a sec

**Comment by Tubby737** [comment]
Well that seems to have worked. I thought i had changed it to kappa mode on both but i guess not. Thx for the help and keep up the good work :).
