### ISSUE TITLE
Netty ServerIO issue?

### ISSUE THREAD

**Issue by Noliwankenobi** [Cazadorsniper/PO3#953]
At random points while running my Project Ozone 3 server, the console is spammed with [this message ](https://pastebin.com/raw/59MjLEAd)over and over, accompanied with severe server lag. Does anyone know what the problem is here, and how to fix it?

**Comment by Cazadorsniper** [comment]
Someone is having issues connecting to the server.

**Comment by Noliwankenobi** [comment]
> Someone is having issues connecting to the server.

The error also occurs sometimes when I join the server, everyone gets server lag or is kicked. Is this due to not having enough bandwidth on my end? Sometimes it happens when I'm not on the server as well.

**Comment by Cazadorsniper** [comment]
Maybe.
