### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by DemiurgeOfficial** [Cazadorsniper/PO3#954]
Server won't start period. No log, nothing. Wont even run.
I am using the latest server files.

**Comment by Cazadorsniper** [comment]
What are you doing to start the server?

**Comment by Cazadorsniper** [comment]
Did you accept the eula?

**Comment by DemiurgeOfficial** [comment]
Using your start batch. The server hasnt even started to get to the EULA agreement file.  I tried running the normal server first before, accepted EULA, and that didnt work so I now have a fresh install.

**Comment by Cazadorsniper** [comment]
I was able to start the server fine. edit the bat file to start minecraft server, after starting the server accept the eula, start again, stop server and edit bat to use forge, delete world file and set level-type, then start server again.
