### ISSUE TITLE
Default recipes

### ISSUE THREAD

**Issue by KrazyMiner001** [Cazadorsniper/PO3#956]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version: 3.2.54**
**Pack Mode: Normal**
**Singleplayer, Multiplayer, or LAN?: Singleplayer**

**Description: Some Recipes have the craft tweaker and normal recipes**

**Steps to reproduce: Look at recipe of crystal matrix and probarbly others**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
update
