### ISSUE TITLE
Missing recipes from mekanism crusher ( and probably a few other machines)

### ISSUE THREAD

**Issue by lyuben-todorov** [Cazadorsniper/PO3#957]
These recipes are available in the SAG mill and the Pulverizer, but not in Mek crushers. So far I've encountered:

- Bone meal
- Enderium, Steel, Electrum, Invar, Constantan, Signalum, Lumium, Fluxed Electrum **blends** 
- all of the EnderIO 'grains' ( Prescience, Vibrancy, Piezality, End)
- Ender dust (from ender pearl)
- Prismarine crystals

A question to the maintainer: Would you like me to keep making these meticulous issues about small things? Is it pointless?

**Comment by Cazadorsniper** [comment]
I'm going to keep these recipes as is.
