### ISSUE TITLE
Extra loot bags

### ISSUE THREAD

**Issue by FailToSurvive** [Cazadorsniper/PO3#958]
**Pack Version:** 3.2.54
**Pack Mode:** kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:**
You can duplicate loot bags by using item conduits extracting from the loot bag storage. It seems to pull 4 bags at the cost of 1 bag. The server log entry is below.

**Steps to reproduce:**
1. Put 3 loot bags into a Loot Bag Storage
2. Connect item conduits with the Bag Storage and a chest/crate.
3. Set the item conduits to extract
4. See more than 3 bags in the chest.

**Log Entry:**
(I figured since this was just 1 line from the log it would be fine without pastebin)
```
[enderio]: NetworkedInventory.itemExtracted: Inserted 4 §6Legendary Lootbag§r but only 
removed 1 §6Legendary Lootbag§r from net.minecraftforge.items.wrapper.SidedInvWrapper@f03bdd1d
at BlockPos{x=804, y=81, z=-419}. This means that 3 items were just duped 
by net.minecraftforge.items.wrapper.SidedInvWrapper@f03bdd1d!
```

**Comment by Cazadorsniper** [comment]
I'm aware of this and I recommend you stop that from happening or the server will get bogged down.

**Comment by FailToSurvive** [comment]
Okay thanks.
