### ISSUE TITLE
Instakilled by every mob that can hit

### ISSUE THREAD

**Issue by RedSnowball** [Cazadorsniper/PO3#959]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** Me with 100 health, absorption, and regeneration being one shot by any mob that can hit back... even one of those chickens.... This goes for everyone on our server
(having armour on doesn't seem to make a difference...)

**Steps to reproduce:** Get near hostile mob, get hit, die no matter what you are wearing.
(the only way I have been able to counter this is is hold totem of undying)

**Crash log (use pastebin or issue will be closed):** No crash log because it is such an odd issue

**Comment by Cazadorsniper** [comment]
Killed a lot of bosses.

**Comment by freundlich** [comment]
Considering the buggy interaction with Woot, why not turn ESM damage scaling off completely?

**Comment by RedSnowball** [comment]
Cheers will converse with the rest of the crew and see, I understand now
why and how, our bad, have a good one

**Comment by Cazadorsniper** [comment]
@freundlich I do not consider the interaction to be buggy.
