### ISSUE TITLE
Bandwidth issue - After Opening

### ISSUE THREAD

**Issue by Eavon** [Cazadorsniper/PO3#96]
Hello,

I am not sure whats causing this issue but whenever I launch Project Ozone 3 (Toasty networks version) it uses nearly 100% of my bandwidth at-least 5 minutes before I can connect to any server. (This is after the game has loaded)

![image](https://user-images.githubusercontent.com/13237393/53849467-f67b8080-3f85-11e9-86f3-b9bb2ddfba18.png)

What would cause this kind of issue? 

Thank you,
Eavon

**Comment by Zapstur** [comment]
Ok, for one, I don't see how one application using a mere 300 KB/s of data could bog down your network capabilities THAT much.  That being the case, your first order of business should be checking your hardware capabilities and your internet speed, to see if that is the issue.  Then, after that, if your computer has been confirmed to have a CPU with a decent speed and your download speeds are satisfactory (I.E. over 2 MB/s), but you still encounter the problem, ask for assistance from the owners of that server for help.  Why is that?  Because that issue is not present when the modpack is started through the Twitch Desktop App.

**Comment by Eavon** [comment]
I do understand that you guys don't support the Toasty Networks Launcher, but I was told that I need to create an issue via the mod pack issue tracker and see if I can figure this out. Honestly, everything bogs my network down that much due to the shear size of files you need to download... SVC Network Host drains my network if its on, I have to go and stop it whenever it starts up because I cannot do anything.

I live on the top of a mountain and I'm seriously a finger away from moving out and finding somewhere else, anyways... 

Network Validation:
![image](https://user-images.githubusercontent.com/13237393/53878028-cf9a6a00-3fd8-11e9-9017-8c8fb84233dd.png)

PC Validation:
https://valid.x86.fr/0pbela

I will try the pack with the Twitch Launcher to see how it works for me. I will let you know if i can figure anything out.

**Comment by Zapstur** [comment]
Well, that just revealed one major issue.  You really shouldn't have to shut down svchost.exe.  The background network usage it has is used to handle software updates for users, like Windows Updates.  However, you CAN safely turn off its ability to chew up what little bandwidth you have, and here's how:

1.) Use the key combination "WIN+R", and type in "services.msc"

2.) Find the "Background Intelligent Transfer Service", and Stop that service.

3.) Then, open the Properties for that service, and change its Startup Type to "Disabled"

If that solves the issue of it taking up too much bandwidth, great.  If it doesn't, you should check to see if the Drivers on your system are up to date, and, if they aren't, update them.

**Comment by Eavon** [comment]
The svchost has already been stopped and it is not using any bandwidth on my laptop whenever this issue occurs, the only reason I stop the svchost is due to the fact that it uses bandwidth inside of my active hours (because Windows 10 Update Management is total trash). So I highly doubt that is the cause of my issue.

I don't think you're understanding the issue at hand:
**This issue is occurring after minecraft fully loads and when I'm sitting on the start screen it starts using this bandwidth.** This issue stops ~5mins after and then I can play. It's extremely annoying for me. 

As I said earlier, I will try the Twitch Launcher to see if it occurs with that. I will have to wait until I get home later on to do this.
