### ISSUE TITLE
Name ingot slow down me craft

### ISSUE THREAD

**Issue by anthonyL05** [Cazadorsniper/PO3#960]
**Pack Version:**
3.2.51

**Pack Mode:**
Ozone 3 kappa mod

**Singleplayer, Multiplayer, or LAN?:**
Singleplayer

**Description:**

Since 2 day i begin to get realy long time to load craft in me system.
I decide to try to find on the github and i see close post  who speak about that with no anserws.
I passed 2 hour and find why the system is slow to craft. When you auto-craft huge item you need sevral craft. For that i use like i use many time the name ingot (make with inscriber) to make it. When i cut the me line who use the name ingot as result of the craft its sudently go fast again.
For the moment i auto-craft something like different stair to make it and it work perfectly.

**Steps to reproduce:**

put a craft who result a name ingot. Try a big craft and see how many time it make to load the craft.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
You mean using "Copper Ingot" rather than its oredict name "ingotCopper".

**Comment by anthonyL05** [comment]
I use an iron igot in the first recipie and name it with the inscriber name (in an inscriber) to be the result of the first one. I require for the second craft who realy craft the item and drop the named-ingot.

Apparently the result of the craft cant be named with inscriber plate.

**Comment by GodlyIdea** [comment]
Recursive crafting is sort of known to be slow. It's AE2 issue and sort of not related to current modpack.

Could you specify what are you trying to craft that require more than 9 different items?
For those items you need to use packager and unpackager. (I hope those are in this pack but haven't checked)
