### ISSUE TITLE
Agricraft/InfinityLib Related Crash

### ISSUE THREAD

**Issue by Danke96** [Cazadorsniper/PO3#963]
**Version** 3.2.51
**Mode**: Titan
Singleplayer

**Description:** Just normal playing, made a search in JEI (presumably related in someway to 
Agricraft or InfinityLib) then client crashed, can´t open any kind of inventory/GUI now or will crash 

**Steps to reproduce:** Open inventory, search in NEI, client crashes

https://pastebin.com/7s6AQp2b

**Comment by Cazadorsniper** [comment]
Step 1: Update the pack.
Step 2: Don't add any extra mods to the pack.
Step 3: Don't remove any mods from the pack (except for waitingtime if your load time is way longer than 10mins)
