### ISSUE TITLE
Philosophers Stone Not Crafting

### ISSUE THREAD

**Issue by fclemo** [Cazadorsniper/PO3#968]
# Use the search function before reporting to see if the issue has been reported before.
**Project Ozone 3 most up to date**
**Titan:**
**Singleplayer:**

**Mr. Sniper,  when I go to craft the philosophers stone, it does not craft. I can shift click in the items, and it appears in the window, however when I go to click on it nothing happens.  If i shift click it into my inventory it will appear in my inventory, and the sub-items will disappear.  However very soon after the stone will disappear and all the items will repair in the ultimate crafting table. Im sorry if this has been brought up before or I am doing something stupid.**

**Can replicate it by spamming the crafting recipe. Closing and relaunching the game does not fix it. :**

**Crash log (use pastebin or issue will be closed):**
![image](https://user-images.githubusercontent.com/61640804/77898242-d10a9480-72b5-11ea-9df2-0e07b0ac3f59.png)
![image](https://user-images.githubusercontent.com/61640804/77898292-e089dd80-72b5-11ea-9baf-1f599668a7d8.png)

**Comment by Cazadorsniper** [comment]
Try attuning the Shifting stars to something.

**Comment by fclemo** [comment]
Yup!  Wouldnt shift click into the crafting table with the ? key but hand placed it crafted just fine.  I attuned them to vicio like the animation wand! Thank you for the help!
