### ISSUE TITLE
Grave in end not appearing

### ISSUE THREAD

**Issue by Cubicalman** [Cazadorsniper/PO3#97]
**Pack Version:**
3.0.38
**Description:**
Fell into the void in the end and grave did not appear after going back to the end, nor a death waypoint
**Steps to reproduce:**
Fall into the void in the end. Grave does not appear
**Crash log:**
N/A

**Comment by Zapstur** [comment]
I haven't been able to replicate that.  Graves are created just fine for me.  Try crafting your Grave Key with an Ender Pearl (useful for teleporting to it, even if you are in a different dimension) to see if it really didn't create a grave, or if you just got lost.

**Comment by Zapstur** [comment]
Another thing to note, is that the mod in question (Corail Tombstone) will try to place your grave on the ground, as clode to the X and Z coordinates of your death as possible.  Sometimes, that means it can end up placing your grave in a weird spot, such as places you never actually went to (like a ledge beneath the main End Island platform).

**Comment by Cubicalman** [comment]
Something I forgot to mention and will add to main post, is no death marker appeared in the end. What dimension is the end, for reference?

**Comment by Zapstur** [comment]
Well, falling into the Void in any dimension will kill players in creative, even in Vanilla.  As to the "/back" command, that is functioning properly; it takes you directly to the EXACT coordinates of your death (in this case, that is beyond the threshold of taking damage from the void), not to your grave.  And for the death marker not appearing, check your JourneyMap options, it will be an option under "Waypoints", called "Create Death Waypoints".  By default, that option is turned on, but if you turn it off and then create a new world with the same name, those settings and waypoint coordinates will be accessible in the new world.

Also, in this modpack, the End is Dimension -2 (visible on each Grave's Key)

**Comment by Cazadorsniper** [comment]
End dimension ID is 1

**Comment by Cubicalman** [comment]
The key I got for the grave did say dim -2 though. Know what that is?

**Comment by Cazadorsniper** [comment]
The Void:-2 basically the voidcraft dimension, falling in the end's void sends you to The Void.

**Comment by Cubicalman** [comment]
Well that's not good. Any ideas on how to get my stuff back?

**Comment by Cazadorsniper** [comment]
go to the void

**Comment by Cubicalman** [comment]
Yes but I can't get there without dying

**Comment by Cazadorsniper** [comment]
try to make potions of plenum

**Comment by Cubicalman** [comment]
Will do and report back

**Comment by Cubicalman** [comment]
Worked. Have my stuff back. Much thanks.
