### ISSUE TITLE
Error by Starting The Mod (With Link to Pastebin !!!)

### ISSUE THREAD

**Issue by ToxicsHD** [Cazadorsniper/PO3#971]
I started the game on Twitch and this happend
i allready reintalled the jar(1.12.2) and my ram for minecraft is on 5  

![efj3jf32i2ß](https://user-images.githubusercontent.com/62951980/78047485-b1887000-7378-11ea-81e2-65ee813fbb2f.PNG)

**Crash log: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)** 

**Version:1.12.2:**

**Mod:Project Ozone 3 A New Way Forward**

**Singleplayer**

**Runed The Game on Twitch:**

any help would be nice. Thx

**Comment by ToxicsHD** [comment]
This Crash report ??? ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  AstralCore (astralsorcery-1.12.2-1.10.22.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  HCASM (HammerCore-1.12.2-2.0.6.13.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  Quark Plugin (Quark-r1.6-178.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b166.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  WTPlugin (WaitingTime-1.0.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

**Comment by Cazadorsniper** [comment]
I need the whole thing with it copy/pasted on pasdtebin.com.

**Comment by ToxicsHD** [comment]
This is The Link https://pastebin.com/mcedGbin

**Comment by Cazadorsniper** [comment]
-Xmx3228m, need more dedicated ram.

**Comment by ToxicsHD** [comment]
how much RAM do you recommend

**Comment by Tomasz-Tabis** [comment]
![image](https://user-images.githubusercontent.com/25965787/78200898-5c3f8200-7490-11ea-855e-987cf88f48a0.png)

**Comment by ToxicsHD** [comment]
ok Thx for the help it worked
