### ISSUE TITLE
AE2 Formation Plane placing blocks in wrong positions

### ISSUE THREAD

**Issue by InterFelix** [Cazadorsniper/PO3#972]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.52
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer

**Description:** AE2 Formation Planes are placing blocks in positions different from the one directly in front of them. I tried to build a wither farm using my usual design with AE2 formation planes, but the formation planes place the blocks randomly in positions next to the one in front of them. Sometimes it will work by chance, but usually it will not.

**Steps to reproduce:** Not sure if it will actually reproduce for you, but build a wither shape with formation planes, connect them up with smart cables and also connect an interface. Supply it with power and configure the formation planes to only place the blocks correct in their position for a wither (top row wither skeleton skulls, middle row soul sand, lowest row in the middle also soul sand). Then put 4 soul sand and 3 wither skeleton skulls into the interface.

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Why not just use woot?

**Comment by GodlyIdea** [comment]
The skulls need something underneath to be placed. So when soul sand isn't placed then the skull gets placed further down.
So you sort of need to delay the skull placement.
In overall its not this mod pack issue - it's AE2 issue.

There is "Wither Builder" machine which does the building perfectly.
Or use woot.
