### ISSUE TITLE
Bricking Quantum Compressor

### ISSUE THREAD

**Issue by TrevorRuppert** [Cazadorsniper/PO3#973]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**3.2.55
**Pack Mode:**Normal
**Singleplayer, Multiplayer, or LAN?:**Singleplayer

**Description:**
When using the quantum compressor and inputting the ultimate catalyst if accidentally placed in the slot for the item to create the singularity (shift clicking the catalyst in) the quantum compressor does not consume the catalyst and instead becomes unusable until broken

**Steps to reproduce:**
Place down a quantum compressor and shift click in an ultimate catalyst. Attempt to compress something the items will just sit in the slot and will not be compressed. Can only be fixed by breaking and replacing the compressor.

**Crash log (use pastebin or issue will be closed):**
Doesnt crash

**Comment by Cazadorsniper** [comment]
That happens quite a bit. There is nothing I can do about it.
