### ISSUE TITLE
Cannot create Lava Infused Obsidian

### ISSUE THREAD

**Issue by johnch18** [Cazadorsniper/PO3#974]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode:**
**Singleplayer, Multiplayer, or LAN?:**
3.2.55
Kappa
Singleplayer

**Description:**
Cannot create Lava Infused Obsidian

**Steps to reproduce:**
1. Place lava bucket inside lava infuser
2. Place obsidian inside lava infuser
https://imgur.com/a/DrgkCBJ

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Try right-clicking lava bucket on the machine.

**Comment by GodlyIdea** [comment]
Make sure it is compressed obsidian (can't really tell from image what you have in there) which is made in Workbench (where you craft the armor stuff).

**Comment by johnch18** [comment]
Dammit, I hate when I overlook simple things like this and embarass myself on the issues page. Thanks guys.
