### ISSUE TITLE
Cost of Creative Chest

### ISSUE THREAD

**Issue by freundlich** [Cazadorsniper/PO3#976]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** LAN

**Description:**
The creative chest needs 8 chaos planks which need 20 chaos ingots each, which in turn need 11 chaos catalysts each. This totals 1760 ultimate singularities. There are 16 singularities that can't be made with EMC. I'm using a combination of 128 mob duplicators and about 70 or 80 harvesters with imaginary time blocks. This is distributed over three different dimensions which are almost at their TPS limits. And still, getting all of this takes way too long, i.e. several weeks of constantly running the server. Either I'm missing something very obvious on how to obtain these resources, or this is just how much time it takes. How about reducing the cost of the creative chest to 1 or 2 chaos planks instead? Or maybe make the chaos plank itself require less chaos ingots? Anyway, I would like this recipe to be cheaper, because at this point it's just a bunch of waiting.

**Comment by Cazadorsniper** [comment]
Nothing will be done about this.

**Comment by ZeBrasa** [comment]
You need to be creative with those. I made the some of the ones that can't be made with EMC with seeds, Mirion I did with some alloy transformers, and the landcraft ones I did with the RFtools dimension. Also, when you get the first block of ultimate ingot just use the wand of animation

**Comment by perpetual-aberrance** [comment]
i agree, but cazador doesn't seem to want to do anything about that. the best option is once you have one chaos plank, and you are mathematically sure you can produce more (at the cost of time and time only), i think it would be OK to cheat the rest in.
