### ISSUE TITLE
generation of a vanilla world

### ISSUE THREAD

**Issue by Mehdi-Ibnlfassi** [Cazadorsniper/PO3#978]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.2.55
**Pack Mode:**

**Singleplayer, Multiplayer, or LAN?:**
Multiplayer
**Description:**
The worlds that the server generates are vanilla worlds. there is no block of a mod.
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
Start the server with forge.
