### ISSUE TITLE
extra utilities 2 transfer nodes and pipes are uncraftable in kappa mode

### ISSUE THREAD

**Issue by maniever** [Cazadorsniper/PO3#979]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:** kappa
**Singleplayer, Multiplayer, or LAN?:** singleplayer

**Description:**
there are recipies that uses it but itself is not craftable
**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by Cazadorsniper** [comment]
They are un-craftable in every mode.
