### ISSUE TITLE
Cloud (Chisel) and Wool Cloth (Extra Planets) have conflicting recipes

### ISSUE THREAD

**Issue by Buudeluu** [Cazadorsniper/PO3#98]
**Pack Version:**
3.0.38
**Description:**
Cloud (Chisel) and Wool Cloth (Extra Planets) have conflicting recipes
**Steps to reproduce:**
Trying to craft Cloud (Chisel) will get you Wool Cloth (Extra Planets)

**Comment by Zapstur** [comment]
Looks like this is caused by the recipe for the Wool Cloth from Extra Planets being "shapeless".  Something simple to fix.
