### ISSUE TITLE
Install on Ubuntu Server

### ISSUE THREAD

**Issue by AbodeRules** [Cazadorsniper/PO3#981]
Hello, i tried to install the server on Ubuntu but it didn't work it gives me error before running

Can you please give me the sh file to run the server?

Thanks

**Comment by Cazadorsniper** [comment]
There is no sh file, you will have to make one yourself.

**Comment by AbodeRules** [comment]
Thanks for your reply,
I tried and made one out of the bat file but it gives me errors

https://pastebin.com/xGiS11vm

**Comment by Cazadorsniper** [comment]
Sadly, I don't know how sh files work so you will have to do some googling.

**Comment by AbodeRules** [comment]
:( I search and find nothing, i guess i have to change my server to windows so i can do that.

Thanks again.
