### ISSUE TITLE
Hunger Bar Problem in Landia Dimension

### ISSUE THREAD

**Issue by Atadele** [Cazadorsniper/PO3#983]
Pack Version: 3.2.54
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?:
Singleplayer

Description:
After getting though most lordcraft, suddenly, hunger bar keeps auto refilling in Landia dimension only

Video:
https://youtu.be/M4iIt0s0EP8

**Comment by Cazadorsniper** [comment]
Have you've checked your passive skills?

**Comment by Atadele** [comment]
the everlasting abilities I don't have saturation. It was only in Landia. I loaded a save from a few hours earlier and trying to see what causes it if it happens again

**Comment by MantiisKnight** [comment]
Feeding (Level 2 water) from Lordcraft regeneratesq food when in water or rain.  I think Landia is always raining, but does not display water.

**Comment by Cazadorsniper** [comment]
Yes, its always raining in Landia.
