### ISSUE TITLE
EnderIO enchanter Crash

### ISSUE THREAD

**Issue by Bolsward1** [Cazadorsniper/PO3#984]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.54 (will test on newest version as soon as we've updated the server.
**Pack Mode:** Kappa
**Singleplayer, Multiplayer, or LAN?:** Multiplayer (it works fine in SP)

**Description:**

Opening the last page of the enderIO enchanter recipes crashes your client.
**Steps to reproduce:**

Open the enderIO enchanter, click the book in the top right to view the recipes then go to the last page (10) it will then crash your game client.

**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/dZ4dFwju

**Comment by Cazadorsniper** [comment]
Did you reproduce the crash on newest version?
