### ISSUE TITLE
Better Questing files reset after server restarts.

### ISSUE THREAD

**Issue by TheKLC** [Cazadorsniper/PO3#985]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
3.1.45
**Pack Mode:**
Default
**Singleplayer, Multiplayer, or LAN?:**
Multiplayer

**Description:**
Whenever our server restarts, the betterquesting files have been reverted to as though they are new.  LifeDatabase.json, NameCache.json, QuestingParties.json, and QuestProgress.json are all overwritten with fresh files (I'd presume QuestDatabase.json as well, but as it doesn't change with gameplay it's hard to know), thereby deleting everyone's progression and making us pause to load the latest backup. Interestingly enough, some of the backups even have "new" files making us go back even further on some occasions. Reading through other similar/same issues, I noted that restoring from backup was the usual go-to fix. With this basically being a daily occurrence for us, I wanted to see if there was something else we could do or if backups are our only option?

**Steps to reproduce:**
Restart Server

**Crash log (use pastebin or issue will be closed):**
No crashlogs or Betterquesting errors found in logs.

**Comment by Cazadorsniper** [comment]
Have you tried updating the pack?

**Comment by TheKLC** [comment]
I did not realize that we were so many versions behind until I started
researching this issue (don't own the server, recent admin). I will work on
getting us to an updated version. Should we just update to the newest
version right away, or should I apply the updates incidentally, version by
version, until I reach the latest?

**Comment by Cazadorsniper** [comment]
Update to newest.
