### ISSUE TITLE
CreativeCore is crashing my pack.

### ISSUE THREAD

**Issue by itsjusttriz** [Cazadorsniper/PO3#986]
Pack version - 3.2.55
Titan mode.

Crashlog - https://pastebin.com/tMHM0haC

Was playing on a server, relaunched the pack due to laptop dying, pack decided to just not launch for me anymore.. tried launching 4 times... no worky ;-;

**Comment by Cazadorsniper** [comment]
Try deleting the creativecore config.

**Comment by itsjusttriz** [comment]
Worked, thanks. :smile:
