### ISSUE TITLE
[AE2:S]: Using CraftingManager fallback: Recipe NOT FOUND, please report.

### ISSUE THREAD

**Issue by Adenser** [Cazadorsniper/PO3#988]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.2.55
**Pack Mode:** Kappa mode 
**Singleplayer, Multiplayer, or LAN?:** multiplayer

**Description:**
Updated pack from 3.2.50 I believe to 3.2.55, after launching server AE2 instantly start spamming with recipe not found
**Steps to reproduce:**
update pack from old version to newest one with something in crafting manager in ae2

**Crash log (use Pastebin or issue will be closed):**
crash: https://pastebin.com/kYkd0nsW
log from the server: It's too big Pastebin so I'm putting it on my own Pastebin https://paste.bombsite.be/raw/hehimutinu.rb

I know server crashes duo to max tick time, but It's because of spam with recipe not found.

**Comment by GodlyIdea** [comment]
It seems to complain about induction cell recipes.
