### ISSUE TITLE
Alloy Transformer

### ISSUE THREAD

**Issue by Cybertick** [Cazadorsniper/PO3#990]
# Use the search function before reporting to see if the issue has been reported before.
Pack Version: 3.2.55
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN? Multiplayer

Description: I feel completely inept. It’s not fun lol

I don’t know if I’m just doing something blatantly wrong, but I have built and destroyed, just to rebuild, the alloy transformer at least 25 times now. I have tried using a matching combo all the way around of every different type of hatch. I’ve tried some different coolers. I tried the modular casings instead of smeltery bricks because all the other machines use casings. To no avail. I don’t know why it doesn’t work. I even followed the in-world guide and no blocks were wrong.

How do I even build?

Steps to reproduce: Attempt to build the alloy transformer

**Comment by Cazadorsniper** [comment]
Some screenshots would help.

**Comment by Cybertick** [comment]
The first 5 pictures are the building process, showing that I complete every layer successfully, all from different angles. I even followed the in-world guide to make sure of it.

The next two are so you can see the hatches and whatnot that I use, all being the max tier all the way around.

The second to last is what I see when I right-click on the controller. It doesn't show me that the setup is even remotely valid. The last is what happens when I cheat in the blueprint itself, it still doesn't change the validity. It just says "missing structure", whatever that means.

Sorry for the overload, just wanted you to have as much info as possible. Also sorry if that's not the best way to upload pictures. Pretty much a straight-up noob at that part.


![Screenshot (50)](https://user-images.githubusercontent.com/63320552/78744238-b0ca7d80-7926-11ea-84a8-242e087fe910.png)

![Screenshot (51)](https://user-images.githubusercontent.com/63320552/78744274-c6d83e00-7926-11ea-88e8-37ac1ffb1a02.png)

![Screenshot (52)](https://user-images.githubusercontent.com/63320552/78744294-d2c40000-7926-11ea-8fa6-ac4d02ea28ae.png)

![Screenshot (53)](https://user-images.githubusercontent.com/63320552/78744307-dc4d6800-7926-11ea-9535-dbe4dd65b1dc.png)

![Screenshot (54)](https://user-images.githubusercontent.com/63320552/78744331-e53e3980-7926-11ea-827c-dc3285f3266e.png)

![Screenshot (55)](https://user-images.githubusercontent.com/63320552/78744355-f129fb80-7926-11ea-921c-4c381ce5f275.png)

![Screenshot (56)](https://user-images.githubusercontent.com/63320552/78744366-fab36380-7926-11ea-8f15-b253877290f0.png)

![Screenshot (57)](https://user-images.githubusercontent.com/63320552/78744376-02730800-7927-11ea-94c0-6dddd405e630.png)

![Screenshot (58)](https://user-images.githubusercontent.com/63320552/78744386-06068f00-7927-11ea-8eca-05bb727a117e.png)

**Comment by Cazadorsniper** [comment]
When you check the structure "recipe" in JEI check to make sure you have the correct blocks.

**Comment by Cybertick** [comment]
I have double and triple checked 10 times. They’re all the same. That’s why I was mentioning I even used the same level hatches all the way around. I don’t know what could possibly be swapped. I’m afraid something is a different item ID but I don’t know what it could be.

**Comment by Cybertick** [comment]
Why would it not recognize the blueprint as a valid structure? Was it disabled in Kappa? Because even if I have a few incorrect blocks, should it recognize the structure and tel me what’s wrong? If so, how close do I have to be for it to tell me that I’m close?

**Comment by Cazadorsniper** [comment]
I'm thinking it maybe the cylindrical blocks that maybe causing it. The blueprint doesn't make it into the structure.

**Comment by GodlyIdea** [comment]
In .51 works fine. Added new instance with version of .55 and doesn't recognize the structure.

**Comment by Cazadorsniper** [comment]
I see, check the inputs/output hatches.

**Comment by GodlyIdea** [comment]
In 3.2.51 works fine. Added new instance with version of 3.2.55 and doesn't recognize the structure.
And it seems the input/output is changed from fluid to item.
And after swapping them it recognizes the structure.

**Comment by Cazadorsniper** [comment]
Because I switched them.

**Comment by GodlyIdea** [comment]
Yea, didn't saw that right away.

**Comment by Cybertick** [comment]
Wait, so should I be using the item inputs and a fluid output? Or item inputs and an item output? Or should they both be fluid?

Also Cazador, do you mean the shaft things in the inside corners is what it doesn’t recognize? If so the blueprint says to use the legacy rotor shafts from extreme reactors. Not sure what they’re supposed to be.

**Comment by Cybertick** [comment]
Can confirm, works with turbine shafts IF you use the ITEM inputs and outputs. Thank you both for the help! The blueprint just needs to be changed if anything!

**Comment by GodlyIdea** [comment]
JEI shows proper items for the machine:
![image](https://user-images.githubusercontent.com/61575892/78810243-c72d1380-79d0-11ea-93cc-370bc873e339.png)
I use that list to get all the items for the modular machines.

**Comment by Cybertick** [comment]
Must be nice lol. All good. It's fixed on my end and works like a dream.

![Screenshot (60)](https://user-images.githubusercontent.com/63320552/78814707-b2328f00-7994-11ea-8931-03ba48d7266a.png)
