### ISSUE TITLE
Problematic Frame on Launch/In Game

### ISSUE THREAD

**Issue by Cybertick** [Cazadorsniper/PO3#993]
Pack Version: 3.2.55
Pack Mode: Kappa
Singleplayer, Multiplayer, or LAN?: Multiplayer

Description: Game will randomly crash without causing too many entities or things like that in the world. I can play fine for 2 or 3 days and then it crashes, sometimes to the point of "blue screen"ing my computer with the windows error "MEMORY_MANAGEMENT". I know that part isn't your realm, but if you have any input it would be greatly appreciated as I have a beefy computer.
Back to the problem. The game will randomly crash for what appears to be no reason, sometimes a couple of times a day, sometimes once every three days. It will occasionally allow me to relaunch it just fine, but I usually have to delete the instance (ATLauncher) and reinstall it. The only thing I bring over is configs and my options as I have play on a server. I don't have crash logs from previous crashes besides today as I mentioned that I just have to delete the instance and for some reason, I haven't decided to keep the logs... I will start now and have no fear, it will happen again soon I'm sure.

I can give any more information you need, I'm not great at these ticket things.

Steps to reproduce: Launch/play the game. It's not always the same "Problematic frame" every crash. I can include more later if needed.

Crash log (use pastebin or issue will be closed):
This is the first one when trying to launch the game after "MEMORY_MANAGEMENT" windows error. This is after uninstall and reinstall of instance:
 https://pastebin.com/26y3Frzn
--------------
This was the second launch two minutes later, with a different problem:
https://pastebin.com/P7SXZTw6

Sorry if this is too much, just really trying to figure out why my strong computer keeps crapping out. Really enjoying the pack so hoping I can work through at least some of this with you.

**Comment by Cazadorsniper** [comment]
ATLuncher?

**Comment by Cybertick** [comment]
Yes sir

**Comment by Cazadorsniper** [comment]
PO3 isn't on ATLauncher though.

**Comment by Cybertick** [comment]
https://pastebin.com/9jmLMkDf

This one happened while using a Draconic Evolution dislocator on a pedestal to teleport from void world to my normal base, regular dimension. Both chunk loaded, nothing new added since last teleport.

**Comment by Cybertick** [comment]
You can add it from the instance tab. I was having java problems on twitch and people said AT Launcher didn't have the same problems. Clearly they were wrong.

**Comment by Cazadorsniper** [comment]
Well the top 2 crashes were of Java, may need to reinstall Java.

**Comment by Cazadorsniper** [comment]
All of them are of Java crashing actually.

**Comment by Cybertick** [comment]
Is there some way to stabilize that or make it more reliable? Because deleting and reinstalling java or the pack over and over gets old :(

**Comment by Cazadorsniper** [comment]
I don't know.

**Comment by Cybertick** [comment]
I submitted a ticket to java over a week ago. Other than that you know of a place I can research this? If not I still really appreciate the help!

**Comment by Cazadorsniper** [comment]
I do not, but it maybe possible that something in your pc maybe failing since this has caused blue screening.

**Comment by Cybertick** [comment]
My HDD is the oldest thing by far. It's about 5 years old or so, slow write speed and whatnot, everything else is compatible and less than a year old. 2070 super, 3200 32 gb ram, i7 9700k. All the goods. 
I'll look to the internet. Again, I really appreciate the help on non-pack related stuff!

**Comment by GodlyIdea** [comment]
Strange errors typical problem I would say is lack of allocated memory. 6GB is minimum but I suggest at least 8GB (As I have that and don't have any issues).
Also allocating too few memory causes slow loading times.

For Java I remember seeing topic that mentioned that development one caused issues.
So sort of check that you don't have that and Java is up to date.

As far as blue screen goes then most cases the issue is bad connection between RAM and motherboard.
Usually helps if you remove the RAM and insert again. (Be aware of warranty stuff)

**Comment by Cybertick** [comment]
I have 12BG allocated out of my 32... lol

But I’ll definitely try the remove and reinsert, it can’t hurt!
I also just yesterday learned that my 3200 ram has only been running at 2133. So I fixed that too. We shall see how it goes! :D
