### ISSUE TITLE
Textures of items added with contenttweaker

### ISSUE THREAD

**Issue by TheUntamed** [Cazadorsniper/PO3#994]
Hi,
I'm creating my own modpack and I wanted to ask if I could use some of the textures you use for items added to your pack with contenttweaker. I really like some of the textures and it would save me some time I otherwise have to spend creating bad textures myself.

**Comment by Cazadorsniper** [comment]
Sure, as long as credit is given.

**Comment by TheUntamed** [comment]
Is mentioning that some of the textures were created by Team Ozone and a link to github or curseforge in the modpack description fine?

**Comment by Cazadorsniper** [comment]
Yes, a link to PO3's curseforge page.
