### ISSUE TITLE
Transfer nodes uncraftable (I know they were meant to be but I want to know why)

### ISSUE THREAD

**Issue by CeddV2** [Cazadorsniper/PO3#996]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:**
**Pack Mode:**
**Singleplayer, Multiplayer, or LAN?:**

**Description:**

**Steps to reproduce:**

**Crash log (use pastebin or issue will be closed):**

**Comment by CeddV2** [comment]
Basically I just want to know why they were removed because in my mind they are essential in the early game. I know I could craft myself some conduits but I love working with transfer nodes/pipes in the early game.

**Comment by Cazadorsniper** [comment]
Lag and crashes.
