### ISSUE TITLE
Can't keep up!

### ISSUE THREAD

**Issue by koczka** [Cazadorsniper/PO3#997]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:*server 3.2.55*
**Pack Mode:*Kappa*
**Singleplayer, Multiplayer, or LAN?:*Multiplayer*

**Description:**
I'm running the pack on a vps with 16g of ram (14g allocated to server) and a Xeon E5-2630 cpu on Ubuntu 19, and as soon as I start up my server it constantly spamming the console with "Can't keep up" warnings.

On the client side I do not feel any bad tick lag, but after a while the server crashes.

**Steps to reproduce:**
Run a dedicated server and start playing.

**Crash log:**
https://pastebin.com/MVa6CE1D

**Comment by Cazadorsniper** [comment]
in server.properties: max-tick-time=-1

**Comment by Cazadorsniper** [comment]
You're still going to see the spam though.

**Comment by jthe111** [comment]
I have been getting this since updating the pack to the latest release. It also creates significant server side lag. The client is fine. On the server I rent it they have stated that there seems to be some java errors as the pack is running that is causing this. They didn't specify which ones though.

**Comment by koczka** [comment]
Update:

I read about the OpenJ9 JVM, and a lot of forum states, that it is great for running minecraft servers, I'm trying it out, and I will share my experience with it a bit later. I'm using this start file, allocating 13gigs max for the minecraft server instance.

https://steinborn.me/posts/tuning-minecraft-openj9/

**Comment by jthe111** [comment]
@koczka Would this work with a rented server?

**Comment by koczka** [comment]
I rent a vps server, just played around a little with this JVM, but it's much worse than the default, the tick lag is horrible, I'm reverting back to the original.

**Comment by koczka** [comment]
> @koczka Would this work with a rented server?

If you only rent a minecraft server instance, then I don't think so, you need access to the OS below your server to do these modifications.

**Comment by koczka** [comment]
Kind of a solution, now I'm using the default JVM that comes with the JDK 8.
I set the max-tick-rate to -1 as Caz suggested, and changed my run script to the one below, and since I've done this the server seems to run fine, I don't feel any kind of tick lag, the client is nice and responsive.

```
java -server -Xms12G -Xmx12G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch  -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=true -Daikars.new.flags=true -jar forge.jar nogui
```

**Comment by koczka** [comment]
Just an interesting fact, after taking down the Immersive Engineering Crusher from my base, my TPS is stabilized, and the can't keep up errors gone away from console.
This might worth to take a look at @Cazadorsniper
