### ISSUE TITLE
Crashed while disabling included texture pack on server

### ISSUE THREAD

**Issue by 314resqi** [Cazadorsniper/PO3#999]
**Pack Version:**
3.2.55
**Pack Mode:**
kappa
**Singleplayer, Multiplayer, or LAN?:**
multiplayer

**Description:**
I was on server and i wanted to disable included texture pack, so i tried to disable it. 
But mc crashed.
**Steps to reproduce:**
esc > options > resource packs > 2nd columm: selected reource packs > click on ozone_resources_3.zip

ozone_resources_3.zip moved from selected to available
click on done 
mc crashed after few minutes
**Crash log (use pastebin or issue will be closed):**
https://pastebin.com/hmnjpLar

**Comment by Cazadorsniper** [comment]
Restart the pack, should be fine. It only crashed because it ran out of memory while reloading all of the textures in the entire pack.
